unpackaged/main/default/objects/clcommon__DAG_Logging__c/clcommon__DAG_Logging__c.object-meta.xml
<CustomObject>
    <label>DAG Logging</label>
    <nameField>
        <displayFormat>DL-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DAG Logging</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/clcommon__DAG_Logging__c/fields/clcommon__Status__c.field-meta.xml
<CustomField>
    <fullName>clcommon__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failure</fullName>
            </value>
            <value>
                <fullName>Initializing</fullName>
            </value>
            <value>
                <fullName>Aborted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/clcommon__Job_Logging__c/clcommon__Job_Logging__c.object-meta.xml
<CustomObject>
    <label>Job Logging</label>
    <nameField>
        <displayFormat>JL-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Loggings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/clcommon__Job_Logging__c/fields/clcommon__DAG_Logging__c.field-meta.xml
<CustomField>
    <fullName>clcommon__DAG_Logging__c</fullName>
    <label>DAG Logging</label>
    <referenceTo>clcommon__DAG_Logging__c</referenceTo>
    <relationshipLabel>Job Loggings</relationshipLabel>
    <relationshipName>Job_Loggings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/clcommon__Job_Logging__c/fields/clcommon__Status__c.field-meta.xml
<CustomField>
    <fullName>clcommon__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Aborted</fullName>
            </value>
            <value>
                <fullName>Failure</fullName>
            </value>
            <value>
                <fullName>Initializing</fullName>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Skipped</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/MW_logCreationOnClCommonJobLoggingTest.cls
@isTest
public class MW_logCreationOnClCommonJobLoggingTest {
	@isTest
	static void insertInfo() {
		// Test data setup
		clcommon__DAG_Logging__c dagLogging = new clcommon__DAG_Logging__c(
			clcommon__Status__c = 'Success'
		);
		insert dagLogging;

		clcommon__Job_Logging__c log = new clcommon__Job_Logging__c(
			clcommon__Status__c = 'Success',
			clcommon__DAG_Logging__c = dagLogging.Id
		);

		// Perform test
		Test.startTest();
		Database.SaveResult result = Database.insert(log, false);
		Test.stopTest();
		// Verify
		System.assert(result.isSuccess(), 'inserted');
		System.assert(result.getErrors().size() == 0, 'no errors');
	}

	@isTest
	static void insertError() {
		// Test data setup
		clcommon__DAG_Logging__c dagLogging = new clcommon__DAG_Logging__c(
			clcommon__Status__c = 'Success'
		);
		insert dagLogging;

		clcommon__Job_Logging__c log = new clcommon__Job_Logging__c(
			clcommon__Status__c = 'Success',
			clcommon__DAG_Logging__c = dagLogging.Id
		);

		// Perform test
		Test.startTest();
		Database.SaveResult result = Database.insert(log, false);

		Test.stopTest();
		// Verify
		System.assert(result.isSuccess(), 'inserted');
		System.assert(result.getErrors().size() == 0, 'no errors');
	}

	@isTest
	static void insertWarning() {
		// Test data setup
		clcommon__DAG_Logging__c dagLogging = new clcommon__DAG_Logging__c(
			clcommon__Status__c = 'Success'
		);
		insert dagLogging;

		clcommon__Job_Logging__c log = new clcommon__Job_Logging__c(
			clcommon__Status__c = 'Success',
			clcommon__DAG_Logging__c = dagLogging.Id
		);

		// Perform test
		Test.startTest();
		Database.SaveResult result = Database.insert(log, false);

		Test.stopTest();
		// Verify
		System.assert(result.isSuccess(), 'inserted');
		System.assert(result.getErrors().size() == 0, 'no errors');
	}
}