unpackaged/main/default/objects/clcommon__DAG_Logging__c/clcommon__DAG_Logging__c.object-meta.xml
<CustomObject>
    <label>DAG Logging</label>
    <nameField>
        <displayFormat>DL-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DAG Logging</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/clcommon__DAG_Logging__c/fields/clcommon__Finish_Time__c.field-meta.xml
<CustomField>
    <fullName>clcommon__Finish_Time__c</fullName>
    <label>Finish Time</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/clcommon__DAG_Logging__c/fields/clcommon__Start_Time__c.field-meta.xml
<CustomField>
    <fullName>clcommon__Start_Time__c</fullName>
    <label>Start Time</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/clcommon__DAG_Logging__c/fields/clcommon__Status__c.field-meta.xml
<CustomField>
    <fullName>clcommon__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failure</fullName>
            </value>
            <value>
                <fullName>Initializing</fullName>
            </value>
            <value>
                <fullName>Aborted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/NightlyDynamicAlertJob.cls
global with sharing class NightlyDynamicAlertJob extends clcommon.DynamicJob implements Database.AllowsCallouts,Database.RaisesPlatformEvents{

    private static String JOB_NAME = 'NightlyDynamicAlertJob'; 

    global NightlyDynamicAlertJob() {
        super(JOB_NAME, null);
    }
    global NightlyDynamicAlertJob(String query) {
        super(JOB_NAME, query);
    }

    global override void doInitialize() {} 
    
    global override String getRuntimeQuery() {   
        mfiflexUtil.ExecutionContext ec = mfiflexUtil.ExecutionContext.getExecContext();
        mfiflexUtil.ObjectCache dagLog = ec.getObject('clcommon__DAG_Logging__c');
        if(dagLog != null) {
            ec.deleteObject('clcommon__DAG_Logging__c');
        }
        dagLog = ec.createObject('clcommon__DAG_Logging__c',
                                    'clcommon__DAG_Logging__c',
                                    '');
        dagLog.addFields('id,name,clcommon__Status__c,clcommon__Start_Time__c,clcommon__Finish_Time__c'); 
        dagLog.setWhereClause('CreatedDate = TODAY');
        dagLog.setOrderClause('CreatedDate DESC ');
        dagLog.setLimitClause('1');
        dagLog.buildQuery(); 
        return dagLog.getQuery();
   } 
     
    global override void doexecute(SchedulableContext sc) {
          
    }
     
    global override void doexecute(Database.BatchableContext bc, List<sObject> scope) {}
  
    global override void doStart(Database.BatchableContext bc) {}
   
    global override void dofinish(Database.BatchableContext bc) {
        //get TODAY DAG logging
        List<clcommon__DAG_Logging__c> dagLog = Database.query(getRuntimeQuery());

        if(!test.isRunningTest()){

            NightlyDynamicAlertHandler.sendSlackCallout(dagLog);

        }  
    }  
}