unpackaged/main/default/objects/clcommon__Batch_Logging__c/clcommon__Batch_Logging__c.object-meta.xml
<CustomObject>
    <label>Batch Logging</label>
    <nameField>
        <displayFormat>BL-{0000}</displayFormat>
        <label>Batch Logging Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batch Loggings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/clcommon__Batch_Logging__c/fields/clcommon__Status__c.field-meta.xml
<CustomField>
    <fullName>clcommon__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failure</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/clcommon__Batch_Logging__c/fields/clcommon__Thread_Logging__c.field-meta.xml
<CustomField>
    <fullName>clcommon__Thread_Logging__c</fullName>
    <label>Thread Logging</label>
    <referenceTo>clcommon__Thread_Logging__c</referenceTo>
    <relationshipLabel>Batch Loggings</relationshipLabel>
    <relationshipName>Batch_Loggings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/clcommon__DAG_Logging__c/clcommon__DAG_Logging__c.object-meta.xml
<CustomObject>
    <label>DAG Logging</label>
    <nameField>
        <displayFormat>DL-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DAG Logging</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/clcommon__DAG_Logging__c/fields/clcommon__Start_Time__c.field-meta.xml
<CustomField>
    <fullName>clcommon__Start_Time__c</fullName>
    <label>Start Time</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/clcommon__DAG_Logging__c/fields/clcommon__Status__c.field-meta.xml
<CustomField>
    <fullName>clcommon__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failure</fullName>
            </value>
            <value>
                <fullName>Initializing</fullName>
            </value>
            <value>
                <fullName>Aborted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/clcommon__Job_Logging__c/clcommon__Job_Logging__c.object-meta.xml
<CustomObject>
    <label>Job Logging</label>
    <nameField>
        <displayFormat>JL-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Loggings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/clcommon__Job_Logging__c/fields/clcommon__DAG_Logging__c.field-meta.xml
<CustomField>
    <fullName>clcommon__DAG_Logging__c</fullName>
    <label>DAG Logging</label>
    <referenceTo>clcommon__DAG_Logging__c</referenceTo>
    <relationshipLabel>Job Loggings</relationshipLabel>
    <relationshipName>Job_Loggings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/clcommon__Job_Logging__c/fields/clcommon__Label__c.field-meta.xml
<CustomField>
    <fullName>clcommon__Label__c</fullName>
    <label>Label</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/clcommon__Job_Logging__c/fields/clcommon__Status__c.field-meta.xml
<CustomField>
    <fullName>clcommon__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Aborted</fullName>
            </value>
            <value>
                <fullName>Failure</fullName>
            </value>
            <value>
                <fullName>Initializing</fullName>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Skipped</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/clcommon__Thread_Logging__c/clcommon__Thread_Logging__c.object-meta.xml
<CustomObject>
    <label>Thread Logging</label>
    <nameField>
        <displayFormat>TL-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Thread Loggings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/clcommon__Thread_Logging__c/fields/clcommon__Job_Logging__c.field-meta.xml
<CustomField>
    <fullName>clcommon__Job_Logging__c</fullName>
    <label>Job Logging</label>
    <referenceTo>clcommon__Job_Logging__c</referenceTo>
    <relationshipLabel>Thread Loggings</relationshipLabel>
    <relationshipName>Thread_Loggings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/clcommon__Thread_Logging__c/fields/clcommon__Status__c.field-meta.xml
<CustomField>
    <fullName>clcommon__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Initializing</fullName>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failure</fullName>
            </value>
            <value>
                <fullName>Aborted</fullName>
            </value>
            <value>
                <fullName>Skipped</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/MW_Settings__c/MW_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>MW_Settings</label>
</CustomObject>

force-app/main/default/objects/MW_Settings__c/fields/Slack_mentions_for_Nacha_alert__c.field-meta.xml
<CustomField>
    <fullName>Slack_mentions_for_Nacha_alert__c</fullName>
    <label>Slack mentions for Nacha alert</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/NightlyDynamicAlertJobTest.cls
@isTest
public with sharing class NightlyDynamicAlertJobTest {

    final static String SUCCESS = 'Success';
    final static String FAILURE = 'Failure';

    @testSetup
    private static void testSetup() {
        MW_Settings__c setting = MW_GlobalTestUtility.GetSettings();
        setting.Slack_mentions_for_Nacha_alert__c = 'test@user.com';
        insert setting;
    }

	static void createJobLogging(String jobStatus, String jobName) {
		clcommon__DAG_Logging__c dagLogging = new clcommon__DAG_Logging__c(
			clcommon__Status__c = jobStatus,
			clcommon__Start_Time__c = System.now()
		);
		insert dagLogging;

		clcommon__Job_Logging__c jobLogging = new clcommon__Job_Logging__c(
			clcommon__Status__c = SUCCESS,
			clcommon__DAG_Logging__c = dagLogging.Id,
			clcommon__Label__c = jobName
		);
		insert jobLogging;

		clcommon__Thread_Logging__c threadLogging = new clcommon__Thread_Logging__c(
			clcommon__Status__c = jobStatus,
			clcommon__Job_Logging__c = jobLogging.Id
		);
		insert threadLogging;

		clcommon__Batch_Logging__c log = new clcommon__Batch_Logging__c();
		log.clcommon__Status__c = jobStatus;
		log.clcommon__Thread_Logging__c = threadLogging.Id;

		Database.SaveResult result = Database.insert(log, false);

		System.assert(result.isSuccess(), 'inserted');
		System.assert(result.getErrors().size() == 0, 'no errors');
	}

    @isTest
    static void jobSuccess() {

		createJobLogging(SUCCESS, '');
		
        Test.startTest();

        Test.setMock(HttpCalloutMock.class, new HttpSlackCalloutMock());

        NightlyDynamicAlertJob job = new NightlyDynamicAlertJob();
        String jobID = Database.executeBatch(job,1);

        List<clcommon__DAG_Logging__c> dagLogList = new List<clcommon__DAG_Logging__c>();

		clcommon__DAG_Logging__c dagLogging = [Select Id from clcommon__DAG_Logging__c LIMIT 1];

        dagLogList.add(dagLogging);
		NightlyDynamicAlertHandler handler = new NightlyDynamicAlertHandler(dagLogList[0].Id);
        System.enqueueJob(handler);
        Test.StopTest();
		
        Assert.isTrue(jobID != null,'job runs 1');

    }

    @isTest
    static void jobFailure() {

		createJobLogging(FAILURE, 'StartOfDayDynamicJob');
        
        Test.startTest();

        Test.setMock(HttpCalloutMock.class, new HttpSlackCalloutMock());

        NightlyDynamicAlertJob job = new NightlyDynamicAlertJob();
        String jobID = Database.executeBatch(job);

        List<clcommon__DAG_Logging__c> dagLogList = new List<clcommon__DAG_Logging__c>();

		clcommon__DAG_Logging__c dagLogging = [Select Id from clcommon__DAG_Logging__c LIMIT 1];
		
        dagLogList.add(dagLogging);
		NightlyDynamicAlertHandler handler = new NightlyDynamicAlertHandler(dagLogList[0].Id);
        System.enqueueJob(handler);

        Test.StopTest();

		Assert.isTrue(jobID != null,'job runs 2');

    }


}