force-app/main/default/objects/BoxUrl__c/BoxUrl__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>BoxUrl</label>
</CustomObject>

force-app/main/default/objects/BoxUrl__c/fields/Boxurl__c.field-meta.xml
<CustomField>
    <fullName>Boxurl__c</fullName>
    <label>Boxurl</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/genesis__Application_Document_Category__c/genesis__Application_Document_Category__c.object-meta.xml
<CustomObject>
    <label>Application Document Category</label>
    <nameField>
        <label>Application Document Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application Document Category</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/genesis__Application_Document_Category__c/fields/Box_URl__c.field-meta.xml
<CustomField>
    <fullName>Box_URl__c</fullName>
    <label>Box URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/genesis__Application_Document_Category__c/fields/Doc_Code_FF__c.field-meta.xml
<CustomField>
    <fullName>Doc_Code_FF__c</fullName>
    <formula>IF( genesis__Parent_Application_Document_Category__r.Name == &apos;ESign Documents&apos;, 
IF( Name == &apos;3rd Party Membership&apos; , IF( Investor_Code__c == &apos;ACU&apos;, &apos;authoritative_ffa_app&apos;, IF(Investor_Code__c == &apos;TCU&apos;, &apos;authoritative_ffa_app&apos;, IF(Investor_Code__c == &apos;FTCU&apos;, &apos;authoritative_ffa_app&apos;, &apos;authoritative_ffa_app&apos;) ) ) , 
IF(Name == &apos;CU Membership&apos;, IF(Investor_Code__c == &apos;ACU&apos;, &apos;authoritative_alliant_agreement&apos;, IF(Investor_Code__c == &apos;TCU&apos;, &apos;authoritative_tcu_member_agreement&apos;, IF(Investor_Code__c == &apos;FTCU&apos;, &apos;ftcu_member_agreement&apos;, &apos;authoritative_member_agreement&apos;) ) ) , 
IF(Name == &apos;Payoff Promissory Note&apos;, IF(Investor_Code__c == &apos;ACU&apos;, &apos;authoritative_promissory_note &apos;, IF(Investor_Code__c == &apos;TCU&apos;, &apos;authoritative_promissory_note&apos;, IF(Investor_Code__c == &apos;FTCU&apos;, &apos;promissory_note&apos;, &apos;authoritative_promissory_note&apos;) ) ) , 
IF(Name == &apos;Payoff Member Agreement&apos;, IF(Investor_Code__c == &apos;ACU&apos;, &apos;authoritative_borrower_agreement &apos;, IF(Investor_Code__c == &apos;TCU&apos;, &apos;authoritative_borrower_agreement&apos;, IF(Investor_Code__c == &apos;FTCU&apos;, &apos;borrower_agreement&apos;, &apos;authoritative_borrower_agreement&apos;) ) ) , 
IF(Name == &apos;Credit Services Contract&apos;, IF(Investor_Code__c == &apos;ACU&apos;, &apos;authoritative_cso_agreement &apos;, IF(Investor_Code__c == &apos;TCU&apos;, &apos;authoritative_cso_agreement&apos;, IF(Investor_Code__c == &apos;FTCU&apos;, &apos;cso_agreement&apos;, &apos;authoritative_cso_agreement&apos;) ) ) ,
IF(Name == &apos;Alliant ACH&apos;,  IF(Investor_Code__c == &apos;ACU&apos;, &apos;authoritative_alliant_ach&apos;,  IF(Investor_Code__c == &apos;TCU&apos;, &apos;&apos;,  IF(Investor_Code__c == &apos;FTCU&apos;, &apos;&apos;, Doc_Code_as_for_Investors__c ) ) ) , Doc_Code_as_for_Investors__c ) ) ) ) ) ) , 
Doc_Code_as_for_Investors__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Doc_Code_FF</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/genesis__Application_Document_Category__c/fields/Doc_URL__c.field-meta.xml
<CustomField>
    <fullName>Doc_URL__c</fullName>
    <label>Doc_URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/genesis__Application_Document_Category__c/fields/genesis__Active__c.field-meta.xml
<CustomField>
    <fullName>genesis__Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/genesis__Application_Document_Category__c/fields/genesis__Application__c.field-meta.xml
<CustomField>
    <fullName>genesis__Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>genesis__Applications__c</referenceTo>
    <relationshipLabel>Application Document Category</relationshipLabel>
    <relationshipName>Application_Document_Category</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/genesis__Application_Document_Category__c/fields/genesis__Status__c.field-meta.xml
<CustomField>
    <fullName>genesis__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>OPEN</fullName>
                <default>true</default>
                <label>OPEN</label>
            </value>
            <value>
                <fullName>SUBMITTED</fullName>
            </value>
            <value>
                <fullName>CLEARED</fullName>
            </value>
            <value>
                <fullName>REJECTED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/genesis__Application_Document_Category__c/fields/Lead_Id__c.field-meta.xml
<CustomField>
    <fullName>Lead_Id__c</fullName>
    <formula>genesis__Application__r.Lead_ID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Lead Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/genesis__Applications__c/genesis__Applications__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{0000000000}</displayFormat>
        <label>Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/genesis__Applications__c/fields/genesis__Status__c.field-meta.xml
<CustomField>
    <fullName>genesis__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>APPROVED - APPROVED</fullName>
            </value>
            <value>
                <fullName>APPROVED - CONVERTED TO CONTRACT</fullName>
            </value>
            <value>
                <fullName>APPROVED - DOCUMENT CHECK</fullName>
            </value>
            <value>
                <fullName>NEW - CREDIT PULLED</fullName>
            </value>
            <value>
                <fullName>NEW - ENTERED</fullName>
                <default>true</default>
                <label>NEW - ENTERED</label>
            </value>
            <value>
                <fullName>NEW - IN CREDIT CHECK</fullName>
            </value>
            <value>
                <fullName>NEW - IN REVIEW</fullName>
            </value>
            <value>
                <fullName>NEW - PRICING GENERATED</fullName>
            </value>
            <value>
                <fullName>NEW - SCORECARD GENERATED</fullName>
            </value>
            <value>
                <fullName>NEW - CHECKLIST GENERATED</fullName>
            </value>
            <value>
                <fullName>NEW - VEHICLE VALUATION REQUIRED</fullName>
            </value>
            <value>
                <fullName>REJECTED</fullName>
            </value>
            <value>
                <fullName>PULL CREDIT</fullName>
            </value>
            <value>
                <fullName>Default Documents</fullName>
            </value>
            <value>
                <fullName>offer_accepted</fullName>
            </value>
            <value>
                <fullName>offer_shown</fullName>
            </value>
            <value>
                <fullName>kba_success</fullName>
            </value>
            <value>
                <fullName>kba_fail</fullName>
            </value>
            <value>
                <fullName>agent_document_verification_pending</fullName>
            </value>
            <value>
                <fullName>agent_verification_pending</fullName>
            </value>
            <value>
                <fullName>agent_verified</fullName>
            </value>
            <value>
                <fullName>docusign_loan_docs_sent</fullName>
            </value>
            <value>
                <fullName>docusign_loan_docs_complete</fullName>
            </value>
            <value>
                <fullName>pre_funding</fullName>
            </value>
            <value>
                <fullName>Approved for funding</fullName>
            </value>
            <value>
                <fullName>funded</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Stacker_Check_Passed</fullName>
            </value>
            <value>
                <fullName>Redecision_Required</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/genesis__Applications__c/fields/Lead_ID__c.field-meta.xml
<CustomField>
    <fullName>Lead_ID__c</fullName>
    <description>This is the LEAD GUID received from FE</description>
    <externalId>true</externalId>
    <label>Lead ID</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Origination_Documents__c/Origination_Documents__c.object-meta.xml
<CustomObject>
    <label>Origination Documents</label>
    <nameField>
        <label>Or Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Origination Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Origination_Documents__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <label>Application</label>
    <referenceTo>genesis__Applications__c</referenceTo>
    <relationshipLabel>Origination Documents</relationshipLabel>
    <relationshipName>Origination_Documents</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Origination_Documents__c/fields/BoxUrl__c.field-meta.xml
<CustomField>
    <fullName>BoxUrl__c</fullName>
    <label>BoxUrl</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Origination_Documents__c/fields/Code_FF__c.field-meta.xml
<CustomField>
    <fullName>Code_FF__c</fullName>
    <label>Code FF</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Origination_Documents__c/fields/Lead_Id__c.field-meta.xml
<CustomField>
    <fullName>Lead_Id__c</fullName>
    <formula>Application__r.Lead_ID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Lead Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/WSApplicationDocuments.cls
@RestResource(urlMapping='/Application/Documents/getForDelivery')
global with sharing class WSApplicationDocuments {

	@HttpGet
	global static void getDocuments() {
		RestRequest req = RestContext.request;
		RestResponse res = RestContext.response;
		try {
			String leadId = req.params.get('lead_id');
			if (String.isBlank(leadId)) {
				res.statusCode = 400;
				res.responseBody = Blob.valueOf('lead_id is required');
				return;
			}

			List<genesis__Application_Document_Category__c> documents = [select Name, Doc_Code_FF__c, Box_URl__c, Doc_URL__c
			                                                             from genesis__Application_Document_Category__c
			                                                             where IsDeleted = FALSE and genesis__Active__c = TRUE and genesis__Status__c = 'CLEARED' and genesis__Application__r.Lead_ID__c = :leadId];

			Map<String, List<String>> docs = new Map<String, List<String>>();
			for (genesis__Application_Document_Category__c document : documents) {
				String code = document.Doc_Code_FF__c;
				String docUrl = String.isBlank(document.Box_URl__c) ? document.Doc_URL__c : document.Box_URl__c;
				if (String.isNotBlank(code) && String.isNotBlank(docUrl)) {
					List<String> items = docs.get(code);
					if (items == null) {
						items = new List<String>();
						docs.put(code, items);
					}
					items.add(docUrl);
				}
			}

			List<Origination_Documents__c> oDocuments = [select id, Code_FF__c, BoxUrl__c from Origination_Documents__c
			                                             where Application__r.Lead_ID__c = :leadId];
			for (Origination_Documents__c oDocument : oDocuments) {
				String code = oDocument.Code_FF__c;
				String boxUrl = oDocument.BoxUrl__c;
				if (String.isNotBlank(code) && String.isNotBlank(boxUrl)) {
					List<String> items = docs.get(code);
					if (items == null) {
						items = new List<String>();
						docs.put(code, items);
					}
					items.add(boxUrl);
				}
			}

			res.statusCode = 200;
			res.responseBody = Blob.valueOf(JSON.serialize(docs));
		}
		catch (Exception e) {
			res.statusCode = 500;
			res.responseBody = Blob.valueOf(e.getMessage());
		}
	}
}