force-app/main/default/objects/BoxUrl__c/BoxUrl__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>BoxUrl</label>
</CustomObject>

force-app/main/default/objects/BoxUrl__c/fields/Boxurl__c.field-meta.xml
<CustomField>
    <fullName>Boxurl__c</fullName>
    <label>Boxurl</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/clcommon__Party_Type__c/clcommon__Party_Type__c.object-meta.xml
<CustomObject>
    <label>Party Type</label>
    <nameField>
        <label>Party Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Party Type</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/genesis__Application_Document_Category__c/genesis__Application_Document_Category__c.object-meta.xml
<CustomObject>
    <label>Application Document Category</label>
    <nameField>
        <label>Application Document Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application Document Category</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/genesis__Application_Document_Category__c/fields/genesis__Document_Category__c.field-meta.xml
<CustomField>
    <fullName>genesis__Document_Category__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Document Category</label>
    <referenceTo>genesis__Document_Category__c</referenceTo>
    <relationshipLabel>Application Document Category</relationshipLabel>
    <relationshipName>Application_Document_Category</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/genesis__Applications__c/genesis__Applications__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{0000000000}</displayFormat>
        <label>Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/genesis__Document_Category__c/genesis__Document_Category__c.object-meta.xml
<CustomObject>
    <label>Document Category</label>
    <nameField>
        <displayFormat>DC-{00000000}</displayFormat>
        <label>Document Category Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Document Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/genesis__Document_Category__c/fields/Code_FF__c.field-meta.xml
<CustomField>
    <fullName>Code_FF__c</fullName>
    <label>Code_FF</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Origination_Documents__c/Origination_Documents__c.object-meta.xml
<CustomObject>
    <label>Origination Documents</label>
    <nameField>
        <label>Or Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Origination Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Origination_Documents__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <label>Application</label>
    <referenceTo>genesis__Applications__c</referenceTo>
    <relationshipLabel>Origination Documents</relationshipLabel>
    <relationshipName>Origination_Documents</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Origination_Documents__c/fields/BoxUrl__c.field-meta.xml
<CustomField>
    <fullName>BoxUrl__c</fullName>
    <label>BoxUrl</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Origination_Documents__c/fields/Code_FF__c.field-meta.xml
<CustomField>
    <fullName>Code_FF__c</fullName>
    <label>Code FF</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Origination_Documents__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>preciseid</fullName>
            </value>
            <value>
                <fullName>talx</fullName>
            </value>
            <value>
                <fullName>linked_acct</fullName>
            </value>
            <value>
                <fullName>cbr</fullName>
            </value>
            <value>
                <fullName>credit_authorization</fullName>
            </value>
            <value>
                <fullName>borrower_bank_agreement</fullName>
            </value>
            <value>
                <fullName>payoff_privacy_policy</fullName>
            </value>
            <value>
                <fullName>privacy_notice</fullName>
            </value>
            <value>
                <fullName>terms_of_use</fullName>
            </value>
            <value>
                <fullName>autopay_authorization</fullName>
            </value>
            <value>
                <fullName>eca</fullName>
            </value>
            <value>
                <fullName>talx_hr</fullName>
            </value>
            <value>
                <fullName>linked_acct_hr</fullName>
            </value>
            <value>
                <fullName>bureau_report_hr</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/WSApplicationDocumentsTest.cls
@isTest
private class WSApplicationDocumentsTest {

    static testMethod void testGetDocuments() {
        String leadId = '9ffffff9-9fff-f999-ff99-9f9f9f9f9f9f';
    	String boxUrl = 'https://test.app.box.com/file/00000000000';
    	
        Account acct = TestDataFactory.createTestAccount();
        insert acct;
        
        Account inv = TestDataFactory.createTestInvestor();
        insert inv;
        
        genesis__Applications__c application = TestDataFactory.createTestApplication(acct.Id, inv.Id, leadId, 
        	Date.today().addDays(2), 'Approved for funding');
        insert application;
           
        clcommon__Party_Type__c partyType = TestDataFactory.createTestPartyType('BORROWER');
        insert partyType;
        
        genesis__Document_Category__c docCat = TestDataFactory.createTestDocumentCategory(partyType.Id, 'til');
        insert docCat;
        
        genesis__Application_Document_Category__c appDocCat = TestDataFactory.createTestApplicationDocumentCategory('TIL Document', 
        	application.Id, docCat.Id, boxUrl, 'CLEARED');
        insert appDocCat;
        
        List<Origination_Documents__c> documents = new List<Origination_Documents__c>();   
        for(Origination_Documents__c document: [select id, Code_FF__c, Application__c, type__c 
        										from Origination_Documents__c 
        										where Application__c = :application.Id and BoxUrl__c = null]) {
		   	document.BoxUrl__c = boxUrl;
		   	documents.add(document);
		}
		update documents;
        
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        
        req.requestURI = '/services/apexrest/Application/Documents/getForDelivery';
        req.addParameter('lead_id', leadId);
       
        req.httpMethod = 'GET';
        RestContext.request = req;
        RestContext.response = res;
        
        Test.startTest();
        WSApplicationDocuments.getDocuments();
        Test.stopTest();
        
        Map<String, List<String>> jsonRes = (Map<String, List<String>>) JSON.deserialize(res.responseBody.toString(), Map<String, List<String>>.class);
        
        System.assertEquals(boxUrl, jsonRes.get('preciseid').get(0));
        System.assertEquals(boxUrl, jsonRes.get('terms_of_use').get(0));
        System.assertEquals(boxUrl, jsonRes.get('eca').get(0));
        System.assertEquals(boxUrl, jsonRes.get('payoff_privacy_policy').get(0));
        System.assertEquals(boxUrl, jsonRes.get('credit_authorization').get(0));
        System.assertEquals(boxUrl, jsonRes.get('privacy_notice').get(0));
        System.assertEquals(boxUrl, jsonRes.get('til').get(0));
    }
    
    static testMethod void testGetDocumentsNoLeadId() {
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        
        req.requestURI = '/services/apexrest/Application/Documents/getForDelivery';
        
        req.httpMethod = 'GET';
        RestContext.request = req;
        RestContext.response = res;
        
        Test.startTest();
        WSApplicationDocuments.getDocuments();
        Test.stopTest();
        
        System.assertEquals(400, res.statusCode);
        System.assertEquals('lead_id is required', res.responseBody.toString());
    }
}