unpackaged/main/default/objects/clcommon__CL_Product__c/clcommon__CL_Product__c.object-meta.xml
<CustomObject>
    <label>CL Product</label>
    <nameField>
        <displayFormat>PRO-{00000000}</displayFormat>
        <label>CL Product Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CL Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/clcommon__CL_Product__c/fields/clcommon__Product_Name__c.field-meta.xml
<CustomField>
    <fullName>clcommon__Product_Name__c</fullName>
    <label>Product Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/genesis__Applications__c/genesis__Applications__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{0000000000}</displayFormat>
        <label>Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/genesis__Applications__c/fields/agentVerificationPendingFlag__c.field-meta.xml
<CustomField>
    <fullName>agentVerificationPendingFlag__c</fullName>
    <defaultValue>false</defaultValue>
    <label>agentVerificationPendingFlag</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/genesis__Applications__c/fields/BoxFolderID__c.field-meta.xml
<CustomField>
    <fullName>BoxFolderID__c</fullName>
    <label>BoxFolderID</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/genesis__Applications__c/fields/custom_APR_for_not_rounding__c.field-meta.xml
<CustomField>
    <fullName>custom_APR_for_not_rounding__c</fullName>
    <label>custom_APR_for_not_rounding</label>
    <precision>18</precision>
    <scale>8</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/objects/genesis__Applications__c/fields/Employment_Status__c.field-meta.xml
<CustomField>
    <fullName>Employment_Status__c</fullName>
    <label>Employment Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Full Time</fullName>
            </value>
            <value>
                <fullName>Part Time</fullName>
            </value>
            <value>
                <fullName>Retired</fullName>
            </value>
            <value>
                <fullName>Self Employed</fullName>
            </value>
            <value>
                <fullName>Contract</fullName>
            </value>
            <value>
                <fullName>Seasonal</fullName>
            </value>
            <value>
                <fullName>Investment</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/genesis__Applications__c/fields/genesis__APR__c.field-meta.xml
<CustomField>
    <fullName>genesis__APR__c</fullName>
    <description>Annual Percentage Rate</description>
    <label>APR</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/objects/genesis__Applications__c/fields/genesis__CL_Product__c.field-meta.xml
<CustomField>
    <fullName>genesis__CL_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CL Product</label>
    <referenceTo>clcommon__CL_Product__c</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/genesis__Applications__c/fields/genesis__Status__c.field-meta.xml
<CustomField>
    <fullName>genesis__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>APPROVED - APPROVED</fullName>
            </value>
            <value>
                <fullName>APPROVED - CONVERTED TO CONTRACT</fullName>
            </value>
            <value>
                <fullName>APPROVED - DOCUMENT CHECK</fullName>
            </value>
            <value>
                <fullName>NEW - CREDIT PULLED</fullName>
            </value>
            <value>
                <fullName>NEW - ENTERED</fullName>
                <default>true</default>
                <label>NEW - ENTERED</label>
            </value>
            <value>
                <fullName>NEW - IN CREDIT CHECK</fullName>
            </value>
            <value>
                <fullName>NEW - IN REVIEW</fullName>
            </value>
            <value>
                <fullName>NEW - PRICING GENERATED</fullName>
            </value>
            <value>
                <fullName>NEW - SCORECARD GENERATED</fullName>
            </value>
            <value>
                <fullName>NEW - CHECKLIST GENERATED</fullName>
            </value>
            <value>
                <fullName>NEW - VEHICLE VALUATION REQUIRED</fullName>
            </value>
            <value>
                <fullName>REJECTED</fullName>
            </value>
            <value>
                <fullName>PULL CREDIT</fullName>
            </value>
            <value>
                <fullName>Default Documents</fullName>
            </value>
            <value>
                <fullName>offer_accepted</fullName>
            </value>
            <value>
                <fullName>offer_shown</fullName>
            </value>
            <value>
                <fullName>kba_success</fullName>
            </value>
            <value>
                <fullName>kba_fail</fullName>
            </value>
            <value>
                <fullName>agent_document_verification_pending</fullName>
            </value>
            <value>
                <fullName>agent_verification_pending</fullName>
            </value>
            <value>
                <fullName>agent_verified</fullName>
            </value>
            <value>
                <fullName>docusign_loan_docs_sent</fullName>
            </value>
            <value>
                <fullName>docusign_loan_docs_complete</fullName>
            </value>
            <value>
                <fullName>pre_funding</fullName>
            </value>
            <value>
                <fullName>Approved for funding</fullName>
            </value>
            <value>
                <fullName>funded</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Stacker_Check_Passed</fullName>
            </value>
            <value>
                <fullName>Redecision_Required</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Self Employed Documents</fullName>
            </value>
            <value>
                <fullName>Decline_Manual_Review</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/genesis__Applications__c/fields/isSelfEmployed__c.field-meta.xml
<CustomField>
    <fullName>isSelfEmployed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isSelfEmployed</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/genesis__Applications__c/fields/readyforverificationQueueFlag__c.field-meta.xml
<CustomField>
    <fullName>readyforverificationQueueFlag__c</fullName>
    <defaultValue>false</defaultValue>
    <label>readyforverificationQueueFlag</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/genesis__Applications__c/fields/Required_Docs_Count__c.field-meta.xml
<CustomField>
    <fullName>Required_Docs_Count__c</fullName>
    <label>Required Docs Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/MCCallout__c/MCCallout__c.object-meta.xml
<CustomObject>
    <label>MCCallout</label>
    <nameField>
        <label>MCCallout Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MCCallouts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/MCCallout__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>genesis__Applications__c</referenceTo>
    <relationshipLabel>MCCallouts</relationshipLabel>
    <relationshipName>MCCallouts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/MCCallout__c/fields/Job_ID__c.field-meta.xml
<CustomField>
    <fullName>Job_ID__c</fullName>
    <label>Job ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/MCCallout__c/fields/Send_on__c.field-meta.xml
<CustomField>
    <fullName>Send_on__c</fullName>
    <label>Send on</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/MCCallout__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Queued</fullName>
            </value>
            <value>
                <fullName>Pass</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/MW_Settings__c/MW_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>MW_Settings</label>
</CustomObject>

unpackaged/main/default/objects/MW_Settings__c/fields/BOXRootFolder__c.field-meta.xml
<CustomField>
    <fullName>BOXRootFolder__c</fullName>
    <label>BOXRootFolder</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/MW_ApplicationService.cls
public class MW_ApplicationService {

    public static void postDealRoomStructure(List< genesis__Applications__c > apps, Map<Id, genesis__Applications__c> oldMap){

        List<String> appList                 = new List<String>();
        List<MCCallout__c> calloutsScheduled = new List<MCCallout__c>();

        for(genesis__Applications__c ls : apps) {
            if(ls.genesis__Status__c != oldMap.get(ls.Id).genesis__Status__c && ls.genesis__Status__c=='offer_shown') {
                appList.add(ls.Id);
            }
        }

        if(appList.size()>0) {
            Set<String> appListNoDups = new Set<String>();
            appListNoDups.addAll(appList);
            String app = '';
            if(!appListNoDups.isEmpty()) {app = new list<String>(appListNoDups)[0];}
            List<MCCallout__c> currentCallout = new List<MCCallout__c>([Select Id From MCCallout__c Where Application__c=: app limit 1]);

            if(currentCallout == null && currentCallout.size()<=0) {
                ID jobID = System.enqueueJob(new MWQueuebleJob(appList));
                System.debug('>>> 1'+jobID);
                calloutsScheduled.add(new MCCallout__c(Job_ID__c = jobID, Application__c=app, Status__c = 'Queued', Send_on__c=System.now()));
            }

            if(calloutsScheduled.size()>0) {
                insert calloutsScheduled;
            }
        }


    }


    public static void UpdateApplicationFlags(List<genesis__Applications__c> appslist, Map<Id, genesis__Applications__c> oldMap)
    {
        for(genesis__Applications__c app : appslist) {
            /* CLS-676 -- Moved to process builder as a part of CLS-1302
            if(app.Employment_Status__c!= null && oldMap.get(app.Id).genesis__Status__c!=app.Employment_Status__c  && app.Employment_Status__c =='Self Employed' && !app.isSelfEmployed__c) {
                app.genesis__Status__c ='Self Employed Documents';
                app.isSelfEmployed__c = true;
            }*/

            if(app.genesis__Status__c == 'Redecision_Required' && app.genesis__Status__c!=oldMap.get(app.Id).genesis__Status__c) {
                app.agentVerificationPendingFlag__c = false;
            }

            if(app.custom_APR_for_not_rounding__c == null || app.custom_APR_for_not_rounding__c == 0 || oldMap.get(app.Id).genesis__APR__c!=app.genesis__APR__c) {
                app.custom_APR_for_not_rounding__c = app.genesis__APR__c;
            }

            if(app.Required_Docs_Count__c==0 && app.genesis__Status__c !='agent_document_verification_pending' && !app.agentVerificationPendingFlag__c /*CLS-980-->*/
                    && app.genesis__Status__c !='Redecision_Required' /*CLS-994 --> */ && app.genesis__Status__c !='Stacker_Check_Passed' && app.genesis__Status__c !='agent_verified'
                    && app.genesis__Status__c !='docusign_loan_docs_sent' && app.genesis__Status__c !='docusign_loan_docs_complete' && app.genesis__Status__c !='pre_funding'
                    && app.genesis__Status__c !='Approved for funding' && app.genesis__Status__c !='funded' /*PS-1709-->*/ && app.genesis__Status__c !='offer_shown'
                    && app.genesis__Status__c !='Declined' && app.genesis__Status__c !='Expired' && app.genesis__Status__c !='Withdrawn'
                    && app.genesis__Status__c !='Decline_Manual_Review' && app.owner.Name != 'Review Queue') {

                app.genesis__Status__c ='agent_document_verification_pending';

                if(MW_WebhookHelper.appQueueDetails().size()>0 && /*CLS-1174 -->*/ !app.readyforverificationQueueFlag__c) {
                    app.ownerid = MW_WebhookHelper.appQueueDetails().get('Ready for Verification');
                    app.readyforverificationQueueFlag__c = true;/*CLS-1174 --*/
                }

                app.agentVerificationPendingFlag__c = true;
            }
        }
    }

    public static void updateBoxFolder(List<genesis__Applications__c> appslist){

        for(genesis__Applications__c app : appslist)
        {
            if(app.BoxFolderID__c==null) {
                app.BoxFolderID__c     = MW_Settings__c.getInstance().BOXRootFolder__c;
            }

            if(app.genesis__Status__c=='NEW - ENTERED') {
                app.genesis__Status__c ='Default Documents';
            }

            if(app.genesis__CL_Product__c==null) {
                List<clcommon__CL_Product__c> productlist  = new List<clcommon__CL_Product__c>([SELECT Id,Name from clcommon__CL_Product__c where clcommon__Product_Name__c='Auto Payer' limit 1]);
                if(productlist.size()>0) {
                    app.genesis__CL_Product__c =productlist[0].Id;
                }
            }
        }
    }

}