unpackaged/main/default/objects/genesis__AppDocCatAttachmentJunction__c/genesis__AppDocCatAttachmentJunction__c.object-meta.xml
<CustomObject>
    <label>AppDocCatAttachmentJunction</label>
    <nameField>
        <displayFormat>ADCA-{00000000}</displayFormat>
        <label>AppDocCatAttachmentJunction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AppDocCatAttachmentJunctions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/genesis__AppDocCatAttachmentJunction__c/fields/genesis__Application_Document_Category__c.field-meta.xml
<CustomField>
    <fullName>genesis__Application_Document_Category__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application Document Category</label>
    <referenceTo>genesis__Application_Document_Category__c</referenceTo>
    <relationshipLabel>AppDocCatAttachmentJunctions</relationshipLabel>
    <relationshipName>AppDocCatAttachmentJunctions</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/genesis__AppDocCatAttachmentJunction__c/fields/genesis__AttachmentId__c.field-meta.xml
<CustomField>
    <fullName>genesis__AttachmentId__c</fullName>
    <label>AttachmentId</label>
    <length>21</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/genesis__Application_Document_Category__c/genesis__Application_Document_Category__c.object-meta.xml
<CustomObject>
    <label>Application Document Category</label>
    <nameField>
        <label>Application Document Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application Document Category</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/genesis__Application_Document_Category__c/fields/genesis__Application__c.field-meta.xml
<CustomField>
    <fullName>genesis__Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>genesis__Applications__c</referenceTo>
    <relationshipLabel>Application Document Category</relationshipLabel>
    <relationshipName>Application_Document_Category</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/loan__Batch_Process_Log__c/loan__Batch_Process_Log__c.object-meta.xml
<CustomObject>
    <label>Batch Process Log</label>
    <nameField>
        <label>Apex Batch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Batch Process Log</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/loan__Batch_Process_Log__c/fields/loan__Message__c.field-meta.xml
<CustomField>
    <fullName>loan__Message__c</fullName>
    <label>Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/loan__Batch_Process_Log__c/fields/loan__Origin__c.field-meta.xml
<CustomField>
    <fullName>loan__Origin__c</fullName>
    <label>Origin</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Start Of Day Process</fullName>
            </value>
            <value>
                <fullName>End of Day Process</fullName>
            </value>
            <value>
                <fullName>Month End Process</fullName>
            </value>
            <value>
                <fullName>Year End Process</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/loan__Batch_Process_Log__c/fields/loan__Time__c.field-meta.xml
<CustomField>
    <fullName>loan__Time__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <label>Time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/loan__Batch_Process_Log__c/fields/loan__Type__c.field-meta.xml
<CustomField>
    <fullName>loan__Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Exception</fullName>
            </value>
            <value>
                <fullName>Warning</fullName>
            </value>
            <value>
                <fullName>Info</fullName>
            </value>
            <value>
                <fullName>Result</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/AppDealRoomAttachment.cls
Public With Sharing class AppDealRoomAttachment{
    public static void DealroomAttachment(Id applicationId, Set<Id> attachmentId){
        Map<Id,String> attachCategory = new Map<Id,String>();
        try{         
            List<Attachment> attachments = [Select Id,Name,Description from Attachment where id in:attachmentId];
            for(Attachment attachId : attachments){
                attachCategory.put(attachId.id,attachId.Description);
            }
            List<genesis__Application_Document_Category__c> lstAppDocCat = [Select Id,Name from genesis__Application_Document_Category__c where genesis__Application__c =: applicationId and Name like: attachCategory.values() and IsDeleted = false];
            List<genesis__AppDocCatAttachmentJunction__c> appDocCatAttInsert = new List<genesis__AppDocCatAttachmentJunction__c>();
            for(genesis__Application_Document_Category__c appDoc : lstAppDocCat) {
                for(Id attachId : attachmentId){
                    if(appDoc.name.equalsIgnoreCase(attachCategory.get(attachId))) {
                        genesis__AppDocCatAttachmentJunction__c lstAppDocCatAttachment = new genesis__AppDocCatAttachmentJunction__c();  
                        lstAppDocCatAttachment.genesis__Application_Document_Category__c = appDoc.Id;
                        lstAppDocCatAttachment.genesis__AttachmentId__c = attachId;  
                        appDocCatAttInsert.add(lstAppDocCatAttachment); 
                    }
                }
            }
            if(!appDocCatAttInsert.isEmpty())
            	insert appDocCatAttInsert;
            
            /*for(Id attachId : attachmentId){
            	if(!lstAppDocCat.isEmpty()){
                    system.debug('---lstAppDocCat----'+lstAppDocCat); 
                    System.debug('.... Attachment Id ..' + attachId );
                    
                    for(genesis__Application_Document_Category__c genesisAppIterate : lstAppDocCat){
                        genesis__AppDocCatAttachmentJunction__c lstAppDocCatAttachment = new genesis__AppDocCatAttachmentJunction__c();  
                        
                        lstAppDocCatAttachment.genesis__Application_Document_Category__c = genesisAppIterate.Id;
                        lstAppDocCatAttachment.genesis__AttachmentId__c = attachId;  
                        appDocCatAttInsert.add(lstAppDocCatAttachment); 
                    }
                    if(!appDocCatAttInsert.isEmpty())
                        insert appDocCatAttInsert;
                }
            }*/
        }catch (Exception ex){
            loan__Batch_Process_Log__c bplog = new loan__Batch_Process_Log__c(loan__Origin__c = 'Adverse Action Dealroom',loan__Message__c = 'Error: ' + ex.getLineNumber() + ' Desc. ' + ex.getMessage()+' Stack: '+ex.getStackTraceString(),loan__Type__c = 'Exception',loan__Time__c = DateTime.now());
            insert bplog;  throw ex;
        } 
     }
}