force-app/main/default/objects/DM_Accrual_Entry__c/DM_Accrual_Entry__c.object-meta.xml
<CustomObject>
    <label>DM Accrual Entry</label>
    <nameField>
        <label>DM  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DM Accrual Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DM_Automated_Payment_Setup__c/DM_Automated_Payment_Setup__c.object-meta.xml
<CustomObject>
    <label>DM Automated Payment Setup</label>
    <nameField>
        <label>DM Automated Payment Setup Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DM Automated Payment Setup</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DM_Bill__c/DM_Bill__c.object-meta.xml
<CustomObject>
    <label>DM Bill</label>
    <nameField>
        <label>DM Bill Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DM Bills</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DM_Charge__c/DM_Charge__c.object-meta.xml
<CustomObject>
    <label>DM Charge</label>
    <nameField>
        <label>DM Charge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DM Charges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DM_Disbursal_Transaction_Distribution__c/DM_Disbursal_Transaction_Distribution__c.object-meta.xml
<CustomObject>
    <label>DM Disbursal Transaction Distribution</label>
    <nameField>
        <label>DM Disbursal Transaction Distribution Na</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DM Disbursal Transaction Distributions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DM_Disbursal_Transaction_Distribution__c/fields/DM_Loan_Disbursal_Transaction__c.field-meta.xml
<CustomField>
    <fullName>DM_Loan_Disbursal_Transaction__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>DM Loan Disbursal Transaction</label>
    <referenceTo>DM_Loan_Disbursal_Transaction__c</referenceTo>
    <relationshipLabel>DM Disbursal Transaction Distributions</relationshipLabel>
    <relationshipName>DM_Disbursal_Transaction_Distributions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DM_Due_Payment__c/DM_Due_Payment__c.object-meta.xml
<CustomObject>
    <label>DM Due Payment</label>
    <nameField>
        <label>DM Due Payment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DM Due Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DM_Due_Payment__c/fields/DM_Loan_Payment_Transaction__c.field-meta.xml
<CustomField>
    <fullName>DM_Loan_Payment_Transaction__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>DM Loan Payment Transaction</label>
    <referenceTo>DM_Loan_Payment_Transaction__c</referenceTo>
    <relationshipLabel>DM Due Payments</relationshipLabel>
    <relationshipName>DM_Due_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DM_Interest_Posting_Transaction__c/DM_Interest_Posting_Transaction__c.object-meta.xml
<CustomObject>
    <label>DM Interest Posting Transaction</label>
    <nameField>
        <label>DM  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DM Interest Posting Transaction</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DM_Investment_Order__c/DM_Investment_Order__c.object-meta.xml
<CustomObject>
    <label>DM Investment Order</label>
    <nameField>
        <label>Investment Order	 Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DM Investment Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DM_Investor_Loan_Transaction__c/DM_Investor_Loan_Transaction__c.object-meta.xml
<CustomObject>
    <label>DM Investor Loan Transaction</label>
    <nameField>
        <label>DM Investor Loan Transaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DM Investor Loan Transaction</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DM_Investor_Loan_Transaction__c/fields/DM_Investment_Order__c.field-meta.xml
<CustomField>
    <fullName>DM_Investment_Order__c</fullName>
    <label>DM Investment Order</label>
    <referenceTo>DM_Investment_Order__c</referenceTo>
    <relationshipLabel>DM Investor Loan Transaction</relationshipLabel>
    <relationshipName>DM_Investor_Loan_Transaction</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DM_Investor_Loan_Transaction__c/fields/DM_Loan_Payment_Transaction__c.field-meta.xml
<CustomField>
    <fullName>DM_Loan_Payment_Transaction__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>DM Loan Payment Transaction</label>
    <referenceTo>DM_Loan_Payment_Transaction__c</referenceTo>
    <relationshipLabel>DM Investor Loan Transaction</relationshipLabel>
    <relationshipName>DM_Investor_Loan_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DM_Loan_Disbursal_Transaction__c/DM_Loan_Disbursal_Transaction__c.object-meta.xml
<CustomObject>
    <label>DM Loan Disbursal Transaction</label>
    <nameField>
        <label>DM  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DM Loan Disbursal Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DM_Loan_Payment_Transaction__c/DM_Loan_Payment_Transaction__c.object-meta.xml
<CustomObject>
    <label>DM Loan Payment Transaction</label>
    <nameField>
        <label>DM  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DM Loan Payment Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DM_Loan_Payment_Transaction__c/fields/DM_Automated_Payment_Setup__c.field-meta.xml
<CustomField>
    <fullName>DM_Automated_Payment_Setup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>DM Automated Payment Setup</label>
    <referenceTo>DM_Automated_Payment_Setup__c</referenceTo>
    <relationshipLabel>DM Loan Payment Transactions</relationshipLabel>
    <relationshipName>DM_Loan_Payment_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DM_Multi_Step_Loan_Setup__c/DM_Multi_Step_Loan_Setup__c.object-meta.xml
<CustomObject>
    <label>DM Rate Schedule Setup</label>
    <nameField>
        <label>DM Rate Schedule Setup Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DM Rate Schedule Setups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DM_Repayment_Plan__c/DM_Repayment_Plan__c.object-meta.xml
<CustomObject>
    <label>DM Repayment Plan</label>
    <nameField>
        <label>DM Repayment Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DM Repayment Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DM_Repayment_Schedule__c/DM_Repayment_Schedule__c.object-meta.xml
<CustomObject>
    <label>DM Amortization Schedule</label>
    <nameField>
        <label>Dm Repayment Schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DM Amortization Schedule</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DM_Repayment_Schedule_Summary__c/DM_Repayment_Schedule_Summary__c.object-meta.xml
<CustomObject>
    <label>DM Repayment Schedule</label>
    <nameField>
        <label>DM Amortization Schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DM Repayment Schedule</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DM_Repayment_Schedule_Summary__c/fields/DM_Loan_Disbursal_Transaction__c.field-meta.xml
<CustomField>
    <fullName>DM_Loan_Disbursal_Transaction__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Repayment Schedule Record of which LDT</description>
    <inlineHelpText>This field is used only in case of FIT (Fund in Tranches) Loans. Every disbursal re-generates repayment schedule, this field keeps track of parent disbursal due to which record is created.</inlineHelpText>
    <label>DM Loan Disbursal Transaction</label>
    <referenceTo>DM_Loan_Disbursal_Transaction__c</referenceTo>
    <relationshipName>DM_Loan_Disbursal_Transaction</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DM_Repayment_Transaction_Reversal__c/DM_Repayment_Transaction_Reversal__c.object-meta.xml
<CustomObject>
    <label>DM Repayment Transaction Reversal</label>
    <nameField>
        <label>DM Repayment Transaction Reversal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DM Repayment Transaction Reversal</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DM_Repayment_Transaction_Reversal__c/fields/DM_Loan_Payment_Transaction__c.field-meta.xml
<CustomField>
    <fullName>DM_Loan_Payment_Transaction__c</fullName>
    <label>DM Loan Payment Transaction</label>
    <referenceTo>DM_Loan_Payment_Transaction__c</referenceTo>
    <relationshipLabel>DM Repayment Transaction Reversal</relationshipLabel>
    <relationshipName>DM_Repayment_Transaction_Reversal</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/DM_ComputeStrategy_Interface.cls
/**
 * Interface - Hook provided to implement Strategy-1000
 * 
 * 
 * @author - Nikhil Chawra
 * **/

Global interface DM_ComputeStrategy_Interface {
    List<DM_Repayment_Schedule_Summary__c> computeRSS(Id ParentId);
    List<dm_Loan_Payment_Transaction__c> computeLPT(Id ParentId);
    List<dm_Loan_Disbursal_Transaction__c> computeLDT(Id ParentId);
    List<DM_Bill__c> computeBill(Id ParentId);
    List<DM_Charge__c> computeCharge(Id ParentId);
    List<DM_Automated_Payment_Setup__c> computeAPS(Id ParentId);
    List<DM_Repayment_Schedule__c> computeRS(Id ParentId); 
    List<DM_Accrual_Entry__c> computeAccrual(Id ParentId);
    List<DM_Interest_Posting_Transaction__c> computeIPT(Id ParentId);
    List<DM_Investment_Order__c> computeInvestorLoan(Id ParentId); 
    
    // added by NehaDM
    List<DM_Disbursal_Transaction_Distribution__c> computeDDI(Id ParentId);
    List<DM_Multi_Step_Loan_Setup__c> computeMSLS(Id ParentId);
    //List<DM_Investor_Loan_Transaction__c> computeInvLT(Id ParentId); 
    /*pallavi*/
    List<DM_Due_Payment__c> computeDPT(Id ParentId);
    /*pallavi*/
    /*pallavi*/
    List<DM_Repayment_Transaction_Reversal__c> computetxnRev(Id ParentId);
    List<DM_Repayment_Plan__c> computerepPlan(Id ParentId);
    /*pallavi*/
}