force-app/main/default/objects/DM_Accrual_Entry__c/DM_Accrual_Entry__c.object-meta.xml
<CustomObject>
    <label>DM Accrual Entry</label>
    <nameField>
        <label>DM  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DM Accrual Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DM_Automated_Payment_Setup__c/DM_Automated_Payment_Setup__c.object-meta.xml
<CustomObject>
    <label>DM Automated Payment Setup</label>
    <nameField>
        <label>DM Automated Payment Setup Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DM Automated Payment Setup</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DM_Bill__c/DM_Bill__c.object-meta.xml
<CustomObject>
    <label>DM Bill</label>
    <nameField>
        <label>DM Bill Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DM Bills</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DM_Charge__c/DM_Charge__c.object-meta.xml
<CustomObject>
    <label>DM Charge</label>
    <nameField>
        <label>DM Charge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DM Charges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DM_Interest_Posting_Transaction__c/DM_Interest_Posting_Transaction__c.object-meta.xml
<CustomObject>
    <label>DM Interest Posting Transaction</label>
    <nameField>
        <label>DM  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DM Interest Posting Transaction</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DM_Investment_Order__c/DM_Investment_Order__c.object-meta.xml
<CustomObject>
    <label>DM Investment Order</label>
    <nameField>
        <label>Investment Order	 Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DM Investment Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DM_Loan_Account__c/DM_Loan_Account__c.object-meta.xml
<CustomObject>
    <label>DM CL Contract</label>
    <nameField>
        <label>DM Loan Con Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DM CL Contract</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DM_Loan_Disbursal_Transaction__c/DM_Loan_Disbursal_Transaction__c.object-meta.xml
<CustomObject>
    <label>DM Loan Disbursal Transaction</label>
    <nameField>
        <label>DM  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DM Loan Disbursal Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DM_Loan_Payment_Transaction__c/DM_Loan_Payment_Transaction__c.object-meta.xml
<CustomObject>
    <label>DM Loan Payment Transaction</label>
    <nameField>
        <label>DM  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DM Loan Payment Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DM_Loan_Payment_Transaction__c/fields/DM_Automated_Payment_Setup__c.field-meta.xml
<CustomField>
    <fullName>DM_Automated_Payment_Setup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>DM Automated Payment Setup</label>
    <referenceTo>DM_Automated_Payment_Setup__c</referenceTo>
    <relationshipLabel>DM Loan Payment Transactions</relationshipLabel>
    <relationshipName>DM_Loan_Payment_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DM_Multi_Step_Loan_Setup__c/DM_Multi_Step_Loan_Setup__c.object-meta.xml
<CustomObject>
    <label>DM Rate Schedule Setup</label>
    <nameField>
        <label>DM Rate Schedule Setup Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DM Rate Schedule Setups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DM_Multi_Step_Loan_Setup__c/fields/DM_Loan_Account__c.field-meta.xml
<CustomField>
    <fullName>DM_Loan_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>DM Loan Account</label>
    <referenceTo>DM_Loan_Account__c</referenceTo>
    <relationshipLabel>DM Rate Schedule Setups</relationshipLabel>
    <relationshipName>DM_Rate_Schedule_Setups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DM_Repayment_Schedule__c/DM_Repayment_Schedule__c.object-meta.xml
<CustomObject>
    <label>DM Amortization Schedule</label>
    <nameField>
        <label>Dm Repayment Schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DM Amortization Schedule</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DM_Repayment_Schedule_Summary__c/DM_Repayment_Schedule_Summary__c.object-meta.xml
<CustomObject>
    <label>DM Repayment Schedule</label>
    <nameField>
        <label>DM Amortization Schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DM Repayment Schedule</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DM_Repayment_Schedule_Summary__c/fields/DM_Loan_Disbursal_Transaction__c.field-meta.xml
<CustomField>
    <fullName>DM_Loan_Disbursal_Transaction__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Repayment Schedule Record of which LDT</description>
    <inlineHelpText>This field is used only in case of FIT (Fund in Tranches) Loans. Every disbursal re-generates repayment schedule, this field keeps track of parent disbursal due to which record is created.</inlineHelpText>
    <label>DM Loan Disbursal Transaction</label>
    <referenceTo>DM_Loan_Disbursal_Transaction__c</referenceTo>
    <relationshipName>DM_Loan_Disbursal_Transaction</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DM_StagingObject_Query_Generator__c/DM_StagingObject_Query_Generator__c.object-meta.xml
<CustomObject>
    <label>DM StagingObject Query Generator</label>
    <nameField>
        <label>DM StagingObject Query Generator Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DM StagingObject Query Generators</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DM_StagingObject_Query_Generator__c/fields/DM_isChild_of_Contract__c.field-meta.xml
<CustomField>
    <fullName>DM_isChild_of_Contract__c</fullName>
    <defaultValue>false</defaultValue>
    <label>DM isChild of Contract</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DM_StagingObject_Query_Generator__c/fields/DM_Parent_API_Name__c.field-meta.xml
<CustomField>
    <fullName>DM_Parent_API_Name__c</fullName>
    <label>DM Parent API Name</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DM_StagingObject_Query_Generator__c/fields/DM_Parent_Object__c.field-meta.xml
<CustomField>
    <fullName>DM_Parent_Object__c</fullName>
    <label>DM Parent Object</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DM_StagingObject_Query_Generator__c/fields/DM_Query_Fields__c.field-meta.xml
<CustomField>
    <fullName>DM_Query_Fields__c</fullName>
    <label>DM Query Fields</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/DM_Validation_JOB_stagingObjects.cls
global class DM_Validation_JOB_stagingObjects implements Database.Batchable<sObject> {
    Integer thread = 0;
    Integer queryLimit = 0;
    public List<DM_StagingObject_Query_Generator__c> queryGenerate = [Select id,DM_object_name__c,DM_Query_Fields__c,DM_Parent_Object__c
                                                        from DM_StagingObject_Query_Generator__c
                                                        where DM_Active__c = true and DM_isChild_of_anotherObject__c = true];

    Map<String,DM_StagingObject_Query_Generator__c> MapQueryGenerate = new  Map<String,DM_StagingObject_Query_Generator__c>();
    Map<String,List<sObject>> queryChildContracts = new Map<String,List<sObject>>();
    global DM_Validation_JOB_stagingObjects(){
        for(DM_StagingObject_Query_Generator__c QueryGen : queryGenerate){
            MapQueryGenerate.put(QueryGen.DM_object_name__c,QueryGen);
        }    
                
    }
    /*pallavi*/
    global DM_Validation_JOB_stagingObjects(Integer threadNumber){
        thread = threadNumber;  
        for(DM_StagingObject_Query_Generator__c QueryGen : queryGenerate){
            MapQueryGenerate.put(QueryGen.DM_object_name__c,QueryGen);
        }     
    }
    /*global DM_Validation_JOB_stagingObjects(Integer threadNumber,Integer qryLimit){
        thread = threadNumber; 
        queryLimit = qryLimit;
        for(DM_StagingObject_Query_Generator__c QueryGen : queryGenerate){
            MapQueryGenerate.put(QueryGen.DM_object_name__c,QueryGen);
        }     
    }*/
    /*pallavi*/
    
    global Database.QueryLocator start(Database.BatchableContext BC)
    {
        String migrationBatchType = null;	//changed
        DM_SqlQueryGenerator_forValidation sqlQuery = new DM_SqlQueryGenerator_forValidation();  
        //System.debug('query... '+sqlQuery.GetQueryString('DM_Repayment_Schedule_Summary__c;DM_Loan_Payment_Transaction__c;DM_Loan_Disbursal_Transaction__c;DM_Charge__c;DM_Bill__c;DM_Automated_Payment_Setup__c;DM_Repayment_Schedule__c;DM_Investment_Order__c;DM_Interest_Posting_Transaction__c;DM_Accrual_Entry__c;DM_Multi_Step_Loan_Setup__c;DM_Loan_Account__c',migrationBatchType,thread));
		return Database.getQueryLocator(sqlQuery.GetQueryString(migrationBatchType,thread));   
    }
    global void execute(Database.BatchableContext BC,List<dm_Loan_Account__c> ContractList)
    {
        system.debug('scope list '+ContractList.size());
        
         List<DM_StagingObject_Query_Generator__c> generateQuery = [Select id,DM_object_name__c,DM_Query_Fields__c,DM_Parent_API_Name__c
                                                                from DM_StagingObject_Query_Generator__c
                                                                where DM_Active__c = true
                                                                and DM_isChild_of_Contract__c = true ];
        for(DM_StagingObject_Query_Generator__c objectFields : generateQuery){
            String query = 'Select ' + objectFields.DM_Query_Fields__c + ' from ' + objectFields.DM_object_name__c + ' where '+objectFields.DM_Parent_API_Name__c+ ' in: ContractList';
            System.debug('query ' + query);
            List<sObject> childData = Database.query(query);
            queryChildContracts.put(objectFields.DM_object_name__c, childData);
        }
        
        DM_Validation_stagingObjects_Handler handler = new DM_Validation_stagingObjects_Handler();
        handler.ValidationWrapper(ContractList,MapQueryGenerate,queryChildContracts);
     }
      global void finish(Database.BatchableContext BC) {
         system.debug('Finish Batch Job');
    }
}