unpackaged/main/default/objects/loan__Loan_Account__c/loan__Loan_Account__c.object-meta.xml
<CustomObject>
    <description>Lending Account</description>
    <label>CL Contract</label>
    <nameField>
        <displayFormat>LAI-{00000000}</displayFormat>
        <label>CL Contract ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CL Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/loan__Loan_Account__c/fields/loan__Payment_Amount__c.field-meta.xml
<CustomField>
    <fullName>loan__Payment_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Loan payment amount. It excludes any fee that is gathered as a part of EMI.</description>
    <inlineHelpText>Contractual payment amount</inlineHelpText>
    <label>Payment Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/loan__Loan_Account__c/fields/Mod_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Mod_End_Date__c</fullName>
    <label>Mod End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/loan__Loan_Account__c/fields/Mod_Payment_Amount__c.field-meta.xml
<CustomField>
    <fullName>Mod_Payment_Amount__c</fullName>
    <label>Mod Payment Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/loan__Repayment_Schedule_Summary__c/loan__Repayment_Schedule_Summary__c.object-meta.xml
<CustomObject>
    <label>Repayment Schedule</label>
    <nameField>
        <displayFormat>RSS-{0000000000}</displayFormat>
        <label>Repayment Schedule id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Repayment Schedule</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/loan__Repayment_Schedule_Summary__c/fields/loan__RSS_Loan_Account__c.field-meta.xml
<CustomField>
    <fullName>loan__RSS_Loan_Account__c</fullName>
    <label>Loan</label>
    <referenceTo>loan__Loan_Account__c</referenceTo>
    <relationshipName>Repayment_Schedule_Summary</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/loan__Repayment_Schedule_Summary__c/fields/loan__RSS_Repayment_Amt__c.field-meta.xml
<CustomField>
    <fullName>loan__RSS_Repayment_Amt__c</fullName>
    <label>Repayment Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/loan__Repayment_Schedule_Summary__c/fields/loan__RSS_Repayment_Dt__c.field-meta.xml
<CustomField>
    <fullName>loan__RSS_Repayment_Dt__c</fullName>
    <label>Repayment Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/loan__Repayment_Schedule_Summary__c/fields/loan__RSS_Seq__c.field-meta.xml
<CustomField>
    <fullName>loan__RSS_Seq__c</fullName>
    <label>Sequence</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/classes/loan_RepaymentScheduleHandler.cls
public with sharing class loan_RepaymentScheduleHandler {

    final List<loan__Repayment_Schedule_Summary__c> newRecords;
    final Map<Id, loan__Repayment_Schedule_Summary__c> oldMap;
    final Map<Id, loan__Repayment_Schedule_Summary__c> newMap;

    public loan_RepaymentScheduleHandler(List< loan__Repayment_Schedule_Summary__c> newRecords, Map<Id, loan__Repayment_Schedule_Summary__c> oldMap, Map<Id, loan__Repayment_Schedule_Summary__c> newMap) {
        this.newRecords = newRecords;
        this.oldMap = oldMap;
        this.newMap = newMap;
    }

    public void afterInsert() {
        updateContractPaymentAmount();
    }

    //LSP-1153
    private void updateContractPaymentAmount() {
        Set<String> contractIds = new Set<String>();
    
        for(loan__Repayment_Schedule_Summary__c rs : newRecords) {
    
            if (rs.loan__RSS_Seq__c == 3 && rs.loan__RSS_Primary_flag__c == true) {
                contractIds.add(rs.loan__RSS_Loan_Account__c);
            }
        }
    
        List<loan__Loan_Account__c> updateContract = new List<loan__Loan_Account__c>();
    
        for (List<loan__Loan_Account__c> clContracts : [SELECT 
                                                        Id, loan__Payment_Amount__c, 
                                                        (select id, loan__RSS_Seq__c, loan__RSS_Repayment_Amt__c, loan__RSS_Repayment_Dt__c 
                                                        FROM loan__Repayment_Schedule_Summary__r 
                                                        WHERE loan__RSS_Primary_flag__c = true order by loan__RSS_Seq__c asc) 
                                                        FROM loan__Loan_Account__c 
                                                        WHERE id IN :contractIds
                                                        WITH SECURITY_ENFORCED]){
            for(loan__Loan_Account__c clContract : clContracts) {
    
                if (clContract.loan__Repayment_Schedule_Summary__r.size() >= 2) {
                    if (clContract.loan__Repayment_Schedule_Summary__r[0].loan__RSS_Seq__c == 1 && 
                        clContract.loan__Repayment_Schedule_Summary__r[0].loan__RSS_Repayment_Amt__c != clContract.loan__Payment_Amount__c
                    ) {
    
                        clContract.Mod_Payment_Amount__c = clContract.loan__Repayment_Schedule_Summary__r[0].loan__RSS_Repayment_Amt__c;
                        clContract.Mod_End_Date__c = clContract.loan__Repayment_Schedule_Summary__r[1].loan__RSS_Repayment_Dt__c.addDays(-1);
    
    
                        updateContract.add(clContract);
                    }
                }
            }                                                    
        }
    
        if (updateContract.size() > 0) {
            update updateContract;
        }
    }

}