unpackaged/main/default/objects/loan__Loan_Account__c/loan__Loan_Account__c.object-meta.xml
<CustomObject>
    <description>Lending Account</description>
    <label>CL Contract</label>
    <nameField>
        <displayFormat>LAI-{00000000}</displayFormat>
        <label>CL Contract ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CL Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/loan__Loan_Account__c/fields/loan__Interest_Accrued_Not_Due__c.field-meta.xml
<CustomField>
    <fullName>loan__Interest_Accrued_Not_Due__c</fullName>
    <defaultValue>0.0</defaultValue>
    <description>This field gets updated on Payment Date. It is the accrued interest that is posted on the account.</description>
    <inlineHelpText>Interest balance as of last accrual date.</inlineHelpText>
    <label>Interest Accrued</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/loan__Loan_Disbursal_Transaction__c/loan__Loan_Disbursal_Transaction__c.object-meta.xml
<CustomObject>
    <description>This is the final stage where all the documents submitted by a customer are finally checked and the loan is approved.</description>
    <label>Loan Disbursal Transaction</label>
    <nameField>
        <displayFormat>LDTI-{0000000000}</displayFormat>
        <label>Loan Disbursal Transaction ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loan Disbursal Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/loan__Loan_Disbursal_Transaction__c/fields/loan__Loan_Account__c.field-meta.xml
<CustomField>
    <fullName>loan__Loan_Account__c</fullName>
    <description>Loan Account</description>
    <inlineHelpText>Loan Account</inlineHelpText>
    <label>Loan Account</label>
    <referenceTo>loan__Loan_Account__c</referenceTo>
    <relationshipLabel>Loan Disbursal Transactions</relationshipLabel>
    <relationshipName>Loan_Disbursal_Transactions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/loan__Repayment_Schedule__c/loan__Repayment_Schedule__c.object-meta.xml
<CustomObject>
    <description>Amortization schedule is also called as Repayment schedule.</description>
    <label>Amortization Schedule</label>
    <nameField>
        <displayFormat>RSI-{0000000000}</displayFormat>
        <label>Repayment Schedule ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Amortization Schedule</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/loan__Repayment_Schedule__c/fields/loan__Balance__c.field-meta.xml
<CustomField>
    <fullName>loan__Balance__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Principal Balance</description>
    <inlineHelpText>Principal Balance</inlineHelpText>
    <label>Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/loan__Repayment_Schedule__c/fields/loan__Barcode_Subtype__c.field-meta.xml
<CustomField>
    <fullName>loan__Barcode_Subtype__c</fullName>
    <label>Barcode Subtype</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>loan__Barcode_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>128A</fullName>
            </value>
            <value>
                <fullName>128B</fullName>
            </value>
            <value>
                <fullName>128C</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/loan__Repayment_Schedule__c/fields/loan__Barcode_Type__c.field-meta.xml
<CustomField>
    <fullName>loan__Barcode_Type__c</fullName>
    <label>Barcode Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Code128</fullName>
                <default>true</default>
                <label>Code128</label>
            </value>
            <value>
                <fullName>code39</fullName>
            </value>
            <value>
                <fullName>ean13</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/loan__Repayment_Schedule__c/fields/loan__Date_Paid__c.field-meta.xml
<CustomField>
    <fullName>loan__Date_Paid__c</fullName>
    <description>Date paid</description>
    <inlineHelpText>Date paid</inlineHelpText>
    <label>Date Paid</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/loan__Repayment_Schedule__c/fields/loan__Due_Amount__c.field-meta.xml
<CustomField>
    <fullName>loan__Due_Amount__c</fullName>
    <label>Due_Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/loan__Repayment_Schedule__c/fields/loan__Due_Date__c.field-meta.xml
<CustomField>
    <fullName>loan__Due_Date__c</fullName>
    <description>Due date</description>
    <inlineHelpText>The date on which the loan payment is due.</inlineHelpText>
    <label>Due Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/loan__Repayment_Schedule__c/fields/loan__Due_Interest__c.field-meta.xml
<CustomField>
    <fullName>loan__Due_Interest__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Due Interest</description>
    <inlineHelpText>Due Interest</inlineHelpText>
    <label>Due Interest</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/loan__Repayment_Schedule__c/fields/loan__Due_Interest_On_Overdue__c.field-meta.xml
<CustomField>
    <fullName>loan__Due_Interest_On_Overdue__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Due Interest On Overdue Amount</description>
    <inlineHelpText>Due Interest On Overdue Amount</inlineHelpText>
    <label>Due Interest On Overdue</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/loan__Repayment_Schedule__c/fields/loan__Due_Principal__c.field-meta.xml
<CustomField>
    <fullName>loan__Due_Principal__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Due Principal</description>
    <inlineHelpText>Due Principal</inlineHelpText>
    <label>Due Principal</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/loan__Repayment_Schedule__c/fields/loan__Installment_Snapshot__c.field-meta.xml
<CustomField>
    <fullName>loan__Installment_Snapshot__c</fullName>
    <label>Installment Snapshot</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/loan__Repayment_Schedule__c/fields/loan__Interest_Accrued_Not_Due__c.field-meta.xml
<CustomField>
    <fullName>loan__Interest_Accrued_Not_Due__c</fullName>
    <defaultValue>0.0</defaultValue>
    <description>Its the interest accrued on a daily basis, but not due until the due date.</description>
    <inlineHelpText>Its the interest accrued on a daily basis, but not due until the due date.</inlineHelpText>
    <label>Interest Accrued Not Due</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/loan__Repayment_Schedule__c/fields/loan__Is_Archived__c.field-meta.xml
<CustomField>
    <fullName>loan__Is_Archived__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates if a new repayment schedule for this loan account has been generated and this one is archived for reference.</description>
    <inlineHelpText>Indicates if a new repayment schedule for this loan account has been generated and this one is archived for reference.</inlineHelpText>
    <label>Is Archived</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/loan__Repayment_Schedule__c/fields/loan__Is_Billed__c.field-meta.xml
<CustomField>
    <fullName>loan__Is_Billed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Billed</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/loan__Repayment_Schedule__c/fields/loan__Is_Partially_Paid__c.field-meta.xml
<CustomField>
    <fullName>loan__Is_Partially_Paid__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates if this scheduled installment is only partially paid.</description>
    <inlineHelpText>Indicates if this scheduled installment is only partially paid.</inlineHelpText>
    <label>Is Partially Paid</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/loan__Repayment_Schedule__c/fields/loan__isPaid__c.field-meta.xml
<CustomField>
    <fullName>loan__isPaid__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checked if the scheduled payment is/was completely paid</description>
    <inlineHelpText>Checked if the scheduled payment is/was completely paid</inlineHelpText>
    <label>Is Paid</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/loan__Repayment_Schedule__c/fields/loan__Loan_Account__c.field-meta.xml
<CustomField>
    <fullName>loan__Loan_Account__c</fullName>
    <description>Repayment Schedule of which Loan account</description>
    <inlineHelpText>Repayment Schedule of which Loan account</inlineHelpText>
    <label>Loan Account</label>
    <referenceTo>loan__Loan_Account__c</referenceTo>
    <relationshipName>Repayment_Schedule</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/loan__Repayment_Schedule__c/fields/loan__Paid_Fees__c.field-meta.xml
<CustomField>
    <fullName>loan__Paid_Fees__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Paid Fees</description>
    <inlineHelpText>Paid Fees</inlineHelpText>
    <label>Paid Fees</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/loan__Repayment_Schedule__c/fields/loan__Paid_Interest__c.field-meta.xml
<CustomField>
    <fullName>loan__Paid_Interest__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Paid Interest</description>
    <inlineHelpText>Paid Interest</inlineHelpText>
    <label>Paid Interest</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/loan__Repayment_Schedule__c/fields/loan__Paid_Interest_On_Overdue__c.field-meta.xml
<CustomField>
    <fullName>loan__Paid_Interest_On_Overdue__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Paid Interest On Overdue Amount</description>
    <inlineHelpText>Paid Interest On Overdue Amount</inlineHelpText>
    <label>Paid Interest On Overdue</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/loan__Repayment_Schedule__c/fields/loan__Paid_Principal__c.field-meta.xml
<CustomField>
    <fullName>loan__Paid_Principal__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Paid Principal</description>
    <inlineHelpText>Paid Principal</inlineHelpText>
    <label>Paid Principal</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/loan__Repayment_Schedule__c/fields/loan__Paid_Total__c.field-meta.xml
<CustomField>
    <fullName>loan__Paid_Total__c</fullName>
    <formula>loan__Total_Paid_Fees__c +  loan__Paid_Interest__c +  loan__Paid_Principal__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Paid Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/loan__Repayment_Schedule__c/fields/loan__Past_Due_Date__c.field-meta.xml
<CustomField>
    <fullName>loan__Past_Due_Date__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Past Due Date</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/loan__Repayment_Schedule__c/fields/loan__Total_Installment__c.field-meta.xml
<CustomField>
    <fullName>loan__Total_Installment__c</fullName>
    <formula>loan__Due_Principal__c + loan__Due_Interest__c + loan__Total_Due_Fees__c +  loan__Due_Interest_On_Overdue__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Installment</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/loan__Repayment_Schedule__c/fields/loan__Transaction_Amount__c.field-meta.xml
<CustomField>
    <fullName>loan__Transaction_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <description>This represents the amount paid by the borrower towards this repayment schedule.</description>
    <inlineHelpText>This represents the amount paid by the borrower towards this repayment schedule.</inlineHelpText>
    <label>Transaction Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/loan__Repayment_Schedule__c/fields/loan__Unpaid_Fees__c.field-meta.xml
<CustomField>
    <fullName>loan__Unpaid_Fees__c</fullName>
    <formula>loan__Total_Due_Fees__c - loan__Total_Paid_Fees__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Unpaid Fees</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/loan__Repayment_Schedule__c/fields/loan__Unpaid_Installment__c.field-meta.xml
<CustomField>
    <fullName>loan__Unpaid_Installment__c</fullName>
    <formula>loan__Unpaid_Principal__c + loan__Unpaid_Interest__c + loan__Unpaid_Fees__c + loan__Unpaid_Overdue_Interest__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Unpaid Installment</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/loan__Repayment_Schedule__c/fields/loan__Unpaid_Interest__c.field-meta.xml
<CustomField>
    <fullName>loan__Unpaid_Interest__c</fullName>
    <formula>loan__Due_Interest__c  -  loan__Paid_Interest__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Unpaid Interest</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/loan__Repayment_Schedule__c/fields/loan__Unpaid_Overdue_Interest__c.field-meta.xml
<CustomField>
    <fullName>loan__Unpaid_Overdue_Interest__c</fullName>
    <formula>loan__Due_Interest_On_Overdue__c - loan__Paid_Interest_On_Overdue__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Unpaid Overdue Interest</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/loan__Repayment_Schedule__c/fields/loan__Unpaid_Principal__c.field-meta.xml
<CustomField>
    <fullName>loan__Unpaid_Principal__c</fullName>
    <formula>loan__Due_Principal__c - loan__Paid_Principal__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Unpaid Principal</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/classes/MW_RetrieveRSbyContractId.cls
@RestResource(urlMapping='/repayment-schedule/contract-id/*')
global with sharing class MW_RetrieveRSbyContractId {
    @HttpGet
    global static void MW_RetrieveRSbyContractId() {
        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;
        try {
            String contractId = req.params.get('contract-id');
            if (String.isBlank(contractId)) {
                res.statusCode = 400;
                res.responseBody = Blob.valueOf('contract id is required');
                return;
            }

            List<Loan__Repayment_Schedule__c> repaymentSchedules = [
                SELECT
                Id,
                ReplayId,
                Name,
                CreatedDate,
                CreatedById,
                LastModifiedDate,
                LastModifiedById,
                loan__Loan_Account__c,
                loan__Balance__c,
                loan__Barcode_Subtype__c,
                loan__Barcode_Type__c,
                loan__Date_Paid__c,
                loan__Due_Amount__c,
                loan__Due_Date__c,
                loan__Due_Interest_On_Overdue__c,
                loan__Due_Interest__c,
                loan__Due_Principal__c,
                loan__Id__c,
                loan__Installment_Snapshot__c,
                loan__Interest_Accrued_Not_Due__c,
                loan__Is_Archived__c,
                loan__Is_Billed__c,
                loan__Is_Partially_Paid__c,
                loan__Paid_Fees__c,
                loan__Paid_Interest_On_Overdue__c,
                loan__Paid_Interest__c,
                loan__Paid_Principal__c,
                loan__Paid_Total__c,
                loan__Past_Due_Date__c,
                loan__Total_Installment__c,
                loan__Transaction_Amount__c,
                loan__Unpaid_Fees__c,
                loan__Unpaid_Installment__c,
                loan__Unpaid_Interest__c,
                loan__Unpaid_Overdue_Interest__c,
                loan__Unpaid_Principal__c,
                loan__isPaid__c,
                loan__Total_Due_Fees__c,
                loan__Total_Paid_Fees__c,
                loan__Archived__c,
                loan__Is_Posted__c,
                loan__Loan_Disbursal_Transaction__c,
                loan__Master_Archive_Object__c,
                loan__Summary_Record_Id__c,
                loan__Summary__c,
                loan__Waived_Interest__c,
                loan__Interest_Rounding_Error__c,
                loan__Due_Fee1__c,
                loan__Is_Fee_Posted__c,
                loan__TDS_Amount_Paid__c,
                loan__TDS_Amount__c,
                External_Id__c,
                isBilledwasUnchecked__c,
                isDeleted
                FROM Loan__Repayment_Schedule__c
                WHERE loan__Loan_Account__c = :contractId 
            ];
            res.statusCode = 200;
            res.responseBody = Blob.valueOf(JSON.serialize(repaymentSchedules));
        }
        catch (Exception e) {
            res.statusCode = 500;
            res.responseBody = Blob.valueOf(e.getMessage());
        }
    }
}