unpackaged/main/default/objects/loan__Loan_Account__c/loan__Loan_Account__c.object-meta.xml
<CustomObject>
    <description>Lending Account</description>
    <label>CL Contract</label>
    <nameField>
        <displayFormat>LAI-{00000000}</displayFormat>
        <label>CL Contract ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CL Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/loan__Loan_Account__c/fields/Placement_Status__c.field-meta.xml
<CustomField>
    <fullName>Placement_Status__c</fullName>
    <label>Placement Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Placed - HM</fullName>
            </value>
            <value>
                <fullName>Placed - ACU</fullName>
            </value>
            <value>
                <fullName>Placed - ARS</fullName>
            </value>
            <value>
                <fullName>Placed - Remitter (Pre-CO)</fullName>
            </value>
            <value>
                <fullName>Placed - Remitter (Post-CO)</fullName>
            </value>
            <value>
                <fullName>Placed - TrueAccord</fullName>
            </value>
            <value>
                <fullName>Placed - Remitter</fullName>
                <isActive>false</isActive>
                <label>Placed - Remitter</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/Placement_Status_EndDate__c.field-meta.xml
<CustomField>
    <fullName>Placement_Status_EndDate__c</fullName>
    <label>Placement Status EndDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/Placement_Status_StartDate__c.field-meta.xml
<CustomField>
    <fullName>Placement_Status_StartDate__c</fullName>
    <label>Placement Status StartDate</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/classes/MW_LoanAccountTriggerHandler.cls
public class MW_LoanAccountTriggerHandler {
    
    public static void updatePlacedStatusFields(List<loan__Loan_Account__c> newList, map<Id,loan__Loan_Account__c> oldMap){
        try{
            Timezone tz = Timezone.getTimeZone('America/Los_Angeles');
            
            for(loan__Loan_Account__c newLoan : newList){
                loan__Loan_Account__c oldLoan = oldMap.get(newLoan.Id);
                if(oldLoan.Placement_Status__c == null && oldLoan.Placement_Status__c != newLoan.Placement_Status__c){
                    newLoan.Placement_Status_StartDate__c = newLoan.Placement_Status__c + '  ' + DateTime.newInstance(System.Now().getTime() + tz.getOffset(System.Now()));
                }else if(oldLoan.Placement_Status__c != null && oldLoan.Placement_Status__c != newLoan.Placement_Status__c){
                    newLoan.Placement_Status_StartDate__c = newLoan.Placement_Status__c + '  ' + DateTime.newInstance(System.Now().getTime() + tz.getOffset(System.Now()));
                    newLoan.Placement_Status_EndDate__c = oldLoan.Placement_Status__c + '  ' + DateTime.newInstance(System.Now().getTime() + tz.getOffset(System.Now()));
                }
            }
        }catch(Exception exe){
            MW_LogUtility.error('MW_LoanAccountTriggerHandler', '', '', 'updatePlacedStatusFields', exe);
        }
    }
}