unpackaged/main/default/objects/loan__Loan_Account__c/loan__Loan_Account__c.object-meta.xml
<CustomObject>
    <description>Lending Account</description>
    <label>CL Contract</label>
    <nameField>
        <displayFormat>LAI-{00000000}</displayFormat>
        <label>CL Contract ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CL Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/loan__Loan_Account__c/fields/Skipped_a_Pay__c.field-meta.xml
<CustomField>
    <fullName>Skipped_a_Pay__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Flag to indicate if the most recent loan modification activity on the loan is a skip-a-pay.  This flag should be settable manually or by the batch skip-a-pay upload process</inlineHelpText>
    <label>Skipped a Pay</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/classes/MW_SkipAPayControllerTest.cls
@isTest
private class MW_SkipAPayControllerTest {
    @testSetup
    static void dataSetup() {
        //Todo
        loan__Loan_Account__c loan = new loan__Loan_Account__c(
            id = 'Testing'
        );
        insert loan;
    }

    static testMethod void testPost() {
        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();             
        req.requestURI = '/services/apexrest/skipapay/';
        req.httpMethod = 'POST';
        req.requestBody = Blob.valueOf('{ "loanId": "Testing", "numberOfSkips": "4"}');
        RestContext.request = req;
        RestContext.response= res;
        MW_SkipAPayController.SkipAPayController();
        loan__Loan_Account__c loan = [ SELECT Id, Name, Skipped_a_Pay__c FROM loan__Loan_Account__c WHERE Id = 'Testing' ];
        system.assertEquals(loan.Skipped_a_Pay__c, true, 'passed');
    }
}