unpackaged/main/default/objects/loan__Batch_Process_Log__c/loan__Batch_Process_Log__c.object-meta.xml
<CustomObject>
    <label>Batch Process Log</label>
    <nameField>
        <label>Apex Batch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Batch Process Log</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/loan__Batch_Process_Log__c/fields/loan__Batch_Id__c.field-meta.xml
<CustomField>
    <fullName>loan__Batch_Id__c</fullName>
    <label>Batch Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/loan__Batch_Process_Log__c/fields/loan__Branch__c.field-meta.xml
<CustomField>
    <fullName>loan__Branch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Branch</label>
    <referenceTo>loan__Office_Name__c</referenceTo>
    <relationshipLabel>Batch Process Log</relationshipLabel>
    <relationshipName>Batch_Process_Log</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/loan__Batch_Process_Log__c/fields/loan__Log_Level__c.field-meta.xml
<CustomField>
    <fullName>loan__Log_Level__c</fullName>
    <description>An indicator of level of logging</description>
    <label>Log Level</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ERROR</fullName>
                <default>true</default>
                <label>ERROR</label>
            </value>
            <value>
                <fullName>DEBUG</fullName>
            </value>
            <value>
                <fullName>INFO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/loan__Batch_Process_Log__c/fields/loan__Message__c.field-meta.xml
<CustomField>
    <fullName>loan__Message__c</fullName>
    <label>Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/loan__Loan_Account__c/loan__Loan_Account__c.object-meta.xml
<CustomObject>
    <description>Lending Account</description>
    <label>CL Contract</label>
    <nameField>
        <displayFormat>LAI-{00000000}</displayFormat>
        <label>CL Contract ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CL Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/loan__Loan_Account__c/fields/loan__Branch__c.field-meta.xml
<CustomField>
    <fullName>loan__Branch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The branch name of the loan account.</inlineHelpText>
    <label>Branch</label>
    <referenceTo>loan__Office_Name__c</referenceTo>
    <relationshipName>Loan_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/loan__Office_Name__c/loan__Office_Name__c.object-meta.xml
<CustomObject>
    <description>Name of the office</description>
    <label>Company</label>
    <nameField>
        <label>Company</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/loan__Office_Name__c/fields/loan__Current_System_Date__c.field-meta.xml
<CustomField>
    <fullName>loan__Current_System_Date__c</fullName>
    <label>Current System Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/classes/LoanRescheduleJob.cls
/*******************************************************************************************************
 * 
 * @author Anusha
 * 
 * This class is to run reschedule job from CL contract details page and also from list view of CL contracts
 * This generates new amortization schedule in case of advance payment of loan...etc for both single and multiple contracts
 * LoanRescheduleJob of managed package is called interally.
 * 
 *********************************************************************************************************/

global class LoanRescheduleJob {
    Webservice static void runRescheduleJob(List<Id> LoanId)
    {
        Boolean submitNextJob = False;
        Integer batchSize = 1;
        Set<Id> loanIDs = new Set<Id>();
        loanIDs.addall(LoanId);
        loan__Batch_Process_Log__c batch = new loan__Batch_Process_Log__c();
        try{        
            List<loan__Loan_Account__c> loanAcc = [Select Id,loan__Branch__r.loan__Current_System_Date__c from loan__Loan_Account__c where Id in:LoanId];
            Date systemDate = loanAcc.get(0).loan__Branch__r.loan__Current_System_Date__c;
            loan.LoanRescheduleJob resc = new loan.LoanRescheduleJob(systemDate,loanIDs,submitNextJob,batchSize);
            Database.executebatch(resc,1);
        }catch(Exception e){
            System.debug('Batch processing failed with exception: '+e.getMessage());
            batch.loan__Log_Level__c = 'ERROR';
            batch.loan__Message__c = 'Rescheduling failed for one or more loans in ::'+ loanIDs + '. :: ERROR :: '+e.getMessage() + ' :: StackTrace ::' +e.getStackTraceString() ;
            batch.loan__Batch_Id__c = 'LoanRescheduleJob';
            insert batch;
        }
        System.debug('Batch processing completed for loan ids: '+loanIDs);
    }
    
}