unpackaged/main/default/objects/loan__Batch_Process_Log__c/loan__Batch_Process_Log__c.object-meta.xml
<CustomObject>
    <label>Batch Process Log</label>
    <nameField>
        <label>Apex Batch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Batch Process Log</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/loan__Batch_Process_Log__c/fields/loan__Batch_Id__c.field-meta.xml
<CustomField>
    <fullName>loan__Batch_Id__c</fullName>
    <label>Batch Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/loan__Batch_Process_Log__c/fields/loan__Log_Level__c.field-meta.xml
<CustomField>
    <fullName>loan__Log_Level__c</fullName>
    <description>An indicator of level of logging</description>
    <label>Log Level</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ERROR</fullName>
                <default>true</default>
                <label>ERROR</label>
            </value>
            <value>
                <fullName>DEBUG</fullName>
            </value>
            <value>
                <fullName>INFO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/loan__Batch_Process_Log__c/fields/loan__Message__c.field-meta.xml
<CustomField>
    <fullName>loan__Message__c</fullName>
    <label>Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/loan__Loan_Account__c/loan__Loan_Account__c.object-meta.xml
<CustomObject>
    <description>Lending Account</description>
    <label>CL Contract</label>
    <nameField>
        <displayFormat>LAI-{00000000}</displayFormat>
        <label>CL Contract ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CL Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/loan__Loan_Account__c/fields/loan__Accrual_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>loan__Accrual_Start_Date__c</fullName>
    <description>The date from which interest accrual starts</description>
    <inlineHelpText>The date from which interest accrual starts</inlineHelpText>
    <label>Accrual Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/loan__Loan_Account__c/fields/loan__Interest_Accrued_Not_Due__c.field-meta.xml
<CustomField>
    <fullName>loan__Interest_Accrued_Not_Due__c</fullName>
    <defaultValue>0.0</defaultValue>
    <description>This field gets updated on Payment Date. It is the accrued interest that is posted on the account.</description>
    <inlineHelpText>Interest balance as of last accrual date.</inlineHelpText>
    <label>Interest Accrued</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/loan__Loan_Account__c/fields/loan__Interest_Remaining__c.field-meta.xml
<CustomField>
    <fullName>loan__Interest_Remaining__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Unpaid Interest, accrued till last accrual date.</description>
    <inlineHelpText>Unpaid Interest, accrued till last accrual date.</inlineHelpText>
    <label>Interest Remaining</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/loan__Loan_Account__c/fields/loan__Last_Accrual_Date__c.field-meta.xml
<CustomField>
    <fullName>loan__Last_Accrual_Date__c</fullName>
    <description>Last accrual Date on loan account</description>
    <inlineHelpText>The date on which Interest was computed and posted on the Account.</inlineHelpText>
    <label>Last Accrual Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/loan__Other_Transaction__c/loan__Other_Transaction__c.object-meta.xml
<CustomObject>
    <label>Other Loan Transaction</label>
    <nameField>
        <displayFormat>OLTID-{0000000000}</displayFormat>
        <label>Other Transaction ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Other Loan Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/loan__Other_Transaction__c/fields/loan__Loan_Account__c.field-meta.xml
<CustomField>
    <fullName>loan__Loan_Account__c</fullName>
    <label>Loan Account</label>
    <referenceTo>loan__Loan_Account__c</referenceTo>
    <relationshipLabel>Other Loan Transactions</relationshipLabel>
    <relationshipName>Other_Loan_Transactions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/classes/CLS_LPTReversalJobV1.cls
public class CLS_LPTReversalJobV1 implements Database.Batchable<sObject>,Database.AllowsCallouts{
    
    private List<String> loanContract;
    loan__Batch_Process_Log__c batch = new loan__Batch_Process_Log__c();
    
    public CLS_LPTReversalJobV1(List<String> loanContract){
        this.loanContract = loanContract;
    }
    
    public Database.QueryLocator start(Database.BatchableContext bc){
        String query = '';
        if(loanContract!=null && loanContract.size() > 0){
            String contractNamesStr = '';
            for (String contractName : loanContract) {
                contractNamesStr = contractNamesStr + '\'' + String.escapeSingleQuotes(contractName) + '\'' + ',';
            }
            contractNamesStr = contractNamesStr.substring(0, contractNamesStr.length() - 1);  
            query = 'SELECT Id,Name,loan__Last_Accrual_Date__c,loan__Accrual_Start_Date__c,loan__Interest_Remaining__c,'+
                'loan__Interest_Accrued_Not_Due__c,(Select Id,Name FROM loan__Other_Loan_Transactions__r) FROM loan__Loan_Account__c WHERE Name IN ('+contractNamesStr+')';
        }
        
        System.debug(LoggingLevel.ERROR, 'query in initialize : ' + query);
        return Database.getQueryLocator(query);
    }
    
    public void execute(Database.BatchableContext bc, List<sObject> scope){
        Savepoint sp = database.setsavepoint();
        
        List<loan__Loan_Account__c> loanAccountList = (List<loan__Loan_Account__c>)scope;
        
        for(loan__Loan_Account__c loan:loanAccountList){
            System.debug(logginglevel.error, 'Processing Loan :: '+loan.name);
            try{
                //CLS_LPTReversalJobHandler handler = new CLS_LPTReversalJobHandler(loan);
                CLS_LPTReversalJobHandler.LPTReversal(loan);
            }catch(exception e){
                database.rollback(sp); 
                System.debug(logginglevel.ERROR,'LPT Reversal failed for :'+loan.Name);
                batch.loan__Log_Level__c = 'ERROR';
                batch.loan__Message__c = 'LPT Reversal failed for ::'+ loan.Name + '. :: ERROR :: '+e.getMessage() + ' :: StackTrace ::' +e.getStackTraceString() ;
                batch.loan__Batch_Id__c = 'LPTReversalJob';
                insert batch;
            } 
        }
    }
    
    public void finish(Database.BatchableContext bc){} 
    
}