unpackaged/main/default/objects/Account/fields/Account_External_ID__c.field-meta.xml
<CustomField>
    <fullName>Account_External_ID__c</fullName>
    <description>Account External ID from Legacy system. For DM purpose</description>
    <externalId>true</externalId>
    <label>Account External ID</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Borrower_s_Email__c.field-meta.xml
<CustomField>
    <fullName>Borrower_s_Email__c</fullName>
    <description>/*Created By Nupur */
For Email Alert</description>
    <formula>IF( RecordType.Name='Member',ints__Email__c , Null)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Borrower's Email</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/cnotify__Email__c.field-meta.xml
<CustomField>
    <fullName>cnotify__Email__c</fullName>
    <label>Email</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/ints__Yodlee_Password__c.field-meta.xml
<CustomField>
    <fullName>ints__Yodlee_Password__c</fullName>
    <description>Password for Yodlee Username.</description>
    <label>Yodlee_Password</label>
    <length>100</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/ints__Yodlee_Username__c.field-meta.xml
<CustomField>
    <fullName>ints__Yodlee_Username__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Username registered with Yodlee. This Username can have multiple bank accounts linked with Yodlee.</description>
    <label>Yodlee Username</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Account/fields/Number_of_Days__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Days__c</fullName>
    <label>Number of Days</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Investor.recordType-meta.xml
<RecordType>
    <fullName>Investor</fullName>
    <active>true</active>
    <label>Investor</label>
</RecordType>

unpackaged/main/default/objects/genesis__Applications__c/genesis__Applications__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{0000000000}</displayFormat>
        <label>Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/genesis__Applications__c/fields/Application_Start_DateV2__c.field-meta.xml
<CustomField>
    <fullName>Application_Start_DateV2__c</fullName>
    <label>Application Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/genesis__Applications__c/fields/Borrower_s_Email__c.field-meta.xml
<CustomField>
    <fullName>Borrower_s_Email__c</fullName>
    <description>/*Created By Nupur */ 
For Email Alert</description>
    <label>Borrower's Email</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/genesis__Applications__c/fields/DocuSignFlag__c.field-meta.xml
<CustomField>
    <fullName>DocuSignFlag__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Checked - DocuSign Email sent</description>
    <label>DocuSignFlag</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/genesis__Applications__c/fields/genesis__Account__c.field-meta.xml
<CustomField>
    <fullName>genesis__Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Applications_account</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/genesis__Applications__c/fields/genesis__Draw_Period_End_Date__c.field-meta.xml
<CustomField>
    <fullName>genesis__Draw_Period_End_Date__c</fullName>
    <label>Draw Period End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/genesis__Applications__c/fields/genesis__Due_Day__c.field-meta.xml
<CustomField>
    <fullName>genesis__Due_Day__c</fullName>
    <description>dueDay field.</description>
    <inlineHelpText>If Due Day field is null, then by default it will have Expected First Payment Date day value</inlineHelpText>
    <label>Due_Day</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/genesis__Applications__c/fields/genesis__Expected_First_Payment_Date__c.field-meta.xml
<CustomField>
    <fullName>genesis__Expected_First_Payment_Date__c</fullName>
    <label>Expected First Payment Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/genesis__Applications__c/fields/genesis__Expected_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>genesis__Expected_Start_Date__c</fullName>
    <label>Expected Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/genesis__Applications__c/fields/genesis__Funding_in_Tranches__c.field-meta.xml
<CustomField>
    <fullName>genesis__Funding_in_Tranches__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Funding in Tranches</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/genesis__Applications__c/fields/genesis__Status__c.field-meta.xml
<CustomField>
    <fullName>genesis__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>APPROVED - APPROVED</fullName>
            </value>
            <value>
                <fullName>APPROVED - CONVERTED TO CONTRACT</fullName>
            </value>
            <value>
                <fullName>APPROVED - DOCUMENT CHECK</fullName>
            </value>
            <value>
                <fullName>NEW - CREDIT PULLED</fullName>
            </value>
            <value>
                <fullName>NEW - ENTERED</fullName>
                <default>true</default>
                <label>NEW - ENTERED</label>
            </value>
            <value>
                <fullName>NEW - IN CREDIT CHECK</fullName>
            </value>
            <value>
                <fullName>NEW - IN REVIEW</fullName>
            </value>
            <value>
                <fullName>NEW - PRICING GENERATED</fullName>
            </value>
            <value>
                <fullName>NEW - SCORECARD GENERATED</fullName>
            </value>
            <value>
                <fullName>NEW - CHECKLIST GENERATED</fullName>
            </value>
            <value>
                <fullName>NEW - VEHICLE VALUATION REQUIRED</fullName>
            </value>
            <value>
                <fullName>REJECTED</fullName>
            </value>
            <value>
                <fullName>PULL CREDIT</fullName>
            </value>
            <value>
                <fullName>Default Documents</fullName>
            </value>
            <value>
                <fullName>offer_accepted</fullName>
            </value>
            <value>
                <fullName>offer_shown</fullName>
            </value>
            <value>
                <fullName>kba_success</fullName>
            </value>
            <value>
                <fullName>kba_fail</fullName>
            </value>
            <value>
                <fullName>agent_document_verification_pending</fullName>
            </value>
            <value>
                <fullName>agent_verification_pending</fullName>
            </value>
            <value>
                <fullName>agent_verified</fullName>
            </value>
            <value>
                <fullName>docusign_loan_docs_sent</fullName>
            </value>
            <value>
                <fullName>docusign_loan_docs_complete</fullName>
            </value>
            <value>
                <fullName>pre_funding</fullName>
            </value>
            <value>
                <fullName>Approved for funding</fullName>
            </value>
            <value>
                <fullName>funded</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Stacker_Check_Passed</fullName>
            </value>
            <value>
                <fullName>Redecision_Required</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/genesis__Applications__c/fields/Number_of_days__c.field-meta.xml
<CustomField>
    <fullName>Number_of_days__c</fullName>
    <label>Number of days</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/ints__Yodlee_Cobrand_Credentials__c/ints__Yodlee_Cobrand_Credentials__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Yodlee Cobrand Credentials</label>
</CustomObject>

unpackaged/main/default/objects/ints__Yodlee_Cobrand_Credentials__c/fields/FromDate_Attribute_value__c.field-meta.xml
<CustomField>
    <fullName>FromDate_Attribute_value__c</fullName>
    <inlineHelpText>Specify the number of days from when you want to get the Transactions.</inlineHelpText>
    <label>FromDate Attribute value</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/ints__Yodlee_Cobrand_Credentials__c/fields/ints__APP_ID__c.field-meta.xml
<CustomField>
    <fullName>ints__APP_ID__c</fullName>
    <label>APP ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ints__Yodlee_Cobrand_Credentials__c/fields/ints__APP_Secret__c.field-meta.xml
<CustomField>
    <fullName>ints__APP_Secret__c</fullName>
    <label>APP Secret</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ints__Yodlee_Cobrand_Credentials__c/fields/ints__Application_Key__c.field-meta.xml
<CustomField>
    <fullName>ints__Application_Key__c</fullName>
    <label>Application Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ints__Yodlee_Cobrand_Credentials__c/fields/ints__Auto_Register_User__c.field-meta.xml
<CustomField>
    <fullName>ints__Auto_Register_User__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Auto Register User</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/ints__Yodlee_Cobrand_Credentials__c/fields/ints__Callback_URL__c.field-meta.xml
<CustomField>
    <fullName>ints__Callback_URL__c</fullName>
    <label>Callback URL</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ints__Yodlee_Cobrand_Credentials__c/fields/ints__Cobrand_id__c.field-meta.xml
<CustomField>
    <fullName>ints__Cobrand_id__c</fullName>
    <label>Cobrand Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ints__Yodlee_Cobrand_Credentials__c/fields/ints__Cobrand_Password__c.field-meta.xml
<CustomField>
    <fullName>ints__Cobrand_Password__c</fullName>
    <label>Cobrand Password</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ints__Yodlee_Cobrand_Credentials__c/fields/ints__Cobrand_Username__c.field-meta.xml
<CustomField>
    <fullName>ints__Cobrand_Username__c</fullName>
    <label>Cobrand Username</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ints__Yodlee_Cobrand_Credentials__c/fields/ints__Node_URL__c.field-meta.xml
<CustomField>
    <fullName>ints__Node_URL__c</fullName>
    <label>Node URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ints__Yodlee_Cobrand_Credentials__c/fields/ints__Rest_URL__c.field-meta.xml
<CustomField>
    <fullName>ints__Rest_URL__c</fullName>
    <label>Rest URL</label>
    <type>Url</type>
</CustomField>

unpackaged/main/default/objects/ints__Yodlee_Cobrand_Credentials__c/fields/ints__Soap_URL__c.field-meta.xml
<CustomField>
    <fullName>ints__Soap_URL__c</fullName>
    <label>Soap URL</label>
    <type>Url</type>
</CustomField>

unpackaged/main/default/objects/ints__Yodlee_User_Credentials__c/ints__Yodlee_User_Credentials__c.object-meta.xml
<CustomObject>
    <label>Yodlee User Credentials</label>
    <nameField>
        <displayFormat>YUC-{00000000}</displayFormat>
        <label>Yodlee User Credentials Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Yodlee User Credentials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ints__Yodlee_User_Credentials__c/fields/ints__Account__c.field-meta.xml
<CustomField>
    <fullName>ints__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Yodlee User Credentials</relationshipLabel>
    <relationshipName>Yodlee_User_Credentials</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ints__Yodlee_User_Credentials__c/fields/ints__Yodlee_Password__c.field-meta.xml
<CustomField>
    <fullName>ints__Yodlee_Password__c</fullName>
    <label>Yodlee Password</label>
    <length>100</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <required>true</required>
    <type>EncryptedText</type>
</CustomField>

unpackaged/main/default/objects/ints__Yodlee_User_Credentials__c/fields/ints__Yodlee_Username__c.field-meta.xml
<CustomField>
    <fullName>ints__Yodlee_Username__c</fullName>
    <label>Yodlee Username</label>
    <length>100</length>
    <maskChar>asterisk</maskChar>
    <maskType>lastFour</maskType>
    <required>true</required>
    <type>EncryptedText</type>
</CustomField>

unpackaged/main/default/classes/TestYodleeTransactionAPICallout.cls
@isTest
global class TestYodleeTransactionAPICallout{

    public static TestMethod void TestMethod1(){
        ints__Yodlee_Cobrand_Credentials__c ycc = new ints__Yodlee_Cobrand_Credentials__c();
        ycc.ints__APP_ID__c = '10003600';
        //ycc.ints__Application_Key__c = 
        //ycc.ints__APP_Secret__c =
        //ycc.ints__Auto_Register_User__c = 
        //ycc.ints__Callback_URL__c =
        ycc.ints__Cobrand_id__c = '4410018556';
        ycc.ints__Cobrand_Password__c = 'fpoie176bPIOY!T';
        ycc.ints__Cobrand_Username__c = 'payoff';
        ycc.FromDate_Attribute_value__c = 1100;
        ycc.ints__Node_URL__c = 'https://yieapnodestage.yodlee.com/authenticate/payoff/?channelAppName=yisandbox';
        ycc.ints__Rest_URL__c = 'https://stage.api.yodlee.com/ysl/payoff/v1/';
        ycc.ints__Soap_URL__c = 'https://stage.api.yodlee.com/ysl/payoff/v1/';
        
        insert  ycc;
        Test.startTest();
        
        YodleeTransactionAPICallOut.getCobSession();
        
        Test.stopTest();
    }
    
    public static TestMethod void TestMethod2(){
        
        ints__Yodlee_Cobrand_Credentials__c ycc = new ints__Yodlee_Cobrand_Credentials__c();
        ycc.ints__APP_ID__c = '10003600';
        //ycc.ints__Application_Key__c = 
        //ycc.ints__APP_Secret__c =
        //ycc.ints__Auto_Register_User__c = 
        //ycc.ints__Callback_URL__c =
        ycc.ints__Cobrand_id__c = '4410018556';
        ycc.ints__Cobrand_Password__c = 'fpoie176bPIOY!T';
        ycc.ints__Cobrand_Username__c = 'payoff';
        ycc.FromDate_Attribute_value__c = 1100;
        ycc.ints__Node_URL__c = 'https://yieapnodestage.yodlee.com/authenticate/payoff/?channelAppName=yisandbox';
        ycc.ints__Rest_URL__c = 'https://stage.api.yodlee.com/ysl/payoff/v1/';
        ycc.ints__Soap_URL__c = 'https://stage.api.yodlee.com/ysl/payoff/v1/';
        
        insert  ycc;
        
        Account acc = new Account();
        acc.name = 'Test Yodlee Account';
        acc.Account_External_ID__c = 'Yodlee';
        acc.cnotify__Email__c = 'no-reply@testorganization.com';
        insert acc;
        
        //Creating Application
        genesis__Applications__c app= new genesis__Applications__c(
                                            genesis__Due_Day__c = 20,
                                            genesis__Expected_First_Payment_Date__c = system.Today(),
                                            genesis__Expected_Start_Date__c = system.Today(),
                                            genesis__Funding_in_Tranches__c = true,
                                            Borrower_s_Email__c = null,
                                            genesis__Account__c = acc.Id,
                                            Application_Start_DateV2__c = system.Today(),
                                            DocuSignFlag__c=true,
                                            genesis__Status__c = 'agent_verified',
                                            genesis__Draw_Period_End_Date__c = system.Today(),
            								Number_of_days__c = 30
                                            );
        insert app;
        System.assertEquals(null,app.Borrower_s_Email__c,'Borrower Email is not null');
        
        Test.startTest();
        
        YodleeTransactionAPICallOut.UserToken(acc.Id);
        YodleeTransactionAPICallOut.deleteYodleeTxn(acc.Id,app.id);
        
        Test.stopTest();
    }
    
    public static TestMethod void TestMethod3(){
        ints__Yodlee_Cobrand_Credentials__c ycc = new ints__Yodlee_Cobrand_Credentials__c();
        ycc.ints__APP_ID__c = '10003600';
        //ycc.ints__Application_Key__c = 
        //ycc.ints__APP_Secret__c =
        //ycc.ints__Auto_Register_User__c = 
        //ycc.ints__Callback_URL__c =
        ycc.ints__Cobrand_id__c = '4410018556';
        ycc.ints__Cobrand_Password__c = 'fpoie176bPIOY!T';
        ycc.ints__Cobrand_Username__c = 'payoff';
        ycc.FromDate_Attribute_value__c = 1100;
        ycc.ints__Node_URL__c = 'https://yieapnodestage.yodlee.com/authenticate/payoff/?channelAppName=yisandbox';
        ycc.ints__Rest_URL__c = 'https://stage.api.yodlee.com/ysl/payoff/v1/';
        ycc.ints__Soap_URL__c = 'https://stage.api.yodlee.com/ysl/payoff/v1/';
        
        insert  ycc;
        
        Account acc = new Account();
        acc.name = 'Test Yodlee Account2';
        acc.Account_External_ID__c = 'Yodlee1';
        acc.cnotify__Email__c = 'no-reply@testorganization.com';
        insert acc;
        
        ints__Yodlee_User_Credentials__c userCred = new ints__Yodlee_User_Credentials__c();
        userCred.ints__Account__c = acc.Id;
        userCred.ints__Yodlee_Username__c = 'testuserName';
        userCred.ints__Yodlee_Password__c = 'testpassword';
        userCred.yodlee_Account_count__c  =1;
        insert userCred;
        
        Test.startTest();
        
        YodleeTransactionAPICallOut.UserToken(acc.Id);
        
        Test.stopTest();
    }
    
    public static TestMethod void testMethod4(){
        ints__Yodlee_Cobrand_Credentials__c ycc = new ints__Yodlee_Cobrand_Credentials__c();
        ycc.ints__APP_ID__c = '10003600';
        //ycc.ints__Application_Key__c = 
        //ycc.ints__APP_Secret__c =
        //ycc.ints__Auto_Register_User__c = 
        //ycc.ints__Callback_URL__c =
        ycc.ints__Cobrand_id__c = '4410018556';
        ycc.ints__Cobrand_Password__c = 'fpoie176bPIOY!T';
        ycc.ints__Cobrand_Username__c = 'payoff';
        ycc.FromDate_Attribute_value__c = 1100;
        ycc.ints__Node_URL__c = 'https://yieapnodestage.yodlee.com/authenticate/payoff/?channelAppName=yisandbox';
        ycc.ints__Rest_URL__c = 'https://stage.api.yodlee.com/ysl/payoff/v1/';
        ycc.ints__Soap_URL__c = 'https://stage.api.yodlee.com/ysl/payoff/v1/';
        
        insert  ycc;
        
        Account acc = new Account();
        acc.name = 'Test Yodlee Account';
        acc.Account_External_ID__c = 'Yodlee';
        acc.cnotify__Email__c = 'no-reply@testorganization.com';
        insert acc;
        
        
        ints__Yodlee_User_Credentials__c userCred = new ints__Yodlee_User_Credentials__c();
        userCred.ints__Account__c = acc.Id;
        userCred.ints__Yodlee_Username__c = 'testuserName';
        userCred.ints__Yodlee_Password__c = 'testpassword';
        userCred.yodlee_Account_count__c  =1;
        insert userCred;
        
        //Creating Application
        genesis__Applications__c app= new genesis__Applications__c(
                                            genesis__Due_Day__c = 20,
                                            genesis__Expected_First_Payment_Date__c = system.Today(),
                                            genesis__Expected_Start_Date__c = system.Today(),
                                            genesis__Funding_in_Tranches__c = true,
                                            Borrower_s_Email__c = null,
                                            genesis__Account__c = acc.Id,
                                            Application_Start_DateV2__c = system.Today(),
                                            DocuSignFlag__c=true,
                                            genesis__Status__c = 'agent_verified',
                                            genesis__Draw_Period_End_Date__c = system.Today()
                                            );
        insert app;
        System.assertEquals(null,app.Borrower_s_Email__c,'Borrower Email is not null');
        loan.GlobalLoanUtilFacade util = new loan.GlobalLoanUtilFacade();
        
        Test.startTest();
        
        
        Test.setMock(HttpCalloutMock.class, new MockYodleeTransactionAPICallOut1());
        YodleeTransactionAPICallOut.getTransactions(acc.Id,app.id,10);
        
        Test.stopTest();
    }
    
    public static TestMethod void testMethod5(){
         ints__Yodlee_Cobrand_Credentials__c ycc = new ints__Yodlee_Cobrand_Credentials__c();
        ycc.ints__APP_ID__c = '10003600';
        //ycc.ints__Application_Key__c = 
        //ycc.ints__APP_Secret__c =
        //ycc.ints__Auto_Register_User__c = 
        //ycc.ints__Callback_URL__c =
        ycc.ints__Cobrand_id__c = '4410018556';
        ycc.ints__Cobrand_Password__c = 'fpoie176bPIOY!T';
        ycc.ints__Cobrand_Username__c = 'payoff';
        ycc.FromDate_Attribute_value__c = 1100;
        ycc.ints__Node_URL__c = 'https://yieapnodestage.yodlee.com/authenticate/payoff/?channelAppName=yisandbox';
        ycc.ints__Rest_URL__c = 'https://stage.api.yodlee.com/ysl/payoff/v1/';
        ycc.ints__Soap_URL__c = 'https://stage.api.yodlee.com/ysl/payoff/v1/';
        
        insert  ycc;
        
        Account acc = new Account();
        acc.name = 'Test Yodlee Account';
        acc.Account_External_ID__c = 'Yodlee';
        acc.cnotify__Email__c = 'no-reply@testorganization.com';
        insert acc;
        
        //Creating Application
        genesis__Applications__c app= new genesis__Applications__c(
                                            genesis__Due_Day__c = 20,
                                            genesis__Expected_First_Payment_Date__c = system.Today(),
                                            genesis__Expected_Start_Date__c = system.Today(),
                                            genesis__Funding_in_Tranches__c = true,
                                            Borrower_s_Email__c = null,
                                            genesis__Account__c = acc.Id,
                                            Application_Start_DateV2__c = system.Today(),
                                            DocuSignFlag__c=true,
                                            genesis__Status__c = 'agent_verified',
                                            genesis__Draw_Period_End_Date__c = system.Today(),
            								Number_of_days__c = 10
                                            );
        insert app;
        System.assertEquals(null,app.Borrower_s_Email__c,'Borrower Email is not null');
        
        list<Yodlee_User_Transaction__c> yodleeTxn = new list<Yodlee_User_Transaction__c>();
        
        Yodlee_User_Transaction__c yodlee = new Yodlee_User_Transaction__c();
        
        for(integer i=0; i<3;i++){
            yodlee.Balance__c = 100;
            yodlee.Category__c = 'Test';
            yodlee.Yodlee_Account__c = acc.Id;
            yodleeTxn.add(yodlee);
        }
        
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new MockYodleeTransactionAPICallOut());
        YodleeTransactionAPICallOut.deleteYodleeTxn(acc.Id,app.id);
        Test.stopTest();
        
    }
    
   /* public static TestMethod void TestMethod6(){	//COMMENTED(LOS-63) function not needed
        ints__Yodlee_Cobrand_Credentials__c ycc = new ints__Yodlee_Cobrand_Credentials__c();
        ycc.ints__APP_ID__c = '10003600';
        //ycc.ints__Application_Key__c = 
        //ycc.ints__APP_Secret__c =
        //ycc.ints__Auto_Register_User__c = 
        //ycc.ints__Callback_URL__c =
        ycc.ints__Cobrand_id__c = '4410018556';
        ycc.ints__Cobrand_Password__c = 'fpoie176bPIOY!T';
        ycc.ints__Cobrand_Username__c = 'payoff';
        ycc.FromDate_Attribute_value__c = 1100;
        ycc.ints__Node_URL__c = 'https://yieapnodestage.yodlee.com/authenticate/payoff/?channelAppName=yisandbox';
        ycc.ints__Rest_URL__c = 'https://stage.api.yodlee.com/ysl/payoff/v1/';
        ycc.ints__Soap_URL__c = 'https://stage.api.yodlee.com/ysl/payoff/v1/';
        
        insert  ycc;
        
        Account acc = new Account();
        acc.name = 'Test Yodlee Account';
        acc.Account_External_ID__c = 'Yodlee';
        acc.cnotify__Email__c = 'no-reply@testorganization.com';
        insert acc;
        
        //Creating Application
        genesis__Applications__c app= new genesis__Applications__c(
                                            genesis__Due_Day__c = 20,
                                            genesis__Expected_First_Payment_Date__c = system.Today(),
                                            genesis__Expected_Start_Date__c = system.Today(),
                                            genesis__Funding_in_Tranches__c = true,
                                            Borrower_s_Email__c = null,
                                            genesis__Account__c = acc.Id,
                                            Application_Start_DateV2__c = system.Today(),
                                            DocuSignFlag__c=true,
                                            genesis__Status__c = 'agent_verified',
                                            genesis__Draw_Period_End_Date__c = system.Today(),
            								Number_of_days__c = 10
                                            );
        insert app;
        System.assertEquals(null,app.Borrower_s_Email__c,'Borrower Email is not null');
        
        ints__Yodlee_User_Credentials__c userCred = new ints__Yodlee_User_Credentials__c();
        userCred.ints__Account__c = acc.Id;
        userCred.ints__Yodlee_Username__c = 'testuserName';
        userCred.ints__Yodlee_Password__c = 'testpassword';
        userCred.yodlee_Account_count__c  =1;
        insert userCred;
        
        String leadsEndPoint = MW_Settings__c.getInstance().LEADS_FE_EndpointURL__c;	//temp
        
        Test.startTest();
        
        Test.setMock(HttpCalloutMock.class, new MockYodleeTransactionAPICallOut());
        String res = YodleeTransactionAPICallOut.getTransactions(acc.Id,app.id, Integer.valueof(app.Number_of_days__c));
        
        Test.stopTest();
    }
    public static TestMethod void TestMethod7(){
        ints__Yodlee_Cobrand_Credentials__c ycc = new ints__Yodlee_Cobrand_Credentials__c();
        ycc.ints__APP_ID__c = '10003600';
        //ycc.ints__Application_Key__c = 
        //ycc.ints__APP_Secret__c =
        //ycc.ints__Auto_Register_User__c = 
        //ycc.ints__Callback_URL__c =
        ycc.ints__Cobrand_id__c = '4410018556';
        ycc.ints__Cobrand_Password__c = 'fpoie176bPIOY!T';
        ycc.ints__Cobrand_Username__c = 'payoff';
        ycc.FromDate_Attribute_value__c = 1100;
        ycc.ints__Node_URL__c = 'https://yieapnodestage.yodlee.com/authenticate/payoff/?channelAppName=yisandbox';
        ycc.ints__Rest_URL__c = 'https://stage.api.yodlee.com/ysl/payoff/v1/';
        ycc.ints__Soap_URL__c = 'https://stage.api.yodlee.com/ysl/payoff/v1/';
        
        insert  ycc;
        
        Account acc = new Account();
        acc.name = 'Test Yodlee Account';
        acc.Account_External_ID__c = 'Yodlee';
        acc.cnotify__Email__c = 'no-reply@testorganization.com';
        insert acc;
        
        loan__Bank_Account__c ba = new loan__Bank_Account__c();
        ba.loan__Account__c = acc.id;
        ba.loan__Bank_Account_Number__c = 'XXXXXXXXXXX4802';
        ba.loan__Bank_Name__c = 'M&T Bank';
        ba.loan__Routing_Number__c = '022000046';
        ba.loan__ACH_Code__c = '081904808';
        ba.loan__Active__c = true;
        ba.Unmasked_Bank_Account_Number__c = '884895318794802';
        ba.loan__Account_Type__c = 'Savings';
        ba.loan__Account_Usage__c = 'Borrower/Investor Account';	//pallavi(LOS-63)
        insert ba;
        
        //Creating Application
        genesis__Applications__c app= new genesis__Applications__c(
                                            genesis__Due_Day__c = 20,
                                            genesis__Expected_First_Payment_Date__c = system.Today(),
                                            genesis__Expected_Start_Date__c = system.Today(),
                                            genesis__Funding_in_Tranches__c = true,
                                            Borrower_s_Email__c = null,
                                            genesis__Account__c = acc.Id,
                                            Application_Start_DateV2__c = system.Today(),
                                            DocuSignFlag__c=true,
                                            genesis__Status__c = 'agent_verified',
                                            genesis__Draw_Period_End_Date__c = system.Today()
                                            );
        insert app;
        System.assertEquals(null,app.Borrower_s_Email__c,'Borrower Email is not null');
        
        ints__Yodlee_User_Credentials__c userCred = new ints__Yodlee_User_Credentials__c();
        userCred.ints__Account__c = acc.Id;
        userCred.ints__Yodlee_Username__c = 'testuserName';
        userCred.ints__Yodlee_Password__c = 'testpassword';
        userCred.yodlee_Account_count__c  =1;
        insert userCred;
        
        Test.startTest();
        
        Test.setMock(HttpCalloutMock.class, new MockYodleeTransactionAPICallOut1());
        YodleeTransactionAPICallOut.getYodleeAccount(acc.Id,app.id);
        
        Test.stopTest();

   }*/
}