unpackaged/main/default/objects/Account/fields/Amount_Invested__c.field-meta.xml
<CustomField>
    <fullName>Amount_Invested__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Total loan amount allocated to investor. Field is updated by allocation process.</description>
    <inlineHelpText>Total loan amount allocated to investor. Field is updated by allocation process.</inlineHelpText>
    <label>Amount Invested</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Borrower_s_Email__c.field-meta.xml
<CustomField>
    <fullName>Borrower_s_Email__c</fullName>
    <description>/*Created By Nupur */
For Email Alert</description>
    <formula>IF( RecordType.Name='Member',ints__Email__c , Null)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Borrower's Email</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/cnotify__Email__c.field-meta.xml
<CustomField>
    <fullName>cnotify__Email__c</fullName>
    <label>Email</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Investor_Code__c.field-meta.xml
<CustomField>
    <fullName>Investor_Code__c</fullName>
    <label>Investor Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/loan__Investor__c.field-meta.xml
<CustomField>
    <fullName>loan__Investor__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Investor</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/loan__SOCIAL_SECURITY_NUMBER__c.field-meta.xml
<CustomField>
    <fullName>loan__SOCIAL_SECURITY_NUMBER__c</fullName>
    <label>SOCIAL_SECURITY_NUMBER</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Number_Of_Applications_Invested__c.field-meta.xml
<CustomField>
    <fullName>Number_Of_Applications_Invested__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Total number of applications allocated to investor LTD. Field is adjusted in allocations routine.</description>
    <inlineHelpText>Total number of applications allocated to investor LTD. Field is adjusted in allocations routine.</inlineHelpText>
    <label>Number Of Applications Invested</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/peer__Last_Name__c.field-meta.xml
<CustomField>
    <fullName>peer__Last_Name__c</fullName>
    <label>Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/CL_Document__c/CL_Document__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>CL_Generated Documents Names</description>
    <label>CL Document</label>
</CustomObject>

unpackaged/main/default/objects/CL_Document__c/fields/Doc1__c.field-meta.xml
<CustomField>
    <fullName>Doc1__c</fullName>
    <label>Doc1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/CL_Document__c/fields/Doc2__c.field-meta.xml
<CustomField>
    <fullName>Doc2__c</fullName>
    <inlineHelpText>TIL Document</inlineHelpText>
    <label>Doc2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/CL_Document__c/fields/Doc3__c.field-meta.xml
<CustomField>
    <fullName>Doc3__c</fullName>
    <label>Doc3</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/CL_Document__c/fields/UploadedBOX__c.field-meta.xml
<CustomField>
    <fullName>UploadedBOX__c</fullName>
    <label>UploadedBOX</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/genesis__Application_Document_Category__c/genesis__Application_Document_Category__c.object-meta.xml
<CustomObject>
    <label>Application Document Category</label>
    <nameField>
        <label>Application Document Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application Document Category</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/genesis__Application_Document_Category__c/fields/Borrower_s_Email__c.field-meta.xml
<CustomField>
    <fullName>Borrower_s_Email__c</fullName>
    <description>/* Created By Nupur */

------ For Email Alerts --pending_document_reminder.liquid</description>
    <label>Borrower's Email</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/genesis__Application_Document_Category__c/fields/genesis__Application__c.field-meta.xml
<CustomField>
    <fullName>genesis__Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>genesis__Applications__c</referenceTo>
    <relationshipLabel>Application Document Category</relationshipLabel>
    <relationshipName>Application_Document_Category</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/genesis__Application_Document_Category__c/fields/genesis__Status__c.field-meta.xml
<CustomField>
    <fullName>genesis__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>OPEN</fullName>
                <default>true</default>
                <label>OPEN</label>
            </value>
            <value>
                <fullName>SUBMITTED</fullName>
            </value>
            <value>
                <fullName>CLEARED</fullName>
            </value>
            <value>
                <fullName>REJECTED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/genesis__Application_Document_Category__c/fields/Investor_Code__c.field-meta.xml
<CustomField>
    <fullName>Investor_Code__c</fullName>
    <formula>genesis__Application__r.Investor__r.Investor_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Investor Code</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/genesis__Applications__c/genesis__Applications__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{0000000000}</displayFormat>
        <label>Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/genesis__Applications__c/fields/Application_Start_DateV2__c.field-meta.xml
<CustomField>
    <fullName>Application_Start_DateV2__c</fullName>
    <label>Application Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/genesis__Applications__c/fields/Borrower_s_Email__c.field-meta.xml
<CustomField>
    <fullName>Borrower_s_Email__c</fullName>
    <description>/*Created By Nupur */ 
For Email Alert</description>
    <label>Borrower's Email</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/genesis__Applications__c/fields/DocuSignFlag__c.field-meta.xml
<CustomField>
    <fullName>DocuSignFlag__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Checked - DocuSign Email sent</description>
    <label>DocuSignFlag</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/genesis__Applications__c/fields/genesis__Account__c.field-meta.xml
<CustomField>
    <fullName>genesis__Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Applications_account</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/genesis__Applications__c/fields/genesis__Draw_Period_End_Date__c.field-meta.xml
<CustomField>
    <fullName>genesis__Draw_Period_End_Date__c</fullName>
    <label>Draw Period End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/genesis__Applications__c/fields/genesis__Due_Day__c.field-meta.xml
<CustomField>
    <fullName>genesis__Due_Day__c</fullName>
    <description>dueDay field.</description>
    <inlineHelpText>If Due Day field is null, then by default it will have Expected First Payment Date day value</inlineHelpText>
    <label>Due_Day</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/genesis__Applications__c/fields/genesis__Expected_First_Payment_Date__c.field-meta.xml
<CustomField>
    <fullName>genesis__Expected_First_Payment_Date__c</fullName>
    <label>Expected First Payment Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/genesis__Applications__c/fields/genesis__Expected_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>genesis__Expected_Start_Date__c</fullName>
    <label>Expected Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/genesis__Applications__c/fields/genesis__Funding_in_Tranches__c.field-meta.xml
<CustomField>
    <fullName>genesis__Funding_in_Tranches__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Funding in Tranches</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/genesis__Applications__c/fields/genesis__Loan_Amount__c.field-meta.xml
<CustomField>
    <fullName>genesis__Loan_Amount__c</fullName>
    <label>Loan Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/genesis__Applications__c/fields/genesis__Status__c.field-meta.xml
<CustomField>
    <fullName>genesis__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>APPROVED - APPROVED</fullName>
            </value>
            <value>
                <fullName>APPROVED - CONVERTED TO CONTRACT</fullName>
            </value>
            <value>
                <fullName>APPROVED - DOCUMENT CHECK</fullName>
            </value>
            <value>
                <fullName>NEW - CREDIT PULLED</fullName>
            </value>
            <value>
                <fullName>NEW - ENTERED</fullName>
                <default>true</default>
                <label>NEW - ENTERED</label>
            </value>
            <value>
                <fullName>NEW - IN CREDIT CHECK</fullName>
            </value>
            <value>
                <fullName>NEW - IN REVIEW</fullName>
            </value>
            <value>
                <fullName>NEW - PRICING GENERATED</fullName>
            </value>
            <value>
                <fullName>NEW - SCORECARD GENERATED</fullName>
            </value>
            <value>
                <fullName>NEW - CHECKLIST GENERATED</fullName>
            </value>
            <value>
                <fullName>NEW - VEHICLE VALUATION REQUIRED</fullName>
            </value>
            <value>
                <fullName>REJECTED</fullName>
            </value>
            <value>
                <fullName>PULL CREDIT</fullName>
            </value>
            <value>
                <fullName>Default Documents</fullName>
            </value>
            <value>
                <fullName>offer_accepted</fullName>
            </value>
            <value>
                <fullName>offer_shown</fullName>
            </value>
            <value>
                <fullName>kba_success</fullName>
            </value>
            <value>
                <fullName>kba_fail</fullName>
            </value>
            <value>
                <fullName>agent_document_verification_pending</fullName>
            </value>
            <value>
                <fullName>agent_verification_pending</fullName>
            </value>
            <value>
                <fullName>agent_verified</fullName>
            </value>
            <value>
                <fullName>docusign_loan_docs_sent</fullName>
            </value>
            <value>
                <fullName>docusign_loan_docs_complete</fullName>
            </value>
            <value>
                <fullName>pre_funding</fullName>
            </value>
            <value>
                <fullName>Approved for funding</fullName>
            </value>
            <value>
                <fullName>funded</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Stacker_Check_Passed</fullName>
            </value>
            <value>
                <fullName>Redecision_Required</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/genesis__Applications__c/fields/Invested_Amount__c.field-meta.xml
<CustomField>
    <fullName>Invested_Amount__c</fullName>
    <label>Invested Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/genesis__Applications__c/fields/Investor__c.field-meta.xml
<CustomField>
    <fullName>Investor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Investor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.loan__Investor__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Applications (Investor)</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/TestManualAttachPDFtoApplication.cls
/* ****************Modification History******************
*    Created By        	 Date			Version
*1. Bhavya Maliwal        2022/02/23    LSP:572 Initial Version, method Name modified, Validation errors Corrected

******************Modification History******************/
@isTest
public class TestManualAttachPDFtoApplication{
    /*Created By : Bhavya Maliwal
Method name : manualAttachPDFtoApplication_PositiveScenario
Purpose : to cover code satisfying ManualAttachPDFtoApplication
*/
    testmethod static void manualAttachPDFtoApplication_PositiveScenario(){
        
        //Creating Account
        Account acc = new Account(
            Name = 'Test',
            peer__Last_Name__c='TestLName2',
            loan__Investor__c=False,
            cnotify__Email__c = 'abc@test.com',
            loan__SOCIAL_SECURITY_NUMBER__c = '123123123'
        );
        insert acc;
        System.assertEquals('Test',acc.Name,'Wrong Account');
        
        /*pallavi (LOS-123) correcting the Test class*/
        Account acc1 = new Account(
            Name = 'Test',
            loan__Investor__c=True,
            Amount_Invested__c = 1200,
            peer__Last_Name__c='TestLName2',
            Number_Of_Applications_Invested__c =3,
            cnotify__Email__c = 'abc@test.com',
            loan__SOCIAL_SECURITY_NUMBER__c = '123123121',
            Investor_Code__c = 'TNA'
        );
        insert acc1;
        
          CL_Document__c cs = new CL_Document__c();
        cs.Doc1__c = 'Credit Score Notice';
        cs.Doc2__c = 'TIL Document';
        cs.Doc3__c = 'Adverse Action Document';
        cs.UploadedBOX__c = 'UploadedBOX';
        insert cs;
        
        /*pallavi (LOS-123) correcting the Test class*/
        //Creating Application
        genesis__Applications__c app= new genesis__Applications__c(
            genesis__Due_Day__c = 20,
            genesis__Expected_First_Payment_Date__c = system.Today(),
            genesis__Expected_Start_Date__c = system.Today(),
            genesis__Funding_in_Tranches__c = true,
            Borrower_s_Email__c = null,
            genesis__Account__c = acc.Id,
            Application_Start_DateV2__c = system.Today(),
            DocuSignFlag__c=true,
            genesis__Status__c = 'agent_verified',
            genesis__Draw_Period_End_Date__c = system.Today(),
            investor__c= acc1.id,   //pallavi (LOS-123) correcting the Test class
            Invested_Amount__c = 100, //pallavi (LOS-123) correcting the Test class
            genesis__loan_amount__c = 100 //pallavi (LOS-123) correcting the Test class
        );
        insert app;
         Attachment attachmentTwo = new Attachment(
            ParentId = app.id, 
            Name = 'TIL', 
            IsPrivate = false, 
            Body = Blob.valueOf('Unit Test Attachment Body Two'), 
            Description = '15');
        insert attachmentTwo;
        
        
        genesis__Application_Document_Category__c adcTwo = new genesis__Application_Document_Category__c();
        adcTwo.name = 'TIL Document';
        adcTwo.genesis__Application__c = app.id;
        insert adcTwo;
        
        System.assertEquals(null,app.Borrower_s_Email__c,'Borrower Email is not null');
        
        Attachment attachment = new Attachment(
            ParentId = app.id, 
            Name = 'TIL', 
            IsPrivate = false, 
            Body = Blob.valueOf('Unit Test Attachment Body Two'), 
            Description = '15');
        insert attachment;
        
        genesis__Application_Document_Category__c adc = new genesis__Application_Document_Category__c();
        adc.name = 'TIL Document';
        adc.genesis__Application__c = app.id;
        
        insert adc;
        
        Test.startTest();        
        ManualAttachPDFtoApplication.attachPDFWebService(app.id,true,true);
        String result=ManualAttachPDFtoApplication.ManualTILgenerate(app.id);
        Test.stopTest();
        system.assert(result!=null);
    } 
}