unpackaged/main/default/objects/Account/fields/Amount_Invested__c.field-meta.xml
<CustomField>
    <fullName>Amount_Invested__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Total loan amount allocated to investor. Field is updated by allocation process.</description>
    <inlineHelpText>Total loan amount allocated to investor. Field is updated by allocation process.</inlineHelpText>
    <label>Amount Invested</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/cnotify__Email__c.field-meta.xml
<CustomField>
    <fullName>cnotify__Email__c</fullName>
    <label>Email</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Last_Application_assigned_on__c.field-meta.xml
<CustomField>
    <fullName>Last_Application_assigned_on__c</fullName>
    <label>Last Application assigned on</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/loan__Active__c.field-meta.xml
<CustomField>
    <fullName>loan__Active__c</fullName>
    <label>Active</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/loan__Investor__c.field-meta.xml
<CustomField>
    <fullName>loan__Investor__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Investor</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/loan__Undeployed_Funds__c.field-meta.xml
<CustomField>
    <fullName>loan__Undeployed_Funds__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Total amount which is available to invest in loans.</description>
    <inlineHelpText>tracks the investor payout or investor funds while creating investor loan or while selling the loan</inlineHelpText>
    <label>Available Funds</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/no_of_shares_to_be_Sold__c.field-meta.xml
<CustomField>
    <fullName>no_of_shares_to_be_Sold__c</fullName>
    <inlineHelpText>Provided value is % of Shares that will be Sold to the Funding partner automatically.</inlineHelpText>
    <label>% of shares to be Sold.</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Number_Of_Applications_Invested__c.field-meta.xml
<CustomField>
    <fullName>Number_Of_Applications_Invested__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Total number of applications allocated to investor LTD. Field is adjusted in allocations routine.</description>
    <inlineHelpText>Total number of applications allocated to investor LTD. Field is adjusted in allocations routine.</inlineHelpText>
    <label>Number Of Applications Invested</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Number_of_Days__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Days__c</fullName>
    <label>Number of Days</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/peer__First_Name__c.field-meta.xml
<CustomField>
    <fullName>peer__First_Name__c</fullName>
    <label>First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/peer__Last_Name__c.field-meta.xml
<CustomField>
    <fullName>peer__Last_Name__c</fullName>
    <label>Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Total_Investment_Limit__c.field-meta.xml
<CustomField>
    <fullName>Total_Investment_Limit__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Total loan amount that can be allocated to investor. Field is manually set.</description>
    <inlineHelpText>Total loan amount that can be allocated to investor. Field is manually set.</inlineHelpText>
    <label>Total Investment Limit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Total_No_of_Application_Limit__c.field-meta.xml
<CustomField>
    <fullName>Total_No_of_Application_Limit__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Max number of applications that can be allocated to an investor. Field is manually set.</description>
    <inlineHelpText>Max number of applications that can be allocated to an investor. Field is manually set.</inlineHelpText>
    <label>Total No of Application Limit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/ZIP_Code__c.field-meta.xml
<CustomField>
    <fullName>ZIP_Code__c</fullName>
    <label>ZIP Code</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Investor.recordType-meta.xml
<RecordType>
    <fullName>Investor</fullName>
    <active>true</active>
    <label>Investor</label>
</RecordType>

unpackaged/main/default/objects/loan__Fee__c/loan__Fee__c.object-meta.xml
<CustomObject>
    <description>Fee</description>
    <label>Fee</label>
    <nameField>
        <label>Fee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/loan__Fee__c/fields/loan__Currency__c.field-meta.xml
<CustomField>
    <fullName>loan__Currency__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Currency</description>
    <inlineHelpText>Currency</inlineHelpText>
    <label>Currency</label>
    <referenceTo>loan__Currency__c</referenceTo>
    <relationshipLabel>Fees</relationshipLabel>
    <relationshipName>Fees</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/loan__Fee_Junction__c/loan__Fee_Junction__c.object-meta.xml
<CustomObject>
    <label>Fee Set/Fee</label>
    <nameField>
        <displayFormat>FJIP-{0000000000}</displayFormat>
        <label>Fee Junction ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fee Set/Fee</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/loan__Fee_Junction__c/fields/loan__Fee__c.field-meta.xml
<CustomField>
    <fullName>loan__Fee__c</fullName>
    <label>Fee</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>loan__Fee__c.loan__Time_of_charge__c</field>
            <operation>notEqual</operation>
            <value>Pre-Paid Fees</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>loan__Fee__c</referenceTo>
    <relationshipLabel>Fee Set/Fee</relationshipLabel>
    <relationshipName>Fee_Junction</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/loan__Fee_Junction__c/fields/loan__Fee_Set__c.field-meta.xml
<CustomField>
    <fullName>loan__Fee_Set__c</fullName>
    <label>Fee Set</label>
    <referenceTo>loan__Fee_Set__c</referenceTo>
    <relationshipName>Fee_Junction</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/loan__Investor_Loan__c/loan__Investor_Loan__c.object-meta.xml
<CustomObject>
    <description>This is a conjunction object to keep many to many relationships for loans and accounts (Investor)</description>
    <label>Investment Order</label>
    <nameField>
        <displayFormat>ILID-{0000000000}</displayFormat>
        <label>Investor Loan ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Investment Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/loan__Investor_Loan__c/fields/Number_of_Days__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Days__c</fullName>
    <inlineHelpText>Number of days after which IO will be sold automatically.</inlineHelpText>
    <label>Number of Days</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/loan__Loan_Account__c/loan__Loan_Account__c.object-meta.xml
<CustomObject>
    <description>Lending Account</description>
    <label>CL Contract</label>
    <nameField>
        <displayFormat>LAI-{00000000}</displayFormat>
        <label>CL Contract ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CL Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/loan__Loan_Account__c/fields/loan__Fee_Set__c.field-meta.xml
<CustomField>
    <fullName>loan__Fee_Set__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Fee Set</description>
    <inlineHelpText>Lookup to associate the fee set on this lending account. Only the fees defined within the fee set can be assessed on this contract.
To create a fee set, Servicing configuration-&gt;Product-&gt;Manage fee set</inlineHelpText>
    <label>Fee Set</label>
    <referenceTo>loan__Fee_Set__c</referenceTo>
    <relationshipName>Loan_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/loan__Loan_Account__c/fields/loan__Loan_Purpose__c.field-meta.xml
<CustomField>
    <fullName>loan__Loan_Purpose__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Loan Purpose</description>
    <inlineHelpText>Loan purpose</inlineHelpText>
    <label>Purpose</label>
    <referenceTo>loan__Loan_Purpose__c</referenceTo>
    <relationshipName>Loan_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/loan__Loan_Account__c/fields/loan__Payment_Mode__c.field-meta.xml
<CustomField>
    <fullName>loan__Payment_Mode__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>This is the default payment mode for this loan. It will be used to populate the payment mode on the loan payment transaction screen.</inlineHelpText>
    <label>Payment Mode</label>
    <referenceTo>loan__Payment_Mode__c</referenceTo>
    <relationshipLabel>CL Contracts</relationshipLabel>
    <relationshipName>CL_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/loan__Loan_Product__c/loan__Loan_Product__c.object-meta.xml
<CustomObject>
    <description>Lending Product Definition1</description>
    <label>Lending Product</label>
    <nameField>
        <label>Loan Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lending Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/loan__Loan_Product__c/fields/loan__Currency__c.field-meta.xml
<CustomField>
    <fullName>loan__Currency__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Currency</description>
    <inlineHelpText>Currency</inlineHelpText>
    <label>Currency</label>
    <referenceTo>loan__Currency__c</referenceTo>
    <relationshipName>Loan_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/loan__Loan_Product__c/fields/loan__Fee_Set__c.field-meta.xml
<CustomField>
    <fullName>loan__Fee_Set__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Fee Set</description>
    <inlineHelpText>Fee set contains the details of all the fees associated with the loan.</inlineHelpText>
    <label>Fee Set</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Selected Fee Set's category must be of type 'Loan' and it should include at least one fee.</errorMessage>
        <filterItems>
            <field>loan__Fee_Set__c.loan__Fee_Set_Category__c</field>
            <operation>equals</operation>
            <value>Loan</value>
        </filterItems>
        <filterItems>
            <field>loan__Fee_Set__c.loan__Number_of_Fees__c</field>
            <operation>notEqual</operation>
            <value>0</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>loan__Fee_Set__c</referenceTo>
    <relationshipName>Loan_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/TestAutoSaleBatchAssignCntrl.cls
/* ****************Modification History******************
 * Created by    	Date    	JIRA number
 *     Pallavi      2019/12/13    LOS-185/186 auto sale in bulk
 ******************Modification History******************/
@isTest
public class TestAutoSaleBatchAssignCntrl {
    
    static loan__Loan_Account__c createLoanAccount() {
        
        //Creating Seed Data for Testing
        loan.TestHelper.createSeedDataForTesting();

        loan__Currency__c curr = loan.TestHelper.createCurrency();
        //Create a dummy MF_Account
        loan__MF_Account__c dummyAccount = loan.TestHelper.createMFAccount('XXXAccountForTest','10000 - ASSETS');
        loan__MF_Account__c dummyIncAccount = loan.TestHelper.createMFAccount('XXXIncAccountForTest','30000 - INCOME');

        //Create a Fee Set
        loan__Fee__c dummyFee = loan.TestHelper.createFee(curr,dummyIncAccount ,dummyAccount);
        loan__Fee_Set__c dummyFeeSet = loan.TestHelper.createFeeSet();
        loan__Fee_Junction__c dummyFeeJunction = loan.TestHelper.createFeeJunction(dummyFee,dummyFeeSet);

        loan__Office_Name__c dummyOffice = loan.TestHelper.createOffice();

        //Create a dummy Loan Product
        loan__Loan_Product__c dummyLP = loan.TestHelper.createLoanProduct('Loan Product',
                            dummyOffice,
                            dummyAccount,
                            curr,
                            dummyFeeSet,
                            'Interest Only',
                            40,
                            12,
                            null);

        loan__Loan_Purpose__c dummyLoanPurpose = loan.TestHelper.createLoanPurpose();


        Account acc = new Account(Name = 'SF');
        insert acc;

        loan__Payment_Mode__c paymentMode = new loan__Payment_Mode__c(name='ACH');
        insert paymentMode;
        //Create a dummy Loan Account
        loan__Loan_Account__c loanAccount = loan.TestHelper.createLoanAccountForAccountObj(dummyLP,
                                                    acc,
                                                    dummyFeeSet,
                                                    dummyLoanPurpose,
                                                    dummyOffice);
        return loanAccount;
    }
    
    @isTest
    static void test_AutoSaleBatchAssignCntrl(){
        //loan.TestHelper.systemDate = Date.newInstance(2016, 1, 15);
        loan.GlobalLoanUtilFacade util = new loan.GlobalLoanUtilFacade();
        loan__Loan_Account__c lAcct = createLoanAccount();
        Date systemDate = util.getCurrentSystemDate();

        Account invacc = new Account(
            Name = 'Investor',
            loan__Investor__c = true,
            Amount_Invested__c = 1000,
            Number_Of_Applications_Invested__c = 3, 
            Total_No_of_Application_Limit__c = 30,
            Last_Application_assigned_on__c = system.now()-7,
            Total_Investment_Limit__c = 1000000,
            loan__Undeployed_Funds__c = 500000,
            cnotify__Email__c = 'no-reply@testorganization.com',
            peer__First_Name__c = 'TestFName1',
            peer__Last_Name__c='TestLName2',
            no_of_shares_to_be_Sold__c = 1,
            Number_of_Days__c = 0,
            loan__Active__c = 'YES', 
            City__c='CANADA',
            State__c='CA',
            ZIP_Code__c='123456'
        );
        Insert invacc;
        
        Account acc = new Account(Name = 'Test Account', loan__Undeployed_Funds__c = 10000);
        insert acc;
        
        list<loan__Investor_Loan__c> ioList = new list<loan__Investor_Loan__c>();
         
           loan__Investor_Loan__c lo = new loan__Investor_Loan__c();
           lo.loan__Certificate_Rate__c                   = 1.0;
           lo.Buyer__c                                    = invacc.id;
           lo.loan__Service_Rate__c                       = 10.0;
           lo.loan__Account__c                            = invacc.id;
           lo.loan__Loan__c                               = lAcct.id;
           lo.loan__Share__c                              = 100;
           lo.loan__Status__c                             = 'Active';
           lo.loan__Enabled_Flag__c                       =  true;
           lo.loan__Inv_Accrued_Interest_Amt__c           =  0;
           lo.loan__Investment_Amount__c                  = 1000;
           lo.loan__Principal_Amount_Paid__c              = 2;
           lo.loan__Loan_Principal_Remaining__c           =1000;
           lo.loan__Investor_Start_Date__c                = System.today();
           
         
           insert lo;
        
           List<loan__loan_account__c> contractList = new List<loan__loan_account__c>();
           contractList.add(lAcct);
        
            Test.startTest();
            Test.setCurrentPage(Page.AutoSaleBatchAssign);
            ApexPages.StandardSetController stdSetController = new ApexPages.StandardSetController(contractList);
            stdSetController.setSelected(contractList);
            AutoSaleBatchAssignCntrl ctopc = new AutoSaleBatchAssignCntrl(stdSetController);
            ctopc.contract = lAcct;
            ctopc.saveBuyerandDate();
            ctopc.validateBuyerandDate();
        
        	lAcct.Buyer__c = acc.id;
        	update lAcct;
        
            Test.setCurrentPage(Page.AutoSaleBatchAssign);
            stdSetController.setSelected(contractList);
            ctopc.contract = lAcct;
            ctopc.saveBuyerandDate();
            ctopc.validateBuyerandDate();
        
        	lAcct.Effective_Date_for_AutoSale__c = Date.newInstance(2015, 02, 02);
        	update lAcct;
        	
        	Test.setCurrentPage(Page.AutoSaleBatchAssign);
            ctopc.contract = lAcct;
            ctopc.saveBuyerandDate();
            ctopc.validateBuyerandDate();
        
        	lAcct.Buyer__c = invacc.id;
        	update lAcct;
        
            Test.setCurrentPage(Page.AutoSaleBatchAssign);
            stdSetController.setSelected(contractList);
            ctopc.contract = lAcct;
            ctopc.saveBuyerandDate();
            ctopc.validateBuyerandDate();
        
        	lAcct.Effective_Date_for_AutoSale__c = systemDate.addDays(2);
        	update lAcct;
        	
        	Test.setCurrentPage(Page.AutoSaleBatchAssign);
            ctopc.contract = lAcct;
            ctopc.saveBuyerandDate();
            ctopc.validateBuyerandDate();
        
        	lAcct.Buyer__c = invacc.id;
        	update lAcct;
             
        	ctopc.updateBuyerandDate();
                
            Test.stopTest();
        
        	
    }

}