unpackaged/main/default/objects/Account/fields/Amount_Invested__c.field-meta.xml
<CustomField>
    <fullName>Amount_Invested__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Total loan amount allocated to investor. Field is updated by allocation process.</description>
    <inlineHelpText>Total loan amount allocated to investor. Field is updated by allocation process.</inlineHelpText>
    <label>Amount Invested</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/cnotify__Email__c.field-meta.xml
<CustomField>
    <fullName>cnotify__Email__c</fullName>
    <label>Email</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/loan__Investor__c.field-meta.xml
<CustomField>
    <fullName>loan__Investor__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Investor</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/loan__SOCIAL_SECURITY_NUMBER__c.field-meta.xml
<CustomField>
    <fullName>loan__SOCIAL_SECURITY_NUMBER__c</fullName>
    <label>SOCIAL_SECURITY_NUMBER</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Number_Of_Applications_Invested__c.field-meta.xml
<CustomField>
    <fullName>Number_Of_Applications_Invested__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Total number of applications allocated to investor LTD. Field is adjusted in allocations routine.</description>
    <inlineHelpText>Total number of applications allocated to investor LTD. Field is adjusted in allocations routine.</inlineHelpText>
    <label>Number Of Applications Invested</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/CL_Document__c/CL_Document__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>CL_Generated Documents Names</description>
    <label>CL Document</label>
</CustomObject>

unpackaged/main/default/objects/CL_Document__c/fields/Doc1__c.field-meta.xml
<CustomField>
    <fullName>Doc1__c</fullName>
    <label>Doc1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/CL_Document__c/fields/Doc2__c.field-meta.xml
<CustomField>
    <fullName>Doc2__c</fullName>
    <inlineHelpText>TIL Document</inlineHelpText>
    <label>Doc2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/CL_Document__c/fields/Doc3__c.field-meta.xml
<CustomField>
    <fullName>Doc3__c</fullName>
    <label>Doc3</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/CL_Document__c/fields/OrginaitionDocumentFolder__c.field-meta.xml
<CustomField>
    <fullName>OrginaitionDocumentFolder__c</fullName>
    <label>OrginaitionDocumentFolder</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/CL_Document__c/fields/UploadedBOX__c.field-meta.xml
<CustomField>
    <fullName>UploadedBOX__c</fullName>
    <label>UploadedBOX</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/genesis__Application_Document_Category__c/genesis__Application_Document_Category__c.object-meta.xml
<CustomObject>
    <label>Application Document Category</label>
    <nameField>
        <label>Application Document Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application Document Category</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/genesis__Application_Document_Category__c/fields/genesis__Document_Category__c.field-meta.xml
<CustomField>
    <fullName>genesis__Document_Category__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Document Category</label>
    <referenceTo>genesis__Document_Category__c</referenceTo>
    <relationshipLabel>Application Document Category</relationshipLabel>
    <relationshipName>Application_Document_Category</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/genesis__Application_Document_Category__c/fields/genesis__Status__c.field-meta.xml
<CustomField>
    <fullName>genesis__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>OPEN</fullName>
                <default>true</default>
                <label>OPEN</label>
            </value>
            <value>
                <fullName>SUBMITTED</fullName>
            </value>
            <value>
                <fullName>CLEARED</fullName>
            </value>
            <value>
                <fullName>REJECTED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/genesis__Applications__c/genesis__Applications__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{0000000000}</displayFormat>
        <label>Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/genesis__Applications__c/fields/genesis__Due_Day__c.field-meta.xml
<CustomField>
    <fullName>genesis__Due_Day__c</fullName>
    <description>dueDay field.</description>
    <inlineHelpText>If Due Day field is null, then by default it will have Expected First Payment Date day value</inlineHelpText>
    <label>Due_Day</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/genesis__Applications__c/fields/genesis__Expected_First_Payment_Date__c.field-meta.xml
<CustomField>
    <fullName>genesis__Expected_First_Payment_Date__c</fullName>
    <label>Expected First Payment Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/genesis__Applications__c/fields/genesis__Expected_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>genesis__Expected_Start_Date__c</fullName>
    <label>Expected Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/genesis__Applications__c/fields/genesis__Funding_in_Tranches__c.field-meta.xml
<CustomField>
    <fullName>genesis__Funding_in_Tranches__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Funding in Tranches</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/genesis__Applications__c/fields/genesis__Status__c.field-meta.xml
<CustomField>
    <fullName>genesis__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>APPROVED - APPROVED</fullName>
            </value>
            <value>
                <fullName>APPROVED - CONVERTED TO CONTRACT</fullName>
            </value>
            <value>
                <fullName>APPROVED - DOCUMENT CHECK</fullName>
            </value>
            <value>
                <fullName>NEW - CREDIT PULLED</fullName>
            </value>
            <value>
                <fullName>NEW - ENTERED</fullName>
                <default>true</default>
                <label>NEW - ENTERED</label>
            </value>
            <value>
                <fullName>NEW - IN CREDIT CHECK</fullName>
            </value>
            <value>
                <fullName>NEW - IN REVIEW</fullName>
            </value>
            <value>
                <fullName>NEW - PRICING GENERATED</fullName>
            </value>
            <value>
                <fullName>NEW - SCORECARD GENERATED</fullName>
            </value>
            <value>
                <fullName>NEW - CHECKLIST GENERATED</fullName>
            </value>
            <value>
                <fullName>NEW - VEHICLE VALUATION REQUIRED</fullName>
            </value>
            <value>
                <fullName>REJECTED</fullName>
            </value>
            <value>
                <fullName>PULL CREDIT</fullName>
            </value>
            <value>
                <fullName>Default Documents</fullName>
            </value>
            <value>
                <fullName>offer_accepted</fullName>
            </value>
            <value>
                <fullName>offer_shown</fullName>
            </value>
            <value>
                <fullName>kba_success</fullName>
            </value>
            <value>
                <fullName>kba_fail</fullName>
            </value>
            <value>
                <fullName>agent_document_verification_pending</fullName>
            </value>
            <value>
                <fullName>agent_verification_pending</fullName>
            </value>
            <value>
                <fullName>agent_verified</fullName>
            </value>
            <value>
                <fullName>docusign_loan_docs_sent</fullName>
            </value>
            <value>
                <fullName>docusign_loan_docs_complete</fullName>
            </value>
            <value>
                <fullName>pre_funding</fullName>
            </value>
            <value>
                <fullName>Approved for funding</fullName>
            </value>
            <value>
                <fullName>funded</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Stacker_Check_Passed</fullName>
            </value>
            <value>
                <fullName>Redecision_Required</fullName>
            </value>
            <value>
                <fullName>Decline_Manual_Review</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/genesis__Applications__c/fields/Investor__c.field-meta.xml
<CustomField>
    <fullName>Investor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Investor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.loan__Investor__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Applications (Investor)</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/genesis__Document_Category__c/genesis__Document_Category__c.object-meta.xml
<CustomObject>
    <label>Document Category</label>
    <nameField>
        <displayFormat>DC-{00000000}</displayFormat>
        <label>Document Category Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Document Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/genesis__Document_Category__c/fields/genesis__Applicable_For__c.field-meta.xml
<CustomField>
    <fullName>genesis__Applicable_For__c</fullName>
    <label>Applicable For</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CONTRACT</fullName>
            </value>
            <value>
                <fullName>PARTY</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/genesis__Document_Category__c/fields/genesis__Responsible_Party_Type__c.field-meta.xml
<CustomField>
    <fullName>genesis__Responsible_Party_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Responsible Party Type</label>
    <referenceTo>clcommon__Party_Type__c</referenceTo>
    <relationshipLabel>Document Categories</relationshipLabel>
    <relationshipName>Document_Categories</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Origination_Documents__c/Origination_Documents__c.object-meta.xml
<CustomObject>
    <label>Origination Documents</label>
    <nameField>
        <label>Or Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Origination Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Origination_Documents__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>preciseid</fullName>
            </value>
            <value>
                <fullName>talx</fullName>
            </value>
            <value>
                <fullName>linked_acct</fullName>
            </value>
            <value>
                <fullName>cbr</fullName>
            </value>
            <value>
                <fullName>credit_authorization</fullName>
            </value>
            <value>
                <fullName>borrower_bank_agreement</fullName>
            </value>
            <value>
                <fullName>payoff_privacy_policy</fullName>
            </value>
            <value>
                <fullName>privacy_notice</fullName>
            </value>
            <value>
                <fullName>terms_of_use</fullName>
            </value>
            <value>
                <fullName>autopay_authorization</fullName>
            </value>
            <value>
                <fullName>eca</fullName>
            </value>
            <value>
                <fullName>talx_hr</fullName>
            </value>
            <value>
                <fullName>linked_acct_hr</fullName>
            </value>
            <value>
                <fullName>bureau_report_hr</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/MWOriginationDocuments_ManualTest.cls
@isTest
private class MWOriginationDocuments_ManualTest {
    @testSetup static void setup(){
        loan.TestHelper.createSeedDataForTesting();
        loan__Office_Name__c dummyOffice = loan.TestHelper.createOffice();

        //Party Type insert
        clcommon__Party_Type__c pt = new clcommon__Party_Type__c();
        pt.name = 'Borrower';
        insert pt;

        CL_Document__c cs = new CL_Document__c();
        cs.Doc1__c = 'Credit Score Notice';
        cs.Doc2__c = 'TIL Document';
        cs.Doc3__c = 'Adverse Action Document';
        cs.UploadedBOX__c = 'UploadedBOX';
        cs.OrginaitionDocumentFolder__C = '1111111111';
        insert cs;

        //Document category
        genesis__Document_Category__c dc = new genesis__Document_Category__c();
        dc.genesis__Responsible_Party_Type__c = pt.id;
        dc.genesis__Applicable_For__c = 'PARTY';
        insert dc;
        Account acc = new Account(
                Name = 'Test',
                loan__Investor__c = True,
                Amount_Invested__c = 1200,
                Number_Of_Applications_Invested__c =3,
                cnotify__Email__c = 'abc@test.com',
                loan__SOCIAL_SECURITY_NUMBER__c = '123'
        );
        insert acc;

        //Inserting Application record
        genesis__Applications__c genesis_applications_Obj = new genesis__Applications__c(
                genesis__Due_Day__c = 20,
                genesis__Expected_First_Payment_Date__c = system.Today(),
                genesis__Expected_Start_Date__c = system.Today(),
                genesis__Funding_in_Tranches__c = true,
                Investor__c = acc.id,
                genesis__Status__c = 'pre_funding',
                DocuSign_Sign_Date__c = system.Today(),
                genesis__Draw_Period_End_Date__c = system.Today(),
                Lead_ID__c = '1231231231',
                Payment_Mode__c = 'AutoPay');
        insert genesis_applications_Obj;

        Origination_Documents__c ogDoc = new Origination_Documents__c();
        ogDoc.Application__c = genesis_applications_Obj.id;
        ogDoc.type__c = 'cbr';
        insert ogDoc;

        Origination_Documents__c ogDoc1 = new Origination_Documents__c();
        ogDoc1.Application__c = genesis_applications_Obj.id;
        ogDoc1.type__c = 'autopay_authorization';
        ogDoc1.Code_FF__c = 'autopay_authorization';
        insert ogDoc1;

        Origination_Documents__c ogDoc2 = new Origination_Documents__c();
        ogDoc2.Application__c = genesis_applications_Obj.id;
        ogDoc2.type__c = 'terms_of_use';
        ogDoc2.Code_FF__c = 'terms_of_use';
        insert ogDoc2;

        list<Attachment> attachment_ObjList = new list<Attachment>();
        attachment_ObjList.add(new Attachment(
                ParentId = genesis_applications_Obj.id,
                Name = 'DocuSignName312',
                IsPrivate = false,
                Body = Blob.valueOf('Unit Test Attachment Body'),
                Description = '15'));

        attachment_ObjList.add(new Attachment(
                ParentId = genesis_applications_Obj.id,
                Name = 'preciseid_1231231231.xml',
                IsPrivate = false,
                Body = Blob.valueOf('Unit Test Attachment Body'),
                Description = '15'));

        attachment_ObjList.add(new Attachment(
                ParentId = genesis_applications_Obj.id,
                Name = 'cbr_1231231231.xml',
                IsPrivate = false,
                Body = Blob.valueOf('Unit Test Attachment Body'),
                Description = '15'));

        attachment_ObjList.add(new Attachment(
                ParentId = genesis_applications_Obj.id,
                Name = 'linked_acct_1231231231.json',
                IsPrivate = false,
                Body = Blob.valueOf('Unit Test Attachment Body'),
                Description = '15'));

        attachment_ObjList.add(new Attachment(
                ParentId = acc.id,
                Name = 'autopay_authorization',
                IsPrivate = false,
                Body = Blob.valueOf('Unit Test Attachment Body'),
                Description = '15'));
        
        attachment_ObjList.add(new Attachment(
                ParentId = genesis_applications_Obj.id,
                Name = 'TIL Document',
                IsPrivate = false,
                Body = Blob.valueOf('Unit Test Attachment Body'),
                Description = 'TIL Document'));
        insert attachment_ObjList;

        genesis__Application_Document_Category__c adc = new genesis__Application_Document_Category__c();
        adc.name = 'TIL Document';
        adc.genesis__Active__c = true;
        adc.genesis__Document_Category__c =  dc.id;
        adc.genesis__Application__c = genesis_applications_Obj.id;
        adc.Box_URl__c = '';
        insert adc;

        genesis__AppDocCatAttachmentJunction__c adcj = new genesis__AppDocCatAttachmentJunction__c();
        adcj.genesis__Application_Document_Category__c = adc.id;
        adcj.genesis__AttachmentId__c = attachment_ObjList[0].id;
        insert adcj;

    }
    @isTest static void testMWOriginationDocuments_AppDocs() {
        Test.startTest();
        genesis__Application_Document_Category__c docBeforeBatch = [Select Id, name, Box_URl__c From genesis__Application_Document_Category__c limit 1];

        Set<String> appStatus = new Set<String>{'Decline_Manual_Review', 'Declined'};
        String selectAppsBy = 'AppCreatedDate';
        //String appStartDate = '2019-05-15T00:00:00Z';
        String appStartDate = String.valueOf(DateTime.now().year()).leftPad(2,'0') + '-' + String.valueOf(DateTime.now().month()).leftPad(2,'0') + '-'
                + String.valueOf(DateTime.now().day()).leftPad(2,'0') + 'T00:00:00Z';
        //String appEndDate = '2019-05-16T24:00:00Z';
        String appEndDate = String.valueOf(DateTime.now().year()).leftPad(2,'0') + '-' + String.valueOf(DateTime.now().month()).leftPad(2,'0') + '-'
                + String.valueOf(DateTime.now().day()).leftPad(2,'0') + 'T23:00:00Z';
        MWOriginationDocuments_AppDocs_Manual b = new MWOriginationDocuments_AppDocs_Manual(selectAppsBy, appStartDate, appEndDate, appStatus);
        Database.executeBatch(b,200);


        Set<String> appStatusAD = new Set<String>{'pre_funding'};
        String selectAppsByAD = 'DocuSignSignedDate';
        //String appStartDateAD = '2020-05-21';
        String appStartDateAD = String.valueOf(DateTime.now().year()).leftPad(2,'0') + '-' + String.valueOf(DateTime.now().month()).leftPad(2,'0') + '-'
                + String.valueOf(DateTime.now().day()).leftPad(2,'0');
        //String appEndDateAD = '2020-05-21';
        String appEndDateAD = String.valueOf(DateTime.now().year()).leftPad(2,'0') + '-' + String.valueOf(DateTime.now().month()).leftPad(2,'0') + '-'
                + String.valueOf(DateTime.now().day()).leftPad(2,'0');

        MWOriginationDocuments_AppDocs_Manual bAD = new MWOriginationDocuments_AppDocs_Manual(selectAppsByAD, appStartDateAD, appEndDateAD, appStatusAD);
        Database.executeBatch(bAD,200);

        genesis__Application_Document_Category__c docAfterBatch = [Select Id, name, Box_URl__c From genesis__Application_Document_Category__c limit 1];
        System.assertEquals(docBeforeBatch.Box_URl__c, docAfterBatch.Box_URl__c);
        Test.stopTest();
    }

    @isTest static void testMWOriginationDocuments_OrgiDocs() {
        Test.startTest();
        Set<String> appStatus = new Set<String>{'Decline_Manual_Review', 'Declined'};
        String selectAppsBy = 'AppCreatedDate';
        //String appStartDate = '2019-05-15T00:00:00Z';
        String appStartDate = String.valueOf(DateTime.now().year()).leftPad(2,'0') + '-' + String.valueOf(DateTime.now().month()).leftPad(2,'0') + '-'
                + String.valueOf(DateTime.now().day()).leftPad(2,'0') + 'T00:00:00Z';
        //String appEndDate = '2019-05-16T24:00:00Z';
        String appEndDate = String.valueOf(DateTime.now().year()).leftPad(2,'0') + '-' + String.valueOf(DateTime.now().month()).leftPad(2,'0') + '-'
                + String.valueOf(DateTime.now().day()).leftPad(2,'0') + 'T23:00:00Z';
        MWOriginationDocuments_OrgiDocs_Manual b = new MWOriginationDocuments_OrgiDocs_Manual(selectAppsBy, appStartDate, appEndDate, appStatus);
        Database.executeBatch(b,200);

        Set<String> appStatusOD = new Set<String>{'pre_funding'};
        String selectAppsByOD = 'DocuSignSignedDate';
        //String appStartDateOD = '2020-05-21';
        String appStartDateOD = String.valueOf(DateTime.now().year()).leftPad(2,'0') + '-' + String.valueOf(DateTime.now().month()).leftPad(2,'0') + '-'
                + String.valueOf(DateTime.now().day()).leftPad(2,'0');
        //String appEndDateOD = '2020-05-21';
        String appEndDateOD = String.valueOf(DateTime.now().year()).leftPad(2,'0') + '-' + String.valueOf(DateTime.now().month()).leftPad(2,'0') + '-'
                + String.valueOf(DateTime.now().day()).leftPad(2,'0');

        MWOriginationDocuments_OrgiDocs_Manual bOD = new MWOriginationDocuments_OrgiDocs_Manual(selectAppsByOD, appStartDateOD, appEndDateOD, appStatusOD);
        Database.executeBatch(bOD,200);

        Test.stopTest();
    }

}