unpackaged/main/default/objects/Account/fields/Annual_Individual_Income__c.field-meta.xml
<CustomField>
    <fullName>Annual_Individual_Income__c</fullName>
    <label>Annual Individual Income</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/cnotify__Email__c.field-meta.xml
<CustomField>
    <fullName>cnotify__Email__c</fullName>
    <label>Email</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Income_Include_Bonuses_or_Commissions__c.field-meta.xml
<CustomField>
    <fullName>Income_Include_Bonuses_or_Commissions__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Income Include Bonuses or Commissions</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/loan__Investor__c.field-meta.xml
<CustomField>
    <fullName>loan__Investor__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Investor</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/peer__First_Name__c.field-meta.xml
<CustomField>
    <fullName>peer__First_Name__c</fullName>
    <label>First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/peer__Last_Name__c.field-meta.xml
<CustomField>
    <fullName>peer__Last_Name__c</fullName>
    <label>Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Credit_Policy__c/Credit_Policy__c.object-meta.xml
<CustomObject>
    <label>Credit Policy</label>
    <nameField>
        <label>Credit Policy Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Credit Policy</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Credit_Policy__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>genesis__Applications__c</referenceTo>
    <relationshipLabel>Credit Policy</relationshipLabel>
    <relationshipName>Credit_Policy</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Credit_Policy__c/fields/FICO__c.field-meta.xml
<CustomField>
    <fullName>FICO__c</fullName>
    <label>FICO</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Credit_Policy__c/fields/final_decision__c.field-meta.xml
<CustomField>
    <fullName>final_decision__c</fullName>
    <label>final decision</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Credit_Policy__c/fields/Pricing_test_bucket__c.field-meta.xml
<CustomField>
    <fullName>Pricing_test_bucket__c</fullName>
    <label>Pricing test bucket</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Credit_Policy__c/fields/request_intent__c.field-meta.xml
<CustomField>
    <fullName>request_intent__c</fullName>
    <description>intent of the credit poilcy transmission as defined within credit policy call</description>
    <label>request intent</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/genesis__Applications__c/genesis__Applications__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{0000000000}</displayFormat>
        <label>Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/genesis__Applications__c/fields/Application_Start_DateV2__c.field-meta.xml
<CustomField>
    <fullName>Application_Start_DateV2__c</fullName>
    <label>Application Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/genesis__Applications__c/fields/Employment_Status__c.field-meta.xml
<CustomField>
    <fullName>Employment_Status__c</fullName>
    <label>Employment Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Full Time</fullName>
            </value>
            <value>
                <fullName>Part Time</fullName>
            </value>
            <value>
                <fullName>Retired</fullName>
            </value>
            <value>
                <fullName>Self Employed</fullName>
            </value>
            <value>
                <fullName>Contract</fullName>
            </value>
            <value>
                <fullName>Seasonal</fullName>
            </value>
            <value>
                <fullName>Investment</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/genesis__Applications__c/fields/FICO__c.field-meta.xml
<CustomField>
    <fullName>FICO__c</fullName>
    <label>FICO</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/genesis__Applications__c/fields/genesis__Account__c.field-meta.xml
<CustomField>
    <fullName>genesis__Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Applications_account</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/genesis__Applications__c/fields/genesis__APR__c.field-meta.xml
<CustomField>
    <fullName>genesis__APR__c</fullName>
    <description>Annual Percentage Rate</description>
    <label>APR</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/objects/genesis__Applications__c/fields/genesis__Draw_Period_End_Date__c.field-meta.xml
<CustomField>
    <fullName>genesis__Draw_Period_End_Date__c</fullName>
    <label>Draw Period End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/genesis__Applications__c/fields/genesis__Due_Day__c.field-meta.xml
<CustomField>
    <fullName>genesis__Due_Day__c</fullName>
    <description>dueDay field.</description>
    <inlineHelpText>If Due Day field is null, then by default it will have Expected First Payment Date day value</inlineHelpText>
    <label>Due_Day</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/genesis__Applications__c/fields/genesis__Expected_First_Payment_Date__c.field-meta.xml
<CustomField>
    <fullName>genesis__Expected_First_Payment_Date__c</fullName>
    <label>Expected First Payment Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/genesis__Applications__c/fields/genesis__Expected_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>genesis__Expected_Start_Date__c</fullName>
    <label>Expected Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/genesis__Applications__c/fields/genesis__Funding_in_Tranches__c.field-meta.xml
<CustomField>
    <fullName>genesis__Funding_in_Tranches__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Funding in Tranches</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/genesis__Applications__c/fields/genesis__Status__c.field-meta.xml
<CustomField>
    <fullName>genesis__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>APPROVED - APPROVED</fullName>
            </value>
            <value>
                <fullName>APPROVED - CONVERTED TO CONTRACT</fullName>
            </value>
            <value>
                <fullName>APPROVED - DOCUMENT CHECK</fullName>
            </value>
            <value>
                <fullName>NEW - CREDIT PULLED</fullName>
            </value>
            <value>
                <fullName>NEW - ENTERED</fullName>
                <default>true</default>
                <label>NEW - ENTERED</label>
            </value>
            <value>
                <fullName>NEW - IN CREDIT CHECK</fullName>
            </value>
            <value>
                <fullName>NEW - IN REVIEW</fullName>
            </value>
            <value>
                <fullName>NEW - PRICING GENERATED</fullName>
            </value>
            <value>
                <fullName>NEW - SCORECARD GENERATED</fullName>
            </value>
            <value>
                <fullName>NEW - CHECKLIST GENERATED</fullName>
            </value>
            <value>
                <fullName>NEW - VEHICLE VALUATION REQUIRED</fullName>
            </value>
            <value>
                <fullName>REJECTED</fullName>
            </value>
            <value>
                <fullName>PULL CREDIT</fullName>
            </value>
            <value>
                <fullName>Default Documents</fullName>
            </value>
            <value>
                <fullName>offer_accepted</fullName>
            </value>
            <value>
                <fullName>offer_shown</fullName>
            </value>
            <value>
                <fullName>kba_success</fullName>
            </value>
            <value>
                <fullName>kba_fail</fullName>
            </value>
            <value>
                <fullName>agent_document_verification_pending</fullName>
            </value>
            <value>
                <fullName>agent_verification_pending</fullName>
            </value>
            <value>
                <fullName>agent_verified</fullName>
            </value>
            <value>
                <fullName>docusign_loan_docs_sent</fullName>
            </value>
            <value>
                <fullName>docusign_loan_docs_complete</fullName>
            </value>
            <value>
                <fullName>pre_funding</fullName>
            </value>
            <value>
                <fullName>Approved for funding</fullName>
            </value>
            <value>
                <fullName>funded</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Stacker_Check_Passed</fullName>
            </value>
            <value>
                <fullName>Redecision_Required</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/genesis__Applications__c/fields/Sift_Status__c.field-meta.xml
<CustomField>
    <fullName>Sift_Status__c</fullName>
    <label>Sift Status</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/classes/CreditPolicyControllerTest.cls
@isTest
private class CreditPolicyControllerTest {
    @testSetup
    static void setup(){
       test.startTest();
    Account acc = new Account(
            Name = 'Test',
            loan__Investor__c=False,
            peer__First_Name__c= 'Testfname',
            peer__Last_Name__c= 'Testlname',
            cnotify__Email__c = 'no-reply@testorganization.com',
            Annual_Individual_Income__c = 10000, 
            Income_Include_Bonuses_or_Commissions__c = false
        );
        Insert acc;
        genesis__Applications__c app = new genesis__Applications__c(
            genesis__Due_Day__c = 20,
            genesis__Expected_First_Payment_Date__c = system.Today(),
            genesis__Expected_Start_Date__c = system.Today(),
            genesis__Funding_in_Tranches__c = true,
            genesis__Account__c = acc.Id,        
            Application_Start_DateV2__c = system.Today(),
            genesis__Status__c = 'Default Documents',
            genesis__Draw_Period_End_Date__c = system.Today(),
            Employment_Status__c = 'Full Time',
            genesis__APR__c=10.2,
            Sift_Status__c=30
        );      
        Insert app;
        
        Account acc2 = new Account(
            Name = 'Test2',
            loan__Investor__c=False,
            peer__First_Name__c= 'Testfname',
            peer__Last_Name__c= 'Testlname',
            cnotify__Email__c = 'no-reply@testorganization.com',
            Annual_Individual_Income__c = 10000, 
            Income_Include_Bonuses_or_Commissions__c = false
        );
        Insert acc2;
        genesis__Applications__c app2 = new genesis__Applications__c(
            genesis__Due_Day__c = 20,
            genesis__Expected_First_Payment_Date__c = system.Today(),
            genesis__Expected_Start_Date__c = system.Today(),
            genesis__Funding_in_Tranches__c = true,
            genesis__Account__c = acc2.Id,        
            Application_Start_DateV2__c = system.Today(),
            genesis__Status__c = 'Default Documents',
            genesis__Draw_Period_End_Date__c = system.Today(),
            Employment_Status__c = 'Full Time',
            genesis__APR__c=10.2,
            Sift_Status__c=30
        );      
        Insert app2;
        Credit_Policy__c cPolicy = new Credit_Policy__c(
            Application__c=app.Id,
            FICO__C=10.20,
            final_decision__c='Approve',
            pricing_test_bucket__c='Test',
            request_intent__c='application'
        );
        Insert cPolicy;
        test.stopTest();
    }
    @isTest
    static void CreditPolicyControllerTest_UseCase1(){
        Account acc = [select Id from Account  where Name = 'Test' LIMIT 1];
        System.assertEquals(true, acc!=Null); 
        genesis__Applications__c app = [SELECT Id from genesis__Applications__c WHERE genesis__Account__c =: acc.Id LIMIT 1];
        
        System.assertEquals(true, app!=Null);
        
        
        PageReference pageRef = Page.CSNDocument;
        Test.setCurrentPage(pageRef);
        
        pageRef.getParameters().put('Id', String.valueOf(app.Id));
        CreditPolicyController cpCtrl = new CreditPolicyController();
        //Decimal ficoVal = cpCtrl.creditPolicyRec[0].FICO__C;
        //System.assertEquals(true, ficoVal==10);
    }
    
     @isTest
    static void CreditPolicyControllerTest_UseCase2(){
        Account acc2 = [select Id from Account  where Name = 'Test2' LIMIT 1];
        System.assertEquals(true, acc2!=Null); 
        genesis__Applications__c app2 = [SELECT Id from genesis__Applications__c WHERE genesis__Account__c =: acc2.Id LIMIT 1];
        
        System.assertEquals(true, app2!=Null);
        
        
        PageReference pageRef = Page.CSNDocument;
        Test.setCurrentPage(pageRef);
        
        pageRef.getParameters().put('Id', String.valueOf(app2.Id));
        CreditPolicyController cpCtrl = new CreditPolicyController();
        //Decimal ficoVal = cpCtrl.creditPolicyRec[0].FICO__C;
        //System.assertEquals(true, ficoVal==10);
    }
}