unpackaged/main/default/objects/Account/fields/Borrower_s_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Borrower_s_Last_Name__c</fullName>
    <description>/*Created by Nupur */
 - For Email Templates</description>
    <formula>IF( RecordType.Name='Member' , peer__Last_Name__c,NULL)</formula>
    <label>Borrower's Last Name</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/cnotify__Email__c.field-meta.xml
<CustomField>
    <fullName>cnotify__Email__c</fullName>
    <label>Email</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/loan__Investor__c.field-meta.xml
<CustomField>
    <fullName>loan__Investor__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Investor</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/loan__SOCIAL_SECURITY_NUMBER__c.field-meta.xml
<CustomField>
    <fullName>loan__SOCIAL_SECURITY_NUMBER__c</fullName>
    <label>SOCIAL_SECURITY_NUMBER</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/TestHelperUtility.cls
@isTest
public class TestHelperUtility{
   testmethod static void method1(){
       Date currentSystemDate = Date.newInstance(2016,03,12);  //Saturday
       Date currentSystemDate1 = Date.newInstance(2016,03,10);
       String message = 'Test message';
       String origin ='Test';
       Test.startTest();
       //Creating Account
         Account acc = new Account(
            Name = 'Test',
            loan__Investor__c=False,
            //Borrower_s_Last_Name__c='Testborrower',
            cnotify__Email__c = 'abc@test.com',
            loan__SOCIAL_SECURITY_NUMBER__c = '123'
            );
        insert acc;
        System.assertEquals('Test',acc.Name,'Wrong Account');
        
        list<Attachment> attachments = new list<Attachment>();
        Attachment att = new Attachment();
        att.ParentId = acc.id;
        att.Name = 'Credit Score Notice';
        att.Body = Blob.valueOf('Test Attachment');
        attachments.add(att);
        Database.SaveResult[] srList = Database.insert(attachments, false);
        
        HelperUtility.getNextOriginationDate(currentSystemDate);
        HelperUtility.getNextOriginationDate(currentSystemDate1);
        HelperUtility.createLog(message,origin,currentSystemDate);
        HelperUtility.createLogs(srList,origin);
        Test.stopTest();
       
   }
}