unpackaged/main/default/objects/Account/fields/Borrower_s_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Borrower_s_Last_Name__c</fullName>
    <description>/*Created by Nupur */
 - For Email Templates</description>
    <formula>IF( RecordType.Name='Member' , peer__Last_Name__c,NULL)</formula>
    <label>Borrower's Last Name</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/cnotify__Email__c.field-meta.xml
<CustomField>
    <fullName>cnotify__Email__c</fullName>
    <label>Email</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/loan__Batch_Process_Log__c/loan__Batch_Process_Log__c.object-meta.xml
<CustomObject>
    <label>Batch Process Log</label>
    <nameField>
        <label>Apex Batch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Batch Process Log</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/loan__Batch_Process_Log__c/fields/loan__Message__c.field-meta.xml
<CustomField>
    <fullName>loan__Message__c</fullName>
    <label>Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/loan__Loan_Account__c/loan__Loan_Account__c.object-meta.xml
<CustomObject>
    <description>Lending Account</description>
    <label>CL Contract</label>
    <nameField>
        <displayFormat>LAI-{00000000}</displayFormat>
        <label>CL Contract ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CL Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/loan__Loan_Account__c/fields/Borrowers_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Borrowers_First_Name__c</fullName>
    <formula>loan__Account__r.Borrower_s_First_Name__c</formula>
    <label>Borrowers First Name</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/loan__Loan_Account__c/fields/loan__Account__c.field-meta.xml
<CustomField>
    <fullName>loan__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Please choose a account, which will be associated as a customer on this lending account.
You can create a new account, from the lookup window by clicking on new or select the existing account from the lookup.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Loan_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/loan__Loan_Account__c/fields/loan__Loan_Product_Name__c.field-meta.xml
<CustomField>
    <fullName>loan__Loan_Product_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Loan Product Name</description>
    <inlineHelpText>Please choose a lending product, which will be associated as a lending product on this lending account.
You can choose a existing product from the lookup or create a new product from 
Servicing Configuration-&gt;Product-&gt;Create new lending product</inlineHelpText>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Please select active lending product.</errorMessage>
        <filterItems>
            <field>loan__Loan_Product__c.loan__Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>loan__Loan_Product__c</referenceTo>
    <relationshipName>Loan_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/loan__Loan_Account__c/fields/loan__Next_Installment_Date__c.field-meta.xml
<CustomField>
    <fullName>loan__Next_Installment_Date__c</fullName>
    <description>Date of the next installment</description>
    <inlineHelpText>Date of the Next Due</inlineHelpText>
    <label>Next Due Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/loan__Loan_Account__c/fields/loan__Payment_Amount__c.field-meta.xml
<CustomField>
    <fullName>loan__Payment_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Loan payment amount. It excludes any fee that is gathered as a part of EMI.</description>
    <inlineHelpText>Contractual payment amount</inlineHelpText>
    <label>Payment Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/loan__Loan_Account__c/fields/loan__Previous_Installment_Date__c.field-meta.xml
<CustomField>
    <fullName>loan__Previous_Installment_Date__c</fullName>
    <description>Last Billing Date</description>
    <inlineHelpText>Last Bill Date</inlineHelpText>
    <label>Last Due Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/loan__Loan_Product__c/loan__Loan_Product__c.object-meta.xml
<CustomObject>
    <description>Lending Product Definition1</description>
    <label>Lending Product</label>
    <nameField>
        <label>Loan Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lending Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/LoanPaymentDays__c/LoanPaymentDays__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>LoanPaymentDays - For Remainder Mails</description>
    <label>LoanPaymentDays</label>
</CustomObject>

unpackaged/main/default/objects/LoanPaymentDays__c/fields/AutoPaymentRemainder__c.field-meta.xml
<CustomField>
    <fullName>AutoPaymentRemainder__c</fullName>
    <label>AutoPaymentRemainder</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/LoanPaymentDays__c/fields/ManualPaymentRemainder__c.field-meta.xml
<CustomField>
    <fullName>ManualPaymentRemainder__c</fullName>
    <label>ManualPaymentRemainder</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/classes/LoanPaymentRemainder.cls
global class LoanPaymentRemainder Implements Database.batchable<sObject>, Schedulable{
     String query;
     Date CSD = new loan.GlobalLoanUtilFacade().getCurrentSystemDate();   
     LoanPaymentDays__c paymentDueDays = LoanPaymentDays__c.getInstance();  
     Integer autoPaymentDue = Integer.valueOf(paymentDueDays.AutoPaymentRemainder__c);
     Integer manualPaymentDue = Integer.valueOf(paymentDueDays.ManualPaymentRemainder__c);
     Date D3Remainder = CSD + autoPaymentDue;
     Date D15Remainder = CSD + manualPaymentDue;
     //System.debug('...Dates...'+ D3Remainder +'...'+ D15Remainder );
     
     global LoanPaymentRemainder(){
         String productType = 'Manual';
         query = 'SELECT ID, loan__Previous_Installment_Date__c,loan__Account__r.cnotify__Email__c,loan__Loan_Product_Name__r.name, loan__Payment_Amount__c, loan__Next_Installment_Date__c, loan__Account__r.ID,Borrowers_First_Name__c,loan__Account__r.Borrower_s_Last_Name__c,loan__Loan_Product_Name__c from loan__Loan_Account__c WHERE loan__Previous_Installment_Date__c = :D3Remainder OR (loan__Previous_Installment_Date__c = :D15Remainder AND loan__Loan_Product_Name__r.name like \'%' + productType + '%\')';
         System.debug(logginglevel.error,'query+++'+query); 
     }   
     global LoanPaymentRemainder(String query){
         this.query = query;
     }
     
     global void execute(SchedulableContext sc){
         LoanPaymentRemainder lpr = new LoanPaymentRemainder();
         Database.executeBatch(lpr,1);
     }
     
     global Database.QueryLocator start(Database.BatchableContext bc){
         System.debug('...Query...'+query);
         return Database.getQueryLocator(query);
     }
     
     global void execute(Database.BatchableContext bc, List<sObject> scope){
         System.debug('...Scope....' + scope);
         try{
             List<loan__Loan_Account__c > lstLoanPayments = (List<loan__Loan_Account__c >)scope;
             List<loan__Loan_Account__c > lstPaymentRemainders = new List<loan__Loan_Account__c>(); 
             String userId = UserInfo.getUserId();
             
             Id templateId;         
             Id templateId3D =  [select id, name from EmailTemplate where developername = 'Upcoming_Auto_Loan_Payment_Reminder'].Id;
             Id templateIdManual =  [select id, name from EmailTemplate where developername = 'Upcoming_Manual_Loan_Payment_Reminder'].Id;         
                  
             Contact con = new Contact();
             con.LastName = 'Test';
             con.Email = 'no-reply@organization.com';
             insert con; 
             
             Id orgWideEmailId;
             OrgWideEmailAddress owea = [select Id from OrgWideEmailAddress where DisplayName = 'PayOff' LIMIT 1];
             if(owea != null)
                orgWideEmailId = owea.Id;
                
             for(loan__Loan_Account__c loanAccount : lstLoanPayments){
                if(loanAccount.loan__Previous_Installment_Date__c != null && loanAccount.loan__Previous_Installment_Date__c == D3Remainder)                
                    templateId = templateId3D;
                
                else if(loanAccount.loan__Previous_Installment_Date__c != null && loanAccount.loan__Loan_Product_Name__r.name != null && (loanAccount.loan__Previous_Installment_Date__c == D15Remainder && loanAccount.loan__Loan_Product_Name__r.name.contains('Manual')))
                    templateId = templateIdManual;                
                String emailAddress = loanAccount.loan__Account__r.cnotify__Email__c;
                SendLoanPaymentEmailHandler.SendMail(templateId, loanAccount.ID, con.Id, orgWideEmailId, emailAddress);
             }
             delete con;
         }
         catch(Exception ex){
            loan__batch_process_log__c logs = new loan__batch_process_log__c(loan__Message__c='Error in SendEnvDocuSignAPI.voidInvestorDocuments:  '+ex.getlinenumber()+'Error: '+ex.getMessage());
            insert logs;
            System.debug('Exception: '+ex.getMessage());    
        }
     }   
     
     global void finish(Database.BatchableContext bc){
     
     } 
}