unpackaged/main/default/objects/Account/fields/Borrower_s_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Borrower_s_Last_Name__c</fullName>
    <description>/*Created by Nupur */
 - For Email Templates</description>
    <formula>IF( RecordType.Name='Member' , peer__Last_Name__c,NULL)</formula>
    <label>Borrower's Last Name</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/cnotify__Email__c.field-meta.xml
<CustomField>
    <fullName>cnotify__Email__c</fullName>
    <label>Email</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/loan__Investor__c.field-meta.xml
<CustomField>
    <fullName>loan__Investor__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Investor</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/loan__SOCIAL_SECURITY_NUMBER__c.field-meta.xml
<CustomField>
    <fullName>loan__SOCIAL_SECURITY_NUMBER__c</fullName>
    <label>SOCIAL_SECURITY_NUMBER</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/peer__Last_Name__c.field-meta.xml
<CustomField>
    <fullName>peer__Last_Name__c</fullName>
    <label>Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/loan__Fee__c/loan__Fee__c.object-meta.xml
<CustomObject>
    <description>Fee</description>
    <label>Fee</label>
    <nameField>
        <label>Fee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/loan__Fee__c/fields/loan__Currency__c.field-meta.xml
<CustomField>
    <fullName>loan__Currency__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Currency</description>
    <inlineHelpText>Currency</inlineHelpText>
    <label>Currency</label>
    <referenceTo>loan__Currency__c</referenceTo>
    <relationshipLabel>Fees</relationshipLabel>
    <relationshipName>Fees</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/loan__Fee_Junction__c/loan__Fee_Junction__c.object-meta.xml
<CustomObject>
    <label>Fee Set/Fee</label>
    <nameField>
        <displayFormat>FJIP-{0000000000}</displayFormat>
        <label>Fee Junction ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fee Set/Fee</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/loan__Fee_Junction__c/fields/loan__Fee__c.field-meta.xml
<CustomField>
    <fullName>loan__Fee__c</fullName>
    <label>Fee</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>loan__Fee__c.loan__Time_of_charge__c</field>
            <operation>notEqual</operation>
            <value>Pre-Paid Fees</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>loan__Fee__c</referenceTo>
    <relationshipLabel>Fee Set/Fee</relationshipLabel>
    <relationshipName>Fee_Junction</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/loan__Fee_Junction__c/fields/loan__Fee_Set__c.field-meta.xml
<CustomField>
    <fullName>loan__Fee_Set__c</fullName>
    <label>Fee Set</label>
    <referenceTo>loan__Fee_Set__c</referenceTo>
    <relationshipName>Fee_Junction</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/loan__Loan_Account__c/loan__Loan_Account__c.object-meta.xml
<CustomObject>
    <description>Lending Account</description>
    <label>CL Contract</label>
    <nameField>
        <displayFormat>LAI-{00000000}</displayFormat>
        <label>CL Contract ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CL Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/loan__Loan_Account__c/fields/loan__Account__c.field-meta.xml
<CustomField>
    <fullName>loan__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Please choose a account, which will be associated as a customer on this lending account.
You can create a new account, from the lookup window by clicking on new or select the existing account from the lookup.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Loan_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/loan__Loan_Account__c/fields/loan__Fee_Set__c.field-meta.xml
<CustomField>
    <fullName>loan__Fee_Set__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Fee Set</description>
    <inlineHelpText>Lookup to associate the fee set on this lending account. Only the fees defined within the fee set can be assessed on this contract.
To create a fee set, Servicing configuration-&gt;Product-&gt;Manage fee set</inlineHelpText>
    <label>Fee Set</label>
    <referenceTo>loan__Fee_Set__c</referenceTo>
    <relationshipName>Loan_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/loan__Loan_Account__c/fields/loan__Loan_Amount__c.field-meta.xml
<CustomField>
    <fullName>loan__Loan_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Loan Amount</description>
    <inlineHelpText>This is the financed amount on the contract which will be disbursed to the customer.</inlineHelpText>
    <label>Loan Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/loan__Loan_Account__c/fields/loan__Loan_Product_Name__c.field-meta.xml
<CustomField>
    <fullName>loan__Loan_Product_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Loan Product Name</description>
    <inlineHelpText>Please choose a lending product, which will be associated as a lending product on this lending account.
You can choose a existing product from the lookup or create a new product from 
Servicing Configuration-&gt;Product-&gt;Create new lending product</inlineHelpText>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Please select active lending product.</errorMessage>
        <filterItems>
            <field>loan__Loan_Product__c.loan__Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>loan__Loan_Product__c</referenceTo>
    <relationshipName>Loan_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/loan__Loan_Account__c/fields/loan__Next_Installment_Date__c.field-meta.xml
<CustomField>
    <fullName>loan__Next_Installment_Date__c</fullName>
    <description>Date of the next installment</description>
    <inlineHelpText>Date of the Next Due</inlineHelpText>
    <label>Next Due Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/loan__Loan_Account__c/fields/loan__Payment_Amount__c.field-meta.xml
<CustomField>
    <fullName>loan__Payment_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Loan payment amount. It excludes any fee that is gathered as a part of EMI.</description>
    <inlineHelpText>Contractual payment amount</inlineHelpText>
    <label>Payment Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/loan__Loan_Account__c/fields/loan__Previous_Installment_Date__c.field-meta.xml
<CustomField>
    <fullName>loan__Previous_Installment_Date__c</fullName>
    <description>Last Billing Date</description>
    <inlineHelpText>Last Bill Date</inlineHelpText>
    <label>Last Due Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/loan__Loan_Account__c/fields/loan__Product_Type__c.field-meta.xml
<CustomField>
    <fullName>loan__Product_Type__c</fullName>
    <description>Type of Product, only LoC and Loans are supported.</description>
    <inlineHelpText>This will be populated from lending product and must not be changed by the user.
This will define the classification of the product.
Possible values are
1) Loan
2) Line of credit
3) Merchant Cash Advance</inlineHelpText>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Loan</fullName>
                <default>true</default>
                <label>Loan</label>
            </value>
            <value>
                <fullName>Line of Credit</fullName>
            </value>
            <value>
                <fullName>Merchant Cash Advance</fullName>
            </value>
            <value>
                <fullName>Amz Based Loan</fullName>
            </value>
            <value>
                <fullName>Flexible Amz Loan</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/loan__Loan_Product__c/loan__Loan_Product__c.object-meta.xml
<CustomObject>
    <description>Lending Product Definition1</description>
    <label>Lending Product</label>
    <nameField>
        <label>Loan Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lending Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/loan__Loan_Product__c/fields/loan__Currency__c.field-meta.xml
<CustomField>
    <fullName>loan__Currency__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Currency</description>
    <inlineHelpText>Currency</inlineHelpText>
    <label>Currency</label>
    <referenceTo>loan__Currency__c</referenceTo>
    <relationshipName>Loan_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/loan__Loan_Product__c/fields/loan__Fee_Set__c.field-meta.xml
<CustomField>
    <fullName>loan__Fee_Set__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Fee Set</description>
    <inlineHelpText>Fee set contains the details of all the fees associated with the loan.</inlineHelpText>
    <label>Fee Set</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Selected Fee Set's category must be of type 'Loan' and it should include at least one fee.</errorMessage>
        <filterItems>
            <field>loan__Fee_Set__c.loan__Fee_Set_Category__c</field>
            <operation>equals</operation>
            <value>Loan</value>
        </filterItems>
        <filterItems>
            <field>loan__Fee_Set__c.loan__Number_of_Fees__c</field>
            <operation>notEqual</operation>
            <value>0</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>loan__Fee_Set__c</referenceTo>
    <relationshipName>Loan_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/loan__Org_Parameters__c/loan__Org_Parameters__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Org Parameters</label>
</CustomObject>

unpackaged/main/default/objects/loan__Org_Parameters__c/fields/loan__Disable_Triggers__c.field-meta.xml
<CustomField>
    <fullName>loan__Disable_Triggers__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>This disables all the triggers. It is to be used only while migrating data into the system. It must be disabled otherwise.</inlineHelpText>
    <label>Disable Triggers</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/LoanPaymentDays__c/LoanPaymentDays__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>LoanPaymentDays - For Remainder Mails</description>
    <label>LoanPaymentDays</label>
</CustomObject>

unpackaged/main/default/objects/LoanPaymentDays__c/fields/AutoPaymentRemainder__c.field-meta.xml
<CustomField>
    <fullName>AutoPaymentRemainder__c</fullName>
    <label>AutoPaymentRemainder</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/LoanPaymentDays__c/fields/ManualPaymentRemainder__c.field-meta.xml
<CustomField>
    <fullName>ManualPaymentRemainder__c</fullName>
    <label>ManualPaymentRemainder</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/MigrationPhase__c/MigrationPhase__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>MigrationPhase</label>
</CustomObject>

unpackaged/main/default/objects/MigrationPhase__c/fields/phase__c.field-meta.xml
<CustomField>
    <fullName>phase__c</fullName>
    <label>phase</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/TestActivateFractionalizationBatch.cls
/* ****************Modification History******************
*    Created By        	 Date			Version
*1. Bhavya Maliwal        2022/02/16    LSP-546 Initial Version

******************Modification History******************/
@isTest
private class TestActivateFractionalizationBatch{

   public static String CRON_EXP = '0 0 0 15 3 ? 2022';
   @testSetup static void setup() {
   
       loan.TestHelper.createSeedDataForTesting();
       //pallavi
        MigrationPhase__c phase = new MigrationPhase__c();
        phase.name = 'phase1';
        phase.phase__c = 'phase1';
        insert phase;
        //pallavi
       loan__Currency__c curr = loan.TestHelper.createCurrency();
       //Create a dummy MF_Account
        loan__MF_Account__c dummyAccount = loan.TestHelper.createMFAccount('XXXAccountForTest','10000 - ASSETS');
        loan__MF_Account__c dummyIncAccount = loan.TestHelper.createMFAccount('XXXIncAccountForTest','30000 - INCOME');
     
        //Create a Fee Set
        loan__Fee__c dummyFee = loan.TestHelper.createFee(curr,dummyIncAccount ,dummyAccount);                                    
        loan__Fee_Set__c dummyFeeSet = loan.TestHelper.createFeeSet();
        loan__Fee_Junction__c dummyFeeJunction = loan.TestHelper.createFeeJunction(dummyFee,dummyFeeSet);
        
        loan__Office_Name__c dummyOffice = loan.TestHelper.createOffice();
        
        loan__Org_Parameters__c org = loan__Org_Parameters__c.getOrgDefaults();
         org.loan__Disable_Triggers__c = true;
         upsert org;  
   
        //Creating Account
         Account acc = new Account(
            Name = 'Test',
            loan__Investor__c=False,
             peer__Last_Name__c='TestLName2',
            //Borrower_s_Last_Name__c='Testborrower',
            cnotify__Email__c = 'abc@test.com',
            loan__SOCIAL_SECURITY_NUMBER__c = '123123123'
            );
        insert acc;
        System.assertEquals('Test',acc.Name,'Wrong Account');
        
        LoanPaymentDays__c lpdays = new LoanPaymentDays__c();
        lpdays.AutoPaymentRemainder__c= 3;
        lpdays.ManualPaymentRemainder__c= 5;
        insert lpdays;
        
        loan__Loan_Product__c loanProdObj = new loan__Loan_Product__c(name='TestProduct'); 
        insert loanProdObj;
        System.assertEquals('TestProduct', loanProdObj.Name,'Wrong Loan Product');
        
        
        loan__Loan_Account__c lacc = new loan__Loan_Account__c(
                                            loan__Account__c= acc.Id,
                                            loan__Product_Type__c='Flexible Amz Loan',
                                            loan__Loan_Amount__c =1000,
                                            loan__Loan_Product_Name__c=loanProdObj.Id,
                                            loan__Payment_Amount__c=100, 
                                            loan__Next_Installment_Date__c=system.today(), 
                                            loan__Previous_Installment_Date__c= system.today()
                                            );
        insert lacc; 
        
        
        
   }
     /*Created By : Bhavya Maliwal
Method name : ActivateFractionalizationBatch_SetofLoanIds_Constructor
Purpose : to cover code satisfying constructor where Set of loan Ids is passed and for Batch execution,  for ActivateFractionalizationBatch
*/
   Testmethod static void ActivateFractionalizationBatch_SetofLoanIds_Constructor(){
        List<loan__Loan_Account__c> lappList = [SELECT ID, 
                                                    loan__Previous_Installment_Date__c,
                                                    loan__Account__r.cnotify__Email__c,
                                                    loan__Loan_Product_Name__r.name, 
                                                    loan__Payment_Amount__c, 
                                                    loan__Next_Installment_Date__c, 
                                                    loan__Account__r.ID,Borrowers_First_Name__c,
                                                    loan__Account__r.Borrower_s_Last_Name__c,
                                                    loan__Loan_Product_Name__c 
                                                    from loan__Loan_Account__c];
                                                    
        System.debug('==============lapp=============='+lappList);
        test.startTest();
        Set<Id> Idset = new Set<Id>();
        for(loan__Loan_Account__c lc : lappList){
            Idset.add(lc.id);
        }
        ActivateFractionalizationBatch job = new ActivateFractionalizationBatch(Idset);
        Database.QueryLocator ql = job.start(null);
        job.execute(null,lappList);
        ID batchprocessid = Database.executeBatch(job);
        job.finish(null);
       
        test.stopTest();
    }
     /*Created By : Bhavya Maliwal
Method name : ActivateFractionalizationBatch_default_Constructor
Purpose : to cover code satisfying default constructor and Batch execution for ActivateFractionalizationBatch
*/
     Testmethod static void ActivateFractionalizationBatch_default_Constructor(){
        List<loan__Loan_Account__c> lappList = [SELECT ID, 
                                                    loan__Previous_Installment_Date__c,
                                                    loan__Account__r.cnotify__Email__c,
                                                    loan__Loan_Product_Name__r.name, 
                                                    loan__Payment_Amount__c, 
                                                    loan__Next_Installment_Date__c, 
                                                    loan__Account__r.ID,Borrowers_First_Name__c,
                                                    loan__Account__r.Borrower_s_Last_Name__c,
                                                    loan__Loan_Product_Name__c 
                                                    from loan__Loan_Account__c];
                                                    
        System.debug('==============lapp=============='+lappList);
        test.startTest();
      ActivateFractionalizationBatch b = new ActivateFractionalizationBatch();
        test.stopTest();
    }
     /*Created By : Bhavya Maliwal
Method name : InvestorAllocation_runInvestorAllocationBasedOnWeighting
Purpose : to cover code satisfying constructor where thread is passed and for Batch execution, for ActivateFractionalizationBatch
*/
     Testmethod static void ActivateFractionalizationBatch_thread_Constructor(){
        List<loan__Loan_Account__c> lappList = [SELECT ID, 
                                                    loan__Previous_Installment_Date__c,
                                                    loan__Account__r.cnotify__Email__c,
                                                    loan__Loan_Product_Name__r.name, 
                                                    loan__Payment_Amount__c, 
                                                    loan__Next_Installment_Date__c, 
                                                    loan__Account__r.ID,Borrowers_First_Name__c,
                                                    loan__Account__r.Borrower_s_Last_Name__c,
                                                    loan__Loan_Product_Name__c 
                                                    from loan__Loan_Account__c];
                                                    
        System.debug('==============lapp=============='+lappList);
        test.startTest();
        ActivateFractionalizationBatch b1 = new ActivateFractionalizationBatch(1);
       test.stopTest();
    }

}