unpackaged/main/default/objects/Account/fields/Borrower_s_Email__c.field-meta.xml
<CustomField>
    <fullName>Borrower_s_Email__c</fullName>
    <description>/*Created By Nupur */
For Email Alert</description>
    <formula>IF( RecordType.Name='Member',ints__Email__c , Null)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Borrower's Email</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Borrower_s_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Borrower_s_Last_Name__c</fullName>
    <description>/*Created by Nupur */
 - For Email Templates</description>
    <formula>IF( RecordType.Name='Member' , peer__Last_Name__c,NULL)</formula>
    <label>Borrower's Last Name</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/cnotify__Email__c.field-meta.xml
<CustomField>
    <fullName>cnotify__Email__c</fullName>
    <label>Email</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/loan__Investor__c.field-meta.xml
<CustomField>
    <fullName>loan__Investor__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Investor</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/loan__SOCIAL_SECURITY_NUMBER__c.field-meta.xml
<CustomField>
    <fullName>loan__SOCIAL_SECURITY_NUMBER__c</fullName>
    <label>SOCIAL_SECURITY_NUMBER</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Application_Tags__c/Application_Tags__c.object-meta.xml
<CustomObject>
    <label>Application Tag</label>
    <nameField>
        <label>Application Tags Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application Tags</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Application_Tags__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <label>Application</label>
    <referenceTo>genesis__Applications__c</referenceTo>
    <relationshipLabel>Application Tags</relationshipLabel>
    <relationshipName>Application_Tags</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/CL_Document__c/CL_Document__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>CL_Generated Documents Names</description>
    <label>CL Document</label>
</CustomObject>

unpackaged/main/default/objects/CL_Document__c/fields/Doc1__c.field-meta.xml
<CustomField>
    <fullName>Doc1__c</fullName>
    <label>Doc1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/CL_Document__c/fields/Doc2__c.field-meta.xml
<CustomField>
    <fullName>Doc2__c</fullName>
    <inlineHelpText>TIL Document</inlineHelpText>
    <label>Doc2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/genesis__Application_Document_Category__c/genesis__Application_Document_Category__c.object-meta.xml
<CustomObject>
    <label>Application Document Category</label>
    <nameField>
        <label>Application Document Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application Document Category</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/genesis__Application_Document_Category__c/fields/Borrower_s_Email__c.field-meta.xml
<CustomField>
    <fullName>Borrower_s_Email__c</fullName>
    <description>/* Created By Nupur */

------ For Email Alerts --pending_document_reminder.liquid</description>
    <label>Borrower's Email</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/genesis__Application_Document_Category__c/fields/genesis__Application__c.field-meta.xml
<CustomField>
    <fullName>genesis__Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>genesis__Applications__c</referenceTo>
    <relationshipLabel>Application Document Category</relationshipLabel>
    <relationshipName>Application_Document_Category</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/genesis__Application_Document_Category__c/fields/genesis__Document_Category__c.field-meta.xml
<CustomField>
    <fullName>genesis__Document_Category__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Document Category</label>
    <referenceTo>genesis__Document_Category__c</referenceTo>
    <relationshipLabel>Application Document Category</relationshipLabel>
    <relationshipName>Application_Document_Category</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/genesis__Application_Document_Category__c/fields/genesis__Required__c.field-meta.xml
<CustomField>
    <fullName>genesis__Required__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Required</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/genesis__Application_Document_Category__c/fields/genesis__Status__c.field-meta.xml
<CustomField>
    <fullName>genesis__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>OPEN</fullName>
                <default>true</default>
                <label>OPEN</label>
            </value>
            <value>
                <fullName>SUBMITTED</fullName>
            </value>
            <value>
                <fullName>CLEARED</fullName>
            </value>
            <value>
                <fullName>REJECTED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/genesis__Applications__c/genesis__Applications__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{0000000000}</displayFormat>
        <label>Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/genesis__Applications__c/fields/Application_Start_DateV2__c.field-meta.xml
<CustomField>
    <fullName>Application_Start_DateV2__c</fullName>
    <label>Application Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/genesis__Applications__c/fields/Borrower_s_Email__c.field-meta.xml
<CustomField>
    <fullName>Borrower_s_Email__c</fullName>
    <description>/*Created By Nupur */ 
For Email Alert</description>
    <label>Borrower's Email</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/genesis__Applications__c/fields/DocuSignFlag__c.field-meta.xml
<CustomField>
    <fullName>DocuSignFlag__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Checked - DocuSign Email sent</description>
    <label>DocuSignFlag</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/genesis__Applications__c/fields/genesis__Account__c.field-meta.xml
<CustomField>
    <fullName>genesis__Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Applications_account</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/genesis__Applications__c/fields/genesis__Draw_Period_End_Date__c.field-meta.xml
<CustomField>
    <fullName>genesis__Draw_Period_End_Date__c</fullName>
    <label>Draw Period End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/genesis__Applications__c/fields/genesis__Due_Day__c.field-meta.xml
<CustomField>
    <fullName>genesis__Due_Day__c</fullName>
    <description>dueDay field.</description>
    <inlineHelpText>If Due Day field is null, then by default it will have Expected First Payment Date day value</inlineHelpText>
    <label>Due_Day</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/genesis__Applications__c/fields/genesis__Expected_First_Payment_Date__c.field-meta.xml
<CustomField>
    <fullName>genesis__Expected_First_Payment_Date__c</fullName>
    <label>Expected First Payment Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/genesis__Applications__c/fields/genesis__Expected_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>genesis__Expected_Start_Date__c</fullName>
    <label>Expected Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/genesis__Applications__c/fields/genesis__Funding_in_Tranches__c.field-meta.xml
<CustomField>
    <fullName>genesis__Funding_in_Tranches__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Funding in Tranches</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/genesis__Applications__c/fields/genesis__Status__c.field-meta.xml
<CustomField>
    <fullName>genesis__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>APPROVED - APPROVED</fullName>
            </value>
            <value>
                <fullName>APPROVED - CONVERTED TO CONTRACT</fullName>
            </value>
            <value>
                <fullName>APPROVED - DOCUMENT CHECK</fullName>
            </value>
            <value>
                <fullName>NEW - CREDIT PULLED</fullName>
            </value>
            <value>
                <fullName>NEW - ENTERED</fullName>
                <default>true</default>
                <label>NEW - ENTERED</label>
            </value>
            <value>
                <fullName>NEW - IN CREDIT CHECK</fullName>
            </value>
            <value>
                <fullName>NEW - IN REVIEW</fullName>
            </value>
            <value>
                <fullName>NEW - PRICING GENERATED</fullName>
            </value>
            <value>
                <fullName>NEW - SCORECARD GENERATED</fullName>
            </value>
            <value>
                <fullName>NEW - CHECKLIST GENERATED</fullName>
            </value>
            <value>
                <fullName>NEW - VEHICLE VALUATION REQUIRED</fullName>
            </value>
            <value>
                <fullName>REJECTED</fullName>
            </value>
            <value>
                <fullName>PULL CREDIT</fullName>
            </value>
            <value>
                <fullName>Default Documents</fullName>
            </value>
            <value>
                <fullName>offer_accepted</fullName>
            </value>
            <value>
                <fullName>offer_shown</fullName>
            </value>
            <value>
                <fullName>kba_success</fullName>
            </value>
            <value>
                <fullName>kba_fail</fullName>
            </value>
            <value>
                <fullName>agent_document_verification_pending</fullName>
            </value>
            <value>
                <fullName>agent_verification_pending</fullName>
            </value>
            <value>
                <fullName>agent_verified</fullName>
            </value>
            <value>
                <fullName>docusign_loan_docs_sent</fullName>
            </value>
            <value>
                <fullName>docusign_loan_docs_complete</fullName>
            </value>
            <value>
                <fullName>pre_funding</fullName>
            </value>
            <value>
                <fullName>Approved for funding</fullName>
            </value>
            <value>
                <fullName>funded</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Stacker_Check_Passed</fullName>
            </value>
            <value>
                <fullName>Redecision_Required</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/genesis__Document_Category__c/genesis__Document_Category__c.object-meta.xml
<CustomObject>
    <label>Document Category</label>
    <nameField>
        <displayFormat>DC-{00000000}</displayFormat>
        <label>Document Category Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Document Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/genesis__Document_Category__c/fields/genesis__Category_Name__c.field-meta.xml
<CustomField>
    <fullName>genesis__Category_Name__c</fullName>
    <label>Category Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/genesis__Document_Category__c/fields/genesis__Required__c.field-meta.xml
<CustomField>
    <fullName>genesis__Required__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Required</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/TLO_URL_Config__c/TLO_URL_Config__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>TLO URL Config</label>
</CustomObject>

unpackaged/main/default/objects/TLO_URL_Config__c/fields/TLO_URL__c.field-meta.xml
<CustomField>
    <fullName>TLO_URL__c</fullName>
    <label>TLO URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/TLO_URL_Config__c/fields/TLOURLappname__c.field-meta.xml
<CustomField>
    <fullName>TLOURLappname__c</fullName>
    <label>TLOURLappname</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/TestPayoffTags.cls
@isTest
public class TestPayoffTags {
     testmethod static void method1(){
         /*CRM-32*/
         TLO_URL_Config__c tlo = new TLO_URL_Config__c();
         tlo.TLO_URL__c = 'https://doppio-leads-dev.int.payoff.com/';
         tlo.TLOURLappname__c = 'verification';   
         insert tlo;
         /*CRM-32*/
         //Creating Account
         Account acc = new Account(
            Name = 'Test',
            loan__Investor__c=False,
            //Borrower_s_Last_Name__c='Testborrower',
            cnotify__Email__c = 'abc@test.com',
            loan__SOCIAL_SECURITY_NUMBER__c = '123'
            );
        insert acc;
         List<Id> IDs = new List<Id>();
        System.assertEquals('Test',acc.Name,'Wrong Account');
         //Creating Application
        genesis__Applications__c app1= new genesis__Applications__c(
                                            genesis__Due_Day__c = 10,
                                            genesis__Expected_First_Payment_Date__c = system.Today(),
                                            genesis__Expected_Start_Date__c = system.Today(),
                                            genesis__Funding_in_Tranches__c = true,
                                            Borrower_s_Email__c = null,
                                            genesis__Account__c = acc.Id,
                                            Application_Start_DateV2__c = system.Today(),
                                            DocuSignFlag__c=true,
                                            genesis__Status__c = 'agent_verified',
                                            genesis__Draw_Period_End_Date__c = system.Today()
                                            );
        insert app1;
         IDs.add(app1.id);
        System.assertEquals(null,app1.Borrower_s_Email__c,'Borrower Email is not null');
         genesis__Applications__c app= new genesis__Applications__c(
                                            genesis__Due_Day__c = 20,
                                            genesis__Expected_First_Payment_Date__c = system.Today(),
                                            genesis__Expected_Start_Date__c = system.Today(),
                                            genesis__Funding_in_Tranches__c = true,
                                            Borrower_s_Email__c = null,
                                            genesis__Account__c = acc.Id,
                                            Application_Start_DateV2__c = system.Today(),
                                            DocuSignFlag__c=true,
                                            genesis__Status__c = 'offer_accepted',
                                            genesis__Draw_Period_End_Date__c = system.Today()
                                            );
        insert app;
         IDs.add(app.id);
        System.assertEquals(null,app.Borrower_s_Email__c,'Borrower Email is not null');
        test.startTest();
         PayoffTags.TagsParameter t = new PayoffTags.TagsParameter();
         t.apps = app.id;
         t.tag = 'Test';
         List<PayoffTags.TagsParameter> tagList = new List<PayoffTags.TagsParameter>();
         taglist.add(t);
        PayoffTags.appToPayoffTags(taglist);
        test.stopTest();
     }
     testmethod static void method2(){
         //Creating Account
         CL_Document__c cs = new CL_Document__c();
         cs.Doc1__c = 'Credit';
         cs.Doc2__c = 'Til';
         insert cs;
         
         /*CRM-32*/
         TLO_URL_Config__c tlo = new TLO_URL_Config__c();
         tlo.TLO_URL__c = 'https://doppio-leads-dev.int.payoff.com/';
         tlo.TLOURLappname__c = 'verification';   
         insert tlo;
         /*CRM-32*/

         Account acc = new Account(
            Name = 'Test',
            loan__Investor__c=False,
            //Borrower_s_Last_Name__c='Testborrower',
            cnotify__Email__c = 'abc@test.com',
            loan__SOCIAL_SECURITY_NUMBER__c = '123'
            );
        insert acc;
         List<Id> IDs = new List<Id>();
        System.assertEquals('Test',acc.Name,'Wrong Account');
         //Creating Application
        genesis__Applications__c app1= new genesis__Applications__c(
                                            genesis__Due_Day__c = 10,
                                            genesis__Expected_First_Payment_Date__c = system.Today(),
                                            genesis__Expected_Start_Date__c = system.Today(),
                                            genesis__Funding_in_Tranches__c = true,
                                            Borrower_s_Email__c = null,
                                            genesis__Account__c = acc.Id,
                                            Application_Start_DateV2__c = system.Today(),
                                            DocuSignFlag__c=true,
                                            genesis__Status__c = 'agent_verified',
                                            genesis__Draw_Period_End_Date__c = system.Today()
                                            );
        insert app1;
         IDs.add(app1.id);
        System.assertEquals(null,app1.Borrower_s_Email__c,'Borrower Email is not null');
         genesis__Applications__c app= new genesis__Applications__c(
                                            genesis__Due_Day__c = 20,
                                            genesis__Expected_First_Payment_Date__c = system.Today(),
                                            genesis__Expected_Start_Date__c = system.Today(),
                                            genesis__Funding_in_Tranches__c = true,
                                            Borrower_s_Email__c = null,
                                            genesis__Account__c = acc.Id,
                                            Application_Start_DateV2__c = system.Today(),
                                            DocuSignFlag__c=true,
                                            genesis__Status__c = 'offer_accepted',
                                            genesis__Draw_Period_End_Date__c = system.Today()
                                            );
        insert app;
         genesis__Document_Category__c docCat = new genesis__Document_Category__c(
            genesis__Category_Name__c = 'Test_Paystub_Id',
            genesis__Required__c = true
        );
        Insert docCat;
        genesis__Application_Document_Category__c appDocCat = new genesis__Application_Document_Category__c(
            Name = 'Test_AppDocCat',
            genesis__Document_Category__c = docCat.Id,
            genesis__Application__c = app.Id,
            genesis__Status__c = 'SUBMITTED'
        );
         Insert appDocCat;
         IDs.add(app.id);
        //System.assertEquals(null,app.Borrower_s_Email__c,'Borrower Email is not null');
        test.startTest();
         PayoffTags.TagsParameter t = new PayoffTags.TagsParameter();
         t.apps = app.id;
         t.tag = 'Test';
         List<PayoffTags.TagsParameter> tagList = new List<PayoffTags.TagsParameter>();
         taglist.add(t);
        PayoffTags.appToPayoffTags(taglist);
        test.stopTest();
     }
    testmethod static void method3(){
         /*CRM-32*/
         TLO_URL_Config__c tlo = new TLO_URL_Config__c();
         tlo.TLO_URL__c = 'https://doppio-leads-dev.int.payoff.com/';
         tlo.TLOURLappname__c = 'verification';   
         insert tlo;
         /*CRM-32*/
         //Creating Account
         Account acc = new Account(
            Name = 'Test',
            loan__Investor__c=False,
            //Borrower_s_Last_Name__c='Testborrower',
            cnotify__Email__c = 'abc@test.com',
            loan__SOCIAL_SECURITY_NUMBER__c = '123'
            );
        insert acc;
         List<Id> IDs = new List<Id>();
        System.assertEquals('Test',acc.Name,'Wrong Account');
         //Creating Application
        genesis__Applications__c app1= new genesis__Applications__c(
                                            genesis__Due_Day__c = 10,
                                            genesis__Expected_First_Payment_Date__c = system.Today(),
                                            genesis__Expected_Start_Date__c = system.Today(),
                                            genesis__Funding_in_Tranches__c = true,
                                            Borrower_s_Email__c = null,
                                            genesis__Account__c = acc.Id,
                                            Application_Start_DateV2__c = system.Today(),
                                            DocuSignFlag__c=true,
                                            genesis__Status__c = 'agent_verified',
                                            genesis__Draw_Period_End_Date__c = system.Today()
                                            );
        insert app1;
         IDs.add(app1.id);
        System.assertEquals(null,app1.Borrower_s_Email__c,'Borrower Email is not null');
         genesis__Applications__c app= new genesis__Applications__c(
                                            genesis__Due_Day__c = 20,
                                            genesis__Expected_First_Payment_Date__c = system.Today(),
                                            genesis__Expected_Start_Date__c = system.Today(),
                                            genesis__Funding_in_Tranches__c = true,
                                            Borrower_s_Email__c = null,
                                            genesis__Account__c = acc.Id,
                                            Application_Start_DateV2__c = system.Today(),
                                            DocuSignFlag__c=true,
                                            genesis__Status__c = 'offer_accepted',
                                            genesis__Draw_Period_End_Date__c = system.Today()
                                            );
        insert app;
        /* genesis__Document_Category__c docCat = new genesis__Document_Category__c(
            genesis__Category_Name__c = 'Test_Paystub_Id',
            genesis__Required__c = true
        );
        Insert docCat;
        genesis__Application_Document_Category__c appDocCat = new genesis__Application_Document_Category__c(
            Name = 'Test_AppDocCat',
            genesis__Document_Category__c = docCat.Id,
            genesis__Application__c = app.Id,
            genesis__Status__c = 'SUBMITTED'
        );
         Insert appDocCat;*/
        Application_Tags__c apptags = new Application_Tags__c(
            Application__c = app.Id,
        Application_Tag__c = 'New Documents');
         IDs.add(app.id);
        //System.assertEquals(null,app.Borrower_s_Email__c,'Borrower Email is not null');
        test.startTest();
         PayoffTags.TagsParameter t = new PayoffTags.TagsParameter();
         t.apps = app.id;
         t.tag = 'New Interaction';
         List<PayoffTags.TagsParameter> tagList = new List<PayoffTags.TagsParameter>();
         taglist.add(t);
        PayoffTags.appToPayoffTags(taglist);
        test.stopTest();
     }
}