unpackaged/main/default/objects/Account/fields/BoxFolderID__c.field-meta.xml
<CustomField>
    <fullName>BoxFolderID__c</fullName>
    <label>BoxFolderID</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/loan__SOCIAL_SECURITY_NUMBER__c.field-meta.xml
<CustomField>
    <fullName>loan__SOCIAL_SECURITY_NUMBER__c</fullName>
    <label>SOCIAL_SECURITY_NUMBER</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/peer__First_Name__c.field-meta.xml
<CustomField>
    <fullName>peer__First_Name__c</fullName>
    <label>First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/peer__Last_Name__c.field-meta.xml
<CustomField>
    <fullName>peer__Last_Name__c</fullName>
    <label>Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/social_security_number_uniqueness_field__c.field-meta.xml
<CustomField>
    <fullName>social_security_number_uniqueness_field__c</fullName>
    <label>Social Security Number</label>
    <length>128</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Member.recordType-meta.xml
<RecordType>
    <fullName>Member</fullName>
    <active>true</active>
    <label>Member</label>
</RecordType>

unpackaged/main/default/objects/genesis__Applications__c/genesis__Applications__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{0000000000}</displayFormat>
        <label>Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/genesis__Applications__c/fields/BoxFolderID__c.field-meta.xml
<CustomField>
    <fullName>BoxFolderID__c</fullName>
    <label>BoxFolderID</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/genesis__Applications__c/fields/Bureau_SSN__c.field-meta.xml
<CustomField>
    <fullName>Bureau_SSN__c</fullName>
    <label>Bureau SSN</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/genesis__Applications__c/fields/genesis__Account__c.field-meta.xml
<CustomField>
    <fullName>genesis__Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Applications_account</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/genesis__Applications__c/fields/genesis__CL_Product__c.field-meta.xml
<CustomField>
    <fullName>genesis__CL_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CL Product</label>
    <referenceTo>clcommon__CL_Product__c</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/genesis__Applications__c/fields/genesis__Status__c.field-meta.xml
<CustomField>
    <fullName>genesis__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>APPROVED - APPROVED</fullName>
            </value>
            <value>
                <fullName>APPROVED - CONVERTED TO CONTRACT</fullName>
            </value>
            <value>
                <fullName>APPROVED - DOCUMENT CHECK</fullName>
            </value>
            <value>
                <fullName>NEW - CREDIT PULLED</fullName>
            </value>
            <value>
                <fullName>NEW - ENTERED</fullName>
                <default>true</default>
                <label>NEW - ENTERED</label>
            </value>
            <value>
                <fullName>NEW - IN CREDIT CHECK</fullName>
            </value>
            <value>
                <fullName>NEW - IN REVIEW</fullName>
            </value>
            <value>
                <fullName>NEW - PRICING GENERATED</fullName>
            </value>
            <value>
                <fullName>NEW - SCORECARD GENERATED</fullName>
            </value>
            <value>
                <fullName>NEW - CHECKLIST GENERATED</fullName>
            </value>
            <value>
                <fullName>NEW - VEHICLE VALUATION REQUIRED</fullName>
            </value>
            <value>
                <fullName>REJECTED</fullName>
            </value>
            <value>
                <fullName>PULL CREDIT</fullName>
            </value>
            <value>
                <fullName>Default Documents</fullName>
            </value>
            <value>
                <fullName>offer_accepted</fullName>
            </value>
            <value>
                <fullName>offer_shown</fullName>
            </value>
            <value>
                <fullName>kba_success</fullName>
            </value>
            <value>
                <fullName>kba_fail</fullName>
            </value>
            <value>
                <fullName>agent_document_verification_pending</fullName>
            </value>
            <value>
                <fullName>agent_verification_pending</fullName>
            </value>
            <value>
                <fullName>agent_verified</fullName>
            </value>
            <value>
                <fullName>docusign_loan_docs_sent</fullName>
            </value>
            <value>
                <fullName>docusign_loan_docs_complete</fullName>
            </value>
            <value>
                <fullName>pre_funding</fullName>
            </value>
            <value>
                <fullName>Approved for funding</fullName>
            </value>
            <value>
                <fullName>funded</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Stacker_Check_Passed</fullName>
            </value>
            <value>
                <fullName>Redecision_Required</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/genesis__Applications__c/fields/Lead_ID__c.field-meta.xml
<CustomField>
    <fullName>Lead_ID__c</fullName>
    <description>This is the LEAD GUID received from FE</description>
    <externalId>true</externalId>
    <label>Lead ID</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/genesis__Applications__c/fields/Required_Docs_Count__c.field-meta.xml
<CustomField>
    <fullName>Required_Docs_Count__c</fullName>
    <label>Required Docs Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/loan__Loan_Account__c/loan__Loan_Account__c.object-meta.xml
<CustomObject>
    <description>Lending Account</description>
    <label>CL Contract</label>
    <nameField>
        <displayFormat>LAI-{00000000}</displayFormat>
        <label>CL Contract ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CL Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/loan__Loan_Account__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>genesis__Applications__c</referenceTo>
    <relationshipLabel>CL Contracts</relationshipLabel>
    <relationshipName>CL_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/loan__Loan_Account__c/fields/lead_Guid__c.field-meta.xml
<CustomField>
    <fullName>lead_Guid__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>lead_Guid</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/loan__Loan_Account__c/fields/loan__Account__c.field-meta.xml
<CustomField>
    <fullName>loan__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Please choose a account, which will be associated as a customer on this lending account.
You can create a new account, from the lookup window by clicking on new or select the existing account from the lookup.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Loan_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/loan__Loan_Account__c/fields/loan__Loan_Product_Name__c.field-meta.xml
<CustomField>
    <fullName>loan__Loan_Product_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Loan Product Name</description>
    <inlineHelpText>Please choose a lending product, which will be associated as a lending product on this lending account.
You can choose a existing product from the lookup or create a new product from 
Servicing Configuration-&gt;Product-&gt;Create new lending product</inlineHelpText>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Please select active lending product.</errorMessage>
        <filterItems>
            <field>loan__Loan_Product__c.loan__Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>loan__Loan_Product__c</referenceTo>
    <relationshipName>Loan_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/loan__Loan_Account__c/fields/loan__Loan_Status__c.field-meta.xml
<CustomField>
    <fullName>loan__Loan_Status__c</fullName>
    <inlineHelpText>Status of the Account, expected values are :
Pending Approval
Active - Good Standing
Active - Bad Standing
Active - Matured
Approved
Canceled
Closed - Obligations met
Closed- Written Off
Closed - Refinanced
Partial Application</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Partial Application</fullName>
                <default>true</default>
                <label>Partial Application</label>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Active - Good Standing</fullName>
            </value>
            <value>
                <fullName>Active - Bad Standing</fullName>
            </value>
            <value>
                <fullName>Closed - Obligations met</fullName>
            </value>
            <value>
                <fullName>Closed- Written Off</fullName>
            </value>
            <value>
                <fullName>Closed - Refinanced</fullName>
            </value>
            <value>
                <fullName>Active - Matured</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Active - Marked for Closure</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/loan__Loan_Product__c/loan__Loan_Product__c.object-meta.xml
<CustomObject>
    <description>Lending Product Definition1</description>
    <label>Lending Product</label>
    <nameField>
        <label>Loan Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lending Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/loan__Loan_Status__c/loan__Loan_Status__c.object-meta.xml
<CustomObject>
    <description>Object for storing Loan Statuses</description>
    <label>Loan Status</label>
    <nameField>
        <label>Loan Status Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loan Status</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/loan__Office_Name__c/loan__Office_Name__c.object-meta.xml
<CustomObject>
    <description>Name of the office</description>
    <label>Company</label>
    <nameField>
        <label>Company</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/classes/MW_ApplicationServiceTest.cls
/*
Include existing test class - 'TestCustomTriggerOnApplication.cls' as well for increasing coverage. 
Mohan Kiran - 09/26/2022 - Made changes to fix test failures.
*/
@isTest
private class MW_ApplicationServiceTest {
    @testSetup 
    static void setup(){
        
        test.startTest();
        
        //Create pre-exist account
        Account preExistAct = MW_GlobalTestUtility.GetAccount('Member');
        //preExistAct.Name = 'PreExistAct';
        preExistAct.peer__First_Name__c ='PreExist';
        preExistAct.peer__Last_Name__c = 'Act';
        Insert preExistAct;
        System.debug('preExistAct=' + preExistAct);
        
        //Create app for pre-exist account
        genesis__Applications__c appForPreExistAct = MW_GlobalTestUtility.GetApplication();
        appForPreExistAct.genesis__Account__c = preExistAct.Id;
        appForPreExistAct.Bureau_SSN__c = preExistAct.loan__SOCIAL_SECURITY_NUMBER__c;
        Insert appForPreExistAct;
        
        //Create Loan for pre-exist account
        loan.TestHelper.createSeedDataForTesting();
        loan__Office_Name__c office = loan.TestHelper.createOffice();
        loan__Loan_Product__c loanProd = MW_GlobalTestUtility.GetLoanProduct(); 
        insert loanProd;
        
        loan__Loan_Account__c loanForPreExistAcct = MW_GlobalTestUtility.GetCLContract();
        loanForPreExistAcct.loan__Account__c= preExistAct.Id;
        loanForPreExistAcct.loan__Loan_Product_Name__c=loanProd.Id;
        loanForPreExistAcct.application__c = appForPreExistAct.id;
        loanForPreExistAcct.loan__Loan_Status__c = 'Closed - Obligations met'; //'Active - Good Standing';
        Insert loanForPreExistAcct;
        
        //Create one more Account
        Account actWithDuplicateSsn = MW_GlobalTestUtility.GetAccount('Member');
        //actWithDuplicateSsn.Name = 'ActWithDuplicateSsn';
        actWithDuplicateSsn.peer__First_Name__c ='ActWithDuplicate';
        actWithDuplicateSsn.peer__Last_Name__c = 'Ssn';
        actWithDuplicateSsn.loan__SOCIAL_SECURITY_NUMBER__c = null;
        actWithDuplicateSsn.social_security_number_uniqueness_field__c = '123987123';
        Insert actWithDuplicateSsn;
        
        //Create app for one more account with duplicate SSN
        genesis__Applications__c appForDuplicateAct = MW_GlobalTestUtility.GetApplication();
        appForDuplicateAct.genesis__Account__c = actWithDuplicateSsn.Id;
        appForDuplicateAct.Bureau_SSN__c = actWithDuplicateSsn.loan__SOCIAL_SECURITY_NUMBER__c;
        appForDuplicateAct.genesis__Status__c = null;
        appForDuplicateAct.LEAD_ID__C = 'c9149473-e69f-ee12-38a7-d18b0cba847z';
        Insert appForDuplicateAct;
        
        loan__Loan_Product__c loanProd1 = MW_GlobalTestUtility.GetLoanProduct(); 
        loanProd1.name = 'TestProductNew';
        insert loanProd1;
        
        loan__Loan_Account__c loanForDuplicateSSN = MW_GlobalTestUtility.GetCLContract();
        loanForDuplicateSSN.loan__Account__c= actWithDuplicateSsn.Id;
        loanForDuplicateSSN.loan__Loan_Product_Name__c=loanProd1.Id;
        loanForDuplicateSSN.application__c = appForDuplicateAct.id;
        loanForDuplicateSSN.loan__Loan_Status__c = 'Closed - Obligations met'; 
        loanForDuplicateSSN.lead_guid__c = 'TestClassGuid01';
        Insert loanForDuplicateSSN;
        
        Account preExistAct2 = MW_GlobalTestUtility.GetAccount('Member');
        //preExistAct2.Name = 'preExistAct2';
        preExistAct2.peer__First_Name__c ='PreExist';
        preExistAct2.peer__Last_Name__c = 'Act2';
        //preExistAct2.social_security_number_uniqueness_field__c = '';
        Insert preExistAct2;
        
        //Create one more Account
        Account actWithDuplicateSsn2 = MW_GlobalTestUtility.GetAccount('Member');
        //actWithDuplicateSsn2.Name = 'actWithDuplicateSsn2';
        actWithDuplicateSsn2.peer__First_Name__c ='ActWithDuplicate';
        actWithDuplicateSsn2.peer__Last_Name__c = 'Ssn2';
        actWithDuplicateSsn2.loan__SOCIAL_SECURITY_NUMBER__c = null;
        Insert actWithDuplicateSsn2;
        
        //Create app for one more account with duplicate SSN
        genesis__Applications__c appForDuplicateAct2 = MW_GlobalTestUtility.GetApplication();
        appForDuplicateAct2.genesis__Account__c = actWithDuplicateSsn2.Id;
        appForDuplicateAct2.Bureau_SSN__c = preExistAct2.loan__SOCIAL_SECURITY_NUMBER__c;
        appForDuplicateAct2.genesis__Status__c = null;
        Insert appForDuplicateAct2;
        
        Test.stopTest();
    }
    
    @isTest static void TestPifLoanUpdates(){
        test.startTest();
        genesis__Applications__c appForDuplicateAct2 = [SELECT Id, Name, Bureau_SSN__c, genesis__Status__c, genesis__Account__c FROM genesis__Applications__c WHERE genesis__Account__r.Name = 'ActWithDuplicate Ssn2' LIMIT 1];
        appForDuplicateAct2.Required_Docs_Count__c=0;
        appForDuplicateAct2.genesis__Status__c = 'offer_shown';
        update appForDuplicateAct2;
        
        list<genesis__Applications__c> appList = new list<genesis__Applications__c>();
        Account preExistAct = [SELECT Id, Name, loan__SOCIAL_SECURITY_NUMBER__c FROM Account WHERE Name = 'PreExist Act2' LIMIT 1];
        
        Account actWithDuplicateSsn = [SELECT Id, Name, loan__SOCIAL_SECURITY_NUMBER__c FROM Account WHERE Name = 'ActWithDuplicate Ssn' LIMIT 1];
        
        appForDuplicateAct2.BoxFolderID__c = null;
        appForDuplicateAct2.genesis__Status__c = 'NEW - ENTERED';
        appForDuplicateAct2.genesis__CL_Product__c = null;
        appList.add(appForDuplicateAct2);
        
        MW_ApplicationService.updateBoxFolder(appList);
        MW_ApplicationService.PostAccounts(preExistAct,actWithDuplicateSsn);
        
        
        Test.stopTest();
        
        Account actwithDuplicate = [SELECT Id, Name, loan__SOCIAL_SECURITY_NUMBER__c FROM Account WHERE Name = 'ActWithDuplicate Ssn2' LIMIT 1];
        
        
        system.assertEquals(appForDuplicateAct2.genesis__Status__c,'Default Documents');
        system.assertEquals(appForDuplicateAct2.BoxFolderID__c,null);
        system.assertEquals(appForDuplicateAct2.Required_Docs_Count__c,0);
        
    }
    @isTest static void testExistingDupeAccts(){
        
        
        test.startTest();
        genesis__Applications__c appForDuplicateAct2 = [SELECT Id, Name, Bureau_SSN__c, genesis__Status__c, genesis__Account__c FROM genesis__Applications__c WHERE genesis__Account__r.Name = 'ActWithDuplicate Ssn2' LIMIT 1];
        appForDuplicateAct2.Bureau_SSN__c = '123987123';
        appForDuplicateAct2.genesis__Status__c = 'kba_fail';
        
        
        Account preExistAct = [SELECT Id, Name, loan__SOCIAL_SECURITY_NUMBER__c FROM Account WHERE Name = 'PreExist Act2' LIMIT 1];
        appForDuplicateAct2.genesis__Account__c = preExistAct.id;
        Update appForDuplicateAct2;
        
        Account actWithDuplicateSsn = [SELECT Id, Name, loan__SOCIAL_SECURITY_NUMBER__c FROM Account WHERE Name = 'ActWithDuplicate Ssn' LIMIT 1];
        
        
        Test.stopTest();
        
        
        Account actwithDuplicate = [SELECT Id, Name, loan__SOCIAL_SECURITY_NUMBER__c FROM Account WHERE Name = 'ActWithDuplicate Ssn2' LIMIT 1];
        
        system.assertEquals(appForDuplicateAct2.Bureau_SSN__c,'123987123');
        system.assertEquals(appForDuplicateAct2.genesis__Status__c,'kba_fail');
        
    }
}