unpackaged/main/default/objects/Account/fields/ints__Yodlee_Password__c.field-meta.xml
<CustomField>
    <fullName>ints__Yodlee_Password__c</fullName>
    <description>Password for Yodlee Username.</description>
    <label>Yodlee_Password</label>
    <length>100</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/ints__Yodlee_Username__c.field-meta.xml
<CustomField>
    <fullName>ints__Yodlee_Username__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Username registered with Yodlee. This Username can have multiple bank accounts linked with Yodlee.</description>
    <label>Yodlee Username</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Investor.recordType-meta.xml
<RecordType>
    <fullName>Investor</fullName>
    <active>true</active>
    <label>Investor</label>
</RecordType>

unpackaged/main/default/objects/Account/recordTypes/Member.recordType-meta.xml
<RecordType>
    <fullName>Member</fullName>
    <active>true</active>
    <label>Member</label>
</RecordType>

unpackaged/main/default/objects/genesis__Applications__c/genesis__Applications__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{0000000000}</displayFormat>
        <label>Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/genesis__Applications__c/fields/Bank_Account__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bank Account</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Value does not exist or does not match filter criteria. Must choose bank account associated with account.</errorMessage>
        <filterItems>
            <field>loan__Bank_Account__c.loan__Account__c</field>
            <operation>equals</operation>
            <valueField>$Source.genesis__Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>loan__Bank_Account__c</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/genesis__Applications__c/fields/genesis__Due_Day__c.field-meta.xml
<CustomField>
    <fullName>genesis__Due_Day__c</fullName>
    <description>dueDay field.</description>
    <inlineHelpText>If Due Day field is null, then by default it will have Expected First Payment Date day value</inlineHelpText>
    <label>Due_Day</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/genesis__Applications__c/fields/genesis__Expected_First_Payment_Date__c.field-meta.xml
<CustomField>
    <fullName>genesis__Expected_First_Payment_Date__c</fullName>
    <label>Expected First Payment Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/genesis__Org_Parameters__c/fields/genesis__Disable_Triggers__c.field-meta.xml
<CustomField>
    <fullName>genesis__Disable_Triggers__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>This option disables all triggers. It is only to be used while migrating data into the system. At all other times, it must be disabled.</inlineHelpText>
    <label>Disable Triggers</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/ints__Yodlee_Cobrand_Credentials__c/ints__Yodlee_Cobrand_Credentials__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Yodlee Cobrand Credentials</label>
</CustomObject>

unpackaged/main/default/objects/ints__Yodlee_Cobrand_Credentials__c/fields/FromDate_Attribute_value__c.field-meta.xml
<CustomField>
    <fullName>FromDate_Attribute_value__c</fullName>
    <inlineHelpText>Specify the number of days from when you want to get the Transactions.</inlineHelpText>
    <label>FromDate Attribute value</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/ints__Yodlee_Cobrand_Credentials__c/fields/ints__APP_ID__c.field-meta.xml
<CustomField>
    <fullName>ints__APP_ID__c</fullName>
    <label>APP ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ints__Yodlee_Cobrand_Credentials__c/fields/ints__APP_Secret__c.field-meta.xml
<CustomField>
    <fullName>ints__APP_Secret__c</fullName>
    <label>APP Secret</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ints__Yodlee_Cobrand_Credentials__c/fields/ints__Application_Key__c.field-meta.xml
<CustomField>
    <fullName>ints__Application_Key__c</fullName>
    <label>Application Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ints__Yodlee_Cobrand_Credentials__c/fields/ints__Auto_Register_User__c.field-meta.xml
<CustomField>
    <fullName>ints__Auto_Register_User__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Auto Register User</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/ints__Yodlee_Cobrand_Credentials__c/fields/ints__Callback_URL__c.field-meta.xml
<CustomField>
    <fullName>ints__Callback_URL__c</fullName>
    <label>Callback URL</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ints__Yodlee_Cobrand_Credentials__c/fields/ints__Cobrand_id__c.field-meta.xml
<CustomField>
    <fullName>ints__Cobrand_id__c</fullName>
    <label>Cobrand Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ints__Yodlee_Cobrand_Credentials__c/fields/ints__Cobrand_Password__c.field-meta.xml
<CustomField>
    <fullName>ints__Cobrand_Password__c</fullName>
    <label>Cobrand Password</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ints__Yodlee_Cobrand_Credentials__c/fields/ints__Cobrand_Username__c.field-meta.xml
<CustomField>
    <fullName>ints__Cobrand_Username__c</fullName>
    <label>Cobrand Username</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ints__Yodlee_Cobrand_Credentials__c/fields/ints__Node_URL__c.field-meta.xml
<CustomField>
    <fullName>ints__Node_URL__c</fullName>
    <label>Node URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ints__Yodlee_Cobrand_Credentials__c/fields/ints__Rest_URL__c.field-meta.xml
<CustomField>
    <fullName>ints__Rest_URL__c</fullName>
    <label>Rest URL</label>
    <type>Url</type>
</CustomField>

unpackaged/main/default/objects/ints__Yodlee_Cobrand_Credentials__c/fields/ints__Soap_URL__c.field-meta.xml
<CustomField>
    <fullName>ints__Soap_URL__c</fullName>
    <label>Soap URL</label>
    <type>Url</type>
</CustomField>

unpackaged/main/default/objects/ints__Yodlee_User_Credentials__c/ints__Yodlee_User_Credentials__c.object-meta.xml
<CustomObject>
    <label>Yodlee User Credentials</label>
    <nameField>
        <displayFormat>YUC-{00000000}</displayFormat>
        <label>Yodlee User Credentials Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Yodlee User Credentials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ints__Yodlee_User_Credentials__c/fields/ints__Account__c.field-meta.xml
<CustomField>
    <fullName>ints__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Yodlee User Credentials</relationshipLabel>
    <relationshipName>Yodlee_User_Credentials</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ints__Yodlee_User_Credentials__c/fields/ints__Yodlee_Password__c.field-meta.xml
<CustomField>
    <fullName>ints__Yodlee_Password__c</fullName>
    <label>Yodlee Password</label>
    <length>100</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <required>true</required>
    <type>EncryptedText</type>
</CustomField>

unpackaged/main/default/objects/ints__Yodlee_User_Credentials__c/fields/ints__Yodlee_Username__c.field-meta.xml
<CustomField>
    <fullName>ints__Yodlee_Username__c</fullName>
    <label>Yodlee Username</label>
    <length>100</length>
    <maskChar>asterisk</maskChar>
    <maskType>lastFour</maskType>
    <required>true</required>
    <type>EncryptedText</type>
</CustomField>

unpackaged/main/default/objects/ints__Yodlee_User_Credentials__c/fields/yodlee_Account_count__c.field-meta.xml
<CustomField>
    <fullName>yodlee_Account_count__c</fullName>
    <label>yodlee_Account_count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/loan__Bank_Account__c/loan__Bank_Account__c.object-meta.xml
<CustomObject>
    <label>Bank Account</label>
    <nameField>
        <displayFormat>BA-{00000}</displayFormat>
        <label>Bank Account Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bank Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/loan__Bank_Account__c/fields/Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Account_Number__c</fullName>
    <label>Account Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/loan__Bank_Account__c/fields/loan__Account__c.field-meta.xml
<CustomField>
    <fullName>loan__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bank Accounts</relationshipLabel>
    <relationshipName>Bank_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/loan__Bank_Account__c/fields/loan__Account_Type__c.field-meta.xml
<CustomField>
    <fullName>loan__Account_Type__c</fullName>
    <label>Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Savings</fullName>
            </value>
            <value>
                <fullName>Checking</fullName>
                <default>true</default>
                <label>Checking</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/loan__Bank_Account__c/fields/loan__Account_Usage__c.field-meta.xml
<CustomField>
    <fullName>loan__Account_Usage__c</fullName>
    <label>Account Usage</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Investor Trust Account</fullName>
            </value>
            <value>
                <fullName>Collections Trust Account</fullName>
            </value>
            <value>
                <fullName>Advance Trust Account</fullName>
            </value>
            <value>
                <fullName>Business Account</fullName>
            </value>
            <value>
                <fullName>Tax Withholding Account</fullName>
            </value>
            <value>
                <fullName>Borrower/Investor Account</fullName>
            </value>
            <value>
                <fullName>Broker Account</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/loan__Bank_Account__c/fields/loan__Bank_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>loan__Bank_Account_Number__c</fullName>
    <label>Bank Account Number</label>
    <length>50</length>
    <maskChar>X</maskChar>
    <maskType>lastFour</maskType>
    <required>true</required>
    <type>EncryptedText</type>
</CustomField>

unpackaged/main/default/objects/loan__Bank_Account__c/fields/loan__Bank_Name__c.field-meta.xml
<CustomField>
    <fullName>loan__Bank_Name__c</fullName>
    <label>Bank Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/loan__Bank_Account__c/fields/loan__Routing_Number__c.field-meta.xml
<CustomField>
    <fullName>loan__Routing_Number__c</fullName>
    <inlineHelpText>This is a nine digit number used to identify the financial institution in a transaction.</inlineHelpText>
    <label>Routing Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/loan__Bank_Account__c/fields/Unmasked_Bank_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Unmasked_Bank_Account_Number__c</fullName>
    <label>Unmasked Bank Account Number</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Yodlee_User_Account__c/Yodlee_User_Account__c.object-meta.xml
<CustomObject>
    <label>Yodlee User Account</label>
    <nameField>
        <label>Yodlee User Accounts Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Yodlee User Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Yodlee_User_Account__c/fields/Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Account_Number__c</fullName>
    <label>Account Number</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Yodlee_User_Account__c/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <label>Account Type</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/TestDeactivateYodleeAccounts.cls
/* ****************Modification History******************
 * Created By        Date          JIRA number
 *      
 *      1. Neha          2021/01/10        LOP-4
 * Modified By        Date          JIRA number
 *      1. Pallavi       2021/01/25        LOP-4
 *      
 ******************Modification History******************/
@isTest
public class TestDeactivateYodleeAccounts {
    
    @isTest static Void deactivateBankAccount(){
        loan.TestHelper.createSeedDataForTesting();
        loan__Office_Name__c dummyOffice = loan.TestHelper.createOffice();
        
        genesis__Org_Parameters__c cso = new genesis__Org_Parameters__c(genesis__Disable_Triggers__c = true);
        insert cso;
        
        ints__Yodlee_Cobrand_Credentials__c ycc = new ints__Yodlee_Cobrand_Credentials__c();
        ycc.ints__APP_ID__c = '10003600';
        //ycc.ints__Application_Key__c = 
        //ycc.ints__APP_Secret__c =
        //ycc.ints__Auto_Register_User__c = 
        //ycc.ints__Callback_URL__c =
        ycc.ints__Cobrand_id__c = '4410018556';
        ycc.ints__Cobrand_Password__c = 'fpoie176bPIOY!T';
        ycc.ints__Cobrand_Username__c = 'payoff';
        ycc.FromDate_Attribute_value__c = 1100;
        ycc.ints__Node_URL__c = 'https://yieapnodestage.yodlee.com/authenticate/payoff/?channelAppName=yisandbox';
        ycc.ints__Rest_URL__c = 'https://stage.api.yodlee.com/ysl/payoff/v1/';
        ycc.ints__Soap_URL__c = 'https://stage.api.yodlee.com/ysl/payoff/v1/';
        
        insert  ycc;
        
        
        Account acc = MW_GlobalTestUtility.GetAccount('Member');
        Insert acc;
        
        ints__Yodlee_User_Credentials__c userCred = new ints__Yodlee_User_Credentials__c();
        userCred.ints__Account__c = acc.Id;
        userCred.ints__Yodlee_Username__c = 'testuserName';
        userCred.ints__Yodlee_Password__c = 'testpassword';
        userCred.yodlee_Account_count__c  =1;
        insert userCred;
        
        loan__bank_account__c bank = new loan__bank_account__c();
        bank.Account_Number__c = '123456800';
        bank.loan__Routing_Number__c = '999999999';
        bank.loan__Account__c = acc.id;
        bank.loan__Account_Type__c = 'Saving';
        bank.loan__Bank_Name__c='ABc';
        bank.Unmasked_Bank_Account_Number__c='123456800';
        bank.loan__Account_Usage__c = 'Borrower/Investor Account';  //LOS-156
        bank.loan__Bank_Account_Number__c = acc.Id;
        insert bank;
        
         genesis__Applications__c app = new genesis__Applications__c(
         genesis__Due_Day__c = 20,
         genesis__Expected_First_Payment_Date__c = system.Today(),
         genesis__Expected_Start_Date__c = system.Today(),
         genesis__Funding_in_Tranches__c = true,
         genesis__Account__c = acc.Id,        
         Application_Start_DateV2__c = system.Today(),
         genesis__Status__c = 'Decline_Manual_Review',
         genesis__Draw_Period_End_Date__c = system.Today(),
         Employment_Status__c = 'Full Time',
         genesis__Loan_Amount__c=1000,
         Bank_Account__c = bank.id 
        );      
        Insert app;
        
        Yodlee_User_Account__c Yodleeacc = new Yodlee_User_Account__c();
        Yodleeacc.Account_Number__c = 'xxxx3xxx'; 
        Yodleeacc.Account_Type__c = 'SAVINGS';
        Yodleeacc.Available_Balance__c = 65454.78;
        Yodleeacc.Current_Balance__c = 904478;
        Yodleeacc.Status__c = 'ACTIVE';
        Yodleeacc.verified__c = false;
        Yodleeacc.Yodlee_Account__c = acc.Id;
        Yodleeacc.Yodlee_Application__c = app.Id;
        Yodleeacc.YodleeBankAccountId__c = '44473248';
        Yodleeacc.Name = 'DagBank';
        insert Yodleeacc;
        
        List<Yodlee_User_Transaction__c> yodleeTxn = new List<Yodlee_User_Transaction__c>();
        
        Yodlee_User_Transaction__c yodlee = new Yodlee_User_Transaction__c();
        yodlee.Balance__c = 100;
        yodlee.Category__c = 'Test';
        yodlee.Yodlee_Account__c = acc.Id;
        yodlee.YodleeBankAccountId__c = '10563602';
        yodlee.Yodlee_Application__c = app.id;
        
        Yodlee_User_Transaction__c yodlee1 = new Yodlee_User_Transaction__c();
        yodlee1.Balance__c = 100;
        yodlee1.Category__c = 'Test';
        yodlee1.Yodlee_Account__c = acc.Id;
        yodlee1.YodleeBankAccountId__c = '10563603';
        yodlee1.Yodlee_Application__c = app.id;
        
        Yodlee_User_Transaction__c yodlee2 = new Yodlee_User_Transaction__c();
        yodlee2.Balance__c = 1000;
        yodlee2.Category__c = 'Test';
        yodlee2.Yodlee_Account__c = acc.Id;
        yodlee2.YodleeBankAccountId__c = '10563602';
        yodlee2.Yodlee_Application__c = app.id;
        
        Yodlee_User_Transaction__c yodlee3 = new Yodlee_User_Transaction__c();
        yodlee3.Balance__c = 1000;
        yodlee3.Category__c = 'Test';
        yodlee3.Yodlee_Account__c = acc.Id;
        yodlee3.YodleeBankAccountId__c = '10563603';
        yodlee3.Yodlee_Application__c = app.id;
        
        yodleeTxn.add(yodlee);
        yodleeTxn.add(yodlee1);
        yodleeTxn.add(yodlee2);
        yodleeTxn.add(yodlee3);
        
        insert yodleeTxn;
        /*LOP-4 update*/
        Expiry_Date__c expiryDate = new Expiry_Date__c();
        expiryDate.Application_Status_to_deactivate_Yodlee__c = 'Decline_Manual_Review,';
        expiryDate.Loan_Status_to_deactivate_Yodlee__c = 'Closed - Obligations met,';
        expiryDate.Yodlee_Acc_expiration_after__c = -1;
        insert expiryDate;
        /*LOP-4 update*/
        
        Test.setMock(HttpCalloutMock.class, new MockYodleeTransactionAPICallOut1());
               
        Test.startTest(); 
        YodleeDeactivateAccountsBatch b = new YodleeDeactivateAccountsBatch();
        
        String batchId = Database.executebatch(b,1);     
        
        /*LOP-4 update*/
        Set<String> YodleeAccId = new Set<String>();
        Set<Id> accountId = new Set<Id>();
        YodleeAccId.add(Yodleeacc.YodleeBankAccountId__c);
        accountId.add(Yodleeacc.Yodlee_Account__c);        
            
        YodleeDeactivateAccountsBatch b1 = new YodleeDeactivateAccountsBatch(YodleeAccId,accountId);
        /*LOP-4 update*/
        
        Test.stopTest();
        
        cso.genesis__Disable_Triggers__c = false;
        //update cso;

    }

}