unpackaged/main/default/objects/Account/fields/loan__Active__c.field-meta.xml
<CustomField>
    <fullName>loan__Active__c</fullName>
    <label>Active</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/loan__Bank_Account__c/loan__Bank_Account__c.object-meta.xml
<CustomObject>
    <label>Bank Account</label>
    <nameField>
        <displayFormat>BA-{00000}</displayFormat>
        <label>Bank Account Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bank Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/loan__Bank_Account__c/fields/Account_Holder__c.field-meta.xml
<CustomField>
    <fullName>Account_Holder__c</fullName>
    <label>Account Holder</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/loan__Bank_Account__c/fields/Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Account_Number__c</fullName>
    <label>Account Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/loan__Bank_Account__c/fields/Account_Number_Con_Info__c.field-meta.xml
<CustomField>
    <fullName>Account_Number_Con_Info__c</fullName>
    <label>Account Number Con Info</label>
    <length>50</length>
    <maskChar>X</maskChar>
    <maskType>lastFour</maskType>
    <type>EncryptedText</type>
</CustomField>

unpackaged/main/default/objects/loan__Bank_Account__c/fields/Bank_Account_External_Id__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account_External_Id__c</fullName>
    <description>Bank Account LAPro Id. Using for Data migration</description>
    <externalId>true</externalId>
    <label>Bank Account External Id</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/loan__Bank_Account__c/fields/Bank_Name_Derived__c.field-meta.xml
<CustomField>
    <fullName>Bank_Name_Derived__c</fullName>
    <label>Bank Name (Derived)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/loan__Bank_Account__c/fields/BankACctMatch__c.field-meta.xml
<CustomField>
    <fullName>BankACctMatch__c</fullName>
    <formula>if(Account_Number__c = Unmasked_Bank_Account_Number__c,true,false)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>BankAcctMatch</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/loan__Bank_Account__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <inlineHelpText>Bank Account Holder First Name</inlineHelpText>
    <label>First Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/loan__Bank_Account__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <inlineHelpText>Bank Account Holder Last Name</inlineHelpText>
    <label>Last Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/loan__Bank_Account__c/fields/loan__Account__c.field-meta.xml
<CustomField>
    <fullName>loan__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bank Accounts</relationshipLabel>
    <relationshipName>Bank_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/loan__Bank_Account__c/fields/loan__Account_Type__c.field-meta.xml
<CustomField>
    <fullName>loan__Account_Type__c</fullName>
    <label>Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Savings</fullName>
            </value>
            <value>
                <fullName>Checking</fullName>
                <default>true</default>
                <label>Checking</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/loan__Bank_Account__c/fields/loan__Account_Usage__c.field-meta.xml
<CustomField>
    <fullName>loan__Account_Usage__c</fullName>
    <label>Account Usage</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Investor Trust Account</fullName>
            </value>
            <value>
                <fullName>Collections Trust Account</fullName>
            </value>
            <value>
                <fullName>Advance Trust Account</fullName>
            </value>
            <value>
                <fullName>Business Account</fullName>
            </value>
            <value>
                <fullName>Tax Withholding Account</fullName>
            </value>
            <value>
                <fullName>Borrower/Investor Account</fullName>
            </value>
            <value>
                <fullName>Broker Account</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/loan__Bank_Account__c/fields/loan__ACH_Code__c.field-meta.xml
<CustomField>
    <fullName>loan__ACH_Code__c</fullName>
    <label>ACH Code</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/loan__Bank_Account__c/fields/loan__Bank_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>loan__Bank_Account_Number__c</fullName>
    <label>Bank Account Number</label>
    <length>50</length>
    <maskChar>X</maskChar>
    <maskType>lastFour</maskType>
    <required>true</required>
    <type>EncryptedText</type>
</CustomField>

unpackaged/main/default/objects/loan__Bank_Account__c/fields/loan__Bank_Name__c.field-meta.xml
<CustomField>
    <fullName>loan__Bank_Name__c</fullName>
    <label>Bank Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/loan__Bank_Account__c/fields/loan__Contact__c.field-meta.xml
<CustomField>
    <fullName>loan__Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Bank Accounts</relationshipLabel>
    <relationshipName>Bank_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/loan__Bank_Account__c/fields/loan__Routing_Number__c.field-meta.xml
<CustomField>
    <fullName>loan__Routing_Number__c</fullName>
    <inlineHelpText>This is a nine digit number used to identify the financial institution in a transaction.</inlineHelpText>
    <label>Routing Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/loan__Bank_Account__c/fields/loan__Signature_Line__c.field-meta.xml
<CustomField>
    <fullName>loan__Signature_Line__c</fullName>
    <label>Signature Line</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/loan__Bank_Account__c/fields/Name_Matches__c.field-meta.xml
<CustomField>
    <fullName>Name_Matches__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Name Matches</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/loan__Bank_Account__c/fields/Name_on_Account__c.field-meta.xml
<CustomField>
    <fullName>Name_on_Account__c</fullName>
    <label>Name on Account</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/loan__Bank_Account__c/fields/peer__Account_Age__c.field-meta.xml
<CustomField>
    <fullName>peer__Account_Age__c</fullName>
    <label>Account Age</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/loan__Bank_Account__c/fields/peer__Allow_for_Direct_Credit__c.field-meta.xml
<CustomField>
    <fullName>peer__Allow_for_Direct_Credit__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Allow for Direct Credit</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/loan__Bank_Account__c/fields/peer__Branch_Code__c.field-meta.xml
<CustomField>
    <fullName>peer__Branch_Code__c</fullName>
    <label>Branch Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/loan__Bank_Account__c/fields/peer__Savings_No__c.field-meta.xml
<CustomField>
    <fullName>peer__Savings_No__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Savings_No</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/loan__Bank_Account__c/fields/peer__Savings_Other__c.field-meta.xml
<CustomField>
    <fullName>peer__Savings_Other__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Savings Other</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/loan__Bank_Account__c/fields/peer__Savings_Pensions__c.field-meta.xml
<CustomField>
    <fullName>peer__Savings_Pensions__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Savings Pensions</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/loan__Bank_Account__c/fields/peer__Working_Place_Type__c.field-meta.xml
<CustomField>
    <fullName>peer__Working_Place_Type__c</fullName>
    <label>Working Place Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>State employed</fullName>
            </value>
            <value>
                <fullName>Government company</fullName>
            </value>
            <value>
                <fullName>Big company</fullName>
            </value>
            <value>
                <fullName>Small company</fullName>
            </value>
            <value>
                <fullName>Personal company</fullName>
            </value>
            <value>
                <fullName>Unemployed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/loan__Bank_Account__c/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <label>Source</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Bank Account</fullName>
            </value>
            <value>
                <fullName>Voided Check</fullName>
            </value>
            <value>
                <fullName>Bank Statement</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/loan__Bank_Account__c/fields/Unmask__c.field-meta.xml
<CustomField>
    <fullName>Unmask__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Unmask</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/loan__Bank_Account__c/fields/Unmask_Con_Info__c.field-meta.xml
<CustomField>
    <fullName>Unmask_Con_Info__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Unmask Con Info</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/loan__Bank_Account__c/fields/Unmasked_Bank_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Unmasked_Bank_Account_Number__c</fullName>
    <label>Unmasked Bank Account Number</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/loan__Bank_Account__c/fields/Verified_by_linked_bank_account__c.field-meta.xml
<CustomField>
    <fullName>Verified_by_linked_bank_account__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Verified by linked bank account instead of bank statement</description>
    <inlineHelpText>Verified by linked bank account instead of bank statement</inlineHelpText>
    <label>Verified by linked bank account</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/loan__Bank_Account__c/fields/YodleeBank_Accounts__c.field-meta.xml
<CustomField>
    <fullName>YodleeBank_Accounts__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checked - if there are accounts in Yodlee</description>
    <label>YodleeBank Accounts</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/classes/MW_RetrieveBankAcctbyAccountId.cls
@RestResource(urlMapping='/bank-account/contract-id/*')
global with sharing class MW_RetrieveBankAcctbyAccountId {
    @HttpGet
    global static void MW_RetrieveBankAcctbyAccountId() {
        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;
        try {
            String contractId = req.params.get('contract-id');
            if (String.isBlank(contractId)) {
                res.statusCode = 400;
                res.responseBody = Blob.valueOf('contract id is required');
                return;
            }
            List<loan__Bank_Account__c> bankAccounts = [
                SELECT
                Id,
                OwnerId,
                IsDeleted,
                Name,
                CreatedDate,
                CreatedById,
                LastModifiedDate,
                LastModifiedById,
                loan__ACH_Code__c,
                loan__Account_Type__c,
                loan__Account_Usage__c,
                loan__Account__c,
                loan__Active__c,
                loan__Bank_Account_Number__c,
                loan__Bank_Name__c,
                loan__Contact__c,
                loan__Routing_Number__c,
                loan__Archived__c,
                loan__Master_Archive_Object__c,
                loan__Signature_Line__c,
                loan__Summary_Record_Id__c,
                loan__Summary__c,
                peer__Account_Age__c,
                peer__Allow_for_Direct_Credit__c,
                peer__Branch_Code__c,
                peer__Savings_No__c,
                peer__Savings_Other__c,
                peer__Savings_Pensions__c,
                peer__Working_Place_Type__c,
                Account_Holder__c,
                Account_Number_Con_Info__c,
                Account_Number__c,
                Bank_Account_External_Id__c,
                Bank_Name_Derived__c,
                First_Name__c,
                Last_Name__c,
                Name_Matches__c,
                Name_on_Account__c,
                Source__c,
                Unmask_Con_Info__c,
                Unmask__c,
                Unmasked_Bank_Account_Number__c,
                Verified_by_linked_bank_account__c,
                YodleeBank_Accounts__c,
                BankACctMatch__c
                FROM loan__Bank_Account__c
                WHERE loan__Account__c = :contractId 
            ];
            res.statusCode = 200;
            res.responseBody = Blob.valueOf(JSON.serialize(bankAccounts));
        }
        catch (Exception e) {
            res.statusCode = 500;
            res.responseBody = Blob.valueOf(e.getMessage());
        }
    }
}