unpackaged/main/default/objects/Account/fields/loan__Active__c.field-meta.xml
<CustomField>
    <fullName>loan__Active__c</fullName>
    <label>Active</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/loan__SOCIAL_SECURITY_NUMBER__c.field-meta.xml
<CustomField>
    <fullName>loan__SOCIAL_SECURITY_NUMBER__c</fullName>
    <label>SOCIAL_SECURITY_NUMBER</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/peer__First_Name__c.field-meta.xml
<CustomField>
    <fullName>peer__First_Name__c</fullName>
    <label>First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/peer__Last_Name__c.field-meta.xml
<CustomField>
    <fullName>peer__Last_Name__c</fullName>
    <label>Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Investor.recordType-meta.xml
<RecordType>
    <fullName>Investor</fullName>
    <active>true</active>
    <label>Investor</label>
</RecordType>

unpackaged/main/default/objects/clcommon__DAG_Logging__c/clcommon__DAG_Logging__c.object-meta.xml
<CustomObject>
    <label>DAG Logging</label>
    <nameField>
        <displayFormat>DL-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DAG Logging</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/clcommon__DAG_Logging__c/fields/clcommon__DAG__c.field-meta.xml
<CustomField>
    <fullName>clcommon__DAG__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>DAG</label>
    <referenceTo>clcommon__DAG_Schedule__c</referenceTo>
    <relationshipLabel>DAG Loggings</relationshipLabel>
    <relationshipName>DAG_Loggings</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/clcommon__DAG_Logging__c/fields/clcommon__Status__c.field-meta.xml
<CustomField>
    <fullName>clcommon__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failure</fullName>
            </value>
            <value>
                <fullName>Initializing</fullName>
            </value>
            <value>
                <fullName>Aborted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/clcommon__DAG_Schedule__c/clcommon__DAG_Schedule__c.object-meta.xml
<CustomObject>
    <label>DAG Schedule</label>
    <nameField>
        <displayFormat>DAG-{00000}</displayFormat>
        <label>Autofield</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DAG Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/clcommon__DAG_Schedule__c/fields/clcommon__DAG_Name__c.field-meta.xml
<CustomField>
    <fullName>clcommon__DAG_Name__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>DAG Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/loan__Automated_Payment_Configuration__c/loan__Automated_Payment_Configuration__c.object-meta.xml
<CustomObject>
    <customHelpPage>loan__AutomatedPaymentConfigurationHelp</customHelpPage>
    <label>Automated Payment Configuration</label>
    <nameField>
        <displayFormat>APC-{0000000000}</displayFormat>
        <label>Automated Payment Configuration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Automated Payment Configuration</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/loan__Automated_Payment_Configuration__c/fields/Box_Folder_ID__c.field-meta.xml
<CustomField>
    <fullName>Box_Folder_ID__c</fullName>
    <label>Box Folder ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/loan__Automated_Payment_Configuration__c/fields/loan__Active__c.field-meta.xml
<CustomField>
    <fullName>loan__Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/loan__Automated_Payment_Configuration__c/fields/loan__Bank_Account__c.field-meta.xml
<CustomField>
    <fullName>loan__Bank_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bank Account</label>
    <referenceTo>loan__Bank_Account__c</referenceTo>
    <relationshipLabel>Automated Payment Configuration</relationshipLabel>
    <relationshipName>Automated_Payment_Configuration</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/loan__Automated_Payment_Configuration__c/fields/loan__Event__c.field-meta.xml
<CustomField>
    <fullName>loan__Event__c</fullName>
    <label>Event</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>LOAN PAYMENT</fullName>
            </value>
            <value>
                <fullName>LOAN REPAYMENT REFUND</fullName>
            </value>
            <value>
                <fullName>LOAN DISBURSAL</fullName>
            </value>
            <value>
                <fullName>INVESTOR WITHDRAWAL</fullName>
            </value>
            <value>
                <fullName>INVESTOR DEPOSIT</fullName>
            </value>
            <value>
                <fullName>INVESTOR PAYMENT</fullName>
            </value>
            <value>
                <fullName>FEE PAYMENT</fullName>
            </value>
            <value>
                <fullName>BROKER TRANSACTION</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/loan__Automated_Payment_Configuration__c/fields/loan__File_Type__c.field-meta.xml
<CustomField>
    <fullName>loan__File_Type__c</fullName>
    <label>File Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>TEXT</fullName>
            </value>
            <value>
                <fullName>CSV</fullName>
            </value>
            <value>
                <fullName>JSON</fullName>
            </value>
            <value>
                <fullName>XML</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/loan__Automated_Payment_Configuration__c/fields/loan__Filegen_Class__c.field-meta.xml
<CustomField>
    <fullName>loan__Filegen_Class__c</fullName>
    <label>Filegen Class</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/loan__Automated_Payment_Configuration__c/fields/loan__Folder_Name__c.field-meta.xml
<CustomField>
    <fullName>loan__Folder_Name__c</fullName>
    <inlineHelpText>Please create a folder with a name under the Documents tab. Then put the folder name here.</inlineHelpText>
    <label>Folder Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/loan__Automated_Payment_Configuration__c/fields/loan__Payment_Mode__c.field-meta.xml
<CustomField>
    <fullName>loan__Payment_Mode__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Mode</label>
    <referenceTo>loan__Payment_Mode__c</referenceTo>
    <relationshipLabel>Automated Payment Configuration</relationshipLabel>
    <relationshipName>Automated_Payment_Configuration</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/loan__Bank_Account__c/loan__Bank_Account__c.object-meta.xml
<CustomObject>
    <label>Bank Account</label>
    <nameField>
        <displayFormat>BA-{00000}</displayFormat>
        <label>Bank Account Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bank Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/loan__Bank_Account__c/fields/loan__Account__c.field-meta.xml
<CustomField>
    <fullName>loan__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bank Accounts</relationshipLabel>
    <relationshipName>Bank_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/loan__Bank_Account__c/fields/loan__Account_Type__c.field-meta.xml
<CustomField>
    <fullName>loan__Account_Type__c</fullName>
    <label>Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Savings</fullName>
            </value>
            <value>
                <fullName>Checking</fullName>
                <default>true</default>
                <label>Checking</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/loan__Bank_Account__c/fields/loan__Bank_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>loan__Bank_Account_Number__c</fullName>
    <label>Bank Account Number</label>
    <length>50</length>
    <maskChar>X</maskChar>
    <maskType>lastFour</maskType>
    <required>true</required>
    <type>EncryptedText</type>
</CustomField>

unpackaged/main/default/objects/loan__Bank_Account__c/fields/loan__Bank_Name__c.field-meta.xml
<CustomField>
    <fullName>loan__Bank_Name__c</fullName>
    <label>Bank Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/loan__Bank_Account__c/fields/loan__Routing_Number__c.field-meta.xml
<CustomField>
    <fullName>loan__Routing_Number__c</fullName>
    <inlineHelpText>This is a nine digit number used to identify the financial institution in a transaction.</inlineHelpText>
    <label>Routing Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/loan__Bank_Account__c/fields/Unmasked_Bank_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Unmasked_Bank_Account_Number__c</fullName>
    <label>Unmasked Bank Account Number</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/loan__Org_Parameters__c/loan__Org_Parameters__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Org Parameters</label>
</CustomObject>

unpackaged/main/default/objects/loan__Org_Parameters__c/fields/Auto_Payer_Lending_Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Auto_Payer_Lending_Product_Name__c</fullName>
    <label>Auto Payer Lending Product Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/loan__Org_Parameters__c/fields/Manual_Payer_Lending_product_name__c.field-meta.xml
<CustomField>
    <fullName>Manual_Payer_Lending_product_name__c</fullName>
    <label>Manual Payer Lending product name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/loan__Payment_Mode__c/loan__Payment_Mode__c.object-meta.xml
<CustomObject>
    <label>Payment Mode</label>
    <nameField>
        <label>Payment Mode Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Mode</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/MW_Settings__c/MW_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>MW_Settings</label>
</CustomObject>

force-app/main/default/objects/MW_Settings__c/fields/Slack_mentions_for_Nacha_alert__c.field-meta.xml
<CustomField>
    <fullName>Slack_mentions_for_Nacha_alert__c</fullName>
    <label>Slack mentions for Nacha alert</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/NachaAlertDynamicJobTest.cls
@isTest
public with sharing class NachaAlertDynamicJobTest {
    @TestSetup
    public static void testSetup(){
        MW_Settings__c setting = MW_GlobalTestUtility.GetSettings();
        setting.Slack_mentions_for_Nacha_alert__c = 'test@user.com';
        insert setting;
        
        clcommon__DAG_Schedule__c dagFileGen = new clcommon__DAG_Schedule__c();
        dagFileGen.clcommon__DAG_Name__c    = 'Payment - Filegen - Upload to Box';
        insert dagFileGen;
        
        clcommon__DAG_Logging__c dagLogging = new clcommon__DAG_Logging__c(
			clcommon__Status__c = 'Success',
            clcommon__DAG__c = dagFileGen.Id
		);
		insert dagLogging;

        loan__Org_Parameters__c loanorg = loan.CustomSettingsUtil.getOrgParameters();
        loanorg.Manual_Payer_Lending_product_name__c = 'Manual Payer';
        loanorg.Auto_Payer_Lending_Product_Name__c = 'Auto Payer';
        upsert loanorg;
        
        Account invacc = new Account();
        invacc.peer__First_Name__c = 'investor';
        invacc.peer__Last_Name__c = 'testOne';
        invacc.loan__SOCIAL_SECURITY_NUMBER__c = '123456780';
        insert invacc;
        
        loan__Bank_Account__c bainv = new loan__Bank_Account__c(loan__Bank_Account_Number__c = '12',
                                                                loan__Bank_Name__c = 'Some Bank',
                                                                loan__Routing_Number__c = '999999999',
                                                                loan__Account_Type__c = 'Checking',
                                                                loan__Active__c = true,
                                                                Unmasked_Bank_Account_Number__c = '99999999',
                                                                loan__Account__c = invacc.id);
        insert bainv;
        
        loan__Payment_Mode__c pm = new loan__Payment_Mode__c();
        pm.name = 'Wire';
        insert pm;
        
        loan__Automated_Payment_Configuration__c invaps = new loan__Automated_Payment_Configuration__c();
        invaps.loan__Payment_Mode__c = pm.id;
        invaps.loan__Bank_Account__c = bainv.id;
        invaps.loan__Filegen_Class__c = 'CustomLoanPaymentTxnNACHAGen';
        invaps.loan__Folder_Name__c = 'ACU';
        invaps.loan__File_Type__c = 'CSV';
        invaps.loan__Event__c = 'LOAN PAYMENT';
        invaps.loan__Active__c = true;
        invaps.Box_Folder_ID__c = '48673238292';
        insert invaps;
        
        List<Document> docs= new list<Document>();
        for(integer i=0;i<5;i++){
            Document documents = new Document();
            documents.Body = Blob.valueOf('Some Text');
            documents.ContentType = 'application/pdf';
            documents.DeveloperName = 'my_document'+i;
            documents.IsPublic = true;
            documents.Name = 'My Document'+i;
            documents.FolderId = [select id from folder where name = 'ACU'].id;
            docs.add(documents);
        }
        insert docs;
    }

    @isTest
    static void testNachaAlertDynamicJob() {
        Test.startTest();
        NachaAlertDynamicJob job = new NachaAlertDynamicJob();
        String jobID = Database.executeBatch(job,1);
        Test.StopTest();
        
        Assert.isTrue(jobID != null,'job runs 1');
    }

    /*Created By: Ngoc Phan
    Purpose: To test logic for Dynamic query passing query as parameter to the constructor*/
    @isTest
    static void testDynamicQueryOneParam(){
        Test.startTest();
        String  query = 'Select id,name, Box_Folder_ID__c,loan__Folder_Name__c From loan__Automated_Payment_Configuration__c Where loan__Active__c = True limit 1';
        NachaAlertDynamicJob job = new NachaAlertDynamicJob(query);
        String jobID = Database.executeBatch(job);
        Test.StopTest();
        
        Assert.isTrue(jobID != null,'job runs 2');
    }

    @isTest
    static void testLogsCalloutBatch() {
        Test.startTest();

        Test.setMock(HttpCalloutMock.class, new HttpSlackCalloutMock());

        List<loan__Automated_Payment_Configuration__c> apcList = [Select id, loan__Folder_Name__c FROM loan__Automated_Payment_Configuration__c];
        LogsCalloutBatch job = new LogsCalloutBatch(apcList, System.now());
        String jobID = Database.executeBatch(job);
        Test.StopTest();
        
        Assert.isTrue(jobID != null,'job runs 3');
    }

    /**
     * Increase code coverage LogsCalloutBatch Constructor with 4 params
     */
    @isTest
    static void testLogsCalloutBatch2() {
        Test.startTest();

        Test.setMock(HttpCalloutMock.class, new HttpSlackCalloutMock());

        List<loan__Automated_Payment_Configuration__c> apcList = [Select id, loan__Folder_Name__c FROM loan__Automated_Payment_Configuration__c];

        List<String> folderList = new List<String>();

        for(loan__Automated_Payment_Configuration__c aPC : apcList) {
            folderList.add(aPC.loan__Folder_Name__c);
        }

        List<Document> docList = [Select id from Document];

        Set<Id> docIdSet = new Set<Id>();

        Set<Id> failSet = new Set<Id>();

        for(Document doc : docList) {
            docIdSet.add(doc.Id);
        }

        LogsCalloutBatch job = new LogsCalloutBatch(folderList, docIdSet.size(), docIdSet , failSet);
        String jobID = Database.executeBatch(job);
        Test.StopTest();
        
        Assert.isTrue(jobID != null,'job runs 4');
    }
    
    
    @isTest
    static void testNightlyJobFailure() {
        Test.startTest();

        Test.setMock(HttpCalloutMock.class, new HttpSlackCalloutMock());
        
        List<String> apexListDummy = new List<String>();
        apexListDummy.add('StartOfDayDynamicJob');
        
        LogsCalloutBatchHelper.sendFailureNightlyJobAlerts(apexListDummy, System.now());
        
        Test.StopTest();
    }
}