unpackaged/main/default/objects/Account/fields/loan__Active__c.field-meta.xml
<CustomField>
    <fullName>loan__Active__c</fullName>
    <label>Active</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/loan__Automated_Payment_Setup__c/loan__Automated_Payment_Setup__c.object-meta.xml
<CustomObject>
    <label>Automated Payment Setup</label>
    <nameField>
        <displayFormat>APS-{0000000000}</displayFormat>
        <label>Automated Payment Setup Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Automated Payment Setup</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/loan__Automated_Payment_Setup__c/fields/loan__Active__c.field-meta.xml
<CustomField>
    <fullName>loan__Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/loan__Automated_Payment_Setup__c/fields/loan__Bank_Account__c.field-meta.xml
<CustomField>
    <fullName>loan__Bank_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bank Account</label>
    <referenceTo>loan__Bank_Account__c</referenceTo>
    <relationshipName>ACH_Setup</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/loan__Automated_Payment_Setup__c/fields/loan__Transaction_Amount__c.field-meta.xml
<CustomField>
    <fullName>loan__Transaction_Amount__c</fullName>
    <label>Transaction Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/loan__Bank_Account__c/loan__Bank_Account__c.object-meta.xml
<CustomObject>
    <label>Bank Account</label>
    <nameField>
        <displayFormat>BA-{00000}</displayFormat>
        <label>Bank Account Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bank Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/loan__Bank_Account__c/fields/Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Account_Number__c</fullName>
    <label>Account Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/loan__Bank_Account__c/fields/loan__Bank_Name__c.field-meta.xml
<CustomField>
    <fullName>loan__Bank_Name__c</fullName>
    <label>Bank Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/loan__Bank_Account__c/fields/loan__Routing_Number__c.field-meta.xml
<CustomField>
    <fullName>loan__Routing_Number__c</fullName>
    <inlineHelpText>This is a nine digit number used to identify the financial institution in a transaction.</inlineHelpText>
    <label>Routing Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/loan__Bank_Account__c/fields/Unmasked_Bank_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Unmasked_Bank_Account_Number__c</fullName>
    <label>Unmasked Bank Account Number</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/TestCustomBankAccountHandler.cls
/* ****************Modification History******************
*    Created By        	 Date			Version
*1. Bhavya Maliwal        2022/07/07     Initial Version

******************Modification History******************/
@isTest
Private class TestCustomBankAccountHandler {
    /*Created By : Bhavya Maliwal
Method name : inactiveAPS
Purpose : to cover code satisfying if Bank Account gets inactive the corresponding APS gets inactive ; for CustomBankAccountHandler
*/
    @isTest static Void inactiveAPS(){
        loan__Bank_Account__c bankAccount=new loan__Bank_Account__c();
        bankAccount.Account_Number__c='2345678755699';
        bankAccount.Unmasked_Bank_Account_Number__c='30983456787346';
        bankAccount.loan__Active__c=true;
        bankAccount.loan__Routing_Number__c='245765432';
        bankAccount.loan__Bank_Name__c='hdfc';
        insert bankAccount;
        
        loan__Automated_Payment_Setup__c aps=new loan__Automated_Payment_Setup__c();
        aps.loan__Active__c=true;
        aps.loan__Bank_Account__c=bankAccount.id;
        aps.loan__Transaction_Amount__c=1221;
        
        insert aps;
        test.startTest();
        bankAccount.loan__Active__c=false;
        test.stopTest();
        loan__Automated_Payment_Setup__c apscheck=[Select id,loan__Active__c from loan__Automated_Payment_Setup__c
                                                   where loan__Bank_Account__c=:bankAccount.id limit 1];
        system.assert(!apscheck.loan__Active__c);
    }
    
}