unpackaged/main/default/objects/Account/fields/loan__Investor__c.field-meta.xml
<CustomField>
    <fullName>loan__Investor__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Investor</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/loan__SOCIAL_SECURITY_NUMBER__c.field-meta.xml
<CustomField>
    <fullName>loan__SOCIAL_SECURITY_NUMBER__c</fullName>
    <label>SOCIAL_SECURITY_NUMBER</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/genesis__Applications__c/genesis__Applications__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{0000000000}</displayFormat>
        <label>Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/genesis__Applications__c/fields/Neo_Verify__c.field-meta.xml
<CustomField>
    <fullName>Neo_Verify__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Neo Verify</label>
    <referenceTo>Neo_Verify__c</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/MW_Callout__c/MW_Callout__c.object-meta.xml
<CustomObject>
    <label>MW_Callout</label>
    <nameField>
        <label>MW_Callout Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MW_Callout</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/MW_Callout__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>genesis__Applications__c</referenceTo>
    <relationshipLabel>MW_Callout</relationshipLabel>
    <relationshipName>MW_Callout</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/MW_Callout__c/fields/JobID__c.field-meta.xml
<CustomField>
    <fullName>JobID__c</fullName>
    <label>JobID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/MW_Callout__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/MW_Settings__c/MW_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>MW_Settings</label>
</CustomObject>

unpackaged/main/default/objects/MW_Settings__c/fields/Neoverify_APIkey__c.field-meta.xml
<CustomField>
    <fullName>Neoverify_APIkey__c</fullName>
    <description>API key to connect with neoverify</description>
    <label>Neoverify_APIkey</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Neo_Verify__c/Neo_Verify__c.object-meta.xml
<CustomObject>
    <label>Neo Verify</label>
    <nameField>
        <displayFormat>A-{0000000000}</displayFormat>
        <label>Neo Verify Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Neo Verify</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Neo_Verify__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <label>Application</label>
    <referenceTo>genesis__Applications__c</referenceTo>
    <relationshipLabel>Neo Verify</relationshipLabel>
    <relationshipName>Neo_Verify</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Neo_Verify__c/fields/NSF_OD__c.field-meta.xml
<CustomField>
    <fullName>NSF_OD__c</fullName>
    <label>NSF/OD</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Yodlee_User_Account__c/Yodlee_User_Account__c.object-meta.xml
<CustomObject>
    <label>Yodlee User Account</label>
    <nameField>
        <label>Yodlee User Accounts Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Yodlee User Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Yodlee_User_Account__c/fields/Account_Holder_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Holder_Name__c</fullName>
    <label>Account Holder Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Yodlee_User_Account__c/fields/Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Account_Number__c</fullName>
    <label>Account Number</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Yodlee_User_Account__c/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <label>Account Type</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Yodlee_User_Account__c/fields/Available_Balance__c.field-meta.xml
<CustomField>
    <fullName>Available_Balance__c</fullName>
    <label>Available Balance</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Yodlee_User_Account__c/fields/Current_Balance__c.field-meta.xml
<CustomField>
    <fullName>Current_Balance__c</fullName>
    <label>Current Balance</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Yodlee_User_Account__c/fields/Yodlee_Account__c.field-meta.xml
<CustomField>
    <fullName>Yodlee_Account__c</fullName>
    <label>Yodlee Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Yodlee User Accounts</relationshipLabel>
    <relationshipName>Yodlee_User_Accounts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Yodlee_User_Account__c/fields/Yodlee_Application__c.field-meta.xml
<CustomField>
    <fullName>Yodlee_Application__c</fullName>
    <label>Application</label>
    <referenceTo>genesis__Applications__c</referenceTo>
    <relationshipLabel>Yodlee User Accounts</relationshipLabel>
    <relationshipName>Yodlee_User_Accounts</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Yodlee_User_Transaction__c/Yodlee_User_Transaction__c.object-meta.xml
<CustomObject>
    <label>Yodlee User Transaction</label>
    <nameField>
        <displayFormat>YUT-{0000000}</displayFormat>
        <label>Yodlee User Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Yodlee User Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Yodlee_User_Transaction__c/fields/Account_Holder_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Holder_Name__c</fullName>
    <description>Account Holder Name pulled from Yodlee User Account</description>
    <label>Account Holder Name</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Yodlee_User_Transaction__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Yodlee_User_Transaction__c/fields/Debit__c.field-meta.xml
<CustomField>
    <fullName>Debit__c</fullName>
    <label>Debit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Yodlee_User_Transaction__c/fields/isLatest__c.field-meta.xml
<CustomField>
    <fullName>isLatest__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isLatest</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Yodlee_User_Transaction__c/fields/Transaction_Date__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Date__c</fullName>
    <label>Transaction Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Yodlee_User_Transaction__c/fields/Transaction_Type__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Type__c</fullName>
    <label>Transaction Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CREDIT</fullName>
            </value>
            <value>
                <fullName>DEBIT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Yodlee_User_Transaction__c/fields/Yodlee_Account__c.field-meta.xml
<CustomField>
    <fullName>Yodlee_Account__c</fullName>
    <label>Yodlee Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Yodlee User Transactions</relationshipLabel>
    <relationshipName>Yodlee_User_Transactions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Yodlee_User_Transaction__c/fields/Yodlee_Application__c.field-meta.xml
<CustomField>
    <fullName>Yodlee_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>genesis__Applications__c</referenceTo>
    <relationshipLabel>Yodlee User Transactions</relationshipLabel>
    <relationshipName>Yodlee_User_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Yodlee_User_Transaction__c/fields/Yodlee_User_account__c.field-meta.xml
<CustomField>
    <fullName>Yodlee_User_account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>lookup to Yodlee User Account object</description>
    <label>Yodlee User Account</label>
    <referenceTo>Yodlee_User_Account__c</referenceTo>
    <relationshipLabel>Yodlee User Transactions</relationshipLabel>
    <relationshipName>Yodlee_User_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/MW_NeoVerifyIntegrationTest.cls
@isTest
private class MW_NeoVerifyIntegrationTest {

    @testSetup static void setup() {
        list<account> accList                  = MW_DataFactoryTest.createAccounts(1);
        accList[0].loan__SOCIAL_SECURITY_NUMBER__c = '6831540283';
        accList[0].loan__Investor__c=true;
        insert accList;
        list<genesis__Applications__c> appList = MW_DataFactoryTest.createApplication(1, accList[0].Id);
        insert appList;
        MW_Settings__c mwSetting = new MW_Settings__c();
        mwSetting.Neoverify_APIkey__c = 'testapikey';
        insert mwSetting;
 

        Yodlee_User_Transaction__c sobj = new Yodlee_User_Transaction__c(
            Transaction_Date__c = system.Today(),
            Balance__c = 10.00,                                                                          // Balance
            Description__c = 'Debit transction for Goal',                                               // Description
            Category__c = 'Other Expenses',                                                             // Category
            Yodlee_Account__c = accList[0].id,                                                      // Yodlee Account
            Transaction_Type__c = 'DEBIT',                                                              // Transaction Type
            Debit__c = 8000.00,                                                                         // Debit
            isLatest__c = true,                                                                         // isLatest
            Yodlee_Application__c=appList[0].Id
            );
        insert sobj;

        Yodlee_User_Transaction__c sobj1 = new Yodlee_User_Transaction__c(
            Transaction_Date__c = system.Today(),
            Balance__c = 10.00,                                                                          // Balance
            Description__c = 'Debit transction for Goal',                                               // Description
            Category__c = 'Other Expenses',                                                             // Category
            Yodlee_Account__c = accList[0].id,                                                      // Yodlee Account
            Transaction_Type__c = 'DEBIT',                                                              // Transaction Type
            Debit__c = 8000.00,                                                                         // Debit
            isLatest__c = true,                                                                         // isLatest
            Yodlee_Application__c=appList[0].Id
            );
        insert sobj1;

        Yodlee_User_Account__c sobj22 = new Yodlee_User_Account__c(
            Name = 'TESTDATA-txn DUNKIN',                                              // Yodlee User Accounts Name
            Account_Number__c = '5031123456',                                            // Account Number
            Account_Holder_Name__c = 'accountHolder',                                    // Account Holder Name
            Available_Balance__c = 404.78,                                               // Available Balance
            Current_Balance__c = 304.78,                                                 // Current Balance
            Account_Type__c = 'CHECKING',                                                // Account Type
            Status__c = 'ACTIVE',                                                        // Status
            Yodlee_Application__c=appList[0].Id,
            Yodlee_Account__c= accList[0].id
            );
        insert sobj22;

        Attachment attach = new Attachment();
        attach.Name = appList[0].Id+'linked_acct_';
        Blob bodyBlob = Blob.valueOf('Unit Test Attachment Body');
        attach.body = bodyBlob;
        attach.parentId = appList[0].Id;
        insert attach;
    }

    @isTest static void testNeoVerifyTransactionQueue() {
        Test.startTest();
        Set<Id> alist = new Set<Id>();
        for(genesis__Applications__c app:[select Id from genesis__Applications__c limit 99]) {
            alist.add(app.id);
        }
        Id jobId = System.enqueueJob(new MW_NeoVerifyTransactionsCalloutQueue(alist));
        MW_Callout__c newCalloutJob = new MW_Callout__c();
        newCalloutJob.JobID__c = jobId;
        newCalloutJob.Status__c = 'Queued';
        insert newCalloutJob;
        Test.stopTest();
    }

    @isTest static void testMethod1() {
        test.StartTest();
        genesis__Applications__c aapp = [select Id from genesis__Applications__c];
        NeoVeifyRequestDetails ff = new NeoVeifyRequestDetails();
        ff.linkAccountTransactions(aapp.id, '1232312');
        test.StopTest();
    }


    @isTest static void testCallout() {

        Set<Id> alist = new Set<Id>();
        for(genesis__Applications__c app:[select Id from genesis__Applications__c limit 99]) {
            alist.add(app.id);
        }
        String xmlString ='{ "report_id": "SL2Mq6jtrCuirj7OiiS5FcM85","url": "https://payofftest.neoverify.com/income_verification/SL2Mq6jtrCuirj7OiiS5FcM85"}';
        Test.setMock(HttpCalloutMock.class, new MW_NeoVerifyIntegrationHttpCalloutMock(xmlString, 201));
        MW_NeoVerifyIntegration.postRegNeoVerify(alist);
    }

    @isTest static void testCalloutFail() {

        Set<Id> alist = new Set<Id>();
        for(genesis__Applications__c app:[select Id from genesis__Applications__c limit 99]) {
            alist.add(app.id);
        }
        String xmlString ='{ "report_id": "","url": "https://payofftest.neoverify.com/income_verification/SL2Mq6jtrCuirj7OiiS5FcM85"}';
        Test.setMock(HttpCalloutMock.class, new MW_NeoVerifyIntegrationHttpCalloutMock(xmlString, 200));
        MW_NeoVerifyIntegration.postRegNeoVerify(alist);
    }

    @isTest static void testCalloutFail2() {
		test.startTest();
        Set<Id> alist = new Set<Id>();
        for(genesis__Applications__c app:[select Id from genesis__Applications__c limit 99]) {
            alist.add(app.id);
        }
        String xmlString ='{ "report_id": 123456,"url": "https://payofftest.neoverify.com/income_verification/SL2Mq6jtrCuirj7OiiS5FcM85"}';
        Test.setMock(HttpCalloutMock.class, new MW_NeoVerifyIntegrationHttpCalloutMock(xmlString, 200));
        MW_NeoVerifyIntegration.postRegNeoVerify(alist);
        test.stopTest();
    }

    @isTest static void postlinkAccountTransactionsTest(){
        test.startTest();
        List<Attachment> aList = [select id, name, body, parentId from Attachment limit 99];
        Test.setMock(HttpCalloutMock.class, new MW_NeoVerifyIntegrationHttpCalloutMock('test response', 202));
        MW_NeoVerifyIntegration.postlinkAccountTransactions(aList[0].id, 'SL2Mq6jtrCuirj7OiiS5FcM85');
        test.stopTest();
    }

    @isTest static void testReportStatusFail() {

        List<ID> alist = new List<ID>();

        for(genesis__Applications__c app:[select Id from genesis__Applications__c limit 99]) {
            alist.add(app.id);
        }
        //StaticResource sr = [select Body from StaticResource where Name='neoVerify' limit 1];
        String xmlString = '{"report_status": {"status": "Report Ready","report_id": "ouztd12PRze8dYnceQ4eQAgBd"}}';//sr.Body.toString();

        Test.setMock(HttpCalloutMock.class, new MW_NeoVerifyIntegrationHttpCalloutMock(xmlString, 200));
        MW_NeoVerifyIntegration.processNeoVerifyReport(alist);
        //MW_NeoVerifyIntegration.getReportStatus(alist[0]);
    }

    @isTest static void testReportSta() {
		test.startTest();
        List<ID> alist = new List<ID>();

        for(genesis__Applications__c app:[select Id from genesis__Applications__c limit 99]) {
            alist.add(app.id);
        }

        String xmlString ='{ "Employments": [{"employer": "Report Ready","first_pay_date1": "ouztd12PRze8dYnceQ4eQAgBd","last_pay_date1":"45454","paychecks":1,"avg_paycheck":"1.0","pay_cycle":"monthly","next_day_date1":"45454","total_earnings":"1.0"}]}';

        Test.setMock(HttpCalloutMock.class, new MW_NeoVerifyIntegrationHttpCalloutMock(xmlString, 200));
        MW_NeoVerifyIntegration.Neoverifyfuturemethod(alist[0]);
        test.stoptest();
    }
    @isTest static void testscorecardtrigger() {
        
         list<account> accList                  = MW_DataFactoryTest.createAccounts(1);
         insert accList;
         list<genesis__Applications__c> appList = MW_DataFactoryTest.createApplication(1, accList[0].Id);
         insert appList;
 
         Neo_Verify__c no = new Neo_Verify__c(
         Application__c = appList[0].Id,
         NSF_OD__c = '1');
         insert no;
        }
    @isTest static void postCreateRegisterUserRequestTest(){
        Set<Id> alist = new Set<Id>();
        for(genesis__Applications__c app:[select Id from genesis__Applications__c limit 99]) {
            alist.add(app.id);
        }
        String xmlString ='{ "report_id": "","url": "https://payofftest.neoverify.com/income_verification/SL2Mq6jtrCuirj7OiiS5FcM85"}';
        Test.setMock(HttpCalloutMock.class, new MW_NeoVerifyIntegrationHttpCalloutMock(xmlString, 200));
        MW_NeoVerifyIntegration.postCreateRegisterUserRequest([select Id from genesis__Applications__c limit 1].id);
        
    }

}