unpackaged/main/default/objects/Account/fields/loan__SOCIAL_SECURITY_NUMBER__c.field-meta.xml
<CustomField>
    <fullName>loan__SOCIAL_SECURITY_NUMBER__c</fullName>
    <label>SOCIAL_SECURITY_NUMBER</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/peer__First_Name__c.field-meta.xml
<CustomField>
    <fullName>peer__First_Name__c</fullName>
    <label>First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/peer__Last_Name__c.field-meta.xml
<CustomField>
    <fullName>peer__Last_Name__c</fullName>
    <label>Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Member.recordType-meta.xml
<RecordType>
    <fullName>Member</fullName>
    <active>true</active>
    <label>Member</label>
</RecordType>

unpackaged/main/default/objects/genesis__Applications__c/genesis__Applications__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{0000000000}</displayFormat>
        <label>Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/genesis__Applications__c/fields/Bureau_SSN__c.field-meta.xml
<CustomField>
    <fullName>Bureau_SSN__c</fullName>
    <label>Bureau SSN</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/genesis__Applications__c/fields/genesis__Account__c.field-meta.xml
<CustomField>
    <fullName>genesis__Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Applications_account</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/loan__Loan_Account__c/loan__Loan_Account__c.object-meta.xml
<CustomObject>
    <description>Lending Account</description>
    <label>CL Contract</label>
    <nameField>
        <displayFormat>LAI-{00000000}</displayFormat>
        <label>CL Contract ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CL Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/loan__Loan_Account__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>genesis__Applications__c</referenceTo>
    <relationshipLabel>CL Contracts</relationshipLabel>
    <relationshipName>CL_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/loan__Loan_Account__c/fields/loan__Account__c.field-meta.xml
<CustomField>
    <fullName>loan__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Please choose a account, which will be associated as a customer on this lending account.
You can create a new account, from the lookup window by clicking on new or select the existing account from the lookup.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Loan_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/loan__Loan_Account__c/fields/loan__Loan_Product_Name__c.field-meta.xml
<CustomField>
    <fullName>loan__Loan_Product_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Loan Product Name</description>
    <inlineHelpText>Please choose a lending product, which will be associated as a lending product on this lending account.
You can choose a existing product from the lookup or create a new product from 
Servicing Configuration-&gt;Product-&gt;Create new lending product</inlineHelpText>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Please select active lending product.</errorMessage>
        <filterItems>
            <field>loan__Loan_Product__c.loan__Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>loan__Loan_Product__c</referenceTo>
    <relationshipName>Loan_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/loan__Loan_Account__c/fields/loan__Loan_Status__c.field-meta.xml
<CustomField>
    <fullName>loan__Loan_Status__c</fullName>
    <inlineHelpText>Status of the Account, expected values are :
Pending Approval
Active - Good Standing
Active - Bad Standing
Active - Matured
Approved
Canceled
Closed - Obligations met
Closed- Written Off
Closed - Refinanced
Partial Application</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Partial Application</fullName>
                <default>true</default>
                <label>Partial Application</label>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Active - Good Standing</fullName>
            </value>
            <value>
                <fullName>Active - Bad Standing</fullName>
            </value>
            <value>
                <fullName>Closed - Obligations met</fullName>
            </value>
            <value>
                <fullName>Closed- Written Off</fullName>
            </value>
            <value>
                <fullName>Closed - Refinanced</fullName>
            </value>
            <value>
                <fullName>Active - Matured</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Active - Marked for Closure</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/loan__Loan_Product__c/loan__Loan_Product__c.object-meta.xml
<CustomObject>
    <description>Lending Product Definition1</description>
    <label>Lending Product</label>
    <nameField>
        <label>Loan Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lending Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/loan__Loan_Status__c/loan__Loan_Status__c.object-meta.xml
<CustomObject>
    <description>Object for storing Loan Statuses</description>
    <label>Loan Status</label>
    <nameField>
        <label>Loan Status Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loan Status</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/loan__Office_Name__c/loan__Office_Name__c.object-meta.xml
<CustomObject>
    <description>Name of the office</description>
    <label>Company</label>
    <nameField>
        <label>Company</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/classes/ActivityOnOtherAccountsControllerTest.cls
@isTest
private class ActivityOnOtherAccountsControllerTest {
  @testSetup 
  static void setup(){

    test.startTest();
    
    //Create pre-exist account
    Account preExistAct = MW_GlobalTestUtility.GetAccount('Member');
    //preExistAct.Name = 'PreExist Act';
    preExistAct.peer__First_Name__c ='PreExist';
    preExistAct.peer__Last_Name__c = 'Act';
    Insert preExistAct;

    //Create app for pre-exist account
    genesis__Applications__c appForPreExistAct = MW_GlobalTestUtility.GetApplication();
    appForPreExistAct.genesis__Account__c = preExistAct.Id;
    appForPreExistAct.Bureau_SSN__c = preExistAct.loan__SOCIAL_SECURITY_NUMBER__c;
    Insert appForPreExistAct;

    //Create Loan for pre-exist account
    loan.TestHelper.createSeedDataForTesting();
    loan__Office_Name__c office = loan.TestHelper.createOffice();
    loan__Loan_Product__c loanProd = MW_GlobalTestUtility.GetLoanProduct(); 
    insert loanProd;
    loan__Loan_Account__c loanForPreExistAcct = MW_GlobalTestUtility.GetCLContract();
    loanForPreExistAcct.loan__Account__c= preExistAct.Id;
    loanForPreExistAcct.loan__Loan_Product_Name__c=loanProd.Id;
    loanForPreExistAcct.application__c = appForPreExistAct.id;
    loanForPreExistAcct.loan__Loan_Status__c = 'Active - Good Standing'; //'Closed - Obligations met';
    Insert loanForPreExistAcct;

    //Create one more Account
    Account actWithDuplicateSsn = MW_GlobalTestUtility.GetAccount('Member');
    //actWithDuplicateSsn.Name = 'ActWithDuplicate Ssn';
    actWithDuplicateSsn.peer__First_Name__c ='ActWithDuplicate';
    actWithDuplicateSsn.peer__Last_Name__c = 'Ssn';
    Insert actWithDuplicateSsn;

    //Create app for one more account with duplicate SSN
    genesis__Applications__c appForDuplicateAct = MW_GlobalTestUtility.GetApplication();
    appForDuplicateAct.genesis__Account__c = actWithDuplicateSsn.Id;
    appForDuplicateAct.Bureau_SSN__c = preExistAct.loan__SOCIAL_SECURITY_NUMBER__c;
    Insert appForDuplicateAct;

    Test.stopTest();
  }
  
  @isTest static void TestActivities(){
    //call controller          
    Account actWithDuplicateSsn = [SELECT Id, Name, loan__SOCIAL_SECURITY_NUMBER__c FROM Account WHERE Name = 'ActWithDuplicate Ssn' LIMIT 1];
    ActivityOnOtherAccountsController actyOnOtherAcct = new ActivityOnOtherAccountsController();
    actyOnOtherAcct.AcctId = actWithDuplicateSsn.Id;
    actyOnOtherAcct.PopulateAcctActivities();

    System.AssertEquals(true, actyOnOtherAcct.IsAcctActivitiesExist);
  }
}