unpackaged/main/default/objects/Account/fields/peer__First_Name__c.field-meta.xml
<CustomField>
    <fullName>peer__First_Name__c</fullName>
    <label>First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/genesis__Applications__c/genesis__Applications__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{0000000000}</displayFormat>
        <label>Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/genesis__Applications__c/fields/genesis__Loan_Amount__c.field-meta.xml
<CustomField>
    <fullName>genesis__Loan_Amount__c</fullName>
    <label>Loan Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Redecision_Request__c/Redecision_Request__c.object-meta.xml
<CustomObject>
    <label>Redecision Request</label>
    <nameField>
        <displayFormat>RR-{00000000}</displayFormat>
        <label>Redecision Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Redecision Request</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Redecision_Request__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <label>Application</label>
    <referenceTo>genesis__Applications__c</referenceTo>
    <relationshipLabel>Redecision Request</relationshipLabel>
    <relationshipName>Redecision_Request</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Redecision_Request__c/fields/Body__c.field-meta.xml
<CustomField>
    <fullName>Body__c</fullName>
    <label>Body</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Redecision_Request__c/fields/Triggered_From__c.field-meta.xml
<CustomField>
    <fullName>Triggered_From__c</fullName>
    <label>Triggered From</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Account</fullName>
            </value>
            <value>
                <fullName>Application</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/MW_RedecisionRequestTest.cls
@isTest
private class MW_RedecisionRequestTest {

	@isTest static void accountRedecisionRequestTest() {
		Test.startTest();

		List<account> accList = MW_DataFactoryTest.createAccounts(1);
		insert accList;
		List<genesis__Applications__c> appList = MW_DataFactoryTest.createApplication(1, accList[0].Id);
		insert appList;

		Redecision_Request__c testObj = new Redecision_Request__c();
		testObj.Application__c = appList[0].Id;
		testObj.Triggered_From__c = 'Account';
		testObj.Body__c = 'peer__First_Name__c';
		insert testObj;

		MW_RedecisionRequest.invokeRedecisionRequest(new List<Redecision_Request__c>{testObj});

		System.assertEquals('redecision', MW_RedecisionRequest.redeci.type);

		Test.stopTest();
	}

	@isTest static void applicationRedecisionRequestTest() {
		Test.startTest();

		List<account> accList = MW_DataFactoryTest.createAccounts(1);
		insert accList;
		List<genesis__Applications__c> appList = MW_DataFactoryTest.createApplication(1, accList[0].Id);
		insert appList;

		Redecision_Request__c testObj = new Redecision_Request__c();
		testObj.Application__c = appList[0].Id;
		testObj.Triggered_From__c = 'Application';
		testObj.Body__c = 'genesis__Loan_Amount__c';
		insert testObj;

		MW_RedecisionRequest.invokeRedecisionRequest(new List<Redecision_Request__c>{testObj});

		System.assertEquals('redecision', MW_RedecisionRequest.redeci.type);

		Test.stopTest();
	}
}