unpackaged/main/default/objects/genesis__Amortization_Schedule__c/genesis__Amortization_Schedule__c.object-meta.xml
<CustomObject>
    <description>Amortization schedule is also called as Repayment schedule.</description>
    <label>Amortization_Schedule</label>
    <nameField>
        <displayFormat>AMZ-{0000000000}</displayFormat>
        <label>Amortization Schedule ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Amortization_Schedule</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/genesis__Amortization_Schedule__c/fields/genesis__Application__c.field-meta.xml
<CustomField>
    <fullName>genesis__Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>genesis__Applications__c</referenceTo>
    <relationshipLabel>Amortization_Schedule</relationshipLabel>
    <relationshipName>Amortization_Schedule</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/genesis__Amortization_Schedule__c/fields/genesis__Due_Date__c.field-meta.xml
<CustomField>
    <fullName>genesis__Due_Date__c</fullName>
    <description>Due date</description>
    <inlineHelpText>The date on which the loan payment is due.</inlineHelpText>
    <label>Due Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/genesis__Amortization_Schedule__c/fields/genesis__Due_Interest__c.field-meta.xml
<CustomField>
    <fullName>genesis__Due_Interest__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Due Interest</description>
    <inlineHelpText>Due Interest</inlineHelpText>
    <label>Due Interest</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/genesis__Amortization_Schedule__c/fields/genesis__Due_Principal__c.field-meta.xml
<CustomField>
    <fullName>genesis__Due_Principal__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Due Principal</description>
    <inlineHelpText>Due Principal</inlineHelpText>
    <label>Due Principal</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/genesis__Amortization_Schedule__c/fields/genesis__Payment_Number__c.field-meta.xml
<CustomField>
    <fullName>genesis__Payment_Number__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Payment Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/genesis__Amortization_Schedule__c/fields/genesis__Total_Due_Amount__c.field-meta.xml
<CustomField>
    <fullName>genesis__Total_Due_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Total Due Amount</description>
    <inlineHelpText>Total Due Amount</inlineHelpText>
    <label>Total Due Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/genesis__Applications__c/genesis__Applications__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{0000000000}</displayFormat>
        <label>Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/genesis__Applications__c/fields/genesis__APR__c.field-meta.xml
<CustomField>
    <fullName>genesis__APR__c</fullName>
    <description>Annual Percentage Rate</description>
    <label>APR</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/objects/genesis__Applications__c/fields/genesis__Draw_Period_End_Date__c.field-meta.xml
<CustomField>
    <fullName>genesis__Draw_Period_End_Date__c</fullName>
    <label>Draw Period End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/genesis__Applications__c/fields/genesis__Due_Day__c.field-meta.xml
<CustomField>
    <fullName>genesis__Due_Day__c</fullName>
    <description>dueDay field.</description>
    <inlineHelpText>If Due Day field is null, then by default it will have Expected First Payment Date day value</inlineHelpText>
    <label>Due_Day</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/genesis__Applications__c/fields/genesis__Expected_First_Payment_Date__c.field-meta.xml
<CustomField>
    <fullName>genesis__Expected_First_Payment_Date__c</fullName>
    <label>Expected First Payment Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/genesis__Applications__c/fields/genesis__Expected_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>genesis__Expected_Start_Date__c</fullName>
    <label>Expected Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/genesis__Applications__c/fields/genesis__Funding_in_Tranches__c.field-meta.xml
<CustomField>
    <fullName>genesis__Funding_in_Tranches__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Funding in Tranches</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/genesis__Applications__c/fields/Origination_fee__c.field-meta.xml
<CustomField>
    <fullName>Origination_fee__c</fullName>
    <label>Origination fee</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/classes/ApplicationControllerTest.cls
@isTest
public class ApplicationControllerTest {
    static testMethod void test_ApplicationController_UseCase1(){
        loan.TestHelper.createSeedDataForTesting();
        loan.TestHelper.createOffice();
        genesis__Applications__c genesis_applications_Obj = new genesis__Applications__c(
            genesis__Due_Day__c = 20,
            genesis__Expected_First_Payment_Date__c = system.Today(),
            genesis__Expected_Start_Date__c = system.Today(),
            genesis__Funding_in_Tranches__c = true,
            genesis__Draw_Period_End_Date__c = system.Today(),
            genesis__APR__c = 173,
            Origination_fee__c = 100.2345
        );
        Insert genesis_applications_Obj;
        PageReference pageRef = Page.TILDocument;
        Test.setCurrentPage(pageRef);
        List<Id> applist = new List<Id>();
        applist.add(genesis_applications_Obj.Id);
        pageRef.getParameters().put('Id', String.valueOf(genesis_applications_Obj.Id));
        //genesis.AutoGenerateSchedule.generateSchedule(applist);
        genesis__Amortization_Schedule__c amortSchedule = new genesis__Amortization_Schedule__c();
        amortSchedule.genesis__Due_Date__c = Date.today();
        amortSchedule.genesis__Total_Due_Amount__c = 120;
        amortSchedule.genesis__Due_Principal__c = 100;
        amortSchedule.genesis__Due_Interest__c = 20;
        amortSchedule.genesis__Payment_Number__c=1;
        amortSchedule.genesis__Application__c = genesis_applications_Obj.id;
        insert amortSchedule;
        ApplicationController testApplication = new ApplicationController();
    }
}