unpackaged/main/default/objects/genesis__Application_Document_Category__c/genesis__Application_Document_Category__c.object-meta.xml
<CustomObject>
    <label>Application Document Category</label>
    <nameField>
        <label>Application Document Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application Document Category</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/genesis__Application_Document_Category__c/fields/Action_Reason__c.field-meta.xml
<CustomField>
    <fullName>Action_Reason__c</fullName>
    <formula>IF( (ISPICKVAL(Rejection_Reasons__c, "Accept: Additional Docs")),"We still need additional documents of this type.",
IF( (ISPICKVAL(Rejection_Reasons__c, "Accept: Previous Statement")),"We still need the previous month's bank statement.",IF( (ISPICKVAL(Rejection_Reasons__c, "Accept: Primary Statement")),"We still need the statement from your primary bank account where your income is deposited.",IF( (ISPICKVAL(Rejection_Reasons__c, "Accept: More Recent Statement")),"We still need your most recent bank statement.",IF((ISPICKVAL(Rejection_Reasons__c, "Accept: Not Personal Account")),"We still need your personal account statement as we cannot use business accounts for verification.",
IF( ISPICKVAL(Rejection_Reasons__c, "Accept: Previous Paystub"),"We still need a paystub from the previous pay period.",
IF( ISPICKVAL(Rejection_Reasons__c, "Statement: Missing Pages"),"Document Incomplete: Please include all pages of your bank statement.",
IF( ISPICKVAL(Rejection_Reasons__c, "Statement: Not PDF"),"Incorrect file type: Please upload your most recent PDF bank statement. You can download this from your online bank account.",
IF( ISPICKVAL(Rejection_Reasons__c, "Statement: Not Recent"),"Document out of date: Please upload the most recent version of your bank statement.",
IF( ISPICKVAL(Rejection_Reasons__c, "Paystub: Not Recent"),"Document out of date: Please upload the most recent version of your paystubs.",
IF( ISPICKVAL(Rejection_Reasons__c, "ID: Expired"),"Document out of date: Please upload a non-expired form of identification.",
IF( ISPICKVAL(Rejection_Reasons__c, "ID: Non-color"),"Image not in color: Please upload a color photo of your ID. Hint: Use your smart phone to take a picture.",
IF( ISPICKVAL(Rejection_Reasons__c, "ID: Security Image"),"Please upload a copy of your ID with the security image clearly visible.",
IF( ISPICKVAL(Rejection_Reasons__c, "Blurry/Glare/Dark"),"Insufficient quality: Please upload a clear and legible copy.",
IF( ISPICKVAL(Rejection_Reasons__c, "Image Cut Off"),"Insufficient quality: Please make sure the entire document is clearly visible.",
IF( ISPICKVAL(Rejection_Reasons__c, "Not Applicable"),"Not applicable: This document is not required.",
IF( ISPICKVAL(Rejection_Reasons__c, "Duplicate"),"Duplicate: This document is a duplicate of an existing uploaded document.",
IF( ISPICKVAL(Rejection_Reasons__c, "Password Protected"),"Password Protected: This file is password protected. Please upload an accessible file."
,NULL))))))))))))))))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Action Reason</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/genesis__Application_Document_Category__c/fields/Application_Email__c.field-meta.xml
<CustomField>
    <fullName>Application_Email__c</fullName>
    <formula>genesis__Application__r.Application_Email__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Application Email</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/genesis__Application_Document_Category__c/fields/Borrower_s_Email__c.field-meta.xml
<CustomField>
    <fullName>Borrower_s_Email__c</fullName>
    <description>/* Created By Nupur */

------ For Email Alerts --pending_document_reminder.liquid</description>
    <label>Borrower's Email</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/genesis__Application_Document_Category__c/fields/Borrower_s_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Borrower_s_First_Name__c</fullName>
    <formula>genesis__Application__r.Borrower_s_First_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Borrower's First Name</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/genesis__Application_Document_Category__c/fields/Box_URl__c.field-meta.xml
<CustomField>
    <fullName>Box_URl__c</fullName>
    <label>Box URL</label>
    <type>Url</type>
</CustomField>

unpackaged/main/default/objects/genesis__Application_Document_Category__c/fields/Deliver_Status__c.field-meta.xml
<CustomField>
    <fullName>Deliver_Status__c</fullName>
    <description>Used in Loan Origination Package - Deliver Documents From CLS to Push the documents to Box</description>
    <label>Deliver Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>FF</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/genesis__Application_Document_Category__c/fields/genesis__Active__c.field-meta.xml
<CustomField>
    <fullName>genesis__Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/genesis__Application_Document_Category__c/fields/genesis__Application__c.field-meta.xml
<CustomField>
    <fullName>genesis__Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>genesis__Applications__c</referenceTo>
    <relationshipLabel>Application Document Category</relationshipLabel>
    <relationshipName>Application_Document_Category</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/genesis__Application_Document_Category__c/fields/genesis__Description__c.field-meta.xml
<CustomField>
    <fullName>genesis__Description__c</fullName>
    <label>Description</label>
    <length>32000</length>
    <type>Html</type>
</CustomField>

unpackaged/main/default/objects/genesis__Application_Document_Category__c/fields/genesis__Document_Category__c.field-meta.xml
<CustomField>
    <fullName>genesis__Document_Category__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Document Category</label>
    <referenceTo>genesis__Document_Category__c</referenceTo>
    <relationshipLabel>Application Document Category</relationshipLabel>
    <relationshipName>Application_Document_Category</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/genesis__Application_Document_Category__c/fields/genesis__Email__c.field-meta.xml
<CustomField>
    <fullName>genesis__Email__c</fullName>
    <label>Email</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/genesis__Application_Document_Category__c/fields/genesis__Id__c.field-meta.xml
<CustomField>
    <fullName>genesis__Id__c</fullName>
    <description>Unique Id</description>
    <label>Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/genesis__Application_Document_Category__c/fields/genesis__Parent_Application_Document_Category__c.field-meta.xml
<CustomField>
    <fullName>genesis__Parent_Application_Document_Category__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Application Document Category</label>
    <referenceTo>genesis__Application_Document_Category__c</referenceTo>
    <relationshipLabel>Application Document Category</relationshipLabel>
    <relationshipName>Application_Document_Category</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/genesis__Application_Document_Category__c/fields/genesis__Parent_Id__c.field-meta.xml
<CustomField>
    <fullName>genesis__Parent_Id__c</fullName>
    <label>Parent Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/genesis__Application_Document_Category__c/fields/genesis__Party__c.field-meta.xml
<CustomField>
    <fullName>genesis__Party__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Party responsible for providing the document.</description>
    <label>Responsible Party</label>
    <referenceTo>clcommon__Party__c</referenceTo>
    <relationshipLabel>Application Document Category</relationshipLabel>
    <relationshipName>Application_Document_Category</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/genesis__Application_Document_Category__c/fields/genesis__Party_Type__c.field-meta.xml
<CustomField>
    <fullName>genesis__Party_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Party Type</label>
    <referenceTo>clcommon__Party_Type__c</referenceTo>
    <relationshipLabel>Application Document Category</relationshipLabel>
    <relationshipName>Application_Document_Category</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/genesis__Application_Document_Category__c/fields/genesis__Review_Assigned_To__c.field-meta.xml
<CustomField>
    <fullName>genesis__Review_Assigned_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Review Assigned To</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Application_Document_Category</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/genesis__Application_Document_Category__c/fields/Lead_Id__c.field-meta.xml
<CustomField>
    <fullName>Lead_Id__c</fullName>
    <formula>genesis__Application__r.Lead_ID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Lead Id</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/genesis__Application_Document_Category__c/fields/Member_Email__c.field-meta.xml
<CustomField>
    <fullName>Member_Email__c</fullName>
    <formula>genesis__Application__r.genesis__Account__r.cnotify__Email__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Member Email</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/genesis__Applications__c/genesis__Applications__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{0000000000}</displayFormat>
        <label>Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/genesis__Applications__c/fields/Application_Email__c.field-meta.xml
<CustomField>
    <fullName>Application_Email__c</fullName>
    <formula>if(genesis__Account__r.cnotify__Email__c != NULL, genesis__Account__r.cnotify__Email__c, '')</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Application Email</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/genesis__Applications__c/fields/Borrower_s_Email__c.field-meta.xml
<CustomField>
    <fullName>Borrower_s_Email__c</fullName>
    <description>/*Created By Nupur */ 
For Email Alert</description>
    <label>Borrower's Email</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/genesis__Applications__c/fields/Borrower_s_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Borrower_s_First_Name__c</fullName>
    <description>/*Created by Nupur */ 
- For Email Templates</description>
    <formula>genesis__Account__r.Borrower_s_First_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Borrower's First Name</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/genesis__Applications__c/fields/genesis__Description__c.field-meta.xml
<CustomField>
    <fullName>genesis__Description__c</fullName>
    <label>Description</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

unpackaged/main/default/objects/genesis__Applications__c/fields/Lead_ID__c.field-meta.xml
<CustomField>
    <fullName>Lead_ID__c</fullName>
    <description>This is the LEAD GUID received from FE</description>
    <externalId>true</externalId>
    <label>Lead ID</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/genesis__Applications__c/fields/LEAD_ID_ExtKey__c.field-meta.xml
<CustomField>
    <fullName>LEAD_ID_ExtKey__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>LEAD_ID_ExtKey</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/genesis__Applications__c/fields/Member_ID__c.field-meta.xml
<CustomField>
    <fullName>Member_ID__c</fullName>
    <formula>genesis__Account__r.Member_ID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Member ID</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/genesis__Document_Category__c/genesis__Document_Category__c.object-meta.xml
<CustomObject>
    <label>Document Category</label>
    <nameField>
        <displayFormat>DC-{00000000}</displayFormat>
        <label>Document Category Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Document Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/genesis__Document_Category__c/fields/genesis__Category_Name__c.field-meta.xml
<CustomField>
    <fullName>genesis__Category_Name__c</fullName>
    <label>Category Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/genesis__Document_Category__c/fields/genesis__Description__c.field-meta.xml
<CustomField>
    <fullName>genesis__Description__c</fullName>
    <label>Description</label>
    <length>130000</length>
    <type>Html</type>
</CustomField>

unpackaged/main/default/objects/genesis__Document_Category__c/fields/genesis__Parent_Document_Category__c.field-meta.xml
<CustomField>
    <fullName>genesis__Parent_Document_Category__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Child document category to define folder structure in documents.</description>
    <label>Parent Document Category</label>
    <referenceTo>genesis__Document_Category__c</referenceTo>
    <relationshipLabel>Document Categories</relationshipLabel>
    <relationshipName>Document_Categories</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/MW_Settings__c/MW_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>MW_Settings</label>
</CustomObject>

unpackaged/main/default/objects/MW_Settings__c/fields/docCategoriesNamestoskip__c.field-meta.xml
<CustomField>
    <fullName>docCategoriesNamestoskip__c</fullName>
    <label>docCategoriesNamestoskip</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/MW_DocumentCategoryHandler.cls
public with sharing class MW_DocumentCategoryHandler {

    public Static List<genesis__Application_Document_Category__c> applicationDocumentCategory(String appId)
    {
        List<String> docCategoriesNamestoskip = MW_Settings__c.getInstance().docCategoriesNamestoskip__c.split(',');
        List<genesis__Application_Document_Category__c> sobjList = new List<genesis__Application_Document_Category__c>();
        List<genesis__Application_Document_Category__c> sobjList1 = new List<genesis__Application_Document_Category__c>();

        /* -- CLS-892 - Doc upload temporary fix for MVP -- in below query end after OR with Hardcoded name Name ='Verification Documents' -- */
        /* -- CLS-1177 -- Deal room -- MW change payload sent back to FE for verification docs -- */
        for(genesis__Application_Document_Category__c adc1:[SELECT Id,name, Action_Reason__c, genesis__Active__c, genesis__Application__c, genesis__Application__r.Lead_Id__c, genesis__Application__r.LEAD_ID_ExtKey__c, genesis__Application__r.Member_ID__c, Application_Email__c,Borrower_s_Email__c,
                                                           Borrower_s_First_Name__c,Box_URl__c,Deliver_Status__c, genesis__Description__c, genesis__Document_Category__r.genesis__Category_Name__c,
                                                           genesis__Parent_Application_Document_Category__r.name,genesis__Parent_Application_Document_Category__r.genesis__Description__c,
                                                           genesis__Document_Category__r.genesis__Parent_Document_Category__r.genesis__Category_Name__c, genesis__Email__c,genesis__Id__c, Member_Email__c,
                                                           genesis__Parent_Application_Document_Category__c, genesis__Parent_Id__c, genesis__Party_Type__c, genesis__Priority__c, Rejection_Reasons__c,
                                                           genesis__Required__c, genesis__Application__r.genesis__Account__c, genesis__Party__c, genesis__Review_Assigned_To__c, genesis__Review_Comments__c, Doc_Code_FF__c, genesis__Reviewed_By__c, genesis__Send_Notification__c,genesis__Status__c, ShareBoxLink__c,
                                                           genesis__Application__r.is_Plaid_Asset_Available__c
                                                           from genesis__Application_Document_Category__c where (genesis__Application__c =:appId
                                                                                                                                          AND genesis__Parent_Application_Document_Category__r.name != 'Root'
                                                                                                                                          AND genesis__Required__c = true AND
                                                                                                                                                                     Name NOT IN : docCategoriesNamestoskip) OR (genesis__Application__c =:appId AND Name ='Verification Documents') LIMIT 25]) {
            sobjList1.add(adc1);
        }

        Set<String> ParentIdOfRequiredDocs = new Set<String>();
        for(genesis__Application_Document_Category__c ad: sobjList1)
        {
            if(ad.genesis__Parent_Application_Document_Category__r.name != 'Verification Documents' && ad.genesis__Parent_Application_Document_Category__r.name!='Self Employed Documents' && ad.genesis__Parent_Application_Document_Category__r.name!='Root')
            {
               ParentIdOfRequiredDocs.add(ad.genesis__Parent_Application_Document_Category__c);
            }
            else
            {
                 sobjList.add(ad);
            }

        }

        for(genesis__Application_Document_Category__c adc:[SELECT Id,name, Action_Reason__c, genesis__Active__c, genesis__Application__c, genesis__Application__r.Lead_Id__c, genesis__Application__r.LEAD_ID_ExtKey__c, genesis__Application__r.Member_ID__c, Application_Email__c,Borrower_s_Email__c,
                                                           Borrower_s_First_Name__c,Box_URl__c,Deliver_Status__c, genesis__Description__c, genesis__Document_Category__r.genesis__Category_Name__c,
                                                           genesis__Parent_Application_Document_Category__r.name,genesis__Parent_Application_Document_Category__r.genesis__Description__c,
                                                           genesis__Document_Category__r.genesis__Parent_Document_Category__r.genesis__Category_Name__c, genesis__Email__c,genesis__Id__c, Member_Email__c,
                                                           genesis__Parent_Application_Document_Category__c, genesis__Parent_Id__c, genesis__Party_Type__c, genesis__Priority__c, Rejection_Reasons__c,
                                                           genesis__Required__c, genesis__Application__r.genesis__Account__c, genesis__Party__c, genesis__Review_Assigned_To__c, genesis__Review_Comments__c, Doc_Code_FF__c, genesis__Reviewed_By__c, genesis__Send_Notification__c,genesis__Status__c, ShareBoxLink__c,
                                                           genesis__Application__r.is_Plaid_Asset_Available__c
                                                           from genesis__Application_Document_Category__c where genesis__Parent_Application_Document_Category__c IN : ParentIdOfRequiredDocs order by Last2characters_forSorting__c ASC LIMIT 100]) {
            sobjList.add(adc);
        }
         /* -- END --- CLS-1177 -- Deal room -- MW change payload sent back to FE for verification docs -- */
        return sobjList;

    }

    //@future (callout=true)
    public static void processDataCate(List<String> appList){

        /* change for too many soql : 201 on MWQueable job */
        Set<String> appElements = new Set<String>();
        appElements.addAll(appList);
        /* ---- END change for too many soql : 201 on MWQueable job */
        System.debug('>>>>>>%%%%'+appElements.size());
        for(String appid:appElements) {
            Sync_Document_Category_ToWebHook(appid);
        }

    }

    public static void Sync_Document_Category_ToWebHook(String appid)
    {
        list<DocumentInformation> listOfDoc = new list<DocumentInformation>();
        list<DocumentData> listOfDocdata    = new list<DocumentData>();

        String leadId;
        String lead_id_ext_key;
        String member_id;

        List<genesis__Application_Document_Category__c> appDclist = applicationDocumentCategory(appid);

        List<String> accList = new List<String>();
        for(genesis__Application_Document_Category__c acc:appDclist) {
            accList.add(acc.genesis__Application__r.genesis__Account__c);
        }

        //LOP-324, don't need this
        //Map<Id, boolean> accMap                                   = MW_WebhookHelper.applicationHasYodleeDetails(accList);

        for(genesis__Application_Document_Category__c docCatlist: appDclist)
        {
            //LOP-324, don't need this
            /*
            if((docCatlist.genesis__Application__r.is_Plaid_Asset_Available__c || (accMap.get(docCatlist.genesis__Application__r.genesis__Account__c) !=null & accMap.size()>0)) &&
               docCatlist.genesis__Parent_Application_Document_Category__r.name=='Bank Statements' && docCatlist.genesis__Status__c=='OPEN')
                continue;
            */

            DocumentInformation dci = new DocumentInformation();
            if(docCatlist.genesis__Parent_Application_Document_Category__r.name!='Verification Documents' /*CLS-892 --> */ && docCatlist.genesis__Parent_Application_Document_Category__r.name!='Root' && docCatlist.genesis__Parent_Application_Document_Category__r.name!='Self Employed Documents') {
                System.debug('>>>>'+docCatlist.genesis__Parent_Application_Document_Category__r.name);
                dci.category           = docCatlist.genesis__Parent_Application_Document_Category__r.name;
                dci.category_label     = docCatlist.genesis__Parent_Application_Document_Category__r.name;
                dci.category_text      = docCatlist.genesis__Parent_Application_Document_Category__r.genesis__Description__c;
            }else{
                dci.category           = docCatlist.genesis__Document_Category__r.genesis__Category_Name__c;
                dci.category_label     = docCatlist.genesis__Document_Category__r.genesis__Category_Name__c;
                dci.category_text      = docCatlist.genesis__Description__c;
            }
            dci.document_id        = docCatlist.Id;
            dci.status             = docCatlist.genesis__Status__c;
            dci.url                = docCatlist.Box_URl__c;
            dci.share_box_link     = docCatlist.ShareBoxLink__c;
            dci.isRequired         = docCatlist.genesis__Required__c;
            if(docCatlist.Doc_Code_FF__c!=null && docCatlist.Doc_Code_FF__c!='')
                dci.code               = docCatlist.Doc_Code_FF__c;
            if(docCatlist.genesis__Status__c == 'REJECTED')
                dci.rejection_reason   = docCatlist.Rejection_Reasons__c;
            listOfDoc.add(dci);

            if(leadId==null) leadId = docCatlist.genesis__Application__r.Lead_Id__c;
            if(lead_id_ext_key == null) lead_id_ext_key = docCatlist.genesis__Application__r.LEAD_ID_ExtKey__c;
            if(member_id == null) member_id = docCatlist.genesis__Application__r.Member_ID__c;
        }

        DocumentData doc    = new DocumentData(leadId,lead_id_ext_key,member_id,listOfDoc);
        listOfDocdata.add(doc);
        System.debug('>>>>>*** ' +listOfDocdata);

        Document_Category_Info syncdci = new Document_Category_Info('verification_docs', listOfDocdata);
        String str = JSON.serialize(syncdci, true);
        System.debug('>> Details '+ str);
        MW_WebhookHandler.CallWebHookIntegration(str, appid, leadId);
    }

    class DocumentInformation {
        public String category;
        public String category_label;
        public String category_text;
        public String section;
        public String section_label;
        public String document_id;
        public String status;
        public String url;
        public String member_id;
        public String lead_id;
        public String share_box_link;
        public String rejection_reason;
        public String code;
        public boolean isRequired;
    }

    class DocumentData {
        DocumentInformation[] docs;
        String lead_guid;
        String lead_id;
        String member_id;
        boolean verification_docs_approved;

        public DocumentData(String leadId, String lead_id_ext_key, String member_id, DocumentInformation[] docData){
            this.lead_guid = leadId;
            this.lead_id = lead_id_ext_key;
            this.member_id = member_id;
            this.docs = docData;
            this.verification_docs_approved=false;
        }
    }

    class Document_Category_Info {
        String type;
        DocumentData[] data;
        public Document_Category_Info(String type, DocumentData[] docData){
            this.type = type;
            this.data = docData;
        }
    }

}