unpackaged/main/default/objects/genesis__Application_Document_Category__c/genesis__Application_Document_Category__c.object-meta.xml
<CustomObject>
    <label>Application Document Category</label>
    <nameField>
        <label>Application Document Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application Document Category</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/genesis__Application_Document_Category__c/fields/Box_URl__c.field-meta.xml
<CustomField>
    <fullName>Box_URl__c</fullName>
    <label>Box URL</label>
    <type>Url</type>
</CustomField>

unpackaged/main/default/objects/genesis__Application_Document_Category__c/fields/genesis__Active__c.field-meta.xml
<CustomField>
    <fullName>genesis__Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/genesis__Application_Document_Category__c/fields/genesis__Application__c.field-meta.xml
<CustomField>
    <fullName>genesis__Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>genesis__Applications__c</referenceTo>
    <relationshipLabel>Application Document Category</relationshipLabel>
    <relationshipName>Application_Document_Category</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/genesis__Application_Document_Category__c/fields/genesis__Document_Category__c.field-meta.xml
<CustomField>
    <fullName>genesis__Document_Category__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Document Category</label>
    <referenceTo>genesis__Document_Category__c</referenceTo>
    <relationshipLabel>Application Document Category</relationshipLabel>
    <relationshipName>Application_Document_Category</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/genesis__Application_Document_Category__c/fields/genesis__Parent_Application_Document_Category__c.field-meta.xml
<CustomField>
    <fullName>genesis__Parent_Application_Document_Category__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Application Document Category</label>
    <referenceTo>genesis__Application_Document_Category__c</referenceTo>
    <relationshipLabel>Application Document Category</relationshipLabel>
    <relationshipName>Application_Document_Category</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/genesis__Applications__c/genesis__Applications__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{0000000000}</displayFormat>
        <label>Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/genesis__Applications__c/fields/Anniversary_Date__c.field-meta.xml
<CustomField>
    <fullName>Anniversary_Date__c</fullName>
    <label>Anniversary Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/genesis__Document_Category__c/genesis__Document_Category__c.object-meta.xml
<CustomObject>
    <label>Document Category</label>
    <nameField>
        <displayFormat>DC-{00000000}</displayFormat>
        <label>Document Category Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Document Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/classes/InvestorReallocation.cls
global Class InvestorReallocation{

    public static void ResetDoc(id appId){
    
        List<Id> app = new List<Id>();
        app.add(appId);
        InvestorReallocation.ResetDocument(app);
    }
    @InvocableMethod
    public static void ResetDocument(List<id> idVal){
        
        list<genesis__Application_Document_Category__c> docCategory = [SELECT id, Name,
                                                                        genesis__Active__c,
                                                                        genesis__Application__c,
                                                                        Box_URl__c 
                                                                        FROM genesis__Application_Document_Category__c
                                                                        WHERE genesis__Application__c in :idVal
                                                                        AND genesis__Active__c = TRUE 
                                                                        AND (Name like 'TIL%'
                                                                        OR Name like 'Cred%')];
                                                                        
        For(genesis__Application_Document_Category__c doc : docCategory){
            doc.genesis__Active__c = FALSE;
            doc.Box_URl__c='';
        }             
        update docCategory;
  //reset Anniversary date to null after reallocation
    list<genesis__Applications__c> ResetAnniv = [SELECT id, Anniversary_Date__c from genesis__Applications__c where id=:idVal AND Anniversary_Date__c != null];
    if(ResetAnniv != null && !ResetAnniv.isEmpty()){
    ResetAnniv[0].Anniversary_Date__c =null;   }
    system.debug('... AppId>> ' + idVal);
    //system.debug('... Anniversary >> ' + ResetAnniv[0].Anniversary_Date__c);
    update ResetAnniv;    
  /*  //to clear out loan documents after reallocation
        //find Esign doc category ID
        String ESignID;
        list<genesis__Application_Document_Category__c> EsignCategory = [SELECT id, genesis__Document_Category__c 
                                                                        FROM genesis__Application_Document_Category__c
                                                                        WHERE genesis__Application__c in :idVal
                                                                        AND genesis__Active__c = TRUE 
                                                                        AND Name like 'Esign%'];
        ESignID = ESignCategory[0].genesis__Document_Category__c;
        //clear out all doc categories with parent category = Esgn Documents ID
        list<genesis__Application_Document_Category__c> docEsignCategory = [SELECT id, Name,
                                                                        genesis__Active__c,
                                                                        genesis__Application__c,
                                                                        Box_URl__c 
                                                                        FROM genesis__Application_Document_Category__c
                                                                        WHERE genesis__Application__c in :idVal
                                                                        AND genesis__Active__c = TRUE 
                                                                        AND genesis__Parent_Application_Document_Category__c= :ESignID];
                                                                        
        For(genesis__Application_Document_Category__c docE : docEsignCategory){
            docE.genesis__Active__c = FALSE;
            docE.Box_URl__c='';
        }             
        update docEsignCategory; */                                            
    }
}