unpackaged/main/default/objects/Lead/fields/lead_guid__c.field-meta.xml
<CustomField>
    <fullName>lead_guid__c</fullName>
    <externalId>true</externalId>
    <label>lead_guid</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/MW_Settings__c/MW_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>MW_Settings</label>
</CustomObject>

force-app/main/default/objects/MW_Settings__c/fields/MemberMatchingDeactivationTool__c.field-meta.xml
<CustomField>
    <fullName>MemberMatchingDeactivationTool__c</fullName>
    <label>MemberMatchingDeactivationTool</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/MW_MemberMatchingDeactivation_Test.cls
@isTest(seeAllData = false)
public class MW_MemberMatchingDeactivation_Test {
	    private static testmethod void testMethod1(){
            MW_Settings__c testSettings= new MW_Settings__c(MemberMatchingDeactivationTool__c = 'https://sfapi-dev.payoff.com/ms/api/admin/member_match_resolver');
            insert testSettings;
            Lead testLead = new Lead(LastName = 'TestLastName',
                                    FirstName = 'TestFirstName',
                                    Company = 'TestCompany',
                                    lead_guid__c= 'a257adc0-70e7-1b50-4300-ecf90e617d09');
            insert testLead;
            

        Test.setMock(HttpCalloutMock.class, new MW_MemberMatchingDeactivation_HttpMock());
        Test.startTest();
        	MW_MemberMatchingDeactivation.makeCallout(testLead.id);
        Test.stopTest();
            
        }
    	private static testmethod void testMethod2(){
            MW_Settings__c testSettings= new MW_Settings__c(MemberMatchingDeactivationTool__c = 'https://sfapi-dev.payoff.com/ms/api/admin/member_match_resolver');
            insert testSettings;
            Lead testLead = new Lead(LastName = 'TestLastName',
                                    FirstName = 'TestFirstName',
                                    Company = 'TestCompany',
                                    lead_guid__c= 'a257adc0-70e7-1b50-4300-ecf90e617d09');
            insert testLead;
            

        Test.setMock(HttpCalloutMock.class, new MW_MemberMatchingDeactivation_HttpMock());
        Test.startTest();
        	MW_MemberMatchingDeactivation.makeCallout('234242');
        Test.stopTest();
            
        }
}