force-app/main/default/objects/Pricing_Offer__c/Pricing_Offer__c.object-meta.xml
<CustomObject>
    <label>Pricing Offer</label>
    <nameField>
        <label>Pricing Offer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pricing Offer</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Pricing_Offer__c/fields/Above_prime_max__c.field-meta.xml
<CustomField>
    <fullName>Above_prime_max__c</fullName>
    <label>Above prime max</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Pricing_Offer__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Pricing_Offer__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <description>/Changed on 16-10-2017 by Sagar Hinsu</description>
    <label>Application</label>
    <referenceTo>genesis__Applications__c</referenceTo>
    <relationshipLabel>Pricing Offer</relationshipLabel>
    <relationshipName>Pricing_Offer</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Pricing_Offer__c/fields/APR__c.field-meta.xml
<CustomField>
    <fullName>APR__c</fullName>
    <label>APR</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/objects/Pricing_Offer__c/fields/DM_External_Id__c.field-meta.xml
<CustomField>
    <fullName>DM_External_Id__c</fullName>
    <externalId>true</externalId>
    <label>DM External Id</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Pricing_Offer__c/fields/Interest_Rate__c.field-meta.xml
<CustomField>
    <fullName>Interest_Rate__c</fullName>
    <label>Interest Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Pricing_Offer__c/fields/IntRate_Words__c.field-meta.xml
<CustomField>
    <fullName>IntRate_Words__c</fullName>
    <description>Converts Interest Rate value to words</description>
    <formula>CASE(floor(10 * Interest_Rate__c), 0, CASE(FLOOR(100*Interest_Rate__c )-(10*FLOOR(10*Interest_Rate__c )), 0, &quot;Zero&quot;, 1,&quot;One&quot;,2, &quot;Two&quot;,3,&quot;Three&quot;, 4,&quot;Four&quot;,5,&quot;Five&quot;,6,&quot;Six&quot;,7,&quot;Seven&quot;,8,&quot;Eight&quot;,9,&quot;Nine&quot;,null),

1, (CASE(FLOOR(100 * Interest_Rate__c) - (10 * FLOOR(10 * Interest_Rate__c )), 0,&quot;Ten&quot;,1,&quot;Eleven&quot;,2, &quot;Twelve&quot;,3,&quot;Thirteen&quot;, 4,&quot;Fourteen&quot;,5,&quot;Fifteen&quot;,6,&quot;Sixteen&quot;,7,&quot;Seventeen&quot;,8,&quot;Eighteen&quot;,9,&quot;Nineteen&quot;,null)),

(CASE(FLOOR(10*Interest_Rate__c), 2,&quot;Twenty-&quot;,3, &quot;Thirty-&quot;,4,&quot;Forty-&quot;,5,&quot;Fifty-&quot;,6,&quot;Sixty-&quot;,7,&quot;Seventy-&quot;,8,&quot;Eighty-&quot;,9,&quot;Ninety-&quot;,null) +
CASE(FLOOR(100*Interest_Rate__c )-(10*FLOOR(10*Interest_Rate__c )), 0, &quot;Zero&quot;, 1,&quot;One&quot;,2, &quot;Two&quot;,3,&quot;Three&quot;, 4,&quot;Four&quot;,5,&quot;Five&quot;,6,&quot;Six&quot;,7,&quot;Seven&quot;,8,&quot;Eight&quot;,9,&quot;Nine&quot;,null))
)

+ &quot; Point &quot; +

CASE(FLOOR(1000*Interest_Rate__c)-(10*FLOOR(100*Interest_Rate__c)), 0, &quot;Zero&quot;, 1,&quot;One&quot;,2, &quot;Two&quot;,3,&quot;Three&quot;, 4,&quot;Four&quot;,5,&quot;Five&quot;,6,&quot;Six&quot;,7,&quot;Seven&quot;,8,&quot;Eight&quot;,9,&quot;Nine&quot;,null)

+ &quot; &quot; +

CASE(FLOOR(10000*Interest_Rate__c)-(10*FLOOR(1000*Interest_Rate__c)), 0, &quot;Zero&quot;, 1,&quot;One&quot;,2, &quot;Two&quot;,3,&quot;Three&quot;, 4,&quot;Four&quot;,5,&quot;Five&quot;,6,&quot;Six&quot;,7,&quot;Seven&quot;,8,&quot;Eight&quot;,9,&quot;Nine&quot;,null)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>IntRate_Words</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pricing_Offer__c/fields/InvestorCodeOnApp__c.field-meta.xml
<CustomField>
    <fullName>InvestorCodeOnApp__c</fullName>
    <label>InvestorCodeOnApp</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pricing_Offer__c/fields/Is_Offer_Selected__c.field-meta.xml
<CustomField>
    <fullName>Is_Offer_Selected__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Offer Selected</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Pricing_Offer__c/fields/Key__c.field-meta.xml
<CustomField>
    <fullName>Key__c</fullName>
    <label>Key</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Pricing_Offer__c/fields/Loan_Premium_Amount__c.field-meta.xml
<CustomField>
    <fullName>Loan_Premium_Amount__c</fullName>
    <formula>Amount__c *  LoanPremiumPrice__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Loan Premium Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Pricing_Offer__c/fields/Loan_Premium_Price__c.field-meta.xml
<CustomField>
    <fullName>Loan_Premium_Price__c</fullName>
    <formula>IF( Is_Offer_Selected__c == true,  IF(  OR(Application__r.Investor__r.Investor_Code__c ==&apos;FTCU&apos;,Application__r.Investor__r.Investor_Code__c ==&apos;TCU&apos;) ,
 IF( Term__c ==24, IF( Pricing_Tier__c == &apos;t1&apos;, 0.025, IF(Pricing_Tier__c == &apos;t2&apos;, 0.027, IF(Pricing_Tier__c == &apos;t3&apos;, 0.032, IF(Pricing_Tier__c == &apos;t4&apos;, 0.034, IF(Pricing_Tier__c == &apos;t5&apos;, 0.043, 0) ) ) ) ) , 
IF( Term__c == 36, IF(Pricing_Tier__c == &apos;t1&apos;, 0.035, IF(Pricing_Tier__c == &apos;t2&apos;, 0.037, IF(Pricing_Tier__c == &apos;t3&apos;,0.045, IF(Pricing_Tier__c == &apos;t4&apos;, 0.047, IF(Pricing_Tier__c == &apos;t5&apos;, 0.055, 0) ) ) ) ) , 
IF( Term__c == 48, IF(Pricing_Tier__c == &apos;t1&apos;, 0.045, IF(Pricing_Tier__c == &apos;t2&apos;, 0.048, IF(Pricing_Tier__c == &apos;t3&apos;, 0.050, IF(Pricing_Tier__c == &apos;t4&apos;, 0.052, IF(Pricing_Tier__c == &apos;t5&apos;, 0.058, 0) ) ) ) ) , 
IF( Term__c == 60, IF(Pricing_Tier__c == &apos;t1&apos;, 0.050, IF(Pricing_Tier__c == &apos;t2&apos;, 0.053, IF(Pricing_Tier__c == &apos;t3&apos;, 0.055, IF(Pricing_Tier__c == &apos;t4&apos;, 0.055, IF(Pricing_Tier__c == &apos;t5&apos;, 0.060, 0) ) ) ) ) , 0) ) ) )
 ,  IF(Application__r.Investor__r.Investor_Code__c ==&apos;ACU&apos;, 
IF( Term__c ==24,  IF( Pricing_Tier__c == &apos;t1&apos;,0.022,  IF(Pricing_Tier__c == &apos;t2&apos;, 0.023,  IF(Pricing_Tier__c == &apos;t3&apos;, 0.028,  IF(Pricing_Tier__c == &apos;t4&apos;, 0.029,  IF(Pricing_Tier__c == &apos;t5&apos;, 0.037, 0) ) ) ) ) ,
  IF(Term__c ==36,  IF(Pricing_Tier__c == &apos;t1&apos;, 0.03,  IF(Pricing_Tier__c == &apos;t2&apos;, 0.032,  IF(Pricing_Tier__c == &apos;t3&apos;, 0.039,  IF(Pricing_Tier__c == &apos;t4&apos;, 0.04,  IF(Pricing_Tier__c == &apos;t5&apos;, 0.047, 0) ) ) ) ) , 
 IF(Term__c ==48,  IF(Pricing_Tier__c == &apos;t1&apos;, 0.039, IF(Pricing_Tier__c == &apos;t2&apos;, 0.041,  IF(Pricing_Tier__c == &apos;t3&apos;, 0.043,  IF(Pricing_Tier__c == &apos;t4&apos;, 0.045,  IF(Pricing_Tier__c == &apos;t5&apos;, 0.05, 0) ) ) )  ) , 
 IF(Term__c ==60,  IF(Pricing_Tier__c == &apos;t1&apos;, 0.043,  IF(Pricing_Tier__c == &apos;t2&apos;, 0.046,  IF(Pricing_Tier__c == &apos;t3&apos;, 0.047,  IF(Pricing_Tier__c == &apos;t4&apos;, 0.047,  IF(Pricing_Tier__c == &apos;t5&apos;, 0.052, 0) ) ) ) ) , 0) ) ) ) , 0) ),0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Loan Premium Price</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Pricing_Offer__c/fields/Loan_Premium_Price_ACU__c.field-meta.xml
<CustomField>
    <fullName>Loan_Premium_Price_ACU__c</fullName>
    <description>Updated the values in this formula. Related to LOP-252</description>
    <formula>IF( AND(Application__r.Investor__r.Investor_Code__c ==&apos;ACU&apos;,Application__r.Loan_Origination_Date__c &gt;=  DATE(2021,06,15)) ,
 IF(Term__c == 24,  IF(Pricing_Tier__c == &apos;t1&apos;, 0.0300,  IF(Pricing_Tier__c == &apos;t2&apos;, 0.0275,  IF(Pricing_Tier__c == &apos;t3&apos;, 0.0375,  IF(Pricing_Tier__c == &apos;t4&apos;, 0.0425,  IF(Pricing_Tier__c == &apos;t5&apos;, 0.0250, 0) ) ) ) ) ,
IF(Term__c == 36,  IF(Pricing_Tier__c == &apos;t1&apos;, 0.0400,  IF(Pricing_Tier__c == &apos;t2&apos;, 0.0375,  IF(Pricing_Tier__c == &apos;t3&apos;, 0.0400,  IF(Pricing_Tier__c == &apos;t4&apos;, 0.0450,  IF(Pricing_Tier__c == &apos;t5&apos;, 0.0250, 0) ) ) ) ) ,
IF(Term__c == 48,  IF(Pricing_Tier__c == &apos;t1&apos;, 0.0500,  IF(Pricing_Tier__c == &apos;t2&apos;, 0.0475,  IF(Pricing_Tier__c == &apos;t3&apos;, 0.0425,  IF(Pricing_Tier__c == &apos;t4&apos;, 0.0475,  IF(Pricing_Tier__c == &apos;t5&apos;, 0.0250, 0) ) ) ) ) ,
IF(Term__c == 60,  IF(Pricing_Tier__c == &apos;t1&apos;, 0.0600,  IF(Pricing_Tier__c == &apos;t2&apos;, 0.0575,  IF(Pricing_Tier__c == &apos;t3&apos;, 0.0450,  IF(Pricing_Tier__c == &apos;t4&apos;, 0.0500,  IF(Pricing_Tier__c == &apos;t5&apos;, 0.0250, 0) ) ) ) ) , 0) ) ) ) , 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Loan_Premium_Price_ACU</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Pricing_Offer__c/fields/Loan_Premium_Price_FTCU_TCU__c.field-meta.xml
<CustomField>
    <fullName>Loan_Premium_Price_FTCU_TCU__c</fullName>
    <formula>IF( OR(Application__r.Investor__r.Investor_Code__c ==&apos;FTCU&apos;,Application__r.Investor__r.Investor_Code__c ==&apos;TCU&apos;) ,
IF( Term__c ==24, IF( Pricing_Tier__c == &apos;t1&apos;, 0.025, IF(Pricing_Tier__c == &apos;t2&apos;, 0.027, IF(Pricing_Tier__c == &apos;t3&apos;, 0.032, IF(Pricing_Tier__c == &apos;t4&apos;, 0.034, IF(Pricing_Tier__c == &apos;t5&apos;, 0.043, 0) ) ) ) ) , 
IF( Term__c == 36, IF(Pricing_Tier__c == &apos;t1&apos;, 0.035, IF(Pricing_Tier__c == &apos;t2&apos;, 0.037, IF(Pricing_Tier__c == &apos;t3&apos;,0.045, IF(Pricing_Tier__c == &apos;t4&apos;, 0.047, IF(Pricing_Tier__c == &apos;t5&apos;, 0.055, 0) ) ) ) ) , 
IF( Term__c == 48, IF(Pricing_Tier__c == &apos;t1&apos;, 0.045, IF(Pricing_Tier__c == &apos;t2&apos;, 0.048, IF(Pricing_Tier__c == &apos;t3&apos;, 0.050, IF(Pricing_Tier__c == &apos;t4&apos;, 0.052, IF(Pricing_Tier__c == &apos;t5&apos;, 0.058, 0) ) ) ) ) , 
IF( Term__c == 60, IF(Pricing_Tier__c == &apos;t1&apos;, 0.050, IF(Pricing_Tier__c == &apos;t2&apos;, 0.053, IF(Pricing_Tier__c == &apos;t3&apos;, 0.055, IF(Pricing_Tier__c == &apos;t4&apos;, 0.055, IF(Pricing_Tier__c == &apos;t5&apos;, 0.060, 0) ) ) ) ) , 0) ) ) )
 , 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Loan_Premium_Price_FTCU_TCU</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Pricing_Offer__c/fields/Loan_Premium_Price_TFCU__c.field-meta.xml
<CustomField>
    <fullName>Loan_Premium_Price_TFCU__c</fullName>
    <formula>IF(Application__r.Investor__r.Investor_Code__c ==&apos;TFCU&apos; ,
IF(Term__c == 24, IF(Pricing_Tier__c == &apos;t1&apos;, 0.0250, IF(Pricing_Tier__c == &apos;t2&apos;, 0.0270, IF(Pricing_Tier__c == &apos;t3&apos;, 0.0320, IF(Pricing_Tier__c == &apos;t4&apos;, 0.0340, IF(Pricing_Tier__c == &apos;t5&apos;, 0.0430, 0) ) ) ) ) ,
IF(Term__c == 36, IF(Pricing_Tier__c == &apos;t1&apos;, 0.0350, IF(Pricing_Tier__c == &apos;t2&apos;, 0.0370, IF(Pricing_Tier__c == &apos;t3&apos;, 0.0450, IF(Pricing_Tier__c == &apos;t4&apos;, 0.0470, IF(Pricing_Tier__c == &apos;t5&apos;, 0.0550, 0) ) ) ) ) ,
IF(Term__c == 48, IF(Pricing_Tier__c == &apos;t1&apos;, 0.0450, IF(Pricing_Tier__c == &apos;t2&apos;, 0.0480, IF(Pricing_Tier__c == &apos;t3&apos;, 0.0500, IF(Pricing_Tier__c == &apos;t4&apos;, 0.0520, IF(Pricing_Tier__c == &apos;t5&apos;, 0.0580, 0) ) ) ) ) ,
IF(Term__c == 60, IF(Pricing_Tier__c == &apos;t1&apos;, 0.0500, IF(Pricing_Tier__c == &apos;t2&apos;, 0.0530, IF(Pricing_Tier__c == &apos;t3&apos;, 0.0550, IF(Pricing_Tier__c == &apos;t4&apos;, 0.0550, IF(Pricing_Tier__c == &apos;t5&apos;, 0.0600, 0) ) ) ) ) , 0) ) ) ) , 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Loan_Premium_Price_TFCU</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Pricing_Offer__c/fields/LoanPremiumPrice__c.field-meta.xml
<CustomField>
    <fullName>LoanPremiumPrice__c</fullName>
    <defaultValue>0</defaultValue>
    <label>LoanPremiumPrice</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Pricing_Offer__c/fields/Monthly_Payment__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Payment__c</fullName>
    <label>Monthly Payment</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Pricing_Offer__c/fields/Origination_fee__c.field-meta.xml
<CustomField>
    <fullName>Origination_fee__c</fullName>
    <label>Origination fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Pricing_Offer__c/fields/Origination_fee_rate__c.field-meta.xml
<CustomField>
    <fullName>Origination_fee_rate__c</fullName>
    <label>Origination fee rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Pricing_Offer__c/fields/OriginationDateOnApp__c.field-meta.xml
<CustomField>
    <fullName>OriginationDateOnApp__c</fullName>
    <label>OriginationDateOnApp</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Pricing_Offer__c/fields/Pricing_Tier__c.field-meta.xml
<CustomField>
    <fullName>Pricing_Tier__c</fullName>
    <label>Pricing Tier</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Pricing_Offer__c/fields/Segment__c.field-meta.xml
<CustomField>
    <fullName>Segment__c</fullName>
    <label>Segment</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pricing_Offer__c/fields/Term__c.field-meta.xml
<CustomField>
    <fullName>Term__c</fullName>
    <label>Term</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Pricing_Offer__c/fields/Total_of_Payments_TIL__c.field-meta.xml
<CustomField>
    <fullName>Total_of_Payments_TIL__c</fullName>
    <description>Monthly_Payment__c * Term__c</description>
    <formula>Monthly_Payment__c * Term__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total of Payments TIL</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Pricing_Offer__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/MW_RetrievePricingOfferByApplicationId.cls
@RestResource(urlMapping='/pricing-offer/application-id/*')

global with sharing class MW_RetrievePricingOfferByApplicationId {
    @HttpGet
    global static void MW_RetrievePricingOfferByApplicationId() {
        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;
        try {
            
            String applicationId = req.params.get('application-id');
            if (String.isBlank(applicationId)) {
                res.statusCode = 400;
                res.responseBody = Blob.valueOf('application id is required');
                return;
            }
            List<Pricing_Offer__c> pricingOffers = [
                SELECT
                Id,
                Name,
                CreatedDate,
                CreatedById,
                LastModifiedDate,
                LastModifiedById,
                Application__c,
                APR__c,
                Above_prime_max__c,
                Active__c,
                Amount__c,
                Interest_Rate__c,
                IntRate_Words__c,
                Is_Offer_Selected__c,
                Key__c,
                Loan_Premium_Amount__c,
                Loan_Premium_Price__c,
                Monthly_Payment__c,
                Origination_fee__c,
                Origination_fee_rate__c,
                Pricing_Tier__c,
                Segment__c,
                Term__c,
                Type__c,
                InvestorCodeOnApp__c,
                LoanPremiumPrice__c,
                Loan_Premium_Price_ACU__c,
                Loan_Premium_Price_FTCU_TCU__c,
                OriginationDateOnApp__c,
                Total_of_Payments_TIL__c,
                Loan_Premium_Price_TFCU__c,
                DM_External_Id__c,
                Loan_Premium_Price_GSCU__c,
                Loan_Premium_Price_USAFCU__c,
                DataArchiva_Old_Id__c,
                DataArchiva_Read_Only_Data__c,
                EBP_Offer_Code__c,
                Loan_Premium_Price_BFCU__c,
                Loan_Premium_Price_CRB_Theorem_Main__c,
                Loan_Premium_Price_CRB_Theorem_Prime__c,
                Loan_Premium_Price_GSCU_PART__c,
                Loan_Premium_Price_ITB_CRB_Theorem_Main__c,
                Loan_Premium_Price_ITB_CRB_Theorem_Prime__c,
                Loan_Premium_Price_OTB_CRB_Theorem_Main__c,
                Loan_Premium_Price_OTB_CRB_Theorem_Prime__c,
                Loan_Premium_Price_VCU__c
                FROM Pricing_Offer__c 
                WHERE Application__c = :applicationId
            ];
            res.statusCode = 200;
            res.responseBody = Blob.valueOf(JSON.serialize(pricingOffers));
        }
        catch (Exception e) {
            res.statusCode = 500;
            res.responseBody = Blob.valueOf(e.getMessage());
        }
    }
}