force-app/main/default/objects/loan__Currency__c/loan__Currency__c.object-meta.xml
<CustomObject>
    <description>Currency</description>
    <label>Currency</label>
    <nameField>
        <label>Currency Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Currencies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/loan__Fee__c/loan__Fee__c.object-meta.xml
<CustomObject>
    <description>Fee</description>
    <label>Fee</label>
    <nameField>
        <label>Fee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/loan__Fee__c/fields/loan__Currency__c.field-meta.xml
<CustomField>
    <fullName>loan__Currency__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Currency</description>
    <inlineHelpText>Currency</inlineHelpText>
    <label>Currency</label>
    <referenceTo>loan__Currency__c</referenceTo>
    <relationshipLabel>Fees</relationshipLabel>
    <relationshipName>Fees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/loan__Fee_Junction__c/loan__Fee_Junction__c.object-meta.xml
<CustomObject>
    <label>Fee Set/Fee</label>
    <nameField>
        <displayFormat>FJIP-{0000000000}</displayFormat>
        <label>Fee Junction ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fee Set/Fee</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/loan__Fee_Junction__c/fields/loan__Fee__c.field-meta.xml
<CustomField>
    <fullName>loan__Fee__c</fullName>
    <label>Fee</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>loan__Fee__c.loan__Time_of_charge__c</field>
            <operation>notEqual</operation>
            <value>Pre-Paid Fees</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>loan__Fee__c</referenceTo>
    <relationshipLabel>Fee Set/Fee</relationshipLabel>
    <relationshipName>Fee_Junction</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/loan__Fee_Junction__c/fields/loan__Fee_Set__c.field-meta.xml
<CustomField>
    <fullName>loan__Fee_Set__c</fullName>
    <label>Fee Set</label>
    <referenceTo>loan__Fee_Set__c</referenceTo>
    <relationshipName>Fee_Junction</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/loan__Fee_Set__c/loan__Fee_Set__c.object-meta.xml
<CustomObject>
    <description>A set of fee</description>
    <label>Fee Set</label>
    <nameField>
        <label>Fee Set Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fee Set</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/loan__MF_Account__c/loan__MF_Account__c.object-meta.xml
<CustomObject>
    <label>GL Account</label>
    <nameField>
        <label>Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/loan__MF_Account__c/fields/loan__Branch__c.field-meta.xml
<CustomField>
    <fullName>loan__Branch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Branch</label>
    <referenceTo>loan__Office_Name__c</referenceTo>
    <relationshipName>MF_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/loan__Office_Name__c/loan__Office_Name__c.object-meta.xml
<CustomObject>
    <description>Name of the office</description>
    <label>Company</label>
    <nameField>
        <label>Company</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/loan__User_Branch_Info__c/loan__User_Branch_Info__c.object-meta.xml
<CustomObject>
    <label>User Branch Info</label>
    <nameField>
        <label>User Branch Info Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Branch Info</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/loan__User_Branch_Info__c/fields/loan__Branch__c.field-meta.xml
<CustomField>
    <fullName>loan__Branch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Branch</label>
    <referenceTo>loan__Office_Name__c</referenceTo>
    <relationshipLabel>User Branch Info</relationshipLabel>
    <relationshipName>User_Branch_Info</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/loan__User_Branch_Info__c/fields/loan__Default_Branch__c.field-meta.xml
<CustomField>
    <fullName>loan__Default_Branch__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Default Branch</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/loan__User_Branch_Info__c/fields/loan__User__c.field-meta.xml
<CustomField>
    <fullName>loan__User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>User_Branch_Info</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User/fields/loan__Current_Branch__c.field-meta.xml
<CustomField>
    <fullName>loan__Current_Branch__c</fullName>
    <label>Current Branch</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/loan__Default_Branch__c.field-meta.xml
<CustomField>
    <fullName>loan__Default_Branch__c</fullName>
    <label>Default Branch</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TestClearingJobCustomQueryDAG.cls
@isTest
private class TestClearingJobCustomQueryDAG{
    Testmethod static void method1(){
        loan.TestHelper.createSeedDataForTesting();
        //Create Currency...
        loan__Currency__c curr = loan.TestHelper.createCurrency();
        string job = 'LPTclearingjob';
        //Create a dummy MF_Account... 
        loan__MF_Account__c dummyAccount = loan.TestHelper.createMFAccount('AccountForTest','10000 - ASSETS');
        loan__MF_Account__c dummyIncAccount = loan.TestHelper.createMFAccount('IncAccountForTest','30000 - INCOME');
        
        //Create a Fee,Fee Set and link them...
        loan__Fee__c dummyFee = loan.TestHelper.createFee(curr,dummyIncAccount ,dummyAccount);                                    
        loan__Fee_Set__c dummyFeeSet = loan.TestHelper.createFeeSet();
        loan__Fee_Junction__c dummyFeeJunction = loan.TestHelper.createFeeJunction(dummyFee,dummyFeeSet);
        
        //Create Company...
        loan__Office_Name__c dummyCompany = loan.TestHelper.createOffice();
        
        User loggedUser = [select Id, Name,username, 
                           CompanyName,
                           loan__Current_Branch__c
                           from User where Id = :UserInfo.getUserId()];
        
        //User Compnay Assignment...
        loan__User_Branch_Info__c userCompany = new loan__User_Branch_Info__c();
        
        userCompany.loan__Branch__c = dummyCompany.id;
        userCompany.loan__Default_Branch__c = True;
        userCompany.loan__User__c = loggedUser.id;
        insert userCompany;
        LoanPaymentTxnClearingJobCustomQueryDAG.getCustomQuery(job);
    }
}