force-app/main/default/objects/MW_Callout__c/MW_Callout__c.object-meta.xml
<CustomObject>
    <label>MW_Callout</label>
    <nameField>
        <label>MW_Callout Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MW_Callout</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MW_Callout__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>genesis__Applications__c</referenceTo>
    <relationshipLabel>MW_Callout</relationshipLabel>
    <relationshipName>MW_Callout</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MW_Callout__c/fields/JobID__c.field-meta.xml
<CustomField>
    <fullName>JobID__c</fullName>
    <label>JobID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/MW_Callout__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/MW_NeoVerifyTransactionsCalloutQueue.cls
public class MW_NeoVerifyTransactionsCalloutQueue implements Queueable, Database.AllowsCallouts {
	private Set<Id> applicationIds {get; set;}

	public MW_NeoVerifyTransactionsCalloutQueue(Set<Id> applicationIds){
		this.applicationIds = applicationIds;
	}

	public void execute(QueueableContext context) {
		MW_NeoVerifyIntegration.postRegNeoVerify(applicationIds);
		ID JobID = context.getJobId();
		List<MW_Callout__c> newCalloutJob = new list<MW_Callout__c>([Select id from MW_Callout__c where JobID__c=: JobID LIMIT 1]);
		if(newCalloutJob.size()>0) {
			newCalloutJob[0].Application__c= new list<Id>(applicationIds)[0];
			newCalloutJob[0].Status__c = 'processed';
			update newCalloutJob;
		}
	}
}