force-app/main/default/objects/CL_Document__c/CL_Document__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>CL_Generated Documents Names</description>
    <label>CL Document</label>
</CustomObject>

force-app/main/default/objects/CL_Document__c/fields/Doc1__c.field-meta.xml
<CustomField>
    <fullName>Doc1__c</fullName>
    <label>Doc1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CL_Document__c/fields/Doc2__c.field-meta.xml
<CustomField>
    <fullName>Doc2__c</fullName>
    <inlineHelpText>TIL Document</inlineHelpText>
    <label>Doc2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CL_Document__c/fields/Doc3__c.field-meta.xml
<CustomField>
    <fullName>Doc3__c</fullName>
    <label>Doc3</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CL_Document__c/fields/OrginaitionDocumentFolder__c.field-meta.xml
<CustomField>
    <fullName>OrginaitionDocumentFolder__c</fullName>
    <label>OrginaitionDocumentFolder</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CL_Document__c/fields/UploadedBOX__c.field-meta.xml
<CustomField>
    <fullName>UploadedBOX__c</fullName>
    <label>UploadedBOX</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/genesis__Application_Document_Category__c/genesis__Application_Document_Category__c.object-meta.xml
<CustomObject>
    <label>Application Document Category</label>
    <nameField>
        <label>Application Document Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application Document Category</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/genesis__Application_Document_Category__c/fields/Box_URl__c.field-meta.xml
<CustomField>
    <fullName>Box_URl__c</fullName>
    <label>Box URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/genesis__Application_Document_Category__c/fields/Doc_Code_FF__c.field-meta.xml
<CustomField>
    <fullName>Doc_Code_FF__c</fullName>
    <formula>IF( genesis__Parent_Application_Document_Category__r.Name == &apos;ESign Documents&apos;, 
IF( Name == &apos;3rd Party Membership&apos; , IF( Investor_Code__c == &apos;ACU&apos;, &apos;authoritative_ffa_app&apos;, IF(Investor_Code__c == &apos;TCU&apos;, &apos;authoritative_ffa_app&apos;, IF(Investor_Code__c == &apos;FTCU&apos;, &apos;authoritative_ffa_app&apos;, &apos;authoritative_ffa_app&apos;) ) ) , 
IF(Name == &apos;CU Membership&apos;, IF(Investor_Code__c == &apos;ACU&apos;, &apos;authoritative_alliant_agreement&apos;, IF(Investor_Code__c == &apos;TCU&apos;, &apos;authoritative_tcu_member_agreement&apos;, IF(Investor_Code__c == &apos;FTCU&apos;, &apos;ftcu_member_agreement&apos;, &apos;authoritative_member_agreement&apos;) ) ) , 
IF(Name == &apos;Payoff Promissory Note&apos;, IF(Investor_Code__c == &apos;ACU&apos;, &apos;authoritative_promissory_note &apos;, IF(Investor_Code__c == &apos;TCU&apos;, &apos;authoritative_promissory_note&apos;, IF(Investor_Code__c == &apos;FTCU&apos;, &apos;promissory_note&apos;, &apos;authoritative_promissory_note&apos;) ) ) , 
IF(Name == &apos;Payoff Member Agreement&apos;, IF(Investor_Code__c == &apos;ACU&apos;, &apos;authoritative_borrower_agreement &apos;, IF(Investor_Code__c == &apos;TCU&apos;, &apos;authoritative_borrower_agreement&apos;, IF(Investor_Code__c == &apos;FTCU&apos;, &apos;borrower_agreement&apos;, &apos;authoritative_borrower_agreement&apos;) ) ) , 
IF(Name == &apos;Credit Services Contract&apos;, IF(Investor_Code__c == &apos;ACU&apos;, &apos;authoritative_cso_agreement &apos;, IF(Investor_Code__c == &apos;TCU&apos;, &apos;authoritative_cso_agreement&apos;, IF(Investor_Code__c == &apos;FTCU&apos;, &apos;cso_agreement&apos;, &apos;authoritative_cso_agreement&apos;) ) ) ,
IF(Name == &apos;Alliant ACH&apos;,  IF(Investor_Code__c == &apos;ACU&apos;, &apos;authoritative_alliant_ach&apos;,  IF(Investor_Code__c == &apos;TCU&apos;, &apos;&apos;,  IF(Investor_Code__c == &apos;FTCU&apos;, &apos;&apos;, Doc_Code_as_for_Investors__c ) ) ) , Doc_Code_as_for_Investors__c ) ) ) ) ) ) , 
Doc_Code_as_for_Investors__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Doc_Code_FF</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/genesis__Application_Document_Category__c/fields/genesis__Application__c.field-meta.xml
<CustomField>
    <fullName>genesis__Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>genesis__Applications__c</referenceTo>
    <relationshipLabel>Application Document Category</relationshipLabel>
    <relationshipName>Application_Document_Category</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/genesis__Application_Document_Category__c/fields/genesis__Status__c.field-meta.xml
<CustomField>
    <fullName>genesis__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>OPEN</fullName>
                <default>true</default>
                <label>OPEN</label>
            </value>
            <value>
                <fullName>SUBMITTED</fullName>
            </value>
            <value>
                <fullName>CLEARED</fullName>
            </value>
            <value>
                <fullName>REJECTED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/genesis__Application_Document_Category__c/fields/Lead_Id__c.field-meta.xml
<CustomField>
    <fullName>Lead_Id__c</fullName>
    <formula>genesis__Application__r.Lead_ID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Lead Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/genesis__Applications__c/genesis__Applications__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{0000000000}</displayFormat>
        <label>Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/genesis__Applications__c/fields/DocuSign_Sign_Date__c.field-meta.xml
<CustomField>
    <fullName>DocuSign_Sign_Date__c</fullName>
    <label>DocuSign Sign Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/genesis__Applications__c/fields/genesis__Status__c.field-meta.xml
<CustomField>
    <fullName>genesis__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>APPROVED - APPROVED</fullName>
            </value>
            <value>
                <fullName>APPROVED - CONVERTED TO CONTRACT</fullName>
            </value>
            <value>
                <fullName>APPROVED - DOCUMENT CHECK</fullName>
            </value>
            <value>
                <fullName>NEW - CREDIT PULLED</fullName>
            </value>
            <value>
                <fullName>NEW - ENTERED</fullName>
                <default>true</default>
                <label>NEW - ENTERED</label>
            </value>
            <value>
                <fullName>NEW - IN CREDIT CHECK</fullName>
            </value>
            <value>
                <fullName>NEW - IN REVIEW</fullName>
            </value>
            <value>
                <fullName>NEW - PRICING GENERATED</fullName>
            </value>
            <value>
                <fullName>NEW - SCORECARD GENERATED</fullName>
            </value>
            <value>
                <fullName>NEW - CHECKLIST GENERATED</fullName>
            </value>
            <value>
                <fullName>NEW - VEHICLE VALUATION REQUIRED</fullName>
            </value>
            <value>
                <fullName>REJECTED</fullName>
            </value>
            <value>
                <fullName>PULL CREDIT</fullName>
            </value>
            <value>
                <fullName>Default Documents</fullName>
            </value>
            <value>
                <fullName>offer_accepted</fullName>
            </value>
            <value>
                <fullName>offer_shown</fullName>
            </value>
            <value>
                <fullName>kba_success</fullName>
            </value>
            <value>
                <fullName>kba_fail</fullName>
            </value>
            <value>
                <fullName>agent_document_verification_pending</fullName>
            </value>
            <value>
                <fullName>agent_verification_pending</fullName>
            </value>
            <value>
                <fullName>agent_verified</fullName>
            </value>
            <value>
                <fullName>docusign_loan_docs_sent</fullName>
            </value>
            <value>
                <fullName>docusign_loan_docs_complete</fullName>
            </value>
            <value>
                <fullName>pre_funding</fullName>
            </value>
            <value>
                <fullName>Approved for funding</fullName>
            </value>
            <value>
                <fullName>funded</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Stacker_Check_Passed</fullName>
            </value>
            <value>
                <fullName>Redecision_Required</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/genesis__Applications__c/fields/Lead_ID__c.field-meta.xml
<CustomField>
    <fullName>Lead_ID__c</fullName>
    <description>This is the LEAD GUID received from FE</description>
    <externalId>true</externalId>
    <label>Lead ID</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/genesis__Applications__c/fields/LeadGUIDBoxFolderID__c.field-meta.xml
<CustomField>
    <fullName>LeadGUIDBoxFolderID__c</fullName>
    <description>This field will contain the folder id for the Lead guid box folder.</description>
    <label>LeadGUIDBoxFolderID</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/MWOriginationDocuments_AppDocs.cls
global with sharing class MWOriginationDocuments_AppDocs implements Database.Batchable<sObject>,Database.AllowsCallouts {

	public static CL_Document__c cs = CL_Document__c.getOrgDefaults();
	public static string credit = cs.Doc1__c;
	public string Til = cs.Doc2__c;
	public string Adverse = cs.Doc3__c;
	public string uploadbox = cs.UploadedBOX__c;
	public static String OrginaitionDocumentFolder =cs.OrginaitionDocumentFolder__C;
	public string applnType;

	//global Final String query = 'SELECT id, genesis__Application__c, genesis__Application__r.genesis__Status__c, Lead_Id__c, Doc_Code_FF__c, genesis__Application__r.id, genesis__Application__r.LeadGUIDBoxFolderID__c, Name, Box_URl__c FROM genesis__Application_Document_Category__c WHERE (genesis__Application__r.genesis__Status__c=\'pre_funding\' AND genesis__Application__r.DocuSign_Sign_Date__c=YESTERDAY AND Box_URl__c=\'\' AND'+
	//		'(Name=:credit OR Name=: Adverse OR Name=: Til)) OR (genesis__Application__r.LastModifiedDate<=YESTERDAY AND (genesis__Application__r.genesis__Status__c=\'Decline_Manual_Review\' OR genesis__Application__r.genesis__Status__c=\'Declined\') AND Box_URl__c=\'\' AND (Name=:credit OR Name=: Adverse OR Name=: Til))';


	global final String query;

	global MWOriginationDocuments_AppDocs(String appType)
	{
		applnType = appType;
		if(appType == 'PreFunding') {
			this.query = 'SELECT id, genesis__Application__c, genesis__Application__r.genesis__Status__c, Lead_Id__c, Doc_Code_FF__c, genesis__Application__r.id, genesis__Application__r.LeadGUIDBoxFolderID__c, Name, Box_URl__c FROM genesis__Application_Document_Category__c ' +
					'WHERE ' +
					'(genesis__Application__r.genesis__Status__c=\'pre_funding\' AND genesis__Application__r.DocuSign_Sign_Date__c=YESTERDAY AND Box_URl__c=\'\' AND '+
					'(Name=:credit OR Name=: Adverse OR Name=: Til))';
		} else if(appType =='Declined')
		{
			this.query = 'SELECT id, genesis__Application__c, genesis__Application__r.genesis__Status__c, Lead_Id__c, Doc_Code_FF__c, genesis__Application__r.id, genesis__Application__r.LeadGUIDBoxFolderID__c, Name, Box_URl__c FROM genesis__Application_Document_Category__c ' +
					'WHERE ' +
					'(genesis__Application__r.LastModifiedDate<=YESTERDAY AND (genesis__Application__r.genesis__Status__c=\'Decline_Manual_Review\' OR genesis__Application__r.genesis__Status__c=\'Declined\') ' +
					'AND Box_URl__c=\'\' AND (Name=:credit OR Name=: Adverse OR Name=: Til))';

		}

		System.debug('query=' + query);
	}

	global Database.QueryLocator start(Database.BatchableContext BC) {
		return Database.getQueryLocator(query);
	}

	global void execute(Database.BatchableContext BC, List<genesis__Application_Document_Category__c> scope) {

		Map<String, String> appMap          = new Map<String, String>();
		List<genesis__Application_Document_Category__c> dealRoomDocs  = new List<genesis__Application_Document_Category__c>();

		for(genesis__Application_Document_Category__c app:scope) {
			appMap.put(app.genesis__Application__r.id,app.genesis__Application__r.LeadGUIDBoxFolderID__c);
		}

		/*
		    GeneraratedDocsMap
		 */
		map<String,Attachment> generatedDocsMap = new map<String,Attachment>();
		for(Attachment atch:[SELECT Name,body,ParentId,Description from Attachment where (Description =: credit OR Description =: Til OR Description =: Adverse)
		AND ParentId IN:appMap.keyset() AND Description!=:uploadbox and BodyLength>0 Order By CreatedDate ASC]) {
			generatedDocsMap.put(atch.ParentId+'_'+atch.Description, atch);
		}

		for(genesis__Application_Document_Category__c AppDocCategory:scope)
		{
			if(generatedDocsMap.size()>0 && generatedDocsMap.get(AppDocCategory.genesis__Application__r.id+'_'+AppDocCategory.Name)!=null) {
				String boxUrl = null;
				boxUrl = MW_BoxUtil1.uploadFileToBox(generatedDocsMap.get(AppDocCategory.genesis__Application__r.id+'_'+AppDocCategory.Name).body,AppDocCategory.Doc_Code_FF__c +'_'+AppDocCategory.Lead_Id__c+'.pdf',appMap.get(AppDocCategory.genesis__Application__c),AppDocCategory.genesis__Application__c);
				if(boxUrl!=null) {
					AppDocCategory.Box_URl__c = boxUrl;
					dealRoomDocs.add(AppDocCategory);
				}
			}
		}

		MW_BoxUtil1.insertAccessToken();
		if(dealRoomDocs.size()>0) update dealRoomDocs;
	}


	global void finish(Database.BatchableContext BC) {
		System.debug('MWOriginationDocuments_AppDocs ' + applnType);
		System.debug('query=' + query);
	}

}