force-app/main/default/objects/Account/recordTypes/Member.recordType-meta.xml
<RecordType>
    <fullName>Member</fullName>
    <active>true</active>
    <label>Member</label>
</RecordType>

force-app/main/default/objects/genesis__Applications__c/genesis__Applications__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{0000000000}</displayFormat>
        <label>Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/genesis__Applications__c/fields/genesis__Account__c.field-meta.xml
<CustomField>
    <fullName>genesis__Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Applications_account</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Pricing_Offer__c/Pricing_Offer__c.object-meta.xml
<CustomObject>
    <label>Pricing Offer</label>
    <nameField>
        <label>Pricing Offer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pricing Offer</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Pricing_Offer__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <description>/Changed on 16-10-2017 by Sagar Hinsu</description>
    <label>Application</label>
    <referenceTo>genesis__Applications__c</referenceTo>
    <relationshipLabel>Pricing Offer</relationshipLabel>
    <relationshipName>Pricing_Offer</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/MW_PricingOfferTriggerTest.cls
@isTest
public class MW_PricingOfferTriggerTest {
    
    @testSetup static void Testsetup(){
        Account acc = MW_GlobalTestUtility.GetAccount('Member');
        insert acc;
        
        genesis__Applications__c app = MW_GlobalTestUtility.GetApplication();
        app.genesis__Account__c = acc.Id;
        insert app;
        
    }
        static testmethod void insertOffer(){
            genesis__Applications__c app1 = [select id, name from genesis__Applications__c];
            test.startTest();
            Pricing_Offer__c POffer = MW_GlobalTestUtility.getPricingOffer('t1');
            POffer.Application__c = app1.id;
            insert POffer;
            test.stopTest();
            
        }
        static testmethod void updateOffer(){
            genesis__Applications__c app1 = [select id, name from genesis__Applications__c];
            
            Pricing_Offer__c POffer2 = MW_GlobalTestUtility.getPricingOffer('t2');
            POffer2.Application__c = app1.id;
            insert POffer2;
            test.startTest();
            update POffer2;
            test.stopTest();
        }
        
    }