unpackaged/main/default/objects/Credit_Policy__c/Credit_Policy__c.object-meta.xml
<CustomObject>
    <label>Credit Policy</label>
    <nameField>
        <label>Credit Policy Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Credit Policy</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Credit_Policy__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>genesis__Applications__c</referenceTo>
    <relationshipLabel>Credit Policy</relationshipLabel>
    <relationshipName>Credit_Policy</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Credit_Policy__c/fields/Loan_amount_counteroffer__c.field-meta.xml
<CustomField>
    <fullName>Loan_amount_counteroffer__c</fullName>
    <label>Loan amount counteroffer</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Expiry_Date__c/Expiry_Date__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Expiry Date</label>
</CustomObject>

unpackaged/main/default/objects/genesis__Applications__c/genesis__Applications__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{0000000000}</displayFormat>
        <label>Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/genesis__Applications__c/fields/DocuSign_EnvelopeId__c.field-meta.xml
<CustomField>
    <fullName>DocuSign_EnvelopeId__c</fullName>
    <label>DocuSign EnvelopeId</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/genesis__Applications__c/fields/Expiration_Tag__c.field-meta.xml
<CustomField>
    <fullName>Expiration_Tag__c</fullName>
    <label>Expiration Tag</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>expired_pre_qual</fullName>
            </value>
            <value>
                <fullName>expired_verification</fullName>
            </value>
            <value>
                <fullName>expired_docs</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/genesis__Applications__c/fields/Expiry_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiry_Date__c</fullName>
    <description>/*Created By Nupur */
------- For Email Alert</description>
    <formula>Application_Start_DateV2__c + $Setup.Expiry_Date__c.No_of_days_for_Expiration__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Expiry Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/genesis__Applications__c/fields/genesis__Status__c.field-meta.xml
<CustomField>
    <fullName>genesis__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>APPROVED - APPROVED</fullName>
            </value>
            <value>
                <fullName>APPROVED - CONVERTED TO CONTRACT</fullName>
            </value>
            <value>
                <fullName>APPROVED - DOCUMENT CHECK</fullName>
            </value>
            <value>
                <fullName>NEW - CREDIT PULLED</fullName>
            </value>
            <value>
                <fullName>NEW - ENTERED</fullName>
                <default>true</default>
                <label>NEW - ENTERED</label>
            </value>
            <value>
                <fullName>NEW - IN CREDIT CHECK</fullName>
            </value>
            <value>
                <fullName>NEW - IN REVIEW</fullName>
            </value>
            <value>
                <fullName>NEW - PRICING GENERATED</fullName>
            </value>
            <value>
                <fullName>NEW - SCORECARD GENERATED</fullName>
            </value>
            <value>
                <fullName>NEW - CHECKLIST GENERATED</fullName>
            </value>
            <value>
                <fullName>NEW - VEHICLE VALUATION REQUIRED</fullName>
            </value>
            <value>
                <fullName>REJECTED</fullName>
            </value>
            <value>
                <fullName>PULL CREDIT</fullName>
            </value>
            <value>
                <fullName>Default Documents</fullName>
            </value>
            <value>
                <fullName>offer_accepted</fullName>
            </value>
            <value>
                <fullName>offer_shown</fullName>
            </value>
            <value>
                <fullName>kba_success</fullName>
            </value>
            <value>
                <fullName>kba_fail</fullName>
            </value>
            <value>
                <fullName>agent_document_verification_pending</fullName>
            </value>
            <value>
                <fullName>agent_verification_pending</fullName>
            </value>
            <value>
                <fullName>agent_verified</fullName>
            </value>
            <value>
                <fullName>docusign_loan_docs_sent</fullName>
            </value>
            <value>
                <fullName>docusign_loan_docs_complete</fullName>
            </value>
            <value>
                <fullName>pre_funding</fullName>
            </value>
            <value>
                <fullName>Approved for funding</fullName>
            </value>
            <value>
                <fullName>funded</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Stacker_Check_Passed</fullName>
            </value>
            <value>
                <fullName>Redecision_Required</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/MW_Settings__c/MW_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>MW_Settings</label>
</CustomObject>

force-app/main/default/objects/MW_Settings__c/fields/Allocation_Engine_Batch_Size__c.field-meta.xml
<CustomField>
    <fullName>Allocation_Engine_Batch_Size__c</fullName>
    <label>Allocation Engine Batch Size</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/classes/ApplicationExpiryUpdateTEMP.cls
/*
This is to expire the applications for a specific expiry date.
How to execute batch(one time execute) :
Date dt = Date.valueOf('2019-04-20');
string qry = 'select id, Expiry_Date__c, genesis__Status__c,CreatedById, DocuSign_EnvelopeId__c, Expiration_Tag__c, (select id,name,Loan_amount_counteroffer__c from Credit_Policy__r where Loan_amount_counteroffer__c!=null limit 1) from genesis__Applications__c where Expiry_Date__c = 2019-04-20 and genesis__Status__c not in (\'funded\',\'Expired\',\'Approved for funding\',\'pre_funding\',\'Withdrawn\')';
Database.executeBatch(new ApplicationExpiryUpdateTEMP(qry,dt),1);

---schedule the batch, if required -----
//System.schedule('ApplicationExpiryUpdateTEMP', '0 32 13 * * ?', new ApplicationExpiryUpdateTEMP(qry,dt));
*/

global class ApplicationExpiryUpdateTEMP implements Database.Batchable<SObject>, Schedulable, Database.AllowsCallouts {

    static global Set<Id> notifyIds = new Set<Id>();

    String query;
    List<String> skipLoanStatus = System.Label.Application_Expired_Status.split(',');
    String CSD;
    Date currentSystemDate;

    global ApplicationExpiryUpdateTEMP() {
        CSD = String.valueOf(new loan.GlobalLoanUtilFacade().getCurrentSystemDate());
        currentSystemDate = (new loan.GlobalLoanUtilFacade().getCurrentSystemDate());
    }

    global ApplicationExpiryUpdateTEMP(String query, Date currentSystemDate) {
        this.query = query;
        if (currentSystemDate != null) {
            CSD = String.valueOf(currentSystemDate);
            this.currentSystemDate = currentSystemDate;
        } else {
            this.currentSystemDate = (new loan.GlobalLoanUtilFacade().getCurrentSystemDate());
        }
    }
    
    global void execute(SchedulableContext sc) {        
        ApplicationExpiryUpdateTEMP b = new ApplicationExpiryUpdateTEMP(query,currentSystemDate);
        Database.executeBatch(b,1);
    }

    global Database.QueryLocator start(Database.BatchableContext bc) {

        notifyIds.clear();
        if(query == null){
            query = 'select id, Expiry_Date__c, genesis__Status__c,CreatedById, DocuSign_EnvelopeId__c, Expiration_Tag__c, (select id,name,Loan_amount_counteroffer__c from Credit_Policy__r where Loan_amount_counteroffer__c!=null limit 1 ) from genesis__Applications__c where Expiry_Date__c =' + CSD +' and genesis__Status__c not in : skipLoanStatus';
        }
        System.debug(LoggingLevel.INFO, 'ApplicationExpiryUpdateTEMP Query===>' + query);
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext bc, List<SObject> scope) {
        ApplicationExpiryUpdateHandler.execute(CSD, currentSystemDate, scope, notifyIds);
    }

    public void finish(Database.BatchableContext bc) {

        System.debug(LoggingLevel.INFO, 'ApplicationExpiryUpdateTEMP.finish:' + notifyIds);
        if (notifyIds != null && !notifyIds.isEmpty()) {
            try{
                Integer batchSize = Integer.valueOf(MW_Settings__c.getInstance().Allocation_Engine_Batch_Size__c);
                AllocationEngineCalloutBatch aEBatch = new AllocationEngineCalloutBatch(notifyIds, MW_AllocationEngineHandler.CANCELLED);
                Database.executeBatch(aEBatch, batchSize);
            }catch(Exception ex){
                MW_LogUtility.error('ApplicationExpiryUpdateTEMP','','','finish',ex);
            }
        }
    }
}