unpackaged/main/default/objects/Credit_Policy__c/Credit_Policy__c.object-meta.xml
<CustomObject>
    <label>Credit Policy</label>
    <nameField>
        <label>Credit Policy Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Credit Policy</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Credit_Policy__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>genesis__Applications__c</referenceTo>
    <relationshipLabel>Credit Policy</relationshipLabel>
    <relationshipName>Credit_Policy</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Credit_Policy__c/fields/Lead_ID__c.field-meta.xml
<CustomField>
    <fullName>Lead_ID__c</fullName>
    <formula>Application__r.Lead_ID__c</formula>
    <label>Lead ID</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Credit_Policy__c/fields/Loan_amount_counteroffer__c.field-meta.xml
<CustomField>
    <fullName>Loan_amount_counteroffer__c</fullName>
    <label>Loan amount counteroffer</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Expiry_Date__c/Expiry_Date__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Expiry Date</label>
</CustomObject>

unpackaged/main/default/objects/genesis__Applications__c/genesis__Applications__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{0000000000}</displayFormat>
        <label>Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/genesis__Applications__c/fields/DocuSign_EnvelopeId__c.field-meta.xml
<CustomField>
    <fullName>DocuSign_EnvelopeId__c</fullName>
    <label>DocuSign EnvelopeId</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/genesis__Applications__c/fields/Expiration_Tag__c.field-meta.xml
<CustomField>
    <fullName>Expiration_Tag__c</fullName>
    <label>Expiration Tag</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>expired_pre_qual</fullName>
            </value>
            <value>
                <fullName>expired_verification</fullName>
            </value>
            <value>
                <fullName>expired_docs</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/genesis__Applications__c/fields/Expiry_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiry_Date__c</fullName>
    <description>/*Created By Nupur */
------- For Email Alert</description>
    <formula>Application_Start_DateV2__c + $Setup.Expiry_Date__c.No_of_days_for_Expiration__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Expiry Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/genesis__Applications__c/fields/genesis__Status__c.field-meta.xml
<CustomField>
    <fullName>genesis__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>APPROVED - APPROVED</fullName>
            </value>
            <value>
                <fullName>APPROVED - CONVERTED TO CONTRACT</fullName>
            </value>
            <value>
                <fullName>APPROVED - DOCUMENT CHECK</fullName>
            </value>
            <value>
                <fullName>NEW - CREDIT PULLED</fullName>
            </value>
            <value>
                <fullName>NEW - ENTERED</fullName>
                <default>true</default>
                <label>NEW - ENTERED</label>
            </value>
            <value>
                <fullName>NEW - IN CREDIT CHECK</fullName>
            </value>
            <value>
                <fullName>NEW - IN REVIEW</fullName>
            </value>
            <value>
                <fullName>NEW - PRICING GENERATED</fullName>
            </value>
            <value>
                <fullName>NEW - SCORECARD GENERATED</fullName>
            </value>
            <value>
                <fullName>NEW - CHECKLIST GENERATED</fullName>
            </value>
            <value>
                <fullName>NEW - VEHICLE VALUATION REQUIRED</fullName>
            </value>
            <value>
                <fullName>REJECTED</fullName>
            </value>
            <value>
                <fullName>PULL CREDIT</fullName>
            </value>
            <value>
                <fullName>Default Documents</fullName>
            </value>
            <value>
                <fullName>offer_accepted</fullName>
            </value>
            <value>
                <fullName>offer_shown</fullName>
            </value>
            <value>
                <fullName>kba_success</fullName>
            </value>
            <value>
                <fullName>kba_fail</fullName>
            </value>
            <value>
                <fullName>agent_document_verification_pending</fullName>
            </value>
            <value>
                <fullName>agent_verification_pending</fullName>
            </value>
            <value>
                <fullName>agent_verified</fullName>
            </value>
            <value>
                <fullName>docusign_loan_docs_sent</fullName>
            </value>
            <value>
                <fullName>docusign_loan_docs_complete</fullName>
            </value>
            <value>
                <fullName>pre_funding</fullName>
            </value>
            <value>
                <fullName>Approved for funding</fullName>
            </value>
            <value>
                <fullName>funded</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Stacker_Check_Passed</fullName>
            </value>
            <value>
                <fullName>Redecision_Required</fullName>
            </value>
            <value>
                <fullName>Decline_Manual_Review</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/genesis__Applications__c/fields/Lead_ID__c.field-meta.xml
<CustomField>
    <fullName>Lead_ID__c</fullName>
    <description>This is the LEAD GUID received from FE</description>
    <externalId>true</externalId>
    <label>Lead ID</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/genesis__Applications__c/fields/LEAD_ID_ExtKey__c.field-meta.xml
<CustomField>
    <fullName>LEAD_ID_ExtKey__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>LEAD_ID_ExtKey</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/genesis__Applications__c/fields/Member_ID__c.field-meta.xml
<CustomField>
    <fullName>Member_ID__c</fullName>
    <formula>genesis__Account__r.Member_ID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Member ID</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/MWBatchPostExpiryApplicationTEMP.cls
/*
This is to send the expiry updates to FE for a specific expiry date.
How to execute batch(one time execute) :
Date dt = Date.valueOf('2019-04-20');
string qry = 'select id, Expiry_Date__c, genesis__Status__c,CreatedById, owner.Name, LEAD_ID_ExtKey__c, Member_ID__c, Lead_ID__c, DocuSign_EnvelopeId__c, Expiration_Tag__c, LastModifiedDate , (select id,name,Loan_amount_counteroffer__c from Credit_Policy__r where Loan_amount_counteroffer__c != null limit 1 ) from genesis__Applications__c where (Expiry_Date__c = 2019-04-20 and genesis__Status__c in (\'Expired\',\'Declined\',\'Decline_Manual_Review\')) or (LastModifiedDate= YESTERDAY and genesis__Status__c in (\'Declined\'))';
Database.executeBatch(new MWBatchPostExpiryApplicationTEMP(qry,dt),1);

---schedule the batch, if required -----
//System.schedule('MWBatchPostExpiryApplicationTEMP', '0 32 13 * * ?', new MWBatchPostExpiryApplicationTEMP(qry,dt));
*/

global class MWBatchPostExpiryApplicationTEMP implements Database.batchable<sObject>, Schedulable, Database.AllowsCallouts {

    String query;
    Set<String> applicationStatus = new Set<String>{'Expired','Declined','Decline_Manual_Review'};
    Set<String> applicationStatusDec = new Set<String>{'Declined'};

    String CSD;
    Date currentSystemDate;
    Datetime currentSystemDateTime;
    String previousDate;

    @TestVisible static SObjectField lastModifiedDateField = genesis__Applications__c.LastModifiedDate;
    @TestVisible static sync_application syncApp;
    global Database.QueryLocator start(Database.BatchableContext BC) {
        if(query == null){
            this.query = 'select id, Expiry_Date__c, genesis__Status__c,CreatedById, owner.Name, LEAD_ID_ExtKey__c, Member_ID__c, Lead_ID__c, DocuSign_EnvelopeId__c, Expiration_Tag__c, '+ lastModifiedDateField +', (select id,name,Loan_amount_counteroffer__c from Credit_Policy__r where Loan_amount_counteroffer__c!=null limit 1 ) from genesis__Applications__c where (Expiry_Date__c =' + CSD +' and genesis__Status__c in: applicationStatus) or ('+ lastModifiedDateField +'= ' + previousDate +' and genesis__Status__c in: applicationStatusDec)';
        }
        System.debug('query=====>'+query);
        return Database.getQueryLocator(query);
    }
    public MWBatchPostExpiryApplicationTEMP(){
        CSD = String.valueof(new loan.GlobalLoanUtilFacade().getCurrentSystemDate());
        currentSystemDate = new loan.GlobalLoanUtilFacade().getCurrentSystemDate();
        currentSystemDateTime = DateTime.newInstance(currentSystemDate.year(), currentSystemDate.month(), currentSystemDate.day());
        previousDate = currentSystemDateTime.addDays(-1).format('yyyy-MM-dd\'T\'hh:mm:ss\'Z\'');
    }
    public MWBatchPostExpiryApplicationTEMP(string query,Date currentSystemDate){
        this.query = query;
        if(currentSystemDate != null){
            CSD = String.valueof(currentSystemDate);
            this.currentSystemDate = currentSystemDate;
            this.currentSystemDateTime = DateTime.newInstance(currentSystemDate.year(), currentSystemDate.month(), currentSystemDate.day());
            this.previousDate = currentSystemDateTime.addDays(-1).format('yyyy-MM-dd\'T\'hh:mm:ss\'Z\'');
        }
    }
    global void execute(Database.BatchableContext BC, List<sObject> scope) {
        //for logging only
        String appIdList = '';
        String leadIdList = '';

        List<genesis__Applications__c > listOfApp = (List<genesis__Applications__c >)scope;

        list<ApplicationInformation> listAppInfo  = new list<ApplicationInformation>();

        for(genesis__Applications__c app : listOfApp) {
            appIdList = appIdList + String.valueOf(app.Id) + ' ';
            leadIdList = leadIdList + app.Lead_ID__c + ' ';
            applicationinformation appinfo             = new ApplicationInformation();

            appinfo.expiry_date                        = app.Expiry_Date__c;

            if(app.genesis__Status__c=='Expired') {
                appinfo.lead_guid                            = app.Lead_ID__c;
                appinfo.lead_id                              = app.LEAD_ID_ExtKey__c;
                appinfo.member_id                            = app.Member_ID__c;

                appinfo.is_expired                           = true;
                listAppInfo.add(appinfo);
            }

            if((app.genesis__Status__c=='Declined' || app.genesis__Status__c=='Decline_Manual_Review') && app.owner.Name=='Declined' && app.Expiry_Date__c == currentSystemDate) {
                appinfo.lead_guid                            = app.Lead_ID__c;
                appinfo.lead_id                              = app.LEAD_ID_ExtKey__c;
                appinfo.member_id                            = app.Member_ID__c;

                appinfo.is_expired                           = true;
                listAppInfo.add(appinfo);
            }
            else if(app.genesis__Status__c=='Declined' && app.owner.Name=='Declined') {
                appinfo.lead_guid = app.Lead_ID__c;
                appinfo.lead_id = app.LEAD_ID_ExtKey__c;
                appinfo.member_id = app.Member_ID__c;
                appinfo.is_expired = false;
                listAppInfo.add(appinfo);
            }
        }

        syncApp = new sync_application('sync_application', listAppInfo);
        String str = JSON.serialize(syncApp, true);
        MW_WebhookHandler.CallWebHookIntegration(str, appIdList, leadIdList);
    }

    global void finish(Database.BatchableContext BC) {

    }

    global void execute(SchedulableContext sc) {
        MWBatchPostExpiryApplicationTEMP b = new MWBatchPostExpiryApplicationTEMP(query,currentSystemDate);
        Database.executeBatch(b,1);
    }

    class ApplicationInformation
    {
        public string lead_guid;
        public string lead_id;
        public string member_id;
        public date expiration_date;
        public date expiry_date;
        public boolean is_expired;
    }

    class sync_application {
        String type;
        @TestVisible ApplicationInformation[] data;
        public sync_application(String type, ApplicationInformation[] appInfo){
            this.type = type;
            this.data = appInfo;
        }
    }

}