force-app/main/default/objects/DCp_Arcus_Transactions__c/DCp_Arcus_Transactions__c.object-meta.xml
<CustomObject>
    <label>DCP Arcus Transaction</label>
    <nameField>
        <displayFormat>DAT-{0}</displayFormat>
        <label>DCp Arcus Transactions Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DCP Arcus Transaction</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DCp_Arcus_Transactions__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>DCP Arcus Transaction</relationshipLabel>
    <relationshipName>DCP_Arcus_Transaction</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DCp_Arcus_Transactions__c/fields/Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Account_Number__c</fullName>
    <label>Account Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DCp_Arcus_Transactions__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <label>Application</label>
    <referenceTo>genesis__Applications__c</referenceTo>
    <relationshipLabel>DCP Arcus Transaction</relationshipLabel>
    <relationshipName>DCP_Arcus_Transaction</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DCp_Arcus_Transactions__c/fields/Arcus_Eligible__c.field-meta.xml
<CustomField>
    <fullName>Arcus_Eligible__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Arcus Eligible</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DCp_Arcus_Transactions__c/fields/Arcus_Failed_Message__c.field-meta.xml
<CustomField>
    <fullName>Arcus_Failed_Message__c</fullName>
    <label>Arcus Failed Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DCp_Arcus_Transactions__c/fields/Bank_Name__c.field-meta.xml
<CustomField>
    <fullName>Bank_Name__c</fullName>
    <label>Bank Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DCp_Arcus_Transactions__c/fields/Braintree_Verification_Failed__c.field-meta.xml
<CustomField>
    <fullName>Braintree_Verification_Failed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Braintree Verification Failed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DCp_Arcus_Transactions__c/fields/Card_Number__c.field-meta.xml
<CustomField>
    <fullName>Card_Number__c</fullName>
    <label>Card Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/DCp_Arcus_Transactions__c/fields/Date_Opened__c.field-meta.xml
<CustomField>
    <fullName>Date_Opened__c</fullName>
    <label>Date Opened</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/DCp_Arcus_Transactions__c/fields/FE_Id__c.field-meta.xml
<CustomField>
    <fullName>FE_Id__c</fullName>
    <description>Unique ID from FE to update Transactions</description>
    <externalId>true</externalId>
    <label>FE Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/DCp_Arcus_Transactions__c/fields/Member_Code__c.field-meta.xml
<CustomField>
    <fullName>Member_Code__c</fullName>
    <label>Member Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DCp_Arcus_Transactions__c/fields/Pay_at_Funding__c.field-meta.xml
<CustomField>
    <fullName>Pay_at_Funding__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Pay at Funding</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DCp_Arcus_Transactions__c/fields/Portfolio_Type__c.field-meta.xml
<CustomField>
    <fullName>Portfolio_Type__c</fullName>
    <label>Portfolio Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DCp_Arcus_Transactions__c/fields/Requested_Amount__c.field-meta.xml
<CustomField>
    <fullName>Requested_Amount__c</fullName>
    <label>Requested Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DCp_Arcus_Transactions__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DCp_Arcus_Transactions__c/fields/Transaction_Id__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Id__c</fullName>
    <label>Transaction Id</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/genesis__Applications__c/genesis__Applications__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{0000000000}</displayFormat>
        <label>Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/genesis__Applications__c/fields/genesis__Account__c.field-meta.xml
<CustomField>
    <fullName>genesis__Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Applications_account</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/MW_DCPTransactions.cls
public with sharing class MW_DCPTransactions {

    public class DCPClass {
        public String lead_id;
        public List<TransactionClass> dcp;
        public Datetime dcp_confirmation_date;
    }

    public class TransactionClass {
        //insert dcp values
        public String balance;
        public String bank_name;
        public String id;

        //update dcp values
        public String transaction_id;
        public String credit_card_number;
        public Double payoff_amount;
        public Boolean braintree_verification_failed;
        public String arcus_failed_message;
        
        public String member_code;
        public String portfolio_type;
        public String account_number;
        public Date date_opened;
        public Boolean arcus_eligible;
    }

    public static void storeDCPTransactions(List<genesis__Applications__c> apps, String transactionsString){
        DCPClass dcpObj = (DCPClass) JSON.deserialize(transactionsString, DCPClass.class);
        try {
            List<DCp_Arcus_Transactions__c> newTransactions = new List<DCp_Arcus_Transactions__c>();
            for(TransactionClass eachTran: dcpObj.dcp) {
                DCp_Arcus_Transactions__c transactionObj = new DCp_Arcus_Transactions__c();
                transactionObj.FE_Id__c = eachTran.id;
                transactionObj.Account__c = apps[0].genesis__Account__c;
                transactionObj.Application__c = apps[0].id;
                if(eachTran.credit_card_number !=null)
                transactionObj.Card_Number__c = eachTran.credit_card_number;
                if(eachTran.bank_name !=null)
                transactionObj.Bank_Name__c = eachTran.bank_name;
                if(eachTran.payoff_amount !=null)
                transactionObj.Requested_Amount__c = eachTran.payoff_amount;
                if(eachTran.transaction_id !=null)
                transactionObj.Transaction_Id__c = eachTran.transaction_id;
                if(eachTran.braintree_verification_failed != null){
                    transactionObj.Braintree_Verification_Failed__c = eachTran.braintree_verification_failed;
                }
                if(eachTran.arcus_failed_message !=null)
                transactionObj.Arcus_Failed_Message__c = eachTran.arcus_failed_message;
                if(eachTran.transaction_id != null) {
                    transactionObj.Status__c = 'On Hold';
                    transactionObj.Pay_at_Funding__c = true;
                }
                if(eachTran.member_code !=null){
                    transactionObj.Member_Code__c = eachTran.member_code;
                }
                if(eachTran.portfolio_type !=null){
                    transactionObj.Portfolio_Type__c = eachTran.portfolio_type;
                }
                if(eachTran.account_number !=null){
                    transactionObj.Account_Number__c = eachTran.account_number;
                }
                if(eachTran.date_opened !=null){
                    transactionObj.Date_Opened__c = eachTran.date_opened;
                }
                if(eachTran.arcus_eligible !=null){
                    transactionObj.Arcus_Eligible__c = eachTran.arcus_eligible;
                }
                newTransactions.add(transactionObj);
            }
            if(newTransactions.size() > 0) {
                //upsert using external id
                upsert newTransactions FE_Id__c;
            }
        }
        catch(Exception e){
            MW_LogUtility.error('MW_DCPTransactions', apps[0].id, '', 'storeDCPTransactions', e);
        }
    }
}