force-app/main/default/objects/genesis__Applications__c/genesis__Applications__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{0000000000}</displayFormat>
        <label>Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/genesis__Applications__c/fields/LEAD_ID_ExtKey__c.field-meta.xml
<CustomField>
    <fullName>LEAD_ID_ExtKey__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>LEAD_ID_ExtKey</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/genesis__Applications__c/fields/Member_ID__c.field-meta.xml
<CustomField>
    <fullName>Member_ID__c</fullName>
    <formula>genesis__Account__r.Member_ID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Member ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Identity_Verification__c/Identity_Verification__c.object-meta.xml
<CustomObject>
    <label>Identity Verification</label>
    <nameField>
        <displayFormat>IDN-{0000000}</displayFormat>
        <label>Identity Verification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Identity Verifications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Identity_Verification__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <label>Application</label>
    <referenceTo>genesis__Applications__c</referenceTo>
    <relationshipLabel>Identity Verifications</relationshipLabel>
    <relationshipName>Identity_Verifications</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Identity_Verification__c/fields/check_match__c.field-meta.xml
<CustomField>
    <fullName>check_match__c</fullName>
    <label>check_match</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Identity_Verification__c/fields/Identity_Verification__c.field-meta.xml
<CustomField>
    <fullName>Identity_Verification__c</fullName>
    <label>Identity Verification</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>PASS</fullName>
            </value>
            <value>
                <fullName>FAIL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Identity_Verification__c/fields/TLO_Link__c.field-meta.xml
<CustomField>
    <fullName>TLO_Link__c</fullName>
    <label>TLO Link</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Identity_Verification__c/fields/TLO_Link_formula__c.field-meta.xml
<CustomField>
    <fullName>TLO_Link_formula__c</fullName>
    <formula>&apos;https://&apos; +  $Setup.TLO_URL_Config__c.TLO_URL__c  +&apos;/&apos;+ $Setup.TLO_URL_Config__c.TLOURLappname__c + &apos;/tlo?lead_id=&apos; + Application__r.LEAD_ID_ExtKey__c +&apos;&amp;member_id=&apos;+ Application__r.Member_ID__c +&apos;&amp;user_id=&apos;+  $User.Id + check_match__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>TLO Link formula</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TLO_URL_Config__c/TLO_URL_Config__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>TLO URL Config</label>
</CustomObject>

force-app/main/default/objects/TLO_URL_Config__c/fields/TLO_URL__c.field-meta.xml
<CustomField>
    <fullName>TLO_URL__c</fullName>
    <label>TLO URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TLO_URL_Config__c/fields/TLOURLappname__c.field-meta.xml
<CustomField>
    <fullName>TLOURLappname__c</fullName>
    <label>TLOURLappname</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TLOLinkConfig.cls
/* ****************Modification History*****************************************************************
 * Modified by      Date        JIRA number
 *    Anusha       2020/07/07     CRM-543 (Schema changes)Display link to 3rd party data portal
 *    Anusha       2020/07/24     CRM-748 Update TLO URL when PII changed (rematch)
 *    Neha         2020/11/12     CRM-963 Enable Dynamic TLO URL to reflect current UserId.
 ******************Modification History*****************************************************************/
Public class TLOLinkConfig{

    public void updateLinkonApps(List<genesis__applications__c> app){
        
        System.debug(logginglevel.error, 'In TLOLink.cls');
        
        Id appID = app[0].Id;
        
        // commented part of CRM-963
        //TLO_Link__c field update not required on IDV record creation. Created TLO_Link_formula__c.
        /*String TLOurl = null; 
        TLO_URL_Config__c tlo = [select id,name,TLO_URL__c, TLOURLappname__c from TLO_URL_Config__c];*/
        List<Identity_Verification__c> IdentityRecord = [select id,name, TLO_Link__c                                                          
                                                        from Identity_Verification__c 
                                                        where Application__c =:appID 
                                                        order by createddate desc limit 1]; 
                                                        
        //new changes - start
        if(IdentityRecord == null || IdentityRecord.size() == 0){
            //CRM-963
            /*TLOurl ='https://' + tlo.TLO_URL__c +'/'+ tlo.TLOURLappname__c + '/tlo?lead_id=' + 
                                        app[0].LEAD_ID_ExtKey__c +'&member_id='+ 
                                        app[0].Member_ID__c +'&user_id='+ UserInfo.getUserId() ;
            
            System.debug(logginglevel.error,'TLOurl created :'+TLOurl);*/
            
            Identity_Verification__c IDVnewRecord = new Identity_Verification__c();
            IDVnewRecord.Application__c = appID;
            //IDVnewRecord.TLO_Link__c = TLOurl; //CRM-963
            
            insert IDVnewRecord;                               
        //new changes - end
        
        /*}else if (IdentityRecord != null && IdentityRecord.size() != 0 && IdentityRecord[0].TLO_Link__c == null){
        
            TLOurl= 'https://' + tlo.TLO_URL__c +'/'+ tlo.TLOURLappname__c + '/tlo?lead_id=' + app[0].LEAD_ID_ExtKey__c +'&member_id='+ app[0].Member_ID__c +'&user_id='+ UserInfo.getUserId() ;
    
            System.debug(logginglevel.error,'TLOurl :'+TLOurl);
            
            IdentityRecord[0].TLO_Link__c = TLOurl;
            
            update IdentityRecord;*/ //CRM-963
        
        }
    
    }
  //CRM-748 start
    public void updateTLOLink(List<Id> appIdList){
        
        System.debug('Inside updateTLOLink..'+ appIdList);
        List<Identity_Verification__c> updateTLOLinkOnIDV = new List<Identity_Verification__c>();
            List<Identity_Verification__c> identityRecord = [select id, name, check_match__c                                                          
                                                            from Identity_Verification__c 
                                                            where Application__c IN:appIdList];
            
            if(identityRecord != null && identityRecord.size() > 0){
                System.debug('identityRecord list is not null..');
                for(Identity_Verification__c idvRecord:identityRecord){
                
                    String tloLinkToUpdate = null;
                    if(idvRecord.check_match__c == null){
                       //CRM-963 
                       //System.debug('idvRecord.TLO_Link__c: '+idvRecord.TLO_Link__c);                       
                       // if((idvRecord.TLO_Link__c).indexOf('&check_match=true') == -1){
                            //tloLinkToUpdate = idvRecord.TLO_Link__c + '&check_match=true';
                            
                        tloLinkToUpdate = '&check_match=true';
                        idvRecord.check_match__c = tloLinkToUpdate;
                        updateTLOLinkOnIDV.add(idvRecord); 
                        //CRM-963
                        /*}else{
                            System.debug('TLO_Link__c is already updated with &check_match=true..');
                        }*/    
                    }else{
                        //System.debug('TLO Link does not exist for update'); // CRM-963
                        System.debug('TLO_Link__c is already updated with &check_match=true..');
                    }
                }
            }

        if(updateTLOLinkOnIDV.size()>0){
             System.debug('Number of identity verification records updated: '+updateTLOLinkOnIDV.size());
            update updateTLOLinkOnIDV;
        }
   }
  //CRM-748 end
}