force-app/main/default/objects/genesis__Applications__c/genesis__Applications__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{0000000000}</displayFormat>
        <label>Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/genesis__Applications__c/fields/genesis__Account__c.field-meta.xml
<CustomField>
    <fullName>genesis__Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Applications_account</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/genesis__Applications__c/fields/genesis__Status__c.field-meta.xml
<CustomField>
    <fullName>genesis__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>APPROVED - APPROVED</fullName>
            </value>
            <value>
                <fullName>APPROVED - CONVERTED TO CONTRACT</fullName>
            </value>
            <value>
                <fullName>APPROVED - DOCUMENT CHECK</fullName>
            </value>
            <value>
                <fullName>NEW - CREDIT PULLED</fullName>
            </value>
            <value>
                <fullName>NEW - ENTERED</fullName>
                <default>true</default>
                <label>NEW - ENTERED</label>
            </value>
            <value>
                <fullName>NEW - IN CREDIT CHECK</fullName>
            </value>
            <value>
                <fullName>NEW - IN REVIEW</fullName>
            </value>
            <value>
                <fullName>NEW - PRICING GENERATED</fullName>
            </value>
            <value>
                <fullName>NEW - SCORECARD GENERATED</fullName>
            </value>
            <value>
                <fullName>NEW - CHECKLIST GENERATED</fullName>
            </value>
            <value>
                <fullName>NEW - VEHICLE VALUATION REQUIRED</fullName>
            </value>
            <value>
                <fullName>REJECTED</fullName>
            </value>
            <value>
                <fullName>PULL CREDIT</fullName>
            </value>
            <value>
                <fullName>Default Documents</fullName>
            </value>
            <value>
                <fullName>offer_accepted</fullName>
            </value>
            <value>
                <fullName>offer_shown</fullName>
            </value>
            <value>
                <fullName>kba_success</fullName>
            </value>
            <value>
                <fullName>kba_fail</fullName>
            </value>
            <value>
                <fullName>agent_document_verification_pending</fullName>
            </value>
            <value>
                <fullName>agent_verification_pending</fullName>
            </value>
            <value>
                <fullName>agent_verified</fullName>
            </value>
            <value>
                <fullName>docusign_loan_docs_sent</fullName>
            </value>
            <value>
                <fullName>docusign_loan_docs_complete</fullName>
            </value>
            <value>
                <fullName>pre_funding</fullName>
            </value>
            <value>
                <fullName>Approved for funding</fullName>
            </value>
            <value>
                <fullName>funded</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Stacker_Check_Passed</fullName>
            </value>
            <value>
                <fullName>Redecision_Required</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/genesis__Applications__c/fields/Lead_ID__c.field-meta.xml
<CustomField>
    <fullName>Lead_ID__c</fullName>
    <description>This is the LEAD GUID received from FE</description>
    <externalId>true</externalId>
    <label>Lead ID</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/loan__Bank_Account__c/loan__Bank_Account__c.object-meta.xml
<CustomObject>
    <label>Bank Account</label>
    <nameField>
        <displayFormat>BA-{00000}</displayFormat>
        <label>Bank Account Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bank Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/loan__Bank_Account__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <inlineHelpText>Bank Account Holder First Name</inlineHelpText>
    <label>First Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/loan__Bank_Account__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <inlineHelpText>Bank Account Holder Last Name</inlineHelpText>
    <label>Last Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/loan__Bank_Account__c/fields/loan__Account__c.field-meta.xml
<CustomField>
    <fullName>loan__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bank Accounts</relationshipLabel>
    <relationshipName>Bank_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/loan__Bank_Account__c/fields/loan__Account_Type__c.field-meta.xml
<CustomField>
    <fullName>loan__Account_Type__c</fullName>
    <label>Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Savings</fullName>
            </value>
            <value>
                <fullName>Checking</fullName>
                <default>true</default>
                <label>Checking</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/loan__Bank_Account__c/fields/loan__Bank_Name__c.field-meta.xml
<CustomField>
    <fullName>loan__Bank_Name__c</fullName>
    <label>Bank Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/loan__Bank_Account__c/fields/loan__Routing_Number__c.field-meta.xml
<CustomField>
    <fullName>loan__Routing_Number__c</fullName>
    <inlineHelpText>This is a nine digit number used to identify the financial institution in a transaction.</inlineHelpText>
    <label>Routing Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/loan__Bank_Account__c/fields/Unmasked_Bank_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Unmasked_Bank_Account_Number__c</fullName>
    <label>Unmasked Bank Account Number</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/MW_BankAccountUpdateSync.cls
public class MW_BankAccountUpdateSync{
    public static void sendUpdatesToMatcha(map<Id,loan__Bank_Account__c> newMap, map<Id,loan__Bank_Account__c> OldMap){
        List<BankAccountDetails> bankAccPaylodList = new List<BankAccountDetails>();
        list<string> statusList = Label.MW_ExcludeAppStatusForBankAccountSync.split(';');
        map<Id,String> accAppIdMap = new map<Id,String>();
        set<Id> accIds = new set<Id>();
        
        for(loan__Bank_Account__c bankAcc : newMap.values()){
            accIds.add(bankAcc.loan__Account__c);
        }
        
        for(genesis__applications__c app : [select Id,Lead_ID__c,genesis__Account__c from genesis__applications__c 
                                            where genesis__Account__c IN : accIds AND 
                                            genesis__Status__c NOT IN : statusList]){
            accAppIdMap.put(app.genesis__Account__c,app.Lead_ID__c);
        }
        Boolean sendBankSync = false;
        for(Id bankId : newMap.keyset()){
            loan__Bank_Account__c bankAccRec = newMap.get(bankId);
            loan__Bank_Account__c oldBankAccRec = OldMap.get(bankId);
            if(bankAccRec != null && bankAccRec.loan__Active__c){
                BankAccountDetails bankAccPaylod = new BankAccountDetails();
                
                if(bankAccRec.Unmasked_Bank_Account_Number__c != oldBankAccRec.Unmasked_Bank_Account_Number__c ||
                    bankAccRec.loan__Routing_Number__c != oldBankAccRec.loan__Routing_Number__c ||
                    bankAccRec.loan__Account_Type__c != oldBankAccRec.loan__Account_Type__c ||
                    bankAccRec.loan__Bank_Name__c != oldBankAccRec.loan__Bank_Name__c ||
                    bankAccRec.First_Name__c != oldBankAccRec.First_Name__c ||
                    bankAccRec.Last_Name__c != oldBankAccRec.Last_Name__c)
                {
                    sendBankSync = true;
                }
                
                bankAccPaylod.bank_account_number = bankAccRec.Unmasked_Bank_Account_Number__c;
                bankAccPaylod.routing_number = bankAccRec.loan__Routing_Number__c;
                bankAccPaylod.account_type = bankAccRec.loan__Account_Type__c;
                bankAccPaylod.bank_name = bankAccRec.loan__Bank_Name__c;
                bankAccPaylod.first_name = bankAccRec.First_Name__c;
                bankAccPaylod.last_name = bankAccRec.Last_Name__c;
                                        
                if(accAppIdMap.get(bankAccRec.loan__Account__c) != null && sendBankSync){
                    bankAccPaylod.lead_guid = accAppIdMap.get(bankAccRec.loan__Account__c);
                    bankAccPaylodList.add(bankAccPaylod);
                }
            }
        }
        if(bankAccPaylodList.size() > 0){
            BankAccountPayload bap = new BankAccountPayload('sync_bank_account',bankAccPaylodList);
            Sync_bankAccount(JSON.serialize(bap,true),JSON.serialize(accAppIdMap.values(),true));
        }
    }
    @Future(callout=true)
    public static void Sync_bankAccount(string bankAccPaylod,string appIds){
        system.debug('bankAccPaylod====>'+bankAccPaylod);
        system.debug('appIds====>'+appIds);
        MW_WebhookHandler.CallWebHookIntegration(bankAccPaylod,appIds, '');
    }
    public class BankAccountDetails{
        public string lead_guid;
        public string bank_account_number;
        public string routing_number;
        public string account_type;
        public string bank_name;
        public string first_name;
        public string last_name;
        
        public BankAccountDetails(){}
    }
    public class BankAccountPayload{
        public string type;
        public List<BankAccountDetails> data;
        
        public BankAccountPayload(string type,List<BankAccountDetails> bankAccounts){
            this.type = type;
            this.data = bankAccounts;
        }
    }
    
}