force-app/main/default/objects/genesis__Applications__c/genesis__Applications__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{0000000000}</displayFormat>
        <label>Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/genesis__Applications__c/fields/genesis__Account__c.field-meta.xml
<CustomField>
    <fullName>genesis__Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Applications_account</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/genesis__Applications__c/fields/genesis__Status__c.field-meta.xml
<CustomField>
    <fullName>genesis__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>APPROVED - APPROVED</fullName>
            </value>
            <value>
                <fullName>APPROVED - CONVERTED TO CONTRACT</fullName>
            </value>
            <value>
                <fullName>APPROVED - DOCUMENT CHECK</fullName>
            </value>
            <value>
                <fullName>NEW - CREDIT PULLED</fullName>
            </value>
            <value>
                <fullName>NEW - ENTERED</fullName>
                <default>true</default>
                <label>NEW - ENTERED</label>
            </value>
            <value>
                <fullName>NEW - IN CREDIT CHECK</fullName>
            </value>
            <value>
                <fullName>NEW - IN REVIEW</fullName>
            </value>
            <value>
                <fullName>NEW - PRICING GENERATED</fullName>
            </value>
            <value>
                <fullName>NEW - SCORECARD GENERATED</fullName>
            </value>
            <value>
                <fullName>NEW - CHECKLIST GENERATED</fullName>
            </value>
            <value>
                <fullName>NEW - VEHICLE VALUATION REQUIRED</fullName>
            </value>
            <value>
                <fullName>REJECTED</fullName>
            </value>
            <value>
                <fullName>PULL CREDIT</fullName>
            </value>
            <value>
                <fullName>Default Documents</fullName>
            </value>
            <value>
                <fullName>offer_accepted</fullName>
            </value>
            <value>
                <fullName>offer_shown</fullName>
            </value>
            <value>
                <fullName>kba_success</fullName>
            </value>
            <value>
                <fullName>kba_fail</fullName>
            </value>
            <value>
                <fullName>agent_document_verification_pending</fullName>
            </value>
            <value>
                <fullName>agent_verification_pending</fullName>
            </value>
            <value>
                <fullName>agent_verified</fullName>
            </value>
            <value>
                <fullName>docusign_loan_docs_sent</fullName>
            </value>
            <value>
                <fullName>docusign_loan_docs_complete</fullName>
            </value>
            <value>
                <fullName>pre_funding</fullName>
            </value>
            <value>
                <fullName>Approved for funding</fullName>
            </value>
            <value>
                <fullName>funded</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Stacker_Check_Passed</fullName>
            </value>
            <value>
                <fullName>Redecision_Required</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ints__Yodlee_User_Credentials__c/ints__Yodlee_User_Credentials__c.object-meta.xml
<CustomObject>
    <label>Yodlee User Credentials</label>
    <nameField>
        <displayFormat>YUC-{00000000}</displayFormat>
        <label>Yodlee User Credentials Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Yodlee User Credentials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ints__Yodlee_User_Credentials__c/fields/ints__Account__c.field-meta.xml
<CustomField>
    <fullName>ints__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Yodlee User Credentials</relationshipLabel>
    <relationshipName>Yodlee_User_Credentials</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/FetchYodleeTransaction.cls
public class FetchYodleeTransaction {

    
    @future(callout=true)
    public static void fetchTxn(Map<Id,Id> accApp,Map<Id,Integer> accDays) {
        for(Id acc:accApp.keySet()) {
            System.debug('Hello'+acc);
            String txnResult = YodleeTransactionAPICallOut.getTransactions(acc,accApp.get(acc),accDays.get(acc));
            String updateAccInfo = UpdateAccountInfo.getLastUpdate(acc);
        }
        
    }
    
    /*@InvocableMethod 
    public static void invoke(List<Id> ids) {
        Set<Id> accId = new Set<Id>();
        List<ints__Yodlee_User_Credentials__c > userCred = [select id,name,ints__account__c
                                                            from ints__Yodlee_User_Credentials__c 
                                                            where id in: ids ];
        System.debug('Hello');
        for(ints__Yodlee_User_Credentials__c yodleeUser :userCred) {
            accId.add(yodleeUser.ints__Account__c);
        }
        List<String> status = new List<String>{'funded','Declined','Expired'};
        list<genesis__applications__c> appLst= [select id,name,genesis__status__c,genesis__account__c 
                                                from genesis__applications__c
                                                where genesis__account__c in: accId
                                                and genesis__status__c not in :status];
        
        Map<Id,Id> accApp = new Map<Id,Id>();
        for(genesis__applications__c app:appLst) {
            accApp.put(app.genesis__account__c,app.Id);
        }
        
        System.debug('Hello');
        fetchTxn(accApp);
    }*/

}