force-app/main/default/objects/genesis__Applications__c/genesis__Applications__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{0000000000}</displayFormat>
        <label>Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/genesis__Applications__c/fields/genesis__Status__c.field-meta.xml
<CustomField>
    <fullName>genesis__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>APPROVED - APPROVED</fullName>
            </value>
            <value>
                <fullName>APPROVED - CONVERTED TO CONTRACT</fullName>
            </value>
            <value>
                <fullName>APPROVED - DOCUMENT CHECK</fullName>
            </value>
            <value>
                <fullName>NEW - CREDIT PULLED</fullName>
            </value>
            <value>
                <fullName>NEW - ENTERED</fullName>
                <default>true</default>
                <label>NEW - ENTERED</label>
            </value>
            <value>
                <fullName>NEW - IN CREDIT CHECK</fullName>
            </value>
            <value>
                <fullName>NEW - IN REVIEW</fullName>
            </value>
            <value>
                <fullName>NEW - PRICING GENERATED</fullName>
            </value>
            <value>
                <fullName>NEW - SCORECARD GENERATED</fullName>
            </value>
            <value>
                <fullName>NEW - CHECKLIST GENERATED</fullName>
            </value>
            <value>
                <fullName>NEW - VEHICLE VALUATION REQUIRED</fullName>
            </value>
            <value>
                <fullName>REJECTED</fullName>
            </value>
            <value>
                <fullName>PULL CREDIT</fullName>
            </value>
            <value>
                <fullName>Default Documents</fullName>
            </value>
            <value>
                <fullName>offer_accepted</fullName>
            </value>
            <value>
                <fullName>offer_shown</fullName>
            </value>
            <value>
                <fullName>kba_success</fullName>
            </value>
            <value>
                <fullName>kba_fail</fullName>
            </value>
            <value>
                <fullName>agent_document_verification_pending</fullName>
            </value>
            <value>
                <fullName>agent_verification_pending</fullName>
            </value>
            <value>
                <fullName>agent_verified</fullName>
            </value>
            <value>
                <fullName>docusign_loan_docs_sent</fullName>
            </value>
            <value>
                <fullName>docusign_loan_docs_complete</fullName>
            </value>
            <value>
                <fullName>pre_funding</fullName>
            </value>
            <value>
                <fullName>Approved for funding</fullName>
            </value>
            <value>
                <fullName>funded</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Stacker_Check_Passed</fullName>
            </value>
            <value>
                <fullName>Redecision_Required</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/genesis__Applications__c/fields/Send_Offer_expiry_notification__c.field-meta.xml
<CustomField>
    <fullName>Send_Offer_expiry_notification__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Send Offer expiry notification</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/genesis__Applications__c/fields/X14day_s_Before_Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>X14day_s_Before_Expiration_Date__c</fullName>
    <description>/*Created By Nupur */
 For Email Trigger --  &quot;offer_expiration_14_days.liquid&quot;</description>
    <formula>IF( Differenc_Between_Today_and_Expiry_Date__c == $Setup.Expiry_Date__c.Alert_Before_Expiration_Date__c , TRUE, FALSE)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>14day&apos;s Before Expiration Date</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/SendOfferExpiryNotification.cls
/* ****************Modification History******************
* Modified By       Date                    JIRA Number
*   Shakul        15/3/2022          LSP-601 (Added Test.isRunningTest()in the query)	
******************Modification History******************/
global class SendOfferExpiryNotification implements Database.batchable<sObject>,Schedulable{
            
    String query;
       
    global SendOfferExpiryNotification(){
        //LSP-601-- Modified the query
        query = 'select id from genesis__Applications__c where X14day_s_Before_Expiration_Date__c = True '+(Test.isRunningTest()?' LIMIT 1':'');
                // 'and genesis__Status__c !=\''+String.escapeSingleQuotes(Status1)+'\' and genesis__Status__c !=\''+String.escapeSingleQuotes(Status2)+'\'';
        
        System.debug(logginglevel.error,'query+++'+query); 
                
    }
    
    global SendOfferExpiryNotification(String query){
        
        this.query = query; 
    }
    
    global void execute(SchedulableContext sc) {
        
        SendOfferExpiryNotification b = new SendOfferExpiryNotification();
        Database.executeBatch(b,1);
    
    }
    
    global Database.QueryLocator start(Database.BatchableContext bc){
                              
        System.debug('Query'+query);    
        return Database.getQueryLocator(query);
    
    }
    
    global void execute(Database.BatchableContext BC, List<sObject> scope){
        
        System.debug('----Method execute(+)scope----'+ scope);
        List<genesis__Applications__c > listOfApp = (List<genesis__Applications__c >)scope;
        List<genesis__Applications__c > listOfAppTobeUpdated = new List<genesis__Applications__c> ();
       
                
        for(genesis__Applications__c  app : listOfApp){
            
            app.Send_Offer_expiry_notification__c = true;
            listOfAppTobeUpdated.add(app);
            
        }
        
        update listOfAppTobeUpdated ;
    } 
    
    public void finish(Database.BatchableContext BC){

    }
    
}