force-app/main/default/objects/genesis__Applications__c/genesis__Applications__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{0000000000}</displayFormat>
        <label>Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/genesis__Applications__c/fields/Bank_Account__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bank Account</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Value does not exist or does not match filter criteria. Must choose bank account associated with account.</errorMessage>
        <filterItems>
            <field>loan__Bank_Account__c.loan__Account__c</field>
            <operation>equals</operation>
            <valueField>$Source.genesis__Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>loan__Bank_Account__c</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/genesis__Applications__c/fields/genesis__Account__c.field-meta.xml
<CustomField>
    <fullName>genesis__Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Applications_account</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/genesis__Applications__c/fields/genesis__Status__c.field-meta.xml
<CustomField>
    <fullName>genesis__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>APPROVED - APPROVED</fullName>
            </value>
            <value>
                <fullName>APPROVED - CONVERTED TO CONTRACT</fullName>
            </value>
            <value>
                <fullName>APPROVED - DOCUMENT CHECK</fullName>
            </value>
            <value>
                <fullName>NEW - CREDIT PULLED</fullName>
            </value>
            <value>
                <fullName>NEW - ENTERED</fullName>
                <default>true</default>
                <label>NEW - ENTERED</label>
            </value>
            <value>
                <fullName>NEW - IN CREDIT CHECK</fullName>
            </value>
            <value>
                <fullName>NEW - IN REVIEW</fullName>
            </value>
            <value>
                <fullName>NEW - PRICING GENERATED</fullName>
            </value>
            <value>
                <fullName>NEW - SCORECARD GENERATED</fullName>
            </value>
            <value>
                <fullName>NEW - CHECKLIST GENERATED</fullName>
            </value>
            <value>
                <fullName>NEW - VEHICLE VALUATION REQUIRED</fullName>
            </value>
            <value>
                <fullName>REJECTED</fullName>
            </value>
            <value>
                <fullName>PULL CREDIT</fullName>
            </value>
            <value>
                <fullName>Default Documents</fullName>
            </value>
            <value>
                <fullName>offer_accepted</fullName>
            </value>
            <value>
                <fullName>offer_shown</fullName>
            </value>
            <value>
                <fullName>kba_success</fullName>
            </value>
            <value>
                <fullName>kba_fail</fullName>
            </value>
            <value>
                <fullName>agent_document_verification_pending</fullName>
            </value>
            <value>
                <fullName>agent_verification_pending</fullName>
            </value>
            <value>
                <fullName>agent_verified</fullName>
            </value>
            <value>
                <fullName>docusign_loan_docs_sent</fullName>
            </value>
            <value>
                <fullName>docusign_loan_docs_complete</fullName>
            </value>
            <value>
                <fullName>pre_funding</fullName>
            </value>
            <value>
                <fullName>Approved for funding</fullName>
            </value>
            <value>
                <fullName>funded</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Stacker_Check_Passed</fullName>
            </value>
            <value>
                <fullName>Redecision_Required</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/loan__Bank_Account__c/loan__Bank_Account__c.object-meta.xml
<CustomObject>
    <label>Bank Account</label>
    <nameField>
        <displayFormat>BA-{00000}</displayFormat>
        <label>Bank Account Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bank Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/loan__Bank_Account__c/fields/loan__Account__c.field-meta.xml
<CustomField>
    <fullName>loan__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bank Accounts</relationshipLabel>
    <relationshipName>Bank_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/loan__Batch_Process_Log__c/loan__Batch_Process_Log__c.object-meta.xml
<CustomObject>
    <label>Batch Process Log</label>
    <nameField>
        <label>Apex Batch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Batch Process Log</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/loan__Batch_Process_Log__c/fields/loan__Log_Level__c.field-meta.xml
<CustomField>
    <fullName>loan__Log_Level__c</fullName>
    <description>An indicator of level of logging</description>
    <label>Log Level</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ERROR</fullName>
                <default>true</default>
                <label>ERROR</label>
            </value>
            <value>
                <fullName>DEBUG</fullName>
            </value>
            <value>
                <fullName>INFO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/loan__Batch_Process_Log__c/fields/loan__Message__c.field-meta.xml
<CustomField>
    <fullName>loan__Message__c</fullName>
    <label>Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/loan__Batch_Process_Log__c/fields/loan__Origin__c.field-meta.xml
<CustomField>
    <fullName>loan__Origin__c</fullName>
    <label>Origin</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Start Of Day Process</fullName>
            </value>
            <value>
                <fullName>End of Day Process</fullName>
            </value>
            <value>
                <fullName>Month End Process</fullName>
            </value>
            <value>
                <fullName>Year End Process</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DeactivateBankAccountsforApplications.cls
/***********Modification History**************
Pallavi			LOS-156			2019-11-21
/********************************************/
public class DeactivateBankAccountsforApplications {
    
    public static void deactivateBankAccount(Id appId) {
        
        List<String> deactivateStatus = System.Label.BankDeactivateStatus.split(',');
        list<genesis__applications__c> apps = [select id,name,genesis__account__c,Bank_Account__c,Bank_Account__r.loan__active__c from genesis__applications__c	//pallavi(LOS-156)
                                               where id =: appId and genesis__status__c in:deactivateStatus];
        
        List<Id> accountsId = new List<Id>();
        for(genesis__applications__c a:apps) {
            accountsId.add(a.genesis__account__c);
        }
        
        /*list<loan__bank_account__c> banks = [select id,name ,loan__active__c	//pallavi(LOS-156)(commented)
                                            from loan__bank_account__c
                                            where loan__account__c in: accountsId];*/
        
        
        /*if(banks!=null && banks.size()>0) {	//pallavi(LOS-156)(commented)
            List<loan__bank_account__c> deactivatebankAccount = new List<loan__bank_account__c>();
            for(loan__bank_account__c b:banks) {
                b.loan__active__c = false;   
                deactivatebankAccount.add(b);
            }*/
       /*pallavi(LOS-156)*/
        List<Id> bankaccountsId = new List<Id>();
        
        for(genesis__applications__c a:apps) {
            bankaccountsId.add(a.Bank_Account__c);
        }
        
         list<loan__bank_account__c> banks = [select id,name ,loan__active__c
                                            from loan__bank_account__c
                                            where id in: bankaccountsId];
        
        if(!bankaccountsId.isEmpty() && bankaccountsId.size()>0){
            List<loan__bank_account__c> deactivatebankAccount = new List<loan__bank_account__c>();
            for(loan__bank_account__c b:banks){
                b.loan__active__c = false;
                deactivatebankAccount.add(b);
            }
           /*pallavi(LOS-156)*/
                try {
                    if(deactivatebankAccount!=null && deactivatebankAccount.size()>0)	//pallavi
                    	update deactivatebankAccount;
                } catch (Exception e) {
                    loan__batch_process_log__c bpl = new loan__batch_process_log__c();
                    bpl.loan__message__c = e.getMessage() + 'at line number:'+e.getLineNumber();
                    bpl.loan__Origin__c = 'DeactivateBankAccounts';
                    bpl.loan__Log_Level__c = 'Exception';
                    insert bpl;
                }
        }
        
    }

}