force-app/main/default/objects/genesis__Applications__c/genesis__Applications__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{0000000000}</displayFormat>
        <label>Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/genesis__Applications__c/fields/Bank_Account__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bank Account</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Value does not exist or does not match filter criteria. Must choose bank account associated with account.</errorMessage>
        <filterItems>
            <field>loan__Bank_Account__c.loan__Account__c</field>
            <operation>equals</operation>
            <valueField>$Source.genesis__Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>loan__Bank_Account__c</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/genesis__Applications__c/fields/genesis__Status__c.field-meta.xml
<CustomField>
    <fullName>genesis__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>APPROVED - APPROVED</fullName>
            </value>
            <value>
                <fullName>APPROVED - CONVERTED TO CONTRACT</fullName>
            </value>
            <value>
                <fullName>APPROVED - DOCUMENT CHECK</fullName>
            </value>
            <value>
                <fullName>NEW - CREDIT PULLED</fullName>
            </value>
            <value>
                <fullName>NEW - ENTERED</fullName>
                <default>true</default>
                <label>NEW - ENTERED</label>
            </value>
            <value>
                <fullName>NEW - IN CREDIT CHECK</fullName>
            </value>
            <value>
                <fullName>NEW - IN REVIEW</fullName>
            </value>
            <value>
                <fullName>NEW - PRICING GENERATED</fullName>
            </value>
            <value>
                <fullName>NEW - SCORECARD GENERATED</fullName>
            </value>
            <value>
                <fullName>NEW - CHECKLIST GENERATED</fullName>
            </value>
            <value>
                <fullName>NEW - VEHICLE VALUATION REQUIRED</fullName>
            </value>
            <value>
                <fullName>REJECTED</fullName>
            </value>
            <value>
                <fullName>PULL CREDIT</fullName>
            </value>
            <value>
                <fullName>Default Documents</fullName>
            </value>
            <value>
                <fullName>offer_accepted</fullName>
            </value>
            <value>
                <fullName>offer_shown</fullName>
            </value>
            <value>
                <fullName>kba_success</fullName>
            </value>
            <value>
                <fullName>kba_fail</fullName>
            </value>
            <value>
                <fullName>agent_document_verification_pending</fullName>
            </value>
            <value>
                <fullName>agent_verification_pending</fullName>
            </value>
            <value>
                <fullName>agent_verified</fullName>
            </value>
            <value>
                <fullName>docusign_loan_docs_sent</fullName>
            </value>
            <value>
                <fullName>docusign_loan_docs_complete</fullName>
            </value>
            <value>
                <fullName>pre_funding</fullName>
            </value>
            <value>
                <fullName>Approved for funding</fullName>
            </value>
            <value>
                <fullName>funded</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Stacker_Check_Passed</fullName>
            </value>
            <value>
                <fullName>Redecision_Required</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/genesis__Applications__c/fields/Lead_ID__c.field-meta.xml
<CustomField>
    <fullName>Lead_ID__c</fullName>
    <description>This is the LEAD GUID received from FE</description>
    <externalId>true</externalId>
    <label>Lead ID</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/loan__Batch_Process_Log__c/loan__Batch_Process_Log__c.object-meta.xml
<CustomObject>
    <label>Batch Process Log</label>
    <nameField>
        <label>Apex Batch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Batch Process Log</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/loan__Batch_Process_Log__c/fields/loan__Batch_Id__c.field-meta.xml
<CustomField>
    <fullName>loan__Batch_Id__c</fullName>
    <label>Batch Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/loan__Batch_Process_Log__c/fields/loan__Batch_Job_Id__c.field-meta.xml
<CustomField>
    <fullName>loan__Batch_Job_Id__c</fullName>
    <label>Batch Job Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/loan__Batch_Process_Log__c/fields/loan__Log_Level__c.field-meta.xml
<CustomField>
    <fullName>loan__Log_Level__c</fullName>
    <description>An indicator of level of logging</description>
    <label>Log Level</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ERROR</fullName>
                <default>true</default>
                <label>ERROR</label>
            </value>
            <value>
                <fullName>DEBUG</fullName>
            </value>
            <value>
                <fullName>INFO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/loan__Batch_Process_Log__c/fields/loan__Message__c.field-meta.xml
<CustomField>
    <fullName>loan__Message__c</fullName>
    <label>Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/loan__Batch_Process_Log__c/fields/loan__Origin__c.field-meta.xml
<CustomField>
    <fullName>loan__Origin__c</fullName>
    <label>Origin</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Start Of Day Process</fullName>
            </value>
            <value>
                <fullName>End of Day Process</fullName>
            </value>
            <value>
                <fullName>Month End Process</fullName>
            </value>
            <value>
                <fullName>Year End Process</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/loan__Batch_Process_Log__c/fields/loan__Time__c.field-meta.xml
<CustomField>
    <fullName>loan__Time__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <label>Time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/loan__Batch_Process_Log__c/fields/loan__Type__c.field-meta.xml
<CustomField>
    <fullName>loan__Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Exception</fullName>
            </value>
            <value>
                <fullName>Warning</fullName>
            </value>
            <value>
                <fullName>Info</fullName>
            </value>
            <value>
                <fullName>Result</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MW_Settings__c/MW_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>MW_Settings</label>
</CustomObject>

force-app/main/default/objects/MW_Settings__c/fields/MissingDocumentsAppStatuses__c.field-meta.xml
<CustomField>
    <fullName>MissingDocumentsAppStatuses__c</fullName>
    <label>MissingDocumentsAppStatuses</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MW_Settings__c/fields/Slack_Middleware_System_Alert_Channel__c.field-meta.xml
<CustomField>
    <fullName>Slack_Middleware_System_Alert_Channel__c</fullName>
    <label>Slack Middleware System Alert Channel</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Talx__c/Talx__c.object-meta.xml
<CustomObject>
    <label>Talx</label>
    <nameField>
        <displayFormat>TAX-{0000000}</displayFormat>
        <label>Talx Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Talxs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Talx__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Talxs</relationshipLabel>
    <relationshipName>Talxs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Talx__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <label>Application</label>
    <referenceTo>genesis__Applications__c</referenceTo>
    <relationshipLabel>Talxs</relationshipLabel>
    <relationshipName>Talxs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Yodlee_User_Account__c/Yodlee_User_Account__c.object-meta.xml
<CustomObject>
    <label>Yodlee User Account</label>
    <nameField>
        <label>Yodlee User Accounts Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Yodlee User Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Yodlee_User_Account__c/fields/Yodlee_Account__c.field-meta.xml
<CustomField>
    <fullName>Yodlee_Account__c</fullName>
    <label>Yodlee Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Yodlee User Accounts</relationshipLabel>
    <relationshipName>Yodlee_User_Accounts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Yodlee_User_Account__c/fields/Yodlee_Application__c.field-meta.xml
<CustomField>
    <fullName>Yodlee_Application__c</fullName>
    <label>Application</label>
    <referenceTo>genesis__Applications__c</referenceTo>
    <relationshipLabel>Yodlee User Accounts</relationshipLabel>
    <relationshipName>Yodlee_User_Accounts</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/MW_LoanDocumentsPreCheckBatch.cls
global class MW_LoanDocumentsPreCheckBatch implements Database.Batchable<sObject>,Database.AllowsCallouts, Database.Stateful{
    public static List<loan__Batch_Process_Log__c> logList;
    global Database.QueryLocator start(Database.BatchableContext BC) {
        set<String> missingDocAppStatuses = new set<String>();
        if(MW_Settings__c.getInstance().MissingDocumentsAppStatuses__c != null)
            missingDocAppStatuses.addAll(MW_Settings__c.getInstance().MissingDocumentsAppStatuses__c.split(';'));
        String query = 'select Id,Lead_Id__c,Bank_Account__c,Name,genesis__Status__c,(select Id from Yodlee_User_Accounts__r),(select Id from Talxs__r) from genesis__Applications__c ';
        if(missingDocAppStatuses.size() > 0)
            query += 'where genesis__Status__c IN : missingDocAppStatuses';
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<genesis__Applications__c> scope) {
        logList = new List<loan__Batch_Process_Log__c>();
        List<Id> appIdSet = new List<Id>();
        map<Id,genesis__Applications__c> appMap =  new map<Id,genesis__Applications__c>();
        for(genesis__Applications__c app : scope){
            appMap.put(app.Id,app);
        }
        map<Id,list<Attachment>> appsDocumentsMap = new map<Id,list<Attachment>>();
        for(Attachment att : [Select Id,Name,ParentId from Attachment where ParentId IN : appMap.keySet()]){
            if(appsDocumentsMap.containskey(att.ParentId)){
                List<Attachment> existingAttList = new List<Attachment>();
                existingAttList.addAll(appsDocumentsMap.get(att.ParentId));
                existingAttList.add(att);
                appsDocumentsMap.put(att.ParentId,existingAttList);
            }else{
                appsDocumentsMap.put(att.ParentId,new List<Attachment>{att});
            }
        }
        string missingDocs = getMissingDocumentsForApplication(appsDocumentsMap,appMap);
        string body;
        if(missingDocs != ''){
            Map<String, Object> msg = new Map<String, Object>();
            msg.put('text', ':alert::alert::alert::alert::alert: \n' +
                    '****************************************************' + '\n' +
                    '*         MISSING DOCUMENT ALERT* ' + '\n' +
                    '****************************************************' + '\n' +
                    missingDocs);
            if(!Test.isRunningTest()) {
                MW_SlackCallOut.slackCallOut(MW_Settings__c.getInstance().Slack_Middleware_System_Alert_Channel__c, JSON.serialize(msg));
            }
        }
        
        system.debug('logList====>'+logList);
        if(logList.size() > 0){}
            insert logList;
    }
    
    public string getMissingDocumentsForApplication(map<Id,list<Attachment>> appAttachmentMap, map<Id,genesis__Applications__c> appMap){
        string appMissingDocumentsList = '';
        try{
            for(Id appId : appAttachmentMap.keySet()){
                string missingDocs = '========================================\n' + 'Application Name = '+appMap.get(appId).Name + '\n' + 'Application Id = ' + appId + '\n'
                                     + 'Application Status = '+appMap.get(appId).genesis__Status__c+'\n Missing Documents = \n';
                system.debug('missingDocs====>'+missingDocs);
                Boolean cbrMissing = true, csnMissing = true, preciseidMissing = true, tilMissing = true, linkedAccountMissing = true,talxMissing = true;
                for(Attachment att : appAttachmentMap.get(appId)){
                    if(att.Name.containsIgnoreCase('cbr')){
                        cbrMissing = false;
                    }else if(att.Name.containsIgnoreCase('til')){
                        tilMissing = false;
                    }else if(att.Name.containsIgnoreCase('Credit Score Notice')){
                        csnMissing = false;
                    }else if(att.Name.containsIgnoreCase('preciseid')){
                        preciseidMissing = false;
                    }else if(att.Name.containsIgnoreCase('linked')){
                        linkedAccountMissing = false;
                    }else if(att.Name.containsIgnoreCase('talx')){
                        talxMissing = false;
                    }
                }
                if(cbrMissing){ missingDocs = missingDocs +  '* Credit Bureau Report \n';}
                if(csnMissing){ missingDocs = missingDocs + '* Credit Score Notice \n';}
                if(preciseidMissing){ missingDocs = missingDocs + '* Preciseid \n ';}
                if(tilMissing){ missingDocs = missingDocs + '* TIL Document \n ';}
                if(linkedAccountMissing && appMap.get(appId).Yodlee_User_Accounts__r != null && appMap.get(appId).Yodlee_User_Accounts__r.size() > 0){ missingDocs = missingDocs + '* Linked Account \n ';}
                if(talxMissing && appMap.get(appId).Talxs__r != null && appMap.get(appId).Talxs__r.size() > 0){ missingDocs = missingDocs + '* Talx \n ';}
                system.debug('missingDocs====>'+missingDocs);
                if(missingDocs.contains('*')){
                    appMissingDocumentsList += missingDocs + '========================================\n';
                    logList.add(getLogRecord('MW_LoanDocumentsPreCheckBatch','Document Missing','Info','',missingDocs.substringAfter('Missing'),appId,'DEBUG'));
                }
            }
            if(Test.isRunningTest()) {
                Account accTemp = null;
                accTemp.Name = 'Test Catch Block';
            }
        }catch(Exception e){
                logList.add(getLogRecord('MW_LoanDocumentsPreCheckBatch',e.getMessage(),'Exception','','',string.valueOf(appAttachmentMap.keySet()),'DEBUG'));
        }
        system.debug('appMissingDocumentsList====>\n'+appMissingDocumentsList);
        if(appMissingDocumentsList.contains('*'))
            return appMissingDocumentsList; 
        return '';    
    }
    
    public static loan__Batch_Process_Log__c getLogRecord(string origin, string msg, string typeStr, string summaryRecordId, string batchJobId, string batchId, string logLevel){
        loan__Batch_Process_Log__c bplog = new loan__Batch_Process_Log__c();
        bplog.loan__Origin__c = origin;
        bplog.loan__Message__c = msg;
        bplog.loan__Type__c = typeStr;
        bplog.loan__Time__c = DateTime.now();
        bplog.loan__Summary_Record_Id__c = summaryRecordId;
        bplog.loan__Batch_Job_Id__c = batchJobId;
        bplog.loan__Batch_Id__c = batchId;
        bplog.loan__Log_Level__c = logLevel;
        return bplog;
    }
    
    global void finish(Database.BatchableContext BC) {
    }
    
}