force-app/main/default/objects/genesis__Applications__c/genesis__Applications__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{0000000000}</displayFormat>
        <label>Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>genesis__Applications__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/lead_guid__c.field-meta.xml
<CustomField>
    <fullName>lead_guid__c</fullName>
    <externalId>true</externalId>
    <label>lead_guid</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/MC_UpdateLeadHandlerTest.cls
@isTest
private class MC_UpdateLeadHandlerTest {

	@isTest static void checkLeadAppField() {
		Lead newLead = new Lead();
		newLead.LastName = 'test';
		newLead.Company = 'test company';
		newLead.Status = 'open';
		newLead.lead_guid__c = 'c9149473-e69f-ee12-38a7-d18b0cba847d';
		newLead.Application__c = null;
		insert newLead;

		List<Account> accountList = MW_DataFactoryTest.createAccounts(1);
		insert accountList;

		List<genesis__Applications__c> appList = MW_DataFactoryTest.createApplication(1, accountList[0].id);
		insert appList;

		//Test start
		MC_UpdateLeadHandler.updateLead(appList);

		Lead afterUpdateLead = [Select id, Application__c From Lead Where id =: newLead.id];

		System.assertEquals(appList[0].id, afterUpdateLead.Application__c);
	}

}