force-app/main/default/objects/genesis__Applications__c/genesis__Applications__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{0000000000}</displayFormat>
        <label>Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/genesis__Applications__c/fields/Bank_Account__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bank Account</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Value does not exist or does not match filter criteria. Must choose bank account associated with account.</errorMessage>
        <filterItems>
            <field>loan__Bank_Account__c.loan__Account__c</field>
            <operation>equals</operation>
            <valueField>$Source.genesis__Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>loan__Bank_Account__c</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/loan__Bank_Account__c/loan__Bank_Account__c.object-meta.xml
<CustomObject>
    <label>Bank Account</label>
    <nameField>
        <displayFormat>BA-{00000}</displayFormat>
        <label>Bank Account Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bank Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/loan__Loan_Account__c/loan__Loan_Account__c.object-meta.xml
<CustomObject>
    <description>Lending Account</description>
    <label>CL Contract</label>
    <nameField>
        <displayFormat>LAI-{00000000}</displayFormat>
        <label>CL Contract ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CL Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/loan__Loan_Account__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>genesis__Applications__c</referenceTo>
    <relationshipLabel>CL Contracts</relationshipLabel>
    <relationshipName>CL_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/loan__Loan_Status__c.field-meta.xml
<CustomField>
    <fullName>loan__Loan_Status__c</fullName>
    <inlineHelpText>Status of the Account, expected values are :
Pending Approval
Active - Good Standing
Active - Bad Standing
Active - Matured
Approved
Canceled
Closed - Obligations met
Closed- Written Off
Closed - Refinanced
Partial Application</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Partial Application</fullName>
                <default>true</default>
                <label>Partial Application</label>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Active - Good Standing</fullName>
            </value>
            <value>
                <fullName>Active - Bad Standing</fullName>
            </value>
            <value>
                <fullName>Closed - Obligations met</fullName>
            </value>
            <value>
                <fullName>Closed- Written Off</fullName>
            </value>
            <value>
                <fullName>Closed - Refinanced</fullName>
            </value>
            <value>
                <fullName>Active - Matured</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Active - Marked for Closure</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/Mod_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Mod_End_Date__c</fullName>
    <inlineHelpText>Due date of the first modified bill (skipped or reduced amount) for the most recent modification.</inlineHelpText>
    <label>Modification End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/Mod_Payment_Amount__c.field-meta.xml
<CustomField>
    <fullName>Mod_Payment_Amount__c</fullName>
    <inlineHelpText>Reduced payment amount during Payment Reduction period.</inlineHelpText>
    <label>New Payment Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/Skipped_a_Pay__c.field-meta.xml
<CustomField>
    <fullName>Skipped_a_Pay__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Flag to indicate if the most recent loan modification activity on the loan is a skip-a-pay.  This flag should be settable manually or by the batch skip-a-pay upload process</inlineHelpText>
    <label>Skipped a Pay</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/U_LoanModForbearance__c.field-meta.xml
<CustomField>
    <fullName>U_LoanModForbearance__c</fullName>
    <inlineHelpText>Amount of months with $0 billed amount.</inlineHelpText>
    <label>Loan Mod Forbearance Length</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/U_LoanModForbearDt__c.field-meta.xml
<CustomField>
    <fullName>U_LoanModForbearDt__c</fullName>
    <inlineHelpText>Due date of the first modified bill (skipped or reduced amount) for the most recent modification.</inlineHelpText>
    <label>Loan Mod Forbearance Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Status__c/loan__Loan_Status__c.object-meta.xml
<CustomObject>
    <description>Object for storing Loan Statuses</description>
    <label>Loan Status</label>
    <nameField>
        <label>Loan Status Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loan Status</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/LoanAccountHandler.cls
public with sharing class LoanAccountHandler {
    
    List<loan__Loan_Account__c> newRecords;
    Map<Id, loan__Loan_Account__c> oldMap;
    Map<Id, loan__Loan_Account__c> newMap;

    public LoanAccountHandler(List<loan__Loan_Account__c> newRecords, Map<Id, loan__Loan_Account__c> newMap, Map<Id, loan__Loan_Account__c> oldMap) {
        this.newRecords = newRecords;
        this.oldMap = oldMap;
        this.newMap = newMap;
    }

    public void beforeUpdate() {
        List<loan__Bank_Account__c> bankAccToBeDeactivated = new List<loan__Bank_Account__c>();
        try {

            set<id> appId = new Set<id>();
            for (loan__Loan_Account__c newLoanAcc : newRecords) {
                //LPC-938 for skipped a pay
                if (newLoanAcc.Mod_End_Date__c == null && newLoanAcc.Skipped_a_Pay__c && newLoanAcc.U_LoanModForbearDt__c != null && newLoanAcc.U_LoanModForbearance__c != null) {
                    newLoanAcc.Mod_Payment_Amount__c = null;
                    newLoanAcc.Mod_End_Date__c = newLoanAcc.U_LoanModForbearDt__c.addDays(-1).addMonths(Integer.valueOf(newLoanAcc.U_LoanModForbearance__c));
                }

                loan__Loan_Account__c oldLoanAcc = oldMap.get(newLoanAcc.id);
                system.debug('newLoanAcc.Application__c------->' + newLoanAcc.Application__c);
                if (oldLoanAcc.loan__Loan_Status__c != newLoanAcc.loan__Loan_Status__c && newLoanAcc.loan__Loan_Status__c == 'Closed - obligations met' && newLoanAcc.Application__c != null){
                    appId.add(newLoanAcc.Application__c);
                }
            }

            for (genesis__applications__c app : [SELECT id, name, bank_account__c FROM genesis__applications__c WHERE ID IN :appId]) {
                bankAccToBeDeactivated.add(new loan__Bank_Account__c(Id=app.bank_account__c, loan__Active__c = false));
            }
            if (bankAccToBeDeactivated.size() > 0) {
                update bankAccToBeDeactivated;
            }
        } catch (Exception e) {
            MW_LogUtility.error('LoanAccountHandler', 'beforeUpdate', bankAccToBeDeactivated, e);
        }
    }
}