force-app/main/default/objects/genesis__Applications__c/genesis__Applications__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{0000000000}</displayFormat>
        <label>Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/genesis__Applications__c/fields/BoxFolderID__c.field-meta.xml
<CustomField>
    <fullName>BoxFolderID__c</fullName>
    <label>BoxFolderID</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/genesis__Applications__c/fields/DocuSign_Sign_Date__c.field-meta.xml
<CustomField>
    <fullName>DocuSign_Sign_Date__c</fullName>
    <label>DocuSign Sign Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/genesis__Applications__c/fields/Investor__c.field-meta.xml
<CustomField>
    <fullName>Investor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Investor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.loan__Investor__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Applications (Investor)</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/genesis__Applications__c/fields/Lead_ID__c.field-meta.xml
<CustomField>
    <fullName>Lead_ID__c</fullName>
    <description>This is the LEAD GUID received from FE</description>
    <externalId>true</externalId>
    <label>Lead ID</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/genesis__Applications__c/fields/LeadGUIDBoxFolderID__c.field-meta.xml
<CustomField>
    <fullName>LeadGUIDBoxFolderID__c</fullName>
    <description>This field will contain the folder id for the Lead guid box folder.</description>
    <label>LeadGUIDBoxFolderID</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/MW_UpdateBoxFolder2.cls
global class  MW_UpdateBoxFolder2 implements Database.Batchable<sObject>,Database.AllowsCallouts{

  global final String query = 'select Id, Lead_ID__c, LeadGUIDBoxFolderID__c, Investor__c, DocuSign_Sign_Date__c from genesis__Applications__c where LeadGUIDBoxFolderID__c=\'\' and Lead_ID__c!=\'\' and BoxFolderID__c!=\'\'';

  global Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator(query);
   }

   global void execute(Database.BatchableContext BC, List<genesis__Applications__c> scope) {

        List<genesis__Applications__c> appsList  = new List<genesis__Applications__c>();

        for(genesis__Applications__c app:scope)
        {
           genesis__Applications__c apps  = MW_BoxUtil1.createLeadGUIDBoxFolderID(app.Id);
           System.debug('>>>>>>>>+' +apps);
           if(apps!= null && apps.LeadGUIDBoxFolderID__c !=null)
           appsList.add(apps);
        }

        /*
           Update All Applications at a time
        */
        if(appsList.size()>0){
            update appsList;
        }

        MW_BoxUtil1.insertAccessToken();

    }

    global void finish(Database.BatchableContext BC) {

    }
}