force-app/main/default/objects/genesis__Applications__c/genesis__Applications__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{0000000000}</displayFormat>
        <label>Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/genesis__Applications__c/fields/Anniversary_Date__c.field-meta.xml
<CustomField>
    <fullName>Anniversary_Date__c</fullName>
    <label>Anniversary Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/genesis__Applications__c/fields/genesis__Payment_Frequency__c.field-meta.xml
<CustomField>
    <fullName>genesis__Payment_Frequency__c</fullName>
    <label>Payment Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>genesis__Product_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>DAILY</fullName>
            </value>
            <value>
                <fullName>WEEKLY</fullName>
            </value>
            <value>
                <fullName>BI-WEEKLY</fullName>
            </value>
            <value>
                <fullName>MONTHLY</fullName>
                <default>true</default>
                <label>MONTHLY</label>
            </value>
            <value>
                <fullName>QUARTERLY</fullName>
            </value>
            <value>
                <fullName>ANNUAL</fullName>
            </value>
            <value>
                <fullName>SEMI-MONTHLY</fullName>
            </value>
            <value>
                <fullName>BI-MONTHLY</fullName>
            </value>
            <value>
                <fullName>SEMI-ANNUAL</fullName>
            </value>
            <value>
                <fullName>SINGLEPMT</fullName>
            </value>
            <value>
                <fullName>SEMI-MONTHLY-PD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/genesis__Applications__c/fields/genesis__Term__c.field-meta.xml
<CustomField>
    <fullName>genesis__Term__c</fullName>
    <label>Term</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/genesis__Applications__c/fields/maturityDate__c.field-meta.xml
<CustomField>
    <fullName>maturityDate__c</fullName>
    <label>Maturity Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/maturitydate1.cls
// written by Saryu as the addmonths function was not working as expected in calculating the maturity date.
global class maturitydate1 {
    @InvocableMethod
    public static void setmaturitydate(list<id> appId) {
        list<genesis__applications__c> app = [select id, Anniversary_Date__c ,genesis__Term__c,genesis__payment_frequency__c FROM genesis__applications__c WHERE id in:appId and Anniversary_Date__c!=null];
        System.debug('In setmaturitydate');
        list<genesis__applications__c> updateApp = new list<genesis__applications__c>();
        try {
            for(genesis__applications__c a:app) {
                Integer frequencyMultiplier = ((Integer)a.genesis__term__c - 1);
                Integer day = a.Anniversary_Date__c.day();
                Date nextdate = a.Anniversary_Date__c.addMonths(1);
                Date maturityDate = loan.DateUtil.getNextCycleDate(a.Anniversary_Date__c , day,a.genesis__payment_frequency__c,a.Anniversary_Date__c ,nextdate,frequencyMultiplier);
                a.maturityDate__c = maturityDate;
                updateApp.add(a);
            }
			if(updateApp!=null && updateApp.size()>0)
            	update app;
            
       } catch (exception ex) {
            system.debug(logginglevel.error, 'Error a:' + ex.getCause());
            system.debug(logginglevel.error, ex.getLineNumber());
            system.debug(logginglevel.error, ex.getMessage());
            system.debug(logginglevel.error, ex.getStackTraceString());
            throw ex;
        }
        
    }
}