force-app/main/default/objects/clcommon__Repayment_Plan__c/clcommon__Repayment_Plan__c.object-meta.xml
<CustomObject>
    <description>This object is used to capture the Repyament plan for any contract.</description>
    <label>Repayment Plan</label>
    <nameField>
        <displayFormat>RP-{000000}</displayFormat>
        <label>Repayment Plan ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Repayment Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/clcommon__Repayment_Plan__c/fields/loan__Loan_Account__c.field-meta.xml
<CustomField>
    <fullName>loan__Loan_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Reference to CL Contract to which this repayment plan is applicable</description>
    <inlineHelpText>Reference to CL Contract to which this repayment plan is applicable</inlineHelpText>
    <label>CL Contract</label>
    <referenceTo>loan__Loan_Account__c</referenceTo>
    <relationshipLabel>Flexible Repayment Plan</relationshipLabel>
    <relationshipName>Repayment_Plan</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/loan__Batch_Process_Log__c/loan__Batch_Process_Log__c.object-meta.xml
<CustomObject>
    <label>Batch Process Log</label>
    <nameField>
        <label>Apex Batch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Batch Process Log</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/loan__Batch_Process_Log__c/fields/loan__Batch_Id__c.field-meta.xml
<CustomField>
    <fullName>loan__Batch_Id__c</fullName>
    <label>Batch Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/loan__Batch_Process_Log__c/fields/loan__Log_Level__c.field-meta.xml
<CustomField>
    <fullName>loan__Log_Level__c</fullName>
    <description>An indicator of level of logging</description>
    <label>Log Level</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ERROR</fullName>
                <default>true</default>
                <label>ERROR</label>
            </value>
            <value>
                <fullName>DEBUG</fullName>
            </value>
            <value>
                <fullName>INFO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/loan__Batch_Process_Log__c/fields/loan__Message__c.field-meta.xml
<CustomField>
    <fullName>loan__Message__c</fullName>
    <label>Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/loan__Loan_Account__c.object-meta.xml
<CustomObject>
    <description>Lending Account</description>
    <label>CL Contract</label>
    <nameField>
        <displayFormat>LAI-{00000000}</displayFormat>
        <label>CL Contract ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CL Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/loan__Loan_Account__c/fields/CPD_CSD_diff__c.field-meta.xml
<CustomField>
    <fullName>CPD_CSD_diff__c</fullName>
    <formula>$User.loan__Current_Branch_s_System_Date__c - CPD_Unpaid_Due_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CPD CSD diff</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/CPD_Date__c.field-meta.xml
<CustomField>
    <fullName>CPD_Date__c</fullName>
    <description>The payment Date provided by the Member to change the Due date.</description>
    <label>CPD Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/CPD_Expire_Date__c.field-meta.xml
<CustomField>
    <fullName>CPD_Expire_Date__c</fullName>
    <description>date when the CPD reason hold expires and CPD can be performed via API</description>
    <label>CPD Expire Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/CPD_Reason__c.field-meta.xml
<CustomField>
    <fullName>CPD_Reason__c</fullName>
    <description>If CPD triggered from front end, this value is set with reason and to restrict CPD performed via API</description>
    <label>CPD Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Changed Payment Date</fullName>
            </value>
            <value>
                <fullName>Past Due or Loan Mod</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Changed via Member Portal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/CPD_Unpaid_Due_Date__c.field-meta.xml
<CustomField>
    <fullName>CPD_Unpaid_Due_Date__c</fullName>
    <label>CPD - Unpaid Due Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/Future_Bill_Pending__c.field-meta.xml
<CustomField>
    <fullName>Future_Bill_Pending__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Future Bill Pending</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/loan__Frequency_of_Loan_Payment__c.field-meta.xml
<CustomField>
    <fullName>loan__Frequency_of_Loan_Payment__c</fullName>
    <inlineHelpText>This decides the Payment Frequency, below are the supported ones:
Daily
Weekly
Bi-weekly
Semi-Monthly
Monthly
Bi-Monthly  
Quarterly
Semi-Annual
Annual 
Single-Payment</inlineHelpText>
    <label>Payment Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Daily</fullName>
            </value>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>Bi-weekly</fullName>
            </value>
            <value>
                <fullName>Semi-Monthly</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
                <default>true</default>
                <label>Monthly</label>
            </value>
            <value>
                <fullName>Bi-Monthly</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Semi-Annual</fullName>
            </value>
            <value>
                <fullName>Annual</fullName>
            </value>
            <value>
                <fullName>Single-Payment</fullName>
            </value>
            <value>
                <fullName>Semi-Monthly-PD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/loan__Interest_Rate__c.field-meta.xml
<CustomField>
    <fullName>loan__Interest_Rate__c</fullName>
    <description>Interest Rate</description>
    <inlineHelpText>Rate of Interest for the loan.</inlineHelpText>
    <label>Current Interest Rate</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/loan__Last_Installment_Date__c.field-meta.xml
<CustomField>
    <fullName>loan__Last_Installment_Date__c</fullName>
    <description>Maturity Date of Loan account</description>
    <inlineHelpText>Maturity date as per contract.</inlineHelpText>
    <label>Maturity Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/loan__Maturity_Date_Current__c.field-meta.xml
<CustomField>
    <fullName>loan__Maturity_Date_Current__c</fullName>
    <inlineHelpText>This is the date on which the the loan matures</inlineHelpText>
    <label>Current Maturity Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/loan__Next_Installment_Date__c.field-meta.xml
<CustomField>
    <fullName>loan__Next_Installment_Date__c</fullName>
    <description>Date of the next installment</description>
    <inlineHelpText>Date of the Next Due</inlineHelpText>
    <label>Next Due Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/loan__Pmt_Amt_Cur__c.field-meta.xml
<CustomField>
    <fullName>loan__Pmt_Amt_Cur__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Current Payment Amount</description>
    <inlineHelpText>This is the current installment amount that needs to be paid.</inlineHelpText>
    <label>Current Payment Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/loan__Term_Cur__c.field-meta.xml
<CustomField>
    <fullName>loan__Term_Cur__c</fullName>
    <description>Current Term</description>
    <inlineHelpText>Current loan account term.</inlineHelpText>
    <label>Current Term</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/loan__Loan_account_Due_Details__c/loan__Loan_account_Due_Details__c.object-meta.xml
<CustomObject>
    <description>Invoices/bills for customer loans.</description>
    <label>Bills</label>
    <nameField>
        <displayFormat>PCN-{0000000000}</displayFormat>
        <label>Due Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bills</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/loan__Loan_account_Due_Details__c/fields/loan__DD_Primary_Flag__c.field-meta.xml
<CustomField>
    <fullName>loan__DD_Primary_Flag__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Primary</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/loan__Loan_account_Due_Details__c/fields/loan__Due_Date__c.field-meta.xml
<CustomField>
    <fullName>loan__Due_Date__c</fullName>
    <description>Due date of the due.</description>
    <inlineHelpText>Due Date of the Due</inlineHelpText>
    <label>Due Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/loan__Loan_account_Due_Details__c/fields/loan__Loan_Account__c.field-meta.xml
<CustomField>
    <fullName>loan__Loan_Account__c</fullName>
    <label>Loan Account</label>
    <referenceTo>loan__Loan_Account__c</referenceTo>
    <relationshipName>Dues_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/loan__Loan_account_Due_Details__c/fields/loan__Payment_Satisfied__c.field-meta.xml
<CustomField>
    <fullName>loan__Payment_Satisfied__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Payment Satisfied</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/loan__Repayment_Schedule__c/loan__Repayment_Schedule__c.object-meta.xml
<CustomObject>
    <description>Amortization schedule is also called as Repayment schedule.</description>
    <label>Amortization Schedule</label>
    <nameField>
        <displayFormat>RSI-{0000000000}</displayFormat>
        <label>Repayment Schedule ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Amortization Schedule</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/loan__Repayment_Schedule__c/fields/loan__Due_Date__c.field-meta.xml
<CustomField>
    <fullName>loan__Due_Date__c</fullName>
    <description>Due date</description>
    <inlineHelpText>The date on which the loan payment is due.</inlineHelpText>
    <label>Due Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/loan__Repayment_Schedule__c/fields/loan__Is_Archived__c.field-meta.xml
<CustomField>
    <fullName>loan__Is_Archived__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates if a new repayment schedule for this loan account has been generated and this one is archived for reference.</description>
    <inlineHelpText>Indicates if a new repayment schedule for this loan account has been generated and this one is archived for reference.</inlineHelpText>
    <label>Is Archived</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/loan__Repayment_Schedule__c/fields/loan__Loan_Account__c.field-meta.xml
<CustomField>
    <fullName>loan__Loan_Account__c</fullName>
    <description>Repayment Schedule of which Loan account</description>
    <inlineHelpText>Repayment Schedule of which Loan account</inlineHelpText>
    <label>Loan Account</label>
    <referenceTo>loan__Loan_Account__c</referenceTo>
    <relationshipName>Repayment_Schedule</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/CLS_ProcessCPDJob.cls
global class CLS_ProcessCPDJob Implements Database.Batchable<sObject>, Schedulable{
    
    private List<String> loanContract;
    loan__Batch_Process_Log__c batch = new loan__Batch_Process_Log__c();
    
    public CLS_ProcessCPDJob(List<String> loanContract){
        this.loanContract = loanContract;
    }
    
    public CLS_ProcessCPDJob(){}
    
    global void execute(SchedulableContext sc) {
        
        CLS_ProcessCPDJob cpdProcess = new CLS_ProcessCPDJob();
        Database.executeBatch(cpdProcess,1);
    
    }
    
    public Database.QueryLocator start(Database.BatchableContext bc){
        
        String query = 'Select id,name,loan__Last_Installment_Date__c,loan__Interest_Rate__c,loan__Frequency_of_Loan_Payment__c,loan__Pmt_Amt_Cur__c,CPD_CSD_diff__c,CPD_Date__c,CPD_Unpaid_Due_Date__c,Future_Bill_Pending__c,'+
                         'loan__Next_Installment_Date__c,loan__Maturity_Date_Current__c,loan__Term_Cur__c,(Select id,name,loan__Is_Archived__c,loan__Due_Date__c from loan__Repayment_Schedule__r),'+                             
                         '(select id,name,loan__Due_Date__c from loan__Dues_Details__r where loan__Payment_Satisfied__c  = false and loan__DD_Primary_Flag__c = true order by loan__Due_Date__c DESC limit 1),'+
                         '(select id,name from loan__Repayment_Plan__r),CPD_Reason__c,CPD_Expire_Date__c from loan__Loan_Account__c where Future_Bill_Pending__c = True and CPD_CSD_diff__c >= 1';
    
        
        System.debug(LoggingLevel.ERROR, 'query in initialize : ' + query);
        return Database.getQueryLocator(query);
    }
    
    public void execute(Database.BatchableContext bc, List<sObject> scope){
        Savepoint sp = database.setsavepoint();
        
        List<loan__Loan_Account__c> loanAccountList = (List<loan__Loan_Account__c>)scope;
        
        for(loan__Loan_Account__c loan:loanAccountList){
            System.debug(logginglevel.error, 'Processing Loan :: '+loan.name);
            try{
                /*pallavi*/
                if(test.isRunningTest()){
                    Date lastPaymentDate = loan.loan__Last_Installment_Date__c;
                    Date tothrowException = lastPaymentDate.addDays(2);
                }
                /*pallavi*/
                CLS_ProcessCPDJobHandler handler = new CLS_ProcessCPDJobHandler();
                handler.ChangePaymentDate(loan);
            }catch(exception e){
                database.rollback(sp); 
                System.debug(logginglevel.ERROR,'CPD Processing failed for :'+loan.Name);
                batch.loan__Log_Level__c = 'ERROR';
                batch.loan__Message__c = 'Process CPD ::'+ loan.Name + '. :: ERROR :: '+e.getMessage() + ' :: StackTrace ::' +e.getStackTraceString() ;
                batch.loan__Batch_Id__c = 'CLS_ProcessCPDJob';
                insert batch;
            } 
        }
    }
    
    public void finish(Database.BatchableContext bc){}
    
}