force-app/main/default/objects/clcommon__Repayment_Plan__c/clcommon__Repayment_Plan__c.object-meta.xml
<CustomObject>
    <description>This object is used to capture the Repyament plan for any contract.</description>
    <label>Repayment Plan</label>
    <nameField>
        <displayFormat>RP-{000000}</displayFormat>
        <label>Repayment Plan ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Repayment Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/clcommon__Repayment_Plan__c/fields/loan__Loan_Account__c.field-meta.xml
<CustomField>
    <fullName>loan__Loan_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Reference to CL Contract to which this repayment plan is applicable</description>
    <inlineHelpText>Reference to CL Contract to which this repayment plan is applicable</inlineHelpText>
    <label>CL Contract</label>
    <referenceTo>loan__Loan_Account__c</referenceTo>
    <relationshipLabel>Flexible Repayment Plan</relationshipLabel>
    <relationshipName>Repayment_Plan</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/genesis__Applications__c/genesis__Applications__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{0000000000}</displayFormat>
        <label>Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/genesis__Applications__c/fields/genesis__Monthly_Debt_Payments__c.field-meta.xml
<CustomField>
    <fullName>genesis__Monthly_Debt_Payments__c</fullName>
    <label>Monthly Debt Payments</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/genesis__Applications__c/fields/Loan_Origination_Date__c.field-meta.xml
<CustomField>
    <fullName>Loan_Origination_Date__c</fullName>
    <label>Loan Origination Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>genesis__Applications__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/lead_guid__c.field-meta.xml
<CustomField>
    <fullName>lead_guid__c</fullName>
    <externalId>true</externalId>
    <label>lead_guid</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/loan__Batch_Process_Log__c/loan__Batch_Process_Log__c.object-meta.xml
<CustomObject>
    <label>Batch Process Log</label>
    <nameField>
        <label>Apex Batch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Batch Process Log</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/loan__Batch_Process_Log__c/fields/loan__Log_Level__c.field-meta.xml
<CustomField>
    <fullName>loan__Log_Level__c</fullName>
    <description>An indicator of level of logging</description>
    <label>Log Level</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ERROR</fullName>
                <default>true</default>
                <label>ERROR</label>
            </value>
            <value>
                <fullName>DEBUG</fullName>
            </value>
            <value>
                <fullName>INFO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/loan__Loan_Account__c.object-meta.xml
<CustomObject>
    <description>Lending Account</description>
    <label>CL Contract</label>
    <nameField>
        <displayFormat>LAI-{00000000}</displayFormat>
        <label>CL Contract ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CL Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/loan__Loan_Account__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>genesis__Applications__c</referenceTo>
    <relationshipLabel>CL Contracts</relationshipLabel>
    <relationshipName>CL_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/lead_Guid__c.field-meta.xml
<CustomField>
    <fullName>lead_Guid__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>lead_Guid</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/loan__Accrual_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>loan__Accrual_Start_Date__c</fullName>
    <description>The date from which interest accrual starts</description>
    <inlineHelpText>The date from which interest accrual starts</inlineHelpText>
    <label>Accrual Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/loan__Application_Date__c.field-meta.xml
<CustomField>
    <fullName>loan__Application_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <inlineHelpText>Application Received Date.</inlineHelpText>
    <label>Application Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/loan__Disbursal_Date__c.field-meta.xml
<CustomField>
    <fullName>loan__Disbursal_Date__c</fullName>
    <description>Contract Date on the Loan account, this will be updated at the time of funding with the Expected Disbursal Date.</description>
    <inlineHelpText>Contract date on the loan. This will be updated at the time of funding with the expected disbursal date.</inlineHelpText>
    <label>Contract Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/loan__First_Installment_Date__c.field-meta.xml
<CustomField>
    <fullName>loan__First_Installment_Date__c</fullName>
    <description>Date of the first installment</description>
    <inlineHelpText>This is the desired start date of the repayment schedule that is provided while creating the loan application.</inlineHelpText>
    <label>First Payment Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/loan__Frequency_of_Loan_Payment__c.field-meta.xml
<CustomField>
    <fullName>loan__Frequency_of_Loan_Payment__c</fullName>
    <inlineHelpText>This decides the Payment Frequency, below are the supported ones:
Daily
Weekly
Bi-weekly
Semi-Monthly
Monthly
Bi-Monthly  
Quarterly
Semi-Annual
Annual 
Single-Payment</inlineHelpText>
    <label>Payment Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Daily</fullName>
            </value>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>Bi-weekly</fullName>
            </value>
            <value>
                <fullName>Semi-Monthly</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
                <default>true</default>
                <label>Monthly</label>
            </value>
            <value>
                <fullName>Bi-Monthly</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Semi-Annual</fullName>
            </value>
            <value>
                <fullName>Annual</fullName>
            </value>
            <value>
                <fullName>Single-Payment</fullName>
            </value>
            <value>
                <fullName>Semi-Monthly-PD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/loan__Interest_Rate__c.field-meta.xml
<CustomField>
    <fullName>loan__Interest_Rate__c</fullName>
    <description>Interest Rate</description>
    <inlineHelpText>Rate of Interest for the loan.</inlineHelpText>
    <label>Current Interest Rate</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/loan__Last_Installment_Date__c.field-meta.xml
<CustomField>
    <fullName>loan__Last_Installment_Date__c</fullName>
    <description>Maturity Date of Loan account</description>
    <inlineHelpText>Maturity date as per contract.</inlineHelpText>
    <label>Maturity Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/loan__Loan_Status__c.field-meta.xml
<CustomField>
    <fullName>loan__Loan_Status__c</fullName>
    <inlineHelpText>Status of the Account, expected values are :
Pending Approval
Active - Good Standing
Active - Bad Standing
Active - Matured
Approved
Canceled
Closed - Obligations met
Closed- Written Off
Closed - Refinanced
Partial Application</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Partial Application</fullName>
                <default>true</default>
                <label>Partial Application</label>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Active - Good Standing</fullName>
            </value>
            <value>
                <fullName>Active - Bad Standing</fullName>
            </value>
            <value>
                <fullName>Closed - Obligations met</fullName>
            </value>
            <value>
                <fullName>Closed- Written Off</fullName>
            </value>
            <value>
                <fullName>Closed - Refinanced</fullName>
            </value>
            <value>
                <fullName>Active - Matured</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Active - Marked for Closure</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/loan__Maturity_Date_Current__c.field-meta.xml
<CustomField>
    <fullName>loan__Maturity_Date_Current__c</fullName>
    <inlineHelpText>This is the date on which the the loan matures</inlineHelpText>
    <label>Current Maturity Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/loan__Next_Installment_Date__c.field-meta.xml
<CustomField>
    <fullName>loan__Next_Installment_Date__c</fullName>
    <description>Date of the next installment</description>
    <inlineHelpText>Date of the Next Due</inlineHelpText>
    <label>Next Due Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/loan__Payment_Amount__c.field-meta.xml
<CustomField>
    <fullName>loan__Payment_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Loan payment amount. It excludes any fee that is gathered as a part of EMI.</description>
    <inlineHelpText>Contractual payment amount</inlineHelpText>
    <label>Payment Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/loan__Pmt_Amt_Cur__c.field-meta.xml
<CustomField>
    <fullName>loan__Pmt_Amt_Cur__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Current Payment Amount</description>
    <inlineHelpText>This is the current installment amount that needs to be paid.</inlineHelpText>
    <label>Current Payment Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/loan__Previous_Installment_Date__c.field-meta.xml
<CustomField>
    <fullName>loan__Previous_Installment_Date__c</fullName>
    <description>Last Billing Date</description>
    <inlineHelpText>Last Bill Date</inlineHelpText>
    <label>Last Due Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/loan__Term_Cur__c.field-meta.xml
<CustomField>
    <fullName>loan__Term_Cur__c</fullName>
    <description>Current Term</description>
    <inlineHelpText>Current loan account term.</inlineHelpText>
    <label>Current Term</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/loan__Repayment_Schedule__c/loan__Repayment_Schedule__c.object-meta.xml
<CustomObject>
    <description>Amortization schedule is also called as Repayment schedule.</description>
    <label>Amortization Schedule</label>
    <nameField>
        <displayFormat>RSI-{0000000000}</displayFormat>
        <label>Repayment Schedule ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Amortization Schedule</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/loan__Repayment_Schedule__c/fields/loan__Due_Date__c.field-meta.xml
<CustomField>
    <fullName>loan__Due_Date__c</fullName>
    <description>Due date</description>
    <inlineHelpText>The date on which the loan payment is due.</inlineHelpText>
    <label>Due Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/loan__Repayment_Schedule__c/fields/loan__Is_Archived__c.field-meta.xml
<CustomField>
    <fullName>loan__Is_Archived__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates if a new repayment schedule for this loan account has been generated and this one is archived for reference.</description>
    <inlineHelpText>Indicates if a new repayment schedule for this loan account has been generated and this one is archived for reference.</inlineHelpText>
    <label>Is Archived</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/loan__Repayment_Schedule__c/fields/loan__Loan_Account__c.field-meta.xml
<CustomField>
    <fullName>loan__Loan_Account__c</fullName>
    <description>Repayment Schedule of which Loan account</description>
    <inlineHelpText>Repayment Schedule of which Loan account</inlineHelpText>
    <label>Loan Account</label>
    <referenceTo>loan__Loan_Account__c</referenceTo>
    <relationshipName>Repayment_Schedule</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/RescheduleMigratedLoan.cls
public class RescheduleMigratedLoan {
    
    public loan__Loan_Account__c lAtobeUpdated;   
    Date repaymentStartDate;
    Date transactionDate;
    Id CLContractId;
    
    loan__Batch_Process_Log__c batch = new loan__Batch_Process_Log__c();
    loan.globalLoanUtilFacade util = new loan.globalLoanUtilFacade();
    Date systemDate = util.getCurrentSystemDate();
       
    public RescheduleMigratedLoan(Id contractId,Date repaymentDate, Date txnDate){  
        CLContractId = contractId;
        repaymentStartDate = repaymentDate;
        transactionDate = txnDate;
        System.debug(logginglevel.error, ' In RescheduleMigratedLoan : LoanID: '+CLContractId +' ** repaymentStartDate :: '+repaymentStartDate +' ** transactionDate :: '+transactionDate); 
    }
    
    public void rescheduleLoan() {
               
        Date secondPaymentDate = null;
        Date lastPaymentDate; 
        Integer noOfInstallments = null;
        Integer interestOnlyPeriod = 0;
        Decimal interestRate;
        String frequencyOfPayment;
        Boolean maintainDelinquency = true;
        Boolean actualInterestOnlyPayments = False;
        Integer amortizationTerm;
        Integer dueDay;
        String stepUpOption = null;
        Decimal interestOnlyPaymentAmt = 0;
        Boolean regenerateInvAmzSchedule = True;
        
        try {      
                           
            if(lAtobeUpdated == null){
                lAtobeUpdated = [Select id,name,lead_Guid__c,loan__First_Installment_Date__c,
                             Application__r.genesis__Monthly_Debt_Payments__c,
                             loan__Payment_Amount__c,
                             loan__Loan_Status__c,
                             loan__Accrual_Start_Date__c,
                             Application__r.Loan_Origination_Date__c,
                             loan__Last_Installment_Date__c,
                             loan__Interest_Rate__c,
                             loan__Frequency_of_Loan_Payment__c,
                             loan__Pmt_Amt_Cur__c,
                             loan__Next_Installment_Date__c,
                             loan__Previous_Installment_Date__c,
                             loan__Maturity_Date_Current__c,
                             loan__Term_Cur__c,loan__Application_Date__c,                            
                             loan__Disbursal_Date__c,
                             (Select id,name,
                              loan__Is_Archived__c,
                              loan__Due_Date__c
                              from loan__Repayment_Schedule__r),
                             (select id,name from loan__Repayment_Plan__r)                              
                             from loan__Loan_Account__c
                             where Id =: CLContractId limit 1];
                       
            }
            
            System.debug('CLContractId..: '+CLContractId);           
                    
            if (lAtobeUpdated == null ) {
                batch.loan__Log_Level__c = 'ERROR';
                batch.loan__Message__c = 'Please check the Lead Id as there are no contracts for the provided CLContractId ::'+ lAtobeUpdated.Name;                
                batch.loan__Batch_Id__c = 'RescheduleMigratedLoan';
                insert batch;
                return;
            }
            
            //set repayment date            
            System.debug(logginglevel.error, ' lAtobeUpdated.Id: '+lAtobeUpdated.Id +' systemDate: '+systemDate);                                                                                 
            //repaymentStartDate = amortSchedule.get(Integer.valueOf(numberOfSkips)).loan__due_date__c;
            
            system.debug('repaymentStartDate is: '+repaymentStartDate);
                       
            lastPaymentDate = (lAtobeUpdated.loan__Maturity_Date_Current__c);
            interestRate = lAtobeUpdated.loan__Interest_Rate__c;
            frequencyOfPayment = lAtobeUpdated.loan__Frequency_of_Loan_Payment__c;
            if(repaymentStartDate != null){
                dueDay = repaymentStartDate.day();
            }
            System.debug(logginglevel.DEBUG,'Current Maturity Date: '+lastPaymentDate +' DUEDAY: '+dueDay);

            Integer terms = getRemainingTerm();
                
            if(lAtobeUpdated.loan__Repayment_Plan__r != null && lAtobeUpdated.loan__Repayment_Plan__r.size() != 0) {
                delete lAtobeUpdated.loan__Repayment_Plan__r;
            }

            List<clcommon__Repayment_Plan__c> repaymentPlan = new List<clcommon__Repayment_Plan__c>();
            repaymentPlan.add(new clcommon__Repayment_Plan__c(clcommon__Sequence_Number__c = 1,
                                                              clcommon__Payment_Type__c = 'Equal Monthly Installments',
                                                              clcommon__Payment_Amount__c = lAtobeUpdated.loan__Pmt_Amt_Cur__c,                                                              
                                                              clcommon__Payment_Start_Date__c = repaymentStartDate,
                                                              clcommon__Number_Of_Payments__c = (terms - 1),
                                                              clcommon__Due_Day__c = dueDay,
                                                              clcommon__Effective_Date__c = systemDate,// can be transactionDate
                                                              loan__Loan_Account__c = lAtobeUpdated.id));
                                                              
            System.debug(logginglevel.DEBUG,'Repayment PLAN :: '+repaymentPlan);
            insert repaymentPlan;
            
            loan.LoanRescheduleParameters rescheduleParams = new loan.LoanRescheduleParameters(lAtobeUpdated.id,
                                                                                               transactionDate,
                                                                                               repaymentStartDate,
                                                                                               secondPaymentDate,
                                                                                               lastPaymentDate,
                                                                                               noOfInstallments,
                                                                                               interestOnlyPeriod,
                                                                                               interestRate,
                                                                                               frequencyOfPayment,
                                                                                               maintainDelinquency,
                                                                                               actualInterestOnlyPayments,
                                                                                               amortizationTerm,
                                                                                               dueDay,
                                                                                               stepUpOption,
                                                                                               interestOnlyPaymentAmt,
                                                                                               regenerateInvAmzSchedule);

            List<loan.LoanRescheduleParameters.ProposedRepaymentPlan> repaymentPlanList = rescheduleParams.getRepaymentPlan();
            System.debug(logginglevel.DEBUG,'repaymentPlanList.. : '+repaymentPlanList);
            rescheduleParams.setRepaymentPlan(repaymentPlanList);

            loan.LoanActionFactory factory = new loan.LoanActionFactory();
            loan.LoanAction7 loanAction = factory.getLoanAction7API();
            System.debug(logginglevel.DEBUG,'rescheduleParams.. : '+rescheduleParams);
            loanAction.rescheduleALoan(rescheduleParams);            
            
            //check if reschedule is successful
            
            System.debug('Call to rescheduleALoan of loanAction ends..');
            
            //lAtobeUpdated.loan__Next_Installment_Date__c = repaymentStartDate;
            //lAtobeUpdated.loan__Maturity_Date_Current__c = lastPaymentDate;
            if((lAtobeUpdated.loan__Loan_Status__c).equals('Active - Good Standing')){
                lAtobeUpdated.loan__Oldest_Due_Date__c = repaymentStartDate;
                System.debug('loan__Oldest_Due_Date__c is updated to: '+lAtobeUpdated.loan__Oldest_Due_Date__c);
            }
            
            update lAtobeUpdated;      

        } catch (Exception e) {          
            batch.loan__Log_Level__c = 'ERROR';
            batch.loan__Message__c = ' Reschedule Failed for ::'+ lAtobeUpdated.Name + '. :: ERROR :: '+e.getMessage() + ' :: StackTrace ::' +e.getStackTraceString() ;
            batch.loan__Batch_Id__c = 'RescheduleMigratedLoan';
            insert batch;
            
            System.debug(logginglevel.error,'line number'+e.getLineNumber());
            System.debug(logginglevel.error,'error stackTrace'+e.getStackTraceString());
            System.debug(logginglevel.error,'error message'+e.getMessage());

        }
        
    }

    /*
     *  Calculates remaining number of payments to be done
     *  returns integer 
     * 
     */
    public Integer getRemainingTerm() {
    
        Integer remainingTerm;
        if (lAtobeUpdated.loan__Next_Installment_Date__c != null && lAtobeUpdated.loan__Maturity_Date_Current__c != null) {
            remainingTerm = (Integer)(loan.DateUtil.cyclesBetween(transactionDate, //lAtobeUpdated.loan__Next_Installment_Date__c,
                                                                  lAtobeUpdated.loan__Maturity_Date_Current__c,
                                                                  lAtobeUpdated.loan__Frequency_of_Loan_Payment__c));
                                                                  
            System.debug(logginglevel.error,'remainingTerm in IF :: '+remainingTerm);
        }
        System.debug(logginglevel.error,'remainingTerm ::'+remainingTerm);
        return remainingTerm;
    }
    
}