force-app/main/default/objects/clcommon__Repayment_Plan__c/clcommon__Repayment_Plan__c.object-meta.xml
<CustomObject>
    <description>This object is used to capture the Repyament plan for any contract.</description>
    <label>Repayment Plan</label>
    <nameField>
        <displayFormat>RP-{000000}</displayFormat>
        <label>Repayment Plan ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Repayment Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/clcommon__Repayment_Plan__c/fields/loan__Loan_Account__c.field-meta.xml
<CustomField>
    <fullName>loan__Loan_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Reference to CL Contract to which this repayment plan is applicable</description>
    <inlineHelpText>Reference to CL Contract to which this repayment plan is applicable</inlineHelpText>
    <label>CL Contract</label>
    <referenceTo>loan__Loan_Account__c</referenceTo>
    <relationshipLabel>Flexible Repayment Plan</relationshipLabel>
    <relationshipName>Repayment_Plan</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/genesis__Applications__c/genesis__Applications__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{0000000000}</displayFormat>
        <label>Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/genesis__Applications__c/fields/genesis__Monthly_Debt_Payments__c.field-meta.xml
<CustomField>
    <fullName>genesis__Monthly_Debt_Payments__c</fullName>
    <label>Monthly Debt Payments</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/genesis__Applications__c/fields/Loan_Origination_Date__c.field-meta.xml
<CustomField>
    <fullName>Loan_Origination_Date__c</fullName>
    <label>Loan Origination Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/loan__Loan_Account__c.object-meta.xml
<CustomObject>
    <description>Lending Account</description>
    <label>CL Contract</label>
    <nameField>
        <displayFormat>LAI-{00000000}</displayFormat>
        <label>CL Contract ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CL Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/loan__Loan_Account__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>genesis__Applications__c</referenceTo>
    <relationshipLabel>CL Contracts</relationshipLabel>
    <relationshipName>CL_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/CPD_Reason__c.field-meta.xml
<CustomField>
    <fullName>CPD_Reason__c</fullName>
    <description>If CPD triggered from front end, this value is set with reason and to restrict CPD performed via API</description>
    <label>CPD Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Changed Payment Date</fullName>
            </value>
            <value>
                <fullName>Past Due or Loan Mod</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Changed via Member Portal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/lead_Guid__c.field-meta.xml
<CustomField>
    <fullName>lead_Guid__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>lead_Guid</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/loan__Accrual_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>loan__Accrual_Start_Date__c</fullName>
    <description>The date from which interest accrual starts</description>
    <inlineHelpText>The date from which interest accrual starts</inlineHelpText>
    <label>Accrual Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/loan__Disbursal_Date__c.field-meta.xml
<CustomField>
    <fullName>loan__Disbursal_Date__c</fullName>
    <description>Contract Date on the Loan account, this will be updated at the time of funding with the Expected Disbursal Date.</description>
    <inlineHelpText>Contract date on the loan. This will be updated at the time of funding with the expected disbursal date.</inlineHelpText>
    <label>Contract Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/loan__First_Installment_Date__c.field-meta.xml
<CustomField>
    <fullName>loan__First_Installment_Date__c</fullName>
    <description>Date of the first installment</description>
    <inlineHelpText>This is the desired start date of the repayment schedule that is provided while creating the loan application.</inlineHelpText>
    <label>First Payment Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/loan__Frequency_of_Loan_Payment__c.field-meta.xml
<CustomField>
    <fullName>loan__Frequency_of_Loan_Payment__c</fullName>
    <inlineHelpText>This decides the Payment Frequency, below are the supported ones:
Daily
Weekly
Bi-weekly
Semi-Monthly
Monthly
Bi-Monthly  
Quarterly
Semi-Annual
Annual 
Single-Payment</inlineHelpText>
    <label>Payment Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Daily</fullName>
            </value>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>Bi-weekly</fullName>
            </value>
            <value>
                <fullName>Semi-Monthly</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
                <default>true</default>
                <label>Monthly</label>
            </value>
            <value>
                <fullName>Bi-Monthly</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Semi-Annual</fullName>
            </value>
            <value>
                <fullName>Annual</fullName>
            </value>
            <value>
                <fullName>Single-Payment</fullName>
            </value>
            <value>
                <fullName>Semi-Monthly-PD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/loan__Interest_Rate__c.field-meta.xml
<CustomField>
    <fullName>loan__Interest_Rate__c</fullName>
    <description>Interest Rate</description>
    <inlineHelpText>Rate of Interest for the loan.</inlineHelpText>
    <label>Current Interest Rate</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/loan__Last_Installment_Date__c.field-meta.xml
<CustomField>
    <fullName>loan__Last_Installment_Date__c</fullName>
    <description>Maturity Date of Loan account</description>
    <inlineHelpText>Maturity date as per contract.</inlineHelpText>
    <label>Maturity Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/loan__Loan_Status__c.field-meta.xml
<CustomField>
    <fullName>loan__Loan_Status__c</fullName>
    <inlineHelpText>Status of the Account, expected values are :
Pending Approval
Active - Good Standing
Active - Bad Standing
Active - Matured
Approved
Canceled
Closed - Obligations met
Closed- Written Off
Closed - Refinanced
Partial Application</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Partial Application</fullName>
                <default>true</default>
                <label>Partial Application</label>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Active - Good Standing</fullName>
            </value>
            <value>
                <fullName>Active - Bad Standing</fullName>
            </value>
            <value>
                <fullName>Closed - Obligations met</fullName>
            </value>
            <value>
                <fullName>Closed- Written Off</fullName>
            </value>
            <value>
                <fullName>Closed - Refinanced</fullName>
            </value>
            <value>
                <fullName>Active - Matured</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Active - Marked for Closure</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/loan__Maturity_Date_Current__c.field-meta.xml
<CustomField>
    <fullName>loan__Maturity_Date_Current__c</fullName>
    <inlineHelpText>This is the date on which the the loan matures</inlineHelpText>
    <label>Current Maturity Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/loan__Next_Installment_Date__c.field-meta.xml
<CustomField>
    <fullName>loan__Next_Installment_Date__c</fullName>
    <description>Date of the next installment</description>
    <inlineHelpText>Date of the Next Due</inlineHelpText>
    <label>Next Due Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/loan__Payment_Amount__c.field-meta.xml
<CustomField>
    <fullName>loan__Payment_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Loan payment amount. It excludes any fee that is gathered as a part of EMI.</description>
    <inlineHelpText>Contractual payment amount</inlineHelpText>
    <label>Payment Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/loan__Pmt_Amt_Cur__c.field-meta.xml
<CustomField>
    <fullName>loan__Pmt_Amt_Cur__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Current Payment Amount</description>
    <inlineHelpText>This is the current installment amount that needs to be paid.</inlineHelpText>
    <label>Current Payment Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/loan__Previous_Installment_Date__c.field-meta.xml
<CustomField>
    <fullName>loan__Previous_Installment_Date__c</fullName>
    <description>Last Billing Date</description>
    <inlineHelpText>Last Bill Date</inlineHelpText>
    <label>Last Due Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/loan__Term_Cur__c.field-meta.xml
<CustomField>
    <fullName>loan__Term_Cur__c</fullName>
    <description>Current Term</description>
    <inlineHelpText>Current loan account term.</inlineHelpText>
    <label>Current Term</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/Skipped_a_Pay__c.field-meta.xml
<CustomField>
    <fullName>Skipped_a_Pay__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Flag to indicate if the most recent loan modification activity on the loan is a skip-a-pay.  This flag should be settable manually or by the batch skip-a-pay upload process</inlineHelpText>
    <label>Skipped a Pay</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/Skipped_a_pay_Date__c.field-meta.xml
<CustomField>
    <fullName>Skipped_a_pay_Date__c</fullName>
    <description>This field represents the day on which skip-a-pay is performed</description>
    <inlineHelpText>Date batch process for executing Skip a Pays in bulk is run.</inlineHelpText>
    <label>Loan Mod Batch Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/loan__Repayment_Schedule__c/loan__Repayment_Schedule__c.object-meta.xml
<CustomObject>
    <description>Amortization schedule is also called as Repayment schedule.</description>
    <label>Amortization Schedule</label>
    <nameField>
        <displayFormat>RSI-{0000000000}</displayFormat>
        <label>Repayment Schedule ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Amortization Schedule</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/loan__Repayment_Schedule__c/fields/loan__Due_Date__c.field-meta.xml
<CustomField>
    <fullName>loan__Due_Date__c</fullName>
    <description>Due date</description>
    <inlineHelpText>The date on which the loan payment is due.</inlineHelpText>
    <label>Due Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/loan__Repayment_Schedule__c/fields/loan__Is_Archived__c.field-meta.xml
<CustomField>
    <fullName>loan__Is_Archived__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates if a new repayment schedule for this loan account has been generated and this one is archived for reference.</description>
    <inlineHelpText>Indicates if a new repayment schedule for this loan account has been generated and this one is archived for reference.</inlineHelpText>
    <label>Is Archived</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/loan__Repayment_Schedule__c/fields/loan__Loan_Account__c.field-meta.xml
<CustomField>
    <fullName>loan__Loan_Account__c</fullName>
    <description>Repayment Schedule of which Loan account</description>
    <inlineHelpText>Repayment Schedule of which Loan account</inlineHelpText>
    <label>Loan Account</label>
    <referenceTo>loan__Loan_Account__c</referenceTo>
    <relationshipName>Repayment_Schedule</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ForBearanceLoanBatch.cls
/********************************************************************************************************************************
 * author Anusha
 * 
 * This batch is to skip a month's payment for a set of loan ids as borrowers have issues making payment due to COVID-19 pandemic
 * and reschedule those loans to start repayment later after a month
 * 
 * @params : set of loan ids for which skip-a-pay is requested
 * results - 1. given loans are rescheduled
 *        	 2. loan maturity date is moved accordingly
 * 
 *****************Modification History*****************************************************************
 * Modified by      Date            JIRA number
 *    Pallavi       2020/01/14    CRM-952 (Completely automate the SAP processing for LoanOps/Produce errors/logs for failures.)
 * 	  Anusha		2021/02/18	  LSP-3 (Completely automate the SAP processing for LoanOps)
 * 	  Anusha		2021/04/08	  LSP-3 Changes to include bad loans in the mail   
 ******************Modification History*****************************************************************/

global class ForBearanceLoanBatch implements Database.batchable<sObject>,Database.stateful {	//CRM-952
    
    String query;
    Set<Id> loanAccountIdSet = new Set<Id>();
    Set<String> loanAccountNameSet = new Set<String>();
    Map<String,String> loanAccountNameMap = new Map<String,String>();
    List<loan__Loan_Account__c> UnprocessedLoans = new List<loan__Loan_Account__c>();
    loan__Batch_Process_Log__c batch = new loan__Batch_Process_Log__c();
    loan.GlobalLoanUtilFacade util = new loan.GlobalLoanUtilFacade();
    Date systemDate = util.getCurrentSystemDate();
    DateTime systemDateTime = util.getCurrentSystemDateTime();	//CRM-952
    Integer numberOfSkips = 1;
    Map<String,String> contractSAPerror = new Map<String,String>();	//CRM-952
    
    global ForBearanceLoanBatch (Set<Id> LoanIDs){     
        
        loanAccountIdSet = LoanIDs;
        System.debug(logginglevel.DEBUG,'loanAccountIdSet +++'+loanAccountIdSet);
        
        query = 'Select id,name,lead_Guid__c,loan__First_Installment_Date__c, '+
                         'Application__r.genesis__Monthly_Debt_Payments__c,'+
                         'loan__Payment_Amount__c,'+
                         'loan__Loan_Status__c,'+
                         'loan__Accrual_Start_Date__c,'+
                         'Application__r.Loan_Origination_Date__c,'+
                         'loan__Last_Installment_Date__c,'+
                         'loan__Interest_Rate__c,'+
                         'loan__Frequency_of_Loan_Payment__c,'+
                         'loan__Pmt_Amt_Cur__c,'+
                         'loan__Next_Installment_Date__c,'+
                         'loan__Previous_Installment_Date__c,'+
                         'loan__Maturity_Date_Current__c,'+
                         'loan__Disbursal_Date__c,'+
                         'loan__Term_Cur__c,'+
                   		 'Skipped_a_pay_Date__c,'+
                         'Skipped_a_Pay__c,'+
                         '(Select id,name,'+
                         'loan__Is_Archived__c,'+
                         'loan__Due_Date__c'+
                         ' from loan__Repayment_Schedule__r),'+
                         '(select id,name from loan__Repayment_Plan__r),'+
                         'CPD_Reason__c,'+
                         'CPD_Expire_Date__c,'+
            	/*LSP-3 start */
            			 'U_LoanModTermExt__c,'+
            			 'loan__Oldest_Due_Date__c,'+
            			 'U_LoanModForbearance__c,'+
            			 'Hardship_New_Maturity_Date__c,'+
            			 'U_LoanModForbearDt__c,'+
            			 'Hardship_Request_Date__c'+
                /*LSP-3 end */
                         ' from loan__Loan_Account__c'+
                         ' where Id in : loanAccountIdSet';            
    }
    
    global ForBearanceLoanBatch (Set<String> LoanNames){     
        
        loanAccountNameSet = LoanNames;
        System.debug(logginglevel.DEBUG,'loanAccountIdSet +++'+loanAccountIdSet);
        
        query = 'Select id,name,lead_Guid__c,loan__First_Installment_Date__c, '+
                         'Application__r.genesis__Monthly_Debt_Payments__c,'+
                         'loan__Payment_Amount__c,'+
                         'loan__Loan_Status__c,'+
                         'loan__Accrual_Start_Date__c,'+
                         'Application__r.Loan_Origination_Date__c,'+
                         'loan__Last_Installment_Date__c,'+
                         'loan__Interest_Rate__c,'+
                         'loan__Frequency_of_Loan_Payment__c,'+
                         'loan__Pmt_Amt_Cur__c,'+
                         'loan__Next_Installment_Date__c,'+
                         'loan__Previous_Installment_Date__c,'+
                         'loan__Maturity_Date_Current__c,'+
                         'loan__Disbursal_Date__c,'+
                         'loan__Term_Cur__c,'+
                   		 'Skipped_a_pay_Date__c,'+
                         'Skipped_a_Pay__c,'+
                         '(Select id,name,'+
                         'loan__Is_Archived__c,'+
                         'loan__Due_Date__c'+
                         ' from loan__Repayment_Schedule__r),'+
                         '(select id,name from loan__Repayment_Plan__r),'+
                         'CPD_Reason__c,'+
                         'CPD_Expire_Date__c,'+
            /*LSP-3 start */
            			 'U_LoanModTermExt__c,'+
            			 'loan__Oldest_Due_Date__c,'+
            			 'U_LoanModForbearance__c,'+
            			 'Hardship_New_Maturity_Date__c,'+
            			 'U_LoanModForbearDt__c,'+
            			 'Hardship_Request_Date__c'+
            /*LSP-3 end */
                         ' from loan__Loan_Account__c'+
                         ' where Name in : loanAccountNameSet';            
    }
    
    global ForBearanceLoanBatch (Map<String,String> LoanNames, Map<String,String> badLoansMap){//LSP-3 Changes to include bad loans in mail
        loanAccountNameSet = LoanNames.keySet();
        loanAccountNameMap = LoanNames;        
        System.debug(logginglevel.DEBUG,'loanAccountNameMap +++'+loanAccountNameMap);       
        contractSAPerror.putAll(badLoansMap);//LSP-3 Changes to include bad loans in mail
        
        query = 'Select id,name,lead_Guid__c,loan__First_Installment_Date__c, '+
                         'Application__r.genesis__Monthly_Debt_Payments__c,'+
                         'loan__Payment_Amount__c,'+
                         'loan__Loan_Status__c,'+
                         'loan__Accrual_Start_Date__c,'+
                         'Application__r.Loan_Origination_Date__c,'+
                         'loan__Last_Installment_Date__c,'+
                         'loan__Interest_Rate__c,'+
                         'loan__Frequency_of_Loan_Payment__c,'+
                         'loan__Pmt_Amt_Cur__c,'+
                         'loan__Next_Installment_Date__c,'+
                         'loan__Previous_Installment_Date__c,'+
                         'loan__Maturity_Date_Current__c,'+
                         'loan__Disbursal_Date__c,'+
                         'loan__Term_Cur__c,'+
                   		 'Skipped_a_pay_Date__c,'+
                         'Skipped_a_Pay__c,'+
                         '(Select id,name,'+
                         'loan__Is_Archived__c,'+
                         'loan__Due_Date__c'+
                         ' from loan__Repayment_Schedule__r),'+
                         '(select id,name from loan__Repayment_Plan__r),'+
                         'CPD_Reason__c,'+
                         'CPD_Expire_Date__c,'+
            /*LSP-3 start */
            			 'U_LoanModTermExt__c,'+
            			 'loan__Oldest_Due_Date__c,'+
            			 'U_LoanModForbearance__c,'+
            			 'Hardship_New_Maturity_Date__c,'+
            			 'U_LoanModForbearDt__c,'+
            			 'Hardship_Request_Date__c'+
            /*LSP-3 end */
                         ' from loan__Loan_Account__c'+
                         ' where Name in : loanAccountNameSet';            
    }
    
    global Database.QueryLocator start(Database.BatchableContext bc){                           
        System.debug('In Database.QueryLocator : '+query);    
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<sObject> scope){
        System.debug(logginglevel.DEBUG,'*** Method execute(+)scope *** '+ scope);
        List<loan__loan_account__c> listOfLoans = (List<loan__loan_account__c>)scope;                   
        for(loan__loan_account__c loan : listOfLoans ){
            if(loanAccountNameMap != null && loanAccountNameMap.size()>0){
              numberOfSkips = Integer.valueOf((loanAccountNameMap.get(loan.Name)).trim());
          }else numberOfSkips = 1;
            System.debug(logginglevel.DEBUG, 'Processing Loan :: '+loan.name);
            try{                                                                     
                 ForBearanceLoanHelper helper = new ForBearanceLoanHelper(loan,numberOfSkips);
                 helper.rescheduleLoan(contractSAPerror);  //CRM-952             
            }catch(Exception e){
                 System.debug(logginglevel.DEBUG,'Failed to reschedule loan : '+loan.Name);
                 batch.loan__Log_Level__c = 'ERROR';
                 batch.loan__Message__c = ' Reschedule failed for ::'+ loan.Name + '. :: ERROR :: '+e.getMessage() + ' :: StackTrace ::' +e.getStackTraceString() ;
                 batch.loan__Batch_Id__c = 'ForBearanceLoanBatch';
                 insert batch;
                 contractSAPerror.put(loan.Name,batch.loan__Message__c);	//CRM-952
            }
        }
    } 
    /*CRM-952*/
    public void finish(Database.BatchableContext BC){
        String emailBody = 'Skip a Pay Ran by ' + UserInfo.getName() + ' at ' + systemDateTime;	//CRM-952
        emailBody += ' \n\n Please find below the list of unprocessed loans in skip a pay';
        /*CRM-952*/
        Set<String> contractName = new Set<String>();
        contractName = contractSAPerror.keySet();
        if(contractName.size()==0)
            emailBody += '\n\n All the loans are processed for skip a pay.';
        for(String contract : contractName){
            emailBody += '\n'+contract + ' '+ contractSAPerror.get(contract).trim();
        }
        
        emailBody += '\n\n Please find below the list of processed loans in skip a pay';
        
        List<loan__Loan_Account__c> processedLoans = [Select Id,Name from loan__Loan_Account__c
                                                     where (Name IN : loanAccountNameSet OR ID IN : loanAccountIdSet)
                                                     and name not in: contractName];
        if(processedLoans.size()==0)
            emailBody += '\n\n No contract was processed successfully for skip a pay.';
        for(loan__Loan_Account__c loansNotSkipped : processedLoans){
            emailBody += '\n'+loansNotSkipped.name;                                             
        }                                                 
        /*CRM-952*/
        emailBody += '\n\n ** This is a system generated email.';
        
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        List<string> toAddresses = Label.MW_SkipAPayEmailRecipients.split(';');
        toAddresses.add(Userinfo.getUserEmail());
        mail.setToAddresses(toAddresses);
        mail.setSubject('Skip a pay - Processed/Unprocessed loans ');	//CRM-952
        mail.setPlainTextBody(emailBody);	//CRM-952
        Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
    }
    /*CRM-952*/
}