force-app/main/default/objects/clcommon__Repayment_Plan__c/clcommon__Repayment_Plan__c.object-meta.xml
<CustomObject>
    <description>This object is used to capture the Repyament plan for any contract.</description>
    <label>Repayment Plan</label>
    <nameField>
        <displayFormat>RP-{000000}</displayFormat>
        <label>Repayment Plan ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Repayment Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/clcommon__Repayment_Plan__c/fields/clcommon__Due_Day__c.field-meta.xml
<CustomField>
    <fullName>clcommon__Due_Day__c</fullName>
    <inlineHelpText>The day of every cycle on which the payment is expected. This is to capture if the due day is different from the payment start date</inlineHelpText>
    <label>Due Day</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/clcommon__Repayment_Plan__c/fields/clcommon__Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>clcommon__Effective_Date__c</fullName>
    <inlineHelpText>Effective start date for the repayment plan</inlineHelpText>
    <label>Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/clcommon__Repayment_Plan__c/fields/clcommon__Number_Of_Payments__c.field-meta.xml
<CustomField>
    <fullName>clcommon__Number_Of_Payments__c</fullName>
    <inlineHelpText>Number of installments for the plan period</inlineHelpText>
    <label>Number of Payments</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/clcommon__Repayment_Plan__c/fields/clcommon__Payment_Amount__c.field-meta.xml
<CustomField>
    <fullName>clcommon__Payment_Amount__c</fullName>
    <inlineHelpText>The expected payment amount per installment for the plan period</inlineHelpText>
    <label>Payment Amount</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/clcommon__Repayment_Plan__c/fields/clcommon__Payment_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>clcommon__Payment_Start_Date__c</fullName>
    <inlineHelpText>The date of first installment for the plan period</inlineHelpText>
    <label>Payment Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/clcommon__Repayment_Plan__c/fields/clcommon__Payment_Type__c.field-meta.xml
<CustomField>
    <fullName>clcommon__Payment_Type__c</fullName>
    <inlineHelpText>Type of the installment</inlineHelpText>
    <label>Payment Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Equal Monthly Installments</fullName>
                <default>true</default>
                <label>Equal Monthly Installments</label>
            </value>
            <value>
                <fullName>Equated Principal</fullName>
            </value>
            <value>
                <fullName>Interest Only</fullName>
            </value>
            <value>
                <fullName>Principal Only</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/clcommon__Repayment_Plan__c/fields/clcommon__Sequence_Number__c.field-meta.xml
<CustomField>
    <fullName>clcommon__Sequence_Number__c</fullName>
    <inlineHelpText>A number used to order repayment plans as needed</inlineHelpText>
    <label>Sequence Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/clcommon__Repayment_Plan__c/fields/loan__Loan_Account__c.field-meta.xml
<CustomField>
    <fullName>loan__Loan_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Reference to CL Contract to which this repayment plan is applicable</description>
    <inlineHelpText>Reference to CL Contract to which this repayment plan is applicable</inlineHelpText>
    <label>CL Contract</label>
    <referenceTo>loan__Loan_Account__c</referenceTo>
    <relationshipLabel>Flexible Repayment Plan</relationshipLabel>
    <relationshipName>Repayment_Plan</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/lead_guid__c.field-meta.xml
<CustomField>
    <fullName>lead_guid__c</fullName>
    <externalId>true</externalId>
    <label>lead_guid</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/loan__Loan_Account__c.object-meta.xml
<CustomObject>
    <description>Lending Account</description>
    <label>CL Contract</label>
    <nameField>
        <displayFormat>LAI-{00000000}</displayFormat>
        <label>CL Contract ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CL Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/loan__Loan_Account__c/fields/CPD_Date__c.field-meta.xml
<CustomField>
    <fullName>CPD_Date__c</fullName>
    <description>The payment Date provided by the Member to change the Due date.</description>
    <label>CPD Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/CPD_Expire_Date__c.field-meta.xml
<CustomField>
    <fullName>CPD_Expire_Date__c</fullName>
    <description>date when the CPD reason hold expires and CPD can be performed via API</description>
    <label>CPD Expire Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/CPD_Reason__c.field-meta.xml
<CustomField>
    <fullName>CPD_Reason__c</fullName>
    <description>If CPD triggered from front end, this value is set with reason and to restrict CPD performed via API</description>
    <label>CPD Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Changed Payment Date</fullName>
            </value>
            <value>
                <fullName>Past Due or Loan Mod</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Changed via Member Portal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/CPD_Unpaid_Due_Date__c.field-meta.xml
<CustomField>
    <fullName>CPD_Unpaid_Due_Date__c</fullName>
    <label>CPD - Unpaid Due Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/Future_Bill_Pending__c.field-meta.xml
<CustomField>
    <fullName>Future_Bill_Pending__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Future Bill Pending</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/lead_Guid__c.field-meta.xml
<CustomField>
    <fullName>lead_Guid__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>lead_Guid</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/loan__Due_Day__c.field-meta.xml
<CustomField>
    <fullName>loan__Due_Day__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Due Day for the loan account.</description>
    <inlineHelpText>The day on which the loan payment is due.</inlineHelpText>
    <label>Current Due Day</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/loan__Frequency_of_Loan_Payment__c.field-meta.xml
<CustomField>
    <fullName>loan__Frequency_of_Loan_Payment__c</fullName>
    <inlineHelpText>This decides the Payment Frequency, below are the supported ones:
Daily
Weekly
Bi-weekly
Semi-Monthly
Monthly
Bi-Monthly  
Quarterly
Semi-Annual
Annual 
Single-Payment</inlineHelpText>
    <label>Payment Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Daily</fullName>
            </value>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>Bi-weekly</fullName>
            </value>
            <value>
                <fullName>Semi-Monthly</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
                <default>true</default>
                <label>Monthly</label>
            </value>
            <value>
                <fullName>Bi-Monthly</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Semi-Annual</fullName>
            </value>
            <value>
                <fullName>Annual</fullName>
            </value>
            <value>
                <fullName>Single-Payment</fullName>
            </value>
            <value>
                <fullName>Semi-Monthly-PD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/loan__Interest_Rate__c.field-meta.xml
<CustomField>
    <fullName>loan__Interest_Rate__c</fullName>
    <description>Interest Rate</description>
    <inlineHelpText>Rate of Interest for the loan.</inlineHelpText>
    <label>Current Interest Rate</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/loan__Last_Installment_Date__c.field-meta.xml
<CustomField>
    <fullName>loan__Last_Installment_Date__c</fullName>
    <description>Maturity Date of Loan account</description>
    <inlineHelpText>Maturity date as per contract.</inlineHelpText>
    <label>Maturity Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/loan__Maturity_Date_Current__c.field-meta.xml
<CustomField>
    <fullName>loan__Maturity_Date_Current__c</fullName>
    <inlineHelpText>This is the date on which the the loan matures</inlineHelpText>
    <label>Current Maturity Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/loan__Next_Installment_Date__c.field-meta.xml
<CustomField>
    <fullName>loan__Next_Installment_Date__c</fullName>
    <description>Date of the next installment</description>
    <inlineHelpText>Date of the Next Due</inlineHelpText>
    <label>Next Due Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/loan__Pmt_Amt_Cur__c.field-meta.xml
<CustomField>
    <fullName>loan__Pmt_Amt_Cur__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Current Payment Amount</description>
    <inlineHelpText>This is the current installment amount that needs to be paid.</inlineHelpText>
    <label>Current Payment Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/loan__Term_Cur__c.field-meta.xml
<CustomField>
    <fullName>loan__Term_Cur__c</fullName>
    <description>Current Term</description>
    <inlineHelpText>Current loan account term.</inlineHelpText>
    <label>Current Term</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/loan__Loan_account_Due_Details__c/loan__Loan_account_Due_Details__c.object-meta.xml
<CustomObject>
    <description>Invoices/bills for customer loans.</description>
    <label>Bills</label>
    <nameField>
        <displayFormat>PCN-{0000000000}</displayFormat>
        <label>Due Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bills</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/loan__Loan_account_Due_Details__c/fields/loan__DD_Primary_Flag__c.field-meta.xml
<CustomField>
    <fullName>loan__DD_Primary_Flag__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Primary</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/loan__Loan_account_Due_Details__c/fields/loan__Due_Date__c.field-meta.xml
<CustomField>
    <fullName>loan__Due_Date__c</fullName>
    <description>Due date of the due.</description>
    <inlineHelpText>Due Date of the Due</inlineHelpText>
    <label>Due Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/loan__Loan_account_Due_Details__c/fields/loan__Loan_Account__c.field-meta.xml
<CustomField>
    <fullName>loan__Loan_Account__c</fullName>
    <label>Loan Account</label>
    <referenceTo>loan__Loan_Account__c</referenceTo>
    <relationshipName>Dues_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/loan__Loan_account_Due_Details__c/fields/loan__Payment_Amt__c.field-meta.xml
<CustomField>
    <fullName>loan__Payment_Amt__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Payment Amount.</description>
    <label>Payment Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/loan__Loan_account_Due_Details__c/fields/loan__Payment_Satisfied__c.field-meta.xml
<CustomField>
    <fullName>loan__Payment_Satisfied__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Payment Satisfied</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/loan__Repayment_Schedule__c/loan__Repayment_Schedule__c.object-meta.xml
<CustomObject>
    <description>Amortization schedule is also called as Repayment schedule.</description>
    <label>Amortization Schedule</label>
    <nameField>
        <displayFormat>RSI-{0000000000}</displayFormat>
        <label>Repayment Schedule ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Amortization Schedule</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/loan__Repayment_Schedule__c/fields/loan__Due_Date__c.field-meta.xml
<CustomField>
    <fullName>loan__Due_Date__c</fullName>
    <description>Due date</description>
    <inlineHelpText>The date on which the loan payment is due.</inlineHelpText>
    <label>Due Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/loan__Repayment_Schedule__c/fields/loan__Is_Archived__c.field-meta.xml
<CustomField>
    <fullName>loan__Is_Archived__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates if a new repayment schedule for this loan account has been generated and this one is archived for reference.</description>
    <inlineHelpText>Indicates if a new repayment schedule for this loan account has been generated and this one is archived for reference.</inlineHelpText>
    <label>Is Archived</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/loan__Repayment_Schedule__c/fields/loan__Loan_Account__c.field-meta.xml
<CustomField>
    <fullName>loan__Loan_Account__c</fullName>
    <description>Repayment Schedule of which Loan account</description>
    <inlineHelpText>Repayment Schedule of which Loan account</inlineHelpText>
    <label>Loan Account</label>
    <referenceTo>loan__Loan_Account__c</referenceTo>
    <relationshipName>Repayment_Schedule</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/WebServiceChangePaymentDate.cls
/* ****************Modification History*****************************************************************
 * 
 * Modified by      		Date        JIRA number
 * 1.   Pallavi/Neha      2020/12/11  CRM-1056 CPD issue/Reverting issue (short-term fix) - Case #02430069 
 * 2.   Shakul            2022/07/18    LSP-864(Mapping lastPaymentDate to Active Maturity Date instead of Maturity Date)
 ******************Modification History*****************************************************************/
@RestResource(urlMapping='/ChangePaymentDate/*') 
global with sharing class WebServiceChangePaymentDate {
    
    public static loan__Loan_Account__c LAtobeUpdated;
    public static String CPDNote;
    
    global class Response {
        public String status;
        public String errorCode;
        public String errorMessage;
        public String successMessage;
        public Response(){
            errorCode = PayoffConstants.ERROR;
            status = PayoffConstants.FAIL;
        }
    }

    @HttpPost
    global static Response ChangePaymentDate() {

        Response res = new Response();
        RestRequest req = RestContext.request;
        Map<String, Object> reqParams = (Map<String, Object>)JSON.deserializeUntyped(req.requestBody.toString());
        String leadId;
        Date paymentDate;
        Date CPDExpireDate;
        String CPDReason;
        
        loan.GlobalLoanUtilFacade util = new loan.GlobalLoanUtilFacade();
        Date systemDate = util.getCurrentSystemDate();
        Date transactionDate = systemDate;
        /*CRM-1056*/
        if(test.isRunningTest())
            systemDate = System.today();
        /*CRM-1056*/

        Date repaymentStartDate;
        Date secondPaymentDate = null;
        Date lastPaymentDate;
        Integer noOfInstallments = null;
        Integer interestOnlyPeriod = 0;
        Decimal interestRate;
        String frequencyOfPayment;
        Boolean maintainDelinquency = true;
        Boolean actualInterestOnlyPayments = False;
        Integer amortizationTerm;
        Integer dueDay;
        String stepUpOption = null;
        Decimal interestOnlyPaymentAmt = 0;
        Boolean regenerateInvAmzSchedule = True;
        Date generatedBillDate;
        Boolean checkFutureBillFlag = False;

        try {
            
            if (reqParams.get('Id') != null) {
                leadId = (String)reqParams.get('Id');
            }
            if (reqParams.get('paymentDate') != null) {
                paymentDate = Date.valueOf((String)reqParams.get('paymentDate'));
            }
            if (reqParams.get('CPDReason') != null) {
                CPDReason = (String)reqParams.get('CPDReason');
            }
            if (reqParams.get('expiryDate') != null) {
                CPDExpireDate = Date.valueOf((String)reqParams.get('expiryDate'));
            }
            if (reqParams.get('CPDNote') != null) {
                CPDNote = (String)reqParams.get('CPDNote');
            }
            
            
            System.debug('sfaf'+leadId);
            LAtobeUpdated = [Select id,name,
                             loan__Last_Installment_Date__c,
                             loan__Interest_Rate__c,
                             loan__Frequency_of_Loan_Payment__c,
                             loan__Pmt_Amt_Cur__c,
                             loan__Next_Installment_Date__c,
                             loan__Maturity_Date_Current__c,
                             loan__Term_Cur__c,
                             (Select id,name,
                              loan__Is_Archived__c,
                              loan__Due_Date__c
                              from loan__Repayment_Schedule__r),
                             (select id,name,loan__Due_Date__c
                             from loan__Dues_Details__r where 
                             loan__Payment_Satisfied__c  = false 
                             and loan__DD_Primary_Flag__c = true  
                             // and loan__Payment_Amt__c = 0.00
                             order by loan__Due_Date__c DESC limit 1),
                             (select id,name from loan__Repayment_Plan__r),
                             CPD_Reason__c,
                             CPD_Expire_Date__c
                             from loan__Loan_Account__c
                             where lead_guid__c =: leadId limit 1];

            System.debug('Name**'+LAtobeUpdated.name);

            if(LAtobeUpdated != null && LAtobeUpdated.CPD_Expire_Date__c != null && LAtobeUpdated.CPD_Expire_Date__c > systemDate) {
                res.errorCode = 'INVALID_INPUT';
                res.errorMessage = 'This Borrower is not eligible for CPD till ' + LAtobeUpdated.CPD_Expire_Date__c;
                res.status = peer.Constants.ERROR;
                return res;

            } else if (LAtobeUpdated == null ) {
                res.errorCode = 'INVALID_INPUT';
                res.errorMessage = 'Please check the Lead Id as there are no contracts for the provided leadId:'+leadId;
                res.status = peer.Constants.ERROR;
                return res;
            }
            
      if(!LAtobeUpdated.loan__Dues_Details__r.isempty() || LAtobeUpdated.loan__Dues_Details__r.size()>0)  //pallavi(LOS-191)
              generatedBillDate = LAtobeUpdated.loan__Dues_Details__r[0].loan__Due_Date__c;
            System.debug(logginglevel.error,'Next bill present : DUE Date :: '+generatedBillDate);
            System.debug(logginglevel.error,'Payment Date :: '+paymentDate);
                       
            repaymentStartDate = Date.newInstance(paymentDate.year(),paymentDate.month(),paymentDate.day());
  
            lastPaymentDate = LAtobeUpdated.loan__Maturity_Date_Current__c; //LSP-864
            System.debug(logginglevel.error,'lastPaymentDate'+lastPaymentDate);
            interestRate = LAtobeUpdated.loan__Interest_Rate__c;
            frequencyOfPayment = LAtobeUpdated.loan__Frequency_of_Loan_Payment__c;
            dueDay = paymentDate.day();
            System.debug(logginglevel.error,'DUEDAY'+dueDay);

            Integer terms = getRemainingTerm();

            if(LAtobeUpdated.loan__Repayment_Plan__r != null && LAtobeUpdated.loan__Repayment_Plan__r.size() != 0) {

                delete LAtobeUpdated.loan__Repayment_Plan__r;

            }

            List<clcommon__Repayment_Plan__c> repaymentPlan = new List<clcommon__Repayment_Plan__c>();
            
            if(generatedBillDate != null && generatedBillDate > systemDate){  //pallavi(LOS-191)
            
                System.debug(logginglevel.error,'In IF block : repaymentplan'); 
            
                checkFutureBillFlag = True;
                LAtobeUpdated.CPD_Unpaid_Due_Date__c = generatedBillDate;
                
                res.successMessage ='Change Payment Date Request Submitted Successfully.!!';
                res.status = peer.Constants.SUCCESS;
                          
            }else{
            
                System.debug(logginglevel.error,'In ELSE block : repaymentplan');
            
                repaymentPlan.add(new clcommon__Repayment_Plan__c(clcommon__Sequence_Number__c = 1,
                                                                  clcommon__Payment_Type__c = 'Equal Monthly Installments',
                                                                  clcommon__Payment_Amount__c = LAtobeUpdated.loan__Pmt_Amt_Cur__c,
                                                                  clcommon__Payment_Start_Date__c = Date.newInstance(paymentDate.year(),paymentDate.month(),paymentDate.day()),
                                                                  clcommon__Number_Of_Payments__c = terms,
                                                                  clcommon__Due_Day__c = paymentDate.day(),
                                                                  clcommon__Effective_Date__c = systemDate,
                                                                  loan__Loan_Account__c = LAtobeUpdated.id));            
            //}
            
            insert repaymentPlan;
            System.Debug('repaymentStartDate***' + repaymentStartDate);
			 loan.LoanRescheduleParameters rescheduleParams = new loan.LoanRescheduleParameters(LAtobeUpdated.id,
                                                                                               transactionDate,
                                                                                               repaymentStartDate,
                                                                                               secondPaymentDate,
                                                                                               lastPaymentDate,
                                                                                               noOfInstallments,
                                                                                               interestOnlyPeriod,
                                                                                               interestRate,
                                                                                               frequencyOfPayment,
                                                                                               maintainDelinquency,
                                                                                               actualInterestOnlyPayments,
                                                                                               amortizationTerm,
                                                                                               dueDay,
                                                                                               stepUpOption,
                                                                                               interestOnlyPaymentAmt,
                                                                                               regenerateInvAmzSchedule);

            List<loan.LoanRescheduleParameters.ProposedRepaymentPlan> repaymentPlanList = rescheduleParams.getRepaymentPlan();
            System.debug(logginglevel.error,'repaymentPlanList +++++'+repaymentPlanList);
            rescheduleParams.setRepaymentPlan(repaymentPlanList);

            loan.LoanActionFactory factory = new loan.LoanActionFactory();
            loan.LoanAction7 loanAction = factory.getLoanAction7API();
            System.debug(logginglevel.error,'rescheduleParams +++++'+rescheduleParams);
            loanAction.rescheduleALoan(rescheduleParams);

            res.successMessage ='Payment date upated Successfully!!';
            res.status = peer.Constants.SUCCESS;
            
            }
            
            if (LAtobeUpdated != null){
                LAtobeUpdated.CPD_Date__c = paymentDate;
                LAtobeUpdated.Future_Bill_Pending__c = checkFutureBillFlag;
                                
                /*CRM-1056*/
                if(!checkFutureBillFlag){
                    LAtobeUpdated.loan__Next_Installment_Date__c = repaymentStartDate;
                    LAtobeUpdated.loan__Due_Day__c = repaymentStartDate.day();
                }
                /*CRM-1056*/

                if (LAtobeUpdated.CPD_Expire_Date__c == null) {
                    if (CPDReason != null) { LAtobeUpdated.CPD_Reason__c = CPDReason; }
                    if (CPDExpireDate != null) {LAtobeUpdated.CPD_Expire_Date__c = CPDExpireDate; }    
                }

                update LAtobeupdated;
            }
            
            System.debug(logginglevel.error,'Checking if CPDNOte is NULL :: '+CPDNote);
            if (CPDNote != null){
                
                System.debug(logginglevel.error,'Calling insert CPDNOte');
                insertCPDNote();
            
            }

        } catch (Exception e) {
            
            res.errorCode = 'INVALID_INPUT';
            res.errorMessage = e.getMessage() +'Line Number:'+e.getLineNumber();
            System.debug(logginglevel.error,'line number'+e.getLineNumber());
            System.debug(logginglevel.error,'error stackTrace'+e.getStackTraceString());

            res.status = peer.Constants.ERROR;
            return res;
        }
        
        return res;
    }


    public static Integer getRemainingTerm() {

        Integer remainingTerm;

        if (LAtobeUpdated.loan__Next_Installment_Date__c != null && LAtobeUpdated.loan__Maturity_Date_Current__c != null) {
            remainingTerm = (Integer)(loan.DateUtil.cyclesBetween(LAtobeUpdated.loan__Next_Installment_Date__c,
                                                                  LAtobeUpdated.loan__Maturity_Date_Current__c, //loan__Last_Installment_Date__c LOS - 259. Changed by Neha.
                                                                  LAtobeUpdated.loan__Frequency_of_Loan_Payment__c));

            System.debug(logginglevel.error,'remainingTerm in IF'+remainingTerm);

        }
        /*else {
            remainingTerm = (Integer)LAtobeUpdated.loan__Term_Cur__c - 1;
           System.debug(logginglevel.error,'remainingTerm in ELSE'+remainingTerm);

           }*/

        System.debug(logginglevel.error,'remainingTerm'+remainingTerm);
        return remainingTerm;
    }
    
    public static void insertCPDNote(){
    
        Note CPDContractNote = new Note();
        CPDContractNote.ParentId = LAtobeUpdated.Id;
        CPDContractNote.Body = CPDNOte;
        CPDContractNote.Title = 'CPD Note via Member Portal';
        
        System.debug(logginglevel.error,'CPDContractNote'+CPDContractNote);
        
        insert CPDContractNote;
    
    }

}