force-app/main/default/objects/Account/fields/Address_1__c.field-meta.xml
<CustomField>
    <fullName>Address_1__c</fullName>
    <label>Address 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Address_2__c.field-meta.xml
<CustomField>
    <fullName>Address_2__c</fullName>
    <label>Address 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/cnotify__Email__c.field-meta.xml
<CustomField>
    <fullName>cnotify__Email__c</fullName>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/ZIP_Code__c.field-meta.xml
<CustomField>
    <fullName>ZIP_Code__c</fullName>
    <label>ZIP Code</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/genesis__Applications__c/genesis__Applications__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{0000000000}</displayFormat>
        <label>Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/genesis__Applications__c/fields/Lead_ID__c.field-meta.xml
<CustomField>
    <fullName>Lead_ID__c</fullName>
    <description>This is the LEAD GUID received from FE</description>
    <externalId>true</externalId>
    <label>Lead ID</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/genesis__Applications__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <description>State pulled from Account object</description>
    <formula>genesis__Account__r.State__c</formula>
    <label>State</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/loan__Bank_Account__c/loan__Bank_Account__c.object-meta.xml
<CustomObject>
    <label>Bank Account</label>
    <nameField>
        <displayFormat>BA-{00000}</displayFormat>
        <label>Bank Account Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bank Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/loan__Bank_Account__c/fields/loan__Account__c.field-meta.xml
<CustomField>
    <fullName>loan__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bank Accounts</relationshipLabel>
    <relationshipName>Bank_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/loan__Loan_Account__c.object-meta.xml
<CustomObject>
    <description>Lending Account</description>
    <label>CL Contract</label>
    <nameField>
        <displayFormat>LAI-{00000000}</displayFormat>
        <label>CL Contract ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CL Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/loan__Loan_Account__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>genesis__Applications__c</referenceTo>
    <relationshipLabel>CL Contracts</relationshipLabel>
    <relationshipName>CL_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/loan__Account__c.field-meta.xml
<CustomField>
    <fullName>loan__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Please choose a account, which will be associated as a customer on this lending account.
You can create a new account, from the lookup window by clicking on new or select the existing account from the lookup.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Loan_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/MW_WSMemberAccountUpdate.cls
@RestResource(urlMapping='/MemberAccountUpdate/*')
global with sharing class MW_WSMemberAccountUpdate {
   
     global class Response{
        public String status;
        public String errorCode;
        public String errorMessage;
        public String successMessage;
        public Response(){
            errorCode = PayoffConstants.ERROR;
            status = PayoffConstants.FAIL;
        }
    }
    
    @HttpPost
    global static Response MemberAccountUpdate()
    {
           Response res = new Response();
           RestRequest req = RestContext.request;
           Map<String, Object> reqParams = (Map<String, Object>)JSON.deserializeUntyped(req.requestBody.toString());  
           String leadId;
           String Phone;
           String Email;
           String Address1;
           String Address2;
           String City;
           String State;
           String ZIP_Code;
          
           loan__Bank_Account__c bankAccountToCreate = new loan__Bank_Account__c();
           
           try
           {
                    if (reqParams.get('leadID') != null)
                    {
                        leadId = (String)reqParams.get('leadID');
                    }
               
                    //Query cl contract to get account id
                    List< loan__Loan_Account__c> clContractListToUpdate = [Select loan__Account__c, name, Id from loan__Loan_Account__c where Application__r.Lead_ID__c =: leadId LIMIT 1 FOR UPDATE];
                    Id accountId;
                    if(clContractListToUpdate.size() > 0)
                     accountId = clContractListToUpdate[0].loan__Account__c;
                      
                    System.debug('******AccountID: '+accountId);
                  
                    List<Account> accountToUpdate = [Select id,name, Phone, cnotify__Email__c,Address_1__c,Address_2__c,State__c,City__c,ZIP_Code__c from Account where Id=: accountId LIMIT 1 FOR UPDATE];
                    //List<Account> accountToUpdate = new List<Account>();
                    if (reqParams.get('Phone') != null) 
                    {
                        Phone = (String)reqParams.get('Phone');
                        accountToUpdate[0].Phone = Phone;
                    }
                    if (reqParams.get('cnotify__Email__c') != null) 
                    {
                        Email = (String)reqParams.get('cnotify__Email__c');
                        accountToUpdate[0].cnotify__Email__c = Email;
                    }
                    if (reqParams.get('Address_1__c') != null) 
                    {
                        Address1 = (String)reqParams.get('Address_1__c');
                        accountToUpdate[0].Address_1__c = Address1;
                    }
                     if (reqParams.get('Address_2__c') != null) 
                    {
                        Address2 = (String)reqParams.get('Address_2__c');
                        accountToUpdate[0].Address_2__c = Address2;
                    }
                     if (reqParams.get('City__c') != null) 
                    {
                        City = (String)reqParams.get('City__c');
                        accountToUpdate[0].City__c = City;
                    }
                    if (reqParams.get('State__c') != null) 
                    {
                        State = (String)reqParams.get('State__c');
                        accountToUpdate[0].State__c = State;
                    }
                    if (reqParams.get('ZIP_Code__c') != null) 
                    {
                        ZIP_Code = (String)reqParams.get('ZIP_Code__c');
                        accountToUpdate[0].ZIP_Code__c = ZIP_Code;
                    }
                    
                   // accountToUpdate = accountToUpdate1;
    
                    //Update Account
                    if(accountToUpdate.size() > 0)
                      upsert accountToUpdate;
                                
                     if(accountToUpdate.size() > 0)
                     {
                         res.successMessage ='Success!!';
                         res.status = peer.Constants.SUCCESS;
                     }  
                     else
                     {
                           res.errorCode = 'INVALID_INPUT';
                           res.status = peer.Constants.ERROR;
                     }
           
           }
           catch(Exception e)
           {
               res.errorCode = 'INVALID_INPUT';
               res.errorMessage = e.getMessage() +'; Line Number: '+e.getLineNumber();
               System.debug(logginglevel.error,'line number'+e.getLineNumber());
               System.debug(logginglevel.error,'error stackTrace'+e.getStackTraceString());

               res.status = peer.Constants.ERROR;
               return res;
               
           }
          
           
           return res;
         
    }

}