force-app/main/default/objects/Account/fields/BoxFolderID__c.field-meta.xml
<CustomField>
    <fullName>BoxFolderID__c</fullName>
    <label>BoxFolderID</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/cnotify__Email__c.field-meta.xml
<CustomField>
    <fullName>cnotify__Email__c</fullName>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/loan__Investor__c.field-meta.xml
<CustomField>
    <fullName>loan__Investor__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Investor</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/peer__First_Name__c.field-meta.xml
<CustomField>
    <fullName>peer__First_Name__c</fullName>
    <label>First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/peer__Last_Name__c.field-meta.xml
<CustomField>
    <fullName>peer__Last_Name__c</fullName>
    <label>Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/ZIP_Code__c.field-meta.xml
<CustomField>
    <fullName>ZIP_Code__c</fullName>
    <label>ZIP Code</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/genesis__Applications__c/genesis__Applications__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{0000000000}</displayFormat>
        <label>Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/genesis__Applications__c/fields/Application_Start_DateV2__c.field-meta.xml
<CustomField>
    <fullName>Application_Start_DateV2__c</fullName>
    <label>Application Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/genesis__Applications__c/fields/BoxFolderID__c.field-meta.xml
<CustomField>
    <fullName>BoxFolderID__c</fullName>
    <label>BoxFolderID</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/genesis__Applications__c/fields/Employment_Status__c.field-meta.xml
<CustomField>
    <fullName>Employment_Status__c</fullName>
    <label>Employment Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Full Time</fullName>
            </value>
            <value>
                <fullName>Part Time</fullName>
            </value>
            <value>
                <fullName>Retired</fullName>
            </value>
            <value>
                <fullName>Self Employed</fullName>
            </value>
            <value>
                <fullName>Contract</fullName>
            </value>
            <value>
                <fullName>Seasonal</fullName>
            </value>
            <value>
                <fullName>Investment</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/genesis__Applications__c/fields/genesis__Account__c.field-meta.xml
<CustomField>
    <fullName>genesis__Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Applications_account</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/genesis__Applications__c/fields/genesis__Draw_Period_End_Date__c.field-meta.xml
<CustomField>
    <fullName>genesis__Draw_Period_End_Date__c</fullName>
    <label>Draw Period End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/genesis__Applications__c/fields/genesis__Due_Day__c.field-meta.xml
<CustomField>
    <fullName>genesis__Due_Day__c</fullName>
    <description>dueDay field.</description>
    <inlineHelpText>If Due Day field is null, then by default it will have Expected First Payment Date day value</inlineHelpText>
    <label>Due_Day</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/genesis__Applications__c/fields/genesis__Expected_First_Payment_Date__c.field-meta.xml
<CustomField>
    <fullName>genesis__Expected_First_Payment_Date__c</fullName>
    <label>Expected First Payment Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/genesis__Applications__c/fields/genesis__Expected_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>genesis__Expected_Start_Date__c</fullName>
    <label>Expected Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/genesis__Applications__c/fields/genesis__Funding_in_Tranches__c.field-meta.xml
<CustomField>
    <fullName>genesis__Funding_in_Tranches__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Funding in Tranches</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/genesis__Applications__c/fields/genesis__Loan_Amount__c.field-meta.xml
<CustomField>
    <fullName>genesis__Loan_Amount__c</fullName>
    <label>Loan Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/genesis__Applications__c/fields/genesis__Status__c.field-meta.xml
<CustomField>
    <fullName>genesis__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>APPROVED - APPROVED</fullName>
            </value>
            <value>
                <fullName>APPROVED - CONVERTED TO CONTRACT</fullName>
            </value>
            <value>
                <fullName>APPROVED - DOCUMENT CHECK</fullName>
            </value>
            <value>
                <fullName>NEW - CREDIT PULLED</fullName>
            </value>
            <value>
                <fullName>NEW - ENTERED</fullName>
                <default>true</default>
                <label>NEW - ENTERED</label>
            </value>
            <value>
                <fullName>NEW - IN CREDIT CHECK</fullName>
            </value>
            <value>
                <fullName>NEW - IN REVIEW</fullName>
            </value>
            <value>
                <fullName>NEW - PRICING GENERATED</fullName>
            </value>
            <value>
                <fullName>NEW - SCORECARD GENERATED</fullName>
            </value>
            <value>
                <fullName>NEW - CHECKLIST GENERATED</fullName>
            </value>
            <value>
                <fullName>NEW - VEHICLE VALUATION REQUIRED</fullName>
            </value>
            <value>
                <fullName>REJECTED</fullName>
            </value>
            <value>
                <fullName>PULL CREDIT</fullName>
            </value>
            <value>
                <fullName>Default Documents</fullName>
            </value>
            <value>
                <fullName>offer_accepted</fullName>
            </value>
            <value>
                <fullName>offer_shown</fullName>
            </value>
            <value>
                <fullName>kba_success</fullName>
            </value>
            <value>
                <fullName>kba_fail</fullName>
            </value>
            <value>
                <fullName>agent_document_verification_pending</fullName>
            </value>
            <value>
                <fullName>agent_verification_pending</fullName>
            </value>
            <value>
                <fullName>agent_verified</fullName>
            </value>
            <value>
                <fullName>docusign_loan_docs_sent</fullName>
            </value>
            <value>
                <fullName>docusign_loan_docs_complete</fullName>
            </value>
            <value>
                <fullName>pre_funding</fullName>
            </value>
            <value>
                <fullName>Approved for funding</fullName>
            </value>
            <value>
                <fullName>funded</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Stacker_Check_Passed</fullName>
            </value>
            <value>
                <fullName>Redecision_Required</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/genesis__Applications__c/fields/Lead_ID__c.field-meta.xml
<CustomField>
    <fullName>Lead_ID__c</fullName>
    <description>This is the LEAD GUID received from FE</description>
    <externalId>true</externalId>
    <label>Lead ID</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/genesis__Applications__c/fields/LeadGUID_XX_BoxFolderID__c.field-meta.xml
<CustomField>
    <fullName>LeadGUID_XX_BoxFolderID__c</fullName>
    <description>This field will contain the box folder id for the parent folder of the lead guid which will be the first 2 digits of the Lead Guid.</description>
    <label>LeadGUID_XX_BoxFolderID</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/genesis__Applications__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <description>State pulled from Account object</description>
    <formula>genesis__Account__r.State__c</formula>
    <label>State</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/MW_UpdateBoxFolderTest.cls
@isTest
private class MW_UpdateBoxFolderTest {

        static testmethod void MW_UpdateBoxFolder1()
        {

           test.startTest();
           Account acc = new Account(
                Name = 'Test',
                loan__Investor__c=False,
                cnotify__Email__c = 'no-reply@testorganization.com',
                peer__First_Name__c = 'TestFName',
                peer__Last_Name__c='TestLName',
                City__c='TestCity',
                State__c='TestState',
                ZIP_Code__c='123456'
            );
            Insert acc;

            genesis__Applications__c app = new genesis__Applications__c(
            genesis__Due_Day__c = 20,
            genesis__Expected_First_Payment_Date__c = system.Today(),
            genesis__Expected_Start_Date__c = system.Today(),
            genesis__Funding_in_Tranches__c = true,
            genesis__Account__c = acc.Id,
            Application_Start_DateV2__c = system.Today(),
            genesis__Status__c = 'REJECTED',
            genesis__Draw_Period_End_Date__c = system.Today(),
            Employment_Status__c = 'Full Time',
            genesis__Loan_Amount__c=1000,
            BoxFolderID__c='123321',
            Lead_ID__c='123123123',
            LeadGUID_XX_BoxFolderID__c =null
            );
            insert app;

            Database.executeBatch(new MW_UpdateBoxFolder1(), 1);

            Test.stopTest();
        }

         static testmethod void MW_UpdateBoxFolder2()
        {

            test.startTest();
            Account acc = new Account(
                Name = 'Test',
                loan__Investor__c=False,
                cnotify__Email__c = 'no-reply@testorganization.com',
                peer__First_Name__c = 'TestFName',
                peer__Last_Name__c='TestLName',
                City__c='TestCity',
                State__c='TestState',
                ZIP_Code__c='123456'
            );
            Insert acc;

            genesis__Applications__c app = new genesis__Applications__c(
            genesis__Due_Day__c = 20,
            genesis__Expected_First_Payment_Date__c = system.Today(),
            genesis__Expected_Start_Date__c = system.Today(),
            genesis__Funding_in_Tranches__c = true,
            genesis__Account__c = acc.Id,
            Application_Start_DateV2__c = system.Today(),
            genesis__Status__c = 'REJECTED',
            genesis__Draw_Period_End_Date__c = system.Today(),
            Employment_Status__c = 'Full Time',
            genesis__Loan_Amount__c=1000,
            BoxFolderID__c='123321',
            Lead_ID__c='123123123',
            LeadGUID_XX_BoxFolderID__c='123123'
            );
            insert app;

            Database.executeBatch(new MW_UpdateBoxFolder2(), 1);

           Test.stopTest();
        }
}