force-app/main/default/objects/Account/fields/cnotify__Email__c.field-meta.xml
<CustomField>
    <fullName>cnotify__Email__c</fullName>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/loan__Investor__c.field-meta.xml
<CustomField>
    <fullName>loan__Investor__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Investor</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CL_Document__c/CL_Document__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>CL_Generated Documents Names</description>
    <label>CL Document</label>
</CustomObject>

force-app/main/default/objects/CL_Document__c/fields/Doc1__c.field-meta.xml
<CustomField>
    <fullName>Doc1__c</fullName>
    <label>Doc1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CL_Document__c/fields/Doc2__c.field-meta.xml
<CustomField>
    <fullName>Doc2__c</fullName>
    <inlineHelpText>TIL Document</inlineHelpText>
    <label>Doc2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/clcommon__CL_Product__c/clcommon__CL_Product__c.object-meta.xml
<CustomObject>
    <label>CL Product</label>
    <nameField>
        <displayFormat>PRO-{00000000}</displayFormat>
        <label>CL Product Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CL Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/clcommon__CL_Product__c/fields/clcommon__Product_Name__c.field-meta.xml
<CustomField>
    <fullName>clcommon__Product_Name__c</fullName>
    <label>Product Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/clcommon__CL_Product__c/fields/loan__Lending_Product__c.field-meta.xml
<CustomField>
    <fullName>loan__Lending_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lending Product</label>
    <referenceTo>loan__Loan_Product__c</referenceTo>
    <relationshipLabel>CL Products</relationshipLabel>
    <relationshipName>CL_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/genesis__Application_Document_Category__c/genesis__Application_Document_Category__c.object-meta.xml
<CustomObject>
    <label>Application Document Category</label>
    <nameField>
        <label>Application Document Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application Document Category</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/genesis__Application_Document_Category__c/fields/genesis__Document_Category__c.field-meta.xml
<CustomField>
    <fullName>genesis__Document_Category__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Document Category</label>
    <referenceTo>genesis__Document_Category__c</referenceTo>
    <relationshipLabel>Application Document Category</relationshipLabel>
    <relationshipName>Application_Document_Category</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/genesis__Application_Document_Category__c/fields/genesis__Status__c.field-meta.xml
<CustomField>
    <fullName>genesis__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>OPEN</fullName>
                <default>true</default>
                <label>OPEN</label>
            </value>
            <value>
                <fullName>SUBMITTED</fullName>
            </value>
            <value>
                <fullName>CLEARED</fullName>
            </value>
            <value>
                <fullName>REJECTED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/genesis__Applications__c/genesis__Applications__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{0000000000}</displayFormat>
        <label>Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/genesis__Applications__c/fields/genesis__Company__c.field-meta.xml
<CustomField>
    <fullName>genesis__Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Company</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>genesis__Company__c.genesis__Enabled_Flag__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>genesis__Company__c</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/genesis__Applications__c/fields/genesis__Loan_Amount__c.field-meta.xml
<CustomField>
    <fullName>genesis__Loan_Amount__c</fullName>
    <label>Loan Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/genesis__Applications__c/fields/genesis__Product_Type__c.field-meta.xml
<CustomField>
    <fullName>genesis__Product_Type__c</fullName>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>LEASE</fullName>
                <default>true</default>
                <label>LEASE</label>
            </value>
            <value>
                <fullName>LOAN</fullName>
            </value>
            <value>
                <fullName>LINE OF CREDIT</fullName>
            </value>
            <value>
                <fullName>PACKAGE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/genesis__Document_Category__c/genesis__Document_Category__c.object-meta.xml
<CustomObject>
    <label>Document Category</label>
    <nameField>
        <displayFormat>DC-{00000000}</displayFormat>
        <label>Document Category Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Document Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/genesis__Document_Category__c/fields/genesis__Applicable_For__c.field-meta.xml
<CustomField>
    <fullName>genesis__Applicable_For__c</fullName>
    <label>Applicable For</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CONTRACT</fullName>
            </value>
            <value>
                <fullName>PARTY</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/genesis__Document_Category__c/fields/genesis__Responsible_Party_Type__c.field-meta.xml
<CustomField>
    <fullName>genesis__Responsible_Party_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Responsible Party Type</label>
    <referenceTo>clcommon__Party_Type__c</referenceTo>
    <relationshipLabel>Document Categories</relationshipLabel>
    <relationshipName>Document_Categories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/loan__Fee__c/loan__Fee__c.object-meta.xml
<CustomObject>
    <description>Fee</description>
    <label>Fee</label>
    <nameField>
        <label>Fee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/loan__Fee__c/fields/loan__Currency__c.field-meta.xml
<CustomField>
    <fullName>loan__Currency__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Currency</description>
    <inlineHelpText>Currency</inlineHelpText>
    <label>Currency</label>
    <referenceTo>loan__Currency__c</referenceTo>
    <relationshipLabel>Fees</relationshipLabel>
    <relationshipName>Fees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/loan__Fee_Junction__c/loan__Fee_Junction__c.object-meta.xml
<CustomObject>
    <label>Fee Set/Fee</label>
    <nameField>
        <displayFormat>FJIP-{0000000000}</displayFormat>
        <label>Fee Junction ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fee Set/Fee</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/loan__Fee_Junction__c/fields/loan__Fee__c.field-meta.xml
<CustomField>
    <fullName>loan__Fee__c</fullName>
    <label>Fee</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>loan__Fee__c.loan__Time_of_charge__c</field>
            <operation>notEqual</operation>
            <value>Pre-Paid Fees</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>loan__Fee__c</referenceTo>
    <relationshipLabel>Fee Set/Fee</relationshipLabel>
    <relationshipName>Fee_Junction</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/loan__Fee_Junction__c/fields/loan__Fee_Set__c.field-meta.xml
<CustomField>
    <fullName>loan__Fee_Set__c</fullName>
    <label>Fee Set</label>
    <referenceTo>loan__Fee_Set__c</referenceTo>
    <relationshipName>Fee_Junction</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Product__c/loan__Loan_Product__c.object-meta.xml
<CustomObject>
    <description>Lending Product Definition1</description>
    <label>Lending Product</label>
    <nameField>
        <label>Loan Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lending Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/loan__Loan_Product__c/fields/loan__Currency__c.field-meta.xml
<CustomField>
    <fullName>loan__Currency__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Currency</description>
    <inlineHelpText>Currency</inlineHelpText>
    <label>Currency</label>
    <referenceTo>loan__Currency__c</referenceTo>
    <relationshipName>Loan_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Product__c/fields/loan__Fee_Set__c.field-meta.xml
<CustomField>
    <fullName>loan__Fee_Set__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Fee Set</description>
    <inlineHelpText>Fee set contains the details of all the fees associated with the loan.</inlineHelpText>
    <label>Fee Set</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Selected Fee Set&apos;s category must be of type &apos;Loan&apos; and it should include at least one fee.</errorMessage>
        <filterItems>
            <field>loan__Fee_Set__c.loan__Fee_Set_Category__c</field>
            <operation>equals</operation>
            <value>Loan</value>
        </filterItems>
        <filterItems>
            <field>loan__Fee_Set__c.loan__Number_of_Fees__c</field>
            <operation>notEqual</operation>
            <value>0</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>loan__Fee_Set__c</referenceTo>
    <relationshipName>Loan_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TestGenerateAppDocCategory.cls
@isTest
public class TestGenerateAppDocCategory{
    public static testMethod void  testOne() {
        CL_Document__c cs = new CL_Document__c();
        cs.Doc1__c = 'Credit';
        cs.Doc2__c = 'Til';
        insert cs;
        Test.startTest();
        //Party Type insert
        clcommon__Party_Type__c pt = new clcommon__Party_Type__c();
        pt.name = 'Borrower';
        insert pt;
         
        //Document category
        genesis__Document_Category__c dc = new genesis__Document_Category__c();
        dc.genesis__Responsible_Party_Type__c = pt.id;
        dc.genesis__Applicable_For__c = 'PARTY';
        insert dc;
        
         loan.TestHelper.createSeedDataForTesting();
        loan__Currency__c curr = loan.TestHelper.createCurrency();
        
        //Dummy GLAccount
        loan__MF_Account__c dummyAccount = loan.TestHelper.createMFAccount('XXXAccountForTest','10000 - ASSETS');
        
        //Dummy Office insert
        loan__Office_Name__c dummyOffice = loan.TestHelper.createOffice();
        
        //Create a Fee Set
        loan__Fee__c dummyFee = loan.TestHelper.createFee(curr);                                    
        loan__Fee_Set__c dummyFeeSet = loan.TestHelper.createFeeSet();
        loan__Fee_Junction__c dummyFeeJunction = loan.TestHelper.createFeeJunction(dummyFee,dummyFeeSet);
        
        //Creating Conpany
        genesis__Company__c comp = genesis.TestHelper.createCompany(); 
        comp.Name = 'payoff';
        update comp;
        
        //creating lending product
        loan__Loan_Product__c dummyLP = loan.TestHelper.createLoanProduct(dummyOffice, dummyAccount, curr, dummyFeeSet);
        
        //creating CL Product
        clcommon__CL_Product__c pr = new clcommon__CL_Product__c();
        pr.loan__Lending_Product__c = dummyLp.id;
        pr.clcommon__Product_Name__c = 'P1';
        insert pr; 
        
        Account account_Obj = new Account(
            Name = 'Test',
            loan__Investor__c=False,
            cnotify__Email__c = 'no-reply@testorganization.com'
        );
        Insert account_Obj;
         
        //Create Application
        genesis__applications__c application = new genesis__applications__c();
        application.genesis__Product_Type__c = 'LOAN';
        application.genesis__Loan_Amount__c = 6700;
        application.genesis__status__c = 'NEW - ENTERED';
        application.genesis__Term__c = 12;
        application.genesis__Payment_Frequency__c = 'MONTHLY';
        application.genesis__Interest_Rate__c = 10;
        application.genesis__Days_Convention__c = 'ACTUAL/ACTUAL';
        application.genesis__Expected_Start_Date__c = system.today();
        application.genesis__Expected_First_Payment_Date__c = system.today().addDays(60);
        application.genesis__Expected_Close_Date__c = system.today().addDays(30);
        application.genesis__Interest_Calculation_Method__c = 'Declining Balance';
        application.genesis__Interest_Only_Period__c = 0;
        application.genesis__Interest_Rate__c = 100;
        application.genesis__Account__c = account_Obj.Id;
        application.genesis__Total_Estimated_Interest__c=500;
        application.genesis__Valid_Pricing_Flag__c=false;
        application.genesis__Probability__c=100.00;
        application.genesis__Payment_Amount__c=523.80;
        application.genesis__Company__c = comp.id;
        application.genesis__CL_Product__c = pr.id;
        insert application; 
        System.debug('=====Application ID in test class===='+application.id);
         
        //Application document category 
        genesis__Application_Document_Category__c adc = new genesis__Application_Document_Category__c();
        adc.name = 'Promissory Category';
        adc.genesis__Active__c = true;
        adc.genesis__Document_Category__c =  dc.id;
        adc.genesis__Application__c = application.id;
        insert adc;
        
        string appid = application.id;
        appid = appid.substring(0,15);
        
        
        Attachment attach=new Attachment();     
        attach.Name='Promissory Unit'+appid+'.Test';
        Blob bodyBlob=Blob.valueOf('Unit Test Attachment Body');
        attach.body=bodyBlob;
        attach.parentId=application.id;
        insert attach;
        
        //AppDocCatAttachmentJunction 
        genesis__AppDocCatAttachmentJunction__c adcj = new genesis__AppDocCatAttachmentJunction__c();
        adcj.genesis__Application_Document_Category__c = adc.id;
        adcj.genesis__AttachmentId__c = attach.id;
        insert adcj;
        
        
        
        GenerateAppDocCategory.createDocumentCategory(application.id);
        
        Test.stopTest();
    }
    
    public static testMethod void  testTwo() {
        CL_Document__c cs = new CL_Document__c();
        cs.Doc1__c = 'Credit';
        cs.Doc2__c = 'Til';
        insert cs;
        Test.startTest();
        //Party Type insert
        clcommon__Party_Type__c pt = new clcommon__Party_Type__c();
        pt.name = 'Borrower';
        insert pt;
         
        //Document category
        genesis__Document_Category__c dc = new genesis__Document_Category__c();
        dc.genesis__Responsible_Party_Type__c = pt.id;
        dc.genesis__Applicable_For__c = 'PARTY';
        insert dc;
        
         loan.TestHelper.createSeedDataForTesting();
        loan__Currency__c curr = loan.TestHelper.createCurrency();
        
        //Dummy GLAccount
        loan__MF_Account__c dummyAccount = loan.TestHelper.createMFAccount('XXXAccountForTest','10000 - ASSETS');
        
        //Dummy Office insert
        loan__Office_Name__c dummyOffice = loan.TestHelper.createOffice();
        
        //Create a Fee Set
        loan__Fee__c dummyFee = loan.TestHelper.createFee(curr);                                    
        loan__Fee_Set__c dummyFeeSet = loan.TestHelper.createFeeSet();
        loan__Fee_Junction__c dummyFeeJunction = loan.TestHelper.createFeeJunction(dummyFee,dummyFeeSet);
        
        //Creating Conpany
        genesis__Company__c comp = genesis.TestHelper.createCompany(); 
        comp.Name = 'payoff';
        update comp;
        
        //creating lending product
        loan__Loan_Product__c dummyLP = loan.TestHelper.createLoanProduct(dummyOffice, dummyAccount, curr, dummyFeeSet);
        
        //creating CL Product
        clcommon__CL_Product__c pr = new clcommon__CL_Product__c();
        pr.loan__Lending_Product__c = dummyLp.id;
        pr.clcommon__Product_Name__c = 'P1';
        insert pr; 
        
        Account account_Obj = new Account(
            Name = 'Test',
            loan__Investor__c=False,
            cnotify__Email__c = 'no-reply@testorganization.com'
        );
        Insert account_Obj;
         
        //Create Application
        genesis__applications__c application = new genesis__applications__c();
        application.genesis__Product_Type__c = 'LOAN';
        application.genesis__Loan_Amount__c = 6700;
        application.genesis__status__c = 'NEW - ENTERED';
        application.genesis__Term__c = 12;
        application.genesis__Payment_Frequency__c = 'MONTHLY';
        application.genesis__Interest_Rate__c = 10;
        application.genesis__Days_Convention__c = 'ACTUAL/ACTUAL';
        application.genesis__Expected_Start_Date__c = system.today();
        application.genesis__Expected_First_Payment_Date__c = system.today().addDays(60);
        application.genesis__Expected_Close_Date__c = system.today().addDays(30);
        application.genesis__Interest_Calculation_Method__c = 'Declining Balance';
        application.genesis__Interest_Only_Period__c = 0;
        application.genesis__Account__c = account_Obj.Id;
        application.genesis__Interest_Rate__c = 100;
        application.genesis__Total_Estimated_Interest__c=500;
        application.genesis__Valid_Pricing_Flag__c=false;
        application.genesis__Probability__c=100.00;
        application.genesis__Payment_Amount__c=523.80;
        application.genesis__Company__c = comp.id;
        application.genesis__CL_Product__c = pr.id;
        insert application; 
        System.debug('=====Application ID in test class===='+application.id);
         
        //Application document category 
        genesis__Application_Document_Category__c adc = new genesis__Application_Document_Category__c();
        adc.name = 'Promissory Category';
        adc.genesis__Active__c = true;
        adc.genesis__Document_Category__c =  dc.id;
        adc.genesis__Application__c = application.id;
        insert adc;
        
        string appid = application.id;
        appid = appid.substring(0,15);
        
        
        Attachment attach=new Attachment();     
        attach.Name='Promissory Unit'+appid+'.Test';
        Blob bodyBlob=Blob.valueOf('Unit Test Attachment Body');
        attach.body=bodyBlob;
        attach.parentId=application.id;
        insert attach;
        
        //AppDocCatAttachmentJunction 
        genesis__AppDocCatAttachmentJunction__c adcj = new genesis__AppDocCatAttachmentJunction__c();
        adcj.genesis__Application_Document_Category__c = adc.id;
        adcj.genesis__AttachmentId__c = attach.id;
        insert adcj;
        
        
        
        //GenerateAppDocCategory.createDocumentCategory(application.id);
        try{
            GenerateAppDocCategory.createDocumentCategory('01p2F000000GgKu');
        }
        catch(exception e){}
        Test.stopTest();
    }
}