force-app/main/default/objects/Account/fields/cnotify__Email__c.field-meta.xml
<CustomField>
    <fullName>cnotify__Email__c</fullName>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/loan__Batch_Process_Log__c/loan__Batch_Process_Log__c.object-meta.xml
<CustomObject>
    <label>Batch Process Log</label>
    <nameField>
        <label>Apex Batch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Batch Process Log</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/loan__Batch_Process_Log__c/fields/loan__Message__c.field-meta.xml
<CustomField>
    <fullName>loan__Message__c</fullName>
    <label>Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/loan__Batch_Process_Log__c/fields/loan__Time__c.field-meta.xml
<CustomField>
    <fullName>loan__Time__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <label>Time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/loan__Batch_Process_Log__c/fields/loan__Type__c.field-meta.xml
<CustomField>
    <fullName>loan__Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Exception</fullName>
            </value>
            <value>
                <fullName>Warning</fullName>
            </value>
            <value>
                <fullName>Info</fullName>
            </value>
            <value>
                <fullName>Result</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/loan__Loan_Account__c.object-meta.xml
<CustomObject>
    <description>Lending Account</description>
    <label>CL Contract</label>
    <nameField>
        <displayFormat>LAI-{00000000}</displayFormat>
        <label>CL Contract ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CL Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/loan__Loan_Account__c/fields/loan__Account__c.field-meta.xml
<CustomField>
    <fullName>loan__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Please choose a account, which will be associated as a customer on this lending account.
You can create a new account, from the lookup window by clicking on new or select the existing account from the lookup.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Loan_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SendLoanPaymentEmailHandler.cls
public with Sharing class SendLoanPaymentEmailHandler{
    public Static Void SendMail(Id templateId, Id loanAccountID, Id contactID, Id orgWideEmailId, String emailAddress){
        System.debug('...SendLoanPaymentHandler.SendMail ...');
        
        try{
            Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
                
            List<String> sendTo = new List<String>();
            //sendTo.add(loanAccount.loan__Account__r.cnotify__Email__c);
            
            sendTo.add(emailAddress);
            email.setToAddresses(sendTo);             
            //email.setSenderDisplayName('Payoff');
            email.setReplyTo('payments@payoff.com');
    
            email.setorgWideEmailAddressId(orgWideEmailId);
            email.setTargetObjectId(contactID);
            //email.setTargetObjectId(userId);
            //email.setTreatTargetObjectAsRecipient(false);
            email.setWhatId(loanAccountID);
            email.setTemplateId(templateId);
            
            email.saveAsActivity = false;
            Messaging.sendEmail(new Messaging.SingleEmailMessage[] {email});
        }catch(exception ex){
            loan__Batch_Process_Log__c bplog = new loan__Batch_Process_Log__c();
            bplog.loan__Message__c = 'Error in SendLoanPaymentHandler: ' + ex.getLineNumber() + ' Desc. ' + ex.getMessage()+' Stack: '+ex.getStackTraceString();
            bplog.loan__Type__c = 'Exception';
            bplog.loan__Time__c = DateTime.now();
            insert bplog;
            
            throw ex;
        }
    }
       
    
    /*@Future 
    public Static Void ManualPaymentMode(Map<ID, String> lstLoanAcc){
        Contact con = new Contact();
        con.LastName = 'Test';
        con.Email = 'no-reply@organization.com';
        insert con;
        Id templateId =  [select id, name from EmailTemplate where developername = 'Manual_Payment_Selected'].Id; 
        
        Id orgWideEmailId;
        OrgWideEmailAddress owea = [select Id from OrgWideEmailAddress where DisplayName = 'PayOff' LIMIT 1];
        if(owea != null)
            orgWideEmailId = owea.Id;
        String emailAddress;
        for(ID loanAccID : lstLoanAcc.keySet()){
            emailAddress = lstLoanAcc.get(loanAccID);
            System.debug('...Email Details...'+ templateId+'...'+ loanAccID +'...'+ con.Id+'...'+ orgWideEmailId+'...'+ emailAddress);
            SendLoanPaymentEmailHandler.SendMail(templateId, loanAccID, con.Id, orgWideEmailId, emailAddress);
        }
        delete con;
    } */
    
    @InvocableMethod
    public Static Void ManualPaymentMode(List<ID> lstLoanAcc){
        Contact con = new Contact();
        con.LastName = 'Test';
        con.Email = 'no-reply@organization.com';
        insert con;
        Id templateId =  [select id, name from EmailTemplate where developername = 'Manual_Payment_Selected'].Id; 
        
        Id orgWideEmailId;
        OrgWideEmailAddress owea = [select Id from OrgWideEmailAddress where DisplayName = 'PayOff' LIMIT 1];
        if(owea != null)
            orgWideEmailId = owea.Id;
        String emailAddress;
        for(ID loanAccID : lstLoanAcc){
            emailAddress = [SELECT loan__Account__r.cnotify__Email__c FROM loan__Loan_Account__c WHERE ID=:loanAccID].loan__Account__r.cnotify__Email__c;
                         
            //emailAddress = lstLoanAcc.get(loanAccID);
            System.debug('...Email Details...'+ templateId+'...'+ loanAccID +'...'+ con.Id+'...'+ orgWideEmailId+'...'+ emailAddress);
            SendLoanPaymentEmailHandler.SendMail(templateId, loanAccID, con.Id, orgWideEmailId, emailAddress);
        }
        delete con;
    } 
}