force-app/main/default/objects/Account/fields/cnotify__Email__c.field-meta.xml
<CustomField>
    <fullName>cnotify__Email__c</fullName>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/Investor_Code__c.field-meta.xml
<CustomField>
    <fullName>Investor_Code__c</fullName>
    <label>Investor Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/loan__Investor__c.field-meta.xml
<CustomField>
    <fullName>loan__Investor__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Investor</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/peer__Last_Name__c.field-meta.xml
<CustomField>
    <fullName>peer__Last_Name__c</fullName>
    <label>Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CL_Document__c/CL_Document__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>CL_Generated Documents Names</description>
    <label>CL Document</label>
</CustomObject>

force-app/main/default/objects/CL_Document__c/fields/Doc1__c.field-meta.xml
<CustomField>
    <fullName>Doc1__c</fullName>
    <label>Doc1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CL_Document__c/fields/Doc2__c.field-meta.xml
<CustomField>
    <fullName>Doc2__c</fullName>
    <inlineHelpText>TIL Document</inlineHelpText>
    <label>Doc2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CL_Document__c/fields/Doc3__c.field-meta.xml
<CustomField>
    <fullName>Doc3__c</fullName>
    <label>Doc3</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CL_Document__c/fields/UploadedBOX__c.field-meta.xml
<CustomField>
    <fullName>UploadedBOX__c</fullName>
    <label>UploadedBOX</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/genesis__Application_Document_Category__c/genesis__Application_Document_Category__c.object-meta.xml
<CustomObject>
    <label>Application Document Category</label>
    <nameField>
        <label>Application Document Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application Document Category</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/genesis__Application_Document_Category__c/fields/Box_URl__c.field-meta.xml
<CustomField>
    <fullName>Box_URl__c</fullName>
    <label>Box URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/genesis__Application_Document_Category__c/fields/genesis__Application__c.field-meta.xml
<CustomField>
    <fullName>genesis__Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>genesis__Applications__c</referenceTo>
    <relationshipLabel>Application Document Category</relationshipLabel>
    <relationshipName>Application_Document_Category</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/genesis__Application_Document_Category__c/fields/genesis__Status__c.field-meta.xml
<CustomField>
    <fullName>genesis__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>OPEN</fullName>
                <default>true</default>
                <label>OPEN</label>
            </value>
            <value>
                <fullName>SUBMITTED</fullName>
            </value>
            <value>
                <fullName>CLEARED</fullName>
            </value>
            <value>
                <fullName>REJECTED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/genesis__Application_Document_Category__c/fields/Investor_Code__c.field-meta.xml
<CustomField>
    <fullName>Investor_Code__c</fullName>
    <formula>genesis__Application__r.Investor__r.Investor_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Investor Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/genesis__Application_Document_Category__c/fields/Lead_Id__c.field-meta.xml
<CustomField>
    <fullName>Lead_Id__c</fullName>
    <formula>genesis__Application__r.Lead_ID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Lead Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/genesis__Applications__c/genesis__Applications__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{0000000000}</displayFormat>
        <label>Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/genesis__Applications__c/fields/Application_Start_DateV2__c.field-meta.xml
<CustomField>
    <fullName>Application_Start_DateV2__c</fullName>
    <label>Application Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/genesis__Applications__c/fields/Employment_Status__c.field-meta.xml
<CustomField>
    <fullName>Employment_Status__c</fullName>
    <label>Employment Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Full Time</fullName>
            </value>
            <value>
                <fullName>Part Time</fullName>
            </value>
            <value>
                <fullName>Retired</fullName>
            </value>
            <value>
                <fullName>Self Employed</fullName>
            </value>
            <value>
                <fullName>Contract</fullName>
            </value>
            <value>
                <fullName>Seasonal</fullName>
            </value>
            <value>
                <fullName>Investment</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/genesis__Applications__c/fields/genesis__Account__c.field-meta.xml
<CustomField>
    <fullName>genesis__Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Applications_account</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/genesis__Applications__c/fields/genesis__Draw_Period_End_Date__c.field-meta.xml
<CustomField>
    <fullName>genesis__Draw_Period_End_Date__c</fullName>
    <label>Draw Period End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/genesis__Applications__c/fields/genesis__Due_Day__c.field-meta.xml
<CustomField>
    <fullName>genesis__Due_Day__c</fullName>
    <description>dueDay field.</description>
    <inlineHelpText>If Due Day field is null, then by default it will have Expected First Payment Date day value</inlineHelpText>
    <label>Due_Day</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/genesis__Applications__c/fields/genesis__Expected_First_Payment_Date__c.field-meta.xml
<CustomField>
    <fullName>genesis__Expected_First_Payment_Date__c</fullName>
    <label>Expected First Payment Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/genesis__Applications__c/fields/genesis__Expected_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>genesis__Expected_Start_Date__c</fullName>
    <label>Expected Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/genesis__Applications__c/fields/genesis__Funding_in_Tranches__c.field-meta.xml
<CustomField>
    <fullName>genesis__Funding_in_Tranches__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Funding in Tranches</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/genesis__Applications__c/fields/genesis__Status__c.field-meta.xml
<CustomField>
    <fullName>genesis__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>APPROVED - APPROVED</fullName>
            </value>
            <value>
                <fullName>APPROVED - CONVERTED TO CONTRACT</fullName>
            </value>
            <value>
                <fullName>APPROVED - DOCUMENT CHECK</fullName>
            </value>
            <value>
                <fullName>NEW - CREDIT PULLED</fullName>
            </value>
            <value>
                <fullName>NEW - ENTERED</fullName>
                <default>true</default>
                <label>NEW - ENTERED</label>
            </value>
            <value>
                <fullName>NEW - IN CREDIT CHECK</fullName>
            </value>
            <value>
                <fullName>NEW - IN REVIEW</fullName>
            </value>
            <value>
                <fullName>NEW - PRICING GENERATED</fullName>
            </value>
            <value>
                <fullName>NEW - SCORECARD GENERATED</fullName>
            </value>
            <value>
                <fullName>NEW - CHECKLIST GENERATED</fullName>
            </value>
            <value>
                <fullName>NEW - VEHICLE VALUATION REQUIRED</fullName>
            </value>
            <value>
                <fullName>REJECTED</fullName>
            </value>
            <value>
                <fullName>PULL CREDIT</fullName>
            </value>
            <value>
                <fullName>Default Documents</fullName>
            </value>
            <value>
                <fullName>offer_accepted</fullName>
            </value>
            <value>
                <fullName>offer_shown</fullName>
            </value>
            <value>
                <fullName>kba_success</fullName>
            </value>
            <value>
                <fullName>kba_fail</fullName>
            </value>
            <value>
                <fullName>agent_document_verification_pending</fullName>
            </value>
            <value>
                <fullName>agent_verification_pending</fullName>
            </value>
            <value>
                <fullName>agent_verified</fullName>
            </value>
            <value>
                <fullName>docusign_loan_docs_sent</fullName>
            </value>
            <value>
                <fullName>docusign_loan_docs_complete</fullName>
            </value>
            <value>
                <fullName>pre_funding</fullName>
            </value>
            <value>
                <fullName>Approved for funding</fullName>
            </value>
            <value>
                <fullName>funded</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Stacker_Check_Passed</fullName>
            </value>
            <value>
                <fullName>Redecision_Required</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Decline_Manual_Review</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/genesis__Applications__c/fields/Investor__c.field-meta.xml
<CustomField>
    <fullName>Investor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Investor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.loan__Investor__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Applications (Investor)</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/genesis__Applications__c/fields/Lead_ID__c.field-meta.xml
<CustomField>
    <fullName>Lead_ID__c</fullName>
    <description>This is the LEAD GUID received from FE</description>
    <externalId>true</externalId>
    <label>Lead ID</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/genesis__Applications__c/fields/LeadGUID_XX_BoxFolderID__c.field-meta.xml
<CustomField>
    <fullName>LeadGUID_XX_BoxFolderID__c</fullName>
    <description>This field will contain the box folder id for the parent folder of the lead guid which will be the first 2 digits of the Lead Guid.</description>
    <label>LeadGUID_XX_BoxFolderID</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/MW_RegenerateTILTempBatchTest.cls
@isTest
public class MW_RegenerateTILTempBatchTest {
    
    
    
    public static testMethod void testWF_tilRegenerate(){
        
        Account account_Obj = new Account(
            Name = 'Test',
            peer__Last_Name__c = 'LastName',
            loan__Investor__c=False,
            cnotify__Email__c = 'no-reply@testorganization.com'
        );
        Insert account_Obj;
        
        Account investor_Obj = new Account(
            Name = 'Test',
            peer__Last_Name__c = 'LastName',
            loan__Investor__c=true,
            cnotify__Email__c = 'no-reply@testorganizatio.com',
            Investor_Code__c='FTCU'
        );
        Insert investor_Obj;
        
        CL_Document__c cs = new CL_Document__c();
        cs.Doc1__c = 'Credit Score Notice';
        cs.Doc2__c = 'TIL Document';
        cs.Doc3__c = 'Adverse Action Document';
        cs.UploadedBOX__c = 'UploadedBOX';
        insert cs;
        
        genesis__Applications__c genesis_applications_Obj = new genesis__Applications__c(
            genesis__Due_Day__c = 20,
            genesis__Expected_First_Payment_Date__c = system.Today(),
            genesis__Expected_Start_Date__c = system.Today(),
            genesis__Funding_in_Tranches__c = true,
            genesis__Account__c = account_Obj.Id,        
            Application_Start_DateV2__c = system.Today(),
            genesis__Status__c = 'funded', 
            genesis__Draw_Period_End_Date__c = system.Today(),
            Employment_Status__c = 'Full Time',
            Investor__c = investor_Obj.Id,
            Lead_Id__c = '4b98b422-d77c-7a95-a741-1c63994743c6',
            LeadGUID_XX_BoxFolderID__c =' 123213213'
        );      
        Insert genesis_applications_Obj; 
        
        genesis__Application_Document_Category__c appDoc = new genesis__Application_Document_Category__c();
        appDoc.Box_URl__c = 'https://happymoney.app.box.com/file/538729346459';
        appDoc.Name = 'TIL Document';
        
        appDoc.genesis__Application__c = genesis_applications_Obj.Id;
        insert appDoc;
        
        Attachment attach=new Attachment();  
        attach.Name='Unit Test Attachment';
        Blob bodyBlob=Blob.valueOf('Unit Test Attachment Body');
        attach.body=bodyBlob;
        attach.Description = 'TIL Document';
        attach.parentId=genesis_applications_Obj.Id;
        insert attach;

        
        Datetime startDate = datetime.newInstance(2019, 10, 10);
        Datetime endDate = datetime.newInstance(2019, 10, 12);
        system.debug('startDate==='+startDate);
        system.debug('endDate==='+endDate);
        
        set<string> skipLoanStatusSet = new set<string>();
        skipLoanStatusSet.add('Review');
        skipLoanStatusSet.add('Decline_Manual_Review');
        skipLoanStatusSet.add('Declined');
        skipLoanStatusSet.add('Expired');
        skipLoanStatusSet.add('Withdrawn');
        skipLoanStatusSet.add('Default Documents');
        skipLoanStatusSet.add('offer_shown');
        set<String> appStatuses = new set<String>();
        appStatuses.add(genesis_applications_Obj.Lead_Id__c);
        Test.startTest();
        MW_RegenerateTILTempBatch rbcth = new MW_RegenerateTILTempBatch(startDate,endDate,skipLoanStatusSet,'NA',appStatuses);
        Database.executeBatch(rbcth,1);
        Test.stopTest();
    }


}