force-app/main/default/objects/Account/fields/cnotify__Email__c.field-meta.xml
<CustomField>
    <fullName>cnotify__Email__c</fullName>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/loan__Investor__c.field-meta.xml
<CustomField>
    <fullName>loan__Investor__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Investor</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/clcommon__CL_Product__c/clcommon__CL_Product__c.object-meta.xml
<CustomObject>
    <label>CL Product</label>
    <nameField>
        <displayFormat>PRO-{00000000}</displayFormat>
        <label>CL Product Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CL Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/clcommon__CL_Product__c/fields/clcommon__Product_Name__c.field-meta.xml
<CustomField>
    <fullName>clcommon__Product_Name__c</fullName>
    <label>Product Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/clcommon__CL_Product__c/fields/loan__Lending_Product__c.field-meta.xml
<CustomField>
    <fullName>loan__Lending_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lending Product</label>
    <referenceTo>loan__Loan_Product__c</referenceTo>
    <relationshipLabel>CL Products</relationshipLabel>
    <relationshipName>CL_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/genesis__Applications__c/genesis__Applications__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{0000000000}</displayFormat>
        <label>Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/genesis__Applications__c/fields/genesis__Days_Convention__c.field-meta.xml
<CustomField>
    <fullName>genesis__Days_Convention__c</fullName>
    <label>Days Convention</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>genesis__Product_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>30/360</fullName>
                <default>true</default>
                <label>30/360</label>
            </value>
            <value>
                <fullName>365/365</fullName>
            </value>
            <value>
                <fullName>ACTUAL/ACTUAL</fullName>
            </value>
            <value>
                <fullName>ACTUAL/360</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/genesis__Applications__c/fields/genesis__Expected_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>genesis__Expected_Start_Date__c</fullName>
    <label>Expected Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/genesis__Applications__c/fields/genesis__Interest_Rate__c.field-meta.xml
<CustomField>
    <fullName>genesis__Interest_Rate__c</fullName>
    <label>Interest Rate</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/genesis__Applications__c/fields/genesis__Loan_Amount__c.field-meta.xml
<CustomField>
    <fullName>genesis__Loan_Amount__c</fullName>
    <label>Loan Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/genesis__Applications__c/fields/genesis__Payment_Frequency__c.field-meta.xml
<CustomField>
    <fullName>genesis__Payment_Frequency__c</fullName>
    <label>Payment Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>genesis__Product_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>DAILY</fullName>
            </value>
            <value>
                <fullName>WEEKLY</fullName>
            </value>
            <value>
                <fullName>BI-WEEKLY</fullName>
            </value>
            <value>
                <fullName>MONTHLY</fullName>
                <default>true</default>
                <label>MONTHLY</label>
            </value>
            <value>
                <fullName>QUARTERLY</fullName>
            </value>
            <value>
                <fullName>ANNUAL</fullName>
            </value>
            <value>
                <fullName>SEMI-MONTHLY</fullName>
            </value>
            <value>
                <fullName>BI-MONTHLY</fullName>
            </value>
            <value>
                <fullName>SEMI-ANNUAL</fullName>
            </value>
            <value>
                <fullName>SINGLEPMT</fullName>
            </value>
            <value>
                <fullName>SEMI-MONTHLY-PD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/genesis__Applications__c/fields/genesis__Product_Type__c.field-meta.xml
<CustomField>
    <fullName>genesis__Product_Type__c</fullName>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>LEASE</fullName>
                <default>true</default>
                <label>LEASE</label>
            </value>
            <value>
                <fullName>LOAN</fullName>
            </value>
            <value>
                <fullName>LINE OF CREDIT</fullName>
            </value>
            <value>
                <fullName>PACKAGE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/genesis__Applications__c/fields/genesis__Status__c.field-meta.xml
<CustomField>
    <fullName>genesis__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>APPROVED - APPROVED</fullName>
            </value>
            <value>
                <fullName>APPROVED - CONVERTED TO CONTRACT</fullName>
            </value>
            <value>
                <fullName>APPROVED - DOCUMENT CHECK</fullName>
            </value>
            <value>
                <fullName>NEW - CREDIT PULLED</fullName>
            </value>
            <value>
                <fullName>NEW - ENTERED</fullName>
                <default>true</default>
                <label>NEW - ENTERED</label>
            </value>
            <value>
                <fullName>NEW - IN CREDIT CHECK</fullName>
            </value>
            <value>
                <fullName>NEW - IN REVIEW</fullName>
            </value>
            <value>
                <fullName>NEW - PRICING GENERATED</fullName>
            </value>
            <value>
                <fullName>NEW - SCORECARD GENERATED</fullName>
            </value>
            <value>
                <fullName>NEW - CHECKLIST GENERATED</fullName>
            </value>
            <value>
                <fullName>NEW - VEHICLE VALUATION REQUIRED</fullName>
            </value>
            <value>
                <fullName>REJECTED</fullName>
            </value>
            <value>
                <fullName>PULL CREDIT</fullName>
            </value>
            <value>
                <fullName>Default Documents</fullName>
            </value>
            <value>
                <fullName>offer_accepted</fullName>
            </value>
            <value>
                <fullName>offer_shown</fullName>
            </value>
            <value>
                <fullName>kba_success</fullName>
            </value>
            <value>
                <fullName>kba_fail</fullName>
            </value>
            <value>
                <fullName>agent_document_verification_pending</fullName>
            </value>
            <value>
                <fullName>agent_verification_pending</fullName>
            </value>
            <value>
                <fullName>agent_verified</fullName>
            </value>
            <value>
                <fullName>docusign_loan_docs_sent</fullName>
            </value>
            <value>
                <fullName>docusign_loan_docs_complete</fullName>
            </value>
            <value>
                <fullName>pre_funding</fullName>
            </value>
            <value>
                <fullName>Approved for funding</fullName>
            </value>
            <value>
                <fullName>funded</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Stacker_Check_Passed</fullName>
            </value>
            <value>
                <fullName>Redecision_Required</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/genesis__Applications__c/fields/genesis__Term__c.field-meta.xml
<CustomField>
    <fullName>genesis__Term__c</fullName>
    <label>Term</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/loan__Fee__c/loan__Fee__c.object-meta.xml
<CustomObject>
    <description>Fee</description>
    <label>Fee</label>
    <nameField>
        <label>Fee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/loan__Fee__c/fields/loan__Currency__c.field-meta.xml
<CustomField>
    <fullName>loan__Currency__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Currency</description>
    <inlineHelpText>Currency</inlineHelpText>
    <label>Currency</label>
    <referenceTo>loan__Currency__c</referenceTo>
    <relationshipLabel>Fees</relationshipLabel>
    <relationshipName>Fees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/loan__Fee_Junction__c/loan__Fee_Junction__c.object-meta.xml
<CustomObject>
    <label>Fee Set/Fee</label>
    <nameField>
        <displayFormat>FJIP-{0000000000}</displayFormat>
        <label>Fee Junction ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fee Set/Fee</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/loan__Fee_Junction__c/fields/loan__Fee__c.field-meta.xml
<CustomField>
    <fullName>loan__Fee__c</fullName>
    <label>Fee</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>loan__Fee__c.loan__Time_of_charge__c</field>
            <operation>notEqual</operation>
            <value>Pre-Paid Fees</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>loan__Fee__c</referenceTo>
    <relationshipLabel>Fee Set/Fee</relationshipLabel>
    <relationshipName>Fee_Junction</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/loan__Fee_Junction__c/fields/loan__Fee_Set__c.field-meta.xml
<CustomField>
    <fullName>loan__Fee_Set__c</fullName>
    <label>Fee Set</label>
    <referenceTo>loan__Fee_Set__c</referenceTo>
    <relationshipName>Fee_Junction</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Product__c/loan__Loan_Product__c.object-meta.xml
<CustomObject>
    <description>Lending Product Definition1</description>
    <label>Lending Product</label>
    <nameField>
        <label>Loan Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lending Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/loan__Loan_Product__c/fields/loan__Currency__c.field-meta.xml
<CustomField>
    <fullName>loan__Currency__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Currency</description>
    <inlineHelpText>Currency</inlineHelpText>
    <label>Currency</label>
    <referenceTo>loan__Currency__c</referenceTo>
    <relationshipName>Loan_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Product__c/fields/loan__Fee_Set__c.field-meta.xml
<CustomField>
    <fullName>loan__Fee_Set__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Fee Set</description>
    <inlineHelpText>Fee set contains the details of all the fees associated with the loan.</inlineHelpText>
    <label>Fee Set</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Selected Fee Set&apos;s category must be of type &apos;Loan&apos; and it should include at least one fee.</errorMessage>
        <filterItems>
            <field>loan__Fee_Set__c.loan__Fee_Set_Category__c</field>
            <operation>equals</operation>
            <value>Loan</value>
        </filterItems>
        <filterItems>
            <field>loan__Fee_Set__c.loan__Number_of_Fees__c</field>
            <operation>notEqual</operation>
            <value>0</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>loan__Fee_Set__c</referenceTo>
    <relationshipName>Loan_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Test_Call_NeoVerifyTxnsCalloutQueue.cls
/* ****************Modification History******************************************
 * Created By        Date          JIRA number
 *1. Pallavi        2020/08/13     CRM-755(Make NeoVerify Initiated Manually)
 *      
 ******************Modification History******************************************/
@isTest
public class Test_Call_NeoVerifyTxnsCalloutQueue {
	
    @isTest
    public static void testmethod1(){
        
        loan.TestHelper.createSeedDataForTesting();
        loan__Currency__c curr = loan.TestHelper.createCurrency();
        
        //Dummy GLAccount
        loan__MF_Account__c dummyAccount = loan.TestHelper.createMFAccount('XXXAccountForTest','10000 - ASSETS');
        
        //Dummy Office insert
        loan__Office_Name__c dummyOffice = loan.TestHelper.createOffice();
        
        //Create a Fee Set
        loan__Fee__c dummyFee = loan.TestHelper.createFee(curr);                                    
        loan__Fee_Set__c dummyFeeSet = loan.TestHelper.createFeeSet();
        loan__Fee_Junction__c dummyFeeJunction = loan.TestHelper.createFeeJunction(dummyFee,dummyFeeSet);
        
        //creating lending product
        loan__Loan_Product__c dummyLP = loan.TestHelper.createLoanProduct(dummyOffice, dummyAccount, curr, dummyFeeSet);
        
        //creating CL Product
        clcommon__CL_Product__c pr = new clcommon__CL_Product__c();
        pr.loan__Lending_Product__c = dummyLp.id;
        pr.clcommon__Product_Name__c = 'P1';
        insert pr;
        
        Date currentSystemDate = (new loan.GlobalLoanUtilFacade().getCurrentSystemDate());
        Account acc = new Account(
            Name = 'Test',
            loan__Investor__c=False,
            cnotify__Email__c = 'no-reply@testorganization.com'
        );
        Insert acc;
         
        //Create Application
        genesis__applications__c application = new genesis__applications__c();
        application.genesis__Product_Type__c = 'LOAN';
        application.genesis__Loan_Amount__c = 6700;
        application.genesis__status__c = 'NEW - ENTERED';
        application.genesis__Term__c = 12;
        application.genesis__Payment_Frequency__c = 'MONTHLY';
        application.genesis__Interest_Rate__c = 10;
        application.genesis__Days_Convention__c = 'ACTUAL/ACTUAL';
        application.genesis__Expected_Start_Date__c = system.today();
        application.genesis__Expected_First_Payment_Date__c = system.today().addDays(60);
        application.genesis__Expected_Close_Date__c = system.today().addDays(30);
        application.genesis__Interest_Calculation_Method__c = 'Declining Balance';
        application.genesis__Interest_Only_Period__c = 0;
        application.genesis__Interest_Rate__c = 100;
        application.genesis__Account__c = acc.Id;
        application.genesis__Total_Estimated_Interest__c=500;
        application.genesis__Valid_Pricing_Flag__c=false;
        application.genesis__Probability__c=100.00;
        application.genesis__Payment_Amount__c=523.80;
        application.genesis__CL_Product__c = pr.id;
        application.Application_Start_DateV2__c = currentSystemDate.adddays(-30);
        insert application;
        
        Test.startTest();
        String res = Call_NeoVerifyTransactionsCalloutQueue.callMWNeoVerifyTransactions(application.id);
        Test.stopTest();
    }
}