force-app/main/default/objects/Account/fields/cnotify__Email__c.field-meta.xml
<CustomField>
    <fullName>cnotify__Email__c</fullName>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/loan__Investor__c.field-meta.xml
<CustomField>
    <fullName>loan__Investor__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Investor</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/loan__SOCIAL_SECURITY_NUMBER__c.field-meta.xml
<CustomField>
    <fullName>loan__SOCIAL_SECURITY_NUMBER__c</fullName>
    <label>SOCIAL_SECURITY_NUMBER</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/loan__Undeployed_Funds__c.field-meta.xml
<CustomField>
    <fullName>loan__Undeployed_Funds__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Total amount which is available to invest in loans.</description>
    <inlineHelpText>tracks the investor payout or investor funds while creating investor loan or while selling the loan</inlineHelpText>
    <label>Available Funds</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/peer__First_Name__c.field-meta.xml
<CustomField>
    <fullName>peer__First_Name__c</fullName>
    <label>First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/peer__Last_Name__c.field-meta.xml
<CustomField>
    <fullName>peer__Last_Name__c</fullName>
    <label>Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Investor.recordType-meta.xml
<RecordType>
    <fullName>Investor</fullName>
    <active>true</active>
    <label>Investor</label>
</RecordType>

force-app/main/default/objects/loan__Fee__c/loan__Fee__c.object-meta.xml
<CustomObject>
    <description>Fee</description>
    <label>Fee</label>
    <nameField>
        <label>Fee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/loan__Fee__c/fields/loan__Amount__c.field-meta.xml
<CustomField>
    <fullName>loan__Amount__c</fullName>
    <description>Number or %
Amount, is a flat amount. For other fee calculation methods, this is a % amount.</description>
    <inlineHelpText>Number or % 
Amount, is a flat amount. For other fee calculation methods, this is a % amount.</inlineHelpText>
    <label>Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/loan__Fee__c/fields/loan__Currency__c.field-meta.xml
<CustomField>
    <fullName>loan__Currency__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Currency</description>
    <inlineHelpText>Currency</inlineHelpText>
    <label>Currency</label>
    <referenceTo>loan__Currency__c</referenceTo>
    <relationshipLabel>Fees</relationshipLabel>
    <relationshipName>Fees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/loan__Fee__c/fields/loan__Time_of_charge__c.field-meta.xml
<CustomField>
    <fullName>loan__Time_of_charge__c</fullName>
    <description>Time of charge</description>
    <inlineHelpText>Time of charge</inlineHelpText>
    <label>Time of charge</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>loan__Fee_Category__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Late Fees</fullName>
            </value>
            <value>
                <fullName>Maintenance Fees</fullName>
            </value>
            <value>
                <fullName>Pay-Off Fees</fullName>
            </value>
            <value>
                <fullName>NSF Fees</fullName>
            </value>
            <value>
                <fullName>Wire Fees</fullName>
            </value>
            <value>
                <fullName>Periodic Fees</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
                <default>true</default>
                <label>Other</label>
            </value>
            <value>
                <fullName>Amortized Fees</fullName>
            </value>
            <value>
                <fullName>Time of Disbursement</fullName>
            </value>
            <value>
                <fullName>Pre-Paid Fees</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/loan__Fee_Junction__c/loan__Fee_Junction__c.object-meta.xml
<CustomObject>
    <label>Fee Set/Fee</label>
    <nameField>
        <displayFormat>FJIP-{0000000000}</displayFormat>
        <label>Fee Junction ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fee Set/Fee</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/loan__Fee_Junction__c/fields/loan__Fee__c.field-meta.xml
<CustomField>
    <fullName>loan__Fee__c</fullName>
    <label>Fee</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>loan__Fee__c.loan__Time_of_charge__c</field>
            <operation>notEqual</operation>
            <value>Pre-Paid Fees</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>loan__Fee__c</referenceTo>
    <relationshipLabel>Fee Set/Fee</relationshipLabel>
    <relationshipName>Fee_Junction</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/loan__Fee_Junction__c/fields/loan__Fee_Set__c.field-meta.xml
<CustomField>
    <fullName>loan__Fee_Set__c</fullName>
    <label>Fee Set</label>
    <referenceTo>loan__Fee_Set__c</referenceTo>
    <relationshipName>Fee_Junction</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/loan__Investor_Loan__c/loan__Investor_Loan__c.object-meta.xml
<CustomObject>
    <description>This is a conjunction object to keep many to many relationships for loans and accounts (Investor)</description>
    <label>Investment Order</label>
    <nameField>
        <displayFormat>ILID-{0000000000}</displayFormat>
        <label>Investor Loan ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Investment Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/loan__Investor_Loan__c/fields/loan__Loan_Status__c.field-meta.xml
<CustomField>
    <fullName>loan__Loan_Status__c</fullName>
    <description>Loan_Status__c on loan account</description>
    <label>Created Loan Status</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/loan__Loan_Account__c.object-meta.xml
<CustomObject>
    <description>Lending Account</description>
    <label>CL Contract</label>
    <nameField>
        <displayFormat>LAI-{00000000}</displayFormat>
        <label>CL Contract ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CL Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/loan__Loan_Account__c/fields/loan__Fee_Set__c.field-meta.xml
<CustomField>
    <fullName>loan__Fee_Set__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Fee Set</description>
    <inlineHelpText>Lookup to associate the fee set on this lending account. Only the fees defined within the fee set can be assessed on this contract.
To create a fee set, Servicing configuration-&gt;Product-&gt;Manage fee set</inlineHelpText>
    <label>Fee Set</label>
    <referenceTo>loan__Fee_Set__c</referenceTo>
    <relationshipName>Loan_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/loan__Loan_Purpose__c.field-meta.xml
<CustomField>
    <fullName>loan__Loan_Purpose__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Loan Purpose</description>
    <inlineHelpText>Loan purpose</inlineHelpText>
    <label>Purpose</label>
    <referenceTo>loan__Loan_Purpose__c</referenceTo>
    <relationshipName>Loan_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/loan__Number_of_Installments__c.field-meta.xml
<CustomField>
    <fullName>loan__Number_of_Installments__c</fullName>
    <description>Contractual Term Of the Loan Account</description>
    <inlineHelpText>Contractual term of the contract.</inlineHelpText>
    <label>Term</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/loan__Pre_Bill_Days__c.field-meta.xml
<CustomField>
    <fullName>loan__Pre_Bill_Days__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Number of days before due date to have the bill generated.</description>
    <inlineHelpText>Number of days for the bill to be generated before the actual installment date</inlineHelpText>
    <label>Pre Bill Days</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/peer__Note_Type__c.field-meta.xml
<CustomField>
    <fullName>peer__Note_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Note Type</label>
    <referenceTo>peer__Note_Type__c</referenceTo>
    <relationshipLabel>Lending</relationshipLabel>
    <relationshipName>Lending</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Product__c/loan__Loan_Product__c.object-meta.xml
<CustomObject>
    <description>Lending Product Definition1</description>
    <label>Lending Product</label>
    <nameField>
        <label>Loan Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lending Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/loan__Loan_Product__c/fields/loan__Currency__c.field-meta.xml
<CustomField>
    <fullName>loan__Currency__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Currency</description>
    <inlineHelpText>Currency</inlineHelpText>
    <label>Currency</label>
    <referenceTo>loan__Currency__c</referenceTo>
    <relationshipName>Loan_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Product__c/fields/loan__Fee_Set__c.field-meta.xml
<CustomField>
    <fullName>loan__Fee_Set__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Fee Set</description>
    <inlineHelpText>Fee set contains the details of all the fees associated with the loan.</inlineHelpText>
    <label>Fee Set</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Selected Fee Set&apos;s category must be of type &apos;Loan&apos; and it should include at least one fee.</errorMessage>
        <filterItems>
            <field>loan__Fee_Set__c.loan__Fee_Set_Category__c</field>
            <operation>equals</operation>
            <value>Loan</value>
        </filterItems>
        <filterItems>
            <field>loan__Fee_Set__c.loan__Number_of_Fees__c</field>
            <operation>notEqual</operation>
            <value>0</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>loan__Fee_Set__c</referenceTo>
    <relationshipName>Loan_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Product__c/fields/loan__Pre_Bill_Days__c.field-meta.xml
<CustomField>
    <fullName>loan__Pre_Bill_Days__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Number of days for the bill to be generated before the due date.</inlineHelpText>
    <label>Pre Bill Days</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/peer__Note_Type__c/peer__Note_Type__c.object-meta.xml
<CustomObject>
    <label>Note Type</label>
    <nameField>
        <displayFormat>NOTE-{000}</displayFormat>
        <label>Note Type Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Note Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/peer__Note_Type__c/fields/peer__Denomination__c.field-meta.xml
<CustomField>
    <fullName>peer__Denomination__c</fullName>
    <label>Denomination</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/TestCustomIOSaleController.cls
/*
* Description: Test class for CustomIOSaleController.
*/
/* ****************Modification History******************
 * Last Modified by        Date          JIRA number
 *      1. Pallavi        2020/01/27     LOS-28(Remove references to InvestorAccount field on CL contract)
 *      2. Shakul         2022/03/29     LSP-562 (Refactored Test Class)
 ******************Modification History******************/
@isTest
public Class TestCustomIOSaleController{
    
    
    @TestSetup
    public static void testSetup(){
        //Create investor acc
        List<Account> listAcc = new List<Account>();
         Account invacc = new Account(
            peer__First_Name__c ='Account',
            peer__Last_Name__c = 'Test',
            loan__Investor__c= true,
            cnotify__Email__c = 'abc@test.com',
            loan__SOCIAL_SECURITY_NUMBER__c = String.valueOf(math.random()).right(9),
            loan__Undeployed_Funds__c = 1601
            );
        listAcc.add(invacc);

        Account dummyClient = new Account(); 
        dummyClient.Name = 'Payoff';
        dummyClient.peer__Last_Name__c = 'AccountOne';
        dummyClient.peer__First_Name__c = 'TestOne';
        listAcc.add(dummyClient);
        insert listAcc;

        //Creating loan account 
        loan.TestHelper.createSeedDataForTesting();
        loan__Office_Name__c dummyOffice = loan.TestHelper.createOffice();

        loan__Currency__c curr = loan.TestHelper.createCurrency();
        //Create a dummy MF_Account
        loan__MF_Account__c dummyAccount = loan.TestHelper.createMFAccount('XXXAccountForTest','10000 - ASSETS');
        loan__MF_Account__c dummyIncAccount = loan.TestHelper.createMFAccount('XXXIncAccountForTest','30000 - INCOME');

        //Create a Fee Set
        loan__Fee__c dummyFee = loan.TestHelper.createFee(curr,dummyIncAccount ,dummyAccount); 
        dummyFee.loan__Amount__c = 3;      
        dummyFee.loan__Time_Of_Charge__c = 'Other';
        upsert dummyFee;
        loan__Fee_Set__c dummyFeeSet = loan.TestHelper.createFeeSet();
        loan__Fee_Junction__c dummyFeeJunction = loan.TestHelper.createFeeJunction(dummyFee,dummyFeeSet);

        loan__Loan_Product__c dummyLP = loan.TestHelper.createLoanProduct(dummyOffice,
                            dummyAccount, 
                            curr, 
                            dummyFeeSet);
        dummyLP.name = 'Manual Payer';
        dummyLP.loan__Pre_Bill_Days__c = 5;
        upsert dummyLP;

        loan__Loan_Purpose__c dummyLoanPurpose = loan.TestHelper.createLoanPurpose(); 

        peer__Note_Type__c nt = new peer__Note_Type__c(peer__Denomination__c = 10);
        insert nt;

        //Create a dummy Loan Account
        loan__Loan_Account__c loanAccount = loan.TestHelper.createLoanAccountForAccountObj(dummyLP,
                                                    dummyClient,
                                                    dummyFeeSet,
                                                    dummyLoanPurpose,
                                                    dummyOffice);
        loanAccount.loan__Number_of_Installments__c     = 12;                                  
        loanAccount.Loan__Loan_Status__c                = loan.LoanConstants.LOAN_STATUS_ACTIVE_GOOD_STANDING;
        loanAccount.Loan__Fees_Remaining__c             = 100;
        loanAccount.Loan__Interest_Remaining__c         = 500;
        loanAccount.Loan__Principal_Remaining__c        = 1000;
        loanAccount.Loan__Fractionalization_Status__c   = loan.LoanConstants.FRACTIONALIZATION_STATUS_ACTIVE;
        loanAccount.Loan__Pay_off_Amount_As_Of_Today__c = loanAccount.loan__Fees_Remaining__c + loanAccount.loan__Principal_Remaining__c;
        loanAccount.loan__Delinquent_Amount__c             = 5000;
        loanAccount.loan__Next_Due_Generation_Date__c = date.today().adddays(15);
        loanAccount.peer__Note_Type__c = nt.id;
        upsert loanAccount;
        //Create Investment Order
        loan.TestHelper2.createInvestmentOrder(invacc,loanAccount,1600);
    }

    /*Created By: Shakul Siddharth
      Purpose: To check Preview Method in CustomIOSaleController class*/
    public static testMethod void checkPreviewMethod(){
        loan__Investor_Loan__c ilt = [SELECT id, loan__Inv_Accrued_Interest_Amt__c, loan__Principal_Amount_Paid__c,
                                        loan__Account__c FROM loan__Investor_Loan__c];
        ilt.loan__Principal_Amount_Paid__c = 798;
        ilt.loan__Inv_Accrued_Interest_Amt__c = 800;
        update ilt;
        ApexPages.StandardController stdctrl = new ApexPages.StandardController(ilt);
        CustomIOSaleController ctopc = new CustomIOSaleController(stdctrl);
        ctopc.salePrice = 1000;
        ctopc.newIO = ilt;
        ctopc.preview();
        System.assertEquals(false, ctopc.success);
    }
    
    /*Created By: Shakul Siddharth
      Purpose: To check Execute Sale Method in CustomIOSaleController class*/
    public static testMethod void checkExecSaleMethod(){
        loan__Investor_Loan__c ilt = [SELECT id, peer__Number_of_Shares__c FROM loan__Investor_Loan__c];
        ApexPages.StandardController stdctrl = new ApexPages.StandardController(ilt);
        CustomIOSaleController ctopc = new CustomIOSaleController(stdctrl);
        ctopc.isPreview = true;
        ctopc.executeSale();
        System.assertEquals(false, ctopc.success);
    }
}