force-app/main/default/objects/Account/fields/ints__Yodlee_Password__c.field-meta.xml
<CustomField>
    <fullName>ints__Yodlee_Password__c</fullName>
    <description>Password for Yodlee Username.</description>
    <label>Yodlee_Password</label>
    <length>100</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/Account/fields/ints__Yodlee_Username__c.field-meta.xml
<CustomField>
    <fullName>ints__Yodlee_Username__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Username registered with Yodlee. This Username can have multiple bank accounts linked with Yodlee.</description>
    <label>Yodlee Username</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/clcommon__Party_Type__c/clcommon__Party_Type__c.object-meta.xml
<CustomObject>
    <label>Party Type</label>
    <nameField>
        <label>Party Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Party Type</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/clcommon__Party_Type__c/fields/Check__c.field-meta.xml
<CustomField>
    <fullName>Check__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Check</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/genesis__Application_Document_Category__c/genesis__Application_Document_Category__c.object-meta.xml
<CustomObject>
    <label>Application Document Category</label>
    <nameField>
        <label>Application Document Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application Document Category</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/genesis__Application_Document_Category__c/fields/genesis__Active__c.field-meta.xml
<CustomField>
    <fullName>genesis__Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/genesis__Application_Document_Category__c/fields/genesis__Application__c.field-meta.xml
<CustomField>
    <fullName>genesis__Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>genesis__Applications__c</referenceTo>
    <relationshipLabel>Application Document Category</relationshipLabel>
    <relationshipName>Application_Document_Category</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/genesis__Application_Document_Category__c/fields/genesis__Description__c.field-meta.xml
<CustomField>
    <fullName>genesis__Description__c</fullName>
    <label>Description</label>
    <length>32000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/genesis__Application_Document_Category__c/fields/genesis__Document_Category__c.field-meta.xml
<CustomField>
    <fullName>genesis__Document_Category__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Document Category</label>
    <referenceTo>genesis__Document_Category__c</referenceTo>
    <relationshipLabel>Application Document Category</relationshipLabel>
    <relationshipName>Application_Document_Category</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/genesis__Application_Document_Category__c/fields/genesis__Email__c.field-meta.xml
<CustomField>
    <fullName>genesis__Email__c</fullName>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/genesis__Application_Document_Category__c/fields/genesis__Required__c.field-meta.xml
<CustomField>
    <fullName>genesis__Required__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/genesis__Application_Document_Category__c/fields/genesis__Send_Notification__c.field-meta.xml
<CustomField>
    <fullName>genesis__Send_Notification__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Send Notification</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/genesis__Application_Document_Category__c/fields/genesis__Status__c.field-meta.xml
<CustomField>
    <fullName>genesis__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>OPEN</fullName>
                <default>true</default>
                <label>OPEN</label>
            </value>
            <value>
                <fullName>SUBMITTED</fullName>
            </value>
            <value>
                <fullName>CLEARED</fullName>
            </value>
            <value>
                <fullName>REJECTED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/genesis__Applications__c/genesis__Applications__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{0000000000}</displayFormat>
        <label>Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/genesis__Applications__c/fields/genesis__Description__c.field-meta.xml
<CustomField>
    <fullName>genesis__Description__c</fullName>
    <label>Description</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/genesis__Document_Category__c/genesis__Document_Category__c.object-meta.xml
<CustomObject>
    <label>Document Category</label>
    <nameField>
        <displayFormat>DC-{00000000}</displayFormat>
        <label>Document Category Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Document Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/genesis__Document_Category__c/fields/Application_Status__c.field-meta.xml
<CustomField>
    <fullName>Application_Status__c</fullName>
    <description>Mapping Application Status to the Document Category</description>
    <label>Application Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Application_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/genesis__Document_Category__c/fields/Code_FF__c.field-meta.xml
<CustomField>
    <fullName>Code_FF__c</fullName>
    <label>Code_FF</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/genesis__Document_Category__c/fields/genesis__Applicable_For__c.field-meta.xml
<CustomField>
    <fullName>genesis__Applicable_For__c</fullName>
    <label>Applicable For</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CONTRACT</fullName>
            </value>
            <value>
                <fullName>PARTY</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/genesis__Document_Category__c/fields/genesis__Category_Name__c.field-meta.xml
<CustomField>
    <fullName>genesis__Category_Name__c</fullName>
    <label>Category Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/genesis__Document_Category__c/fields/genesis__Create_Tasks__c.field-meta.xml
<CustomField>
    <fullName>genesis__Create_Tasks__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Create Task</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/genesis__Document_Category__c/fields/genesis__Description__c.field-meta.xml
<CustomField>
    <fullName>genesis__Description__c</fullName>
    <label>Description</label>
    <length>130000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/genesis__Document_Category__c/fields/genesis__Generation_Status__c.field-meta.xml
<CustomField>
    <fullName>genesis__Generation_Status__c</fullName>
    <label>Generation Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>PULL CREDIT</fullName>
            </value>
            <value>
                <fullName>agent_verified</fullName>
            </value>
            <value>
                <fullName>offer_shown</fullName>
            </value>
            <value>
                <fullName>Self Employed Documents</fullName>
            </value>
            <value>
                <fullName>Default Documents</fullName>
            </value>
            <value>
                <fullName>kba_success</fullName>
            </value>
            <value>
                <fullName>TRUE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/genesis__Document_Category__c/fields/genesis__Parent_Document_Category__c.field-meta.xml
<CustomField>
    <fullName>genesis__Parent_Document_Category__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Child document category to define folder structure in documents.</description>
    <label>Parent Document Category</label>
    <referenceTo>genesis__Document_Category__c</referenceTo>
    <relationshipLabel>Document Categories</relationshipLabel>
    <relationshipName>Document_Categories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/genesis__Document_Category__c/fields/genesis__Required__c.field-meta.xml
<CustomField>
    <fullName>genesis__Required__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/genesis__Document_Category__c/fields/genesis__Responsible_Party_Type__c.field-meta.xml
<CustomField>
    <fullName>genesis__Responsible_Party_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Responsible Party Type</label>
    <referenceTo>clcommon__Party_Type__c</referenceTo>
    <relationshipLabel>Document Categories</relationshipLabel>
    <relationshipName>Document_Categories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/genesis__Document_Category__c/fields/genesis__Review_Assigned_To_Party_Type__c.field-meta.xml
<CustomField>
    <fullName>genesis__Review_Assigned_To_Party_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Review Assigned To (Party Type)</label>
    <referenceTo>clcommon__Party_Type__c</referenceTo>
    <relationshipLabel>Document Categories (Review Assigned To(Party Type))</relationshipLabel>
    <relationshipName>Document_Categories1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/genesis__Document_Category__c/fields/genesis__Send_Notification__c.field-meta.xml
<CustomField>
    <fullName>genesis__Send_Notification__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Send Notification</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ints__Yodlee_User_Credentials__c/ints__Yodlee_User_Credentials__c.object-meta.xml
<CustomObject>
    <label>Yodlee User Credentials</label>
    <nameField>
        <displayFormat>YUC-{00000000}</displayFormat>
        <label>Yodlee User Credentials Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Yodlee User Credentials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ints__Yodlee_User_Credentials__c/fields/ints__Account__c.field-meta.xml
<CustomField>
    <fullName>ints__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Yodlee User Credentials</relationshipLabel>
    <relationshipName>Yodlee_User_Credentials</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ints__Yodlee_User_Credentials__c/fields/ints__Yodlee_Password__c.field-meta.xml
<CustomField>
    <fullName>ints__Yodlee_Password__c</fullName>
    <label>Yodlee Password</label>
    <length>100</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <required>true</required>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/ints__Yodlee_User_Credentials__c/fields/ints__Yodlee_Username__c.field-meta.xml
<CustomField>
    <fullName>ints__Yodlee_Username__c</fullName>
    <label>Yodlee Username</label>
    <length>100</length>
    <maskChar>asterisk</maskChar>
    <maskType>lastFour</maskType>
    <required>true</required>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/ints__Yodlee_User_Credentials__c/fields/yodlee_Account_count__c.field-meta.xml
<CustomField>
    <fullName>yodlee_Account_count__c</fullName>
    <label>yodlee_Account_count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/globalValueSets/Application_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>APPROVED - CONVERTED TO CONTRACT</fullName>
    </customValue>
    <customValue>
        <fullName>APPROVED - DOCUMENT CHECK</fullName>
    </customValue>
    <customValue>
        <fullName>NEW - CREDIT PULLED</fullName>
    </customValue>
    <customValue>
        <fullName>NEW - ENTERED</fullName>
    </customValue>
    <customValue>
        <fullName>NEW - IN CREDIT CHECK</fullName>
    </customValue>
    <customValue>
        <fullName>NEW - IN REVIEW</fullName>
    </customValue>
    <customValue>
        <fullName>NEW - PRICING GENERATED</fullName>
    </customValue>
    <customValue>
        <fullName>NEW - SCORECARD GENERATED</fullName>
    </customValue>
    <customValue>
        <fullName>NEW - CHECKLIST GENERATED</fullName>
    </customValue>
    <customValue>
        <fullName>NEW - VEHICLE VALUATION REQUIRED</fullName>
    </customValue>
    <customValue>
        <fullName>REJECTED</fullName>
    </customValue>
    <customValue>
        <fullName>PULL CREDIT</fullName>
    </customValue>
    <customValue>
        <fullName>Default Documents</fullName>
    </customValue>
    <customValue>
        <fullName>Self Employed Documents</fullName>
    </customValue>
    <customValue>
        <fullName>e_sign_borrower_signed</fullName>
    </customValue>
    <customValue>
        <fullName>kba_success</fullName>
    </customValue>
    <customValue>
        <fullName>member_account_created</fullName>
    </customValue>
    <customValue>
        <fullName>credit_policy_completed</fullName>
    </customValue>
    <customValue>
        <fullName>offer_shown</fullName>
    </customValue>
    <customValue>
        <fullName>offer_accepted</fullName>
    </customValue>
    <customValue>
        <fullName>expired_offer</fullName>
    </customValue>
    <customValue>
        <fullName>loan_details_collected</fullName>
    </customValue>
    <customValue>
        <fullName>credit_score_notice_shown</fullName>
    </customValue>
    <customValue>
        <fullName>credit_score_notice_accepted</fullName>
    </customValue>
    <customValue>
        <fullName>ach_shown</fullName>
    </customValue>
    <customValue>
        <fullName>ach_collected</fullName>
    </customValue>
    <customValue>
        <fullName>DCP_shown</fullName>
    </customValue>
    <customValue>
        <fullName>kba_disclosure_shown</fullName>
    </customValue>
    <customValue>
        <fullName>kba_disclosure_accepted</fullName>
    </customValue>
    <customValue>
        <fullName>kba_review</fullName>
    </customValue>
    <description>Application Lead Status</description>
    <masterLabel>Application Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/MW_DocumentCategoryHandlerTEMPTest.cls
@isTest (SeeAllData=true)
public with sharing class MW_DocumentCategoryHandlerTEMPTest {

    static testMethod void TestDOcumentCategoryWithYodlee(){
        

        clcommon__Party_Type__c pt = new clcommon__Party_Type__c();
        pt.name = 'Borrower';
        insert pt;

        clcommon__Party_Type__c lo = new clcommon__Party_Type__c();
        lo.Name = 'LOAN OFFICER';
        lo.Check__c = false;
        insert lo;

        clcommon__Party_Type__c entityparty = new clcommon__Party_Type__c();
        entityparty.Name = 'ENTITY';
        entityparty.Check__c = false;
        insert entityparty;

        genesis__Document_Category__c dc = new genesis__Document_Category__c();
        dc.genesis__Responsible_Party_Type__c = pt.id;
        dc.genesis__Applicable_For__c = 'PARTY';
        dc.genesis__Category_Name__c = 'Verification Documents';
        dc.genesis__Required__c = true;
        dc.genesis__Generation_Status__c = 'Default Documents';
        dc.genesis__Send_Notification__c = true;
        dc.genesis__Create_Tasks__c = true;
        dc.genesis__Review_Assigned_To_Party_Type__c=lo.id;
        insert dc;

        genesis__Document_Category__c payStub = new genesis__Document_Category__c();
        payStub.genesis__Applicable_For__c = 'PARTY';
        payStub.genesis__Category_Name__c = 'Credit Card Balances';
        payStub.genesis__Create_Tasks__c = true;
        payStub.genesis__Description__c = 'Credit Card Balances';
        payStub.genesis__Parent_Document_Category__c = dc.id;
        payStub.genesis__Required__c = true;
        payStub.genesis__Responsible_Party_Type__c = pt.id;
        payStub.genesis__Send_Notification__c = true;
        payStub.Application_Status__c = 'Default Documents';
        payStub.Code_FF__c = 'income';
        insert payStub;

        //Insert Account
        List<account> accList = MW_DataFactoryTest.createAccounts(1);
        insert accList;
        ints__Yodlee_User_Credentials__c yodleeUserCredentialTest = new ints__Yodlee_User_Credentials__c();
        yodleeUserCredentialTest.ints__Account__c = accList[0].Id;
        yodleeUserCredentialTest.ints__Yodlee_Username__c = 'testUser1234';
        yodleeUserCredentialTest.ints__Yodlee_Password__c = 'testPassword1234';
        yodleeUserCredentialTest.yodlee_Account_count__c = 1;
        insert yodleeUserCredentialTest;

        genesis__Applications__c genesis_applications_Obj = MW_DataFactoryTest.createApplication(1, accList[0].Id)[0];
        Insert genesis_applications_Obj;

        Attachment attachment_Obj = new Attachment(
            ParentId = genesis_applications_Obj.id,
            Name = 'Name312',
            IsPrivate = false,
            Body = Blob.valueOf('Unit Test Attachment Body'),
            Description = '15');
        Insert attachment_Obj;

        genesis__Application_Document_Category__c root = new genesis__Application_Document_Category__c();
        root.Name = 'test';
        root.genesis__Active__c = true;
        root.genesis__Application__c = genesis_applications_Obj.id;
        root.genesis__Email__c = 'qa+3855474713@payoff.com';
        root.genesis__Required__c = false;
        root.genesis__Send_Notification__c = false;
        root.genesis__Status__c = 'OPEN';
        root.Doc_Upload_Notification__c = false;
        insert root;

        genesis__Application_Document_Category__c parentDoc = new genesis__Application_Document_Category__c();
        parentDoc.Name = 'Verification Documents';
        parentDoc.genesis__Active__c = true;
        parentDoc.genesis__Application__c = genesis_applications_Obj.id;
        parentDoc.genesis__Document_Category__c = dc.Id;
        parentDoc.genesis__Email__c = 'qa+3855474713@payoff.com';
        parentDoc.genesis__Id__c = '0';
        parentDoc.genesis__Parent_Application_Document_Category__c = root.Id;
        parentDoc.genesis__Party_Type__c = entityparty.id;
        parentDoc.genesis__Required__c = true;
        parentDoc.genesis__Send_Notification__c = false;
        parentDoc.genesis__Status__c = 'OPEN';
        parentDoc.Borrower_s_Email__c = 'qa+3855474713@payoff.com';
        parentDoc.Doc_Upload_Notification__c = false;
        parentDoc.Box_URl__c = 'test@abc.com';
        insert parentDoc;
        
        //test.startTest();
        genesis__Application_Document_Category__c apdc = new genesis__Application_Document_Category__c();
        apdc.Name = 'Credit Card Balances';
        apdc.genesis__Active__c = true;
        apdc.genesis__Application__c = genesis_applications_Obj.id;
        apdc.genesis__Description__c = 'Credit Card Balances - Additional';
        apdc.genesis__Document_Category__c = payStub.id;
        apdc.genesis__Email__c = 'qa+3855474713@payoff.com';
        apdc.genesis__Id__c = '1';
        apdc.genesis__Parent_Application_Document_Category__c = parentDoc.id;
        apdc.genesis__Parent_Id__c = '0';
        apdc.genesis__Party_Type__c = pt.id;
        apdc.genesis__Required__c = true;
        apdc.genesis__Status__c = 'OPEN';
        apdc.Doc_Upload_Notification__c = false;
        apdc.Box_URl__c = 'test@abc.com';
        insert apdc;

        genesis__Application_Document_Category__c bankDoc = new genesis__Application_Document_Category__c();
        bankDoc.Name = 'ESign Documents';
        bankDoc.genesis__Active__c = true;
        bankDoc.genesis__Application__c = genesis_applications_Obj.id;
        bankDoc.genesis__Document_Category__c = dc.Id;
        bankDoc.genesis__Email__c = 'qa+3855474713@payoff.com';
        bankDoc.genesis__Id__c = '0';
        bankDoc.genesis__Parent_Application_Document_Category__c = root.Id;
        bankDoc.genesis__Party_Type__c = entityparty.id;
        bankDoc.genesis__Required__c = true;
        bankDoc.genesis__Send_Notification__c = false;
        bankDoc.genesis__Status__c = 'OPEN';
        bankDoc.Borrower_s_Email__c = 'qa+3855474713@payoff.com';
        bankDoc.Doc_Upload_Notification__c = false;
        bankDoc.Box_URl__c = 'test@abc.com';
        insert bankDoc;

        bankDoc.Box_URl__c = 'test2@abc.com';
        update bankDoc;

        genesis__Application_Document_Category__c bank1Doc = new genesis__Application_Document_Category__c();
        apdc.Name = 'Bank Statements1';
        bank1Doc.genesis__Active__c = true;
        bank1Doc.genesis__Application__c = genesis_applications_Obj.id;
        bank1Doc.genesis__Description__c = 'Credit Card Balances - Additional';
        bank1Doc.genesis__Document_Category__c = payStub.id;
        bank1Doc.genesis__Email__c = 'qa+3855474713@payoff.com';
        bank1Doc.genesis__Id__c = '1';
        bank1Doc.genesis__Parent_Application_Document_Category__c = bankDoc.id;
        bank1Doc.genesis__Parent_Id__c = '0';
        bank1Doc.genesis__Party_Type__c = pt.id;
        bank1Doc.genesis__Required__c = true;
        bank1Doc.genesis__Status__c = 'OPEN';
        bank1Doc.Doc_Upload_Notification__c = false;
        bank1Doc.Box_URl__c = 'test@abc.com';
        insert bank1Doc;

        List<String> apList = new List<String>();
        apList.add(genesis_applications_Obj.Id);
        loan__Batch_Process_Log__c logRec = new loan__Batch_Process_Log__c();
        logRec.Name = 'MW_PostDealRoomToFE';
        logRec.App_Ids__c = genesis_applications_Obj.Id;
        insert logRec;
        test.startTest();
        //MW_DocumentCategoryHandlerTEMP.processDataCate(apList);
        MW_DocumentCategoryHandlerTEMP mtp = new MW_DocumentCategoryHandlerTEMP(new List<string>{genesis_applications_Obj.Id});
        Database.executeBatch(mtp,1);
        test.stopTest();
    }
}