force-app/main/default/objects/Account/fields/ints__SSN__c.field-meta.xml
<CustomField>
    <fullName>ints__SSN__c</fullName>
    <label>SSN</label>
    <length>11</length>
    <maskChar>asterisk</maskChar>
    <maskType>ssn</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/Account/fields/loan__SOCIAL_SECURITY_NUMBER__c.field-meta.xml
<CustomField>
    <fullName>loan__SOCIAL_SECURITY_NUMBER__c</fullName>
    <label>SOCIAL_SECURITY_NUMBER</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TalxInt__c/TalxInt__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>TalxInt</label>
</CustomObject>

force-app/main/default/objects/TalxInt__c/fields/APPID__c.field-meta.xml
<CustomField>
    <fullName>APPID__c</fullName>
    <label>APPID</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TalxInt__c/fields/APPVER__c.field-meta.xml
<CustomField>
    <fullName>APPVER__c</fullName>
    <label>APPVER</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TalxInt__c/fields/DTCLIENT__c.field-meta.xml
<CustomField>
    <fullName>DTCLIENT__c</fullName>
    <label>DTCLIENT</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TalxInt__c/fields/LANGUAGE__c.field-meta.xml
<CustomField>
    <fullName>LANGUAGE__c</fullName>
    <label>LANGUAGE</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TalxInt__c/fields/USERID__c.field-meta.xml
<CustomField>
    <fullName>USERID__c</fullName>
    <label>USERID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TalxInt__c/fields/USERPASS__c.field-meta.xml
<CustomField>
    <fullName>USERPASS__c</fullName>
    <label>USERPASS</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TaxIntRequest.cls
public class TaxIntRequest {
    public static string getRequestbody(id accId, id appid){
        System.debug('App id ' + appId + ' AccId ' + accId);
        
        String requestBody = '<?xml version="1.0" encoding="UTF-8"?>'+
            '<?OFX OFXHEADER="200" VERSION="201" SECURITY="NONE" OLDFILEUID="NONE" NEWFILEUID="NONE"?>'+
            '<OFX>'+
            '<SIGNONMSGSRQV1>'+
            '<SONRQ>'+
            +Getusernamepassword()+
            ' </SONRQ>'+
            ' </SIGNONMSGSRQV1>'+
            '<TSVERMSGSRQV1>'+
            '<TSVTWNSELECTTRNRQ>'+
            ' <TRNUID>'+appId+'</TRNUID>'+
            ' <TRNPURPOSE>'+
            '             <CODE>PPCREDIT</CODE>'+
            ' </TRNPURPOSE>'+
            ' <TSVTWNSELECTRQ>'+
            +GetAccountInfo(accId)+
            '        <TEMPLATE_NAME>AutoGold</TEMPLATE_NAME>'+
            ' </TSVTWNSELECTRQ>'+
            '</TSVTWNSELECTTRNRQ>'+
            ' </TSVERMSGSRQV1>'+
            '</OFX>';
        return requestbody;
    }
    public static String Getusernamepassword(){
        TalxInt__c integrtn = TalxInt__c.getInstance();
        string USERID = integrtn.USERID__c;
        string USERPASS = integrtn.USERPASS__c;
        String DTCLIENT = integrtn.DTCLIENT__c;
        String LANG = integrtn.LANGUAGE__c;
        String APPID = integrtn.APPID__c;
        String APPVER = String.valueOf(integrtn.APPVER__c);
        
        XmlStreamWriter w = new XmlStreamWriter();
        // <DTCLIENT>20170612131212</DTCLIENT>
        w.writeStartElement(null,'DTCLIENT',null);
        Datetime now = Datetime.now();
        w.writeCharacters(now.format('yyyyMMddhhmmss'));
        w.writeEndElement();
        //   <USERID>PayoffIntUsrTest@50005</USERID>
        w.writeStartElement(null, 'USERID', null);
        w.writeCharacters(USERID);
        w.writeEndElement();
        
        //  <USERPASS>vQS4iNmTGawu7btqqMJNO2Bq4hQmdzOhlBd8</USERPASS>   
        w.writeStartElement(null, 'USERPASS', null);
        w.writeCharacters(USERPASS);
        w.writeEndElement();
        
        // <LANGUAGE>ENG</LANGUAGE>
        w.writeStartElement(null, 'LANGUAGE', null);
        w.writeCharacters(LANG);
        w.writeEndElement();
        
        //  <APPID>PAYOFF</APPID>
        w.writeStartElement(null, 'APPID', null);
        w.writeCharacters(APPID);
        w.writeEndElement();
        
        //  <APPVER>0001</APPVER>
        w.writeStartElement(null, 'APPVER', null);
        w.writeCharacters(APPVER);
        w.writeEndElement();
        
        String xmlOutput = w.getXmlString();
        w.close();
        return xmlOutput;
    }
    
    public static String GetAccountInfo(id accId){
        Account acc = [select id,
                        ints__SSN__c, loan__SOCIAL_SECURITY_NUMBER__c
                        FROM Account
                        WHERE id =: accId];
        XmlStreamWriter w = new XmlStreamWriter();
        //  <TSVEMPLOYEEID>799005153</TSVEMPLOYEEID>
        w.writeStartElement(null, 'TSVEMPLOYEEID', null);
        w.writeCharacters(String.valueOf(acc.loan__SOCIAL_SECURITY_NUMBER__c).replaceAll('-',''));
        w.writeEndElement();
        
        String xmlOutput = w.getXmlString();
        w.close();
        return xmlOutput;
    }
}