force-app/main/default/objects/Account/fields/ints__Yodlee_Password__c.field-meta.xml
<CustomField>
    <fullName>ints__Yodlee_Password__c</fullName>
    <description>Password for Yodlee Username.</description>
    <label>Yodlee_Password</label>
    <length>100</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/Account/fields/ints__Yodlee_Username__c.field-meta.xml
<CustomField>
    <fullName>ints__Yodlee_Username__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Username registered with Yodlee. This Username can have multiple bank accounts linked with Yodlee.</description>
    <label>Yodlee Username</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Credit_Policy__c/Credit_Policy__c.object-meta.xml
<CustomObject>
    <label>Credit Policy</label>
    <nameField>
        <label>Credit Policy Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Credit Policy</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Credit_Policy__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>genesis__Applications__c</referenceTo>
    <relationshipLabel>Credit Policy</relationshipLabel>
    <relationshipName>Credit_Policy</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/genesis__Application_Document_Category__c/genesis__Application_Document_Category__c.object-meta.xml
<CustomObject>
    <label>Application Document Category</label>
    <nameField>
        <label>Application Document Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application Document Category</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/genesis__Application_Document_Category__c/fields/genesis__Application__c.field-meta.xml
<CustomField>
    <fullName>genesis__Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>genesis__Applications__c</referenceTo>
    <relationshipLabel>Application Document Category</relationshipLabel>
    <relationshipName>Application_Document_Category</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/genesis__Application_Document_Category__c/fields/genesis__Required__c.field-meta.xml
<CustomField>
    <fullName>genesis__Required__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/genesis__Applications__c/genesis__Applications__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{0000000000}</displayFormat>
        <label>Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/genesis__Applications__c/fields/agentVerificationPendingFlag__c.field-meta.xml
<CustomField>
    <fullName>agentVerificationPendingFlag__c</fullName>
    <defaultValue>false</defaultValue>
    <label>agentVerificationPendingFlag</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ints__Yodlee_User_Credentials__c/ints__Yodlee_User_Credentials__c.object-meta.xml
<CustomObject>
    <label>Yodlee User Credentials</label>
    <nameField>
        <displayFormat>YUC-{00000000}</displayFormat>
        <label>Yodlee User Credentials Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Yodlee User Credentials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ints__Yodlee_User_Credentials__c/fields/ints__Account__c.field-meta.xml
<CustomField>
    <fullName>ints__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Yodlee User Credentials</relationshipLabel>
    <relationshipName>Yodlee_User_Credentials</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ints__Yodlee_User_Credentials__c/fields/ints__Yodlee_Password__c.field-meta.xml
<CustomField>
    <fullName>ints__Yodlee_Password__c</fullName>
    <label>Yodlee Password</label>
    <length>100</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <required>true</required>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/ints__Yodlee_User_Credentials__c/fields/ints__Yodlee_Username__c.field-meta.xml
<CustomField>
    <fullName>ints__Yodlee_Username__c</fullName>
    <label>Yodlee Username</label>
    <length>100</length>
    <maskChar>asterisk</maskChar>
    <maskType>lastFour</maskType>
    <required>true</required>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/ints__Yodlee_User_Credentials__c/fields/yodlee_Account_count__c.field-meta.xml
<CustomField>
    <fullName>yodlee_Account_count__c</fullName>
    <label>yodlee_Account_count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/MW_WebhookHelperTest.cls
@isTest
public with sharing class MW_WebhookHelperTest {

    static testMethod void selectedCreditPolicyDetailsTest() {
        Test.startTest();
        List<account> accList = MW_DataFactoryTest.createAccounts(1);
        insert accList;
        List<genesis__Applications__c> appList = MW_DataFactoryTest.createApplication(1, accList[0].Id);
        insert appList;

        Credit_Policy__c testCP = new Credit_Policy__c();
        testCP.Application__c = appList[0].Id;
        testCP.Name = 'test Credit Policy';
        insert testCP;

        Map<Id, Credit_Policy__c> helperResult = MW_WebhookHelper.selectedCreditPolicyDetails(new Set<String>{applist[0].id});
        System.assertEquals(1, helperResult.size());
        Test.stopTest();
    }

    static testMethod void appQueueDetailsTest(){
        Test.startTest();
        Group testGroup = new Group(Name='test group', Type='Queue');
        insert testGroup;

        System.runAs(new User(Id=UserInfo.getUserId()))
        {
        QueuesObject testQueue = new QueueSObject(QueueID = testGroup.Id, SObjectType = 'genesis__Applications__c');
        insert testQueue;
        }
        Map<String, String> appQueueResult = MW_WebhookHelper.appQueueDetails();
        System.assertEquals(true, appQueueResult.size()>0);
        Test.stopTest();
    }

    static testMethod void applicationDocumentCatTest(){
        Test.startTest();
        List<account> accList = MW_DataFactoryTest.createAccounts(1);
        insert accList;
        List<id> accLis = new List<id>();
        accLis.add(accList[0].Id);
        List<genesis__Applications__c> appList = MW_DataFactoryTest.createApplication(1, accList[0].Id);
        appList[0].agentVerificationPendingFlag__c = false;
        insert appList;

        genesis__Application_Document_Category__c appDocCategoryObj = new genesis__Application_Document_Category__c();
        appDocCategoryObj.Name = 'test';
        appDocCategoryObj.genesis__Required__c = true;
        appDocCategoryObj.genesis__Application__c = appList[0].Id;
        genesis__Application_Document_Category__c appDocCategoryObj2 = new genesis__Application_Document_Category__c();
        appDocCategoryObj.Name = 'test2';
        appDocCategoryObj.genesis__Required__c = true;
        appDocCategoryObj.genesis__Application__c = appList[0].Id;
        List<genesis__Application_Document_Category__c> appDocCategoryList = new List<genesis__Application_Document_Category__c>();
        appDocCategoryList.add(appDocCategoryObj);
        appDocCategoryList.add(appDocCategoryObj2);
        insert appDocCategoryList;
        Map<Id, Integer> applicationDocumentCatResult = MW_WebhookHelper.applicationDocumentCat(new List<String>{appList[0].Id});
        System.assertEquals(1, applicationDocumentCatResult.size());
        applicationDocumentCatResult = MW_WebhookHelper.applicationDocumentCat(new List<String>{appList[0].Id});
        System.assertEquals(1, applicationDocumentCatResult.get(appDocCategoryObj.genesis__Application__c));
        MW_WebhookHelper.updateBankApplicationDocCat(accLis);
        Test.stopTest();
    }

    static testMethod void applicationHasYodleeDetailsTest(){
        Test.startTest();
        List<account> accList = MW_DataFactoryTest.createAccounts(1);
        insert accList;
        ints__Yodlee_User_Credentials__c yodleeUserCredentialTest = new ints__Yodlee_User_Credentials__c();
        yodleeUserCredentialTest.ints__Account__c = accList[0].Id;
        yodleeUserCredentialTest.ints__Yodlee_Username__c = 'testUser';
        yodleeUserCredentialTest.ints__Yodlee_Password__c = 'testPassword';
        yodleeUserCredentialTest.yodlee_Account_count__c =1;
        insert yodleeUserCredentialTest;
        Map<Id, boolean> applicationHasYodleeDetailsResult = MW_WebhookHelper.applicationHasYodleeDetails(new List<String>{accList[0].Id});
        System.assertEquals(1, applicationHasYodleeDetailsResult.size());
        Test.stopTest();
    }
}