force-app/main/default/objects/Account/fields/Investor_Code__c.field-meta.xml
<CustomField>
    <fullName>Investor_Code__c</fullName>
    <label>Investor Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/genesis__Applications__c/genesis__Applications__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{0000000000}</displayFormat>
        <label>Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/genesis__Applications__c/fields/Delivery_Id__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Id__c</fullName>
    <externalId>true</externalId>
    <label>Delivery_Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/genesis__Applications__c/fields/Delivery_Partner_Code__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Partner_Code__c</fullName>
    <label>Delivery_Partner_Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/genesis__Applications__c/fields/Delivery_Processed_Date__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Processed_Date__c</fullName>
    <label>Delivery_Processed_Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/genesis__Applications__c/fields/Delivery_Status__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Status__c</fullName>
    <label>Delivery_Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/MW_DeliveryStatusHandlerTest.cls
@isTest
public with sharing class MW_DeliveryStatusHandlerTest {

    @isTest static void testHandleStatus() {
        Account acct = TestDataFactory.createTestAccount();
        insert acct;

        Account inv = TestDataFactory.createTestInvestor();
        inv.Investor_Code__c = 'TEST';
        insert inv;

        genesis__Applications__c app = TestDataFactory.createTestApplication(acct.Id, inv.Id, '9ffffff9-9fff-f999-ff99-9f9f9f9f9f9f',
        Date.today().addDays(2), 'agent_document_verification_pending');

        app.Delivery_Partner_Code__c = 'CRB';
        app.Delivery_Id__c = '1234567890';
        app.Delivery_Status__c = 'Approved';
        app.Delivery_Processed_Date__c = null;
        insert app;

        Test.startTest();
        MW_DeliveryStatusHandler.handleStatus(app);
        Test.stopTest();

        System.assert(app.Delivery_Processed_Date__c != null);
    }
}