force-app/main/default/objects/Account/fields/Investor_Code__c.field-meta.xml
<CustomField>
    <fullName>Investor_Code__c</fullName>
    <label>Investor Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/genesis__Application_Status_History__c/genesis__Application_Status_History__c.object-meta.xml
<CustomObject>
    <label>Application Status History</label>
    <nameField>
        <displayFormat>ASH-{00000000}</displayFormat>
        <label>Application Status History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Status History</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/genesis__Application_Status_History__c/fields/genesis__Application__c.field-meta.xml
<CustomField>
    <fullName>genesis__Application__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Application</label>
    <referenceTo>genesis__Applications__c</referenceTo>
    <relationshipLabel>Application Status History</relationshipLabel>
    <relationshipName>Application_Status_History</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/genesis__Application_Status_History__c/fields/genesis__New_Value__c.field-meta.xml
<CustomField>
    <fullName>genesis__New_Value__c</fullName>
    <description>New Status of application</description>
    <inlineHelpText>New Status of application</inlineHelpText>
    <label>New Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/genesis__Application_Status_History__c/fields/genesis__Old_value__c.field-meta.xml
<CustomField>
    <fullName>genesis__Old_value__c</fullName>
    <description>Old Status of application</description>
    <inlineHelpText>Old Status of application</inlineHelpText>
    <label>Old Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/genesis__Application_Status_History__c/fields/UpdatedByHMMW__c.field-meta.xml
<CustomField>
    <fullName>UpdatedByHMMW__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used for LOS 215 to flag records updated by Happymoney</description>
    <label>UpdatedByHMMW</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/genesis__Applications__c/genesis__Applications__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{0000000000}</displayFormat>
        <label>Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/MW_BackfillIncorrectTerminalStatusesTest.cls
@isTest
private class MW_BackfillIncorrectTerminalStatusesTest {
    @testSetup
	private static void testData() {
        String leadId = '9ffffff9-9fff-f999-ff99-9f9f9f9f9f9f';
		Account acct = TestDataFactory.createTestAccount();
		insert acct;

		Account inv = TestDataFactory.createTestInvestor();
		inv.Investor_Code__c = 'TEST';
		insert inv;

		//Path One Default Documents -> Declined
		genesis__Applications__c application = TestDataFactory.createTestApplication(acct.Id, inv.Id, leadId, Date.today().addDays(2), 'Expired');
		insert application;

		genesis__Application_Status_History__c defaultHistory = new genesis__Application_Status_History__c();
		defaultHistory.genesis__Application__c = application.id;
		defaultHistory.genesis__New_Value__c = 'Expired';
		defaultHistory.genesis__Old_value__c = 'Withdrawn';
		defaultHistory.UpdatedByHMMW__c = true;
		insert defaultHistory;
		
		genesis__Application_Status_History__c defaultHistory1 = new genesis__Application_Status_History__c();
		defaultHistory1.genesis__Application__c = application.id;
		defaultHistory1.genesis__New_Value__c = 'Withdrawn';
		defaultHistory1.genesis__Old_value__c = 'Expired';
		insert defaultHistory1;
		
		genesis__Application_Status_History__c defaultHistory2 = new genesis__Application_Status_History__c();
		defaultHistory2.genesis__Application__c = application.id;
		defaultHistory2.genesis__New_Value__c = 'Expired';
		defaultHistory2.genesis__Old_value__c = 'Withdrawn';
		defaultHistory2.UpdatedByHMMW__c = true;
		insert defaultHistory2;

	}
	private static testMethod void testUpdate(){
	    
	    Test.startTest();
	    String whereClause = 'where genesis__Old_value__c IN (\'Withdrawn\',\'Decline_Manual_Review\',\'Declined\') AND genesis__New_Value__c = \'Expired\' order by CreatedDate DESC';
        MW_BackfillIncorrectTerminalStatuses mb = new MW_BackfillIncorrectTerminalStatuses(whereClause,'Update');
        Database.executeBatch(mb,200);
	    Test.stopTest();
	    
	}
	private static testMethod void testDelete(){
	    
	    Test.startTest();
	    String whereClause = 'where (genesis__Old_value__c = \'Expired\' AND genesis__New_Value__c IN (\'Withdrawn\',\'Decline_Manual_Review\',\'Declined\') AND CreatedbyId = \''+UserInfo.getUserId()+'\' AND CreatedDate = TODAY) OR UpdatedByHMMW__c = true order by CreatedDate DESC';
        MW_BackfillIncorrectTerminalStatuses mb = new MW_BackfillIncorrectTerminalStatuses(whereClause,'Delete');
        Database.executeBatch(mb,200);
	    Test.stopTest();
	    
	}

}