force-app/main/default/objects/Account/fields/loan__Active__c.field-meta.xml
<CustomField>
    <fullName>loan__Active__c</fullName>
    <label>Active</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/loan__SOCIAL_SECURITY_NUMBER__c.field-meta.xml
<CustomField>
    <fullName>loan__SOCIAL_SECURITY_NUMBER__c</fullName>
    <label>SOCIAL_SECURITY_NUMBER</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/peer__First_Name__c.field-meta.xml
<CustomField>
    <fullName>peer__First_Name__c</fullName>
    <label>First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/peer__Last_Name__c.field-meta.xml
<CustomField>
    <fullName>peer__Last_Name__c</fullName>
    <label>Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BoxUrl__c/BoxUrl__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>BoxUrl</label>
</CustomObject>

force-app/main/default/objects/BoxUrl__c/fields/BoxService__c.field-meta.xml
<CustomField>
    <fullName>BoxService__c</fullName>
    <label>BoxService</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BoxUrl__c/fields/Boxurl__c.field-meta.xml
<CustomField>
    <fullName>Boxurl__c</fullName>
    <label>Boxurl</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CL_Document__c/CL_Document__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>CL_Generated Documents Names</description>
    <label>CL Document</label>
</CustomObject>

force-app/main/default/objects/CL_Document__c/fields/UploadedBOX__c.field-meta.xml
<CustomField>
    <fullName>UploadedBOX__c</fullName>
    <label>UploadedBOX</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ints__OAuth_Settings__c/ints__OAuth_Settings__c.object-meta.xml
<CustomObject>
    <label>OAuth Settings</label>
    <nameField>
        <displayFormat>OAUTH - {00000}</displayFormat>
        <label>OAuth Settings Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OAuth Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ints__OAuth_Settings__c/fields/ints__Access_Token_URL__c.field-meta.xml
<CustomField>
    <fullName>ints__Access_Token_URL__c</fullName>
    <label>Access Token URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/ints__OAuth_Settings__c/fields/ints__Consumer_Key__c.field-meta.xml
<CustomField>
    <fullName>ints__Consumer_Key__c</fullName>
    <label>Consumer Key</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ints__OAuth_Settings__c/fields/ints__Consumer_Secret__c.field-meta.xml
<CustomField>
    <fullName>ints__Consumer_Secret__c</fullName>
    <label>Consumer Secret</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ints__OAuth_Settings__c/fields/ints__Service_Name__c.field-meta.xml
<CustomField>
    <fullName>ints__Service_Name__c</fullName>
    <label>Service Name</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ints__OAuth_Token__c/ints__OAuth_Token__c.object-meta.xml
<CustomObject>
    <label>OAuth Token</label>
    <nameField>
        <label>OAuth Token Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OAuth Tokens</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ints__OAuth_Token__c/fields/ints__Is_Valid__c.field-meta.xml
<CustomField>
    <fullName>ints__Is_Valid__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Valid</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ints__OAuth_Token__c/fields/ints__OAuth_Settings__c.field-meta.xml
<CustomField>
    <fullName>ints__OAuth_Settings__c</fullName>
    <label>OAuth Settings</label>
    <referenceTo>ints__OAuth_Settings__c</referenceTo>
    <relationshipLabel>OAuth Tokens</relationshipLabel>
    <relationshipName>OAuth_Tokens</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ints__OAuth_Token__c/fields/ints__Refresh_Token__c.field-meta.xml
<CustomField>
    <fullName>ints__Refresh_Token__c</fullName>
    <label>Refresh Token</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ints__OAuth_Token__c/fields/ints__Token__c.field-meta.xml
<CustomField>
    <fullName>ints__Token__c</fullName>
    <label>Access Token</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/loan__Automated_Payment_Configuration__c/loan__Automated_Payment_Configuration__c.object-meta.xml
<CustomObject>
    <customHelpPage>loan__AutomatedPaymentConfigurationHelp</customHelpPage>
    <label>Automated Payment Configuration</label>
    <nameField>
        <displayFormat>APC-{0000000000}</displayFormat>
        <label>Automated Payment Configuration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Automated Payment Configuration</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/loan__Automated_Payment_Configuration__c/fields/Box_Folder_ID__c.field-meta.xml
<CustomField>
    <fullName>Box_Folder_ID__c</fullName>
    <label>Box Folder ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/loan__Automated_Payment_Configuration__c/fields/loan__Active__c.field-meta.xml
<CustomField>
    <fullName>loan__Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/loan__Automated_Payment_Configuration__c/fields/loan__Bank_Account__c.field-meta.xml
<CustomField>
    <fullName>loan__Bank_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bank Account</label>
    <referenceTo>loan__Bank_Account__c</referenceTo>
    <relationshipLabel>Automated Payment Configuration</relationshipLabel>
    <relationshipName>Automated_Payment_Configuration</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/loan__Automated_Payment_Configuration__c/fields/loan__Event__c.field-meta.xml
<CustomField>
    <fullName>loan__Event__c</fullName>
    <label>Event</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>LOAN PAYMENT</fullName>
            </value>
            <value>
                <fullName>LOAN REPAYMENT REFUND</fullName>
            </value>
            <value>
                <fullName>LOAN DISBURSAL</fullName>
            </value>
            <value>
                <fullName>INVESTOR WITHDRAWAL</fullName>
            </value>
            <value>
                <fullName>INVESTOR DEPOSIT</fullName>
            </value>
            <value>
                <fullName>INVESTOR PAYMENT</fullName>
            </value>
            <value>
                <fullName>FEE PAYMENT</fullName>
            </value>
            <value>
                <fullName>BROKER TRANSACTION</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/loan__Automated_Payment_Configuration__c/fields/loan__File_Type__c.field-meta.xml
<CustomField>
    <fullName>loan__File_Type__c</fullName>
    <label>File Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>TEXT</fullName>
            </value>
            <value>
                <fullName>CSV</fullName>
            </value>
            <value>
                <fullName>JSON</fullName>
            </value>
            <value>
                <fullName>XML</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/loan__Automated_Payment_Configuration__c/fields/loan__Filegen_Class__c.field-meta.xml
<CustomField>
    <fullName>loan__Filegen_Class__c</fullName>
    <label>Filegen Class</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/loan__Automated_Payment_Configuration__c/fields/loan__Folder_Name__c.field-meta.xml
<CustomField>
    <fullName>loan__Folder_Name__c</fullName>
    <inlineHelpText>Please create a folder with a name under the Documents tab. Then put the folder name here.</inlineHelpText>
    <label>Folder Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/loan__Automated_Payment_Configuration__c/fields/loan__Payment_Mode__c.field-meta.xml
<CustomField>
    <fullName>loan__Payment_Mode__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Mode</label>
    <referenceTo>loan__Payment_Mode__c</referenceTo>
    <relationshipLabel>Automated Payment Configuration</relationshipLabel>
    <relationshipName>Automated_Payment_Configuration</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/loan__Bank_Account__c/loan__Bank_Account__c.object-meta.xml
<CustomObject>
    <label>Bank Account</label>
    <nameField>
        <displayFormat>BA-{00000}</displayFormat>
        <label>Bank Account Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bank Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/loan__Bank_Account__c/fields/loan__Account__c.field-meta.xml
<CustomField>
    <fullName>loan__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bank Accounts</relationshipLabel>
    <relationshipName>Bank_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/loan__Bank_Account__c/fields/loan__Account_Type__c.field-meta.xml
<CustomField>
    <fullName>loan__Account_Type__c</fullName>
    <label>Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Savings</fullName>
            </value>
            <value>
                <fullName>Checking</fullName>
                <default>true</default>
                <label>Checking</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/loan__Bank_Account__c/fields/loan__Bank_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>loan__Bank_Account_Number__c</fullName>
    <label>Bank Account Number</label>
    <length>50</length>
    <maskChar>X</maskChar>
    <maskType>lastFour</maskType>
    <required>true</required>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/loan__Bank_Account__c/fields/loan__Bank_Name__c.field-meta.xml
<CustomField>
    <fullName>loan__Bank_Name__c</fullName>
    <label>Bank Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/loan__Bank_Account__c/fields/loan__Routing_Number__c.field-meta.xml
<CustomField>
    <fullName>loan__Routing_Number__c</fullName>
    <inlineHelpText>This is a nine digit number used to identify the financial institution in a transaction.</inlineHelpText>
    <label>Routing Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/loan__Bank_Account__c/fields/Unmasked_Bank_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Unmasked_Bank_Account_Number__c</fullName>
    <label>Unmasked Bank Account Number</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/loan__Org_Parameters__c/loan__Org_Parameters__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Org Parameters</label>
</CustomObject>

force-app/main/default/objects/loan__Org_Parameters__c/fields/Auto_Payer_Lending_Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Auto_Payer_Lending_Product_Name__c</fullName>
    <label>Auto Payer Lending Product Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/loan__Org_Parameters__c/fields/Manual_Payer_Lending_product_name__c.field-meta.xml
<CustomField>
    <fullName>Manual_Payer_Lending_product_name__c</fullName>
    <label>Manual Payer Lending product name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/loan__Payment_Mode__c/loan__Payment_Mode__c.object-meta.xml
<CustomObject>
    <label>Payment Mode</label>
    <nameField>
        <label>Payment Mode Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Mode</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/UploadNachaToBoxJobTest.cls
/*
*    This class tests these classes UploadNachaToBoxJob, LogsCalloutBatch and LogsCalloutBatchHelper
*    Tests if box url is updated in Description field on the Document object record which holds the NACHA file
*    Tests the success and failure of the BOX upload by checking the box url updates in Document
*/

@isTest
private class UploadNachaToBoxJobTest {
    @testSetup static void setupData() {
        CL_Document__c cdRec = CL_Document__c.getOrgDefaults();
        cdRec.UploadedBOX__c = 'UploadedBOX';
        upsert cdRec;
        
        BoxUrl__c box = new BoxUrl__c();
        box.BoxService__c='BoxSB.com';
        box.Boxurl__c='https://happymoney.app.box.com/';
        insert box;
    
        ints__OAuth_Settings__c oAuthName = new ints__OAuth_Settings__c();
        oAuthName.ints__Consumer_Key__c     = 'd998c67720u9bf2zg34ll4ogesxppsh7';
        oAuthName.ints__Consumer_Secret__c  = 'fSmCcCTwBxYHFpxElbYcJJywiw4CelFd';
        oAuthName.ints__Access_Token_URL__c = 'https://api.box.com/oauth2/token';
        oAuthName.ints__Service_Name__c     = 'BoxSB.com';
        insert oAuthName;
    
        ints__OAuth_Token__c authToken = new ints__OAuth_Token__c();
        authToken.ints__Token__c = 'yBE4Ci4BP9wa8D00AXH4rm9t9Y6blKrL';
        authToken.ints__Refresh_Token__c = 'NqDQcTONAkM0U1NJKVBeTi3bNmNHoDwS88TkS-quSK1RVn4tQKlWFBzDkxXy9woPq';
        authToken.ints__OAuth_Settings__c = oAuthName.id;
        authToken.ints__Is_Valid__c = true;
        insert authToken;
        
        loan__Org_Parameters__c loanorg = loan.CustomSettingsUtil.getOrgParameters();
        loanorg.Manual_Payer_Lending_product_name__c = 'Manual Payer';
        loanorg.Auto_Payer_Lending_Product_Name__c = 'Auto Payer';
        upsert loanorg;

        loan__Payment_Mode__c pm = new loan__Payment_Mode__c();
        pm.name = 'Wire';
        insert pm;
        
        Account invacc = new Account();
        invacc.peer__First_Name__c = 'Test';
        invacc.peer__Last_Name__c = 'MandatoryLastName';
        invacc.loan__SOCIAL_SECURITY_NUMBER__c = '123456789';
        insert invacc;
        
        loan__Bank_Account__c bainv = new loan__Bank_Account__c(loan__Bank_Account_Number__c = '12',
                                                 loan__Bank_Name__c = 'Some Bank',
                                                 loan__Routing_Number__c = '999999999',
                                                 loan__Account_Type__c = 'Checking',
                                                 loan__Active__c = true,
                                                 Unmasked_Bank_Account_Number__c = '99999999',
                                                 loan__Account__c = invacc.id);
        insert bainv;

        loan__Automated_Payment_Configuration__c apc = new loan__Automated_Payment_Configuration__c();
        apc.loan__Payment_Mode__c = pm.id;
        apc.loan__Bank_Account__c = bainv.id;
        apc.loan__Filegen_Class__c = 'CustomLoanPaymentTxnNACHAGen';
        apc.loan__Folder_Name__c = 'ACU';
        apc.loan__File_Type__c = 'CSV';
        apc.loan__Event__c = 'LOAN PAYMENT';
        apc.loan__Active__c = true;
        apc.Box_Folder_ID__c = '48673238292';
        insert apc;

        Document docRec = new Document();
        docRec.Body = Blob.valueOf('Some Text');
        docRec.ContentType = 'application/pdf';
        docRec.DeveloperName = 'my_document1';
        docRec.IsPublic = true;
        docRec.Name = 'My Document1';
        docRec.FolderId = [SELECT Id FROM Folder WHERE Name = 'ACU'].Id;
        insert docRec;

    }
    
    @isTest
    private static void testUploadJobScheduler(){
        String hour = String.valueOf(Datetime.now().hour());
        String min = String.valueOf(Datetime.now().minute() + 1); 
        String ss = String.valueOf(Datetime.now().second());
        
        //parse to cron expression
        String nextFireTime = ss + ' ' + min + ' ' + hour + ' * * ?';
        
            UploadNachaToBoxJob s = new UploadNachaToBoxJob(); 
            System.schedule('Job Started At ' + String.valueOf(Datetime.now()), nextFireTime, s);
    }
    
    @isTest
    private static void testUploadJobFailure(){
        Test.startTest();
            UploadNachaToBoxJob s = new UploadNachaToBoxJob(); // No Mock call to check if it fails when there's no box url in response
            Database.executeBatch(s,1);
        Test.stopTest(); 
        Document doc = [SELECT Id, Description FROM Document LIMIT 1];   
        system.assertEquals(null,doc.Description);
    }
    
    @isTest
    private static void testUploadJobSuccess(){
        Test.startTest();
            Test.setMock(HttpCalloutMock.class, new TestUploadFileToBoxMock()); // Mock call to check the success if there's a box url respone
            UploadNachaToBoxJob s = new UploadNachaToBoxJob(); 
            Database.executeBatch(s,1);
        Test.stopTest();   
        Document doc = [SELECT Id, Description FROM Document LIMIT 1];
        system.assertNotEquals(null,doc.Description); 
    }
}