force-app/main/default/objects/Account/fields/loan__Undeployed_Funds__c.field-meta.xml
<CustomField>
    <fullName>loan__Undeployed_Funds__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Total amount which is available to invest in loans.</description>
    <inlineHelpText>tracks the investor payout or investor funds while creating investor loan or while selling the loan</inlineHelpText>
    <label>Available Funds</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/loan__Investor_Loan__c/loan__Investor_Loan__c.object-meta.xml
<CustomObject>
    <description>This is a conjunction object to keep many to many relationships for loans and accounts (Investor)</description>
    <label>Investment Order</label>
    <nameField>
        <displayFormat>ILID-{0000000000}</displayFormat>
        <label>Investor Loan ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Investment Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/loan__Investor_Loan__c/fields/loan__Account__c.field-meta.xml
<CustomField>
    <fullName>loan__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This will be look up from Account</description>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Only investors should be selected.</errorMessage>
        <filterItems>
            <field>Account.loan__Investor__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Investment Orders</relationshipLabel>
    <relationshipName>Investors_Loans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/loan__Investor_Loan__c/fields/loan__Certificate_Rate__c.field-meta.xml
<CustomField>
    <fullName>loan__Certificate_Rate__c</fullName>
    <defaultValue>0.00</defaultValue>
    <description>The certificate rate for this investment. This is the rate which will be payable to the investor who buys invested in this loan and is entitled to its receivable stream.</description>
    <inlineHelpText>This is the rate of Interest earned by the investor.</inlineHelpText>
    <label>Certificate Rate</label>
    <precision>6</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/loan__Investor_Loan__c/fields/loan__Enabled_Flag__c.field-meta.xml
<CustomField>
    <fullName>loan__Enabled_Flag__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Shows if the record is enabled.</description>
    <label>Enabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/loan__Investor_Loan__c/fields/loan__Inv_Accrued_Interest_Amt__c.field-meta.xml
<CustomField>
    <fullName>loan__Inv_Accrued_Interest_Amt__c</fullName>
    <description>Payable Accrued Interest amount to investor</description>
    <inlineHelpText>This is the accrued Interest amount payable to the investor</inlineHelpText>
    <label>Accrued Interest</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/loan__Investor_Loan__c/fields/loan__Loan__c.field-meta.xml
<CustomField>
    <fullName>loan__Loan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is a look up value from Loan</description>
    <label>Loan</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>loan__Loan_Account__c.loan__Loan_Status__c</field>
            <operation>notContain</operation>
            <value>Pending Approval, Approved, Canceled, Partial Application</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>loan__Loan_Account__c</referenceTo>
    <relationshipLabel>Investment Orders</relationshipLabel>
    <relationshipName>Investors_Loans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/loan__Investor_Loan__c/fields/loan__Remaining_Investment_Amount__c.field-meta.xml
<CustomField>
    <fullName>loan__Remaining_Investment_Amount__c</fullName>
    <description>shows remaining investment amount for investment order.</description>
    <formula>loan__Investment_Amount__c -  loan__Principal_Amount_Paid__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Remaining Investment Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/loan__Investor_Loan__c/fields/loan__Service_Rate__c.field-meta.xml
<CustomField>
    <fullName>loan__Service_Rate__c</fullName>
    <defaultValue>0.00</defaultValue>
    <description>On this rate service charge will be charged to the investors for servicing loans, making note payments and maintaining the accounts.
The service charge paid by investors is on all amounts paid by the borrowers.</description>
    <inlineHelpText>Is the %age of the certificate rate which is earned by the P2P platform.</inlineHelpText>
    <label>Interest Service Rate</label>
    <precision>7</precision>
    <required>true</required>
    <scale>4</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/loan__Investor_Loan__c/fields/loan__Share__c.field-meta.xml
<CustomField>
    <fullName>loan__Share__c</fullName>
    <description>Describes the percent share of Investor in Loan amount</description>
    <label>Share</label>
    <precision>10</precision>
    <scale>7</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/loan__Investor_Loan__c/fields/loan__Status__c.field-meta.xml
<CustomField>
    <fullName>loan__Status__c</fullName>
    <description>Describes whether the record is in Active or Inactive state</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Closed - Written Off</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/loan__Investor_Loan__c/fields/peer__Number_of_Shares__c.field-meta.xml
<CustomField>
    <fullName>peer__Number_of_Shares__c</fullName>
    <formula>loan__Investment_Amount__c  /  loan__Loan__r.peer__Note_Type__r.peer__Denomination__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Number of Shares</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/loan__Investor_Loan_Account_Txns__c/loan__Investor_Loan_Account_Txns__c.object-meta.xml
<CustomObject>
    <label>Investor Loan Transaction</label>
    <nameField>
        <displayFormat>ILTID-{0000000000}</displayFormat>
        <label>Investor Loan Transaction ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Investor Loan Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/loan__Investor_Loan_Account_Txns__c/fields/loan__Investor_Loan__c.field-meta.xml
<CustomField>
    <fullName>loan__Investor_Loan__c</fullName>
    <label>Investment Order</label>
    <referenceTo>loan__Investor_Loan__c</referenceTo>
    <relationshipLabel>Investor Loan Transactions</relationshipLabel>
    <relationshipName>Investor_Loan_Txns</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/loan__Investor_Loan_Account_Txns__c/fields/loan__Transaction_Date__c.field-meta.xml
<CustomField>
    <fullName>loan__Transaction_Date__c</fullName>
    <label>Transaction Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/loan__Investor_Loan_Account_Txns__c/fields/peer__Investment_Order_Sale_Transaction__c.field-meta.xml
<CustomField>
    <fullName>peer__Investment_Order_Sale_Transaction__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>When transaction code is &quot;SALE&quot;, this field would have a reference of Investment Order Sale Transaction. Also when IOs are activated or deactivated due to purchase/sale this field would have a reference of Investment Order Sale Transaction.</description>
    <label>Investment Order Sale Transaction</label>
    <referenceTo>peer__Investment_Order_Sale_Transaction__c</referenceTo>
    <relationshipLabel>Investor Loan Transactions</relationshipLabel>
    <relationshipName>Investor_Loan_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/loan__Investor_Loan_Account_Txns__c/fields/peer__Sale_Price_Per_Share__c.field-meta.xml
<CustomField>
    <fullName>peer__Sale_Price_Per_Share__c</fullName>
    <label>Sale Price Per Share</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/peer__Investment_Order_Sale_Transaction__c/peer__Investment_Order_Sale_Transaction__c.object-meta.xml
<CustomObject>
    <label>Investment Order Sale Transaction</label>
    <nameField>
        <displayFormat>IST-{00000000}</displayFormat>
        <label>Investment Order Sale Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Investment Order Sale Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/peer__Investment_Order_Sale_Transaction__c/fields/peer__Add_Income_in_Price__c.field-meta.xml
<CustomField>
    <fullName>peer__Add_Income_in_Price__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If true, investor&apos;s earlier income is added in price.</description>
    <inlineHelpText>If true, investor&apos;s earlier income is added in price.</inlineHelpText>
    <label>Add Income in Price</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/peer__Investment_Order_Sale_Transaction__c/fields/peer__Buyer__c.field-meta.xml
<CustomField>
    <fullName>peer__Buyer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Buyer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Investment Order Sale Transactions</relationshipLabel>
    <relationshipName>Investment_Order_Sale_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/peer__Investment_Order_Sale_Transaction__c/fields/peer__Number_of_Shares__c.field-meta.xml
<CustomField>
    <fullName>peer__Number_of_Shares__c</fullName>
    <description>Number of shares of old IO which are being sold.</description>
    <inlineHelpText>Number of shares of old IO which are being sold.</inlineHelpText>
    <label>Number of Shares</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/peer__Investment_Order_Sale_Transaction__c/fields/peer__Price_per_Share__c.field-meta.xml
<CustomField>
    <fullName>peer__Price_per_Share__c</fullName>
    <label>Price per Share</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/peer__Investment_Order_Sale_Transaction__c/fields/peer__Transfer_Income__c.field-meta.xml
<CustomField>
    <fullName>peer__Transfer_Income__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If true, investor&apos;s earlier income is passed on to new investor.</description>
    <inlineHelpText>If true, investor&apos;s earlier income is passed on to new investor.</inlineHelpText>
    <label>Transfer Income</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/CustomIOSaleController.cls
public class CustomIOSaleController {

    public loan__Investor_Loan__c ioForSale {get; set;}
    public loan__Investor_Loan__c newIO {get; set;}
    
    public loan__Investor_Loan_Account_Txns__c txn {get; set;}
    
    public Date sysDate {get; set;}
    
    public boolean success {get; set;}
    public Decimal salePrice {get; set;}
    public boolean isPreview {get; set;}
    public Decimal numberOfSharesSold;

    public CustomIOSaleController(ApexPages.StandardController controller) {
        ioForSale = (loan__Investor_Loan__c) controller.getRecord();
        ioForSale = [SELECT Id, 
                            Name,
                            loan__Certificate_Rate__c,
                            loan__Service_Rate__c,
                            loan__Account__c,
                            loan__Loan__c,
                            loan__Share__c,
                            loan__Status__c,
                            peer__Number_Of_Shares__c,
                            loan__Enabled_Flag__c,
                            loan__Inv_Accrued_Interest_Amt__c, 
                            loan__Remaining_Investment_Amount__c
                            FROM loan__Investor_Loan__c WHERE Id = :ioForSale.Id LIMIT 1];
        sysDate = new loan.GlobalLoanUtilFacade().getCurrentSystemDate();
        
        newIO = new loan__Investor_Loan__c();
        txn = new loan__Investor_Loan_Account_Txns__c();
        txn.loan__Transaction_Date__c = sysDate;
        isPreview = false;
    }

    public PageReference preview() {
        
        try {
            
            //txn.peer__Sale_Price_Per_Share__c = salePrice/ioForSale.peer__Number_Of_Shares__c;          
            numberOfSharesSold = ioForSale.peer__Number_Of_Shares__c *(salePrice/100);
            system.debug(logginglevel.error,'numberOfSharesSold '+numberOfSharesSold );
            
            // harcoded the Proce per share = 1.
            txn.peer__Sale_Price_Per_Share__c = 1;
            isPreview = True;
            Account  buyer = [Select id,
                                name,
                                loan__Undeployed_Funds__c
                                from Account where id =:newIO.loan__Account__c];
            
            if (buyer.loan__Undeployed_Funds__c < (ioForSale.loan__Inv_Accrued_Interest_Amt__c + ioForSale.loan__Remaining_Investment_Amount__c)){
                isPreview = false;
                success = false;
                ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR, 'Sorry !! Insufficient funds'));
            }
                         
        } catch (Exception e) {
            success = false;
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR, 'Unexcepted error occured - ' + e.getMessage() + ' - ' + e.getLineNumber()));
        }
        
        return null;
    }
    
    public PageReference executeSale() {
        
        if(isPreview){
            
            peer.InvestorAPI7 api = peer.FractionalizationAPIFactory.getInvestorAPI7();  
            
            try {
                
                List<peer__Investment_Order_Sale_Transaction__c> invSaleTxnList = new List<peer__Investment_Order_Sale_Transaction__c>();
                                   
                peer__Investment_Order_Sale_Transaction__c saleTxn = new peer__Investment_Order_Sale_Transaction__c();
                saleTxn.peer__Buyer__c = newIO.loan__Account__c;
                saleTxn.peer__Number_Of_Shares__c = numberOfSharesSold;
                saleTxn.peer__Price_Per_Share__c = 1;
                saleTxn.peer__Transfer_Income__c = true;
                saleTxn.peer__Add_Income_in_Price__c = true;
                invSaleTxnList.add(saleTxn);
                                    
                api.sellInvestmentOrder(ioForSale.Id,invSaleTxnList, true);
                success = true;
                                
                ApexPages.addmessage(new ApexPages.message(ApexPages.severity.INFO, 'Transaction Successful.'));
                
                
            } catch (Exception e) {
                success = false;
                ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR, 'Unexcepted error occured - ' + e.getMessage() + ' - ' + e.getLineNumber()));
            }
            
        }else{
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.INFO, 'Preview sale details before executing sale.'));
        }
        
        return null;
    }
    

}