force-app/main/default/objects/Account/fields/no_of_shares_to_be_Sold__c.field-meta.xml
<CustomField>
    <fullName>no_of_shares_to_be_Sold__c</fullName>
    <inlineHelpText>Provided value is % of Shares that will be Sold to the Funding partner automatically.</inlineHelpText>
    <label>% of shares to be Sold.</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/loan__Bank_Account__c/loan__Bank_Account__c.object-meta.xml
<CustomObject>
    <label>Bank Account</label>
    <nameField>
        <displayFormat>BA-{00000}</displayFormat>
        <label>Bank Account Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bank Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/loan__Bank_Account__c/fields/loan__Account__c.field-meta.xml
<CustomField>
    <fullName>loan__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bank Accounts</relationshipLabel>
    <relationshipName>Bank_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/loan__Investor_Loan__c/loan__Investor_Loan__c.object-meta.xml
<CustomObject>
    <description>This is a conjunction object to keep many to many relationships for loans and accounts (Investor)</description>
    <label>Investment Order</label>
    <nameField>
        <displayFormat>ILID-{0000000000}</displayFormat>
        <label>Investor Loan ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Investment Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/loan__Investor_Loan__c/fields/Auto_Sale_Date__c.field-meta.xml
<CustomField>
    <fullName>Auto_Sale_Date__c</fullName>
    <formula>loan__Account__r.Number_of_Days__c + loan__Investor_Start_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Auto Sale Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/loan__Investor_Loan__c/fields/Buyer__c.field-meta.xml
<CustomField>
    <fullName>Buyer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Buyer&apos;s Account - To whom IOs will be sold after a certain point of time.</description>
    <inlineHelpText>Buyer&apos;s Account - To whom IOs will be sold after a certain point of time.</inlineHelpText>
    <label>Buyer</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.loan__Investor__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Investment Orders (Buyer)</relationshipLabel>
    <relationshipName>Investment_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/loan__Investor_Loan__c/fields/loan__Account__c.field-meta.xml
<CustomField>
    <fullName>loan__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This will be look up from Account</description>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Only investors should be selected.</errorMessage>
        <filterItems>
            <field>Account.loan__Investor__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Investment Orders</relationshipLabel>
    <relationshipName>Investors_Loans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/loan__Investor_Loan__c/fields/loan__Certificate_Rate__c.field-meta.xml
<CustomField>
    <fullName>loan__Certificate_Rate__c</fullName>
    <defaultValue>0.00</defaultValue>
    <description>The certificate rate for this investment. This is the rate which will be payable to the investor who buys invested in this loan and is entitled to its receivable stream.</description>
    <inlineHelpText>This is the rate of Interest earned by the investor.</inlineHelpText>
    <label>Certificate Rate</label>
    <precision>6</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/loan__Investor_Loan__c/fields/loan__Enabled_Flag__c.field-meta.xml
<CustomField>
    <fullName>loan__Enabled_Flag__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Shows if the record is enabled.</description>
    <label>Enabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/loan__Investor_Loan__c/fields/loan__Inv_Accrued_Interest_Amt__c.field-meta.xml
<CustomField>
    <fullName>loan__Inv_Accrued_Interest_Amt__c</fullName>
    <description>Payable Accrued Interest amount to investor</description>
    <inlineHelpText>This is the accrued Interest amount payable to the investor</inlineHelpText>
    <label>Accrued Interest</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/loan__Investor_Loan__c/fields/loan__Loan__c.field-meta.xml
<CustomField>
    <fullName>loan__Loan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is a look up value from Loan</description>
    <label>Loan</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>loan__Loan_Account__c.loan__Loan_Status__c</field>
            <operation>notContain</operation>
            <value>Pending Approval, Approved, Canceled, Partial Application</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>loan__Loan_Account__c</referenceTo>
    <relationshipLabel>Investment Orders</relationshipLabel>
    <relationshipName>Investors_Loans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/loan__Investor_Loan__c/fields/loan__Remaining_Investment_Amount__c.field-meta.xml
<CustomField>
    <fullName>loan__Remaining_Investment_Amount__c</fullName>
    <description>shows remaining investment amount for investment order.</description>
    <formula>loan__Investment_Amount__c -  loan__Principal_Amount_Paid__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Remaining Investment Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/loan__Investor_Loan__c/fields/loan__Service_Rate__c.field-meta.xml
<CustomField>
    <fullName>loan__Service_Rate__c</fullName>
    <defaultValue>0.00</defaultValue>
    <description>On this rate service charge will be charged to the investors for servicing loans, making note payments and maintaining the accounts.
The service charge paid by investors is on all amounts paid by the borrowers.</description>
    <inlineHelpText>Is the %age of the certificate rate which is earned by the P2P platform.</inlineHelpText>
    <label>Interest Service Rate</label>
    <precision>7</precision>
    <required>true</required>
    <scale>4</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/loan__Investor_Loan__c/fields/loan__Share__c.field-meta.xml
<CustomField>
    <fullName>loan__Share__c</fullName>
    <description>Describes the percent share of Investor in Loan amount</description>
    <label>Share</label>
    <precision>10</precision>
    <scale>7</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/loan__Investor_Loan__c/fields/loan__Status__c.field-meta.xml
<CustomField>
    <fullName>loan__Status__c</fullName>
    <description>Describes whether the record is in Active or Inactive state</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Closed - Written Off</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/loan__Investor_Loan__c/fields/peer__Number_of_Shares__c.field-meta.xml
<CustomField>
    <fullName>peer__Number_of_Shares__c</fullName>
    <formula>loan__Investment_Amount__c  /  loan__Loan__r.peer__Note_Type__r.peer__Denomination__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Number of Shares</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/loan__Investor_Loan_Account_Txns__c/loan__Investor_Loan_Account_Txns__c.object-meta.xml
<CustomObject>
    <label>Investor Loan Transaction</label>
    <nameField>
        <displayFormat>ILTID-{0000000000}</displayFormat>
        <label>Investor Loan Transaction ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Investor Loan Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/loan__Investor_Loan_Account_Txns__c/fields/loan__Investor_Loan__c.field-meta.xml
<CustomField>
    <fullName>loan__Investor_Loan__c</fullName>
    <label>Investment Order</label>
    <referenceTo>loan__Investor_Loan__c</referenceTo>
    <relationshipLabel>Investor Loan Transactions</relationshipLabel>
    <relationshipName>Investor_Loan_Txns</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/loan__Loan_Account__c.object-meta.xml
<CustomObject>
    <description>Lending Account</description>
    <label>CL Contract</label>
    <nameField>
        <displayFormat>LAI-{00000000}</displayFormat>
        <label>CL Contract ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CL Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/loan__Loan_Account__c/fields/Auto_Sale_Date__c.field-meta.xml
<CustomField>
    <fullName>Auto_Sale_Date__c</fullName>
    <label>Auto Sale Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/Buyer__c.field-meta.xml
<CustomField>
    <fullName>Buyer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Buyer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>CL Contracts (Buyer)</relationshipLabel>
    <relationshipName>CL_Contracts2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/Effective_Date_for_AutoSale__c.field-meta.xml
<CustomField>
    <fullName>Effective_Date_for_AutoSale__c</fullName>
    <description>for assignment of investors in bulk</description>
    <label>Effective Date for AutoSale</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/Investor_Account__c.field-meta.xml
<CustomField>
    <fullName>Investor_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Investor Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>CL Contracts (Investor Account)</relationshipLabel>
    <relationshipName>CL_Contracts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/loan__Account__c.field-meta.xml
<CustomField>
    <fullName>loan__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Please choose a account, which will be associated as a customer on this lending account.
You can create a new account, from the lookup window by clicking on new or select the existing account from the lookup.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Loan_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/peer__Number_of_Shares__c.field-meta.xml
<CustomField>
    <fullName>peer__Number_of_Shares__c</fullName>
    <formula>loan__Loan_Amount__c /  peer__Note_Type__r.peer__Denomination__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Number of Shares</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/peer__Investment_Order_Sale_Transaction__c/peer__Investment_Order_Sale_Transaction__c.object-meta.xml
<CustomObject>
    <label>Investment Order Sale Transaction</label>
    <nameField>
        <displayFormat>IST-{00000000}</displayFormat>
        <label>Investment Order Sale Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Investment Order Sale Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/peer__Investment_Order_Sale_Transaction__c/fields/peer__Number_of_Shares__c.field-meta.xml
<CustomField>
    <fullName>peer__Number_of_Shares__c</fullName>
    <description>Number of shares of old IO which are being sold.</description>
    <inlineHelpText>Number of shares of old IO which are being sold.</inlineHelpText>
    <label>Number of Shares</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/AutoSale.cls
/* ****************Modification History******************
 * Modified by      Date            JIRA number
 *     Pallavi      2019/12/13    LOS-185/186 auto sale in bulk
 ******************Modification History******************/
global class AutoSale implements Database.batchable<sObject>,Schedulable{
            
    String query;
    String Status = 'Active';
    
    public loan__Investor_Loan__c ioForSale;
    Date CurrentSystemDate = new loan.GlobalLoanUtilFacade().getCurrentSystemDate();
    loan__Investor_Loan__c newIO = new loan__Investor_Loan__c();
    loan__Investor_Loan_Account_Txns__c txn = new loan__Investor_Loan_Account_Txns__c();

    global AutoSale (){
        query = 'select id,name,loan__Certificate_Rate__c,Buyer__c,loan__Account__r.no_of_shares_to_be_Sold__c,loan__Service_Rate__c,loan__Account__c,loan__Loan__c,loan__Loan__r.Investor_Account__c,loan__Share__c,loan__Status__c, '+
                ' peer__Number_Of_Shares__c,loan__Enabled_Flag__c,loan__Inv_Accrued_Interest_Amt__c, loan__Remaining_Investment_Amount__c from loan__Investor_Loan__c where Buyer__c != null and loan__Loan__r.Effective_Date_for_AutoSale__c =: CurrentSystemDate '+   //(LOS-185/186)                   
                ' and loan__Status__c =\''+String.escapeSingleQuotes(Status)+'\'';
        
        System.debug(logginglevel.error,'query+++'+query);      //(Auto_Sale_Date__c =: CurrentSystemDate) HM does not use this anymore
                
    }
    
    global AutoSale (String query){
        
        this.query = query; 
    }
    
    global void execute(SchedulableContext sc) {
        
        AutoSale b = new AutoSale ();
        Database.executeBatch(b,1);
    
    }
    
    global Database.QueryLocator start(Database.BatchableContext bc){
                              
        System.debug('Query'+query);    
        return Database.getQueryLocator(query);
    
    }
    
    global void execute(Database.BatchableContext BC, List<sObject> scope){
        
        System.debug('----Method execute(+)scope----'+ scope);
        List<loan__Investor_Loan__c> listOfIOs = (List<loan__Investor_Loan__c>)scope;
        ioForSale = listOfIOs[0];
        
        /* LOS-185/186*/
        Set<id> contractID = new Set<id>();
        for(loan__Investor_Loan__c IO : listOfIOs)
            contractID.add(IO.loan__Loan__c);
        
        List<loan__loan_account__c> loan = [Select id,Investor_Account__c from loan__loan_account__c where id in: contractID];
        Map<id,loan__loan_account__c> maploan = new Map<id,loan__loan_account__c>();
        for(loan__loan_account__c loans : loan)
            maploan.put(loans.id,loans);
        
        
        
        Map<id,loan__loan_account__c> MaptoUpdate = new Map<id,loan__loan_account__c>();
        List<loan__loan_account__c> toUpdate = new List<loan__loan_account__c>();
        
        Set<Id> apsID = new Set<Id>();
        
        loan__Automated_Payment_Configuration__c apc = [Select id,loan__Payment_Mode__c FROM loan__Automated_Payment_Configuration__c where
                                                       loan__Bank_Account__r.loan__Account__c =: ioForSale.Buyer__c LIMIT 1];
        
        Id paymentMode = apc.loan__Payment_Mode__c;
        
        /* LOS-185/186*/
        
        List<peer__Investment_Order_Sale_Transaction__c> invSaleTxnList = new List<peer__Investment_Order_Sale_Transaction__c>();
        txn.loan__Transaction_Date__c = CurrentSystemDate ;
                
        for(loan__Investor_Loan__c IOs : listOfIOs){
            
            peer.InvestorAPI7 api = peer.FractionalizationAPIFactory.getInvestorAPI7();                                          
            peer__Investment_Order_Sale_Transaction__c saleTxn = new peer__Investment_Order_Sale_Transaction__c();
            saleTxn.peer__Buyer__c = ioForSale.Buyer__c;
            saleTxn.peer__Number_Of_Shares__c = ioForSale.peer__Number_Of_Shares__c *(ioForSale.loan__Account__r.no_of_shares_to_be_Sold__c/100);
            saleTxn.peer__Price_Per_Share__c = 1;
            saleTxn.peer__Transfer_Income__c = True;
            saleTxn.peer__Add_Income_in_Price__c = False;
            invSaleTxnList.add(saleTxn);
            
            try{
            if(!test.isRunningTest())                    
            api.sellInvestmentOrder(ioForSale.Id,invSaleTxnList, true); 
            }
            catch(Exception ex){    // LOS-185/186
            loan__Batch_Process_Log__c bplog = new loan__Batch_Process_Log__c();
            bplog.loan__Origin__c = 'AutoSale' ;
            bplog.loan__Message__c = 'Error: ' + ex.getLineNumber() + ' Desc. ' + ex.getMessage()+' Stack: '+ex.getStackTraceString();
            bplog.loan__Type__c = 'Exception';
            bplog.loan__Time__c = DateTime.now();
            insert bplog;
            
            //throw ex;
            }   
            
            /* LOS-185/186*/
            loan__loan_account__c contract = maploan.get(IOs.loan__Loan__c);
            loan__loan_account__c updatedContract = new loan__loan_account__c();
            updatedContract = contract;
            updatedContract.Investor_Account__c = ioForSale.Buyer__c;
            
            toUpdate.add(updatedContract);
            apsID.add(updatedContract.id);
            
        }
        List<loan__Automated_Payment_Setup__c> aps = [select id,loan__Payment_Mode__c from loan__Automated_Payment_Setup__c where
                                                     loan__CL_Contract__c in: apsId];
        
        List<loan__Automated_Payment_Setup__c> toUpdateAPS = new List<loan__Automated_Payment_Setup__c>();
        
        for(loan__Automated_Payment_Setup__c aps1 :aps){
            aps1.loan__Payment_Mode__c = paymentMode;
            toUpdateAPS.add(aps1);
        }
        if(toUpdate.size()>0 && !toUpdate.isEmpty())
            Database.update(toUpdate);
        if(toUpdateAPS.size()>0 && !toUpdateAPS.isEmpty())
            update toUpdateAPS;
        /* LOS-185/186*/
        
    } 
    
    public void finish(Database.BatchableContext BC){

    }
    
}