force-app/main/default/objects/Account/fields/Payoff_UID__c.field-meta.xml
<CustomField>
    <fullName>Payoff_UID__c</fullName>
    <label>Payoff UID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Adverse__c/Adverse__c.object-meta.xml
<CustomObject>
    <label>Adverse</label>
    <nameField>
        <label>Adverse  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Adverse</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Adverse__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Adverse</relationshipLabel>
    <relationshipName>Adverse</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Adverse__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>genesis__Applications__c</referenceTo>
    <relationshipLabel>Adverse</relationshipLabel>
    <relationshipName>Adverse</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Adverse_Actions__c/Adverse_Actions__c.object-meta.xml
<CustomObject>
    <label>Adverse Actions</label>
    <nameField>
        <label>Adverse Actions Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Adverse Actions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Adverse_Actions__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Adverse Actions</relationshipLabel>
    <relationshipName>Adverse_Actions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Adverse_Actions__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>genesis__Applications__c</referenceTo>
    <relationshipLabel>Adverse Actions</relationshipLabel>
    <relationshipName>Adverse_Actions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/genesis__Applications__c/genesis__Applications__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{0000000000}</displayFormat>
        <label>Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/genesis__Applications__c/fields/genesis__Account__c.field-meta.xml
<CustomField>
    <fullName>genesis__Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Applications_account</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/genesis__Applications__c/fields/genesis__Status__c.field-meta.xml
<CustomField>
    <fullName>genesis__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>APPROVED - APPROVED</fullName>
            </value>
            <value>
                <fullName>APPROVED - CONVERTED TO CONTRACT</fullName>
            </value>
            <value>
                <fullName>APPROVED - DOCUMENT CHECK</fullName>
            </value>
            <value>
                <fullName>NEW - CREDIT PULLED</fullName>
            </value>
            <value>
                <fullName>NEW - ENTERED</fullName>
                <default>true</default>
                <label>NEW - ENTERED</label>
            </value>
            <value>
                <fullName>NEW - IN CREDIT CHECK</fullName>
            </value>
            <value>
                <fullName>NEW - IN REVIEW</fullName>
            </value>
            <value>
                <fullName>NEW - PRICING GENERATED</fullName>
            </value>
            <value>
                <fullName>NEW - SCORECARD GENERATED</fullName>
            </value>
            <value>
                <fullName>NEW - CHECKLIST GENERATED</fullName>
            </value>
            <value>
                <fullName>NEW - VEHICLE VALUATION REQUIRED</fullName>
            </value>
            <value>
                <fullName>REJECTED</fullName>
            </value>
            <value>
                <fullName>PULL CREDIT</fullName>
            </value>
            <value>
                <fullName>Default Documents</fullName>
            </value>
            <value>
                <fullName>offer_accepted</fullName>
            </value>
            <value>
                <fullName>offer_shown</fullName>
            </value>
            <value>
                <fullName>kba_success</fullName>
            </value>
            <value>
                <fullName>kba_fail</fullName>
            </value>
            <value>
                <fullName>agent_document_verification_pending</fullName>
            </value>
            <value>
                <fullName>agent_verification_pending</fullName>
            </value>
            <value>
                <fullName>agent_verified</fullName>
            </value>
            <value>
                <fullName>docusign_loan_docs_sent</fullName>
            </value>
            <value>
                <fullName>docusign_loan_docs_complete</fullName>
            </value>
            <value>
                <fullName>pre_funding</fullName>
            </value>
            <value>
                <fullName>Approved for funding</fullName>
            </value>
            <value>
                <fullName>funded</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Stacker_Check_Passed</fullName>
            </value>
            <value>
                <fullName>Redecision_Required</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/genesis__Applications__c/fields/Payoff_UID__c.field-meta.xml
<CustomField>
    <fullName>Payoff_UID__c</fullName>
    <formula>Lead_ID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Payoff UID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/loan__Batch_Process_Log__c/loan__Batch_Process_Log__c.object-meta.xml
<CustomObject>
    <label>Batch Process Log</label>
    <nameField>
        <label>Apex Batch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Batch Process Log</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/loan__Batch_Process_Log__c/fields/loan__Message__c.field-meta.xml
<CustomField>
    <fullName>loan__Message__c</fullName>
    <label>Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Score_Factors__c/Score_Factors__c.object-meta.xml
<CustomObject>
    <label>Score Factors</label>
    <nameField>
        <label>Score Factors Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Score Factors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Score_Factors__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Score Factors</relationshipLabel>
    <relationshipName>Score_Factors</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Score_Factors__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>genesis__Applications__c</referenceTo>
    <relationshipLabel>Score Factors</relationshipLabel>
    <relationshipName>Score_Factors</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AdverseScorectrl.cls
public class AdverseScorectrl {
     public static boolean isADVTrgExecuting = true;
    public AdverseScorectrl(boolean isExecuting){
        isADVTrgExecuting = isExecuting;
    }    
    
    public Static Void Adversefuturemethod(Id ApplicationId){
        if(isADVTrgExecuting){            
            System.debug('isADVTrgExecuting....'+ isADVTrgExecuting);
            Adversemethodcall(ApplicationId); 
            isADVTrgExecuting = false;
        }
    }
  /*  @InvocableMethod
    public static void AdvMethod(List<ID> AppId){
        
        Adversefuturemethod(AppId);
    }
    */
    
    @future(callout=true)
    public static void Adversemethodcall(Id AppId){
        List<Adverse__c> lstNoHitData=new List<Adverse__c>();
        List<Adverse_Actions__c> lstAdvData=new List<Adverse_Actions__c>();
        List<Score_Factors__c>  lstSFData=new List<Score_Factors__c>();
        genesis__Applications__c app = [SELECT Id,genesis__Account__c,
                                              genesis__Account__r.Payoff_UID__c,
                                              genesis__Status__c
                                              FROM genesis__Applications__c 
                                              WHERE id =:AppId LIMIT 1];
        
        if(app != null) {
            system.debug(app);
            
            AdverseScoreResponse res = new AdverseScoreResponse();            
            AdverseScoreIntegration adv=new AdverseScoreIntegration();
            try{
                res=adv.getAdvScData(app.genesis__Account__r.Payoff_UID__c,app.genesis__Account__c,app.id);
                
                lstSFData= res.scf;
                lstAdvData=res.adv;
                lstNoHitData=res.no_hit;
                /*insert lstAdvData;
                insert lstSFData;
                insert lstNoHitData;*/
                            
                List<Adverse_Actions__c> advActionData = [Select Id from Adverse_Actions__c where Application__c = :app.Id and
                                                Account__c = :app.genesis__Account__c];
                System.debug('....Delete List... '+ advActionData );
                if(! advActionData.isEmpty())
                    delete advActionData ;
                insert lstAdvData;
                
                List<Score_Factors__c> SFData = [Select Id from Score_Factors__c where Application__c = :app.Id and
                                                Account__c = :app.genesis__Account__c];
                System.debug('....Delete SFData List... '+ SFData );
                if(! SFData.isEmpty())
                    delete SFData ;
                insert lstSFData;            
                
                List<Adverse__c> advr = [Select Id from Adverse__c where Application__c = :app.Id and
                                                Account__c = :app.genesis__Account__c]; 
                System.debug('....Delete adv List... '+ advr );
                if(! advr.isEmpty())
                    delete advr;
                insert lstNoHitData; 
            }
            catch(Exception ex){
            loan__batch_process_log__c logs = new loan__batch_process_log__c(loan__Message__c='Error in Adverse Action:  '+ex.getlinenumber()+'Error: '+ex.getMessage());
            insert logs;
            System.debug('Exception: '+ex.getMessage());
        } 
        }
    }
    
}