force-app/main/default/objects/dsfs__DocuSign_Status__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>genesis__Applications__c</referenceTo>
    <relationshipLabel>DocuSign Status</relationshipLabel>
    <relationshipName>DocuSign_Status</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/dsfs__DocuSign_Status__c/fields/dsfs__Completed_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>dsfs__Completed_Date_Time__c</fullName>
    <label>Completed</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/dsfs__DocuSign_Status__c/fields/Lead_Id__c.field-meta.xml
<CustomField>
    <fullName>Lead_Id__c</fullName>
    <formula>Application__r.Lead_ID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Lead_Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/genesis__Applications__c/genesis__Applications__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{0000000000}</displayFormat>
        <label>Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/genesis__Applications__c/fields/Anniversary_Date__c.field-meta.xml
<CustomField>
    <fullName>Anniversary_Date__c</fullName>
    <label>Anniversary Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/genesis__Applications__c/fields/DocuSign_Sign_Date__c.field-meta.xml
<CustomField>
    <fullName>DocuSign_Sign_Date__c</fullName>
    <label>DocuSign Sign Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/genesis__Applications__c/fields/genesis__Status__c.field-meta.xml
<CustomField>
    <fullName>genesis__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>APPROVED - APPROVED</fullName>
            </value>
            <value>
                <fullName>APPROVED - CONVERTED TO CONTRACT</fullName>
            </value>
            <value>
                <fullName>APPROVED - DOCUMENT CHECK</fullName>
            </value>
            <value>
                <fullName>NEW - CREDIT PULLED</fullName>
            </value>
            <value>
                <fullName>NEW - ENTERED</fullName>
                <default>true</default>
                <label>NEW - ENTERED</label>
            </value>
            <value>
                <fullName>NEW - IN CREDIT CHECK</fullName>
            </value>
            <value>
                <fullName>NEW - IN REVIEW</fullName>
            </value>
            <value>
                <fullName>NEW - PRICING GENERATED</fullName>
            </value>
            <value>
                <fullName>NEW - SCORECARD GENERATED</fullName>
            </value>
            <value>
                <fullName>NEW - CHECKLIST GENERATED</fullName>
            </value>
            <value>
                <fullName>NEW - VEHICLE VALUATION REQUIRED</fullName>
            </value>
            <value>
                <fullName>REJECTED</fullName>
            </value>
            <value>
                <fullName>PULL CREDIT</fullName>
            </value>
            <value>
                <fullName>Default Documents</fullName>
            </value>
            <value>
                <fullName>offer_accepted</fullName>
            </value>
            <value>
                <fullName>offer_shown</fullName>
            </value>
            <value>
                <fullName>kba_success</fullName>
            </value>
            <value>
                <fullName>kba_fail</fullName>
            </value>
            <value>
                <fullName>agent_document_verification_pending</fullName>
            </value>
            <value>
                <fullName>agent_verification_pending</fullName>
            </value>
            <value>
                <fullName>agent_verified</fullName>
            </value>
            <value>
                <fullName>docusign_loan_docs_sent</fullName>
            </value>
            <value>
                <fullName>docusign_loan_docs_complete</fullName>
            </value>
            <value>
                <fullName>pre_funding</fullName>
            </value>
            <value>
                <fullName>Approved for funding</fullName>
            </value>
            <value>
                <fullName>funded</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Stacker_Check_Passed</fullName>
            </value>
            <value>
                <fullName>Redecision_Required</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/genesis__Applications__c/fields/Lead_ID__c.field-meta.xml
<CustomField>
    <fullName>Lead_ID__c</fullName>
    <description>This is the LEAD GUID received from FE</description>
    <externalId>true</externalId>
    <label>Lead ID</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/genesis__Applications__c/fields/Loan_Doc_Signed_On__c.field-meta.xml
<CustomField>
    <fullName>Loan_Doc_Signed_On__c</fullName>
    <label>Loan Doc Signed On</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/loan__Batch_Process_Log__c/loan__Batch_Process_Log__c.object-meta.xml
<CustomObject>
    <label>Batch Process Log</label>
    <nameField>
        <label>Apex Batch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Batch Process Log</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/loan__Batch_Process_Log__c/fields/loan__Message__c.field-meta.xml
<CustomField>
    <fullName>loan__Message__c</fullName>
    <label>Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/loan__Batch_Process_Log__c/fields/loan__Origin__c.field-meta.xml
<CustomField>
    <fullName>loan__Origin__c</fullName>
    <label>Origin</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Start Of Day Process</fullName>
            </value>
            <value>
                <fullName>End of Day Process</fullName>
            </value>
            <value>
                <fullName>Month End Process</fullName>
            </value>
            <value>
                <fullName>Year End Process</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/loan__Batch_Process_Log__c/fields/loan__Time__c.field-meta.xml
<CustomField>
    <fullName>loan__Time__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <label>Time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/loan__Batch_Process_Log__c/fields/loan__Type__c.field-meta.xml
<CustomField>
    <fullName>loan__Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Exception</fullName>
            </value>
            <value>
                <fullName>Warning</fullName>
            </value>
            <value>
                <fullName>Info</fullName>
            </value>
            <value>
                <fullName>Result</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/MW_DocuSignTriggerHandler.cls
public class MW_DocuSignTriggerHandler {

    public static void createDocumentCategory(List<dsfs__DocuSign_Status__c> listDocs)
    {
        try{

            Map<ID,Date> SignedCompleteMap = new Map<ID,Date>();
            Map<String,String> EnvelopeMap = new Map<String,String>();

            for(dsfs__DocuSign_Status__c dsStatus :listDocs){
                SignedCompleteMap.put(dsStatus.Application__c,dsStatus.dsfs__Completed_Date_Time__c.date());
            }

            if(SignedCompleteMap.size()>0)
                updatSignedDates(SignedCompleteMap);

            for(dsfs__DocuSign_Status__c dsStatus :listDocs){
                MW_DocuSigneSignedDocuments.postDocumentDetails(dsStatus.dsfs__DocuSign_Envelope_ID__c, dsStatus.Application__c, dsStatus.Lead_Id__c);
            }

        }catch (Exception ex){
            loan__Batch_Process_Log__c bplog = new loan__Batch_Process_Log__c();
            bplog.loan__Origin__c = 'Docusign Status' ;
            bplog.loan__Message__c = 'Error: ' + ex.getLineNumber() + ' Desc. ' + ex.getMessage()+' Stack: '+ex.getStackTraceString();
            bplog.loan__Type__c = 'Exception';
            bplog.loan__Time__c = DateTime.now();
            insert bplog;
            throw ex;
        }
    }

    /*
        Method update the Anniversary_Date DocuSign_Sign_Date on Application.
     */
    public static void updatSignedDates(Map<ID,Date> SignedCompleteMap){


        List<genesis__Applications__c> lstApp  = new List<genesis__Applications__c>();
        for(genesis__Applications__c app :[SELECT Id, Anniversary_Date__c, DocuSign_Sign_Date__c, Loan_Doc_Signed_On__c
        FROM genesis__Applications__c where Id=:SignedCompleteMap.keySet()]){
            if(SignedCompleteMap.get(app.Id)!=null){
                Date signedDate  = SignedCompleteMap.get(app.Id);
                CustomTriggerOnApplicationHandler ctdh = new CustomTriggerOnApplicationHandler();
                Date orignationDt      = ctdh.addWorkingDaysTodate(signedDate,3);
                system.debug('orignationDt=' + orignationDt);
                Date anniversaryDate      = orignationDt.addMonths(1);
                system.debug('anniversaryDate=' + anniversaryDate);
                //Set anniversary date March 1st instead of Feb 28.
                if(orignationDt.month() == 1 && (orignationDt.day() == 29 || orignationDt.day() == 30 || orignationDt.day() == 31))
                {
                    anniversaryDate = anniversaryDate.addDays(1);
                    system.debug('anniversaryDate inside if=' + anniversaryDate);
                }
                app.Anniversary_Date__c   = anniversaryDate.addDays(calcdate(anniversaryDate));
                system.debug('app.Anniversary_Date__c=' + app.Anniversary_Date__c);
                app.DocuSign_Sign_Date__c = signedDate;
                app.Loan_Doc_Signed_On__c = signedDate;
                if(app.Id!='a6h4F0000004ZzSQAU' || app.Id!='a6h4F0000004ZzXQAU'|| app.Id!='a6h4F0000004ZzcQAE' || app.Id!='a6h4F0000004ZzhQAE'){
                    app.genesis__Status__c    =  'docusign_loan_docs_complete';
                }
                lstApp.add(app);
            }
        }
        if(lstApp.size()>0) update lstApp;
    }

    public static Id getApplicationId(string attName){
        if(attName!=null & attName!='') {
            string strAppId = attName.substringBefore('.');
            Id appId        = strAppId.substring(strAppId.length()-18, strAppId.length());
            system.debug('... Application Id >> ' + appId);
            return appId;
        }
        return null;
    }

    public static Integer calcdate(Date SignDate){
        Integer numberofDays = 0;
        while(SignDate.day() == 29 || SignDate.day() == 30 || SignDate.day() == 31) {
            numberofDays++;
            SignDate = SignDate.adddays(1);
        }
        return numberofDays;
    }
}