force-app/main/default/objects/dsfs__DocuSign_Status__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>genesis__Applications__c</referenceTo>
    <relationshipLabel>DocuSign Status</relationshipLabel>
    <relationshipName>DocuSign_Status</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/dsfs__DocuSign_Status__c/fields/Lead_Id__c.field-meta.xml
<CustomField>
    <fullName>Lead_Id__c</fullName>
    <formula>Application__r.Lead_ID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Lead_Id</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/genesis__Applications__c/genesis__Applications__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{0000000000}</displayFormat>
        <label>Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/genesis__Applications__c/fields/DocuSign_Envelope_ID__c.field-meta.xml
<CustomField>
    <fullName>DocuSign_Envelope_ID__c</fullName>
    <label>DocuSign Envelope ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/genesis__Applications__c/fields/DocuSign_Envelope_Status__c.field-meta.xml
<CustomField>
    <fullName>DocuSign_Envelope_Status__c</fullName>
    <label>DocuSign Envelope Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/genesis__Applications__c/fields/DocuSign_EnvelopeId__c.field-meta.xml
<CustomField>
    <fullName>DocuSign_EnvelopeId__c</fullName>
    <label>DocuSign EnvelopeId</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/genesis__Applications__c/fields/genesis__Status__c.field-meta.xml
<CustomField>
    <fullName>genesis__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>APPROVED - APPROVED</fullName>
            </value>
            <value>
                <fullName>APPROVED - CONVERTED TO CONTRACT</fullName>
            </value>
            <value>
                <fullName>APPROVED - DOCUMENT CHECK</fullName>
            </value>
            <value>
                <fullName>NEW - CREDIT PULLED</fullName>
            </value>
            <value>
                <fullName>NEW - ENTERED</fullName>
                <default>true</default>
                <label>NEW - ENTERED</label>
            </value>
            <value>
                <fullName>NEW - IN CREDIT CHECK</fullName>
            </value>
            <value>
                <fullName>NEW - IN REVIEW</fullName>
            </value>
            <value>
                <fullName>NEW - PRICING GENERATED</fullName>
            </value>
            <value>
                <fullName>NEW - SCORECARD GENERATED</fullName>
            </value>
            <value>
                <fullName>NEW - CHECKLIST GENERATED</fullName>
            </value>
            <value>
                <fullName>NEW - VEHICLE VALUATION REQUIRED</fullName>
            </value>
            <value>
                <fullName>REJECTED</fullName>
            </value>
            <value>
                <fullName>PULL CREDIT</fullName>
            </value>
            <value>
                <fullName>Default Documents</fullName>
            </value>
            <value>
                <fullName>offer_accepted</fullName>
            </value>
            <value>
                <fullName>offer_shown</fullName>
            </value>
            <value>
                <fullName>kba_success</fullName>
            </value>
            <value>
                <fullName>kba_fail</fullName>
            </value>
            <value>
                <fullName>agent_document_verification_pending</fullName>
            </value>
            <value>
                <fullName>agent_verification_pending</fullName>
            </value>
            <value>
                <fullName>agent_verified</fullName>
            </value>
            <value>
                <fullName>docusign_loan_docs_sent</fullName>
            </value>
            <value>
                <fullName>docusign_loan_docs_complete</fullName>
            </value>
            <value>
                <fullName>pre_funding</fullName>
            </value>
            <value>
                <fullName>Approved for funding</fullName>
            </value>
            <value>
                <fullName>funded</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Stacker_Check_Passed</fullName>
            </value>
            <value>
                <fullName>Redecision_Required</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/genesis__Applications__c/fields/Lead_ID__c.field-meta.xml
<CustomField>
    <fullName>Lead_ID__c</fullName>
    <description>This is the LEAD GUID received from FE</description>
    <externalId>true</externalId>
    <label>Lead ID</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/loan__Batch_Process_Log__c/loan__Batch_Process_Log__c.object-meta.xml
<CustomObject>
    <label>Batch Process Log</label>
    <nameField>
        <label>Apex Batch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Batch Process Log</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/loan__Batch_Process_Log__c/fields/loan__Message__c.field-meta.xml
<CustomField>
    <fullName>loan__Message__c</fullName>
    <label>Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/loan__Batch_Process_Log__c/fields/loan__Origin__c.field-meta.xml
<CustomField>
    <fullName>loan__Origin__c</fullName>
    <label>Origin</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Start Of Day Process</fullName>
            </value>
            <value>
                <fullName>End of Day Process</fullName>
            </value>
            <value>
                <fullName>Month End Process</fullName>
            </value>
            <value>
                <fullName>Year End Process</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/UpdatePromissoryFieldsDocusignJob.cls
global class UpdatePromissoryFieldsDocusignJob implements Database.Batchable<sObject>,Database.AllowsCallouts,Schedulable {

    List<String> skipLoanStatus = System.Label.skip_docusign_job.split(',');
    String query;
    DateTime systemDate = DateTime.now();
    List<Id> dsfsStatusTime = new List<Id>();
    set<Id> appIds = new set<Id>();
    global UpdatePromissoryFieldsDocusignJob() {
        //query = 'Select id,name,DocuSign_EnvelopeId__c,lead_id__c,DocuSign_Envelope_ID__c,DocuSign_Envelope_Status__c from genesis__applications__c where DocuSign_Envelope_Status__c=\'Sent\' and DocuSign_Envelope_ID__c!=null';
        List<dsfs__DocuSign_Status__c> dsfsStatus = [select id, name, Application__c, dsfs__Envelope_Status__c, dsfs__Sent_Date_Time__c,Application__r.name, dsfs__DocuSign_Envelope_ID__c,Application__r.genesis__Status__c
                                                     from dsfs__DocuSign_Status__c
                                                     where (dsfs__Envelope_Status__c='Sent' Or dsfs__Envelope_Status__c='Delivered') and Application__c!=null and Application__r.genesis__Status__c not in : skipLoanStatus order by createddate desc];
        
         
        for(dsfs__DocuSign_Status__c d : dsfsStatus) {
        if(!appIds.contains(d.Application__c)){ //added by Saryu to get the recent docusign status record linked to one application
            DateTime t = d.dsfs__Sent_Date_Time__c ;
            //String s = String.valueOf(t); Can also use instead of myDate
            String myDate = t.format('yyyy-MM-dd HH:mm:ss', 'PST');
            t = DateTime.valueOfGmt(myDate);
            if(t<systemDate) {
                dsfsStatusTime.add(d.id);
            }

        }
        
        }
        
        /*query = 'select id, name, Application__c, dsfs__Envelope_Status__c, dsfs__Sent_Date_Time__c,Application__r.name, dsfs__DocuSign_Envelope_ID__c '+
                'from dsfs__DocuSign_Status__c '+
                'where dsfs__Envelope_Status__c=\'Sent\' and dsfs__Sent_Date_Time__c<:systemDate and Application__c!=null';*/
        query = 'select id, name, Application__c, dsfs__Envelope_Status__c, dsfs__Sent_Date_Time__c,Application__r.name, dsfs__DocuSign_Envelope_ID__c '+
                'from dsfs__DocuSign_Status__c '+
                'where id in:dsfsStatusTime';

    }
    global Database.QueryLocator start(Database.BatchableContext BC) {
       System.debug(query);
       return Database.getQueryLocator(query);
    }
    global void execute(SchedulableContext sc) {
       UpdatePromissoryFieldsDocusignJob j =new UpdatePromissoryFieldsDocusignJob();
       Database.executebatch(j,1);
    }
    global void execute(Database.BatchableContext BC, List<dsfs__DocuSign_Status__c> scope) {
        System.debug(scope.size());
        list<loan__batch_process_log__c> errorLogs = new list<loan__batch_process_log__c>();
        for(dsfs__DocuSign_Status__c app:scope) {
            //String envelopeStatus = SendEnvDocuSignAPI.getEnvelopeStatus(app.dsfs__Envelope_Status__c);
            //if(envelopeStatus!=null && !envelopeStatus.equalsIgnoreCase('completed')) {
                String documentId = SendEnvDocuSignAPI.getDocumentId(app.dsfs__DocuSign_Envelope_ID__c);
                if(documentId!=null) {
                    String result = SendEnvDocuSignAPI.updateDocumentFields(app.dsfs__DocuSign_Envelope_ID__c,documentId);
                    if(result==null || !result.equalsIgnoreCase('Succesfully Updated the Document Tabs !!')) {
                        loan__batch_process_log__c log = new loan__batch_process_log__c();
                        log.loan__Message__c='Please check the field tag names being sent for the application:'+app.Application__r.name+': '+result;
                        log.loan__Origin__c ='UpdatePromissoryFieldsDocusignJob';
                        errorLogs.add(log);
                    }
                } else {
                    loan__batch_process_log__c log = new loan__batch_process_log__c();
                    log.loan__Message__c='No Document exists for the PayOff Promissory Note for the application:'+app.Application__r.name;
                    log.loan__Origin__c ='UpdatePromissoryFieldsDocusignJob';
                    errorLogs.add(log);
                }
            /*} else {
                loan__batch_process_log__c log = new loan__batch_process_log__c();
                log.loan__Message__c='Please check the envelope status or the docusign envelope id for the application:'+app.name;
                log.loan__Origin__c ='UpdatePromissoryFieldsDocusignJob';
                errorLogs.add(log);
            }*/
        }
        if(errorLogs!=null && errorLogs.size()>0)
            insert errorlogs;
    }
    
    global void finish(Database.BatchableContext BC) {
        // update job's last run time in custom         
    } 
}