unpackaged/main/default/objects/clcommon__Repayment_Plan__c/clcommon__Repayment_Plan__c.object-meta.xml
<CustomObject>
    <description>This object is used to capture the Repyament plan for any contract.</description>
    <label>Repayment Plan</label>
    <nameField>
        <displayFormat>RP-{000000}</displayFormat>
        <label>Repayment Plan ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Repayment Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/clcommon__Repayment_Plan__c/fields/loan__Loan_Account__c.field-meta.xml
<CustomField>
    <fullName>loan__Loan_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Reference to CL Contract to which this repayment plan is applicable</description>
    <inlineHelpText>Reference to CL Contract to which this repayment plan is applicable</inlineHelpText>
    <label>CL Contract</label>
    <referenceTo>loan__Loan_Account__c</referenceTo>
    <relationshipLabel>Flexible Repayment Plan</relationshipLabel>
    <relationshipName>Repayment_Plan</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/genesis__Applications__c/genesis__Applications__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{0000000000}</displayFormat>
        <label>Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/genesis__Applications__c/fields/genesis__Monthly_Debt_Payments__c.field-meta.xml
<CustomField>
    <fullName>genesis__Monthly_Debt_Payments__c</fullName>
    <label>Monthly Debt Payments</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/genesis__Applications__c/fields/Loan_Origination_Date__c.field-meta.xml
<CustomField>
    <fullName>Loan_Origination_Date__c</fullName>
    <label>Loan Origination Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/loan__Loan_Account__c/loan__Loan_Account__c.object-meta.xml
<CustomObject>
    <description>Lending Account</description>
    <label>CL Contract</label>
    <nameField>
        <displayFormat>LAI-{00000000}</displayFormat>
        <label>CL Contract ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CL Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/loan__Loan_Account__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>genesis__Applications__c</referenceTo>
    <relationshipLabel>CL Contracts</relationshipLabel>
    <relationshipName>CL_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/loan__Loan_Account__c/fields/Hardship_New_Maturity_Date__c.field-meta.xml
<CustomField>
    <fullName>Hardship_New_Maturity_Date__c</fullName>
    <inlineHelpText>Manually entered date that reflects the maturity date that resulted due to the all hardship assistance.</inlineHelpText>
    <label>Hardship New Maturity Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/loan__Loan_Account__c/fields/lead_Guid__c.field-meta.xml
<CustomField>
    <fullName>lead_Guid__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>lead_Guid</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/loan__Loan_Account__c/fields/loan__Accrual_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>loan__Accrual_Start_Date__c</fullName>
    <description>The date from which interest accrual starts</description>
    <inlineHelpText>The date from which interest accrual starts</inlineHelpText>
    <label>Accrual Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/loan__Loan_Account__c/fields/loan__Disbursal_Date__c.field-meta.xml
<CustomField>
    <fullName>loan__Disbursal_Date__c</fullName>
    <description>Contract Date on the Loan account, this will be updated at the time of funding with the Expected Disbursal Date.</description>
    <inlineHelpText>Contract date on the loan. This will be updated at the time of funding with the expected disbursal date.</inlineHelpText>
    <label>Contract Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/loan__Loan_Account__c/fields/loan__First_Installment_Date__c.field-meta.xml
<CustomField>
    <fullName>loan__First_Installment_Date__c</fullName>
    <description>Date of the first installment</description>
    <inlineHelpText>This is the desired start date of the repayment schedule that is provided while creating the loan application.</inlineHelpText>
    <label>First Payment Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/loan__Loan_Account__c/fields/loan__Frequency_of_Loan_Payment__c.field-meta.xml
<CustomField>
    <fullName>loan__Frequency_of_Loan_Payment__c</fullName>
    <inlineHelpText>This decides the Payment Frequency, below are the supported ones:
Daily
Weekly
Bi-weekly
Semi-Monthly
Monthly
Bi-Monthly  
Quarterly
Semi-Annual
Annual 
Single-Payment</inlineHelpText>
    <label>Payment Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Daily</fullName>
            </value>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>Bi-weekly</fullName>
            </value>
            <value>
                <fullName>Semi-Monthly</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
                <default>true</default>
                <label>Monthly</label>
            </value>
            <value>
                <fullName>Bi-Monthly</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Semi-Annual</fullName>
            </value>
            <value>
                <fullName>Annual</fullName>
            </value>
            <value>
                <fullName>Single-Payment</fullName>
            </value>
            <value>
                <fullName>Semi-Monthly-PD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/loan__Loan_Account__c/fields/loan__Interest_Rate__c.field-meta.xml
<CustomField>
    <fullName>loan__Interest_Rate__c</fullName>
    <description>Interest Rate</description>
    <inlineHelpText>Rate of Interest for the loan.</inlineHelpText>
    <label>Current Interest Rate</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/objects/loan__Loan_Account__c/fields/loan__Last_Installment_Date__c.field-meta.xml
<CustomField>
    <fullName>loan__Last_Installment_Date__c</fullName>
    <description>Maturity Date of Loan account</description>
    <inlineHelpText>Maturity date as per contract.</inlineHelpText>
    <label>Maturity Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/loan__Loan_Account__c/fields/loan__Loan_Status__c.field-meta.xml
<CustomField>
    <fullName>loan__Loan_Status__c</fullName>
    <inlineHelpText>Status of the Account, expected values are :
Pending Approval
Active - Good Standing
Active - Bad Standing
Active - Matured
Approved
Canceled
Closed - Obligations met
Closed- Written Off
Closed - Refinanced
Partial Application</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Partial Application</fullName>
                <default>true</default>
                <label>Partial Application</label>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Active - Good Standing</fullName>
            </value>
            <value>
                <fullName>Active - Bad Standing</fullName>
            </value>
            <value>
                <fullName>Closed - Obligations met</fullName>
            </value>
            <value>
                <fullName>Closed- Written Off</fullName>
            </value>
            <value>
                <fullName>Closed - Refinanced</fullName>
            </value>
            <value>
                <fullName>Active - Matured</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Active - Marked for Closure</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/loan__Loan_Account__c/fields/loan__Maturity_Date_Current__c.field-meta.xml
<CustomField>
    <fullName>loan__Maturity_Date_Current__c</fullName>
    <inlineHelpText>This is the date on which the the loan matures</inlineHelpText>
    <label>Current Maturity Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/loan__Loan_Account__c/fields/loan__Next_Installment_Date__c.field-meta.xml
<CustomField>
    <fullName>loan__Next_Installment_Date__c</fullName>
    <description>Date of the next installment</description>
    <inlineHelpText>Date of the Next Due</inlineHelpText>
    <label>Next Due Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/loan__Loan_Account__c/fields/loan__Oldest_Due_Date__c.field-meta.xml
<CustomField>
    <fullName>loan__Oldest_Due_Date__c</fullName>
    <description>Oldest Due Date</description>
    <inlineHelpText>Oldest due date on the loan account.</inlineHelpText>
    <label>Oldest Unpaid  Due Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/loan__Loan_Account__c/fields/loan__Payment_Amount__c.field-meta.xml
<CustomField>
    <fullName>loan__Payment_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Loan payment amount. It excludes any fee that is gathered as a part of EMI.</description>
    <inlineHelpText>Contractual payment amount</inlineHelpText>
    <label>Payment Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/loan__Loan_Account__c/fields/loan__Pmt_Amt_Cur__c.field-meta.xml
<CustomField>
    <fullName>loan__Pmt_Amt_Cur__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Current Payment Amount</description>
    <inlineHelpText>This is the current installment amount that needs to be paid.</inlineHelpText>
    <label>Current Payment Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/loan__Loan_Account__c/fields/loan__Previous_Installment_Date__c.field-meta.xml
<CustomField>
    <fullName>loan__Previous_Installment_Date__c</fullName>
    <description>Last Billing Date</description>
    <inlineHelpText>Last Bill Date</inlineHelpText>
    <label>Last Due Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/loan__Loan_Account__c/fields/loan__Term_Cur__c.field-meta.xml
<CustomField>
    <fullName>loan__Term_Cur__c</fullName>
    <description>Current Term</description>
    <inlineHelpText>Current loan account term.</inlineHelpText>
    <label>Current Term</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/loan__Loan_Account__c/fields/Skipped_a_Pay__c.field-meta.xml
<CustomField>
    <fullName>Skipped_a_Pay__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Flag to indicate if the most recent loan modification activity on the loan is a skip-a-pay.  This flag should be settable manually or by the batch skip-a-pay upload process</inlineHelpText>
    <label>Skipped a Pay</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/loan__Loan_Account__c/fields/Skipped_a_pay_Date__c.field-meta.xml
<CustomField>
    <fullName>Skipped_a_pay_Date__c</fullName>
    <description>This field represents the day on which skip-a-pay is performed</description>
    <inlineHelpText>The date when a batch script was applied to affect a loan modification/skip</inlineHelpText>
    <label>Loan Mod Batch Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/loan__Loan_Account__c/fields/U_LoanModForbearance__c.field-meta.xml
<CustomField>
    <fullName>U_LoanModForbearance__c</fullName>
    <inlineHelpText>Manually entered value representing the number of bills forbore by the most recent hardship assistance.</inlineHelpText>
    <label>Loan Mod Forbearance Length</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/loan__Loan_Account__c/fields/U_LoanModForbearDt__c.field-meta.xml
<CustomField>
    <fullName>U_LoanModForbearDt__c</fullName>
    <inlineHelpText>Manually entered value reflecting the due date of the first bill with zero payment due during the most recent loan modification.
In the case of Skip-a-pay, this is the due date of the first skipped bill.</inlineHelpText>
    <label>Loan Mod Forbearance Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/loan__Loan_Account__c/fields/U_LoanModTermExt__c.field-meta.xml
<CustomField>
    <fullName>U_LoanModTermExt__c</fullName>
    <inlineHelpText>Manually entered value to reflect the total period extended on the loan from hardship assistance. If multiple hardship assistance with term extension has been implemented on this loan, this would contain the sum of all term extensions.</inlineHelpText>
    <label>Loan Mod Term Ext Length</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/loan__Repayment_Schedule__c/loan__Repayment_Schedule__c.object-meta.xml
<CustomObject>
    <description>Amortization schedule is also called as Repayment schedule.</description>
    <label>Amortization Schedule</label>
    <nameField>
        <displayFormat>RSI-{0000000000}</displayFormat>
        <label>Repayment Schedule ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Amortization Schedule</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/loan__Repayment_Schedule__c/fields/loan__Loan_Account__c.field-meta.xml
<CustomField>
    <fullName>loan__Loan_Account__c</fullName>
    <description>Repayment Schedule of which Loan account</description>
    <inlineHelpText>Repayment Schedule of which Loan account</inlineHelpText>
    <label>Loan Account</label>
    <referenceTo>loan__Loan_Account__c</referenceTo>
    <relationshipName>Repayment_Schedule</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/classes/MW_SkipAPayController.cls
@RestResource(urlMapping='/skipapay/')
global with sharing class MW_SkipAPayController {
	@HttpPost
	global static Response SkipAPayController() {
		Response res = new Response();
		try {
			RestRequest req = RestContext.request;
			Id loanId;
			Integer numberOfSkips;
			Map<String, Object> reqParams = (Map<String, Object>) JSON.deserializeUntyped(
				req.requestBody.toString()
			);

			if (
				reqParams.get('loanId') == null ||
				reqParams.get('numberOfSkips') == null
			) {
				res.errorCode = 'INVALID_INPUT';
				res.errorMessage = 'both LoanId and numberOfSkips is required';
				res.status = peer.Constants.ERROR;
				return res;
			}

			loanId = (Id) reqParams.get('loanId');
			numberOfSkips = (Integer) reqParams.get('numberOfSkips');

			loan__Loan_Account__c loan = [
				SELECT
					id,
					Name,
					lead_Guid__c,
					loan__First_Installment_Date__c,
					Application__r.genesis__Monthly_Debt_Payments__c,
					loan__Payment_Amount__c,
					loan__Loan_Status__c,
					loan__Accrual_Start_Date__c,
					Application__r.Loan_Origination_Date__c,
					loan__Last_Installment_Date__c,
					loan__Interest_Rate__c,
					loan__Frequency_of_Loan_Payment__c,
					loan__Pmt_Amt_Cur__c,
					loan__Next_Installment_Date__c,
					loan__Previous_Installment_Date__c,
					loan__Maturity_Date_Current__c,
					loan__Disbursal_Date__c,
					loan__Term_Cur__c,
					Skipped_a_pay_Date__c,
					Skipped_a_Pay__c,
					U_LoanModTermExt__c,
					loan__Oldest_Due_Date__c,
					U_LoanModForbearance__c,
					Hardship_New_Maturity_Date__c,
					U_LoanModForbearDt__c,
					Hardship_Request_Date__c,
					(
						SELECT id, name, loan__Is_Archived__c, loan__Due_Date__c
						FROM loan__Repayment_Schedule__r
					),
					(SELECT id, name FROM loan__Repayment_Plan__r),
					CPD_Reason__c,
					CPD_Expire_Date__c
				FROM loan__Loan_Account__c
				WHERE Id = :loanId
				LIMIT 1
			];

			ForBearanceLoanHelper helper = new ForBearanceLoanHelper(
				loan,
				numberOfSkips
			);
			Response rescheduleReponse = helper.rescheduleLoan(new Map<String, String>());

			res.status = rescheduleReponse.status;
			res.errorCode = rescheduleReponse.errorCode;
			res.errorMessage = rescheduleReponse.errorMessage;
			return res;
		} catch (Exception e) {
			res.errorCode = 'INVALID_INPUT';
			res.errorMessage = e.getMessage();
			System.debug(logginglevel.error, 'line number' + e.getLineNumber());
			System.debug(
				logginglevel.error,
				'error stackTrace' + e.getStackTraceString()
			);

			res.status = peer.Constants.ERROR;
			return res;
		}
	}
}