unpackaged/main/default/objects/clcommon__Repayment_Plan__c/clcommon__Repayment_Plan__c.object-meta.xml
<CustomObject>
    <description>This object is used to capture the Repyament plan for any contract.</description>
    <label>Repayment Plan</label>
    <nameField>
        <displayFormat>RP-{000000}</displayFormat>
        <label>Repayment Plan ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Repayment Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/clcommon__Repayment_Plan__c/fields/clcommon__Number_Of_Payments__c.field-meta.xml
<CustomField>
    <fullName>clcommon__Number_Of_Payments__c</fullName>
    <inlineHelpText>Number of installments for the plan period</inlineHelpText>
    <label>Number of Payments</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/clcommon__Repayment_Plan__c/fields/clcommon__Payment_Amount__c.field-meta.xml
<CustomField>
    <fullName>clcommon__Payment_Amount__c</fullName>
    <inlineHelpText>The expected payment amount per installment for the plan period</inlineHelpText>
    <label>Payment Amount</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/clcommon__Repayment_Plan__c/fields/clcommon__Payment_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>clcommon__Payment_Start_Date__c</fullName>
    <inlineHelpText>The date of first installment for the plan period</inlineHelpText>
    <label>Payment Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/clcommon__Repayment_Plan__c/fields/clcommon__Sequence_Number__c.field-meta.xml
<CustomField>
    <fullName>clcommon__Sequence_Number__c</fullName>
    <inlineHelpText>A number used to order repayment plans as needed</inlineHelpText>
    <label>Sequence Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/clcommon__Repayment_Plan__c/fields/loan__Loan_Account__c.field-meta.xml
<CustomField>
    <fullName>loan__Loan_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Reference to CL Contract to which this repayment plan is applicable</description>
    <inlineHelpText>Reference to CL Contract to which this repayment plan is applicable</inlineHelpText>
    <label>CL Contract</label>
    <referenceTo>loan__Loan_Account__c</referenceTo>
    <relationshipLabel>Flexible Repayment Plan</relationshipLabel>
    <relationshipName>Repayment_Plan</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/loan__Loan_Account__c/loan__Loan_Account__c.object-meta.xml
<CustomObject>
    <description>Lending Account</description>
    <label>CL Contract</label>
    <nameField>
        <displayFormat>LAI-{00000000}</displayFormat>
        <label>CL Contract ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CL Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/loan__Loan_Account__c/fields/loan__Pmt_Amt_Cur__c.field-meta.xml
<CustomField>
    <fullName>loan__Pmt_Amt_Cur__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Current Payment Amount</description>
    <inlineHelpText>This is the current installment amount that needs to be paid.</inlineHelpText>
    <label>Current Payment Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/loan__Loan_Account__c/fields/Mod_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Mod_End_Date__c</fullName>
    <label>Mod End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/loan__Loan_Account__c/fields/Mod_Payment_Amount__c.field-meta.xml
<CustomField>
    <fullName>Mod_Payment_Amount__c</fullName>
    <label>Mod Payment Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/classes/ModPaymentAmountFieldUpdateHandler.cls
public with sharing class ModPaymentAmountFieldUpdateHandler {

    public static void updateModField(Set<String> contractIds) {

        List<loan__Loan_Account__c> updateContract = new List<loan__Loan_Account__c>();

        for (List<loan__Loan_Account__c> clContracts : [SELECT 
                                                                Id, loan__Pmt_Amt_Cur__c, 
                                                                (select id, clcommon__Sequence_Number__c, clcommon__Payment_Amount__c, clcommon__Number_Of_Payments__c,
                                                                clcommon__Payment_Start_Date__c  
                                                                FROM loan__Repayment_Plan__r
                                                                ) 
                                                                FROM loan__Loan_Account__c 
                                                                WHERE id IN :contractIds
                                                                WITH SECURITY_ENFORCED])
        {
            for(loan__Loan_Account__c clContract : clContracts) {

                //if there is a repayment plan
                if (clContract.loan__Repayment_Plan__r.size() > 0) {

                    clContract.Mod_Payment_Amount__c = clContract.loan__Repayment_Plan__r[0].clcommon__Payment_Amount__c;
                    clContract.Mod_End_Date__c = clContract.loan__Repayment_Plan__r[0].clcommon__Payment_Start_Date__c.addMonths(Integer.valueOf(clContract.loan__Repayment_Plan__r[0].clcommon__Number_Of_Payments__c));

                    updateContract.add(clContract);
                }
            }                                                    
        }

        if (updateContract.size() > 0) {
            update updateContract;
        }
    }

}