force-app/main/default/objects/genesis__Application_Document_Category__c/genesis__Application_Document_Category__c.object-meta.xml
<CustomObject>
    <label>Application Document Category</label>
    <nameField>
        <label>Application Document Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application Document Category</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/genesis__Application_Document_Category__c/fields/Action_Reason__c.field-meta.xml
<CustomField>
    <fullName>Action_Reason__c</fullName>
    <formula>IF( (ISPICKVAL(Rejection_Reasons__c, &quot;Accept: Additional Docs&quot;)),&quot;We still need additional documents of this type.&quot;,
IF( (ISPICKVAL(Rejection_Reasons__c, &quot;Accept: Previous Statement&quot;)),&quot;We still need the previous month&apos;s bank statement.&quot;,IF( (ISPICKVAL(Rejection_Reasons__c, &quot;Accept: Primary Statement&quot;)),&quot;We still need the statement from your primary bank account where your income is deposited.&quot;,IF( (ISPICKVAL(Rejection_Reasons__c, &quot;Accept: More Recent Statement&quot;)),&quot;We still need your most recent bank statement.&quot;,IF((ISPICKVAL(Rejection_Reasons__c, &quot;Accept: Not Personal Account&quot;)),&quot;We still need your personal account statement as we cannot use business accounts for verification.&quot;,
IF( ISPICKVAL(Rejection_Reasons__c, &quot;Accept: Previous Paystub&quot;),&quot;We still need a paystub from the previous pay period.&quot;,
IF( ISPICKVAL(Rejection_Reasons__c, &quot;Statement: Missing Pages&quot;),&quot;Document Incomplete: Please include all pages of your bank statement.&quot;,
IF( ISPICKVAL(Rejection_Reasons__c, &quot;Statement: Not PDF&quot;),&quot;Incorrect file type: Please upload your most recent PDF bank statement. You can download this from your online bank account.&quot;,
IF( ISPICKVAL(Rejection_Reasons__c, &quot;Statement: Not Recent&quot;),&quot;Document out of date: Please upload the most recent version of your bank statement.&quot;,
IF( ISPICKVAL(Rejection_Reasons__c, &quot;Paystub: Not Recent&quot;),&quot;Document out of date: Please upload the most recent version of your paystubs.&quot;,
IF( ISPICKVAL(Rejection_Reasons__c, &quot;ID: Expired&quot;),&quot;Document out of date: Please upload a non-expired form of identification.&quot;,
IF( ISPICKVAL(Rejection_Reasons__c, &quot;ID: Non-color&quot;),&quot;Image not in color: Please upload a color photo of your ID. Hint: Use your smart phone to take a picture.&quot;,
IF( ISPICKVAL(Rejection_Reasons__c, &quot;ID: Security Image&quot;),&quot;Please upload a copy of your ID with the security image clearly visible.&quot;,
IF( ISPICKVAL(Rejection_Reasons__c, &quot;Blurry/Glare/Dark&quot;),&quot;Insufficient quality: Please upload a clear and legible copy.&quot;,
IF( ISPICKVAL(Rejection_Reasons__c, &quot;Image Cut Off&quot;),&quot;Insufficient quality: Please make sure the entire document is clearly visible.&quot;,
IF( ISPICKVAL(Rejection_Reasons__c, &quot;Not Applicable&quot;),&quot;Not applicable: This document is not required.&quot;,
IF( ISPICKVAL(Rejection_Reasons__c, &quot;Duplicate&quot;),&quot;Duplicate: This document is a duplicate of an existing uploaded document.&quot;,
IF( ISPICKVAL(Rejection_Reasons__c, &quot;Password Protected&quot;),&quot;Password Protected: This file is password protected. Please upload an accessible file.&quot;
,NULL))))))))))))))))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Action Reason</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/genesis__Application_Document_Category__c/fields/Application_Email__c.field-meta.xml
<CustomField>
    <fullName>Application_Email__c</fullName>
    <formula>genesis__Application__r.Application_Email__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Application Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/genesis__Application_Document_Category__c/fields/Borrower_s_Email__c.field-meta.xml
<CustomField>
    <fullName>Borrower_s_Email__c</fullName>
    <description>/* Created By Nupur */

------ For Email Alerts --pending_document_reminder.liquid</description>
    <label>Borrower&apos;s Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/genesis__Application_Document_Category__c/fields/Borrower_s_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Borrower_s_First_Name__c</fullName>
    <formula>genesis__Application__r.Borrower_s_First_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Borrower&apos;s First Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/genesis__Application_Document_Category__c/fields/Box_URl__c.field-meta.xml
<CustomField>
    <fullName>Box_URl__c</fullName>
    <label>Box URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/genesis__Application_Document_Category__c/fields/Cleared_Reason__c.field-meta.xml
<CustomField>
    <fullName>Cleared_Reason__c</fullName>
    <label>Cleared Reason</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/genesis__Application_Document_Category__c/fields/Deliver_Status__c.field-meta.xml
<CustomField>
    <fullName>Deliver_Status__c</fullName>
    <description>Used in Loan Origination Package - Deliver Documents From CLS to Push the documents to Box</description>
    <label>Deliver Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>FF</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/genesis__Application_Document_Category__c/fields/genesis__Active__c.field-meta.xml
<CustomField>
    <fullName>genesis__Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/genesis__Application_Document_Category__c/fields/genesis__Application__c.field-meta.xml
<CustomField>
    <fullName>genesis__Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>genesis__Applications__c</referenceTo>
    <relationshipLabel>Application Document Category</relationshipLabel>
    <relationshipName>Application_Document_Category</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/genesis__Application_Document_Category__c/fields/genesis__Description__c.field-meta.xml
<CustomField>
    <fullName>genesis__Description__c</fullName>
    <label>Description</label>
    <length>32000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/genesis__Application_Document_Category__c/fields/genesis__Document_Category__c.field-meta.xml
<CustomField>
    <fullName>genesis__Document_Category__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Document Category</label>
    <referenceTo>genesis__Document_Category__c</referenceTo>
    <relationshipLabel>Application Document Category</relationshipLabel>
    <relationshipName>Application_Document_Category</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/genesis__Application_Document_Category__c/fields/genesis__Email__c.field-meta.xml
<CustomField>
    <fullName>genesis__Email__c</fullName>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/genesis__Application_Document_Category__c/fields/genesis__Id__c.field-meta.xml
<CustomField>
    <fullName>genesis__Id__c</fullName>
    <description>Unique Id</description>
    <label>Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/genesis__Application_Document_Category__c/fields/genesis__Parent_Application_Document_Category__c.field-meta.xml
<CustomField>
    <fullName>genesis__Parent_Application_Document_Category__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Application Document Category</label>
    <referenceTo>genesis__Application_Document_Category__c</referenceTo>
    <relationshipLabel>Application Document Category</relationshipLabel>
    <relationshipName>Application_Document_Category</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/genesis__Application_Document_Category__c/fields/genesis__Parent_Id__c.field-meta.xml
<CustomField>
    <fullName>genesis__Parent_Id__c</fullName>
    <label>Parent Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/genesis__Application_Document_Category__c/fields/genesis__Party__c.field-meta.xml
<CustomField>
    <fullName>genesis__Party__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Party responsible for providing the document.</description>
    <label>Responsible Party</label>
    <referenceTo>clcommon__Party__c</referenceTo>
    <relationshipLabel>Application Document Category</relationshipLabel>
    <relationshipName>Application_Document_Category</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/genesis__Application_Document_Category__c/fields/genesis__Party_Type__c.field-meta.xml
<CustomField>
    <fullName>genesis__Party_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Party Type</label>
    <referenceTo>clcommon__Party_Type__c</referenceTo>
    <relationshipLabel>Application Document Category</relationshipLabel>
    <relationshipName>Application_Document_Category</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/genesis__Application_Document_Category__c/fields/genesis__Priority__c.field-meta.xml
<CustomField>
    <fullName>genesis__Priority__c</fullName>
    <label>Priority</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>High</fullName>
            </value>
            <value>
                <fullName>Normal</fullName>
            </value>
            <value>
                <fullName>Low</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/genesis__Application_Document_Category__c/fields/genesis__Required__c.field-meta.xml
<CustomField>
    <fullName>genesis__Required__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/genesis__Application_Document_Category__c/fields/genesis__Review_Assigned_To__c.field-meta.xml
<CustomField>
    <fullName>genesis__Review_Assigned_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Review Assigned To</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Application_Document_Category</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/genesis__Application_Document_Category__c/fields/genesis__Review_Comments__c.field-meta.xml
<CustomField>
    <fullName>genesis__Review_Comments__c</fullName>
    <label>Review Comments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/genesis__Application_Document_Category__c/fields/genesis__Reviewed_By__c.field-meta.xml
<CustomField>
    <fullName>genesis__Reviewed_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reviewed By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Application_Document_Category1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/genesis__Application_Document_Category__c/fields/genesis__Send_Notification__c.field-meta.xml
<CustomField>
    <fullName>genesis__Send_Notification__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Send Notification</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/genesis__Application_Document_Category__c/fields/genesis__Status__c.field-meta.xml
<CustomField>
    <fullName>genesis__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>OPEN</fullName>
                <default>true</default>
                <label>OPEN</label>
            </value>
            <value>
                <fullName>SUBMITTED</fullName>
            </value>
            <value>
                <fullName>CLEARED</fullName>
            </value>
            <value>
                <fullName>REJECTED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/genesis__Document_Category__c/genesis__Document_Category__c.object-meta.xml
<CustomObject>
    <label>Document Category</label>
    <nameField>
        <displayFormat>DC-{00000000}</displayFormat>
        <label>Document Category Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Document Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/genesis__Document_Category__c/fields/genesis__Description__c.field-meta.xml
<CustomField>
    <fullName>genesis__Description__c</fullName>
    <label>Description</label>
    <length>130000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/genesis__Document_Category__c/fields/genesis__Priority__c.field-meta.xml
<CustomField>
    <fullName>genesis__Priority__c</fullName>
    <label>Priority</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>High</fullName>
            </value>
            <value>
                <fullName>Normal</fullName>
            </value>
            <value>
                <fullName>Low</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/genesis__Document_Category__c/fields/genesis__Required__c.field-meta.xml
<CustomField>
    <fullName>genesis__Required__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/genesis__Document_Category__c/fields/genesis__Review_Assigned_To__c.field-meta.xml
<CustomField>
    <fullName>genesis__Review_Assigned_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Default reviewer.</description>
    <inlineHelpText>Default reviewer.</inlineHelpText>
    <label>Review Assigned To (Deprecated)</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Document_Categories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/genesis__Document_Category__c/fields/genesis__Send_Notification__c.field-meta.xml
<CustomField>
    <fullName>genesis__Send_Notification__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Send Notification</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/MW_RetrieveADCByLeadGuid.cls
@RestResource(urlMapping='/application-document-category/lead-guid/*')
//MW_RetrieveApplicationDocumentCategoryByLeadGuid
global with sharing class MW_RetrieveADCByLeadGuid {
    @HttpGet
    global static void MW_RetrieveADCByLeadGuid() {
        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;
        try {
            String leadGuid = req.params.get('lead-guid');
            if (String.isBlank(leadGuid)) {
                res.statusCode = 400;
                res.responseBody = Blob.valueOf('guid is required');
                return;
            }
            List<genesis__Application_Document_Category__c> docs = [
                SELECT    
                Id,
                OwnerId,
                Name,
                CreatedDate,
                CreatedById,
                LastModifiedDate,
                LastModifiedById,
                genesis__Active__c,
                genesis__Application__c,
                genesis__Description__c,
                genesis__Document_Category__c,
                genesis__Email__c,
                genesis__Id__c,
                genesis__Parent_Application_Document_Category__c,
                genesis__Parent_Id__c,
                genesis__Party_Type__c,
                genesis__Party__c,
                genesis__Priority__c,
                genesis__Required__c,
                genesis__Review_Assigned_To__c,
                genesis__Review_Comments__c,
                genesis__Reviewed_By__c,
                genesis__Send_Notification__c,
                genesis__Status__c,
                Action_Reason__c,
                Application_Email__c,
                Borrower_s_Email__c,
                Borrower_s_First_Name__c,
                Box_URl__c,
                Cleared_Reason__c,
                Deliver_Status__c,
                Doc_Code_FF__c,
                Doc_Upload_Notification__c,
                Member_Email__c,
                Rejection_Reason__c,
                Rejection_Reasons__c,
                Doc_Code_as_for_Investors__c,
                Investor_Code__c,
                ShareBoxLink__c,
                Last2characters_forSorting__c,
                DataArchiva_Read_Only_Data__c,
                DataArchiva_Old_Id__c,
                Lead_Id__c
                FROM genesis__Application_Document_Category__c
                WHERE Lead_Id__c = :leadGuid
            ];

            res.statusCode = 200;
            res.responseBody = Blob.valueOf(JSON.serialize(docs));
        }
        catch (Exception e) {
            res.statusCode = 500;
            res.responseBody = Blob.valueOf(e.getMessage());
        }
    }
}