force-app/main/default/objects/genesis__Application_Document_Category__c/genesis__Application_Document_Category__c.object-meta.xml
<CustomObject>
    <label>Application Document Category</label>
    <nameField>
        <label>Application Document Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application Document Category</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/genesis__Application_Document_Category__c/fields/Application_Email__c.field-meta.xml
<CustomField>
    <fullName>Application_Email__c</fullName>
    <formula>genesis__Application__r.Application_Email__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Application Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/genesis__Application_Document_Category__c/fields/Borrower_s_Email__c.field-meta.xml
<CustomField>
    <fullName>Borrower_s_Email__c</fullName>
    <description>/* Created By Nupur */

------ For Email Alerts --pending_document_reminder.liquid</description>
    <label>Borrower&apos;s Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/classes/BorrowersEmailIDonDocumentObject.cls
public class BorrowersEmailIDonDocumentObject {

 /*public static list<genesis__Application_Document_Category__c> getBorrowersEmailId(list<ID> Ids){
     List<String> BorrowerEmial = new List<String>();
     list<genesis__Application_Document_Category__c> doclist = [select id,
                                                                     Application_Email__c,
                                                                     Borrower_s_Email__c 
                                                                     FROM genesis__Application_Document_Category__c 
                                                                     WHERE id in:ids];
     for(genesis__Application_Document_Category__c doc: doclist){
         doc.Borrower_s_Email__c = doc.Application_Email__c;
     }  
     update doclist;
        return doclist;
    }*/
    @invocablemethod()
    public static void getBorrowersEmailId(list<ID> Ids){
         genesis__Application_Document_Category__c doclist = [select id, Borrower_s_Email__c,
                                                                         Application_Email__c
                                                                         FROM genesis__Application_Document_Category__c 
                                                                         WHERE id =:ids limit 1];
         if(doclist != Null && doclist.Borrower_s_Email__c == Null){                                                                  
             doclist.Borrower_s_Email__c = doclist.Application_Email__c;   
             update doclist;
             System.debug('Borrower Email...' +   doclist.Borrower_s_Email__c);    
         } 
     }
}