unpackaged/main/default/objects/genesis__Application_Status_History__c/genesis__Application_Status_History__c.object-meta.xml
<CustomObject>
    <label>Application Status History</label>
    <nameField>
        <displayFormat>ASH-{00000000}</displayFormat>
        <label>Application Status History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Status History</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/genesis__Application_Status_History__c/fields/genesis__Application__c.field-meta.xml
<CustomField>
    <fullName>genesis__Application__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Application</label>
    <referenceTo>genesis__Applications__c</referenceTo>
    <relationshipLabel>Application Status History</relationshipLabel>
    <relationshipName>Application_Status_History</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/genesis__Application_Status_History__c/fields/genesis__New_Value__c.field-meta.xml
<CustomField>
    <fullName>genesis__New_Value__c</fullName>
    <description>New Status of application</description>
    <inlineHelpText>New Status of application</inlineHelpText>
    <label>New Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/genesis__Applications__c/genesis__Applications__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{0000000000}</displayFormat>
        <label>Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/genesis__Applications__c/fields/genesis__Status__c.field-meta.xml
<CustomField>
    <fullName>genesis__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>APPROVED - APPROVED</fullName>
            </value>
            <value>
                <fullName>APPROVED - CONVERTED TO CONTRACT</fullName>
            </value>
            <value>
                <fullName>APPROVED - DOCUMENT CHECK</fullName>
            </value>
            <value>
                <fullName>NEW - CREDIT PULLED</fullName>
            </value>
            <value>
                <fullName>NEW - ENTERED</fullName>
                <default>true</default>
                <label>NEW - ENTERED</label>
            </value>
            <value>
                <fullName>NEW - IN CREDIT CHECK</fullName>
            </value>
            <value>
                <fullName>NEW - IN REVIEW</fullName>
            </value>
            <value>
                <fullName>NEW - PRICING GENERATED</fullName>
            </value>
            <value>
                <fullName>NEW - SCORECARD GENERATED</fullName>
            </value>
            <value>
                <fullName>NEW - CHECKLIST GENERATED</fullName>
            </value>
            <value>
                <fullName>NEW - VEHICLE VALUATION REQUIRED</fullName>
            </value>
            <value>
                <fullName>REJECTED</fullName>
            </value>
            <value>
                <fullName>PULL CREDIT</fullName>
            </value>
            <value>
                <fullName>Default Documents</fullName>
            </value>
            <value>
                <fullName>offer_accepted</fullName>
            </value>
            <value>
                <fullName>offer_shown</fullName>
            </value>
            <value>
                <fullName>kba_success</fullName>
            </value>
            <value>
                <fullName>kba_fail</fullName>
            </value>
            <value>
                <fullName>agent_document_verification_pending</fullName>
            </value>
            <value>
                <fullName>agent_verification_pending</fullName>
            </value>
            <value>
                <fullName>agent_verified</fullName>
            </value>
            <value>
                <fullName>docusign_loan_docs_sent</fullName>
            </value>
            <value>
                <fullName>docusign_loan_docs_complete</fullName>
            </value>
            <value>
                <fullName>pre_funding</fullName>
            </value>
            <value>
                <fullName>Approved for funding</fullName>
            </value>
            <value>
                <fullName>funded</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Stacker_Check_Passed</fullName>
            </value>
            <value>
                <fullName>Redecision_Required</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/AllocationEngineCalloutBatch.cls
/*
 * This class is serves as a bridge between ApptoContractConverterBatchJob which converts the applications to contracts 
 * and MW_AllocationEngineHandler which sends the final callouts to Allocation Engine.
 * This class isolates the execution contexts between callout and DMLs from both the classes. Better logic separation.
 * Also it provides better control over the governor limits for Allocation Engine
 * For the constructor with String query parameter, you can pass any query to send final calls to a specific set of applications
 * This will help in case there's a failure and a final Allocation call is to be sent for some set of applications 
 * A sample query :  SELECT Id,genesis__status__c FROM genesis__applications__c WHERE Id IN 
 *                   (SELECT genesis__Application__c FROM genesis__Application_Status_History__c WHERE CreatedDate = TODAY AND 
 *                   genesis__New_Value__c = 'funded')
 */

global class AllocationEngineCalloutBatch implements Database.batchable<sObject>,Database.AllowsCallouts{
    public set<Id> appIdList;
    public String queryStr;
    
    global AllocationEngineCalloutBatch(String query){
       queryStr = query;
    }
    
    global AllocationEngineCalloutBatch(set<Id> appIdList){
        this.appIdList = appIdList;
        if(appIdList != null){
            queryStr = 'SELECT Id FROM genesis__Applications__c WHERE Id IN : appIdList AND genesis__status__c = \'funded\''; 
        }
    }
    
    global Database.QueryLocator start(Database.BatchableContext bc){                              
        return Database.getQueryLocator(queryStr);    
    }
    
    global void execute(Database.BatchableContext bc, List<genesis__Applications__c> scope) {
        List<Id> appIds = new List<Id>();
        if (MW_AllocationEngineHandler.isAllocationEngineServiceEnabled()) {
            for (genesis__Applications__c app : scope) {
                appIds.add(app.Id);
            }   
            MW_AllocationEngineHandler.handleFinal(appIds);
        }else{
            MW_LogUtility.info('AllocationEngineCalloutBatch','Execute','Allocation Engine is NOT enabled');
        }
    }
    public void finish(Database.BatchableContext bc) {
        
    }
}