unpackaged/main/default/objects/loan__Fee__c/loan__Fee__c.object-meta.xml
<CustomObject>
    <description>Fee</description>
    <label>Fee</label>
    <nameField>
        <label>Fee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/loan__Fee__c/fields/loan__Currency__c.field-meta.xml
<CustomField>
    <fullName>loan__Currency__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Currency</description>
    <inlineHelpText>Currency</inlineHelpText>
    <label>Currency</label>
    <referenceTo>loan__Currency__c</referenceTo>
    <relationshipLabel>Fees</relationshipLabel>
    <relationshipName>Fees</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/loan__Fee__c/fields/loan__Interest_Rate__c.field-meta.xml
<CustomField>
    <fullName>loan__Interest_Rate__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Interest Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/loan__Fee_Junction__c/loan__Fee_Junction__c.object-meta.xml
<CustomObject>
    <label>Fee Set/Fee</label>
    <nameField>
        <displayFormat>FJIP-{0000000000}</displayFormat>
        <label>Fee Junction ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fee Set/Fee</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/loan__Fee_Junction__c/fields/loan__Fee__c.field-meta.xml
<CustomField>
    <fullName>loan__Fee__c</fullName>
    <label>Fee</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>loan__Fee__c.loan__Time_of_charge__c</field>
            <operation>notEqual</operation>
            <value>Pre-Paid Fees</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>loan__Fee__c</referenceTo>
    <relationshipLabel>Fee Set/Fee</relationshipLabel>
    <relationshipName>Fee_Junction</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/loan__Fee_Junction__c/fields/loan__Fee_Set__c.field-meta.xml
<CustomField>
    <fullName>loan__Fee_Set__c</fullName>
    <label>Fee Set</label>
    <referenceTo>loan__Fee_Set__c</referenceTo>
    <relationshipName>Fee_Junction</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/loan__Loan_Account__c/loan__Loan_Account__c.object-meta.xml
<CustomObject>
    <description>Lending Account</description>
    <label>CL Contract</label>
    <nameField>
        <displayFormat>LAI-{00000000}</displayFormat>
        <label>CL Contract ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CL Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/loan__Loan_Account__c/fields/lead_Guid__c.field-meta.xml
<CustomField>
    <fullName>lead_Guid__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>lead_Guid</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/loan__Loan_Account__c/fields/loan__Contact__c.field-meta.xml
<CustomField>
    <fullName>loan__Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Please choose a contact, which will be associated as a customer on this lending account. 
You can create a new contact, from the lookup window by clicking on new or select the existing contact from the lookup.</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Loan_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/loan__Loan_Account__c/fields/loan__Fee_Set__c.field-meta.xml
<CustomField>
    <fullName>loan__Fee_Set__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Fee Set</description>
    <inlineHelpText>Lookup to associate the fee set on this lending account. Only the fees defined within the fee set can be assessed on this contract.
To create a fee set, Servicing configuration-&gt;Product-&gt;Manage fee set</inlineHelpText>
    <label>Fee Set</label>
    <referenceTo>loan__Fee_Set__c</referenceTo>
    <relationshipName>Loan_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/loan__Loan_Account__c/fields/loan__Interest_Rate__c.field-meta.xml
<CustomField>
    <fullName>loan__Interest_Rate__c</fullName>
    <description>Interest Rate</description>
    <inlineHelpText>Rate of Interest for the loan.</inlineHelpText>
    <label>Current Interest Rate</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/objects/loan__Loan_Account__c/fields/loan__Last_Installment_Date__c.field-meta.xml
<CustomField>
    <fullName>loan__Last_Installment_Date__c</fullName>
    <description>Maturity Date of Loan account</description>
    <inlineHelpText>Maturity date as per contract.</inlineHelpText>
    <label>Maturity Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/loan__Loan_Account__c/fields/loan__Loan_Purpose__c.field-meta.xml
<CustomField>
    <fullName>loan__Loan_Purpose__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Loan Purpose</description>
    <inlineHelpText>Loan purpose</inlineHelpText>
    <label>Purpose</label>
    <referenceTo>loan__Loan_Purpose__c</referenceTo>
    <relationshipName>Loan_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/loan__Loan_Account__c/fields/loan__Loan_Status__c.field-meta.xml
<CustomField>
    <fullName>loan__Loan_Status__c</fullName>
    <inlineHelpText>Status of the Account, expected values are :
Pending Approval
Active - Good Standing
Active - Bad Standing
Active - Matured
Approved
Canceled
Closed - Obligations met
Closed- Written Off
Closed - Refinanced
Partial Application</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Partial Application</fullName>
                <default>true</default>
                <label>Partial Application</label>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Active - Good Standing</fullName>
            </value>
            <value>
                <fullName>Active - Bad Standing</fullName>
            </value>
            <value>
                <fullName>Closed - Obligations met</fullName>
            </value>
            <value>
                <fullName>Closed- Written Off</fullName>
            </value>
            <value>
                <fullName>Closed - Refinanced</fullName>
            </value>
            <value>
                <fullName>Active - Matured</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Active - Marked for Closure</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/loan__Loan_Account__c/fields/loan__Payment_Mode__c.field-meta.xml
<CustomField>
    <fullName>loan__Payment_Mode__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>This is the default payment mode for this loan. It will be used to populate the payment mode on the loan payment transaction screen.</inlineHelpText>
    <label>Payment Mode</label>
    <referenceTo>loan__Payment_Mode__c</referenceTo>
    <relationshipLabel>CL Contracts</relationshipLabel>
    <relationshipName>CL_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/loan__Loan_Product__c/loan__Loan_Product__c.object-meta.xml
<CustomObject>
    <description>Lending Product Definition1</description>
    <label>Lending Product</label>
    <nameField>
        <label>Loan Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lending Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/loan__Loan_Product__c/fields/loan__Currency__c.field-meta.xml
<CustomField>
    <fullName>loan__Currency__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Currency</description>
    <inlineHelpText>Currency</inlineHelpText>
    <label>Currency</label>
    <referenceTo>loan__Currency__c</referenceTo>
    <relationshipName>Loan_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/loan__Loan_Product__c/fields/loan__Fee_Set__c.field-meta.xml
<CustomField>
    <fullName>loan__Fee_Set__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Fee Set</description>
    <inlineHelpText>Fee set contains the details of all the fees associated with the loan.</inlineHelpText>
    <label>Fee Set</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Selected Fee Set's category must be of type 'Loan' and it should include at least one fee.</errorMessage>
        <filterItems>
            <field>loan__Fee_Set__c.loan__Fee_Set_Category__c</field>
            <operation>equals</operation>
            <value>Loan</value>
        </filterItems>
        <filterItems>
            <field>loan__Fee_Set__c.loan__Number_of_Fees__c</field>
            <operation>notEqual</operation>
            <value>0</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>loan__Fee_Set__c</referenceTo>
    <relationshipName>Loan_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/loan__Org_Parameters__c/loan__Org_Parameters__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Org Parameters</label>
</CustomObject>

unpackaged/main/default/objects/loan__Org_Parameters__c/fields/loan__Disable_Triggers__c.field-meta.xml
<CustomField>
    <fullName>loan__Disable_Triggers__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>This disables all the triggers. It is to be used only while migrating data into the system. It must be disabled otherwise.</inlineHelpText>
    <label>Disable Triggers</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/classes/Test_CLS_ProcessCPDJob.cls
@isTest
public class Test_CLS_ProcessCPDJob {
    
    @testSetup
    public static void testSetupData() {
        loan__Org_Parameters__c loanParam = new loan__Org_Parameters__c(loan__Disable_Triggers__c = true);
        insert loanParam;
        
        //Creating Seed Data for Testing
        loan.TestHelper.createSeedDataForTesting();

        loan__Currency__c curr = loan.TestHelper.createCurrency();
        //Create a dummy MF_Account
        loan__MF_Account__c dummyAccount = loan.TestHelper.createMFAccount('XXXAccountForTest','10000 - ASSETS');
        loan__MF_Account__c dummyIncAccount = loan.TestHelper.createMFAccount('XXXIncAccountForTest','30000 - INCOME');

        //Create a Fee Set
        loan__Fee__c dummyFee = loan.TestHelper.createFee(curr,dummyIncAccount ,dummyAccount);
        loan__Fee_Set__c dummyFeeSet = loan.TestHelper.createFeeSet();
        loan__Fee_Junction__c dummyFeeJunction = loan.TestHelper.createFeeJunction(dummyFee,dummyFeeSet);

        loan__Office_Name__c dummyOffice = loan.TestHelper.createOffice();

        //Create a dummy Loan Product
        loan__Loan_Product__c dummyLP = loan.TestHelper.createLoanProduct('Loan Product',
                            dummyOffice,
                            dummyAccount,
                            curr,
                            dummyFeeSet,
                            'Interest Only',
                            40,
                            12,
                            null);

        loan__Loan_Purpose__c dummyLoanPurpose = loan.TestHelper.createLoanPurpose();


        Account acc = new Account(Name = 'SF');
        insert acc;
        

        loan__Payment_Mode__c paymentMode = new loan__Payment_Mode__c(name='ACH');
        insert paymentMode;
        
        
        //Create a dummy Loan Account
        loan__Loan_Account__c loanAccount = loan.TestHelper.createLoanAccountForAccountObj(dummyLP,
                                                    acc,
                                                    dummyFeeSet,
                                                    dummyLoanPurpose,
                                                    dummyOffice);
       
    } 
    
    @isTest
    static void testMehod1(){
               
        //Create a dummy Loan Account
        loan__Loan_Account__c loanAccount = [SELECT ID FROM loan__Loan_Account__c LIMIT 1];
        

        Date systemDate = TestHelper.getCurrentSystemDate();
        
        loanAccount.loan__Loan_Status__c = loan.LoanConstants.LOAN_STATUS_ACTIVE_GOOD_STANDING;
        loanAccount.loan__Contact__c = null;
        loanAccount.lead_Guid__c = 'qwertt';
        loanAccount.loan__Last_Installment_Date__c = systemDate;
        loanAccount.loan__Interest_Rate__c = 10;
        loanAccount.loan__Frequency_of_Loan_Payment__c = 'Monthly';
        loanAccount.loan__Pmt_Amt_Cur__c = 1000;
        loanAccount.loan__Next_Installment_Date__c = systemDate;
        loanAccount.loan__Maturity_Date_Current__c = systemDate;
        loanAccount.loan__Term_Cur__c = 36;
        loanAccount.CPD_Reason__c = 'Other';
        loanAccount.CPD_Expire_Date__c = Date.newInstance(2019, 12, 4);
        loanAccount.Future_Bill_Pending__c = true;
        loanAccount.loan__Due_Day__c = 3;
        loanAccount.CPD_Date__c = systemDate;
        loanAccount.CPD_Unpaid_Due_Date__c = systemdate.addDays(-1);    //pallavi
        update loanAccount;
        
        loan__Org_Parameters__c loanParam = loan__Org_Parameters__c.getOrgDefaults();
        loanParam.loan__Disable_Triggers__c = false;
        update loanParam;
        
        Test.startTest();
        CLS_ProcessCPDJob dm = new CLS_ProcessCPDJob(); //pallavi
        Database.executeBatch(dm);
        Test.stopTest();
    }
    //pallavi
     @isTest
    static void testMehod2(){
       
        //Create a dummy Loan Account
        loan__Loan_Account__c loanAccount = [SELECT ID FROM loan__Loan_Account__c LIMIT 1];
        

        Date systemDate = TestHelper.getCurrentSystemDate();
        
        loanAccount.loan__Loan_Status__c = loan.LoanConstants.LOAN_STATUS_ACTIVE_GOOD_STANDING;
        loanAccount.loan__Contact__c = null;
        loanAccount.lead_Guid__c = 'qwertt';
        loanAccount.loan__Last_Installment_Date__c = null;
        loanAccount.loan__Interest_Rate__c = 10;
        loanAccount.loan__Frequency_of_Loan_Payment__c = 'Monthly';
        loanAccount.loan__Pmt_Amt_Cur__c = 1000;
        loanAccount.loan__Next_Installment_Date__c = systemDate;
        loanAccount.loan__Maturity_Date_Current__c = systemDate;
        loanAccount.loan__Term_Cur__c = 36;
        loanAccount.CPD_Reason__c = 'Other';
        loanAccount.CPD_Expire_Date__c = Date.newInstance(2019, 12, 4);
        loanAccount.Future_Bill_Pending__c = true;
        loanAccount.loan__Due_Day__c = 3;
        loanAccount.CPD_Date__c = systemDate;
        loanAccount.CPD_Unpaid_Due_Date__c = systemdate.addDays(-1);
        update loanAccount;
        
        loan__Org_Parameters__c loanParam = loan__Org_Parameters__c.getOrgDefaults();
        loanParam.loan__Disable_Triggers__c = false;
        update loanParam;
        
        Test.startTest();
        List<String> contract = new List<String>();
        contract.add(loanAccount.id);
        CLS_ProcessCPDJob dm = new CLS_ProcessCPDJob(contract);
        Database.executeBatch(dm);
        Test.stopTest();
    }

}