unpackaged/main/default/objects/Approved_Offer__c/Approved_Offer__c.object-meta.xml
<CustomObject>
    <label>Approved Offer</label>
    <nameField>
        <label>Approved Offer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Approved Offer</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Approved_Offer__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>genesis__Applications__c</referenceTo>
    <relationshipLabel>Approved Offer</relationshipLabel>
    <relationshipName>Approved_Offer</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Approved_Offer__c/fields/EBP_Offer_Code__c.field-meta.xml
<CustomField>
    <fullName>EBP_Offer_Code__c</fullName>
    <label>EBP_Offer_Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/genesis__Applications__c/genesis__Applications__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{0000000000}</displayFormat>
        <label>Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/MW_Settings__c/MW_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>MW_Settings</label>
</CustomObject>

unpackaged/main/default/objects/MW_Settings__c/fields/FE_User_Filter__c.field-meta.xml
<CustomField>
    <fullName>FE_User_Filter__c</fullName>
    <label>FE User Filter</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Pricing_Offer__c/Pricing_Offer__c.object-meta.xml
<CustomObject>
    <label>Pricing Offer</label>
    <nameField>
        <label>Pricing Offer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pricing Offer</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Pricing_Offer__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <description>/Changed on 16-10-2017 by Sagar Hinsu</description>
    <label>Application</label>
    <referenceTo>genesis__Applications__c</referenceTo>
    <relationshipLabel>Pricing Offer</relationshipLabel>
    <relationshipName>Pricing_Offer</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Pricing_Offer__c/fields/EBP_Offer_Code__c.field-meta.xml
<CustomField>
    <fullName>EBP_Offer_Code__c</fullName>
    <label>EBP_Offer_Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ebp_dcp_75</fullName>
            </value>
            <value>
                <fullName>ebp_dcp_90</fullName>
            </value>
            <value>
                <fullName>ebp_dcp_optout</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/MW_Utilities.cls
public class MW_Utilities {

    public static boolean isFrontEndUserUpdate(){
        List<String> userFilter = MW_Settings__c.getInstance().FE_User_Filter__c.split(',');
        return userFilter.contains(UserInfo.getUserName());
    }

    public static List<String> getPicklistValues(SObjectField field){
        List<String> toList = new List<String>();
        Schema.DescribeFieldResult fieldResult = field.getDescribe();
        List<Schema.PicklistEntry> values = fieldResult.getPicklistValues();
        for( Schema.PicklistEntry value : values) {
            toList.add(value.getLabel());
        }
        return toList;
    }

    public static void clearDCPForEBP(Approved_Offer__c offer) {
        if (getPicklistValues(Pricing_Offer__c.EBP_Offer_Code__c).contains(offer.EBP_Offer_Code__c)) {
            CustomTriggerOnApplicationHandler.payAtFundingForUpdate(offer.Application__r.Id);
        }
    }
}