unpackaged/main/default/objects/Approved_Offer__c/Approved_Offer__c.object-meta.xml
<CustomObject>
    <label>Approved Offer</label>
    <nameField>
        <label>Approved Offer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Approved Offer</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Approved_Offer__c/fields/Above_prime_max__c.field-meta.xml
<CustomField>
    <fullName>Above_prime_max__c</fullName>
    <label>Above prime max</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Approved_Offer__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>genesis__Applications__c</referenceTo>
    <relationshipLabel>Approved Offer</relationshipLabel>
    <relationshipName>Approved_Offer</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Approved_Offer__c/fields/APR__c.field-meta.xml
<CustomField>
    <fullName>APR__c</fullName>
    <label>APR</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Approved_Offer__c/fields/EBP_Offer_Code__c.field-meta.xml
<CustomField>
    <fullName>EBP_Offer_Code__c</fullName>
    <label>EBP_Offer_Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Approved_Offer__c/fields/Interest_Rate__c.field-meta.xml
<CustomField>
    <fullName>Interest_Rate__c</fullName>
    <label>Interest Rate</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Approved_Offer__c/fields/Key__c.field-meta.xml
<CustomField>
    <fullName>Key__c</fullName>
    <label>Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Approved_Offer__c/fields/Monthly_Payment__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Payment__c</fullName>
    <label>Monthly Payment</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Approved_Offer__c/fields/Origination_fee__c.field-meta.xml
<CustomField>
    <fullName>Origination_fee__c</fullName>
    <label>Origination fee</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Approved_Offer__c/fields/Origination_fee_rate__c.field-meta.xml
<CustomField>
    <fullName>Origination_fee_rate__c</fullName>
    <label>Origination fee rate</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Approved_Offer__c/fields/Pricing_Tier__c.field-meta.xml
<CustomField>
    <fullName>Pricing_Tier__c</fullName>
    <label>Pricing Tier</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Approved_Offer__c/fields/Segment__c.field-meta.xml
<CustomField>
    <fullName>Segment__c</fullName>
    <label>Segment</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application_con</label>
    <referenceTo>genesis__Applications__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/genesis__Applications__c/genesis__Applications__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{0000000000}</displayFormat>
        <label>Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/genesis__Applications__c/fields/genesis__APR__c.field-meta.xml
<CustomField>
    <fullName>genesis__APR__c</fullName>
    <description>Annual Percentage Rate</description>
    <label>APR</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/objects/genesis__Applications__c/fields/genesis__Financed_Amount__c.field-meta.xml
<CustomField>
    <fullName>genesis__Financed_Amount__c</fullName>
    <label>Financed Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/genesis__Applications__c/fields/genesis__Interest_Rate__c.field-meta.xml
<CustomField>
    <fullName>genesis__Interest_Rate__c</fullName>
    <label>Interest Rate</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/genesis__Applications__c/fields/genesis__Loan_Amount__c.field-meta.xml
<CustomField>
    <fullName>genesis__Loan_Amount__c</fullName>
    <label>Loan Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/genesis__Applications__c/fields/genesis__Monthly_Debt_Payments__c.field-meta.xml
<CustomField>
    <fullName>genesis__Monthly_Debt_Payments__c</fullName>
    <label>Monthly Debt Payments</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/genesis__Applications__c/fields/genesis__Status__c.field-meta.xml
<CustomField>
    <fullName>genesis__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>APPROVED - APPROVED</fullName>
            </value>
            <value>
                <fullName>APPROVED - CONVERTED TO CONTRACT</fullName>
            </value>
            <value>
                <fullName>APPROVED - DOCUMENT CHECK</fullName>
            </value>
            <value>
                <fullName>NEW - CREDIT PULLED</fullName>
            </value>
            <value>
                <fullName>NEW - ENTERED</fullName>
                <default>true</default>
                <label>NEW - ENTERED</label>
            </value>
            <value>
                <fullName>NEW - IN CREDIT CHECK</fullName>
            </value>
            <value>
                <fullName>NEW - IN REVIEW</fullName>
            </value>
            <value>
                <fullName>NEW - PRICING GENERATED</fullName>
            </value>
            <value>
                <fullName>NEW - SCORECARD GENERATED</fullName>
            </value>
            <value>
                <fullName>NEW - CHECKLIST GENERATED</fullName>
            </value>
            <value>
                <fullName>NEW - VEHICLE VALUATION REQUIRED</fullName>
            </value>
            <value>
                <fullName>REJECTED</fullName>
            </value>
            <value>
                <fullName>PULL CREDIT</fullName>
            </value>
            <value>
                <fullName>Default Documents</fullName>
            </value>
            <value>
                <fullName>offer_accepted</fullName>
            </value>
            <value>
                <fullName>offer_shown</fullName>
            </value>
            <value>
                <fullName>kba_success</fullName>
            </value>
            <value>
                <fullName>kba_fail</fullName>
            </value>
            <value>
                <fullName>agent_document_verification_pending</fullName>
            </value>
            <value>
                <fullName>agent_verification_pending</fullName>
            </value>
            <value>
                <fullName>agent_verified</fullName>
            </value>
            <value>
                <fullName>docusign_loan_docs_sent</fullName>
            </value>
            <value>
                <fullName>docusign_loan_docs_complete</fullName>
            </value>
            <value>
                <fullName>pre_funding</fullName>
            </value>
            <value>
                <fullName>Approved for funding</fullName>
            </value>
            <value>
                <fullName>funded</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Stacker_Check_Passed</fullName>
            </value>
            <value>
                <fullName>Redecision_Required</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/genesis__Applications__c/fields/genesis__Term__c.field-meta.xml
<CustomField>
    <fullName>genesis__Term__c</fullName>
    <label>Term</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/genesis__Applications__c/fields/Lead_ID__c.field-meta.xml
<CustomField>
    <fullName>Lead_ID__c</fullName>
    <description>This is the LEAD GUID received from FE</description>
    <externalId>true</externalId>
    <label>Lead ID</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/genesis__Applications__c/fields/Origination_fee__c.field-meta.xml
<CustomField>
    <fullName>Origination_fee__c</fullName>
    <label>Origination fee</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/genesis__Applications__c/fields/Pricing_Tier__c.field-meta.xml
<CustomField>
    <fullName>Pricing_Tier__c</fullName>
    <label>Pricing Tier</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/genesis__Applications__c/fields/Required_Docs_Count__c.field-meta.xml
<CustomField>
    <fullName>Required_Docs_Count__c</fullName>
    <label>Required Docs Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Pricing_Offer__c/Pricing_Offer__c.object-meta.xml
<CustomObject>
    <label>Pricing Offer</label>
    <nameField>
        <label>Pricing Offer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pricing Offer</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Pricing_Offer__c/fields/Above_prime_max__c.field-meta.xml
<CustomField>
    <fullName>Above_prime_max__c</fullName>
    <label>Above prime max</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Pricing_Offer__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <description>/Changed on 16-10-2017 by Sagar Hinsu</description>
    <label>Application</label>
    <referenceTo>genesis__Applications__c</referenceTo>
    <relationshipLabel>Pricing Offer</relationshipLabel>
    <relationshipName>Pricing_Offer</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Pricing_Offer__c/fields/APR__c.field-meta.xml
<CustomField>
    <fullName>APR__c</fullName>
    <label>APR</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Pricing_Offer__c/fields/EBP_Offer_Code__c.field-meta.xml
<CustomField>
    <fullName>EBP_Offer_Code__c</fullName>
    <label>EBP_Offer_Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ebp_dcp_75</fullName>
            </value>
            <value>
                <fullName>ebp_dcp_90</fullName>
            </value>
            <value>
                <fullName>ebp_dcp_optout</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Pricing_Offer__c/fields/Interest_Rate__c.field-meta.xml
<CustomField>
    <fullName>Interest_Rate__c</fullName>
    <label>Interest Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/objects/Pricing_Offer__c/fields/Is_Offer_Selected__c.field-meta.xml
<CustomField>
    <fullName>Is_Offer_Selected__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Offer Selected</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Pricing_Offer__c/fields/Key__c.field-meta.xml
<CustomField>
    <fullName>Key__c</fullName>
    <label>Key</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Pricing_Offer__c/fields/Monthly_Payment__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Payment__c</fullName>
    <label>Monthly Payment</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Pricing_Offer__c/fields/Origination_fee__c.field-meta.xml
<CustomField>
    <fullName>Origination_fee__c</fullName>
    <label>Origination fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Pricing_Offer__c/fields/Origination_fee_rate__c.field-meta.xml
<CustomField>
    <fullName>Origination_fee_rate__c</fullName>
    <label>Origination fee rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/objects/Pricing_Offer__c/fields/Pricing_Tier__c.field-meta.xml
<CustomField>
    <fullName>Pricing_Tier__c</fullName>
    <label>Pricing Tier</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Pricing_Offer__c/fields/Segment__c.field-meta.xml
<CustomField>
    <fullName>Segment__c</fullName>
    <label>Segment</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Pricing_Offer__c/fields/Term__c.field-meta.xml
<CustomField>
    <fullName>Term__c</fullName>
    <label>Term</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Pricing_Offer__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/WSSelectedOffer.cls
@RestResource(urlMapping='/selectedoffer/*')
global with sharing class WSSelectedOffer{

    global class Response{
        public String status;
        public String errorCode;
        public String errorMessage;
        public String successMessage;
        public String httpStatusCode;
        public Response(){
            errorCode = PayoffConstants.ERROR;
            status = PayoffConstants.FAIL;
        }
    }
    
    global class ApprovePricingOffer{
        public String applicationId;
        public String Key;
        
    }
    
    @HttpPost
    global static Response markTentativeOfferSelected(){
        List<Pricing_Offer__c> pOffer;
        Pricing_Offer__c pOffer1;
        List<Approved_Offer__c> approve1;
        Approved_Offer__c approve = new Approved_Offer__c();
        RestResponse restRes = Restcontext.response;
        RestRequest req = Restcontext.request;
        Response res = new Response();
        
        String jsondata = req.requestBody.toString();
        ApprovePricingOffer approvedOffers;
        
        try{
            MW_LogUtility.info('WSSelectedOffer', 'SelectedOfferRequestBody', null, 'markTentativeOfferSelected',jsondata);
            approvedOffers = (ApprovePricingOffer)JSON.deserialize(jsondata, ApprovePricingOffer.class);
        }catch(Exception e){
            res.status = e.getMessage();
            res.errorCode = PayoffConstants.INVALID_INPUT_FORMAT;
            res.httpStatusCode = PayoffConstants.ERROR_HTTP_CODE;
            MW_LogUtility.error('WSSelectedOffer', res.errorCode, res.httpStatusCode, 'markTentativeOfferSelected',e);
            return res;            
        }
        
        if(approvedOffers.applicationID == null || String.isEmpty(approvedOffers.applicationID)){
            res.errorCode = PayoffConstants.SYSTEM_ERROR;
            res.status = PayoffConstants.ERROR;
            res.errorMessage = PayoffConstants.APP_ID_CANNOT_BE_NULL;
            MW_LogUtility.warn('WSSelectedOffer', approvedOffers.applicationID, null, 'markTentativeOfferSelected',res.errorMessage);
            return res;
        }
        
        if(approvedOffers.Key == null || String.isEmpty(approvedOffers.Key)){
            res.errorCode = PayoffConstants.SYSTEM_ERROR;
            res.status = PayoffConstants.ERROR;
            res.errorMessage = PayoffConstants.KEY_CANNOT_BE_NULL;
            MW_LogUtility.warn('WSSelectedOffer', approvedOffers.applicationID, null, 'markTentativeOfferSelected',res.errorMessage);
            return res;
        }
        
        
        
        if(!(approvedOffers.applicationID instanceof Id)) {
            res.errorCode = PayoffConstants.INVALID_INPUT_FORMAT;
            res.status = PayoffConstants.ERROR;
            res.errorMessage = PayoffConstants.APP_ID_INCORRECT_FORMAT;
            MW_LogUtility.warn('WSSelectedOffer', approvedOffers.applicationID, null, 'markTentativeOfferSelected',res.errorMessage);
            return res;
        }
        genesis__Applications__c app =[SELECT id,Lead_ID__c,
                                       genesis__Term__c,
                                       genesis__APR__c,
                                       Origination_fee__c,
                                       genesis__Monthly_Debt_Payments__c,
                                       genesis__Interest_Rate__c,
                                       genesis__Loan_Amount__c,
                                       genesis__Financed_Amount__c,
                                       genesis__Status__c,
                                       Pricing_Tier__c,
                                       Required_Docs_Count__c
                                       FROM genesis__Applications__c
                                       WHERE id=:approvedOffers.applicationID
                                      LIMIT 1];
                                      
        poffer= [select id,name ,Is_Offer_Selected__c, EBP_Offer_Code__c
                 from Pricing_Offer__c
                 where Application__c=:approvedOffers.applicationID and
                 Is_Offer_Selected__c=:true ];
        if(poffer.size()>0){
            for(Pricing_Offer__c p : pOffer){
                if(p.EBP_Offer_Code__c == null || p.EBP_Offer_Code__c.length() == 0) {
                    res.errorCode = PayoffConstants.ERROR;
                    res.status = PayoffConstants.FAIL;
                    res.errorMessage = 'One loan offer is already selected . Contact the support team for any queries';
                    String infoStr = res.errorMessage + '--Pricing Offer Record = '+ JSON.serialize(p);
                    MW_LogUtility.warn('WSSelectedOffer', approvedOffers.applicationID, app.Lead_Id__c, 'markTentativeOfferSelected',infoStr);
                    return res;
                }
            }
        }
                                      
        pOffer = [select id,
                 Above_prime_max__c,
                 Amount__c,
                 Application__c,
                 APR__c,
                 Interest_Rate__c,
                 Is_Offer_Selected__c,
                 Key__c,
                 Monthly_Payment__c,
                 Origination_fee__c,
                 Origination_fee_rate__c,
                 Pricing_Tier__c,
                 Segment__c,
                 Term__c,
                 Type__c
                 from Pricing_Offer__c
                 where Application__c=:approvedOffers.applicationID and
                (Key__c=:Integer.valueOf(approvedOffers.Key) or Is_Offer_Selected__c=:true)];
        system.debug(pOffer);
        if(pOffer != Null){
            List<Pricing_Offer__c> updateOffer=new List<Pricing_Offer__c>();
            try{
                for(Pricing_Offer__c p : pOffer){
                    if(p.Key__c == Integer.valueOf(approvedOffers.Key) && p.Is_Offer_Selected__c == true)
                        res.successMessage=PayoffConstants.THIS_OFFER_IS_ALREADY_APPROVED; 
                        system.debug('p1' + p);
                    if( p.Is_Offer_Selected__c == true && p.Key__c != Integer.valueOf(approvedOffers.Key) ){                    
                        p.Is_Offer_Selected__c = false;
                        update p;
                        system.debug('p2' + p);
                        approve1 =[select id,
                                  Above_prime_max__c,
                                  Amount__c,
                                  Application__c,
                                  APR__c,
                                  Interest_Rate__c,
                                  Key__c,
                                  Monthly_Payment__c,
                                  Origination_fee__c,
                                  Origination_fee_rate__c,
                                  Pricing_Tier__c,
                                  Segment__c,
                                  Term__c,
                                  Type__c
                                  from Approved_Offer__c
                                  where Application__c =:approvedOffers.applicationID and
                                  Key__c =:String.valueOf(p.Key__c)];
                        delete approve1;
                    }
                    if(p.Key__c == Integer.valueOf(approvedOffers.Key) && p.Is_Offer_Selected__c == false){
                        approve.Above_prime_max__c=p.Above_prime_max__c;
                        system.debug(approve.Above_prime_max__c);
                        approve.Amount__c=p.Amount__c;
                        approve.Application__c=p.Application__c;
                        approve.APR__c=String.valueOf(p.APR__c);
                        approve.Interest_Rate__c=String.valueOf(p.Interest_Rate__c);
                        approve.Key__c=String.valueOf(p.Key__c);
                        approve.Monthly_Payment__c=p.Monthly_Payment__c;
                        approve.Origination_fee__c=String.valueOf(p.Origination_fee__c);
                        approve.Origination_fee_rate__c=String.valueOf(p.Origination_fee_rate__c);
                        approve.Pricing_Tier__c=p.Pricing_Tier__c;
                        approve.Segment__c=p.Segment__c;
                        approve.Term__c=p.Term__c;
                        approve.Type__c=p.Type__c;
                        insert approve;
                        app.genesis__Loan_Amount__c=p.Amount__c;
                        app.genesis__APR__c=p.APR__c;
                        app.genesis__Term__c=p.Term__c;
                        app.Origination_fee__c=p.Origination_fee__c;
                        app.genesis__Monthly_Debt_Payments__c=p.Monthly_Payment__c;
                        app.genesis__Interest_Rate__c=p.Interest_Rate__c;
                        app.genesis__Financed_Amount__c= (p.Amount__c - p.Origination_fee__c);
                        app.genesis__Status__c='offer_accepted';

                        /*
                        LSP-870
                        Pricing Tier requests to AE via Pricing Offer trigger, have to run since it's the correct one.
                        If the pricing doesn't change, the update app can be allowed to execute (or not) now if it's supposed to
                        The app will be allocated because offer_accepted && Required_Docs_Count__c is bumped back to advp
                        via MW_ApplicationService.UpdateApplicationFlags by way of MW_CustomTriggerOnApplication1 before trigger execution
                         */
                        if (app.Required_Docs_Count__c == 0 && p.Pricing_Tier__c != app.Pricing_Tier__c) {
                            System.debug('WSSelectedOffer: Required_Docs_Count__c = 0 and Pricing_Tier__c changed');
                            InvestorAllocation.allocationForADVPcalled = true;
                        }

                        update app;
                        System.debug('WSSelectedOffer: update app completed');
                        p.Is_Offer_Selected__c=true;
                        updateOffer.add(p);
                        system.debug('poffer'+p);
                    }
                    if(!updateOffer.isEmpty())
                        update updateOffer;
                    system.debug('updated offer'+updateOffer);
                } 
            } catch(exception ex){
                MW_LogUtility.ExceptionDO expRex = new MW_LogUtility.ExceptionDO(ex);
                MW_DataDogCallOut.futureSend(JSON.serialize(getLogRecord('WSSelectedOffer', approvedOffers.applicationID, app.Lead_Id__c, 'markTentativeOfferSelected',JSON.serialize(expRex),'Error',null)), new List<String>());
        		res.errorCode = PayoffConstants.ERROR;
                res.status = PayoffConstants.FAIL;
                res.errorMessage = 'Error in CLS : '+JSON.serialize(expRex);
                return res;
            }
        }
        res.errorCode = PayoffConstants.NO_ERROR;
        res.status = PayoffConstants.SUCCESS; 
        MW_DataDogCallOut.futureSend(JSON.serialize(getLogRecord('WSSelectedOffer', approvedOffers.applicationID, app.Lead_Id__c, 'markTentativeOfferSelected',res.status,'info',null)), new List<String>());
        return res;
    }    
    public static MW_LogUtility.Log getLogRecord(String cls,String appId,String leadId,String method,Object data,String type,Integer code){
        MW_LogUtility.Log log = new MW_LogUtility.Log();
        log.apexClass = cls;
        log.applicationId = appId;
        log.leadId = leadId;
        log.method = method;
        log.data = data;
        log.type = type;
        log.statusCode = code;
        return log; 
    }
}