force-app/main/default/objects/loan__Batch_Process_Log__c/loan__Batch_Process_Log__c.object-meta.xml
<CustomObject>
    <label>Batch Process Log</label>
    <nameField>
        <label>Apex Batch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Batch Process Log</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/loan__Batch_Process_Log__c/fields/loan__Batch_Id__c.field-meta.xml
<CustomField>
    <fullName>loan__Batch_Id__c</fullName>
    <label>Batch Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/loan__Batch_Process_Log__c/fields/loan__Log_Level__c.field-meta.xml
<CustomField>
    <fullName>loan__Log_Level__c</fullName>
    <description>An indicator of level of logging</description>
    <label>Log Level</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ERROR</fullName>
                <default>true</default>
                <label>ERROR</label>
            </value>
            <value>
                <fullName>DEBUG</fullName>
            </value>
            <value>
                <fullName>INFO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/loan__Batch_Process_Log__c/fields/loan__Message__c.field-meta.xml
<CustomField>
    <fullName>loan__Message__c</fullName>
    <label>Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/loan__Loan_Account__c.object-meta.xml
<CustomObject>
    <description>Lending Account</description>
    <label>CL Contract</label>
    <nameField>
        <displayFormat>LAI-{00000000}</displayFormat>
        <label>CL Contract ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CL Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/loan__Loan_Account__c/fields/datafixupb__c.field-meta.xml
<CustomField>
    <fullName>datafixupb__c</fullName>
    <defaultValue>false</defaultValue>
    <label>datafixupb</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/loan__Loan_Amount__c.field-meta.xml
<CustomField>
    <fullName>loan__Loan_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Loan Amount</description>
    <inlineHelpText>This is the financed amount on the contract which will be disbursed to the customer.</inlineHelpText>
    <label>Loan Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/loan__Principal_Paid__c.field-meta.xml
<CustomField>
    <fullName>loan__Principal_Paid__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Principal Paid Account Balance Details- System calculated Uneditable fields</description>
    <inlineHelpText>Paid Principal/Advance.</inlineHelpText>
    <label>Principal/Advance Paid</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/Negprincipal__c.field-meta.xml
<CustomField>
    <fullName>Negprincipal__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Negprincipal</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/UPBfixed__c.field-meta.xml
<CustomField>
    <fullName>UPBfixed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>UPBfixed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/UPBunaffected__c.field-meta.xml
<CustomField>
    <fullName>UPBunaffected__c</fullName>
    <defaultValue>false</defaultValue>
    <label>UPBunaffected</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Payment_Transaction__c/loan__Loan_Payment_Transaction__c.object-meta.xml
<CustomObject>
    <description>Loan Payment Transaction</description>
    <label>Loan Payment Transaction</label>
    <nameField>
        <displayFormat>LPT-{000000000}</displayFormat>
        <label>Loan Payment Transaction ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loan Payment Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/loan__Loan_Payment_Transaction__c/fields/loan__Loan_Account__c.field-meta.xml
<CustomField>
    <fullName>loan__Loan_Account__c</fullName>
    <description>Loan Account</description>
    <inlineHelpText>Loan Account</inlineHelpText>
    <label>Loan Account</label>
    <referenceTo>loan__Loan_Account__c</referenceTo>
    <relationshipLabel>Loan Payment Transactions</relationshipLabel>
    <relationshipName>Loan_Payment_Transactions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Payment_Transaction__c/fields/loan__Principal__c.field-meta.xml
<CustomField>
    <fullName>loan__Principal__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>This is the Principal amount collected for the loan</inlineHelpText>
    <label>Principal</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/UPBreportPatch.cls
Global class  UPBreportPatch {
    
    public loan__Loan_Account__c LAtobeUpdated;   
    global UPBreportPatch(loan__loan_Account__c LoanAccount){
        
        LAtobeUpdated = LoanAccount;
    }
    
    global void Reportupbloan() {
        
        Decimal totalPrincipalonLPTs;
        Decimal PrincipalDiff = 0.00;
        Decimal PrincipalforLA = 0.00;
        Decimal PrincipalDiff1= 0.00;
               
        loan__loan_account__c affectedLoans = new loan__loan_account__c();    
        loan__loan_account__c unaffectedLoans = new loan__loan_account__c();     
        loan__loan_account__c NegaffectedLoans = new loan__loan_account__c(); 
        List<loan__Loan_Payment_Transaction__c> LPTs = new List<loan__Loan_Payment_Transaction__c>(); 
        set<id> LPT1 = new set<id>();       
        
        loan.GlobalLoanUtilFacade util = new loan.GlobalLoanUtilFacade();
        Date systemDate = util.getCurrentSystemDate();
        
        loan__Batch_Process_Log__c batch = new loan__Batch_Process_Log__c();
        
        try{                       
           
            PrincipalforLA = LAtobeUpdated.loan__Principal_Paid__c;
            
            /*for(loan__Loan_Payment_Transaction__c lpt : LAtobeUpdated.loan__Loan_Payment_Transactions__r){
                LPTs.add(lpt);
            }*/  

            system.debug(LAtobeUpdated.loan__Loan_Payment_Transactions__r.size());       
          
            if(LAtobeUpdated.loan__Loan_Payment_Transactions__r.size() > 0){
             
                PrincipalDiff = 0.00; 
                totalPrincipalonLPTs = 0.00;
                PrincipalDiff1= 0.00;
                
                for(loan__loan_payment_transaction__c LPT3 : LAtobeUpdated.loan__Loan_Payment_Transactions__r){
                  
                    totalPrincipalonLPTs = totalPrincipalonLPTs + LPT3.loan__Principal__c;
                    System.debug(logginglevel.error, ' totalPrincipalonLPTs :: ' +totalPrincipalonLPTs);
                    
                } 
                
            }
           
            if(LAtobeUpdated.loan__Principal_Paid__c == totalPrincipalonLPTs){
                
                unaffectedLoans = LAtobeUpdated;
                System.debug(logginglevel.error,' UnAffected Loans :: ' +unaffectedLoans);
                System.debug(logginglevel.error, ' LA.loan__Principal_Paid__c :: ' +LAtobeUpdated.loan__Principal_Paid__c);
                System.debug(logginglevel.error, ' totalPrincipalonLPTs :: ' +totalPrincipalonLPTs); 
                
                /*pallavi(moving the update part here)*/
                UnaffectedLoans.datafixupb__c = true;
                UnaffectedLoans.UPBunaffected__c=true;
                //UnaffectedLoans.UPBfixed__c=true;  //Commented by Saryu as we will mark this as UPAfixed in the UPA batch
                update UnaffectedLoans;
                /*pallavi*/
            
            }else{

                PrincipalDiff = totalPrincipalonLPTs - PrincipalforLA;
                System.debug(logginglevel.error, 'PrincipalDiff :: ' +PrincipalDiff);
         
                PrincipalDiff1 = PrincipalforLA - totalPrincipalonLPTs;
                System.debug(logginglevel.error, 'PrincipalDiff1 :: ' +PrincipalDiff);
         
                if (totalPrincipalonLPTs > LAtobeUpdated.loan__Loan_Amount__c){
           
                   NegaffectedLoans = LAtobeUpdated;
                   NegaffectedLoans.Negprincipal__c=true; 
                   NegaffectedLoans.datafixupb__c=true;
                   update NegaffectedLoans;

                }
                          
                if(PrincipalDiff>=0){

                    affectedLoans = LAtobeUpdated;
                    affectedLoans.datafixupb__c=true;
                    System.debug(logginglevel.error, ' affectedLoans.loan__Principal_Paid__c :: ' +affectedLoans.loan__Principal_Paid__c);
                    System.debug(logginglevel.error, ' totalPrincipalonLPTs :: ' +totalPrincipalonLPTs); 
                    update affectedLoans;
                } 

            }
      
        }catch (Exception e) {
            
            batch.loan__Log_Level__c = 'ERROR';
            batch.loan__Message__c = ' Data fix failed for ::'+ LAtobeUpdated.Name + '. :: ERROR :: '+e.getMessage() + ' :: StackTrace ::' +e.getStackTraceString() ;
            batch.loan__Batch_Id__c = 'UPBreportPatch';
            insert batch;
            
            System.debug(logginglevel.error,'line number'+e.getLineNumber());
            System.debug(logginglevel.error,'error stackTrace'+e.getStackTraceString());
            System.debug(logginglevel.error,'error message'+e.getMessage()); 
            
        }        
        
    }
    
}