force-app/main/default/objects/loan__Batch_Process_Log__c/loan__Batch_Process_Log__c.object-meta.xml
<CustomObject>
    <label>Batch Process Log</label>
    <nameField>
        <label>Apex Batch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Batch Process Log</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/loan__Batch_Process_Log__c/fields/loan__Batch_Id__c.field-meta.xml
<CustomField>
    <fullName>loan__Batch_Id__c</fullName>
    <label>Batch Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/loan__Batch_Process_Log__c/fields/loan__Log_Level__c.field-meta.xml
<CustomField>
    <fullName>loan__Log_Level__c</fullName>
    <description>An indicator of level of logging</description>
    <label>Log Level</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ERROR</fullName>
                <default>true</default>
                <label>ERROR</label>
            </value>
            <value>
                <fullName>DEBUG</fullName>
            </value>
            <value>
                <fullName>INFO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/loan__Batch_Process_Log__c/fields/loan__Message__c.field-meta.xml
<CustomField>
    <fullName>loan__Message__c</fullName>
    <label>Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/loan__Loan_Account__c.object-meta.xml
<CustomObject>
    <description>Lending Account</description>
    <label>CL Contract</label>
    <nameField>
        <displayFormat>LAI-{00000000}</displayFormat>
        <label>CL Contract ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CL Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/loan__Loan_Payment_Transaction__c/loan__Loan_Payment_Transaction__c.object-meta.xml
<CustomObject>
    <description>Loan Payment Transaction</description>
    <label>Loan Payment Transaction</label>
    <nameField>
        <displayFormat>LPT-{000000000}</displayFormat>
        <label>Loan Payment Transaction ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loan Payment Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/loan__Loan_Payment_Transaction__c/fields/Custom_Reverse__c.field-meta.xml
<CustomField>
    <fullName>Custom_Reverse__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Custom Reverse</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Payment_Transaction__c/fields/loan__Cleared__c.field-meta.xml
<CustomField>
    <fullName>loan__Cleared__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates if this loan payment transaction is supervised or not.</description>
    <inlineHelpText>Indicates if this loan payment transaction is supervised or not.</inlineHelpText>
    <label>Cleared</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Payment_Transaction__c/fields/loan__Loan_Account__c.field-meta.xml
<CustomField>
    <fullName>loan__Loan_Account__c</fullName>
    <description>Loan Account</description>
    <inlineHelpText>Loan Account</inlineHelpText>
    <label>Loan Account</label>
    <referenceTo>loan__Loan_Account__c</referenceTo>
    <relationshipLabel>Loan Payment Transactions</relationshipLabel>
    <relationshipName>Loan_Payment_Transactions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Payment_Transaction__c/fields/loan__Reversed__c.field-meta.xml
<CustomField>
    <fullName>loan__Reversed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Reversed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Payment_Transaction__c/fields/loan__Transaction_Date__c.field-meta.xml
<CustomField>
    <fullName>loan__Transaction_Date__c</fullName>
    <defaultValue>$User.loan__Current_Branch_s_System_Date__c</defaultValue>
    <description>Transaction Date</description>
    <inlineHelpText>Transaction Date</inlineHelpText>
    <label>Transaction Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/loan__Other_Transaction__c/loan__Other_Transaction__c.object-meta.xml
<CustomObject>
    <label>Other Loan Transaction</label>
    <nameField>
        <displayFormat>OLTID-{0000000000}</displayFormat>
        <label>Other Transaction ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Other Loan Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/loan__Other_Transaction__c/fields/loan__Loan_Account__c.field-meta.xml
<CustomField>
    <fullName>loan__Loan_Account__c</fullName>
    <label>Loan Account</label>
    <referenceTo>loan__Loan_Account__c</referenceTo>
    <relationshipLabel>Other Loan Transactions</relationshipLabel>
    <relationshipName>Other_Loan_Transactions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/loan__Other_Transaction__c/fields/loan__Loan_Payment_Transaction__c.field-meta.xml
<CustomField>
    <fullName>loan__Loan_Payment_Transaction__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loan Payment Transaction</label>
    <referenceTo>loan__Loan_Payment_Transaction__c</referenceTo>
    <relationshipLabel>Principal Adjustment Transactions</relationshipLabel>
    <relationshipName>Other_Loan_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/loan__Other_Transaction__c/fields/loan__Reference__c.field-meta.xml
<CustomField>
    <fullName>loan__Reference__c</fullName>
    <label>Reference</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/loan__Other_Transaction__c/fields/loan__Rejected__c.field-meta.xml
<CustomField>
    <fullName>loan__Rejected__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Rejected</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/loan__Other_Transaction__c/fields/loan__Reversed__c.field-meta.xml
<CustomField>
    <fullName>loan__Reversed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Reversed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/loan__Repayment_Transaction_Adjustment__c/loan__Repayment_Transaction_Adjustment__c.object-meta.xml
<CustomObject>
    <description>Repayment Transaction Adjustment Object</description>
    <label>Repayment Transaction Reversal</label>
    <nameField>
        <displayFormat>RTA-{0000000000}</displayFormat>
        <label>Repayment Transaction Adjustment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Repayment Transaction Reversal</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/loan__Repayment_Transaction_Adjustment__c/fields/loan__Adjustment_Txn_Date__c.field-meta.xml
<CustomField>
    <fullName>loan__Adjustment_Txn_Date__c</fullName>
    <defaultValue>$User.loan__Current_Branch_s_System_Date__c</defaultValue>
    <description>Adjustment Txn Date</description>
    <inlineHelpText>Adjustment Txn Date</inlineHelpText>
    <label>Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/loan__Repayment_Transaction_Adjustment__c/fields/loan__Cleared__c.field-meta.xml
<CustomField>
    <fullName>loan__Cleared__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Cleared</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/loan__Repayment_Transaction_Adjustment__c/fields/loan__Loan_Payment_Transaction__c.field-meta.xml
<CustomField>
    <fullName>loan__Loan_Payment_Transaction__c</fullName>
    <description>Loan Payment Transaction</description>
    <inlineHelpText>Loan Payment Transaction</inlineHelpText>
    <label>Loan Payment Transaction</label>
    <referenceTo>loan__Loan_Payment_Transaction__c</referenceTo>
    <relationshipName>Repayment_Transaction_Adjustment</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/loan__Repayment_Transaction_Adjustment__c/fields/loan__Reason_Code__c.field-meta.xml
<CustomField>
    <fullName>loan__Reason_Code__c</fullName>
    <label>Reason Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>NSF</fullName>
            </value>
            <value>
                <fullName>Human Error</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/loan__Repayment_Transaction_Adjustment__c/fields/loan__Rejected__c.field-meta.xml
<CustomField>
    <fullName>loan__Rejected__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Rejected</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/CLS_LPTReversalJobHandler.cls
public class CLS_LPTReversalJobHandler {
    
    loan__Batch_Process_Log__c batch = new loan__Batch_Process_Log__c();
    public static loan__Loan_Account__c loan;
    
    
    public CLS_LPTReversalJobHandler(loan__Loan_Account__c loan){
        System.debug('Loan:'+loan);
        loan = loan;
        
        List<loan__Other_Transaction__c> listOtherTxn = loan.loan__Other_Loan_Transactions__r;
        if(listOtherTxn.Size()>0 && listOtherTxn != null){
            batch.loan__Log_Level__c = 'ERROR';
            batch.loan__Message__c = 'Loan Contract has Other Transactions';
            batch.loan__Batch_Id__c = 'LPTReversalJobHandler';
            insert batch;
        }else{
            System.debug('Loan:'+loan);
            CLS_LPTReversalJobHandler.LPTReversal(loan);
        }
    }
    
    public static void LPTReversal(loan__Loan_Account__c loan){
        
        try{
            system.debug('Loan:'+loan.Id);
            List<loan__Loan_Payment_Transaction__c> LPTListtoBeReversed = [Select Id,Name,loan__Transaction_Date__c,Custom_Reverse__c
                                                                           FROM loan__Loan_Payment_Transaction__c 
                                                                           WHERE loan__Loan_Account__c =: loan.Id 
                                                                           AND loan__Reversed__c = false 
                                                                           AND Custom_Reverse__c = false
                                                                           AND loan__Rejected__c = false
                                                                           AND loan__Cleared__c = true ORDER BY loan__Transaction_Date__c DESC];
            System.debug('LPT List:'+LPTListtoBeReversed);
            List<loan__Loan_Payment_Transaction__c> lptTOBeUpdate = new List<loan__Loan_Payment_Transaction__c>();
            List<loan__Repayment_Transaction_Adjustment__c> reversalsToBeInserted = new List<loan__Repayment_Transaction_Adjustment__c>();
            
            //inserting repayment txn
            for(loan__Loan_Payment_Transaction__c lpt : LPTListtoBeReversed){
                //custom reverse flag
                lpt.Custom_Reverse__c = true;
                lptTOBeUpdate.add(lpt);
                
                loan__Repayment_Transaction_Adjustment__c reversalTxn  = new loan__Repayment_Transaction_Adjustment__c();
                reversalTxn.loan__Loan_Payment_Transaction__c = lpt.id;
                reversalTxn.loan__Adjustment_Txn_Date__c = date.today();
                reversalTxn.loan__Reason_Code__c = 'Human Error'; //has to be updated by the client
                reversalTxn.loan__Reference__c = 'UpdatedByScript'; //has to be updated by the client
                //reversalsToBeInserted.add(reversalTxn);
                System.debug('reversalsToBeInserted:'+reversalTxn);
                insert reversalTxn;
            }
            if(lptTOBeUpdate != null && lptTOBeUpdate.size() > 0){ 
                System.debug('lptTOBeUpdate:'+lptTOBeUpdate);
                update lptTOBeUpdate;
            }

            
        }catch(exception e){
            loan__Batch_Process_Log__c batch = new loan__Batch_Process_Log__c();
            System.debug('ERROR: '+e.getLineNumber()+'---'+e.getMessage());
            batch.loan__Log_Level__c = 'ERROR';
            batch.loan__Message__c = 'ERROR at:'+e.getLineNumber()+'--'+e.getMessage();
            batch.loan__Batch_Id__c = 'LPTReversalJobHandler';
            insert batch;
        }
    }
    
    
}