force-app/main/default/objects/loan__Batch_Process_Log__c/loan__Batch_Process_Log__c.object-meta.xml
<CustomObject>
    <label>Batch Process Log</label>
    <nameField>
        <label>Apex Batch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Batch Process Log</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/loan__Batch_Process_Log__c/fields/loan__Batch_Id__c.field-meta.xml
<CustomField>
    <fullName>loan__Batch_Id__c</fullName>
    <label>Batch Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/loan__Batch_Process_Log__c/fields/loan__Log_Level__c.field-meta.xml
<CustomField>
    <fullName>loan__Log_Level__c</fullName>
    <description>An indicator of level of logging</description>
    <label>Log Level</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ERROR</fullName>
                <default>true</default>
                <label>ERROR</label>
            </value>
            <value>
                <fullName>DEBUG</fullName>
            </value>
            <value>
                <fullName>INFO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/loan__Batch_Process_Log__c/fields/loan__Message__c.field-meta.xml
<CustomField>
    <fullName>loan__Message__c</fullName>
    <label>Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/loan__Interest_Posting_Transaction__c/loan__Interest_Posting_Transaction__c.object-meta.xml
<CustomObject>
    <label>Interest Posting Transaction</label>
    <nameField>
        <displayFormat>IPT-{00000000}</displayFormat>
        <label>Interest Posting Transaction Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interest Posting Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/loan__Interest_Posting_Transaction__c/fields/loan__Amortization_Schedule__c.field-meta.xml
<CustomField>
    <fullName>loan__Amortization_Schedule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This fields defines a one to one mapping between amortisation schedule and regular Interest Posting Transaction for Flexible Amz Loans.</description>
    <label>Amortization Schedule</label>
    <referenceTo>loan__Repayment_Schedule__c</referenceTo>
    <relationshipLabel>Interest Posting Transactions</relationshipLabel>
    <relationshipName>Interest_Posting_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/loan__Interest_Posting_Transaction__c/fields/loan__Interest_Paid__c.field-meta.xml
<CustomField>
    <fullName>loan__Interest_Paid__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Interest Paid</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/loan__Interest_Posting_Transaction__c/fields/loan__Interest_Posted__c.field-meta.xml
<CustomField>
    <fullName>loan__Interest_Posted__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Interest Posted</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/loan__Interest_Posting_Transaction__c/fields/loan__Interest_Remaining__c.field-meta.xml
<CustomField>
    <fullName>loan__Interest_Remaining__c</fullName>
    <label>Interest Remaining</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/loan__Interest_Posting_Transaction__c/fields/loan__Loan_Contract__c.field-meta.xml
<CustomField>
    <fullName>loan__Loan_Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CL Contract</label>
    <referenceTo>loan__Loan_Account__c</referenceTo>
    <relationshipLabel>Interest Posting Transactions</relationshipLabel>
    <relationshipName>Interest_Posting_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/loan__Interest_Posting_Transaction__c/fields/loan__Principal_Paid__c.field-meta.xml
<CustomField>
    <fullName>loan__Principal_Paid__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Arrear Principal Paid. Only used for AMZ Based Loans.</inlineHelpText>
    <label>Principal Paid</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/loan__Loan_Account__c.object-meta.xml
<CustomObject>
    <description>Lending Account</description>
    <label>CL Contract</label>
    <nameField>
        <displayFormat>LAI-{00000000}</displayFormat>
        <label>CL Contract ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CL Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/loan__Loan_Account__c/fields/IR_Fixed__c.field-meta.xml
<CustomField>
    <fullName>IR_Fixed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>used to track the IR data fix</description>
    <label>IR_Fixed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/loan__Interest_Paid__c.field-meta.xml
<CustomField>
    <fullName>loan__Interest_Paid__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Interest Paid
Account Balance Details- System calculated Uneditable fields</description>
    <inlineHelpText>Interest Paid
Account Balance Details- Fields calculated by the system which cannot be edited.</inlineHelpText>
    <label>Interest Paid</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/loan__Interest_Posted__c.field-meta.xml
<CustomField>
    <fullName>loan__Interest_Posted__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Interest Posted on account</description>
    <inlineHelpText>Interest Posted on account.</inlineHelpText>
    <label>Interest Posted</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/loan__Interest_Remaining__c.field-meta.xml
<CustomField>
    <fullName>loan__Interest_Remaining__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Unpaid Interest, accrued till last accrual date.</description>
    <inlineHelpText>Unpaid Interest, accrued till last accrual date.</inlineHelpText>
    <label>Interest Remaining</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/loan__Principal_Paid__c.field-meta.xml
<CustomField>
    <fullName>loan__Principal_Paid__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Principal Paid Account Balance Details- System calculated Uneditable fields</description>
    <inlineHelpText>Paid Principal/Advance.</inlineHelpText>
    <label>Principal/Advance Paid</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Payment_Transaction__c/loan__Loan_Payment_Transaction__c.object-meta.xml
<CustomObject>
    <description>Loan Payment Transaction</description>
    <label>Loan Payment Transaction</label>
    <nameField>
        <displayFormat>LPT-{000000000}</displayFormat>
        <label>Loan Payment Transaction ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loan Payment Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/loan__Loan_Payment_Transaction__c/fields/loan__Interest__c.field-meta.xml
<CustomField>
    <fullName>loan__Interest__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Interest component for this payment.</description>
    <inlineHelpText>This is the Interest amount collected for the loan</inlineHelpText>
    <label>Interest</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Payment_Transaction__c/fields/loan__Loan_Account__c.field-meta.xml
<CustomField>
    <fullName>loan__Loan_Account__c</fullName>
    <description>Loan Account</description>
    <inlineHelpText>Loan Account</inlineHelpText>
    <label>Loan Account</label>
    <referenceTo>loan__Loan_Account__c</referenceTo>
    <relationshipLabel>Loan Payment Transactions</relationshipLabel>
    <relationshipName>Loan_Payment_Transactions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Payment_Transaction__c/fields/loan__Principal__c.field-meta.xml
<CustomField>
    <fullName>loan__Principal__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>This is the Principal amount collected for the loan</inlineHelpText>
    <label>Principal</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/loan__Repayment_Schedule__c/loan__Repayment_Schedule__c.object-meta.xml
<CustomObject>
    <description>Amortization schedule is also called as Repayment schedule.</description>
    <label>Amortization Schedule</label>
    <nameField>
        <displayFormat>RSI-{0000000000}</displayFormat>
        <label>Repayment Schedule ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Amortization Schedule</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/loan__Repayment_Schedule__c/fields/loan__Due_Interest__c.field-meta.xml
<CustomField>
    <fullName>loan__Due_Interest__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Due Interest</description>
    <inlineHelpText>Due Interest</inlineHelpText>
    <label>Due Interest</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/loan__Repayment_Schedule__c/fields/loan__Loan_Account__c.field-meta.xml
<CustomField>
    <fullName>loan__Loan_Account__c</fullName>
    <description>Repayment Schedule of which Loan account</description>
    <inlineHelpText>Repayment Schedule of which Loan account</inlineHelpText>
    <label>Loan Account</label>
    <referenceTo>loan__Loan_Account__c</referenceTo>
    <relationshipName>Repayment_Schedule</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/InterestFixBatch.cls
/*Author : Vishal Lakkammanavar - CLS */

global class InterestFixBatch {
    
    public loan__Loan_Account__c LAtobeUpdated;   
    global InterestFixBatch(loan__loan_Account__c LoanAccount){
        
        LAtobeUpdated = LoanAccount;
    }
    
    global void FixInterestloan() {
            
        system.debug('Inside FixInterestloan');
    
        Decimal totalPrincipalonLPTs;
        Decimal PrincipalDiff = 0.00;
        Decimal InterestDiff = 0.00;
        Decimal PrincipalforLA = 0.00;
        Decimal InterestRemainingforLA = 0.00;
        Decimal InterestPaidforLA = 0.00;
        Decimal InterestSum = 0.00;
        Decimal IPTInterest = 0.00;
        Decimal RepaymentDueInterest = 0.00;
        Decimal InterestRemainingtobeupdated = 0.00;
        Boolean toFix = false;
                 
        loan__loan_account__c affectedLoans = new loan__loan_account__c();         
        loan__loan_account__c affectedLoans1 = new loan__loan_account__c();    
        
        set<id> LPT1 = new set<id>();
        
        loan.GlobalLoanUtilFacade util = new loan.GlobalLoanUtilFacade();
        Date systemDate = util.getCurrentSystemDate();
        
        loan__Batch_Process_Log__c batch = new loan__Batch_Process_Log__c();
        
        try{
                      
            List<loan__Loan_Payment_Transaction__c> LPTs = new List<loan__Loan_Payment_Transaction__c>();
            List<loan__Interest_Posting_Transaction__c> IPTs = new List<loan__Interest_Posting_Transaction__c>();           
            List<loan__Repayment_Schedule__c> AMZs = new List<loan__Repayment_Schedule__c>();
            
            PrincipalforLA = LAtobeUpdated.loan__Principal_Paid__c;
            InterestPaidforLA = LAtobeUpdated.loan__Interest_Paid__c;
            InterestRemainingforLA = LAtobeUpdated.loan__Interest_Remaining__c;
            
            for(loan__Loan_Payment_Transaction__c lpt : LAtobeUpdated.loan__Loan_Payment_Transactions__r){ 
                LPTs.add(lpt);
            }  
            system.debug(LPTs.size());
            
            for(loan__Interest_Posting_Transaction__c IPT : LAtobeUpdated.loan__Interest_Posting_Transactions__r){
                IPTs.add(ipt);
            }
       
            
            for(loan__Repayment_Schedule__c AMZ : LAtobeUpdated.loan__Repayment_Schedule__r){
                AMZs.add(AMZ);
            }
            
            if(LPTs.size() > 0){
             
                PrincipalDiff = 0.00; 
                InterestSum = 0.00;
                totalPrincipalonLPTs = 0.00;
                
                for(loan__loan_payment_transaction__c LPT3 : LPTs){
                  
                    totalPrincipalonLPTs = totalPrincipalonLPTs + LPT3.loan__Principal__c;
                    InterestSum = InterestSum + LPT3.loan__Interest__c;
                    System.debug(logginglevel.error, ' totalInterestonLPTs :: ' +InterestSum);
                    System.debug(logginglevel.error, ' totalPrincipalonLPTs :: ' +totalPrincipalonLPTs);
                    
                } 
                
            }
            
            if(IPTs.size() > 0){
             
                for(loan__Interest_Posting_Transaction__c IPT3 : IPTs){

                    IPTInterest = IPTInterest + IPT3.loan__Interest_Posted__c;   
                } 
                
            }
            
            /*Repayment schedule Due Interest Vishal*/
            
            if(AMZs.size() > 0){
             for(loan__Repayment_Schedule__c AMZ3 : AMZs){
              RepaymentDueInterest = RepaymentDueInterest + AMZ3.loan__Due_Interest__c;
              }
            }
            
                    
                if(RepaymentDueInterest == InterestPaidforLA ) {
                 affectedLoans = LAtobeUpdated;

                    if(InterestPaidforLA == InterestSum ) {
                   
                   System.debug(logginglevel.error, ' RepaymentDueInterest :: ' + RepaymentDueInterest);
                   System.debug(logginglevel.error, ' InterestPaidforLA :: ' + InterestPaidforLA); 
                   
                   
                   if( InterestRemainingforLA > 0.0){
                                 
                  affectedLoans.Loan__interest_Remaining__c = InterestRemainingtobeupdated ;
                 
                 System.debug(logginglevel.error, ' affectedLoans.Loan__interest_Remaining__c :: ' + affectedLoans.Loan__interest_Remaining__c); 
                  
                  }
                  
                 }

                 if(InterestPaidforLA != InterestSum) {
                 
                   InterestPaidforLA = InterestSum;
                   
                   InterestRemainingtobeupdated = RepaymentDueInterest - InterestPaidforLA;
                    
                   affectedLoans.Loan__interest_Remaining__c = InterestRemainingtobeupdated ;
                   affectedLoans.Loan__interest_Paid__c = InterestPaidforLA;
                   
                  }
                  
              affectedLoans.IR_Fixed__c = true;
              
              update affectedLoans;
             }


              else if( RepaymentDueInterest > InterestPaidforLA ){
                 
                 System.debug(logginglevel.error, ' RepaymentDueInterest :: ' + RepaymentDueInterest);
                 System.debug(logginglevel.error, ' InterestPaidforLA :: ' + InterestPaidforLA); 
                  
                 affectedLoans1 = LAtobeUpdated;
                     
                  if(InterestPaidforLA != InterestSum){
                      InterestPaidforLA = InterestSum;
                      
                   } 
                
                 InterestRemainingtobeupdated  = RepaymentDueInterest - InterestPaidforLA;
                 System.debug(logginglevel.error, ' affectedLoans1.InterestRemainingtobeupdated :: ' + InterestRemainingtobeupdated); 
                 affectedLoans1.Loan__interest_Paid__c = InterestPaidforLA ;           
                 affectedLoans1.Loan__interest_Remaining__c = InterestRemainingtobeupdated ;
                 System.debug(logginglevel.error, ' affectedLoans1.Loan__interest_Remaining__c :: ' + affectedLoans1.Loan__interest_Remaining__c ); 
                affectedLoans1.IR_Fixed__c = true;
                update affectedLoans1;
              }
              
                   
            }
       
         catch (Exception e) {
            
            batch.loan__Log_Level__c = 'ERROR';
            batch.loan__Message__c = ' Data fix failed for ::'+ LAtobeUpdated.Name + '. :: ERROR :: '+e.getMessage() + ' :: StackTrace ::' +e.getStackTraceString() ;
            batch.loan__Batch_Id__c = 'InterestFixBatch';
            insert batch;
            
            System.debug(logginglevel.error,'line number'+e.getLineNumber());
            System.debug(logginglevel.error,'error stackTrace'+e.getStackTraceString());
            System.debug(logginglevel.error,'error message'+e.getMessage()); 
            
        }       
        
    }   
}