force-app/main/default/objects/loan__Batch_Process_Log__c/loan__Batch_Process_Log__c.object-meta.xml
<CustomObject>
    <label>Batch Process Log</label>
    <nameField>
        <label>Apex Batch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Batch Process Log</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/loan__Batch_Process_Log__c/fields/loan__Batch_Id__c.field-meta.xml
<CustomField>
    <fullName>loan__Batch_Id__c</fullName>
    <label>Batch Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/loan__Batch_Process_Log__c/fields/loan__Log_Level__c.field-meta.xml
<CustomField>
    <fullName>loan__Log_Level__c</fullName>
    <description>An indicator of level of logging</description>
    <label>Log Level</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ERROR</fullName>
                <default>true</default>
                <label>ERROR</label>
            </value>
            <value>
                <fullName>DEBUG</fullName>
            </value>
            <value>
                <fullName>INFO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/loan__Batch_Process_Log__c/fields/loan__Message__c.field-meta.xml
<CustomField>
    <fullName>loan__Message__c</fullName>
    <label>Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/loan__Interest_Posting_Transaction__c/loan__Interest_Posting_Transaction__c.object-meta.xml
<CustomObject>
    <label>Interest Posting Transaction</label>
    <nameField>
        <displayFormat>IPT-{00000000}</displayFormat>
        <label>Interest Posting Transaction Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interest Posting Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/loan__Interest_Posting_Transaction__c/fields/loan__Discarded__c.field-meta.xml
<CustomField>
    <fullName>loan__Discarded__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field will represent that the record is no longer in use as it is discarded via. some action like Reschedule.</description>
    <label>Discarded</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/loan__Interest_Posting_Transaction__c/fields/loan__Interest_Posted__c.field-meta.xml
<CustomField>
    <fullName>loan__Interest_Posted__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Interest Posted</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/loan__Interest_Posting_Transaction__c/fields/loan__Loan_Contract__c.field-meta.xml
<CustomField>
    <fullName>loan__Loan_Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CL Contract</label>
    <referenceTo>loan__Loan_Account__c</referenceTo>
    <relationshipLabel>Interest Posting Transactions</relationshipLabel>
    <relationshipName>Interest_Posting_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/loan__Interest_Posting_Transaction__c/fields/loan__Principal_Posted__c.field-meta.xml
<CustomField>
    <fullName>loan__Principal_Posted__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Arrear Principal Posted. Used only for AMZ Based Loans.</inlineHelpText>
    <label>Principal Posted</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/loan__Loan_Account__c.object-meta.xml
<CustomObject>
    <description>Lending Account</description>
    <label>CL Contract</label>
    <nameField>
        <displayFormat>LAI-{00000000}</displayFormat>
        <label>CL Contract ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CL Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/loan__Loan_Account__c/fields/loan__Accrual_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>loan__Accrual_Start_Date__c</fullName>
    <description>The date from which interest accrual starts</description>
    <inlineHelpText>The date from which interest accrual starts</inlineHelpText>
    <label>Accrual Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/loan__Expected_Repayment_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>loan__Expected_Repayment_Start_Date__c</fullName>
    <defaultValue>TODAY() + 30</defaultValue>
    <inlineHelpText>This will be the date from when the customer will be start making the payments on this contract. The first payment date will be derived from payment start date.</inlineHelpText>
    <label>Payment Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/loan__Interest_Posted__c.field-meta.xml
<CustomField>
    <fullName>loan__Interest_Posted__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Interest Posted on account</description>
    <inlineHelpText>Interest Posted on account.</inlineHelpText>
    <label>Interest Posted</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/loan__Last_Interest_Posting_Date__c.field-meta.xml
<CustomField>
    <fullName>loan__Last_Interest_Posting_Date__c</fullName>
    <label>Last Interest Posting Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/loan__Next_Installment_Date__c.field-meta.xml
<CustomField>
    <fullName>loan__Next_Installment_Date__c</fullName>
    <description>Date of the next installment</description>
    <inlineHelpText>Date of the Next Due</inlineHelpText>
    <label>Next Due Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/loan__Next_Interest_Posting_Date__c.field-meta.xml
<CustomField>
    <fullName>loan__Next_Interest_Posting_Date__c</fullName>
    <label>Next Interest Posting Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/loan__Principal_Posted__c.field-meta.xml
<CustomField>
    <fullName>loan__Principal_Posted__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Principal/Advance Posted</description>
    <inlineHelpText>Total Principal/Advance given to customer.</inlineHelpText>
    <label>Principal/Advance Posted</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/CLS_IPTDiscardHandler.cls
public class CLS_IPTDiscardHandler {
    
    loan__Batch_Process_Log__c batch = new loan__Batch_Process_Log__c();
    public loan__Loan_Account__c loanAcctoUpdate;
    
    public CLS_IPTDiscardHandler(loan__Loan_Account__c loan){
        try{
            this.loanAcctoUpdate = loan;
            loanAcctoUpdate.loan__Next_Interest_Posting_Date__c = loanAcctoUpdate.loan__Accrual_Start_Date__c;
            loanAcctoUpdate.loan__Principal_Posted__c = 0;
            loanAcctoUpdate.loan__Next_Installment_Date__c = loanAcctoUpdate.loan__Expected_Repayment_Start_Date__c;
            loanAcctoUpdate.loan__Interest_Posted__c = 0;
            loanAcctoUpdate.loan__Last_Interest_Posting_Date__c = null;
            update loanAcctoUpdate;
            //discard IPT
            discardIPT();
        }catch(exception e){
            System.debug('ERROR:'+e.getLineNumber()+'---'+e.getMessage());
            batch.loan__Log_Level__c = 'ERROR';
            batch.loan__Message__c = 'ERROR at:'+e.getLineNumber()+'--'+e.getMessage();
            batch.loan__Batch_Id__c = 'IPTDiscardHandler';
            insert batch;
        }
        
    }
    
    public void discardIPT(){
        
        List<loan__Interest_Posting_Transaction__c> iptList = [SELECT Id,Name,loan__Discarded__c FROM loan__Interest_Posting_Transaction__c
                                                               WHERE loan__Loan_Contract__c=:loanAcctoUpdate.Id AND loan__Discarded__c = false];
        
        List<loan__Interest_Posting_Transaction__c> iptListToDiscard = new List<loan__Interest_Posting_Transaction__c>();
        if(iptList.Size()>0 && iptList != null){
            for(loan__Interest_Posting_Transaction__c ipt:iptList){
                ipt.loan__Discarded__c = true;
                iptListToDiscard.add(ipt);
            }
            
            if(iptListToDiscard != null && iptListToDiscard.Size()>0){
                update iptListToDiscard;
            }
        }  
    }
}