force-app/main/default/objects/loan__Batch_Process_Log__c/loan__Batch_Process_Log__c.object-meta.xml
<CustomObject>
    <label>Batch Process Log</label>
    <nameField>
        <label>Apex Batch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Batch Process Log</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/loan__Batch_Process_Log__c/fields/loan__Batch_Id__c.field-meta.xml
<CustomField>
    <fullName>loan__Batch_Id__c</fullName>
    <label>Batch Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/loan__Batch_Process_Log__c/fields/loan__Log_Level__c.field-meta.xml
<CustomField>
    <fullName>loan__Log_Level__c</fullName>
    <description>An indicator of level of logging</description>
    <label>Log Level</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ERROR</fullName>
                <default>true</default>
                <label>ERROR</label>
            </value>
            <value>
                <fullName>DEBUG</fullName>
            </value>
            <value>
                <fullName>INFO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/loan__Batch_Process_Log__c/fields/loan__Message__c.field-meta.xml
<CustomField>
    <fullName>loan__Message__c</fullName>
    <label>Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/loan__Loan_Account__c.object-meta.xml
<CustomObject>
    <description>Lending Account</description>
    <label>CL Contract</label>
    <nameField>
        <displayFormat>LAI-{00000000}</displayFormat>
        <label>CL Contract ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CL Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/loan__Loan_Account__c/fields/datafixupb__c.field-meta.xml
<CustomField>
    <fullName>datafixupb__c</fullName>
    <defaultValue>false</defaultValue>
    <label>datafixupb</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/loan__Interest_Paid__c.field-meta.xml
<CustomField>
    <fullName>loan__Interest_Paid__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Interest Paid
Account Balance Details- System calculated Uneditable fields</description>
    <inlineHelpText>Interest Paid
Account Balance Details- Fields calculated by the system which cannot be edited.</inlineHelpText>
    <label>Interest Paid</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/loan__Interest_Remaining__c.field-meta.xml
<CustomField>
    <fullName>loan__Interest_Remaining__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Unpaid Interest, accrued till last accrual date.</description>
    <inlineHelpText>Unpaid Interest, accrued till last accrual date.</inlineHelpText>
    <label>Interest Remaining</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/loan__Last_Accrual_Date__c.field-meta.xml
<CustomField>
    <fullName>loan__Last_Accrual_Date__c</fullName>
    <description>Last accrual Date on loan account</description>
    <inlineHelpText>The date on which Interest was computed and posted on the Account.</inlineHelpText>
    <label>Last Accrual Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/loan__Loan_Amount__c.field-meta.xml
<CustomField>
    <fullName>loan__Loan_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Loan Amount</description>
    <inlineHelpText>This is the financed amount on the contract which will be disbursed to the customer.</inlineHelpText>
    <label>Loan Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/loan__Loan_Status__c.field-meta.xml
<CustomField>
    <fullName>loan__Loan_Status__c</fullName>
    <inlineHelpText>Status of the Account, expected values are :
Pending Approval
Active - Good Standing
Active - Bad Standing
Active - Matured
Approved
Canceled
Closed - Obligations met
Closed- Written Off
Closed - Refinanced
Partial Application</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Partial Application</fullName>
                <default>true</default>
                <label>Partial Application</label>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Active - Good Standing</fullName>
            </value>
            <value>
                <fullName>Active - Bad Standing</fullName>
            </value>
            <value>
                <fullName>Closed - Obligations met</fullName>
            </value>
            <value>
                <fullName>Closed- Written Off</fullName>
            </value>
            <value>
                <fullName>Closed - Refinanced</fullName>
            </value>
            <value>
                <fullName>Active - Matured</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Active - Marked for Closure</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/loan__Principal_Paid__c.field-meta.xml
<CustomField>
    <fullName>loan__Principal_Paid__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Principal Paid Account Balance Details- System calculated Uneditable fields</description>
    <inlineHelpText>Paid Principal/Advance.</inlineHelpText>
    <label>Principal/Advance Paid</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/loan__Principal_Remaining__c.field-meta.xml
<CustomField>
    <fullName>loan__Principal_Remaining__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Principal/Advance Remaining</description>
    <inlineHelpText>Unpaid Principal/advance balance on the loan account.</inlineHelpText>
    <label>Principal/Advance Remaining</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/loan__Uncleared_Repayment_Amount__c.field-meta.xml
<CustomField>
    <fullName>loan__Uncleared_Repayment_Amount__c</fullName>
    <description>The repaid amount, which has not yet been supervised.</description>
    <inlineHelpText>The reapaid amount, which has not yet been supervised.</inlineHelpText>
    <label>Uncleared Payment Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/UPBunaffected__c.field-meta.xml
<CustomField>
    <fullName>UPBunaffected__c</fullName>
    <defaultValue>false</defaultValue>
    <label>UPBunaffected</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Payment_Transaction__c/loan__Loan_Payment_Transaction__c.object-meta.xml
<CustomObject>
    <description>Loan Payment Transaction</description>
    <label>Loan Payment Transaction</label>
    <nameField>
        <displayFormat>LPT-{000000000}</displayFormat>
        <label>Loan Payment Transaction ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loan Payment Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/loan__Loan_Payment_Transaction__c/fields/loan__Cleared__c.field-meta.xml
<CustomField>
    <fullName>loan__Cleared__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates if this loan payment transaction is supervised or not.</description>
    <inlineHelpText>Indicates if this loan payment transaction is supervised or not.</inlineHelpText>
    <label>Cleared</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Payment_Transaction__c/fields/loan__Interest__c.field-meta.xml
<CustomField>
    <fullName>loan__Interest__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Interest component for this payment.</description>
    <inlineHelpText>This is the Interest amount collected for the loan</inlineHelpText>
    <label>Interest</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Payment_Transaction__c/fields/loan__Loan_Account__c.field-meta.xml
<CustomField>
    <fullName>loan__Loan_Account__c</fullName>
    <description>Loan Account</description>
    <inlineHelpText>Loan Account</inlineHelpText>
    <label>Loan Account</label>
    <referenceTo>loan__Loan_Account__c</referenceTo>
    <relationshipLabel>Loan Payment Transactions</relationshipLabel>
    <relationshipName>Loan_Payment_Transactions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Payment_Transaction__c/fields/loan__Principal__c.field-meta.xml
<CustomField>
    <fullName>loan__Principal__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>This is the Principal amount collected for the loan</inlineHelpText>
    <label>Principal</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Payment_Transaction__c/fields/loan__Reversed__c.field-meta.xml
<CustomField>
    <fullName>loan__Reversed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Reversed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Status__c/loan__Loan_Status__c.object-meta.xml
<CustomObject>
    <description>Object for storing Loan Statuses</description>
    <label>Loan Status</label>
    <nameField>
        <label>Loan Status Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loan Status</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/UPBreportbatch.cls
Global class UPBreportbatch implements Database.Batchable<sObject> {
    
    String query = '';
    public Set<Id> lacc = new Set<Id>();
    Date systemDate = new loan.GlobalLoanUtilFacade().getCurrentSystemDate();
    
    public List<String> status = new List<String>();
    loan__Batch_Process_Log__c batch = new loan__Batch_Process_Log__c();
    
    global UPBreportbatch(){

        System.debug('default constructor');
        status.add('Active - Good Standing');
        status.add('Active - Bad Standing');
        //list<loan__loan_account__c> ls = [select id from loan__loan_account__c where loan__Loan_Status__c in:status]; - commented by Neha. Why not have the same query added below?
        
        query = 'Select id from loan__loan_account__c where loan__Uncleared_Repayment_Amount__c > 0 and loan__Principal_paid__c > 0 ' +
                'and datafixupb__c = false and UPBunaffected__c = false and loan__Loan_Status__c in:status and loan__Last_Accrual_Date__c <:systemDate ';

               
    }
        
    global UPBreportbatch(Set<Id> lContract){
        status.add('Active - Good Standing');
        status.add('Active - Bad Standing');
        lacc = lContract;
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC){
    
    if(test.isRunningTest()){
        systemDate = System.today();
    }       

    if(query.length() == 0){
        query = 'Select id from loan__loan_account__c where loan__Uncleared_Repayment_Amount__c > 0 and loan__Principal_paid__c > 0 ' +
                'and datafixupb__c = false and UPBunaffected__c = false and id in:lacc and loan__Loan_Status__c in:status and loan__Last_Accrual_Date__c <:systemDate ';
    }

    System.debug('query ' + query);
    return Database.getQueryLocator(query);

    }
       
    global void execute(Database.BatchableContext BC, List<loan__loan_account__c> loanAccounts){
    
    System.debug('list is not null');
    
    List<loan__loan_Account__c> LAtobeUpdated =[select id,name,loan__Loan_Status__c,
                                                     datafixupb__c,
                                                     loan__Loan_Amount__c,
                                                     loan__Principal_Remaining__c,
                                                     loan__Uncleared_Repayment_Amount__c,
                                                     loan__Principal_Paid__c,
                                                     loan__Interest_Paid__c,
                                                     loan__Interest_Remaining__c,
                                                     (select id,name,createddate,
                                                      loan__Principal__c,
                                                      loan__interest__c 
                                                      from loan__Loan_Payment_Transactions__r 
                                                      where 
                                                      loan__Reversed__c=false and loan__Cleared__c=true and loan__Rejected__c=false)
                                                     from loan__Loan_Account__c where id in:loanAccounts];

        
        System.debug(logginglevel.error, ' LAtobeUpdated :: ' +LAtobeUpdated); 

        for(loan__loan_account__c contract : LAtobeUpdated){
            
            try{
                
                UPBreportPatch datafixreport = new UPBreportPatch(contract);
                datafixreport.Reportupbloan();

            }catch (Exception e) {
                
                batch.loan__Log_Level__c = 'ERROR';
                batch.loan__Message__c = ' Data fix Report Job failed for ::'+ contract.Name + '. :: ERROR :: '+e.getMessage() + ' :: StackTrace ::' +e.getStackTraceString() ;
                batch.loan__Batch_Id__c = 'UPBreportBatch';
                insert batch;
                
                System.debug(logginglevel.error,'line number'+e.getLineNumber());
                System.debug(logginglevel.error,'error stackTrace'+e.getStackTraceString());
                System.debug(logginglevel.error,'error message'+e.getMessage()); 
            
            }

        }
        //System.debug('count ' + LAtobeUpdated.size());
    }
    
    global void finish(Database.BatchableContext BC){
        System.debug('finish batch job');
    }
}