force-app/main/default/objects/Expiry_Date__c/Expiry_Date__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Expiry Date</label>
</CustomObject>

force-app/main/default/objects/Expiry_Date__c/fields/No_of_days_for_Expiration__c.field-meta.xml
<CustomField>
    <fullName>No_of_days_for_Expiration__c</fullName>
    <label>No. of days for Expiration</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/genesis__Applications__c/genesis__Applications__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{0000000000}</displayFormat>
        <label>Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/genesis__Applications__c/fields/Expiration_Date_for_Email_trigger__c.field-meta.xml
<CustomField>
    <fullName>Expiration_Date_for_Email_trigger__c</fullName>
    <description>/*Created By Nupur */</description>
    <label>Expiration Date for Email trigger</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/genesis__Applications__c/fields/Expiry_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiry_Date__c</fullName>
    <description>/*Created By Nupur */
------- For Email Alert</description>
    <formula>Application_Start_DateV2__c + $Setup.Expiry_Date__c.No_of_days_for_Expiration__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Expiry Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/ExpirationAlertEmail.cls
/* Created By Nupur ------
for Generating Expiry Date */
 public class ExpirationAlertEmail {
   public static void daysbeforeExpirationDate(){
        Expiry_Date__c numofdays = Expiry_Date__c.getInstance(); 
        
        list<genesis__Applications__c> applist = [select genesis__Applications__c.CreatedDate,Expiration_Date_for_Email_trigger__c from genesis__Applications__c];
        for(genesis__Applications__c app: applist){
 
            date createdDated = date.newInstance(app.CreatedDate.year(),app.CreatedDate.month(),app.CreatedDate.day());
            app.Expiration_Date_for_Email_trigger__c = createdDated.adddays((Integer)numofdays.No_of_days_for_Expiration__c);
        }  
        update applist;
        // return applist;
        
    }
    
    
}