force-app/main/default/objects/Lead/fields/lead_guid__c.field-meta.xml
<CustomField>
    <fullName>lead_guid__c</fullName>
    <externalId>true</externalId>
    <label>lead_guid</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead__c/Lead__c.object-meta.xml
<CustomObject>
    <label>Lead</label>
    <nameField>
        <label>Leads Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LEADS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead_Offer__c/Lead_Offer__c.object-meta.xml
<CustomObject>
    <label>Lead Offer</label>
    <nameField>
        <label>Lead Offer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lead Offers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead_Offer__c/fields/Key__c.field-meta.xml
<CustomField>
    <fullName>Key__c</fullName>
    <label>Key</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead_Offer__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Offers</relationshipLabel>
    <relationshipName>Lead_Offers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead_Offer__c/fields/Selected_Offer__c.field-meta.xml
<CustomField>
    <fullName>Selected_Offer__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Selected Offer</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/MW_WSSelectedLeadOffer.cls
@RestResource(urlMapping='/SelectedLeadOffer')
global with sharing class MW_WSSelectedLeadOffer {

	public class SelectedOffer {
		public String lead_guid;
		public Integer key;
	}

	//CLS-1188 Update Lead to Partner_pre_qual_shown
	public static void updateLeadStatus(String lead_guid){
		List<Lead> leadList = [Select id, lead_guid__c, status From Lead Where lead_guid__c =: lead_guid];
		if(leadList.size() > 0) {
			leadList[0].status = 'partner_pre_qual_shown';
			update leadList;
		}
	}

	@HttpPost
	global static String create() {
		RestRequest req = Restcontext.request;
		String jsonData = req.requestBody.toString();
		SelectedOffer leadObj = (SelectedOffer) JSON.deserialize(jsonData, SelectedOffer.class);
		try {
			List<Lead_Offer__c> leadOffersList = [SELECT id, Lead__c, Lead__r.status, Key__c, Selected_Offer__c FROM Lead_Offer__c WHERE Lead__r.lead_guid__c =: leadObj.lead_guid];
			Boolean foundLeadOffer = false;
			for(Lead_Offer__c leadOffer : leadOffersList) {
				if(leadOffer.key__c == leadObj.key) {
					leadOffer.Selected_Offer__c = true;
					foundLeadOffer = true;
				}
				else{
					leadOffer.Selected_Offer__c = false;
				}
			}
			if(foundLeadOffer) {
				update leadOffersList;
				updateLeadStatus(leadObj.lead_guid);
				return 'Success';
			}
			else{
				return 'Offer Not Found';
			}
		}
		catch(Exception e){
			MW_LogUtility.error('MW_WSSelectedLeadOffer', '', leadObj.lead_guid, 'create', e);
			System.debug('Error: ' + e.getLineNumber() + ' Desc. ' + e.getMessage()+' Stack: '+e.getStackTraceString());
			System.debug(logginglevel.error,'line number'+e.getLineNumber());
			System.debug(logginglevel.error,'error stackTrace'+e.getStackTraceString());
			return 'Error: ' + e.getLineNumber() + ' Desc. ' + e.getMessage()+' Stack: '+e.getStackTraceString();
		}
	}
}