unpackaged/main/default/objects/CL_Document__c/CL_Document__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>CL_Generated Documents Names</description>
    <label>CL Document</label>
</CustomObject>

unpackaged/main/default/objects/CL_Document__c/fields/UploadedBOX__c.field-meta.xml
<CustomField>
    <fullName>UploadedBOX__c</fullName>
    <label>UploadedBOX</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/loan__Automated_Payment_Configuration__c/loan__Automated_Payment_Configuration__c.object-meta.xml
<CustomObject>
    <customHelpPage>loan__AutomatedPaymentConfigurationHelp</customHelpPage>
    <label>Automated Payment Configuration</label>
    <nameField>
        <displayFormat>APC-{0000000000}</displayFormat>
        <label>Automated Payment Configuration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Automated Payment Configuration</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/loan__Automated_Payment_Configuration__c/fields/Box_Folder_ID__c.field-meta.xml
<CustomField>
    <fullName>Box_Folder_ID__c</fullName>
    <label>Box Folder ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/loan__Automated_Payment_Configuration__c/fields/loan__Active__c.field-meta.xml
<CustomField>
    <fullName>loan__Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/loan__Automated_Payment_Configuration__c/fields/loan__Folder_Name__c.field-meta.xml
<CustomField>
    <fullName>loan__Folder_Name__c</fullName>
    <inlineHelpText>Please create a folder with a name under the Documents tab. Then put the folder name here.</inlineHelpText>
    <label>Folder Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/loan__Batch_Process_Log__c/loan__Batch_Process_Log__c.object-meta.xml
<CustomObject>
    <label>Batch Process Log</label>
    <nameField>
        <label>Apex Batch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Batch Process Log</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/loan__Batch_Process_Log__c/fields/loan__Message__c.field-meta.xml
<CustomField>
    <fullName>loan__Message__c</fullName>
    <label>Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/loan__Batch_Process_Log__c/fields/loan__Origin__c.field-meta.xml
<CustomField>
    <fullName>loan__Origin__c</fullName>
    <label>Origin</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Start Of Day Process</fullName>
            </value>
            <value>
                <fullName>End of Day Process</fullName>
            </value>
            <value>
                <fullName>Month End Process</fullName>
            </value>
            <value>
                <fullName>Year End Process</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/loan__Batch_Process_Log__c/fields/loan__Time__c.field-meta.xml
<CustomField>
    <fullName>loan__Time__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <label>Time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/loan__Batch_Process_Log__c/fields/loan__Type__c.field-meta.xml
<CustomField>
    <fullName>loan__Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Exception</fullName>
            </value>
            <value>
                <fullName>Warning</fullName>
            </value>
            <value>
                <fullName>Info</fullName>
            </value>
            <value>
                <fullName>Result</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/AchDocsUploadToBoxjob.cls
global class AchDocsUploadToBoxjob implements Database.Batchable<sObject>,Database.AllowsCallouts {
   String query;
   public static HttpResponse resp = new HttpResponse();
   global CL_Document__c docs = CL_Document__c.getOrgDefaults();
   String uploadbox = docs.UploadedBOX__c; 
   global Database.QueryLocator start(Database.BatchableContext BC) {
        
        Set<String> foldersName = new Set<String>();
        List<loan__Automated_Payment_Configuration__c> listAPC = [
                SELECT Id,
                       Name,
                       Box_Folder_ID__c,
                       loan__Folder_Name__c
                FROM   loan__Automated_Payment_Configuration__c
                WHERE  Box_Folder_ID__c != NULL
                AND    loan__Active__c = TRUE
        ];
        System.debug('****listAPC****'+listAPC);
        if(!listAPC.IsEmpty()){                                                                     
            for(loan__Automated_Payment_Configuration__c APC : listAPC){
                    
                foldersName.add(APC.loan__Folder_Name__c);  
                
                }
        }
                                                                        
                                                                
        query = 'SELECT Id,Name,FolderId,Folder.Name,body FROM Document WHERE Folder.Name IN : foldersName AND Description !=: uploadbox';       
        System.debug('<< Initial Query >>' +query);
        return Database.getQueryLocator(query);
    }
    global void execute(Database.BatchableContext BC, List<Document> scope) {
       if(!scope.isEmpty()){ 
            list<Document> Documentlist = new list<Document>(scope);
             try{
                  loan__Automated_Payment_Configuration__c APC = [
                          SELECT Id,
                                 Name,
                                 Box_Folder_ID__c,
                                 loan__Folder_Name__c
                          FROM   loan__Automated_Payment_Configuration__c
                          WHERE  loan__Folder_Name__c = :Documentlist[0].Folder.Name
                          AND    loan__Active__c = TRUE
                          LIMIT  1
                  ];
               
              
                resp = BoX_Integ.uploadFileToBox(Documentlist[0].body,Documentlist[0].name,APC.Box_Folder_ID__c,null);
                
                System.debug('****rs****'+resp.getStatusCode());
                System.debug('****rsStatus*****'+resp.getStatus());
                if(resp.getStatusCode() == 201 && resp.getStatus() == 'Created'){
                    
                    Documentlist[0].Description = docs.UploadedBOX__c; 
                    Update Documentlist[0];
                    System.debug('***FileUploadedSuccessfully****');
                }
                if(resp.getStatusCode() == 401 && resp.getStatus() == 'Conflict')
                {
                    System.debug('The file with same name cannot be uploaded');
                }
              
             }
             catch(exception ex){
                  loan__Batch_Process_Log__c bplog = new loan__Batch_Process_Log__c();
                    bplog.loan__Origin__c = 'AchDocsUploadToBoxjob';
                    bplog.loan__Message__c = 'Error: ' + ex.getLineNumber() + ' Desc. ' + ex.getMessage()+' Stack: '+ex.getStackTraceString();
                    bplog.loan__Type__c = 'Exception';
                    bplog.loan__Time__c = DateTime.now();
                    insert bplog;
                 
             }
        }
            
    }
        
    /*global void execute(SchedulableContext ctx) {
        Id batchJobId = Database.executeBatch(new AchDocsUploadToBoxjob(), 40);
    }*/
    
    global void finish(Database.BatchableContext BC) {
        // update job's last run time in custom         
    }  
   
}