force-app/main/default/objects/Contact/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application_con</label>
    <referenceTo>genesis__Applications__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Credit_Policy__c/Credit_Policy__c.object-meta.xml
<CustomObject>
    <label>Credit Policy</label>
    <nameField>
        <label>Credit Policy Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Credit Policy</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Credit_Policy__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>genesis__Applications__c</referenceTo>
    <relationshipLabel>Credit Policy</relationshipLabel>
    <relationshipName>Credit_Policy</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DM_Contingency_Status_Code__c/DM_Contingency_Status_Code__c.object-meta.xml
<CustomObject>
    <label>DM Contingency Status Code</label>
    <nameField>
        <label>DM Contingency Status Code Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contingency Status Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DM_Contingency_Status_Code__c/fields/DM_Contingency_Status_Code__c.field-meta.xml
<CustomField>
    <fullName>DM_Contingency_Status_Code__c</fullName>
    <label>DM Contingency Status Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bankruptcy (B)</fullName>
            </value>
            <value>
                <fullName>Deceased (D)</fullName>
            </value>
            <value>
                <fullName>Fraudulent (F)</fullName>
            </value>
            <value>
                <fullName>Duplicate (K)</fullName>
            </value>
            <value>
                <fullName>No Communication (X)</fullName>
            </value>
            <value>
                <fullName>SCRA (S)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DM_Disbursal_Transaction_Distribution__c/DM_Disbursal_Transaction_Distribution__c.object-meta.xml
<CustomObject>
    <label>DM Disbursal Transaction Distribution</label>
    <nameField>
        <label>DM Disbursal Transaction Distribution Na</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DM Disbursal Transaction Distributions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DM_Disbursal_Transaction_Distribution__c/fields/DM_Loan_Disbursal_Transaction__c.field-meta.xml
<CustomField>
    <fullName>DM_Loan_Disbursal_Transaction__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>DM Loan Disbursal Transaction</label>
    <referenceTo>DM_Loan_Disbursal_Transaction__c</referenceTo>
    <relationshipLabel>DM Disbursal Transaction Distributions</relationshipLabel>
    <relationshipName>DM_Disbursal_Transaction_Distributions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DM_Due_Payment__c/DM_Due_Payment__c.object-meta.xml
<CustomObject>
    <label>DM Due Payment</label>
    <nameField>
        <label>DM Due Payment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DM Due Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DM_Due_Payment__c/fields/DM_Loan_Payment_Transaction__c.field-meta.xml
<CustomField>
    <fullName>DM_Loan_Payment_Transaction__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>DM Loan Payment Transaction</label>
    <referenceTo>DM_Loan_Payment_Transaction__c</referenceTo>
    <relationshipLabel>DM Due Payments</relationshipLabel>
    <relationshipName>DM_Due_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DM_Investment_Order__c/DM_Investment_Order__c.object-meta.xml
<CustomObject>
    <label>DM Investment Order</label>
    <nameField>
        <label>Investment Order	 Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DM Investment Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DM_Investment_Order__c/fields/DM_Account__c.field-meta.xml
<CustomField>
    <fullName>DM_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>DM Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Investment Orders</relationshipLabel>
    <relationshipName>Investment_Orders1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DM_Loan_Account__c/DM_Loan_Account__c.object-meta.xml
<CustomObject>
    <label>DM CL Contract</label>
    <nameField>
        <label>DM Loan Con Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DM CL Contract</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DM_Loan_Account__c/fields/DM_Account__c.field-meta.xml
<CustomField>
    <fullName>DM_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Please choose a account, which will be associated as a customer on this lending account.
You can create a new account, from the lookup window by clicking on new or select the existing account from the lookup.</inlineHelpText>
    <label>DM Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Loan_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DM_Loan_Account__c/fields/DM_Application__c.field-meta.xml
<CustomField>
    <fullName>DM_Application__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>DM Application</label>
    <referenceTo>genesis__Applications__c</referenceTo>
    <relationshipLabel>DM CL Contract</relationshipLabel>
    <relationshipName>DM_CL_Contract</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DM_Loan_Account__c/fields/DM_Contingency_Status_Code__c.field-meta.xml
<CustomField>
    <fullName>DM_Contingency_Status_Code__c</fullName>
    <description>Field Stores contingency status of a contract.</description>
    <inlineHelpText>Field Stores contingency status of a contract.</inlineHelpText>
    <label>DM Contingency Status Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>DM_Bankruptcy (B)</fullName>
            </value>
            <value>
                <fullName>DM_Deceased (D)</fullName>
            </value>
            <value>
                <fullName>DM_Fraudulent (F)</fullName>
            </value>
            <value>
                <fullName>DM_Duplicate (K)</fullName>
            </value>
            <value>
                <fullName>DM_No Communication (X)</fullName>
            </value>
            <value>
                <fullName>DM_Suspend Disbursal (Z)</fullName>
            </value>
            <value>
                <fullName>DM_Normal (N)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DM_Loan_Account__c/fields/DM_Loan_Account_External_Id__c.field-meta.xml
<CustomField>
    <fullName>DM_Loan_Account_External_Id__c</fullName>
    <externalId>true</externalId>
    <label>DM Loan Account External Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/DM_Loan_Payment_Transaction__c/DM_Loan_Payment_Transaction__c.object-meta.xml
<CustomObject>
    <label>DM Loan Payment Transaction</label>
    <nameField>
        <label>DM  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DM Loan Payment Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DM_Loan_Payment_Transaction__c/fields/DM_Automated_Payment_Setup__c.field-meta.xml
<CustomField>
    <fullName>DM_Automated_Payment_Setup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>DM Automated Payment Setup</label>
    <referenceTo>DM_Automated_Payment_Setup__c</referenceTo>
    <relationshipLabel>DM Loan Payment Transactions</relationshipLabel>
    <relationshipName>DM_Loan_Payment_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DM_Repayment_Plan__c/DM_Repayment_Plan__c.object-meta.xml
<CustomObject>
    <label>DM Repayment Plan</label>
    <nameField>
        <label>DM Repayment Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DM Repayment Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DM_Repayment_Plan__c/fields/DM_Application__c.field-meta.xml
<CustomField>
    <fullName>DM_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>DM Application</label>
    <referenceTo>genesis__Applications__c</referenceTo>
    <relationshipLabel>DM Repayment Plans</relationshipLabel>
    <relationshipName>DM_Repayment_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DM_Repayment_Schedule_Summary__c/DM_Repayment_Schedule_Summary__c.object-meta.xml
<CustomObject>
    <label>DM Repayment Schedule</label>
    <nameField>
        <label>DM Amortization Schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DM Repayment Schedule</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DM_Repayment_Schedule_Summary__c/fields/DM_CL_Contract__c.field-meta.xml
<CustomField>
    <fullName>DM_CL_Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>DM CL Contract</label>
    <referenceTo>DM_Loan_Account__c</referenceTo>
    <relationshipLabel>DM Repayment Schedule</relationshipLabel>
    <relationshipName>DM_Repayment_Schedule_Summarys</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DM_Repayment_Schedule_Summary__c/fields/DM_Loan_Disbursal_Transaction__c.field-meta.xml
<CustomField>
    <fullName>DM_Loan_Disbursal_Transaction__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Repayment Schedule Record of which LDT</description>
    <inlineHelpText>This field is used only in case of FIT (Fund in Tranches) Loans. Every disbursal re-generates repayment schedule, this field keeps track of parent disbursal due to which record is created.</inlineHelpText>
    <label>DM Loan Disbursal Transaction</label>
    <referenceTo>DM_Loan_Disbursal_Transaction__c</referenceTo>
    <relationshipName>DM_Loan_Disbursal_Transaction</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/loan__Loan_Account__c.object-meta.xml
<CustomObject>
    <description>Lending Account</description>
    <label>CL Contract</label>
    <nameField>
        <displayFormat>LAI-{00000000}</displayFormat>
        <label>CL Contract ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CL Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/loan__Loan_Account__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>genesis__Applications__c</referenceTo>
    <relationshipLabel>CL Contracts</relationshipLabel>
    <relationshipName>CL_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MigrationPhase__c/MigrationPhase__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>MigrationPhase</label>
</CustomObject>

force-app/main/default/objects/MigrationPhase__c/fields/phase__c.field-meta.xml
<CustomField>
    <fullName>phase__c</fullName>
    <label>phase</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DM_DataCleanUp_Staging.cls
Global class DM_DataCleanUp_Staging implements Database.Batchable<sObject> {
    
    String query;
    String status = 'Failed';
    public Integer thread = 0;
    List<MigrationPhase__c> migrationPhase = MigrationPhase__c.getAll().values();
    String phase = migrationPhase[0].phase__c;
    String id = '';
    List<DM_Repayment_Schedule_Summary__c> rss = new List<DM_Repayment_Schedule_Summary__c>();
    List<DM_Automated_Payment_Setup__c> aps = new List<DM_Automated_Payment_Setup__c>();
    List<DM_Investment_Order__c> io = new List<DM_Investment_Order__c>();
    List<DM_Repayment_Plan__c> rep = new List<DM_Repayment_Plan__c>();
    List<DM_Loan_Disbursal_Transaction__c> ldt = new List<DM_Loan_Disbursal_Transaction__c>();
    List<DM_Loan_Payment_Transaction__c> lpt = new List<DM_Loan_Payment_Transaction__c>();
    List<DM_Repayment_Schedule__c> amz = new List<DM_Repayment_Schedule__c>();
    List<DM_Contingency_Status_Code__c> contingency = new List<DM_Contingency_Status_Code__c>();
    List<id> app = new List<id>();
    List<id> acc = new List<id>();
    List<dm_Loan_Account__c> LoansToBeDeleted = new List<dm_Loan_Account__c>();
    List<Account> accDel = new List<Account>();
    List<String> extId = new List<String>();
    
    global DM_DataCleanUp_Staging(Integer threadNumber){
   			thread = threadNumber;
    } 
    
    global DM_DataCleanUp_Staging(){
        
    } 
        
    global Database.QueryLocator start(Database.BatchableContext BC){      
        
        query  = 'Select id,DM_Application__c,DM_Account__c,DM_Loan_Account_External_Id__c, '+
                        '(Select id from DM_Repayment_Schedule_Summarys__r ), '+
                        '(Select id from DM_Automated_Payment_Setups__r ), '+
                        '(Select id from DM_Investment_Orders__r ), '+ 
                        '(Select id from DM_Repayment_Plans__r ), '+ 
                        '(Select id from DM_Loan_Disbursal_Transactions__r ), '+
                        '(Select id from DM_Loan_Payment_Transactions__r ), '+
                        '(Select id from DM_Repayment_Schedules__r ),'+
            			'(Select id from Contingency_Status_Codes__r ) ' + 	
                        'from dm_Loan_Account__c where '+
                        'Migrated_CL_Contract__c = \'' + id + '\'' ; 	
        if(thread != 0)
           query = query + ' and dm_Thread_Number__c = ' + thread; 
                        
        System.debug(query);
        return Database.getQueryLocator(query);
    }
     global void execute(Database.BatchableContext BC,List<Sobject> scope){
        
        LoansToBeDeleted = (List<dm_Loan_Account__c>)scope;

        System.debug('LoansToBeDeleted ' + LoansToBeDeleted);
        
            for(dm_Loan_Account__c loan : LoansToBeDeleted){
                rep.addall(loan.DM_Repayment_Plans__r);
                amz.addall(loan.DM_Repayment_Schedules__r);
                io.addall(loan.DM_Investment_Orders__r);
                rss.addall(loan.DM_Repayment_Schedule_Summarys__r);
                APS.addall(loan.DM_Automated_Payment_Setups__r);
                LPT.addall(loan.DM_Loan_Payment_Transactions__r);
                LDT.addall(loan.DM_Loan_Disbursal_Transactions__r);
                app.add(loan.DM_Application__c);
                acc.add(loan.DM_Account__c);
                contingency.addall(loan.Contingency_Status_Codes__r);
                extId.add('BA-'+loan.DM_Loan_Account_External_Id__c);
            }
                     	        
         	
            Delete rep ;
            Delete amz ;
            Delete io ;
            delete aps;
            delete rss;
            delete contingency;
         
            List<DM_Due_Payment__c> DMdue = [select id from DM_Due_Payment__c where DM_Loan_Payment_Transaction__c in: LPT];
            delete DMdue;
            delete LPT;
         
            List<DM_Disbursal_Transaction_Distribution__c> DMDDT = [select id from DM_Disbursal_Transaction_Distribution__c where DM_Loan_Disbursal_Transaction__c in: LDT];

            delete DMDDT;
            delete LDT;
         
            List<Credit_Policy__c> creditPolicy = [select id from Credit_Policy__c where Application__c in: app];
            delete creditPolicy;
            
            List<genesis__applications__C> appDel = [select id from genesis__applications__C where Id in: app];
         	
         	List<loan__loan_account__c> loan = [select id from loan__loan_account__c where loan__Account__c in: acc limit 1];
         
         	
           List<loan__Bank_Account__c> bankAccount = [select id from loan__Bank_Account__c where loan__Account__c in: acc
                                                     and Bank_Account_External_Id__c in: extId];
           delete bankAccount;
         	
         	if(loan.size() == 0){
                /*List<Contact> con = [select id from Contact where accountId in: acc];
                delete con;*/	// gets automatically deleted
               
                accDel = [select id from Account where Id in: acc];
            }    
            
            Delete LoansToBeDeleted;
            delete appDel;
           try{
            if(accDel.size()>0)
            	delete accDel;
           }    
           catch(Exception e){
              System.debug('account connected with app');
           }  
         
     }
     global void finish(Database.BatchableContext BC){
                
        system.debug('Finish Batch Job');
        
    }
    
}