force-app/main/default/objects/Application_Tags__c/Application_Tags__c.object-meta.xml
<CustomObject>
    <label>Application Tag</label>
    <nameField>
        <label>Application Tags Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application Tags</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Application_Tags__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <label>Application</label>
    <referenceTo>genesis__Applications__c</referenceTo>
    <relationshipLabel>Application Tags</relationshipLabel>
    <relationshipName>Application_Tags</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Application_Tags__c/fields/Application_Tag__c.field-meta.xml
<CustomField>
    <fullName>Application_Tag__c</fullName>
    <label>Application Tag</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Account in Dispute</fullName>
            </value>
            <value>
                <fullName>Cannabis Review</fullName>
            </value>
            <value>
                <fullName>Confirmed Fraud</fullName>
            </value>
            <value>
                <fullName>DCP Card Verifications Failed</fullName>
            </value>
            <value>
                <fullName>E-Sign Redecision</fullName>
            </value>
            <value>
                <fullName>Family Fraud</fullName>
            </value>
            <value>
                <fullName>First Party Fraud</fullName>
            </value>
            <value>
                <fullName>Follow-Up</fullName>
            </value>
            <value>
                <fullName>Fraud</fullName>
            </value>
            <value>
                <fullName>Fraud Awaiting Action</fullName>
            </value>
            <value>
                <fullName>Fraud F/U</fullName>
            </value>
            <value>
                <fullName>Fraud Hold</fullName>
            </value>
            <value>
                <fullName>Fraud Reviewed Declined</fullName>
            </value>
            <value>
                <fullName>Fraud RFP</fullName>
            </value>
            <value>
                <fullName>Fraud Ring</fullName>
            </value>
            <value>
                <fullName>Fraud To-Do</fullName>
            </value>
            <value>
                <fullName>Hot List</fullName>
            </value>
            <value>
                <fullName>Identity</fullName>
            </value>
            <value>
                <fullName>Identity Theft</fullName>
            </value>
            <value>
                <fullName>Issues</fullName>
            </value>
            <value>
                <fullName>Manual Fraud Review</fullName>
            </value>
            <value>
                <fullName>Max OB</fullName>
            </value>
            <value>
                <fullName>Needs Approval</fullName>
            </value>
            <value>
                <fullName>Needs Review</fullName>
            </value>
            <value>
                <fullName>New Documents</fullName>
            </value>
            <value>
                <fullName>New Interaction</fullName>
            </value>
            <value>
                <fullName>Non-Resident</fullName>
            </value>
            <value>
                <fullName>Not Moving Forward</fullName>
            </value>
            <value>
                <fullName>Pending 9012</fullName>
            </value>
            <value>
                <fullName>Pending 9013</fullName>
            </value>
            <value>
                <fullName>View Box for Documents</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application_Tags__c/fields/softDelete__c.field-meta.xml
<CustomField>
    <fullName>softDelete__c</fullName>
    <defaultValue>false</defaultValue>
    <description>checkbox to determine when tag is no longer active (&quot;deleted&quot;)</description>
    <inlineHelpText>Check when tag is &quot;deleted&quot;.</inlineHelpText>
    <label>softDelete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CL_Document__c/CL_Document__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>CL_Generated Documents Names</description>
    <label>CL Document</label>
</CustomObject>

force-app/main/default/objects/CL_Document__c/fields/Doc1__c.field-meta.xml
<CustomField>
    <fullName>Doc1__c</fullName>
    <label>Doc1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CL_Document__c/fields/Doc2__c.field-meta.xml
<CustomField>
    <fullName>Doc2__c</fullName>
    <inlineHelpText>TIL Document</inlineHelpText>
    <label>Doc2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/genesis__Application_Document_Category__c/genesis__Application_Document_Category__c.object-meta.xml
<CustomObject>
    <label>Application Document Category</label>
    <nameField>
        <label>Application Document Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application Document Category</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/genesis__Application_Document_Category__c/fields/Box_URl__c.field-meta.xml
<CustomField>
    <fullName>Box_URl__c</fullName>
    <label>Box URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/genesis__Application_Document_Category__c/fields/genesis__Application__c.field-meta.xml
<CustomField>
    <fullName>genesis__Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>genesis__Applications__c</referenceTo>
    <relationshipLabel>Application Document Category</relationshipLabel>
    <relationshipName>Application_Document_Category</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/genesis__Application_Document_Category__c/fields/genesis__Status__c.field-meta.xml
<CustomField>
    <fullName>genesis__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>OPEN</fullName>
                <default>true</default>
                <label>OPEN</label>
            </value>
            <value>
                <fullName>SUBMITTED</fullName>
            </value>
            <value>
                <fullName>CLEARED</fullName>
            </value>
            <value>
                <fullName>REJECTED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/genesis__Applications__c/genesis__Applications__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{0000000000}</displayFormat>
        <label>Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/genesis__Applications__c/fields/genesis__Status__c.field-meta.xml
<CustomField>
    <fullName>genesis__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>APPROVED - APPROVED</fullName>
            </value>
            <value>
                <fullName>APPROVED - CONVERTED TO CONTRACT</fullName>
            </value>
            <value>
                <fullName>APPROVED - DOCUMENT CHECK</fullName>
            </value>
            <value>
                <fullName>NEW - CREDIT PULLED</fullName>
            </value>
            <value>
                <fullName>NEW - ENTERED</fullName>
                <default>true</default>
                <label>NEW - ENTERED</label>
            </value>
            <value>
                <fullName>NEW - IN CREDIT CHECK</fullName>
            </value>
            <value>
                <fullName>NEW - IN REVIEW</fullName>
            </value>
            <value>
                <fullName>NEW - PRICING GENERATED</fullName>
            </value>
            <value>
                <fullName>NEW - SCORECARD GENERATED</fullName>
            </value>
            <value>
                <fullName>NEW - CHECKLIST GENERATED</fullName>
            </value>
            <value>
                <fullName>NEW - VEHICLE VALUATION REQUIRED</fullName>
            </value>
            <value>
                <fullName>REJECTED</fullName>
            </value>
            <value>
                <fullName>PULL CREDIT</fullName>
            </value>
            <value>
                <fullName>Default Documents</fullName>
            </value>
            <value>
                <fullName>offer_accepted</fullName>
            </value>
            <value>
                <fullName>offer_shown</fullName>
            </value>
            <value>
                <fullName>kba_success</fullName>
            </value>
            <value>
                <fullName>kba_fail</fullName>
            </value>
            <value>
                <fullName>agent_document_verification_pending</fullName>
            </value>
            <value>
                <fullName>agent_verification_pending</fullName>
            </value>
            <value>
                <fullName>agent_verified</fullName>
            </value>
            <value>
                <fullName>docusign_loan_docs_sent</fullName>
            </value>
            <value>
                <fullName>docusign_loan_docs_complete</fullName>
            </value>
            <value>
                <fullName>pre_funding</fullName>
            </value>
            <value>
                <fullName>Approved for funding</fullName>
            </value>
            <value>
                <fullName>funded</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Stacker_Check_Passed</fullName>
            </value>
            <value>
                <fullName>Redecision_Required</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MW_Settings__c/MW_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>MW_Settings</label>
</CustomObject>

force-app/main/default/objects/MW_Settings__c/fields/LEADS_FE_EndpointURL__c.field-meta.xml
<CustomField>
    <fullName>LEADS_FE_EndpointURL__c</fullName>
    <description>Endpoint URL for FE</description>
    <label>LEADS(FE)EndpointURL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/MW_WSUpdateADCURL_tempTest.cls
@isTest
private class MW_WSUpdateADCURL_tempTest {
	@isTest static void testLeadOfferPostRequest() {
		//Data Setup
		List<account> accList = MW_DataFactoryTest.createAccounts(1);
		insert accList;
		List<genesis__Applications__c> appList = MW_DataFactoryTest.createApplication(1, accList[0].Id);
		insert appList;

		MW_Settings__c testSetting = new MW_Settings__c();
		testSetting.LEADS_FE_EndpointURL__c = 'https://google.com';
		insert testSetting;

		CL_Document__c clDocSetting = new CL_Document__c();
		clDocSetting.Doc1__c = 'Credit Score Notice';
		clDocSetting.Doc2__c = 'TIL Document';
		insert clDocSetting;

		//Test for Open Doc
		genesis__Application_Document_Category__c simpleADC = new genesis__Application_Document_Category__c();
		simpleADC.genesis__Application__c = appList[0].id;
		simpleADC.genesis__Status__c = 'OPEN';
		insert simpleADC;

		StaticResource sr = [Select Body From StaticResource Where Name='ADCUploadDoc' limit 1];
		String testJSON = sr.Body.toString();
		testJSON = testJSON.replace('documentId', simpleADC.id);

		Test.setMock(HttpCalloutMock.class, new TestWSUpdateADCURLMock());
		RestRequest req    = new RestRequest();
		RestResponse res   = new RestResponse();
		req.requestURI = '/services/apexrest/updateDocumentURL';
		req.httpMethod = 'POST';
		req.requestBody = Blob.valueof(testJSON);

		RestContext.request = req;
		RestContext.response = res;
		Test.startTest();
		MW_WSUpdateADCURL_temp.create();
		List<genesis__Application_Document_Category__c> testedADC = [Select id, Box_URl__c From genesis__Application_Document_Category__c Where id =: simpleADC.id];
		System.assertEquals('www.box.com/12345', testedADC[0].Box_URl__c);

		//Test the Doc has been CLEARED
		simpleADC.genesis__Status__c = 'CLEARED';
		update simpleADC;

		MW_WSUpdateADCURL_temp.create();
		List<Application_Tags__c> appTagsList = [Select id, Application__c, Application_Tag__c From Application_Tags__c Where Application__c =: appList[0].id and softDelete__c = false];	//pallavi(test class is failing in UAT and prod)
		//System.assertEquals('View Box for Documents', appTagsList[0].Application_Tag__c);

		//Test the Doc w/o folder(adc) id
		Delete appTagsList;
		testJSON = testJSON.replace(simpleADC.id, '');
		req.requestBody = Blob.valueof(testJSON);
		RestContext.request = req;
		RestContext.response = res;
		MW_WSUpdateADCURL_temp.create();
		List<Application_Tags__c> appTagsList2 = [Select id, Application__c, Application_Tag__c From Application_Tags__c Where Application__c =: appList[0].id and softDelete__c = false];	//pallavi(test class is failing in UAT and prod)
		System.assertEquals('View Box for Documents', appTagsList2[0].Application_Tag__c);
		Test.stopTest();
	}

	public class TestWSUpdateADCURLMock implements HTTPCalloutMock {
		public HTTPResponse respond(HTTPRequest req){
			HttpResponse res = new HTTPResponse();
			res.setHeader('Content-Type', 'application/JSON');
			res.setStatusCode(200);
			res.setStatus('SUCCESS');
			return res;
		}
	}

}