force-app/main/default/objects/genesis__AppDocCatAttachmentJunction__c/genesis__AppDocCatAttachmentJunction__c.object-meta.xml
<CustomObject>
    <label>AppDocCatAttachmentJunction</label>
    <nameField>
        <displayFormat>ADCA-{00000000}</displayFormat>
        <label>AppDocCatAttachmentJunction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AppDocCatAttachmentJunctions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/genesis__AppDocCatAttachmentJunction__c/fields/genesis__Application_Document_Category__c.field-meta.xml
<CustomField>
    <fullName>genesis__Application_Document_Category__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application Document Category</label>
    <referenceTo>genesis__Application_Document_Category__c</referenceTo>
    <relationshipLabel>AppDocCatAttachmentJunctions</relationshipLabel>
    <relationshipName>AppDocCatAttachmentJunctions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/genesis__AppDocCatAttachmentJunction__c/fields/genesis__AttachmentId__c.field-meta.xml
<CustomField>
    <fullName>genesis__AttachmentId__c</fullName>
    <label>AttachmentId</label>
    <length>21</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/genesis__Application_Document_Category__c/genesis__Application_Document_Category__c.object-meta.xml
<CustomObject>
    <label>Application Document Category</label>
    <nameField>
        <label>Application Document Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application Document Category</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/genesis__Application_Document_Category__c/fields/genesis__Application__c.field-meta.xml
<CustomField>
    <fullName>genesis__Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>genesis__Applications__c</referenceTo>
    <relationshipLabel>Application Document Category</relationshipLabel>
    <relationshipName>Application_Document_Category</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/loan__Batch_Process_Log__c/loan__Batch_Process_Log__c.object-meta.xml
<CustomObject>
    <label>Batch Process Log</label>
    <nameField>
        <label>Apex Batch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Batch Process Log</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/loan__Batch_Process_Log__c/fields/loan__Message__c.field-meta.xml
<CustomField>
    <fullName>loan__Message__c</fullName>
    <label>Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/loan__Batch_Process_Log__c/fields/loan__Origin__c.field-meta.xml
<CustomField>
    <fullName>loan__Origin__c</fullName>
    <label>Origin</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Start Of Day Process</fullName>
            </value>
            <value>
                <fullName>End of Day Process</fullName>
            </value>
            <value>
                <fullName>Month End Process</fullName>
            </value>
            <value>
                <fullName>Year End Process</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/loan__Batch_Process_Log__c/fields/loan__Time__c.field-meta.xml
<CustomField>
    <fullName>loan__Time__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <label>Time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/loan__Batch_Process_Log__c/fields/loan__Type__c.field-meta.xml
<CustomField>
    <fullName>loan__Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Exception</fullName>
            </value>
            <value>
                <fullName>Warning</fullName>
            </value>
            <value>
                <fullName>Info</fullName>
            </value>
            <value>
                <fullName>Result</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DocumentAttachmentTriggerHandler.cls
/**
* Description: Document Category related logic.
*
*   Modification Log :
---------------------------------------------------------------------------
Developer               Date                Description
---------------------------------------------------------------------------
Mohseen Begum           07/04/2017          Created
******************************************************************************************/
public class DocumentAttachmentTriggerHandler {
    
    public static boolean isTrgExecuting=false;
    
    /**
* Constructor to initialize
*
* @param isExecuting    Has value of which context it is executing.
*/
    public DocumentAttachmentTriggerHandler(boolean isExecuting){
        isTrgExecuting = isExecuting;
    }
    
    
    /**
* Description: Below method is used to create document category
*
* @param attDetails     Attachment records.
* 
*/
    public static void createDocumentCategory(dsfs__DocuSign_Status__c dsStatus){
        System.debug('.... createDocumentCategory ....' );
                     
        try{            
            if(dsStatus != null && dsStatus.dsfs__Envelope_Status__c == 'Completed'){  
                
                system.debug('status....'+dsStatus.dsfs__Envelope_Status__c + 'ParentId' + dsStatus.Id);
                CreateAppDocCategory(dsStatus.dsfs__Envelope_Status__c);
            }                         
        }catch (Exception ex){
            loan__Batch_Process_Log__c bplog = new loan__Batch_Process_Log__c(loan__Origin__c = 'Promissory Note' ,loan__Message__c = 'Error: ' + ex.getLineNumber() + ' Desc. ' + ex.getMessage()+' Stack: '+ex.getStackTraceString(),loan__Type__c = 'Exception',loan__Time__c = DateTime.now());
            
            insert bplog;
            
            throw ex;
        }
    }
        
    @future
        public static void createAppDocCategory(String dsStatus){
            
            List<genesis__Application_Document_Category__c> lstAppDocCat;
            genesis__AppDocCatAttachmentJunction__c lstAppDocCatAttachment; 
            
            list<attachment> attachmentLst = [select Id, Name from attachment where ParentId = :dsStatus and
                                               IsDeleted = False];
                    
            if(! attachmentLst.isEmpty()){
                if(attachmentLst[0].Name.contains('Promissory')){
                    //exOrigin = 'Promissory';                   
                    system.debug('Prommissory Document');
                    //System.debug('.... Attachment Name ' + attachmentLst[0].Name + '..' + attachmentLst[0].Id +'parentId:' +
                     //            attachmentLst[0].ParentId );
                    
                    lstAppDocCatAttachment = new genesis__AppDocCatAttachmentJunction__c();   
                    Id appId = getApplicationId(attachmentLst[0].Name);
                    system.debug('********appId*****'+appId);
                    lstAppDocCat = [Select Id from genesis__Application_Document_Category__c where genesis__Application__c =: appId 
                                    and Name = 'Promissory Note' and IsDeleted = false];
                    System.debug('hello' +lstAppDocCat + ' ,  ' +appId );
                    if(! lstAppDocCat.isEmpty()){
                        System.debug('.... Attachment Name ' +  '..' + attachmentLst[0].Id );
                        system.debug('... ApplicationDocCategory Id' + lstAppDocCat[0].Id);  
                        lstAppDocCatAttachment.genesis__Application_Document_Category__c = lstAppDocCat[0].Id;
                        lstAppDocCatAttachment.genesis__AttachmentId__c = attachmentLst[0].Id;                             
                        Insert lstAppDocCatAttachment; 
                    }
                }                  
            }
        }  

    /**
* Description: Below method is used to get attachmnet record ID from attachment name.
*
* @param attName     Attachment record name.
* 
*/
    public static Id getApplicationId(string attName){        
        string strAppId = attName.substringBefore('.');
        Id appId = strAppId.substring(strAppId.length()-15, strAppId.length());
        system.debug('... Application Id ' + appId);
        return appId;
    }
}