force-app/main/default/objects/genesis__AppDocCatAttachmentJunction__c/genesis__AppDocCatAttachmentJunction__c.object-meta.xml
<CustomObject>
    <label>AppDocCatAttachmentJunction</label>
    <nameField>
        <displayFormat>ADCA-{00000000}</displayFormat>
        <label>AppDocCatAttachmentJunction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AppDocCatAttachmentJunctions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/genesis__AppDocCatAttachmentJunction__c/fields/genesis__AttachmentId__c.field-meta.xml
<CustomField>
    <fullName>genesis__AttachmentId__c</fullName>
    <label>AttachmentId</label>
    <length>21</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/loan__Batch_Process_Log__c/loan__Batch_Process_Log__c.object-meta.xml
<CustomObject>
    <label>Batch Process Log</label>
    <nameField>
        <label>Apex Batch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Batch Process Log</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/loan__Batch_Process_Log__c/fields/loan__Message__c.field-meta.xml
<CustomField>
    <fullName>loan__Message__c</fullName>
    <label>Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/loan__Batch_Process_Log__c/fields/loan__Origin__c.field-meta.xml
<CustomField>
    <fullName>loan__Origin__c</fullName>
    <label>Origin</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Start Of Day Process</fullName>
            </value>
            <value>
                <fullName>End of Day Process</fullName>
            </value>
            <value>
                <fullName>Month End Process</fullName>
            </value>
            <value>
                <fullName>Year End Process</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/loan__Batch_Process_Log__c/fields/loan__Time__c.field-meta.xml
<CustomField>
    <fullName>loan__Time__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <label>Time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/loan__Batch_Process_Log__c/fields/loan__Type__c.field-meta.xml
<CustomField>
    <fullName>loan__Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Exception</fullName>
            </value>
            <value>
                <fullName>Warning</fullName>
            </value>
            <value>
                <fullName>Info</fullName>
            </value>
            <value>
                <fullName>Result</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DeleteAppDocJunAttachments.cls
Public with Sharing class DeleteAppDocJunAttachments{
    Public static void delAttachments(Set<Id> attmtId){
        System.debug('delAttachments... isDeleted=false');
        List<genesis__AppDocCatAttachmentJunction__c> delAttLst = new List<genesis__AppDocCatAttachmentJunction__c>();
        List<genesis__AppDocCatAttachmentJunction__c> lstAppDocCatAttachment = [Select Id, isDeleted from           genesis__AppDocCatAttachmentJunction__c where 
                    genesis__AttachmentId__c IN :attmtId and isDeleted = false];
        for(genesis__AppDocCatAttachmentJunction__c attCategory : lstAppDocCatAttachment){
                //attCategory.isDeleted = true;
                System.debug('delAttachments... Id: '+attCategory.Id);
                delAttLst.add(attCategory);
        }
        try{	//LOS-38
        if(delAttLst != null)
            delete(delAttLst);	
        }
        catch (DMLException ex){	//LOS-38
            loan__Batch_Process_Log__c bplog = new loan__Batch_Process_Log__c();
            bplog.loan__Origin__c = 'DeleteAppDocJunAttachments - delAttachments';
            bplog.loan__Message__c = 'Error: ' + ex.getLineNumber() + ' Desc. ' + ex.getMessage()+' Stack: '+ex.getStackTraceString();
            bplog.loan__Type__c = 'Exception';
            bplog.loan__Time__c = DateTime.now();
            insert bplog;
            Database.delete(delAttLst, false);	//LOS-38
        }
    }
}