force-app/main/default/objects/genesis__AppDocCatAttachmentJunction__c/genesis__AppDocCatAttachmentJunction__c.object-meta.xml
<CustomObject>
    <label>AppDocCatAttachmentJunction</label>
    <nameField>
        <displayFormat>ADCA-{00000000}</displayFormat>
        <label>AppDocCatAttachmentJunction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AppDocCatAttachmentJunctions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/genesis__AppDocCatAttachmentJunction__c/fields/genesis__Application_Document_Category__c.field-meta.xml
<CustomField>
    <fullName>genesis__Application_Document_Category__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application Document Category</label>
    <referenceTo>genesis__Application_Document_Category__c</referenceTo>
    <relationshipLabel>AppDocCatAttachmentJunctions</relationshipLabel>
    <relationshipName>AppDocCatAttachmentJunctions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/genesis__AppDocCatAttachmentJunction__c/fields/genesis__AttachmentId__c.field-meta.xml
<CustomField>
    <fullName>genesis__AttachmentId__c</fullName>
    <label>AttachmentId</label>
    <length>21</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/genesis__Application_Document_Category__c/genesis__Application_Document_Category__c.object-meta.xml
<CustomObject>
    <label>Application Document Category</label>
    <nameField>
        <label>Application Document Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application Document Category</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/genesis__Application_Document_Category__c/fields/genesis__Application__c.field-meta.xml
<CustomField>
    <fullName>genesis__Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>genesis__Applications__c</referenceTo>
    <relationshipLabel>Application Document Category</relationshipLabel>
    <relationshipName>Application_Document_Category</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/loan__Batch_Process_Log__c/loan__Batch_Process_Log__c.object-meta.xml
<CustomObject>
    <label>Batch Process Log</label>
    <nameField>
        <label>Apex Batch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Batch Process Log</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/loan__Batch_Process_Log__c/fields/loan__Message__c.field-meta.xml
<CustomField>
    <fullName>loan__Message__c</fullName>
    <label>Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/loan__Batch_Process_Log__c/fields/loan__Origin__c.field-meta.xml
<CustomField>
    <fullName>loan__Origin__c</fullName>
    <label>Origin</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Start Of Day Process</fullName>
            </value>
            <value>
                <fullName>End of Day Process</fullName>
            </value>
            <value>
                <fullName>Month End Process</fullName>
            </value>
            <value>
                <fullName>Year End Process</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/loan__Batch_Process_Log__c/fields/loan__Time__c.field-meta.xml
<CustomField>
    <fullName>loan__Time__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <label>Time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/loan__Batch_Process_Log__c/fields/loan__Type__c.field-meta.xml
<CustomField>
    <fullName>loan__Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Exception</fullName>
            </value>
            <value>
                <fullName>Warning</fullName>
            </value>
            <value>
                <fullName>Info</fullName>
            </value>
            <value>
                <fullName>Result</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/GenerateAppDocCategory.cls
public class GenerateAppDocCategory {
	public static void createDocumentCategory(Id lstDocuSignStatusId){
        
        dsfs__DocuSign_Envelope__c lstDocuSignEnv;
        genesis__Application_Document_Category__c lstAppDocCat;
        Attachment lstAttachments;        
        
        try{            
            if(lstDocuSignStatusId != null){  
                
                    system.debug('////// DocuSign Status Id' + lstDocuSignStatusId);
                    lstAttachments = [Select Id, Name from Attachment where ParentId = : lstDocuSignStatusId and 
                                      Name like '%Promissory%' and IsDeleted = false];
                    
                    system.debug('////// Attachment Id' + lstAttachments.Id); 
                
            }      
            
            if(lstAttachments != null){                  
                genesis__AppDocCatAttachmentJunction__c lstAppDocCatAttachment = new genesis__AppDocCatAttachmentJunction__c();                
                lstAppDocCatAttachment.genesis__AttachmentId__c = lstAttachments.Id; 
                
                string strAppId = lstAttachments.Name.substringBefore('.');
                Id appId = strAppId.substring(strAppId.length()-15, strAppId.length());
                system.debug('... Application Id ' + appId);
                
            	lstAppDocCat = [Select Id, Name from genesis__Application_Document_Category__c where genesis__Application__c= :appId and Name = 'Promissory Category' and IsDeleted = false];
                                
                if(lstAppDocCat != null){
                    system.debug('... ApplicationDocCategory Id' + lstAppDocCat.Id);                                   
                    lstAppDocCatAttachment.genesis__Application_Document_Category__c = lstAppDocCat.Id;
                    Insert(lstAppDocCatAttachment); 
                }                  
            }            
        }
        
        catch (Exception ex){
            loan__Batch_Process_Log__c bplog = new loan__Batch_Process_Log__c();
            bplog.loan__Origin__c = 'GenerateDocumentCategory Class' ;
            bplog.loan__Message__c = 'Error: ' + ex.getLineNumber() + ' Desc. ' + ex.getMessage()+' Stack: '+ex.getStackTraceString();
            bplog.loan__Type__c = 'Exception';
            bplog.loan__Time__c = DateTime.now();
            insert bplog;
            
            throw ex;
        }
        
    }
}