unpackaged/main/default/objects/genesis__Employment_Information__c/genesis__Employment_Information__c.object-meta.xml
<CustomObject>
    <label>Employment Information</label>
    <nameField>
        <label>Employment Information Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employment Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/genesis__Employment_Information__c/fields/Avg_Paycheck__c.field-meta.xml
<CustomField>
    <fullName>Avg_Paycheck__c</fullName>
    <label>Avg. Paycheck</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/genesis__Employment_Information__c/fields/genesis__Application__c.field-meta.xml
<CustomField>
    <fullName>genesis__Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>genesis__Applications__c</referenceTo>
    <relationshipLabel>Employment Information</relationshipLabel>
    <relationshipName>Employment_Information</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/genesis__Employment_Information__c/fields/genesis__Contact__c.field-meta.xml
<CustomField>
    <fullName>genesis__Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>If this is null, it is for contact (borrower) of an application</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Employment Information</relationshipLabel>
    <relationshipName>Employment_Information</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/genesis__Employment_Information__c/fields/genesis__Employer_City__c.field-meta.xml
<CustomField>
    <fullName>genesis__Employer_City__c</fullName>
    <label>Employer City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/genesis__Employment_Information__c/fields/genesis__Employer_Country__c.field-meta.xml
<CustomField>
    <fullName>genesis__Employer_Country__c</fullName>
    <label>Employer Country</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/genesis__Employment_Information__c/fields/genesis__Employer_State__c.field-meta.xml
<CustomField>
    <fullName>genesis__Employer_State__c</fullName>
    <label>Employer State</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/genesis__Employment_Information__c/fields/genesis__Employer_Street__c.field-meta.xml
<CustomField>
    <fullName>genesis__Employer_Street__c</fullName>
    <label>Employer Street</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/genesis__Employment_Information__c/fields/genesis__Employer_Zipcode__c.field-meta.xml
<CustomField>
    <fullName>genesis__Employer_Zipcode__c</fullName>
    <label>Employer Zipcode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/genesis__Employment_Information__c/fields/genesis__Name_of_employer__c.field-meta.xml
<CustomField>
    <fullName>genesis__Name_of_employer__c</fullName>
    <label>Name of employer</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/genesis__Employment_Information__c/fields/genesis__Number_of_years_on_job__c.field-meta.xml
<CustomField>
    <fullName>genesis__Number_of_years_on_job__c</fullName>
    <label>Number of years on job</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/genesis__Employment_Information__c/fields/genesis__Phone__c.field-meta.xml
<CustomField>
    <fullName>genesis__Phone__c</fullName>
    <label>Phone</label>
    <type>Phone</type>
</CustomField>

unpackaged/main/default/objects/genesis__Employment_Information__c/fields/genesis__Position__c.field-meta.xml
<CustomField>
    <fullName>genesis__Position__c</fullName>
    <label>Position</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/genesis__Employment_Information__c/fields/genesis__Self_Employed__c.field-meta.xml
<CustomField>
    <fullName>genesis__Self_Employed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Self Employed</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/genesis__Employment_Information__c/fields/genesis__Type_of_business__c.field-meta.xml
<CustomField>
    <fullName>genesis__Type_of_business__c</fullName>
    <label>Type of business</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/genesis__Employment_Information__c/fields/Income_Include_Bonuses_or_Commissions__c.field-meta.xml
<CustomField>
    <fullName>Income_Include_Bonuses_or_Commissions__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Income Include Bonuses or Commissions</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/genesis__Employment_Information__c/fields/Neo_Verify__c.field-meta.xml
<CustomField>
    <fullName>Neo_Verify__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Neo Verify</label>
    <referenceTo>Neo_Verify__c</referenceTo>
    <relationshipLabel>Employment Information</relationshipLabel>
    <relationshipName>Employment_Information</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/genesis__Employment_Information__c/fields/Next_Paydate_estimate__c.field-meta.xml
<CustomField>
    <fullName>Next_Paydate_estimate__c</fullName>
    <label>Next Paydate (estimate)</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/genesis__Employment_Information__c/fields/No_of_Paychecks__c.field-meta.xml
<CustomField>
    <fullName>No_of_Paychecks__c</fullName>
    <label>No. of Paychecks</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/genesis__Employment_Information__c/fields/Pay_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Pay_Frequency__c</fullName>
    <label>Pay Frequency</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/genesis__Employment_Information__c/fields/Payroll_Dates__c.field-meta.xml
<CustomField>
    <fullName>Payroll_Dates__c</fullName>
    <label>Payroll Dates</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/genesis__Employment_Information__c/fields/Payroll_Source_Company__c.field-meta.xml
<CustomField>
    <fullName>Payroll_Source_Company__c</fullName>
    <label>Payroll Source Company</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/genesis__Employment_Information__c/fields/Previous_occupation__c.field-meta.xml
<CustomField>
    <fullName>Previous_occupation__c</fullName>
    <label>Previous_occupation</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/genesis__Employment_Information__c/fields/Send_work_email_verification_Email__c.field-meta.xml
<CustomField>
    <fullName>Send_work_email_verification_Email__c</fullName>
    <defaultValue>false</defaultValue>
    <description>checked by click of button on application. Used to trigger work email alert</description>
    <label>Send work email verification Email</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/genesis__Employment_Information__c/fields/Total_Earnings__c.field-meta.xml
<CustomField>
    <fullName>Total_Earnings__c</fullName>
    <label>Total Earnings</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/genesis__Employment_Information__c/fields/Work_Email__c.field-meta.xml
<CustomField>
    <fullName>Work_Email__c</fullName>
    <label>Work Email</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/genesis__Employment_Information__c/fields/Work_email_verified_check_box__c.field-meta.xml
<CustomField>
    <fullName>Work_email_verified_check_box__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Work email verified check box</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/genesis__Employment_Information__c/fields/WorkEmailKeyCode__c.field-meta.xml
<CustomField>
    <fullName>WorkEmailKeyCode__c</fullName>
    <description>random key code generated when work email address is changed. Used in Work Email Verification email.</description>
    <label>WorkEmailKeyCode</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/genesis__Employment_Information__c/fields/WorkEmailKeyCodeResponse__c.field-meta.xml
<CustomField>
    <fullName>WorkEmailKeyCodeResponse__c</fullName>
    <description>work email verification key code sent by front end system to validate against WorkEmailKeyCode generated when work email was updated.</description>
    <label>WorkEmailKeyCodeResponse</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Neo_Verify__c/Neo_Verify__c.object-meta.xml
<CustomObject>
    <label>Neo Verify</label>
    <nameField>
        <displayFormat>A-{0000000000}</displayFormat>
        <label>Neo Verify Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Neo Verify</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Neo_Verify__c/fields/Avg_Paycheck__c.field-meta.xml
<CustomField>
    <fullName>Avg_Paycheck__c</fullName>
    <label>Avg. Paycheck</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Neo_Verify__c/fields/Next_Paydate_estimate__c.field-meta.xml
<CustomField>
    <fullName>Next_Paydate_estimate__c</fullName>
    <label>Next Paydate (estimate)</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Neo_Verify__c/fields/No_of_Paychecks__c.field-meta.xml
<CustomField>
    <fullName>No_of_Paychecks__c</fullName>
    <label>No. of Paychecks</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Neo_Verify__c/fields/Pay_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Pay_Frequency__c</fullName>
    <label>Pay Frequency</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Neo_Verify__c/fields/Payroll_Dates__c.field-meta.xml
<CustomField>
    <fullName>Payroll_Dates__c</fullName>
    <label>Payroll Dates</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Neo_Verify__c/fields/Payroll_Source_Company__c.field-meta.xml
<CustomField>
    <fullName>Payroll_Source_Company__c</fullName>
    <label>Payroll Source Company</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Neo_Verify__c/fields/Total_Earnings__c.field-meta.xml
<CustomField>
    <fullName>Total_Earnings__c</fullName>
    <label>Total Earnings</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/classes/MW_RetrieveEmpInfobyAppId.cls
@RestResource(urlMapping='/employment-information/application-id/*')
global with sharing class MW_RetrieveEmpInfobyAppId {
    @HttpGet
    global static void MW_RetrieveEmpInfobyAppId() {
        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;
        try {
            String contractId = req.params.get('application-id');
            if (String.isBlank(contractId)) {
                res.statusCode = 400;
                res.responseBody = Blob.valueOf('application id is required');
                return;
            }
            List<genesis__Employment_Information__c> empInfos = [
                SELECT
                Id,
                OwnerId,
                Name,
                CreatedDate,
                CreatedById,
                LastModifiedDate,
                LastModifiedById,
                genesis__Application__c,
                genesis__Contact__c,
                genesis__Employer_City__c,
                genesis__Employer_Country__c,
                genesis__Employer_State__c,
                genesis__Employer_Street__c,
                genesis__Employer_Zipcode__c,
                genesis__Name_of_employer__c,
                genesis__Number_of_years_on_job__c,
                genesis__Phone__c,
                genesis__Position__c,
                genesis__Self_Employed__c,
                genesis__Type_of_business__c,
                Avg_Paycheck__c,
                Income_Include_Bonuses_or_Commissions__c,
                Neo_Verify__c,
                Next_Paydate_estimate__c,
                No_of_Paychecks__c,
                Pay_Frequency__c,
                Payroll_Dates__c,
                Payroll_Source_Company__c,
                Previous_occupation__c,
                Send_work_email_verification_Email__c,
                Total_Earnings__c,
                Work_Email__c,
                Work_email_verified_check_box__c,
                WorkEmailKeyCode__c,
                WorkEmailKeyCodeResponse__c,
                DataArchiva_Old_Id__c,
                DataArchiva_Read_Only_Data__c
                FROM genesis__Employment_Information__c
                WHERE genesis__Application__c = :contractId
            ];
            res.statusCode = 200;
            res.responseBody = Blob.valueOf(JSON.serialize(empInfos));
        }
        catch (Exception e) {
            res.statusCode = 500;
            res.responseBody = Blob.valueOf(e.getMessage());
        }
         
    }
}