force-app/main/default/objects/External_Logger__e/External_Logger__e.object-meta.xml
<CustomObject>
    <description>External log publish object for Datadog</description>
    <label>External Logger</label>
    <pluralLabel>External Logger</pluralLabel>
</CustomObject>

force-app/main/default/objects/External_Logger__e/fields/Log_Id__c.field-meta.xml
<CustomField>
    <fullName>Log_Id__c</fullName>
    <label>Log Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/External_Logger__e/fields/Serialized_Log__c.field-meta.xml
<CustomField>
    <fullName>Serialized_Log__c</fullName>
    <label>Serialized Log</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/MW_LogTriggerHelper.cls
public with sharing class MW_LogTriggerHelper {
    public MW_LogUtility.JobLog construct(String name, String apexclass, String label, String type, String message) {

        MW_LogUtility.JobLog log = new MW_LogUtility.JobLog();
        log.apexClass = apexclass;
		log.label = label;
		log.message = message;
        log.type = type;


        List<String> facetList = new List<String>();
		facetList.add('severity:' + log.type);
		External_Logger__e logEvent = new External_Logger__e(
			Log_Id__c = name,
			Serialized_Log__c = JSON.serialize(log)
		);

		Database.SaveResult result = EventBus.publish(logEvent);

		if (!result.isSuccess()) {
			for (Database.Error err : result.getErrors()) {
				System.debug('Error returned: ' + err.getStatusCode() +	' - ' +	err.getMessage());
			}
		}

		return log;
    }
}