unpackaged/main/default/objects/Expiry_Date__c/Expiry_Date__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Expiry Date</label>
</CustomObject>

unpackaged/main/default/objects/genesis__Applications__c/genesis__Applications__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{0000000000}</displayFormat>
        <label>Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/genesis__Applications__c/fields/DocuSign_EnvelopeId__c.field-meta.xml
<CustomField>
    <fullName>DocuSign_EnvelopeId__c</fullName>
    <label>DocuSign EnvelopeId</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/genesis__Applications__c/fields/Expiration_Tag__c.field-meta.xml
<CustomField>
    <fullName>Expiration_Tag__c</fullName>
    <label>Expiration Tag</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>expired_pre_qual</fullName>
            </value>
            <value>
                <fullName>expired_verification</fullName>
            </value>
            <value>
                <fullName>expired_docs</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/genesis__Applications__c/fields/Expiry_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiry_Date__c</fullName>
    <description>/*Created By Nupur */
------- For Email Alert</description>
    <formula>Application_Start_DateV2__c + $Setup.Expiry_Date__c.No_of_days_for_Expiration__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Expiry Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/genesis__Applications__c/fields/genesis__Status__c.field-meta.xml
<CustomField>
    <fullName>genesis__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>APPROVED - APPROVED</fullName>
            </value>
            <value>
                <fullName>APPROVED - CONVERTED TO CONTRACT</fullName>
            </value>
            <value>
                <fullName>APPROVED - DOCUMENT CHECK</fullName>
            </value>
            <value>
                <fullName>NEW - CREDIT PULLED</fullName>
            </value>
            <value>
                <fullName>NEW - ENTERED</fullName>
                <default>true</default>
                <label>NEW - ENTERED</label>
            </value>
            <value>
                <fullName>NEW - IN CREDIT CHECK</fullName>
            </value>
            <value>
                <fullName>NEW - IN REVIEW</fullName>
            </value>
            <value>
                <fullName>NEW - PRICING GENERATED</fullName>
            </value>
            <value>
                <fullName>NEW - SCORECARD GENERATED</fullName>
            </value>
            <value>
                <fullName>NEW - CHECKLIST GENERATED</fullName>
            </value>
            <value>
                <fullName>NEW - VEHICLE VALUATION REQUIRED</fullName>
            </value>
            <value>
                <fullName>REJECTED</fullName>
            </value>
            <value>
                <fullName>PULL CREDIT</fullName>
            </value>
            <value>
                <fullName>Default Documents</fullName>
            </value>
            <value>
                <fullName>offer_accepted</fullName>
            </value>
            <value>
                <fullName>offer_shown</fullName>
            </value>
            <value>
                <fullName>kba_success</fullName>
            </value>
            <value>
                <fullName>kba_fail</fullName>
            </value>
            <value>
                <fullName>agent_document_verification_pending</fullName>
            </value>
            <value>
                <fullName>agent_verification_pending</fullName>
            </value>
            <value>
                <fullName>agent_verified</fullName>
            </value>
            <value>
                <fullName>docusign_loan_docs_sent</fullName>
            </value>
            <value>
                <fullName>docusign_loan_docs_complete</fullName>
            </value>
            <value>
                <fullName>pre_funding</fullName>
            </value>
            <value>
                <fullName>Approved for funding</fullName>
            </value>
            <value>
                <fullName>funded</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Stacker_Check_Passed</fullName>
            </value>
            <value>
                <fullName>Redecision_Required</fullName>
            </value>
            <value>
                <fullName>Decline_Manual_Review</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/genesis__Applications__c/fields/Lead_ID__c.field-meta.xml
<CustomField>
    <fullName>Lead_ID__c</fullName>
    <description>This is the LEAD GUID received from FE</description>
    <externalId>true</externalId>
    <label>Lead ID</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/genesis__Applications__c/fields/LEAD_ID_ExtKey__c.field-meta.xml
<CustomField>
    <fullName>LEAD_ID_ExtKey__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>LEAD_ID_ExtKey</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/genesis__Applications__c/fields/Member_ID__c.field-meta.xml
<CustomField>
    <fullName>Member_ID__c</fullName>
    <formula>genesis__Account__r.Member_ID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Member ID</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/lead_id__c.field-meta.xml
<CustomField>
    <fullName>lead_id__c</fullName>
    <externalId>true</externalId>
    <label>lead_id</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/member_id__c.field-meta.xml
<CustomField>
    <fullName>member_id__c</fullName>
    <externalId>true</externalId>
    <label>member_id</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/loan__Batch_Process_Log__c/loan__Batch_Process_Log__c.object-meta.xml
<CustomObject>
    <label>Batch Process Log</label>
    <nameField>
        <label>Apex Batch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Batch Process Log</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/loan__Batch_Process_Log__c/fields/App_Ids__c.field-meta.xml
<CustomField>
    <fullName>App_Ids__c</fullName>
    <label>App Ids</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/loan__Batch_Process_Log__c/fields/loan__Log_Level__c.field-meta.xml
<CustomField>
    <fullName>loan__Log_Level__c</fullName>
    <description>An indicator of level of logging</description>
    <label>Log Level</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ERROR</fullName>
                <default>true</default>
                <label>ERROR</label>
            </value>
            <value>
                <fullName>DEBUG</fullName>
            </value>
            <value>
                <fullName>INFO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/loan__Batch_Process_Log__c/fields/loan__Message__c.field-meta.xml
<CustomField>
    <fullName>loan__Message__c</fullName>
    <label>Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/loan__Batch_Process_Log__c/fields/loan__Origin__c.field-meta.xml
<CustomField>
    <fullName>loan__Origin__c</fullName>
    <label>Origin</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Start Of Day Process</fullName>
            </value>
            <value>
                <fullName>End of Day Process</fullName>
            </value>
            <value>
                <fullName>Month End Process</fullName>
            </value>
            <value>
                <fullName>Year End Process</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/loan__Batch_Process_Log__c/fields/loan__Time__c.field-meta.xml
<CustomField>
    <fullName>loan__Time__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <label>Time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/loan__Batch_Process_Log__c/fields/loan__Type__c.field-meta.xml
<CustomField>
    <fullName>loan__Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Exception</fullName>
            </value>
            <value>
                <fullName>Warning</fullName>
            </value>
            <value>
                <fullName>Info</fullName>
            </value>
            <value>
                <fullName>Result</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/MWBatchPostExpiryApplication_Manual.cls
/*
Purpose: Just for running one time, this batch has been created to Send isExpired flag for existing Manual Decline for ticket CRM-535.
This class is replica of 'MWBatchPostExpiryApplication' and modified for this ticket purpose.
How to call this batch?
For CRM-535, we would pass appStatus = 'Decline_Manual_Review' and expiryDate = current date(yyyy-mm-dd). But same can be use again in future by passing different status and expiry date.
Example:
Set<String> appStatus = new Set<String>{'Decline_Manual_Review'}; //{'Expired','Declined','Decline_Manual_Review'};
String expiryDate = '2020-05-21';
MWBatchPostExpiryApplication_Manual b = new MWBatchPostExpiryApplication_Manual(expiryDate, appStatus);
Database.executeBatch(b,1);
*/

global class MWBatchPostExpiryApplication_Manual implements Database.batchable<sObject>, Database.AllowsCallouts {
    //Date currentSystemDate = new loan.GlobalLoanUtilFacade().getCurrentSystemDate();
    global final String query;
    global final String expiryDate;
    global final Set<String> appStatus;

    global MWBatchPostExpiryApplication_Manual(String pExpiryDate, Set<String> pAppStatus) {
        //String CSD = String.valueof(new loan.GlobalLoanUtilFacade().getCurrentSystemDate());

        //SELECT Id, Expiry_Date__c, genesis__Status__c,CreatedById, owner.Name, LEAD_ID_ExtKey__c, Member_ID__c, Lead_ID__c, DocuSign_EnvelopeId__c, Expiration_Tag__c FROM genesis__Applications__c WHERE Expiry_Date__c <= '2020-05-21' AND genesis__Status__c IN ('Decline_Manual_Review')
        expiryDate = pExpiryDate;
        appStatus = pAppStatus;
        query = 'SELECT Id, Expiry_Date__c, genesis__Status__c, CreatedById, owner.Name, LEAD_ID_ExtKey__c, Member_ID__c, Lead_ID__c, DocuSign_EnvelopeId__c, Expiration_Tag__c FROM genesis__Applications__c WHERE Expiry_Date__c <=' + expiryDate + ' AND genesis__Status__c IN : appStatus';

        System.debug('query=' + query);
    }

    @TestVisible static sync_application syncApp;
    global Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<sObject> scope) {
		//for logging only
		String appIdList = '';
		String leadIdList = '';
        try {
			List<genesis__Applications__c > listOfApp = (List<genesis__Applications__c >) scope;

			list<ApplicationInformation> listAppInfo = new list<ApplicationInformation>();

			for (genesis__Applications__c app : listOfApp) {
				appIdList = appIdList + String.valueOf(app.Id) + ' ';
				leadIdList = leadIdList + app.Lead_ID__c + ' ';
				applicationinformation appinfo = new ApplicationInformation();

				appinfo.expiry_date = app.Expiry_Date__c;

				if (app.genesis__Status__c == 'Expired') {
					appinfo.lead_guid = app.Lead_ID__c;
					appinfo.lead_id = app.LEAD_ID_ExtKey__c;
					appinfo.member_id = app.Member_ID__c;

					appinfo.is_expired = true;
					listAppInfo.add(appinfo);
				}
                if (app.genesis__Status__c == 'Expired-Withdrawn') {
					appinfo.lead_guid = app.Lead_ID__c;
					appinfo.lead_id = app.LEAD_ID_ExtKey__c;
					appinfo.member_id = app.Member_ID__c;

					appinfo.is_expired = true;
					listAppInfo.add(appinfo);
				}  

				//if((app.genesis__Status__c=='Declined' || app.genesis__Status__c=='Decline_Manual_Review') && app.owner.Name=='Declined' && app.Expiry_Date__c == currentSystemDate) {
				if ((app.genesis__Status__c == 'Declined' || app.genesis__Status__c == 'Decline_Manual_Review')) {
					appinfo.lead_guid = app.Lead_ID__c;
					appinfo.lead_id = app.LEAD_ID_ExtKey__c;
					appinfo.member_id = app.Member_ID__c;

					appinfo.is_expired = true;
					listAppInfo.add(appinfo);
				} /*else if (app.genesis__Status__c == 'Declined' && app.owner.Name == 'Declined') {
                    appinfo.lead_guid = app.Lead_ID__c;
                    appinfo.lead_id = app.LEAD_ID_ExtKey__c;
                    appinfo.member_id = app.Member_ID__c;
                    appinfo.is_expired = false;
                    listAppInfo.add(appinfo);
                }*/
			}

			syncApp = new sync_application('sync_application', listAppInfo);
			String str = JSON.serialize(syncApp, true);
			System.debug('str=' + str);
			If (!Test.IsRunningTest()) {
				MW_WebhookHandler.CallWebHookIntegration(str, appIdList, leadIdList);
			}
			//log for reporting
			loan__Batch_Process_Log__c bplog = new loan__Batch_Process_Log__c();
            bplog.loan__Origin__c = 'MWBatchPostExpiryApplication_Manual';
            bplog.loan__Message__c = 'JSON = ' + str;
            bplog.loan__Type__c = 'Info';
            bplog.loan__Time__c = DateTime.now();
            bplog.App_Ids__c = 'Lead GUID = ' + leadIdList;
            bplog.loan__Log_Level__c = 'DEBUG';
			insert bplog;

        } catch (Exception ex) {
			//log for reporting
			loan__Batch_Process_Log__c bplog = new loan__Batch_Process_Log__c();
            bplog.loan__Origin__c = 'MWBatchPostExpiryApplication_Manual';
            bplog.loan__Message__c = 'Error: ' + ex.getLineNumber() + ' Desc. ' + ex.getMessage() + ' Stack: ' + ex.getStackTraceString();
            bplog.loan__Type__c = 'Exception';
            bplog.loan__Time__c = DateTime.now();
            bplog.App_Ids__c = 'Lead GUID = ' + leadIdList;
            bplog.loan__Log_Level__c = 'ERROR';
            insert bplog;
        }

    }

    global void finish(Database.BatchableContext BC) {

    }

    /*
    global void execute(SchedulableContext sc) {
        MWBatchPostExpiryApplication_Manual b = new MWBatchPostExpiryApplication_Manual();
        Database.executeBatch(b,1);
    }
    */

    class ApplicationInformation {
        public string lead_guid;
        public string lead_id;
        public string member_id;
        public date expiration_date;
        public date expiry_date;
        public boolean is_expired;
    }

    class sync_application {
        String type;
        @TestVisible ApplicationInformation[] data;
        public sync_application(String type, ApplicationInformation[] appInfo) {
            this.type = type;
            this.data = appInfo;
        }
    }

}