force-app/main/default/objects/loan__Loan_Account__c/loan__Loan_Account__c.object-meta.xml
<CustomObject>
    <description>Lending Account</description>
    <label>CL Contract</label>
    <nameField>
        <displayFormat>LAI-{00000000}</displayFormat>
        <label>CL Contract ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CL Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/loan__Loan_Account__c/fields/loan__Payment_Mode__c.field-meta.xml
<CustomField>
    <fullName>loan__Payment_Mode__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>This is the default payment mode for this loan. It will be used to populate the payment mode on the loan payment transaction screen.</inlineHelpText>
    <label>Payment Mode</label>
    <referenceTo>loan__Payment_Mode__c</referenceTo>
    <relationshipLabel>CL Contracts</relationshipLabel>
    <relationshipName>CL_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Payment_Transaction__c/loan__Loan_Payment_Transaction__c.object-meta.xml
<CustomObject>
    <description>Loan Payment Transaction</description>
    <label>Loan Payment Transaction</label>
    <nameField>
        <displayFormat>LPT-{000000000}</displayFormat>
        <label>Loan Payment Transaction ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loan Payment Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/loan__Loan_Payment_Transaction__c/fields/loan__Cleared__c.field-meta.xml
<CustomField>
    <fullName>loan__Cleared__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates if this loan payment transaction is supervised or not.</description>
    <inlineHelpText>Indicates if this loan payment transaction is supervised or not.</inlineHelpText>
    <label>Cleared</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Payment_Transaction__c/fields/loan__Loan_Account__c.field-meta.xml
<CustomField>
    <fullName>loan__Loan_Account__c</fullName>
    <description>Loan Account</description>
    <inlineHelpText>Loan Account</inlineHelpText>
    <label>Loan Account</label>
    <referenceTo>loan__Loan_Account__c</referenceTo>
    <relationshipLabel>Loan Payment Transactions</relationshipLabel>
    <relationshipName>Loan_Payment_Transactions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Payment_Transaction__c/fields/loan__Payment_Mode__c.field-meta.xml
<CustomField>
    <fullName>loan__Payment_Mode__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Mode</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>loan__Payment_Mode__c.Name</field>
            <operation>notEqual</operation>
            <value>Internal Transfer</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>loan__Payment_Mode__c</referenceTo>
    <relationshipLabel>Loan Payment Transactions</relationshipLabel>
    <relationshipName>Loan_Payment_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Payment_Transaction__c/fields/loan__Reversed__c.field-meta.xml
<CustomField>
    <fullName>loan__Reversed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Reversed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Payment_Transaction__c/fields/loan__Transaction_Date__c.field-meta.xml
<CustomField>
    <fullName>loan__Transaction_Date__c</fullName>
    <defaultValue>$User.loan__Current_Branch_s_System_Date__c</defaultValue>
    <description>Transaction Date</description>
    <inlineHelpText>Transaction Date</inlineHelpText>
    <label>Transaction Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/loan__Payment_Mode__c/loan__Payment_Mode__c.object-meta.xml
<CustomObject>
    <label>Payment Mode</label>
    <nameField>
        <label>Payment Mode Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Mode</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/PaymentReversalsBatch.cls
global class PaymentReversalsBatch implements Database.Batchable<SObject> {
    
    global Database.QueryLocator start(Database.BatchableContext bc) {
        
        String query = 'SELECT Id, loan__Loan_Account__r.Name FROM loan__Loan_Payment_Transaction__c WHERE loan__Transaction_Date__c = 2022-10-28 AND loan__Cleared__c = TRUE AND loan__Reversed__c = FALSE AND loan__Payment_Mode__r.Name != \'Waived\' AND loan__Loan_Account__r.Name NOT IN ( \'LAI-00574687\', \'LAI-00577525\', \'LAI-00079976\', \'LAI-00341021\', \'LAI-00011633\', \'LAI-00553408\', \'LAI-00081184\', \'LAI-00599905\', \'LAI-00539758\', \'LAI-00545713\', \'LAI-00129498\', \'LAI-00096446\', \'LAI-00607800\', \'LAI-00621275\' )' ;       
        System.debug(logginglevel.error,'query'+query);
        return Database.getQueryLocator(query);
        
    } 
    
    global void execute(Database.BatchableContext bc, List<sObject> scope){
            
            System.debug(logginglevel.error,'----Method execute(+)scope----'+ scope);
            List<loan__Loan_Payment_Transaction__c> records = (List<loan__Loan_Payment_Transaction__c>)scope;
            
            Set<Id> loanPaymentIds = new Set<Id>();
            for (loan__Loan_Payment_Transaction__c lpt : records) {
                loanPaymentIds.add(lpt.Id);
            }
            
            loan.LoanActionFactory factory = new loan.LoanActionFactory();
            loan.LoanAction2 loanAction = factory.getLoanAction2API();
            loanAction.reverseLoanPayment(loanPaymentIds,'other',' No Nacha');
        }
    
    global void finish(Database.BatchableContext bc){

        System.debug(LoggingLevel.INFO, 'Successful completion of job');
    }
}