force-app/main/default/objects/loan__Loan_Account__c/loan__Loan_Account__c.object-meta.xml
<CustomObject>
    <description>Lending Account</description>
    <label>CL Contract</label>
    <nameField>
        <displayFormat>LAI-{00000000}</displayFormat>
        <label>CL Contract ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CL Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/loan__Loan_Block_Code__c/loan__Loan_Block_Code__c.object-meta.xml
<CustomObject>
    <description>Contingency Status Code&apos;s are tagging  loan accounts indicating specific situations such as bankruptcy, fraud etc.</description>
    <label>Contingency Status Code</label>
    <nameField>
        <displayFormat>CSC-{0000000}</displayFormat>
        <label>Contingency Status Code Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contingency Status Codes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/loan__Loan_Block_Code__c/fields/loan__Block_Code__c.field-meta.xml
<CustomField>
    <fullName>loan__Block_Code__c</fullName>
    <label>Contingency Status Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Bankruptcy  (B)</fullName>
            </value>
            <value>
                <fullName>Deceased  (D)</fullName>
            </value>
            <value>
                <fullName>Fraudulent (F)</fullName>
            </value>
            <value>
                <fullName>Duplicate (K)</fullName>
            </value>
            <value>
                <fullName>No Communication (X)</fullName>
            </value>
            <value>
                <fullName>SCRA (S)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/loan__Loan_Block_Code__c/fields/loan__Block_Code_Applied_On__c.field-meta.xml
<CustomField>
    <fullName>loan__Block_Code_Applied_On__c</fullName>
    <label>Contingency Status Code Applied On</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Block_Code__c/fields/loan__Block_Code_Expires_On__c.field-meta.xml
<CustomField>
    <fullName>loan__Block_Code_Expires_On__c</fullName>
    <label>Contingency Status Code Expires On</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Block_Code__c/fields/loan__Block_Code_Expiry_Processed__c.field-meta.xml
<CustomField>
    <fullName>loan__Block_Code_Expiry_Processed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is Block Code Expiry Processed?</description>
    <label>Contingency Status Code Expiry Processed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Block_Code__c/fields/loan__Block_Code_Revoked__c.field-meta.xml
<CustomField>
    <fullName>loan__Block_Code_Revoked__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is Block Code Revoked?</description>
    <label>Contingency Status Code Revoked</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Block_Code__c/fields/loan__Block_Code_Revoked_On__c.field-meta.xml
<CustomField>
    <fullName>loan__Block_Code_Revoked_On__c</fullName>
    <label>Contingency Status Code Revoked On</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Block_Code__c/fields/loan__Contingency_Status_Code_Setup__c.field-meta.xml
<CustomField>
    <fullName>loan__Contingency_Status_Code_Setup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Loan Account for which this Contingency Status code is defined</description>
    <inlineHelpText>Id of other transaction made by Contingency Status Code</inlineHelpText>
    <label>Contingency Status Code Setup</label>
    <referenceTo>clcommon__Contingency_Status_Code__c</referenceTo>
    <relationshipLabel>Contingency Status Codes</relationshipLabel>
    <relationshipName>Loan_Block_Codes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Block_Code__c/fields/loan__Invalidate_Contract__c.field-meta.xml
<CustomField>
    <fullName>loan__Invalidate_Contract__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Invalidate Contract</description>
    <label>Invalidate Contract</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Block_Code__c/fields/loan__Loan_Account__c.field-meta.xml
<CustomField>
    <fullName>loan__Loan_Account__c</fullName>
    <description>Loan Account for which this Contingency Status code is defined</description>
    <label>CL Contract</label>
    <referenceTo>loan__Loan_Account__c</referenceTo>
    <relationshipLabel>Contingency Status Codes</relationshipLabel>
    <relationshipName>Loan_Block_Codes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Block_Code__c/fields/loan__Minutes_To_Expire_Code__c.field-meta.xml
<CustomField>
    <fullName>loan__Minutes_To_Expire_Code__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Minutes To Expire Code</description>
    <inlineHelpText>Minutes to expire</inlineHelpText>
    <label>Minutes To Expire Code</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Block_Code__c/fields/loan__Other_Transaction__c.field-meta.xml
<CustomField>
    <fullName>loan__Other_Transaction__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This stores the ID of other transaction made by Loan Block Code.</description>
    <inlineHelpText>Id of other transaction made by Loan Block Code</inlineHelpText>
    <label>Other Loan Transaction</label>
    <referenceTo>loan__Other_Transaction__c</referenceTo>
    <relationshipLabel>Contingency Status Codes</relationshipLabel>
    <relationshipName>Loan_Block_Codes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Block_Code__c/fields/loan__Stop_Accrual_Entries__c.field-meta.xml
<CustomField>
    <fullName>loan__Stop_Accrual_Entries__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Applicable with picklist value &apos;Stop Accrual Entry&apos;</description>
    <inlineHelpText>Applicable with picklist value &apos;Stop Accrual Entry&apos;</inlineHelpText>
    <label>Stop Accrual Entries</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Block_Code__c/fields/loan__Stop_Accruals__c.field-meta.xml
<CustomField>
    <fullName>loan__Stop_Accruals__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Stop Accruals</description>
    <label>Stop Accruals</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Block_Code__c/fields/loan__Suspend_ACH__c.field-meta.xml
<CustomField>
    <fullName>loan__Suspend_ACH__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Suspend ACH</description>
    <label>Suspend ACH</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Block_Code__c/fields/loan__Suspend_Charges__c.field-meta.xml
<CustomField>
    <fullName>loan__Suspend_Charges__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Suspend Charges</description>
    <label>Suspend Charges</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Block_Code__c/fields/loan__Suspend_Communication__c.field-meta.xml
<CustomField>
    <fullName>loan__Suspend_Communication__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Suspend Communication</description>
    <label>Suspend Communication</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Block_Code__c/fields/loan__Suspend_Disbursals__c.field-meta.xml
<CustomField>
    <fullName>loan__Suspend_Disbursals__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Suspend Disbursals</description>
    <label>Suspend Disbursals</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/loan__Other_Transaction__c/loan__Other_Transaction__c.object-meta.xml
<CustomObject>
    <label>Other Loan Transaction</label>
    <nameField>
        <displayFormat>OLTID-{0000000000}</displayFormat>
        <label>Other Transaction ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Other Loan Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/loan__Other_Transaction__c/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/loan__Other_Transaction__c/fields/loan__Loan_Account__c.field-meta.xml
<CustomField>
    <fullName>loan__Loan_Account__c</fullName>
    <label>Loan Account</label>
    <referenceTo>loan__Loan_Account__c</referenceTo>
    <relationshipLabel>Other Loan Transactions</relationshipLabel>
    <relationshipName>Other_Loan_Transactions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/MW_RetrieveContByContractId.cls
@RestResource(urlMapping='/contingency/contract-id/*')
global with sharing class MW_RetrieveContByContractId {
    @HttpGet
    global static void  MW_RetrieveContByContractId() {
        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;
        try {
            String contractId = req.params.get('contract-id');
            if (String.isBlank(contractId)) {
                res.statusCode = 400;
                res.responseBody = Blob.valueOf('contract id is required');
                return;
            }
            List<loan__Loan_Block_Code__c> bills = [
                SELECT
                Id,
                Name,
                CreatedDate,
                CreatedById,
                LastModifiedDate,
                LastModifiedById,
                loan__Loan_Account__c,
                loan__Archived__c,
                loan__Block_Code_Applied_On__c,
                loan__Block_Code_Expires_On__c,
                loan__Block_Code_Expiry_Processed__c,
                loan__Block_Code_Revoked_On__c,
                loan__Block_Code_Revoked__c,
                loan__Block_Code__c,
                loan__Master_Archive_Object__c,
                loan__Minutes_To_Expire_Code__c,
                loan__Other_Transaction__c,
                loan__Stop_Accruals__c,
                loan__Summary_Record_Id__c,
                loan__Summary__c,
                loan__Suspend_ACH__c,
                loan__Suspend_Charges__c,
                loan__Suspend_Communication__c,
                loan__Suspend_Disbursals__c,
                loan__Contingency_Status_Code_Setup__c,
                loan__Invalidate_Contract__c,
                loan__Stop_Accrual_Entries__c,
                External_Id__c
                FROM loan__Loan_Block_Code__c
                WHERE loan__Loan_Account__c = :contractId
            ];
            res.statusCode = 200;
            res.responseBody = Blob.valueOf(JSON.serialize(bills));
        }
        catch (Exception e) {
            res.statusCode = 500;
            res.responseBody = Blob.valueOf(e.getMessage());
        }
    }
}