force-app/main/default/objects/loan__Loan_Account__c/loan__Loan_Account__c.object-meta.xml
<CustomObject>
    <description>Lending Account</description>
    <label>CL Contract</label>
    <nameField>
        <displayFormat>LAI-{00000000}</displayFormat>
        <label>CL Contract ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CL Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/loan__Loan_Account__c/fields/loan__Fees_Billed__c.field-meta.xml
<CustomField>
    <fullName>loan__Fees_Billed__c</fullName>
    <defaultValue>0</defaultValue>
    <description>This captures the total fees billed which is calculated at the time of billing.</description>
    <inlineHelpText>This captures the total fees billed which is calculated at the time of billing.</inlineHelpText>
    <label>Fees Billed</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/loan__Fees_Paid__c.field-meta.xml
<CustomField>
    <fullName>loan__Fees_Paid__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Fees Paid</description>
    <inlineHelpText>Fees Paid</inlineHelpText>
    <label>Fees Paid</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/loan__Interest_Paid__c.field-meta.xml
<CustomField>
    <fullName>loan__Interest_Paid__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Interest Paid
Account Balance Details- System calculated Uneditable fields</description>
    <inlineHelpText>Interest Paid
Account Balance Details- Fields calculated by the system which cannot be edited.</inlineHelpText>
    <label>Interest Paid</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/loan__Principal_Paid__c.field-meta.xml
<CustomField>
    <fullName>loan__Principal_Paid__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Principal Paid Account Balance Details- System calculated Uneditable fields</description>
    <inlineHelpText>Paid Principal/Advance.</inlineHelpText>
    <label>Principal/Advance Paid</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/loan__Loan_account_Due_Details__c/loan__Loan_account_Due_Details__c.object-meta.xml
<CustomObject>
    <description>Invoices/bills for customer loans.</description>
    <label>Bills</label>
    <nameField>
        <displayFormat>PCN-{0000000000}</displayFormat>
        <label>Due Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bills</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/loan__Loan_account_Due_Details__c/fields/loan__Actual_Tolerance_Amount__c.field-meta.xml
<CustomField>
    <fullName>loan__Actual_Tolerance_Amount__c</fullName>
    <description>This is the tolerance amount calculated from the bill. It will be populated on billing based on the tolerance defined on Loan account.</description>
    <inlineHelpText>Populated from loan account on the basis of tolerance amount calculated.</inlineHelpText>
    <label>Actual Tolerance Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/loan__Loan_account_Due_Details__c/fields/loan__Average_Daily_Balance__c.field-meta.xml
<CustomField>
    <fullName>loan__Average_Daily_Balance__c</fullName>
    <description>Average daily balance of the billing cycle</description>
    <inlineHelpText>Average daily balance that was maintained from billing start date to billing end date</inlineHelpText>
    <label>Average Daily Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/loan__Loan_account_Due_Details__c/fields/loan__Balance__c.field-meta.xml
<CustomField>
    <fullName>loan__Balance__c</fullName>
    <inlineHelpText>This field contains the principal balance on the loan after this bill has been generated.</inlineHelpText>
    <label>Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/loan__Loan_account_Due_Details__c/fields/loan__Balance_Amount__c.field-meta.xml
<CustomField>
    <fullName>loan__Balance_Amount__c</fullName>
    <formula>loan__Due_Amt__c -  loan__Payment_Amt__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Balance Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/loan__Loan_account_Due_Details__c/fields/loan__Bill_Cycle_End_Date__c.field-meta.xml
<CustomField>
    <fullName>loan__Bill_Cycle_End_Date__c</fullName>
    <inlineHelpText>end date of current billing cycle</inlineHelpText>
    <label>Bill Cycle End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/loan__Loan_account_Due_Details__c/fields/loan__Bill_Cycle_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>loan__Bill_Cycle_Start_Date__c</fullName>
    <inlineHelpText>Date from which billing period starts.</inlineHelpText>
    <label>Bill Cycle Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/loan__Loan_account_Due_Details__c/fields/loan__Closing_Balance__c.field-meta.xml
<CustomField>
    <fullName>loan__Closing_Balance__c</fullName>
    <description>Principal balance maintained as on the last day of current billing cycle. This is the sum of all disbursals minus the sum of all payments made till the last day of the current billing cycle.</description>
    <inlineHelpText>Principal balance maintained as on the last day of current billing cycle. This is the sum of all disbursals minus the sum of all payments made till the last day of the current billing cycle.</inlineHelpText>
    <label>Closing Principal Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/loan__Loan_account_Due_Details__c/fields/loan__Compounding_Interest_Billed__c.field-meta.xml
<CustomField>
    <fullName>loan__Compounding_Interest_Billed__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Compounding Interest Billed (+)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/loan__Loan_account_Due_Details__c/fields/loan__DD_Primary_Flag__c.field-meta.xml
<CustomField>
    <fullName>loan__DD_Primary_Flag__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Primary</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/loan__Loan_account_Due_Details__c/fields/loan__Due_Amt__c.field-meta.xml
<CustomField>
    <fullName>loan__Due_Amt__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Due Amount</description>
    <label>Due Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/loan__Loan_account_Due_Details__c/fields/loan__Due_Date__c.field-meta.xml
<CustomField>
    <fullName>loan__Due_Date__c</fullName>
    <description>Due date of the due.</description>
    <inlineHelpText>Due Date of the Due</inlineHelpText>
    <label>Due Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/loan__Loan_account_Due_Details__c/fields/loan__Due_Type__c.field-meta.xml
<CustomField>
    <fullName>loan__Due_Type__c</fullName>
    <description>Due Type Id</description>
    <label>Due Type Id</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/loan__Loan_account_Due_Details__c/fields/loan__Due_Type_Description__c.field-meta.xml
<CustomField>
    <fullName>loan__Due_Type_Description__c</fullName>
    <description>Description of Due, to be shown on UI</description>
    <label>Due Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/loan__Loan_account_Due_Details__c/fields/loan__Fees_Billed__c.field-meta.xml
<CustomField>
    <fullName>loan__Fees_Billed__c</fullName>
    <label>Billed Fees</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/loan__Loan_account_Due_Details__c/fields/loan__Fees_Due__c.field-meta.xml
<CustomField>
    <fullName>loan__Fees_Due__c</fullName>
    <inlineHelpText>Fees due in this billing cycle</inlineHelpText>
    <label>Fees Due</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/loan__Loan_account_Due_Details__c/fields/loan__Fees_Paid__c.field-meta.xml
<CustomField>
    <fullName>loan__Fees_Paid__c</fullName>
    <label>Paid Fees</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/loan__Loan_account_Due_Details__c/fields/loan__Interest_Billed__c.field-meta.xml
<CustomField>
    <fullName>loan__Interest_Billed__c</fullName>
    <label>Billed Interest (=)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/loan__Loan_account_Due_Details__c/fields/loan__Interest_Due__c.field-meta.xml
<CustomField>
    <fullName>loan__Interest_Due__c</fullName>
    <inlineHelpText>Interest due in this billing cycle</inlineHelpText>
    <label>Interest Due</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/loan__Loan_account_Due_Details__c/fields/loan__Interest_Paid__c.field-meta.xml
<CustomField>
    <fullName>loan__Interest_Paid__c</fullName>
    <label>Paid Interest</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/loan__Loan_account_Due_Details__c/fields/loan__Late_Charge_Applied__c.field-meta.xml
<CustomField>
    <fullName>loan__Late_Charge_Applied__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Late Charge Applied</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/loan__Loan_account_Due_Details__c/fields/loan__Loan_Account__c.field-meta.xml
<CustomField>
    <fullName>loan__Loan_Account__c</fullName>
    <label>Loan Account</label>
    <referenceTo>loan__Loan_Account__c</referenceTo>
    <relationshipName>Dues_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/loan__Loan_account_Due_Details__c/fields/loan__Payment_Amt__c.field-meta.xml
<CustomField>
    <fullName>loan__Payment_Amt__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Payment Amount.</description>
    <label>Payment Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/loan__Loan_account_Due_Details__c/fields/loan__Payment_Date__c.field-meta.xml
<CustomField>
    <fullName>loan__Payment_Date__c</fullName>
    <description>Payment Date.</description>
    <label>Payment Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/loan__Loan_account_Due_Details__c/fields/loan__Payment_Satisfied__c.field-meta.xml
<CustomField>
    <fullName>loan__Payment_Satisfied__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Payment Satisfied</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/loan__Loan_account_Due_Details__c/fields/loan__Payoff_Balance__c.field-meta.xml
<CustomField>
    <fullName>loan__Payoff_Balance__c</fullName>
    <inlineHelpText>This field contains the amount needed to payoff the loan after this bill has been generated.</inlineHelpText>
    <label>Payoff Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/loan__Loan_account_Due_Details__c/fields/loan__Principal_Billed__c.field-meta.xml
<CustomField>
    <fullName>loan__Principal_Billed__c</fullName>
    <description>Billed Principal Amount.</description>
    <label>Billed Principal</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/loan__Loan_account_Due_Details__c/fields/loan__Principal_Paid__c.field-meta.xml
<CustomField>
    <fullName>loan__Principal_Paid__c</fullName>
    <label>Paid Principal</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/loan__Loan_account_Due_Details__c/fields/loan__Regular_Interest_Billed__c.field-meta.xml
<CustomField>
    <fullName>loan__Regular_Interest_Billed__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Regular Interest Billed (+)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/loan__Loan_account_Due_Details__c/fields/loan__Remarks__c.field-meta.xml
<CustomField>
    <fullName>loan__Remarks__c</fullName>
    <description>Remarks for bill amount calculation.</description>
    <label>Remarks</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/loan__Loan_account_Due_Details__c/fields/loan__Rescheduled_flag__c.field-meta.xml
<CustomField>
    <fullName>loan__Rescheduled_flag__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If this flag is checked that means this bills was marked as not enabled as part of Rescheduled transaction posted on this loan account.</description>
    <inlineHelpText>If this flag is checked that means this bills was marked as not enabled as part of Rescheduled transaction posted on this loan account.</inlineHelpText>
    <label>Is Rescheduled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/loan__Loan_account_Due_Details__c/fields/loan__Tolerance__c.field-meta.xml
<CustomField>
    <fullName>loan__Tolerance__c</fullName>
    <defaultValue>0.0</defaultValue>
    <description>This is will be populated on billing based on the tolerance rate defined on Loan account.</description>
    <inlineHelpText>Populated from loan account on the basis of tolerance defined.</inlineHelpText>
    <label>Tolerance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/loan__Loan_account_Due_Details__c/fields/loan__Transaction_Date__c.field-meta.xml
<CustomField>
    <fullName>loan__Transaction_Date__c</fullName>
    <description>Transaction date</description>
    <inlineHelpText>Date on which the transaction got created.</inlineHelpText>
    <label>Transaction Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/loan__Loan_account_Due_Details__c/fields/loan__waiver_applied__c.field-meta.xml
<CustomField>
    <fullName>loan__waiver_applied__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Flag to indicate if any applicable waiver  is applied on this bill. Will be set to true when applied</description>
    <label>Waiver Applied</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/MW_RetrieveBillsbyContractId.cls
@RestResource(urlMapping='/bill/contract-id/*')
global with sharing class MW_RetrieveBillsbyContractId {
    @HttpGet
    global static void MW_RetrieveBillsbyContractId() {
        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;
        try {
            String contractId = req.params.get('contract-id');
            if (String.isBlank(contractId)) {
                res.statusCode = 400;
                res.responseBody = Blob.valueOf('contract id is required');
                return;
            }
            List<loan__Loan_account_Due_Details__c> bills = [
                SELECT 
                id,
                Name,
                CreatedDate,
                CreatedById,
                LastModifiedDate,
                LastModifiedById,
                loan__Loan_Account__c,
                loan__Balance_Amount__c,
                loan__Compounding_Interest_Billed__c,
                loan__DD_Primary_Flag__c,
                loan__Due_Amt__c,
                loan__Due_Date__c,
                loan__Due_Type_Description__c,
                loan__Due_Type__c,
                loan__Interest_Billed__c,
                loan__Interest_Paid__c,
                loan__Late_Charge_Applied__c,
                loan__Payment_Amt__c,
                loan__Payment_Date__c,
                loan__Payment_Satisfied__c,
                loan__Principal_Billed__c,
                loan__Principal_Paid__c,
                loan__Regular_Interest_Billed__c,
                loan__Remarks__c,
                loan__Rescheduled_flag__c,
                loan__Tolerance__c,
                loan__Transaction_Date__c,
                loan__Archived__c,
                loan__Balance__c,
                loan__Master_Archive_Object__c,
                loan__Payoff_Balance__c,
                loan__Summary_Record_Id__c,
                loan__Summary__c,
                loan__waiver_applied__c,
                loan__Actual_Tolerance_Amount__c,
                loan__Average_Daily_Balance__c,
                loan__Bill_Cycle_End_Date__c,
                loan__Bill_Cycle_Start_Date__c,
                loan__Closing_Balance__c,
                loan__Fees_Billed__c,
                loan__Fees_Due__c,
                loan__Fees_Paid__c,
                loan__Interest_Due__c,
                loan__Opening_Balance__c,
                loan__Payoff_As_Of_Previous_Bill__c,
                loan__Previous_Bill_Amount__c,
                loan__Satisfied_With_Tolerance__c,
                loan__Total_Amount_Disbursed__c,
                loan__Total_Payments_Received__c,
                loan__Next_Due_Date_Without_Holiday_Treatment__c,
                loan__TDS_Amount_Due__c,
                loan__TDS_Paid_Amount__c,
                loan__TDS_Percentage__c,
                loan__Total_Fees_Waived__c,
                loan__Total_Interest_Waived__c,
                External_Id__c,
                isMigrated__c,
                ToBeDeleted__c
                FROM loan__Loan_account_Due_Details__c
                WHERE loan__Loan_Account__c = :contractId 
            ];
            
            res.statusCode = 200;
            res.responseBody = Blob.valueOf(JSON.serialize(bills));
        }
        catch (Exception e) {
            res.statusCode = 500;
            res.responseBody = Blob.valueOf(e.getMessage());
        }
    }
}