force-app/main/default/objects/loan__Loan_Account__c/loan__Loan_Account__c.object-meta.xml
<CustomObject>
    <description>Lending Account</description>
    <label>CL Contract</label>
    <nameField>
        <displayFormat>LAI-{00000000}</displayFormat>
        <label>CL Contract ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CL Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/loan__Loan_Account__c/fields/loan__Loan_Product_Name__c.field-meta.xml
<CustomField>
    <fullName>loan__Loan_Product_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Loan Product Name</description>
    <inlineHelpText>Please choose a lending product, which will be associated as a lending product on this lending account.
You can choose a existing product from the lookup or create a new product from 
Servicing Configuration-&gt;Product-&gt;Create new lending product</inlineHelpText>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Please select active lending product.</errorMessage>
        <filterItems>
            <field>loan__Loan_Product__c.loan__Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>loan__Loan_Product__c</referenceTo>
    <relationshipName>Loan_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/loan__Reschedule_Option_On_Excess_Payment__c.field-meta.xml
<CustomField>
    <fullName>loan__Reschedule_Option_On_Excess_Payment__c</fullName>
    <description>The option used for rescheduling the loan when an excess payment equal to or more than the excess threshold for reschedule is received. You can reschedule by changing either the payment amount or the tenure of the loan.</description>
    <inlineHelpText>The option used for rescheduling the loan when an excess payment equal to or more than the excess threshold for reschedule is received. You can reschedule by changing either the payment amount or the tenure of the loan.</inlineHelpText>
    <label>Reschedule Option On Excess Payment</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Change Payment Amount</fullName>
            </value>
            <value>
                <fullName>Keep Same Payment Amount</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/loan__Loan_Product__c/loan__Loan_Product__c.object-meta.xml
<CustomObject>
    <description>Lending Product Definition1</description>
    <label>Lending Product</label>
    <nameField>
        <label>Loan Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lending Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/loan__Loan_Product__c/fields/loan__Excess_Threshold_For_Reschedule__c.field-meta.xml
<CustomField>
    <fullName>loan__Excess_Threshold_For_Reschedule__c</fullName>
    <inlineHelpText>Minimum percentage of principal remaining received as excess in a payment, which must trigger a reschedule of the loan.</inlineHelpText>
    <label>Excess Threshold % for Reschedule</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Product__c/fields/loan__Reschedule_Option_on_Excess_Payment__c.field-meta.xml
<CustomField>
    <fullName>loan__Reschedule_Option_on_Excess_Payment__c</fullName>
    <description>The option used for rescheduling the loan when an excess payment equal to or more than the excess threshold for reschedule is received. You can reschedule by changing either the payment amount or the tenure of the loan.</description>
    <inlineHelpText>The option used for rescheduling the loan when an excess payment equal to or more than the excess threshold for reschedule is received. You can reschedule by changing either the payment amount or the tenure of the loan.</inlineHelpText>
    <label>Reschedule Option on Excess Payment</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Change Payment Amount</fullName>
            </value>
            <value>
                <fullName>Keep Same Payment Amount</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/loan__Org_Parameters__c/loan__Org_Parameters__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Org Parameters</label>
</CustomObject>

force-app/main/default/objects/loan__Org_Parameters__c/fields/loan__Disable_Triggers__c.field-meta.xml
<CustomField>
    <fullName>loan__Disable_Triggers__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>This disables all the triggers. It is to be used only while migrating data into the system. It must be disabled otherwise.</inlineHelpText>
    <label>Disable Triggers</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/loan__Org_Parameters__c/fields/loan__Namespace_Prefix__c.field-meta.xml
<CustomField>
    <fullName>loan__Namespace_Prefix__c</fullName>
    <defaultValue>&quot;loan&quot;</defaultValue>
    <description>This is MFiFlex internal.</description>
    <inlineHelpText>This is MFiFlex internal. Do not delete/edit this value.</inlineHelpText>
    <label>Namespace Prefix</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/UpdateRescheduleOptionJob.cls
/*
 * This batch job initializes 'Reschedule option on excess payment' field on lending product and associated loan contracts
 * if 'Excess threshold % for reschedule' is some positive value on lending product
 */
global class UpdateRescheduleOptionJob extends loan.MFiFlexBatchJob {

    global Integer batchSize;
    private static String JOB_NAME = 'Reschedule Option update job';
    private Boolean submitNextJob = false;

    global virtual override void submitNextJob() {
        if(submitNextJob) {
            //do nothing. 
            return;
        }
    }

    global UpdateRescheduleOptionJob() {
        super(JOB_NAME, getLoansForUpdate(null));
        if(batchSize == 0 || batchSize == null) {
            batchSize = 200;
        }
        this.batchSize = batchSize;
    }

    global UpdateRescheduleOptionJob(String query, Integer batchSize) {
        super(JOB_NAME, getLoansForUpdate(query));
        
        system.debug(LoggingLevel.ERROR, 'passed query : ' + query);
        if(batchSize == 0 || batchSize == null) {
            batchSize = 200;
        }
        this.batchSize = batchSize;
    }

    private static String getLoansForUpdate(String query) {
        //Query loans:
        if(query == null || query.length() == 0) {
            query = 'SELECT Id,' +
                    '       Name,' +
                    '       loan__Reschedule_Option_On_Excess_Payment__c,' +
                    '       loan__Loan_Product_Name__c,'+
                    '       loan__Loan_Product_Name__r.loan__Excess_Threshold_For_Reschedule__c,' +
                    '       loan__Loan_Product_Name__r.loan__Reschedule_Option_On_Excess_Payment__c ' +
                    'FROM loan__Loan_Account__c '+
                    'WHERE loan__Loan_Product_Name__r.loan__Excess_Threshold_For_Reschedule__c > 0 ' +
                    'AND loan__Reschedule_Option_On_Excess_Payment__c = NULL ';

            system.debug(LoggingLevel.ERROR, 'new query : ' + query);
            return query;
        }
        else {
            return query;
        }
    }

    global override void doStart(Database.BatchableContext bc) {

        disableTriggers();

        List<loan__Loan_Product__c> loanProducts = [SELECT Id,
                                                    Name,
                                                    loan__Reschedule_Option_On_Excess_Payment__c
                                             FROM loan__Loan_Product__c
                                             WHERE loan__Excess_Threshold_For_Reschedule__c > 0
                                                 AND loan__Reschedule_Option_On_Excess_Payment__c = NULL
                                            ];
        updateLoanProducts(loanProducts);
        enableTriggers();
    }

    global override void doExecute(Database.BatchableContext bc, List<sObject> scope) {

        disableTriggers();

        List<loan__Loan_Account__c> loanAccountList = (List<loan__Loan_Account__c>)scope;
        updateLoanAccounts(loanAccountList);
        if (loanAccountList != null && loanAccountList.size() > 0) {
            update loanAccountList;
        }
        enableTriggers();
    }

    @TestVisible
    public void updateLoanProducts(List<loan__Loan_Product__c> loanProducts) {
        system.debug(LoggingLevel.ERROR, ' Loan Products size : ' + loanProducts.size());
        if (loanProducts != null && loanProducts.size() > 0) {
            for (loan__Loan_Product__c loanProduct : loanProducts) {
                system.debug(LoggingLevel.ERROR, 'loanProduct : ' + loanProduct);
                loanProduct.loan__Reschedule_Option_On_Excess_Payment__c = loan.LoanConstants.LOAN_RESCHEDULE_TERM_CHANGE;
            }
            update loanProducts;
        }
    }

    @TestVisible
    public void updateLoanAccounts(List<loan__Loan_Account__c> loanAccountList) {
        system.debug(LoggingLevel.ERROR, 'loanAccounts size : ' + loanAccountList.size());
        for (loan__Loan_Account__c loanAccount : loanAccountList) {
            system.debug(LoggingLevel.ERROR, 'loanAccount : ' + loanAccount);
            if (loanAccount.loan__Loan_Product_Name__r.loan__Excess_Threshold_For_Reschedule__c != null
                && loanAccount.loan__Loan_Product_Name__r.loan__Excess_Threshold_For_Reschedule__c > 0
                && (loanAccount.loan__Reschedule_Option_On_Excess_Payment__c == null
                    || loanAccount.loan__Reschedule_Option_On_Excess_Payment__c == '')) {

                //in case reschedule option is present on lending product of loan, then copy its value otherwise make it default to 'Keep Same Payment Amount'
                if (loanAccount.loan__Loan_Product_Name__r.loan__Reschedule_Option_On_Excess_Payment__c != null) {
                    loanAccount.loan__Reschedule_Option_On_Excess_Payment__c = loanAccount.loan__Loan_Product_Name__r.loan__Reschedule_Option_On_Excess_Payment__c;
                }
                else {
                    loanAccount.loan__Reschedule_Option_On_Excess_Payment__c = loan.LoanConstants.LOAN_RESCHEDULE_TERM_CHANGE;
                }
            }
        }
    }

    global override void doFinish(Database.BatchableContext bc) {} //does nothing

    private void disableTriggers() {
        loan__Org_Parameters__c orgParams = loan.CustomSettingsUtil.getOrgParameters();
        orgParams.loan__Namespace_Prefix__c = 'loan';
        orgParams.loan__Disable_Triggers__c = true;
        upsert orgParams;
    }

    private void enableTriggers() {
        loan__Org_Parameters__c orgParams = loan.CustomSettingsUtil.getOrgParameters();
        orgParams.loan__Namespace_Prefix__c = 'loan';
        orgParams.loan__Disable_Triggers__c = false;
        update orgParams;
    }
}