unpackaged/main/default/objects/Application_Tags__c/Application_Tags__c.object-meta.xml
<CustomObject>
    <label>Application Tag</label>
    <nameField>
        <label>Application Tags Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application Tags</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Application_Tags__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <label>Application</label>
    <referenceTo>genesis__Applications__c</referenceTo>
    <relationshipLabel>Application Tags</relationshipLabel>
    <relationshipName>Application_Tags</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Application_Tags__c/fields/Application_Tag__c.field-meta.xml
<CustomField>
    <fullName>Application_Tag__c</fullName>
    <label>Application Tag</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Account in Dispute</fullName>
            </value>
            <value>
                <fullName>Cannabis Review</fullName>
            </value>
            <value>
                <fullName>Confirmed Fraud</fullName>
            </value>
            <value>
                <fullName>DCP Card Verifications Failed</fullName>
            </value>
            <value>
                <fullName>E-Sign Redecision</fullName>
            </value>
            <value>
                <fullName>Follow-Up</fullName>
            </value>
            <value>
                <fullName>Fraud</fullName>
            </value>
            <value>
                <fullName>Fraud Awaiting Action</fullName>
            </value>
            <value>
                <fullName>Fraud F/U</fullName>
            </value>
            <value>
                <fullName>Fraud Hold</fullName>
            </value>
            <value>
                <fullName>Fraud Reviewed Declined</fullName>
            </value>
            <value>
                <fullName>Fraud RFP</fullName>
            </value>
            <value>
                <fullName>Fraud To-Do</fullName>
            </value>
            <value>
                <fullName>Hot List</fullName>
            </value>
            <value>
                <fullName>Identity</fullName>
            </value>
            <value>
                <fullName>Issues</fullName>
            </value>
            <value>
                <fullName>Manual Fraud Review</fullName>
            </value>
            <value>
                <fullName>Max OB</fullName>
            </value>
            <value>
                <fullName>Needs Approval</fullName>
            </value>
            <value>
                <fullName>Needs Review</fullName>
            </value>
            <value>
                <fullName>New Documents</fullName>
            </value>
            <value>
                <fullName>New Interaction</fullName>
            </value>
            <value>
                <fullName>Non-Resident</fullName>
            </value>
            <value>
                <fullName>Not Moving Forward</fullName>
            </value>
            <value>
                <fullName>Pending 9012</fullName>
            </value>
            <value>
                <fullName>Pending 9013</fullName>
            </value>
            <value>
                <fullName>Pending Docs</fullName>
            </value>
            <value>
                <fullName>Pending EmpInfo</fullName>
            </value>
            <value>
                <fullName>Pending Fraud Call</fullName>
            </value>
            <value>
                <fullName>Pending Info</fullName>
            </value>
            <value>
                <fullName>Soft Pull Requested.</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/genesis__Applications__c/genesis__Applications__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{0000000000}</displayFormat>
        <label>Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/genesis__Applications__c/fields/DocuSignFlag__c.field-meta.xml
<CustomField>
    <fullName>DocuSignFlag__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Checked - DocuSign Email sent</description>
    <label>DocuSignFlag</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/genesis__Applications__c/fields/genesis__Description__c.field-meta.xml
<CustomField>
    <fullName>genesis__Description__c</fullName>
    <label>Description</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

unpackaged/main/default/objects/genesis__Applications__c/fields/genesis__Loan_Amount__c.field-meta.xml
<CustomField>
    <fullName>genesis__Loan_Amount__c</fullName>
    <label>Loan Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/genesis__Applications__c/fields/genesis__Status__c.field-meta.xml
<CustomField>
    <fullName>genesis__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>APPROVED - APPROVED</fullName>
            </value>
            <value>
                <fullName>APPROVED - CONVERTED TO CONTRACT</fullName>
            </value>
            <value>
                <fullName>APPROVED - DOCUMENT CHECK</fullName>
            </value>
            <value>
                <fullName>NEW - CREDIT PULLED</fullName>
            </value>
            <value>
                <fullName>NEW - ENTERED</fullName>
                <default>true</default>
                <label>NEW - ENTERED</label>
            </value>
            <value>
                <fullName>NEW - IN CREDIT CHECK</fullName>
            </value>
            <value>
                <fullName>NEW - IN REVIEW</fullName>
            </value>
            <value>
                <fullName>NEW - PRICING GENERATED</fullName>
            </value>
            <value>
                <fullName>NEW - SCORECARD GENERATED</fullName>
            </value>
            <value>
                <fullName>NEW - CHECKLIST GENERATED</fullName>
            </value>
            <value>
                <fullName>NEW - VEHICLE VALUATION REQUIRED</fullName>
            </value>
            <value>
                <fullName>REJECTED</fullName>
            </value>
            <value>
                <fullName>PULL CREDIT</fullName>
            </value>
            <value>
                <fullName>Default Documents</fullName>
            </value>
            <value>
                <fullName>offer_accepted</fullName>
            </value>
            <value>
                <fullName>offer_shown</fullName>
            </value>
            <value>
                <fullName>kba_success</fullName>
            </value>
            <value>
                <fullName>kba_fail</fullName>
            </value>
            <value>
                <fullName>agent_document_verification_pending</fullName>
            </value>
            <value>
                <fullName>agent_verification_pending</fullName>
            </value>
            <value>
                <fullName>agent_verified</fullName>
            </value>
            <value>
                <fullName>docusign_loan_docs_sent</fullName>
            </value>
            <value>
                <fullName>docusign_loan_docs_complete</fullName>
            </value>
            <value>
                <fullName>pre_funding</fullName>
            </value>
            <value>
                <fullName>Approved for funding</fullName>
            </value>
            <value>
                <fullName>funded</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Stacker_Check_Passed</fullName>
            </value>
            <value>
                <fullName>Redecision_Required</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/genesis__Applications__c/fields/Lead_ID__c.field-meta.xml
<CustomField>
    <fullName>Lead_ID__c</fullName>
    <description>This is the LEAD GUID received from FE</description>
    <externalId>true</externalId>
    <label>Lead ID</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/genesis__Applications__c/fields/Manual_Soft_Pull__c.field-meta.xml
<CustomField>
    <fullName>Manual_Soft_Pull__c</fullName>
    <defaultValue>false</defaultValue>
    <description>check if manual soft pull has been completed</description>
    <label>Manual Soft Pull</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/genesis__Applications__c/fields/Stacker_Reviewed__c.field-meta.xml
<CustomField>
    <fullName>Stacker_Reviewed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Stacker Reviewed</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/genesis__Applications__c/fields/User_Outbounder__c.field-meta.xml
<CustomField>
    <fullName>User_Outbounder__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>user assigned as Outbounder on application</description>
    <label>User_Outbounder</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Applications1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/genesis__Applications__c/fields/User_PreChecker__c.field-meta.xml
<CustomField>
    <fullName>User_PreChecker__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>user assigned as pre-checker to application</description>
    <label>User_PreChecker</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/lead_id__c.field-meta.xml
<CustomField>
    <fullName>lead_id__c</fullName>
    <externalId>true</externalId>
    <label>lead_id</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/loan__Batch_Process_Log__c/loan__Batch_Process_Log__c.object-meta.xml
<CustomObject>
    <label>Batch Process Log</label>
    <nameField>
        <label>Apex Batch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Batch Process Log</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/loan__Batch_Process_Log__c/fields/loan__Message__c.field-meta.xml
<CustomField>
    <fullName>loan__Message__c</fullName>
    <label>Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Payoff_Endpoint__mdt/Payoff_Endpoint__mdt.object-meta.xml
<CustomObject>
    <description>This will contains all Pay Off end points which are used in this application. Please make sure always working end point or else code will raise exceptions.</description>
    <label>Payoff Endpoints</label>
    <pluralLabel>Payoff_Endpoints</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/Payoff_Endpoint__mdt/fields/EndPointURL__c.field-meta.xml
<CustomField>
    <fullName>EndPointURL__c</fullName>
    <label>EndPointURL</label>
    <type>Url</type>
</CustomField>

unpackaged/main/default/objects/Payoff_Endpoint__mdt/fields/UserName__c.field-meta.xml
<CustomField>
    <fullName>UserName__c</fullName>
    <label>UserName</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/PayOff_Integrations__c/PayOff_Integrations__c.object-meta.xml
<CustomObject>
    <label>PayOff Integration failure logs</label>
    <nameField>
        <displayFormat>Callout-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PayOff_Integrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/PayOff_Integrations__c/fields/ErrorMsg__c.field-meta.xml
<CustomField>
    <fullName>ErrorMsg__c</fullName>
    <label>ErrorMsg</label>
    <length>131070</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/PayOff_Integrations__c/fields/RunningUser__c.field-meta.xml
<CustomField>
    <fullName>RunningUser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>PayOff_Integrations</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Pricing_Offer__c/Pricing_Offer__c.object-meta.xml
<CustomObject>
    <label>Pricing Offer</label>
    <nameField>
        <label>Pricing Offer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pricing Offer</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Pricing_Offer__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <description>/Changed on 16-10-2017 by Sagar Hinsu</description>
    <label>Application</label>
    <referenceTo>genesis__Applications__c</referenceTo>
    <relationshipLabel>Pricing Offer</relationshipLabel>
    <relationshipName>Pricing_Offer</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Pricing_Offer__c/fields/Interest_Rate__c.field-meta.xml
<CustomField>
    <fullName>Interest_Rate__c</fullName>
    <label>Interest Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/objects/Pricing_Offer__c/fields/Is_Offer_Selected__c.field-meta.xml
<CustomField>
    <fullName>Is_Offer_Selected__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Offer Selected</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Pricing_Offer__c/fields/Monthly_Payment__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Payment__c</fullName>
    <label>Monthly Payment</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Pricing_Offer__c/fields/Term__c.field-meta.xml
<CustomField>
    <fullName>Term__c</fullName>
    <label>Term</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/classes/PayOffUtilities.cls
Global class PayOffUtilities{
    
    Static Map<id, recordtype> orgRecordtypes=new Map<id,recordtype>([SELECT Id, Name,  DeveloperName,  SobjectType, IsActive,NamespacePrefix FROM RecordType]);
    
    Public static Id getRecordtypeId(String ObjName,string RtypName,boolean isActive){
        Map<String,id> rtypeid=new Map<string,id>();
        for(recordtype rtype:orgRecordtypes.Values())
            rtypeid.put(rtype.SobjectType+rtype.DeveloperName+rtype.IsActive,rtype.Id);
        return rtypeid.get(ObjName+RtypName+isActive);
    }
    
    Public static String getRecordtypeName(Id rid){
        return orgRecordtypes.get(rid).DeveloperName;
    }
    
    Public static PayOff_Integrations__c createLog(Exception e){
        PayOff_Integrations__c log=new PayOff_Integrations__c(ErrorMsg__c=e.getMessage()+'_'+e.getStackTraceString(),RunningUser__c=UserInfo.getUserId());
        return log;
    }
    
    Public static  Map<string,Payoff_Endpoint__mdt> getEndpoint(String ApiName){
        Map<string,Payoff_Endpoint__mdt> endpointMap = new Map<string,Payoff_Endpoint__mdt>();
        for(Payoff_Endpoint__mdt cls: [SELECT Id, DeveloperName, UserName__c, EndPointURL__c FROM Payoff_Endpoint__mdt where DeveloperName=:ApiName])
            endpointMap.put(cls.DeveloperName,cls);
        
        return endpointMap;
    }
    
    Webservice Static String AssignToMXQueue(id appId) {
        try{
            
            genesis__Applications__c application= [SELECT id,genesis__Status__c,genesis__Description__c 
                                                   FROM  genesis__Applications__c 
                                                   WHERE id =: appId];
            
            List<QueueSobject> lstQueues = [SELECT Queue.Id,queue.Name, QueueId FROM QueueSobject 
                                            WHERE SobjectType = 'genesis__Applications__c' 
                                            AND queue.DeveloperName =: 'MX_Queue'];
            
            application.OwnerId = lstQueues[0].Queue.Id;
            //application.genesis__Status__c = OppLoansConstants.WAITING_TO_SIGN;
            
            update application;       
            return Label.SUBMITTED_TO_MX_QUEUE;
            
        }catch(Exception ex){
            loan__batch_process_log__c logs = new loan__batch_process_log__c(loan__Message__c='Error in assignToUnderwriterQueue:  '+ex.getlinenumber()+'Error: '+ex.getMessage());
            insert logs;
            return 'Exception: '+ex.getMessage(); 
        }
    } 
    
    Webservice Static String AssignToFraudQueue(id appId) {
        try{
            
            genesis__Applications__c application= [SELECT id,genesis__Status__c,genesis__Description__c 
                                                   FROM  genesis__Applications__c 
                                                   WHERE id =: appId];
            
            List<QueueSobject> lstQueues = [SELECT Queue.Id,queue.Name, QueueId FROM QueueSobject 
                                            WHERE SobjectType = 'genesis__Applications__c' 
                                            AND queue.DeveloperName =: 'Fraud_Queue'];
            
            application.OwnerId = lstQueues[0].Queue.Id;
            update application;       
            return Label.SUBMITTED_TO_FRAUD_QUEUE;
            
        }catch(Exception ex){
            loan__batch_process_log__c logs = new loan__batch_process_log__c(loan__Message__c='Error in assignToUnderwriterQueue:  '+ex.getlinenumber()+'Error: '+ex.getMessage());
            insert logs;
            return 'Exception: '+ex.getMessage(); 
        }
    } 
    
    Webservice Static String AssignToVerificationQueue(id appId) {
        try{
            
    
            
            genesis__Applications__c application= [SELECT id,genesis__Status__c,genesis__Description__c 
                                                   FROM  genesis__Applications__c 
                                                   WHERE id =: appId];
            
            List<QueueSobject> lstQueues = [SELECT Queue.Id,queue.Name, QueueId FROM QueueSobject 
                                            WHERE SobjectType = 'genesis__Applications__c' 
                                            AND queue.DeveloperName =: 'Verification_Queue'];
            
            application.OwnerId = lstQueues[0].Queue.Id;
            
            update application;       
            return Label.ASSIGNED_TO_VERIFICATION_QUEUE;
            
        }catch(Exception ex){
            loan__batch_process_log__c logs = new loan__batch_process_log__c(loan__Message__c='Error in assignToUnderwriterQueue:  '+ex.getlinenumber()+'Error: '+ex.getMessage());
            insert logs;
            return 'Exception: '+ex.getMessage(); 
        }
    } 
    
    Webservice Static String AssignToFundingQueue(id appId) {
        try{
            
            genesis__Applications__c application= [SELECT id,genesis__Status__c,genesis__Description__c 
                                                   FROM  genesis__Applications__c 
                                                   WHERE id =: appId];
            
            List<QueueSobject> lstQueues = [SELECT Queue.Id,queue.Name, QueueId FROM QueueSobject 
                                            WHERE SobjectType = 'genesis__Applications__c' 
                                            AND queue.DeveloperName =: 'Pre_Funding_Queue'];
            
            application.OwnerId = lstQueues[0].Queue.Id;
            application.genesis__Status__c = 'pre_funding';
            
            update application;       
            return 'Assigned to Funding Queue';
            
        }catch(Exception ex){
            loan__batch_process_log__c logs = new loan__batch_process_log__c(loan__Message__c='Error in assignToUnderwriterQueue:  '+ex.getlinenumber()+'Error: '+ex.getMessage());
            insert logs;
            return 'Exception: '+ex.getMessage(); 
        }
    } 
    
    Webservice Static String AssignToDeclinedQueue(id appId) {
        try{
            string SetQueue = 'Declined';
            genesis__Applications__c application= [SELECT id,genesis__Status__c,genesis__Description__c 
                                                   FROM  genesis__Applications__c 
                                                   WHERE id =: appId];
            
            List<QueueSobject> lstQueues = [SELECT Queue.Id,queue.Name, QueueId FROM QueueSobject 
                                            WHERE SobjectType = 'genesis__Applications__c' 
                                            AND queue.Name =: SetQueue ];
            
            application.OwnerId = lstQueues[0].Queue.Id;
            
            update application;  
            //--Added on 24.01.2018 for Adverse Action Mail
            //AdverseScorectrl.Adversefuturemethod(appId);                 
            AttachPDFtoApplication.SaveAttachment(appId,true,true); 
            //---    
            return Label.ASSIGNED_TO_DECLINED_QUEUE;
            
        }catch(Exception ex){
            loan__batch_process_log__c logs = new loan__batch_process_log__c(loan__Message__c='Error in assignToUnderwriterQueue:  '+ex.getlinenumber()+'Error: '+ex.getMessage());
            insert logs;
            return 'Exception: '+ex.getMessage(); 
        }
    }
    
    Webservice Static String AssignToDeclinedQueueStatus(id appId,String status) {
        try{
            string SetQueue = 'Declined';
            genesis__Applications__c application= [SELECT id,genesis__Status__c,genesis__Description__c 
                                                   FROM  genesis__Applications__c 
                                                   WHERE id =: appId];
            
            List<QueueSobject> lstQueues = [SELECT Queue.Id,queue.Name, QueueId FROM QueueSobject 
                                            WHERE SobjectType = 'genesis__Applications__c' 
                                            AND queue.Name =: SetQueue ];
            
            application.OwnerId = lstQueues[0].Queue.Id;
            application.genesis__status__c = status;
            update application;  
            //--Added on 24.01.2018 for Adverse Action Mail
            //AdverseScorectrl.Adversefuturemethod(appId);                 
            AttachPDFtoApplication.SaveAttachment(appId,true,true); 
            //---    
            return Label.ASSIGNED_TO_DECLINED_QUEUE;
            
        }catch(Exception ex){
            loan__batch_process_log__c logs = new loan__batch_process_log__c(loan__Message__c='Error in assignToUnderwriterQueue:  '+ex.getlinenumber()+'Error: '+ex.getMessage());
            insert logs;
            return 'Exception: '+ex.getMessage(); 
        }
    }
 
    Webservice Static String AssignToAgentVerifiedQueue(id appId) {
      try{
          string SetQueue = 'Agent_Verified';
          genesis__Applications__c application = [SELECT id, name, genesis__Status__c, genesis__Description__c,
                                                     genesis__Loan_Amount__c,DocuSignFlag__c, Lead_ID__c, 
                                              ( SELECT id, Interest_Rate__c, Term__c, Monthly_Payment__c,amount__c 
                                                FROM pricing_Offer__r WHERE Is_Offer_Selected__c = TRUE)
                                              FROM genesis__Applications__c WHERE id = :appId];
          List<QueueSobject> lstQueues = [SELECT Queue.Id,queue.Name, QueueId FROM QueueSobject
                                          WHERE SobjectType = 'genesis__Applications__c' 
                                          AND queue.DeveloperName =: SetQueue ];
          if (application.pricing_Offer__r.size() > 0) {
                      if ( //Assuming Offer Selected and DQ Checks not passed 
                            Application.pricing_Offer__r[0].amount__c == null ||
                            Application.pricing_Offer__r[0].Interest_Rate__c == null ||
                            Application.pricing_Offer__r[0].Term__c == null ||
                            Application.pricing_Offer__r[0].Monthly_Payment__c == null ||
                            Application.pricing_Offer__r[0].amount__c == 0 ||
                            Application.pricing_Offer__r[0].Interest_Rate__c == 0 ||
                            Application.pricing_Offer__r[0].Term__c == 0 ||
                            Application.pricing_Offer__r[0].Monthly_Payment__c == 0){

                                OrgWideEmailAddress emailid = [select Id from OrgWideEmailAddress where DisplayName = 'PayOff' LIMIT 1];
                                
                                String body = '<p> The data quality check for your application : '+ application.name +', Lead : '+application.Lead_ID__c+ ' has failed at Agent Verify. <br/>';
                                body += 'Below are the values of fields to be reviewed. <br/>';
                                body += 'Loan Amount : ' + Application.pricing_Offer__r[0].amount__c +'<br/>';
                                body += 'Interest Rate: '+ Application.pricing_Offer__r[0].Interest_Rate__c +'<br/>';
                                body += 'Term: '+ Application.pricing_Offer__r[0].Term__c +'<br/>';
                                body += 'Monthly Payment: '+ Application.pricing_Offer__r[0].Monthly_Payment__c +'<br/>';
                                body += 'Please make sure to correct the above fields. Thank you. </p>';
                                
                                system.debug('Email Body :'+ body);

                                List<Messaging.SingleEmailMessage> mails = new List<Messaging.SingleEmailMessage>();
                                Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
                                List<String> sendTo = Label.jira_email.split(';');
                                mail.setToAddresses(sendTo);
                                mail.setOrgWideEmailAddressId(emailid.id);
                                mail.setSubject(application.name + ' Offer Data Missing for Agent Verify');
                                mail.setHtmlBody(body);
                                mails.add(mail);
                                Messaging.sendEmail(mails); 
                                

                                return AssignToReviewQueue(application.id);
                          } else {
                                        application.OwnerId = lstQueues[0].Queue.Id;
                                        application.genesis__Status__c = 'agent_verified';
                                        application.DocuSignFlag__c = true;
                                        update application;
                                        return Label.ASSIGNED_TO_AGENT_VERIFIED_QUEUE;
                          }
          } else{
              return 'Offer is not Selected';
            }
      }catch(Exception ex){
          loan__batch_process_log__c logs = new loan__batch_process_log__c(loan__Message__c='Error in assignToUnderwriterQueue:  '+ex.getlinenumber()+'Error: '+ex.getMessage());
          insert logs;
          return 'Exception: ' +ex.getMessage();
      }
  }


    

Webservice Static String AssignToReviewQueue(id appId) {
        try{
            string SetQueue = 'Review_Queue';
            genesis__Applications__c application= [SELECT id,genesis__Status__c,genesis__Description__c 
                                                   FROM  genesis__Applications__c 
                                                   WHERE id =: appId];
            
            List<QueueSobject> lstQueues = [SELECT Queue.Id,queue.Name, QueueId FROM QueueSobject 
                                            WHERE SobjectType = 'genesis__Applications__c' 
                                            AND queue.DeveloperName =: SetQueue ];
            
            application.OwnerId = lstQueues[0].Queue.Id;
            
            update application;
            return Label.Assign_To_Review_Queue ;
            
        }catch(Exception ex){
            loan__batch_process_log__c logs = new loan__batch_process_log__c(loan__Message__c='Error in assignToReviewQueue:  '+ex.getlinenumber()+'Error: '+ex.getMessage());
            insert logs;
            return 'Exception: '+ex.getMessage();
                    }
    }
            
 Webservice Static String AssignToUser(id appId) {
        try{
            string SetQueue = UserInfo.getUserId();
            genesis__Applications__c application= [SELECT id,genesis__Status__c,genesis__Description__c 
                                                   FROM  genesis__Applications__c 
                                                   WHERE id =: appId];
            

            
            application.OwnerId = UserInfo.getUserId();
            
            update application;
            return Label.Assigned_to_User;
            
        }catch(Exception ex){
            loan__batch_process_log__c logs = new loan__batch_process_log__c(loan__Message__c='Error in assignToUser:  '+ex.getlinenumber()+'Error: '+ex.getMessage());
            insert logs;
            return 'Exception: '+ex.getMessage(); 
        }
    }

 Webservice Static String AssignToUserPreCheck(id appId) {
        try{
            string SetQueue = UserInfo.getUserId();
            genesis__Applications__c application= [SELECT id,genesis__Status__c,genesis__Description__c, user_prechecker__c 
                                                   FROM  genesis__Applications__c 
                                                   WHERE id =: appId];
                                                   
                                                   
            List<QueueSobject> lstQueues = [SELECT Queue.Id,queue.Name, QueueId FROM QueueSobject 
                                            WHERE SobjectType = 'genesis__Applications__c' 
                                            AND queue.DeveloperName = 'Pre_Checker_Queue' ];
            

            
            application.user_prechecker__c = UserInfo.getUserId();
            application.OwnerId = lstQueues[0].Queue.Id;
            
            update application;
            return Label.Assigned_to_PreChecker;
            
        }catch(Exception ex){
            loan__batch_process_log__c logs = new loan__batch_process_log__c(loan__Message__c='Error in assignToUser:  '+ex.getlinenumber()+'Error: '+ex.getMessage());
            insert logs;
            return 'Exception: '+ex.getMessage(); 
        }
    }
    
 Webservice Static String AssignToUserOutbounder(id appId) {
        try{
            string SetQueue = UserInfo.getUserId();
            genesis__Applications__c application= [SELECT id,genesis__Status__c,genesis__Description__c, user_outbounder__c 
                                                   FROM  genesis__Applications__c 
                                                   WHERE id =: appId];
            
            List<QueueSobject> lstQueues = [SELECT Queue.Id,queue.Name, QueueId FROM QueueSobject 
                                            WHERE SobjectType = 'genesis__Applications__c' 
                                            AND queue.DeveloperName = 'Outbounder_Queue' ];
            
            application.OwnerId = lstQueues[0].Queue.Id;
            
            application.user_outbounder__c= UserInfo.getUserId();
            
            update application;
            return Label.Assigned_to_Outbounder;
            
        }catch(Exception ex){
            loan__batch_process_log__c logs = new loan__batch_process_log__c(loan__Message__c='Error in assignToUser:  '+ex.getlinenumber()+'Error: '+ex.getMessage());
            insert logs;
            return 'Exception: '+ex.getMessage(); 
        }
    }    
    
    
     Webservice Static String createAppTagforSoftpull(id appId) {
         genesis__Applications__c application= [SELECT id,
                                                     genesis__Status__c,
                                                     genesis__Description__c,
                                                     Stacker_reviewed__c,
                                                     Manual_Soft_Pull__c
                                                   FROM  genesis__Applications__c 
                                                   WHERE id =: appId];
         application.Stacker_reviewed__c = False;
         application.Manual_Soft_Pull__c = True;
         Application_Tags__c at = new Application_Tags__c();
         at.Application_Tag__c = 'Soft Pull Requested.';
         at.Application__c = appId;
         System.debug('****POUTIL:::'+appId);
         MW_WebhookHandler.generateSoftPullJson(appId);
         insert at;
         update application;
         return 'Soft Pull Requested';
         
     }
 Webservice Static String AssignToFinalVerificationQueue(id appId) {
        try{
            string SetQueue = 'Final_Verification';
            genesis__Applications__c application= [SELECT id,genesis__Status__c,genesis__Description__c 
                                                   FROM  genesis__Applications__c 
                                                   WHERE id =: appId];
            
            List<QueueSobject> lstQueues = [SELECT Queue.Id,queue.Name, QueueId FROM QueueSobject 
                                            WHERE SobjectType = 'genesis__Applications__c' 
                                            AND queue.DeveloperName =: SetQueue ];
            
            application.OwnerId = lstQueues[0].Queue.Id;
            
            update application;
            return Label.Assigned_to_Final_Verification_Queue;
            
        }catch(Exception ex){
            loan__batch_process_log__c logs = new loan__batch_process_log__c(loan__Message__c='Error in assignToFinalVerificationQueue:  '+ex.getlinenumber()+'Error: '+ex.getMessage());
            insert logs;
            return 'Exception: '+ex.getMessage(); 
        }
        }
             
 Webservice Static String AssignToWithdrawnQueue(id appId) {
        try{
            string SetQueue = 'Withdrawn_Queue';
            genesis__Applications__c application= [SELECT id,genesis__Status__c,genesis__Description__c 
                                                   FROM  genesis__Applications__c 
                                                   WHERE id =: appId];
            
            List<QueueSobject> lstQueues = [SELECT Queue.Id,queue.Name, QueueId FROM QueueSobject 
                                            WHERE SobjectType = 'genesis__Applications__c' 
                                            AND queue.DeveloperName =: SetQueue ];
            
            application.OwnerId = lstQueues[0].Queue.Id;
            
            update application;
            return Label.Assigned_to_Withdrawn_Queue;
            
        }catch(Exception ex){
            loan__batch_process_log__c logs = new loan__batch_process_log__c(loan__Message__c='Error in assignToWithdrawnQueue:  '+ex.getlinenumber()+'Error: '+ex.getMessage());
            insert logs;
            return 'Exception: '+ex.getMessage(); 
        }
        }

 Webservice Static String WorkEmailVerify(id appId) {
        try{
            list <genesis__Employment_Information__c> WorkEmail= [select id, Send_work_email_verification_Email__c,Work_Email__c 
                                                           from genesis__Employment_Information__c 
                                                           where genesis__Application__c =: appID and Work_Email__c  != null and Work_Email__c  !='' limit 1];
             WorkEmail[0].Send_work_email_verification_Email__c =True;         
            update WorkEmail;
            return Label.WorkEmailVerify;
            
        }catch(Exception ex){
            loan__batch_process_log__c logs = new loan__batch_process_log__c(loan__Message__c='Error in WorkEmailVerify:  '+ex.getlinenumber()+'Error: '+ex.getMessage());
            insert logs;
            return 'Exception: '+ex.getMessage(); 
        }
        }     

    
    @InvocableMethod
    public static void AssignToConsentQueue(List<id> appId) {
        try{
            
            List<genesis__Applications__c> application= [SELECT id,genesis__Status__c,genesis__Description__c 
                                                   FROM  genesis__Applications__c 
                                                   WHERE id In: appId];
            
            List<QueueSobject> lstQueues = [SELECT Queue.Id,queue.Name, QueueId FROM QueueSobject 
                                            WHERE SobjectType = 'genesis__Applications__c' 
                                            AND queue.DeveloperName =: 'Review_Queue'];
            
            for(genesis__Applications__c app:application)
                app.OwnerId = lstQueues[0].Queue.Id;
            //application.genesis__Status__c = 'pre_funding';
            
            update application;       
            //return 'Assigned to Funding Queue';
            
        }catch(Exception ex){
            loan__batch_process_log__c logs = new loan__batch_process_log__c(loan__Message__c='Error in assignToUnderwriterQueue:  '+ex.getlinenumber()+'Error: '+ex.getMessage());
            insert logs;
            //return 'Exception: '+ex.getMessage(); 
        }
    }
    Webservice Static String DeleteAppTagforSoftpull(id appId) {
         //delete [SELECT Id FROM Application_Tags__c WHERE Application__c =: appId AND Application_Tag__c =:'Soft Pull Requested.'];
         List<Application_Tags__c> SoftpullAppTags = new List<Application_Tags__c>();
         SoftpullAppTags = [SELECT Id, softDelete__c FROM Application_Tags__c WHERE Application__c =: appId AND Application_Tag__c =:'Soft Pull Requested.' AND softDelete__c=False];
         For (Application_Tags__c SPapp : SoftpullAppTags){
            SPapp.softDelete__c = True;
              }
            update SoftpullAppTags;  
         return 'Soft Pull Requested tag deleted';
     } 
    
    
     
     


}