force-app/main/default/objects/genesis__Application_Status_History__c/genesis__Application_Status_History__c.object-meta.xml
<CustomObject>
    <label>Application Status History</label>
    <nameField>
        <displayFormat>ASH-{00000000}</displayFormat>
        <label>Application Status History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Status History</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/genesis__Application_Status_History__c/fields/genesis__Application__c.field-meta.xml
<CustomField>
    <fullName>genesis__Application__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Application</label>
    <referenceTo>genesis__Applications__c</referenceTo>
    <relationshipLabel>Application Status History</relationshipLabel>
    <relationshipName>Application_Status_History</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/genesis__Application_Status_History__c/fields/genesis__Changed_On__c.field-meta.xml
<CustomField>
    <fullName>genesis__Changed_On__c</fullName>
    <description>DateTime on which the application status is changed</description>
    <inlineHelpText>DateTime on which the application status is changed</inlineHelpText>
    <label>Changed On</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/genesis__Application_Status_History__c/fields/genesis__Current_Status_Duration__c.field-meta.xml
<CustomField>
    <fullName>genesis__Current_Status_Duration__c</fullName>
    <description>If the application is being process, then how much time in minutes elapsed between NOW and the when the application status was changed, else this will be 0</description>
    <formula>IF( genesis__Is_Latest_Status__c ,ROUND( ( NOW() -  genesis__Changed_On__c ) * 24 , 2) , 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>If the application is being process, then how much time in minutes elapsed between NOW and the when the application status was changed, else this will be 0</inlineHelpText>
    <label>Current Status Duration(till now)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/genesis__Application_Status_History__c/fields/genesis__Is_Latest_Status__c.field-meta.xml
<CustomField>
    <fullName>genesis__Is_Latest_Status__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If the application is being processes and it is the most recent status change record, then its true else false. This value is set based on the values provided in Closed Status in Org Parameters.</description>
    <inlineHelpText>If the application is being processes and it is the most recent status change record, then its true else false. This value is set based on the values provided in Closed Status in Org Parameters.</inlineHelpText>
    <label>Is Latest Status</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/genesis__Application_Status_History__c/fields/genesis__New_Value__c.field-meta.xml
<CustomField>
    <fullName>genesis__New_Value__c</fullName>
    <description>New Status of application</description>
    <inlineHelpText>New Status of application</inlineHelpText>
    <label>New Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/genesis__Application_Status_History__c/fields/genesis__Old_value__c.field-meta.xml
<CustomField>
    <fullName>genesis__Old_value__c</fullName>
    <description>Old Status of application</description>
    <inlineHelpText>Old Status of application</inlineHelpText>
    <label>Old Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/genesis__Application_Status_History__c/fields/UpdatedByHMMW__c.field-meta.xml
<CustomField>
    <fullName>UpdatedByHMMW__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used for LOS 215 to flag records updated by Happymoney</description>
    <label>UpdatedByHMMW</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/genesis__Applications__c/genesis__Applications__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{0000000000}</displayFormat>
        <label>Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/genesis__Applications__c/fields/genesis__Status__c.field-meta.xml
<CustomField>
    <fullName>genesis__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>APPROVED - APPROVED</fullName>
            </value>
            <value>
                <fullName>APPROVED - CONVERTED TO CONTRACT</fullName>
            </value>
            <value>
                <fullName>APPROVED - DOCUMENT CHECK</fullName>
            </value>
            <value>
                <fullName>NEW - CREDIT PULLED</fullName>
            </value>
            <value>
                <fullName>NEW - ENTERED</fullName>
                <default>true</default>
                <label>NEW - ENTERED</label>
            </value>
            <value>
                <fullName>NEW - IN CREDIT CHECK</fullName>
            </value>
            <value>
                <fullName>NEW - IN REVIEW</fullName>
            </value>
            <value>
                <fullName>NEW - PRICING GENERATED</fullName>
            </value>
            <value>
                <fullName>NEW - SCORECARD GENERATED</fullName>
            </value>
            <value>
                <fullName>NEW - CHECKLIST GENERATED</fullName>
            </value>
            <value>
                <fullName>NEW - VEHICLE VALUATION REQUIRED</fullName>
            </value>
            <value>
                <fullName>REJECTED</fullName>
            </value>
            <value>
                <fullName>PULL CREDIT</fullName>
            </value>
            <value>
                <fullName>Default Documents</fullName>
            </value>
            <value>
                <fullName>offer_accepted</fullName>
            </value>
            <value>
                <fullName>offer_shown</fullName>
            </value>
            <value>
                <fullName>kba_success</fullName>
            </value>
            <value>
                <fullName>kba_fail</fullName>
            </value>
            <value>
                <fullName>agent_document_verification_pending</fullName>
            </value>
            <value>
                <fullName>agent_verification_pending</fullName>
            </value>
            <value>
                <fullName>agent_verified</fullName>
            </value>
            <value>
                <fullName>docusign_loan_docs_sent</fullName>
            </value>
            <value>
                <fullName>docusign_loan_docs_complete</fullName>
            </value>
            <value>
                <fullName>pre_funding</fullName>
            </value>
            <value>
                <fullName>Approved for funding</fullName>
            </value>
            <value>
                <fullName>funded</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Stacker_Check_Passed</fullName>
            </value>
            <value>
                <fullName>Redecision_Required</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/MW_BackfillIncorrectTerminalStatuses.cls
global class MW_BackfillIncorrectTerminalStatuses implements Database.batchable<sObject>{
    global string whereClause;
    global string operatn;
    global MW_BackfillIncorrectTerminalStatuses(String whereClause, String operatn){
        this.whereClause = whereClause;
        this.operatn = operatn;
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        String query =  'SELECT Id, Name, genesis__New_Value__c, genesis__Old_value__c, genesis__Is_Latest_Status__c, genesis__Changed_On__c, genesis__Application__c, '+
                        'genesis__Current_Status_Duration__c, UpdatedByHMMW__c FROM genesis__Application_Status_History__c '; 
                        
                        if(whereClause != null){
                           query += whereClause;
                        }
                        system.debug('query========>'+query);
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<genesis__Application_Status_History__c> scope) {
        map<Id,genesis__Applications__c> appMap = new map<Id,genesis__Applications__c>();
        list<genesis__Application_Status_History__c> ashList = new list<genesis__Application_Status_History__c>();
        for(genesis__Application_Status_History__c ash : scope){
            if(!appMap.containsKey(ash.genesis__Application__c)){
                ash.UpdatedByHMMW__c = true;
                ashList.add(ash);
                appMap.put(ash.genesis__Application__c,new genesis__Applications__c(Id=ash.genesis__Application__c,genesis__Status__c = ash.genesis__Old_value__c));
            }else if(operatn == 'Delete' && ash.UpdatedByHMMW__c == true){
                ashList.add(ash);
            }
        }
        system.debug('appMap========>'+appMap.size());
        if(operatn == 'Update'){
            update appMap.values();
            system.debug('ashList update size========>'+ashList.size());
            update ashList;
        }else if(operatn == 'Delete'){
            system.debug('ashList delete size========>'+ashList.size());
            delete ashList;
        }
    }
    
    global void finish(Database.BatchableContext BC) {
    }
}