force-app/main/default/objects/loan__Client__c/loan__Client__c.object-meta.xml
<CustomObject>
    <description>Borrower</description>
    <label>Client</label>
    <nameField>
        <displayFormat>C-{00000000}</displayFormat>
        <label>Client ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/loan__Client__c/fields/loan__Fee_Set__c.field-meta.xml
<CustomField>
    <fullName>loan__Fee_Set__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Fee Set for Client Registration</description>
    <inlineHelpText>Fee Set for Client registration</inlineHelpText>
    <label>Fee Set</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Selected Fee Set&apos;s category must be of type &apos;Client&apos; and it should include at least one fee.</errorMessage>
        <filterItems>
            <field>loan__Fee_Set__c.loan__Fee_Set_Category__c</field>
            <operation>equals</operation>
            <value>Client</value>
        </filterItems>
        <filterItems>
            <field>loan__Fee_Set__c.loan__Number_of_Fees__c</field>
            <operation>notEqual</operation>
            <value>0</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>loan__Fee_Set__c</referenceTo>
    <relationshipLabel>Clients</relationshipLabel>
    <relationshipName>Clients</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/loan__Fee__c/loan__Fee__c.object-meta.xml
<CustomObject>
    <description>Fee</description>
    <label>Fee</label>
    <nameField>
        <label>Fee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/loan__Fee__c/fields/loan__Currency__c.field-meta.xml
<CustomField>
    <fullName>loan__Currency__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Currency</description>
    <inlineHelpText>Currency</inlineHelpText>
    <label>Currency</label>
    <referenceTo>loan__Currency__c</referenceTo>
    <relationshipLabel>Fees</relationshipLabel>
    <relationshipName>Fees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/loan__Fee_Junction__c/loan__Fee_Junction__c.object-meta.xml
<CustomObject>
    <label>Fee Set/Fee</label>
    <nameField>
        <displayFormat>FJIP-{0000000000}</displayFormat>
        <label>Fee Junction ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fee Set/Fee</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/loan__Fee_Junction__c/fields/loan__Fee__c.field-meta.xml
<CustomField>
    <fullName>loan__Fee__c</fullName>
    <label>Fee</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>loan__Fee__c.loan__Time_of_charge__c</field>
            <operation>notEqual</operation>
            <value>Pre-Paid Fees</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>loan__Fee__c</referenceTo>
    <relationshipLabel>Fee Set/Fee</relationshipLabel>
    <relationshipName>Fee_Junction</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/loan__Fee_Junction__c/fields/loan__Fee_Set__c.field-meta.xml
<CustomField>
    <fullName>loan__Fee_Set__c</fullName>
    <label>Fee Set</label>
    <referenceTo>loan__Fee_Set__c</referenceTo>
    <relationshipName>Fee_Junction</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/loan__Loan_Account__c.object-meta.xml
<CustomObject>
    <description>Lending Account</description>
    <label>CL Contract</label>
    <nameField>
        <displayFormat>LAI-{00000000}</displayFormat>
        <label>CL Contract ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CL Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/loan__Loan_Account__c/fields/loan__Client__c.field-meta.xml
<CustomField>
    <fullName>loan__Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Loan Account Owner</description>
    <inlineHelpText>Loan Account Owner</inlineHelpText>
    <label>Client</label>
    <referenceTo>loan__Client__c</referenceTo>
    <relationshipName>Loan_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/loan__Fee_Set__c.field-meta.xml
<CustomField>
    <fullName>loan__Fee_Set__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Fee Set</description>
    <inlineHelpText>Lookup to associate the fee set on this lending account. Only the fees defined within the fee set can be assessed on this contract.
To create a fee set, Servicing configuration-&gt;Product-&gt;Manage fee set</inlineHelpText>
    <label>Fee Set</label>
    <referenceTo>loan__Fee_Set__c</referenceTo>
    <relationshipName>Loan_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Account__c/fields/loan__Loan_Purpose__c.field-meta.xml
<CustomField>
    <fullName>loan__Loan_Purpose__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Loan Purpose</description>
    <inlineHelpText>Loan purpose</inlineHelpText>
    <label>Purpose</label>
    <referenceTo>loan__Loan_Purpose__c</referenceTo>
    <relationshipName>Loan_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Payment_Transaction__c/loan__Loan_Payment_Transaction__c.object-meta.xml
<CustomObject>
    <description>Loan Payment Transaction</description>
    <label>Loan Payment Transaction</label>
    <nameField>
        <displayFormat>LPT-{000000000}</displayFormat>
        <label>Loan Payment Transaction ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loan Payment Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/loan__Loan_Payment_Transaction__c/fields/loan__Loan_Account__c.field-meta.xml
<CustomField>
    <fullName>loan__Loan_Account__c</fullName>
    <description>Loan Account</description>
    <inlineHelpText>Loan Account</inlineHelpText>
    <label>Loan Account</label>
    <referenceTo>loan__Loan_Account__c</referenceTo>
    <relationshipLabel>Loan Payment Transactions</relationshipLabel>
    <relationshipName>Loan_Payment_Transactions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Product__c/loan__Loan_Product__c.object-meta.xml
<CustomObject>
    <description>Lending Product Definition1</description>
    <label>Lending Product</label>
    <nameField>
        <label>Loan Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lending Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/loan__Loan_Product__c/fields/loan__Currency__c.field-meta.xml
<CustomField>
    <fullName>loan__Currency__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Currency</description>
    <inlineHelpText>Currency</inlineHelpText>
    <label>Currency</label>
    <referenceTo>loan__Currency__c</referenceTo>
    <relationshipName>Loan_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/loan__Loan_Product__c/fields/loan__Fee_Set__c.field-meta.xml
<CustomField>
    <fullName>loan__Fee_Set__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Fee Set</description>
    <inlineHelpText>Fee set contains the details of all the fees associated with the loan.</inlineHelpText>
    <label>Fee Set</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Selected Fee Set&apos;s category must be of type &apos;Loan&apos; and it should include at least one fee.</errorMessage>
        <filterItems>
            <field>loan__Fee_Set__c.loan__Fee_Set_Category__c</field>
            <operation>equals</operation>
            <value>Loan</value>
        </filterItems>
        <filterItems>
            <field>loan__Fee_Set__c.loan__Number_of_Fees__c</field>
            <operation>notEqual</operation>
            <value>0</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>loan__Fee_Set__c</referenceTo>
    <relationshipName>Loan_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/loan__Org_Parameters__c/loan__Org_Parameters__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Org Parameters</label>
</CustomObject>

force-app/main/default/objects/loan__Org_Parameters__c/fields/loan__Concurrent_BatchJobs__c.field-meta.xml
<CustomField>
    <fullName>loan__Concurrent_BatchJobs__c</fullName>
    <defaultValue>1</defaultValue>
    <description>Number of Batch job instances to be run in parallel</description>
    <inlineHelpText>Number of BatchJob instances to be run in parralel</inlineHelpText>
    <label>Concurrent Batch Jobs</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/loan__Org_Parameters__c/fields/loan__Draw_Amortization_Schedule__c.field-meta.xml
<CustomField>
    <fullName>loan__Draw_Amortization_Schedule__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If this is checked then at rescheduling amortization schedule will be drawn</inlineHelpText>
    <label>Draw Amortization Schedule</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/loan__Org_Parameters__c/fields/loan__Enable_New_Spread_Option__c.field-meta.xml
<CustomField>
    <fullName>loan__Enable_New_Spread_Option__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If this check box is checked then new spread will be enabled.</description>
    <label>Enable New Spread Option</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/loan__Org_Parameters__c/fields/loan__Rounding_Mode__c.field-meta.xml
<CustomField>
    <fullName>loan__Rounding_Mode__c</fullName>
    <defaultValue>&apos;NEAREST&apos;</defaultValue>
    <inlineHelpText>This specifies the rounding behavior for numerical operations capable of discarding precision. Each rounding mode indicates how the least significant returned digit of a rounded result is to be calculated.</inlineHelpText>
    <label>Rounding Mode</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/loan__Transaction_Approval_Config__c/loan__Transaction_Approval_Config__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Transaction Approval Config</label>
</CustomObject>

force-app/main/default/objects/loan__Transaction_Approval_Config__c/fields/loan__Payment__c.field-meta.xml
<CustomField>
    <fullName>loan__Payment__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If you do not check this, the payments will be cleared without running the relevant job</inlineHelpText>
    <label>Loan Payment</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/Testcustomlptclearingdagjob_1.cls
/* ****************Modification History******************
 *Created By       Pallavi          2021-04-15
 ******************Modification History******************/
@isTest
global class Testcustomlptclearingdagjob_1 implements loan.IQueryBuilder {
    String query;
    @testSetup
    static void createData() {
        loan.TestHelper.systemDate = Date.newInstance(2013, 03, 31);
        loan.TestHelper.createSeedDataForTesting();
        loan__Currency__c curr = loan.TestHelper.createCurrency();
        loan__MF_Account__c dummyAccount = loan.TestHelper.createMFAccount('XXXAccountForTest', '10000 - ASSETS');
        loan__MF_Account__c dummyIncAccount = loan.TestHelper.createMFAccount('XXXIncAccountForTest', '30000 - INCOME');

        //Create a Fee Set
        loan__Fee__c dummyFee = loan.TestHelper.createFee(curr,dummyIncAccount ,dummyAccount);
        loan__Fee_Set__c dummyFeeSet = loan.TestHelper.createFeeSet();
        loan__Fee_Junction__c dummyFeeJunction = loan.TestHelper.createFeeJunction(dummyFee,dummyFeeSet);

        loan__Office_Name__c dummyOffice = loan.TestHelper.createOffice();

        //Create a dummy Loan Product
        loan__Loan_Product__c dummyLP = loan.TestHelper.createLoanProduct(dummyOffice,
                                                               dummyAccount,
                                                               curr,
                                                               dummyFeeSet);

        loan__Loan_Purpose__c dummyLoanPurpose = loan.TestHelper.createLoanPurpose();

        loan__Client__c dummyClient = loan.TestHelper.createClient(dummyOffice);
        
        loan.TestHelper.createDayProcessForFullYear(loan.TestHelper.systemDate);

        //Create a dummy Loan Account
        loan__Loan_Account__c loanAccount = loan.TestHelper.createLoanAccount(dummyLP,
                                                                   dummyClient,
                                                                   dummyFeeSet,
                                                                   dummyLoanPurpose,
                                                                   dummyOffice);
        
        //Disburse the loan.
        loan.TestHelper.setupMultiplePaymentModeACH();
        //loan.TestHelper2.createFileGenMetaData();        
        loan__Org_Parameters__c orgParams = loan.CustomSettingsUtil.getOrgParameters();
        orgParams.loan__Enable_New_Spread_Option__c = true;
        orgParams.loan__Draw_Amortization_Schedule__c = true;
        orgParams.loan__Rounding_Mode__c = loan.LoanConstants.ROUNDING_MODE_NEAREST;
        orgParams.loan__Concurrent_BatchJobs__c = 8;
        update orgParams;
        loan__Transaction_Approval_Config__c txnApprovalParams = loan.CustomSettingsUtil.getApprovalConfig();
        txnApprovalParams.loan__Payment__c = true;
        upsert txnApprovalParams;
        loan__Payment_Mode__c cash = [SELECT Id
                                FROM loan__Payment_Mode__c
                                WHERE Name = 'ACH'
                               ];
        loan.TestHelper.setupMultiplePaymentModeACH();
        loan__ACH_Parameters__c achParams = loan.CustomSettingsUtil.getACHParameters();
        achParams.loan__Query_For_Loan_Payment_Clearing__c = 'Testcustomlptclearingdagjob_1';	
        achParams.loan__Multiple_Payment_Method_Support__c = true;
        upsert achParams;
                
        loan__Loan_Payment_Transaction__c pmt = new loan__Loan_Payment_Transaction__c();
        pmt.loan__Loan_Account__c = loanAccount.Id;
        pmt.loan__Transaction_Date__c = loan.TestHelper.systemDate;
        pmt.loan__Transaction_Amount__c =100;
        pmt.loan__Payment_Mode__c = cash.Id;
        pmt.loan__sent_to_ach__c = true;
        pmt.loan__sent_to_ach_on__c = Date.newInstance(2013, 03, 30);
        insert pmt;
    }
    @isTest
    static void testCustomDag() {
        
        Map<String, List<Object>> jobs = new Map<String, List<Object>>(); //All Jobs of the SOD will be recorded here
        Map<String, Set<String>> dependencyList = new Map<String, Set<String>>();// Dependency list of all the SOD jobs will be here
        clcommon.DynamicJobAPI2 apiHandle = clcommon.APIFactory.getDynamicJobAPI2();
        String dagName = 'Custom DAG';
        //String ns = CommonUtil.getMyNameSpace();
        /*if (ns != null && ns != '') {
            ns = ns + '.';
        }*/
        
        jobs.put('CustomLoanPaymentTxnClearingDynamicJob',
                new List<Object>{
                'CustomLoanPaymentTxnClearingDynamicJob',	//ns + 
                1,
                null,
                'Logging',
                200,
                false,
                false,
                false
                }
               );
        dependencyList.put('CustomLoanPaymentTxnClearingDynamicJob', new Set<String>());
        apiHandle.addDag(dagName, jobs, dependencyList);
        
        Test.StartTest();
        
        clcommon.DynamicJobAPI2 apiHandle2 = clcommon.APIFactory.getDynamicJobAPI2();
        apiHandle2.runOnce(dagName);
                               
        Test.StopTest();
    }
    @isTest
    static void testCustomDag1() {
        Test.StartTest();
        
        String query1 = 'select id, name, loan__cleared__c, loan__clearing_date__c, loan__loan_account__c, loan__payment_mode__r.name FROM loan__loan_payment_transaction__c WHERE loan__rejected__c = false and loan__cleared__c = false and loan__sent_to_ach__c = true';
        CustomLoanPaymentTxnClearingDynamicJob a = new CustomLoanPaymentTxnClearingDynamicJob(query1,1);
        
        Set<String> paymentModes = new Set<String>();
        CustomLoanPaymentTxnClearingDynamicJob b = new CustomLoanPaymentTxnClearingDynamicJob(loan.TestHelper.systemDate,paymentModes);
        b.getInstance();
        Test.StopTest();
    }    
    global String getQuery(){
        	query = 'select id, name, loan__cleared__c, loan__clearing_date__c, loan__loan_account__c, loan__payment_mode__r.name FROM loan__loan_payment_transaction__c WHERE loan__rejected__c = false and loan__cleared__c = false and loan__sent_to_ach__c = true';         
            System.Debug('LoanPaymentTxnClearingJob ***Custom Query2***' + query);
            return query;
   }    
}